### ISSUE TITLE
Playback fails, browsing works though

### ISSUE THREAD

**Issue by Sandbird** [CastagnaIT/plugin.video.netflix#1]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

I select a movie or episode to watch and the loading circle shows up but then nothing happens. It just stops, as if i never clicked on a movie.

### Steps to Reproduce

1. Uninstall any previous version of the addon
2. Install zip from this repo.

**Expected behavior:** [Play the movie]

**Actual behavior:** [The movie never starts]

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional information on the environment

The initial setup was done using this guide: https://discourse.osmc.tv/t/can-i-use-netflix-on-osmc-post-4/54741/4
I've been using the official Netflix addon until version .20. I read about this addon on a post there and thought to give it a try. I uninstalled the previous addon, installed this and rebooted.

## Debug log

https://pastebin.com/raw/Dk1m635Y

**Comment by CastagnaIT** [comment]
the log is not very clear, is incomplete and you have not enabled the kodi debug informations

**Comment by Sandbird** [comment]
hmm for some reason i get a lower version of pycryptodomex
```
#pip show pycryptodomex
Name: pycryptodomex
Version: 3.6.1

```
I'll try upgrading that to 3.7.0 and test again

**Comment by Sandbird** [comment]
Ok updated everything (now running latest 18.1 RC1 kodi - osmc) and 3.7.0 cryptodomex.
Still no playback. Latest Log:  https://pastebin.com/raw/pvxbCsuT

**Comment by Sandbird** [comment]
Case closed, it was a stupid DNS settings my router had..Once i restored my ISPs values, everything returned to normal...
So for someone else having the same problems .... if you see socket type errors....its your DNS
