### ISSUE TITLE
Trailers: Issue with TV Shows

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#100]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

Last master

### Description

Can't enter a show after displaying trailers
Can't display trailers after entered the tv show

### Steps to Reproduce

Case 1 : Trying to show trailers then seasons:
1. Select a TV Show (IE Black mirror)
2. Select 'Show trailers'
3a. Trailers are shown correctly, go back to list
 or
3b. Message pops up 'no trailers'
4. Try to enter season list -> No matter 3a or 3b, an error pops up 'VideoListSOrted' has no attribute 'season'

Case 2: Go into season list then move back to display trailers:
1. Select a TV Show
2. Enter the TV Show to display seasons list
3. Move back to list
4. Try to display trailers -> error pops up 'SeasonList' has no attribute 'video'

## Context (Environment)

Platform independent

## Debug log

https://paste.kodi.tv/urehidiqun.kodi

**Comment by CastagnaIT** [comment]
i suppose is a cache problem,
i did some tests but or it's occasional or now is solved,
please confirm, give a try

[plugin.video.netflix_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3267170/plugin.video.netflix_test1.zip)

**Comment by Smeulf** [comment]
Looks very good to me, I can't reproduce the issue with the test version.

Thanks!
