### ISSUE TITLE
Login with Authentication key still asks for password

### ISSUE THREAD

**Issue by tomdeblende** [CastagnaIT/plugin.video.netflix#1003]
#### Your Environment
- Netflix add-on version: 1.12.0
- Operating system version/name: LibreElec 9.2.6
- Device model:  Raspberry Pi 4B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

When using Login with Authentication key, I get asked for the key file, and the PIN. Afterwards I still get prompted for a password. If I enter the password, it says password do not match.

#### Expected behavior

Login using key file and PIN only.

#### Actual behavior

Prompted for password.

#### Steps to reproduce the behavior

1. Configure plugin.
2. Browse to key file and enter.
3. Enter PIN

### Debug log

The debug log can be found from this link:
http://paste.kodi.tv/lofizumoru

#### Installation
* [x] I'm using other Netflix Repo https://castagnait.github.io/repository.castagnait/
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
only one time the login ask the password
the account password is mandatory to input
if you do not type the right password you can not login with the Authentication key

**Comment by tomdeblende** [comment]
The problem is that I do enter the right password, but it says it's wrong.

**Comment by CastagnaIT** [comment]
I can do nothing this answer is given by the netflix website

**Comment by CastagnaIT** [comment]
you can try to change the password account and redo the auth key to see if will be accepted

**Comment by tomdeblende** [comment]
That somehow did the trick! Thanks Stefano.
