### ISSUE TITLE
Can more TCP links be added to speed up the transmission speed？

### ISSUE THREAD

**Issue by matthuo333** [CastagnaIT/plugin.video.netflix#1016]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [y ] change an existing feature

### Describe your request
Through the packet information, it is observed that for the same movie, TCP has two threads, as shown in the figure below：

![image](https://user-images.githubusercontent.com/55862904/103395878-508e0280-4b6b-11eb-813a-762500dc39f3.png)

Can more TCP links be added to speed up the transmission speed？

**Comment by CastagnaIT** [comment]
This add-on not manage streams, you have to write to dev mainteiners of InputStreamAdaptive
and as far as i know there is currently only a single thread per stream
