### ISSUE TITLE
No data received from browser message

### ISSUE THREAD

**Issue by bobblkabb** [CastagnaIT/plugin.video.netflix#1017]
#### Your Environment
- Netflix add-on version: 1.12.0
- Operating system version/name: LibreELEC 9.2.6
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
When I try to generate a key with the script, the script stops when I select my profile. I get the following message:

Browser startup... please wait
which: no google-chrome in (/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin)
which: no google-chrome-stable in (/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin)
which: no google-chrome-unstable in (/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin)
which: no chromium in (/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin)
Establish connection with the browser... please wait
Opening login webpage... please wait
Please login in to website now ...waiting for you to finish...
Verification of data in progress... please wait
File creation in progress... please wait
**No data received from browser**

The key is generated but no PIN is issued

#### Expected behavior
Output of key and PIN

#### Actual behavior
Breaks off with said message

#### Steps to reproduce the behavior

1. Extend script with falkon browser
2. Execute script, falkon starts
3. Log in
4. Select profile. It is loaded and briefly displayed. Netflix crashes and displays an error code: NSES-UHX

#### Other information
Using Falkon browser in openSUSE Tumbleweed.

-->

**Comment by CastagnaIT** [comment]
if you want you are free to develop the support for this browser
but i am not interested to investing time in this

before doing this you have to check that the netflix website works on Falkon in same way of Chrome browser, by compare html page, cookies and network flow, because the add-on works with data of Chrome type/structure only

**Comment by bobblkabb** [comment]
I thought it would work with Falkon as it is based on Chrome. Will see if I have access to a Chrome browser somewhere.

**Comment by bobblkabb** [comment]
Works with chromium!
