### ISSUE TITLE
Key generation error in NF AuthenticationKey program

### ISSUE THREAD

**Issue by BOX369** [CastagnaIT/plugin.video.netflix#1018]
#### Your Environment
- Netflix add-on version: not 
- Operating system version/name:  windows 10
- Device model:   Desktop computer Ryzen 2700 rx570 Processor 
- I am using an anti-virus program V3
Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

After running the program, I logged in from the Netflix web page, but nothing happened

#### Expected behavior

After running the program and closing all web pages, I ran the program.

#### Actual behavior

Two errors occur depending on the behavior

#### Steps to reproduce the behavior

1. Run the program
2. Access to incognito web page.
3. Netflix login 
4. Nothing happens.

#### Possible fix

Tried in various Windows system environments, but all errors are generated.

### Debug log
Debug log does not exist because it is not set to kodi

The debug log can be found here:

#### Other information

I am Korean and I have tried various methods to solve the problem and other users with the same environment and language have no problem

Has anyone had the same problem as me?

#### Screenshots

When I waited quietly after logging in

![Screenshot+2020-12-31+235147](https://user-images.githubusercontent.com/76808413/103416219-105d6d00-4bc9-11eb-8e4d-c6fcf1106abc.jpg)

When you stop the program

![주석+2020-12-31+233810](https://user-images.githubusercontent.com/76808413/103416270-3e42b180-4bc9-11eb-9886-f6f68231e851.jpg)

add photos

![주석+2020-12-31+173032](https://user-images.githubusercontent.com/76808413/103416946-1acd3600-4bcc-11eb-971d-abbef3d6db52.jpg)

**Comment by BOX369** [comment]
Eliminated rule errors

**Comment by CastagnaIT** [comment]
VPN topic is not allowed with this add-on
therefore all reports have to be done _without VPN_ or the Issue will be closed

i have prepared a zip:
[NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
make sure you extract all files before run the executable
and take a new screenshot of the error thanks

**Comment by BOX369** [comment]
![Capture](https://user-images.githubusercontent.com/76808413/103422979-896bbd00-4be7-11eb-99c0-5c0483765064.PNG)
This problem does nothing after logging in

**Comment by BOX369** [comment]
> 이 추가 기능에는 VPN 주제가 허용되지
> 않으므로 모든 보고서는 _VPN없이_ 수행해야합니다. 그렇지 않으면 문제가 종료됩니다.
> 
> zip을 준비했습니다 :
> [NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
> 실행 파일을 실행하기 전에 모든 파일의 압축을 [풀고](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
> 오류 감사의 새 스크린 샷을 찍습니다.
![Capture](https://user-images.githubusercontent.com/76808413/103423033-d0f24900-4be7-11eb-88ed-84bef78bfb65.PNG)

This problem does nothing after logging in

**Comment by BOX369** [comment]
> VPN topic is not allowed with this add-on
> therefore all reports have to be done _without VPN_ or the Issue will be closed
> 
> i have prepared a zip:
> [NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
> make sure you extract all files before run the executable
> and take a new screenshot of the error thanks

![103423081-1282f400-4be8-11eb-82c5-8bd45bdda52c](https://user-images.githubusercontent.com/76808413/103423185-a0f77580-4be8-11eb-8077-316eee800cb8.png)

**Comment by BOX369** [comment]
This problem does nothing after logging in
![103423081-1282f400-4be8-11eb-82c5-8bd45bdda52c](https://user-images.githubusercontent.com/76808413/103423196-b79dcc80-4be8-11eb-9e4c-3aedfa0124b7.png)

**Comment by BOX369** [comment]
> ## 버그 신고
> #### 당신의 환경
> * Netflix 애드온 버전 : 아님
> * 운영 체제 버전 / 이름 : Windows 10
> * 장치 모델 : 데스크탑 컴퓨터 Ryzen 2700 rx570 프로세서
> * 바이러스 백신 프로그램 V3 
>   사용 운영 체제를 사용하고 있습니다.
> 
> * [ ]  기계적 인조 인간
> * [ ]  iOS
> * [ ]  리눅스
> * [ ]  OSX
> * [ ]  라즈베리 파이
> * [x]  윈도우
> 
> ### 버그 설명
> 프로그램을 실행 한 후 Netflix 웹 페이지에서 로그인했는데 아무 일도 일어나지 않았습니다.
> 
> #### 예상되는 행동
> 프로그램을 실행하고 모든 웹 페이지를 닫은 후 프로그램을 실행했습니다.
> 
> #### 실제 행동
> 동작에 따라 두 가지 오류가 발생합니다.
> 
> #### 행동을 재현하는 단계
> 1. 프로그램 실행
> 2. 시크릿 웹 페이지에 액세스합니다.
> 3. Netflix 로그인
> 4. 아무 반응이 없습니다.
> 
> #### 가능한 수정
> 다양한 Windows 시스템 환경에서 시도했지만 모든 오류가 생성됩니다.
> 
> ### 디버그 로그
> kodi로 설정되지 않았기 때문에 디버그 로그가 존재하지 않습니다.
> 디버그 로그는 여기에서 찾을 수 있습니다.
> 
> ### 추가 컨텍스트 또는 스크린 샷 (해당하는 경우)
> #### 기타 정보
> 나는 한국인이고 문제를 해결하기 위해 다양한 방법을 시도해 보았고 같은 환경과 언어를 가진 다른 사용자는 문제가 없습니다
> 
> 누구든지 나와 같은 문제가 있습니까?
> 
> #### 스크린 샷
> 로그인 후 조용히 기다렸을 때
> 
> ![스크린 샷 + 2020-12-31 + 235147](https://user-images.githubusercontent.com/76808413/103416219-105d6d00-4bc9-11eb-8e4d-c6fcf1106abc.jpg)
> 
> 프로그램을 중지 할 때
> 
> ![주석 + 2020-12-31 + 233810](https://user-images.githubusercontent.com/76808413/103416270-3e42b180-4bc9-11eb-9886-f6f68231e851.jpg)
> 
> 사진 추가
> 
> ![주석 + 2020-12-31 + 173032](https://user-images.githubusercontent.com/76808413/103416946-1acd3600-4bcc-11eb-971d-abbef3d6db52.jpg)

**Comment by BOX369** [comment]
This problem does nothing after logging in
![Uploading 103423081-1282f400-4be8-11eb-82c5-8bd45bdda52c.png…]()

**Comment by BOX369** [comment]
> 이 추가 기능에는 VPN 주제가 허용되지
> 않으므로 모든 보고서는 _VPN없이_ 수행해야합니다. 그렇지 않으면 문제가 종료됩니다.
> 
> zip을 준비했습니다 :
> [NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
> 실행 파일을 실행하기 전에 모든 파일의 압축을 [풀고](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
> 오류 감사의 새 스크린 샷을 찍습니다.



> 이 추가 기능에는 VPN 주제가 허용되지
> 않으므로 모든 보고서는 _VPN없이_ 수행해야합니다. 그렇지 않으면 문제가 종료됩니다.
> 
> zip을 준비했습니다 :
> [NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
> 실행 파일을 실행하기 전에 모든 파일의 압축을 [풀고](https://github.com/CastagnaIT/plugin.video.netflix/files/5757664/NFAuthenticationKey.zip)
> 오류 감사의 새 스크린 샷을 찍습니다.



> 이 부가 기능 개발에 관심을 가져 주셔서 감사합니다.
> 이 메시지는 봇이 자동으로 생성 한 메시지입니다.
> 
> 우리가 제공하고 모든 버그 보고서에 필요한 템플릿을 완전히 따르지 않은 것 같습니다.
> 
> 디버그 로그 첨부는 버그 보고서에 필수이며 _로그 규칙은 이슈 생성 페이지 또는 ReadMe에 설명되어_ 있습니다.
> 
> [템플릿](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md) 을 따르도록 문제 메시지를 편집하십시오 . 문제는 귀하의 만족스러운 후속 조치없이 약 1 주일 후에 종료됩니다.
> 
> 잘못 전송되었다고 생각되는 경우 그렇게 말하면 팀원이 "무시 된 규칙"레이블을 제거합니다.

**Comment by BOX369** [comment]
This problem does nothing after logging in
![103423081-1282f400-4be8-11eb-82c5-8bd45bdda52c](https://user-images.githubusercontent.com/76808413/103423428-d51f6600-4be9-11eb-9340-122af511e38b.png)

**Comment by BOX369** [comment]
Could a keyboard security program cause this problem?

**Comment by CastagnaIT** [comment]
> keyboard security program

i do not know this software, you can try disable antivirus/antimalware softwares

seem that the NFAuthenticationKey software not receive the answer of your browser, or your browser not provide an answer

I would not know what to do for you,
what browser version are you using?

**Comment by CastagnaIT** [comment]
Il you have a old versio of browser update the browser, and try with this:
[NFAuthenticationKey_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5758774/NFAuthenticationKey_t1.zip)

**Comment by BOX369** [comment]
> 이전 

> 이전 버전의 브라우저가 있으면 브라우저를 업데이트하고 다음을 시도하십시오.
> [NFAuthenticationKey_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5758774/NFAuthenticationKey_t1.zip)

I'll try it right away and I'll reply

**Comment by BOX369** [comment]
> > 이전
> 
> > 이전 버전의 브라우저가 있으면 브라우저를 업데이트하고 다음을 시도하십시오.
> > [NFAuthenticationKey_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5758774/NFAuthenticationKey_t1.zip)
> 
> I'll try it right away and I'll reply

The program does not print any messages and is still waiting.

**Comment by CastagnaIT** [comment]
means that not receive the response from your browser

I don't know what kind of problem your system has
as far as i know, there is nothing else i can do

**Comment by BOX369** [comment]
> 브라우저에서 응답을받지 못함을 의미합니다.
> 
> 내가 아는 한 시스템에 어떤 종류의 문제가
> 있는지 모르겠습니다.

The version of chrome is 87.0.4280.88

**Comment by BOX369** [comment]
Message has been printed

You have exceeded the time avaliable for the loginRestart the operation

**Comment by BOX369** [comment]
> 브라우저에서 응답을받지 못함을 의미합니다.
> 
> 내가 아는 한 시스템에 어떤 종류의 문제가
> 있는지 모르겠습니다.

I also tried windows safe mode

**Comment by BOX369** [comment]
> > 브라우저에서 응답을받지 못함을 의미합니다.
> > 내가 아는 한 시스템에 어떤 종류의 문제가 
> > 있는지 모르겠습니다.
> 
> 나는 또한 Windows 안전 모드를 시도했습니다

Does this program work well for others without errors?

**Comment by CastagnaIT** [comment]
yes...

**Comment by BOX369** [comment]
I'll try it with Dirn Computer in the university's engineering lab.... If it doesn't work, I'll contact you again.

**Comment by BOX369** [comment]
> 예...

There was an error in the account that did not pay.

**Comment by CastagnaIT** [comment]
> There was an error in the account that did not pay.

can you reformulate your answer? i do not think i understand correctly

**Comment by BOX369** [comment]
> > 지불하지 않은 계정에 오류가 있습니다.
> 
> 당신의 대답을 재구성 할 수 있습니까? 나는 내가 정확하게 이해한다고 생각하지 않는다
The program does not cause errors only when your Netflix account is premium

**Comment by CastagnaIT** [comment]
this should not be related to the website,
when the software try to get the browser navigation history `Page.getNavigationHistory`
the browser DevTools protocol seem not answer or answer in different way

debugging browser is difficult, because i cannot determine what happen to you from my location
i need to try develop something to allow the software to write on a file what happen

**Comment by BOX369** [comment]
.

**Comment by BOX369** [comment]
Hmmmmmm I'm fortunate to have solved this problem

**Comment by BOX369** [comment]
I have solved various problems, tried playing on various devices and succeeded in playing.

**Comment by BOX369** [comment]
당신이 필요한 자료나 궁금한점 이 있다면 재공해 줄수 있습니다.

**Comment by BOX369** [comment]
If you have any data or questions you need, we can provide you with information.

**Comment by BOX369** [comment]
If you need other help, please feel free to comment.

**Comment by BOX369** [comment]
> 이것은 웹 사이트와 관련이 없어야
> 합니다. 소프트웨어가 브라우저 탐색 기록을 얻으려고 할 때 `Page.getNavigationHistory`
> 브라우저 DevTools 프로토콜이 다른 방식으로 응답하거나 응답하지 않는 것처럼 보입니다.
> 
> 내 위치에서 무슨 일이 일어나는지 알 수 없기 때문에 브라우저 디버깅이 어렵습니다
> . 소프트웨어가 파일에 무슨 일이 일어나는지 쓸 수 있도록 무언가를 개발해야합니다.

If there are no related questions, is it okay to close this issue?
