### ISSUE TITLE
Update Portuguese (Brazil) Language

### ISSUE THREAD

**Issue by MediaBrasil** [CastagnaIT/plugin.video.netflix#102]
*I'm submitting a ...*
  - [ ] bug report
  - [ x ] feature request
  - [ ] support request
Please Update Portuguese (Brazil) translation
Download the po file here:

https://files.xbmcbrasil.net/PluginsVideo/strings.po

Thanks

**Comment by CastagnaIT** [comment]
missing this:
msgctxt "#30154"
msgid "Netflix addon configuration"
msgstr ""

you can put the translation here that i add it

**Comment by MediaBrasil** [comment]
msgctxt "#30154"
msgid "Netflix addon configuration"
msgstr "Configuração do add-on do Netflix"

**Comment by CastagnaIT** [comment]
also 30085 is wrong
give me transation of this:

msgctxt "#30085"
msgid "Cache item time-to-live for metadata (days)"
msgstr ""

**Comment by MediaBrasil** [comment]
msgctxt "#30085"
msgid "Cache item time-to-live for metadata (days)"
msgstr "Tempo de vida dos metadados para itens em cache (dias)"

**Comment by CastagnaIT** [comment]
done
