### ISSUE TITLE
Thank you for your interest in this add-on development,

### ISSUE THREAD

**Issue by gozo97** [CastagnaIT/plugin.video.netflix#1021]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not full followed the template we provide and require for all bug reports.

Attach the debug log is mandatory for a bug report, _the log rules are explained in the Issue creation page or in the ReadMe_.

Please edit your Issue message to follow our [template](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md). The issue will be closed after about one week has passed without satisfactory follow-up from your side.

If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

_Originally posted by @github-actions[bot] in https://github.com/CastagnaIT/plugin.video.netflix/issues/1020#issuecomment-753490984_

**Comment by gozo97** [comment]
This does not apply to this situation as there is not a debug report.

**Comment by chris42** [comment]
You figure you are talking to a bot? You really should close this one and not spam the issues...

**Comment by gozo97** [comment]
I do not understand your comment. This is my first post on Github, and I apologise if I have gone about it the wrong way.  I rather expected some help.

**Comment by chris42** [comment]
This issue here does not make any sense to me. What is the question you have or the part you want help with?

**Comment by gozo97** [comment]
Thank you for the reply.  I think I was confused in how the posting works, and the edit I made is to #1020 which I hope explains the help I was asking for. Sorry.

**Comment by chris42** [comment]
Maybe to help a bit: Each issue on github is primarily on its own, hence should contain all information to allow others to understand what is happening. If you read this one from the view of someone unrelated to your problem, you might understand how confusing it is.
You can reference other issues, if you think they are related or to merge issues, if you find that they are duplicates. 

The template the bot is mentioning is primarily there, to ensure that new issues have complete information and the owner has searched for similar issues before opening a new one.
As most projects on github are done by people in their free time, you don't want to waste time on pulling information and figuring out what the writer means, but more work on the problem.

And don't worry, it is OK if you are new and make mistakes, just take the time to explain properly what you are looking for, or if you are unsure what to do...

P.S.: I think you can close this one
