### ISSUE TITLE
Change to menu navigation may have broken profile swapping

### ISSUE THREAD

**Issue by tniagcpm** [CastagnaIT/plugin.video.netflix#1027]
#### Your Environment
- Netflix add-on version: 1.12.1
- Operating system version/name: OSMC buster, rbp2-mediacenter-osmc 18.9.0-4
- Device model:  Raspberry-Pi 2

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

Going back ('..') from a user profile used to go up to the listing of all the profiles.
Now, it goes up to the Videos menu ['Files', 'Playlists', 'Video add-ons'].
Menu navigation changed sometime in November (?) 2020.

This navigation change may have affected profile swapping, as it no longer works for me.

After the navigation step described below, selecting another profile will _not_ swap profile.
So, in the listing for 'profile2', I see all 'profile1' data, instead of 'profile2' data.

Some investigation found that in resources/lib/navigation/directory.py home()
> common.WndHomeProps[common.WndHomeProps.CURRENT_DIRECTORY]

evaluates to 'home', which is _not_ in ['', 'root', 'profiles'], so the profile does not change.
Of course, adding 'home' to the list will make profile swapping work, but it's probably just a fragile hack...

#### Expected behavior

Displayed: List of Netflix account profiles
Selected:  'profile1'
Profile swapping works.

#### Actual behavior

Displayed: Videos menu ['Files', 'Playlists', 'Video add-ons']
Selected:  'Video add-ons'
Profile swapping does not work.

#### Steps to reproduce the behavior

Starting after a reboot...
Displayed: Top level kodi menu
Selected:  'Videos'
\> Enter
Displayed: Videos menu ['Files', 'Playlists', 'Video add-ons']
Selected: 'Files'
\> Down    'Playlists'
\> Down    'Video add-ons'
\> Enter
Displayed: List of Video addons
Selected:  '..'
\> Down     'Netflix'
\> Enter
Displayed: List of Netflix profiles
Selected:  '..'
\> Down     'profile1'
\> Enter
Displayed: Profile1 entries ['..', 'MyList', ...]
Selected:  '..'
\> Backspace

#### Possible fix

Possibly due to the PIN related changes done in mid-Oct ?

### Debug log

The debug log can be found here: [kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5774671/kodi.log)

Note: The log has some added debug lines with the message that starts with '_'.
They are added debug statements in resources/lib/navigation/directory.py home(), to see why profile swapping is not working.

**Comment by jakermx** [comment]
Please keep in mind that you are navigating from a Playlist...not  from the AddOn itselft, so, if in the mean time, NF, changes the way to  call or named profiles, it might affect the AddOn, even more, the saved stuff...

I.E. if your profiles before Oct were named by NF 1, 2 , 3, 4, and so...and ofter Oct they changed to one, two, three, four..an so.... and even worst....if the GUID were changed from something1, something2..... to someotherthing1, someotherthing2....and so....it would be so hard to make it work again, I wouldsuggest toclear cache and start over...and ask for a new feature that could find, match and update new IDs based on User, Profile, Title.....Name so...if NF wants to chinge it agang to somethingelmemore1...etc.. your Profile name will be the same, so try to find, match and update your exported stufff....agreed?

**Comment by CastagnaIT** [comment]
Yes the menu navigation is changed from some time, this due to some Kodi limitations and needed to fix others side effects

now when you are in the "List of Netflix profiles" and you select e.g. Profile 1,
and now you want to change in to the Profile 2, you have to scroll down and select "Profiles" menu entry,
then all profiles list will be displayed again.

If you choose ".." or backspace from the main menu of a Profile, or from the "List of Netflix profiles" page, will return to Kodi home so ['Files', 'Playlists', 'Video add-ons'] etc...

it is not a bug

**Comment by tniagcpm** [comment]
Thanks @CastagnaIT for the information (and for the add-on!).
The new (?) "Profiles" entry was missed, being right at the bottom of the list.
@jakermx  Yes - I remember NF have changed their API before and broken things.
