### ISSUE TITLE
NFAuthKey error

### ISSUE THREAD

**Issue by npmstart-pray** [CastagnaIT/plugin.video.netflix#1028]
![NFAuth-error](https://user-images.githubusercontent.com/18369734/103937579-edfeae80-50f6-11eb-8322-193982285b29.jpg)

what's happening incorrectly?  This ^ is with Default Chrome in the .py script, and when I alter it to point to Brave (which has dev tools), I get the same result.

How do we use Ctrl-Shift-I to troubleshoot what's not happening correctly with this script If it won't even open or "connect" with either of the browsers?

**Comment by jakermx** [comment]
if you have Chrome or Chromium....it will work, but if you dont have neither, and want to work with Brave...mod the script to call Brave and then grab the key from the path Brave uses....the script  invoques an incognito session so you should login again and generate the key file....the script is an external tool and as it says....it should be "used as it".....
I had login into NF addon from chorus...but I am running LibreElec on RPI...you might like to try it

**Comment by npmstart-pray** [comment]
I pointed the script at Brave. Got the same result as with Chrome. 

Does the script need to see the browser on the device that has the addon/Kodi installed for it to work, or can I just generate the Auth file and then move it to that device? Is that what you’re trying to tell me?  It’s not clear from the wiki
