### ISSUE TITLE
 problem with kodi 18.9 in addon version 1.12.1

### ISSUE THREAD

**Issue by Thicoxxi** [CastagnaIT/plugin.video.netflix#1033]
I have a raspberry pi 3 with libreelec installed in version 9.2.6 with kodi 18.9. With adaptive imputstream 2.4.6 and imputstream helper 0.5.2.

I installed the latest version of the addon, however I have had the following error. During the execution of the film or series the video freezes sometimes returns without audio or simply closes the addon returning to the home screen of the kodi.

**Comment by jakermx** [comment]
As RPi3 Has a little amount of RAM, you should set the MaxResolution to 720p and disable MMAL Player....as you did not provide your Log, setting these settings may solve your issues...

**Comment by Thicoxxi** [comment]
> As RPi3 Has a little amount of RAM, you should set the MaxResolution to 720p and disable MMAL Player....as you did not provide your Log, setting these settings may solve your issues...

Hi @jakermx.

I did it as a change; as you suggested and it looks like it solved the problem. follows my kodi's logi URL running on RPi3 with libreelec 9.2.6.
https://pastebin.ubuntu.com/p/xKD4tv9s4t/

**Comment by pkillnine** [comment]
> As RPi3 Has a little amount of RAM, you should set the MaxResolution to 720p and disable MMAL Player....as you did not provide your Log, setting these settings may solve your issues...

What is MMAL Player and how do I disable it?
