### ISSUE TITLE
no video only audio on fedora 33 x86_64

### ISSUE THREAD

**Issue by lfarkas** [CastagnaIT/plugin.video.netflix#1034]
After I upgrade my machine from fedora 31 (where netflix works properly) to fedora 33 which means from kodi 18 to kodi 19 netflix no longer works. 
more precisely login, every menu and film selection working after i start to play any film i hear the voice but no video (not even the control panel) but the subtitle working (but i can't change the language since i can't seem the control. most of the time the tv show the last page from where i select the film. sometimes some garbage shown like a badly decoded jpeg of h264. sometimes even something moves ie these garbage image changes. it seem like bas video decoder choozen or ...
there is not any error message in the  .kodi/temp/kodi.log
and then after a few minutes even the kodi crash.

this is my current package list:

plugin.video.netflix-1.13.0+matrix.1
kernel-core-5.10.6-200.fc33.x86_64
kodi-19.0-0.8.20201207git8cc9e80.fc33.x86_64
kodi-eventclients-19.0-0.8.20201207git8cc9e80.fc33.x86_64
kodi-inputstream-adaptive-2.6.6-1.fc33.x86_64

**Comment by jakermx** [comment]
Please share your log file....no matter there are no error on it....a codec mismatch is not an Error, so we are blind to support you

**Comment by CastagnaIT** [comment]
if you have upgraded to Kodi 19 instead of install Kodi from scratch, suggest to do a clean Kodi install

this addon not handle video/audio only execute "play" command
for audio/video problems you have to ask to Kodi community

**Comment by lfarkas** [comment]
we tested on 4 different fedora 33 machine (3 of these never runs kodi). and none of these working.

**Comment by lfarkas** [comment]
> Please share your log file....no matter there are no error on it....a codec mismatch is not an Error, so we are blind to support you

here is the log:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5821597/kodi.log)

**Comment by jakermx** [comment]
no playback calls on those log...

**Comment by lfarkas** [comment]
sorry. the reason since after a few minutes of netflix "play" usually kodi crash (this doesn't happened with kodi 18 + netflix) and in this case a new log file created.

here is a log after a play: 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5822906/kodi.log)

would you reopen this issue?

**Comment by jakermx** [comment]
2021-01-15 22:07:14.060 T:17876   ERROR <general>: libva error: /usr/lib64/dri/iHD_drv_video.so init failed

this is the reasson....

**Comment by lfarkas** [comment]
that was not the problem. anyway i'm just remove the media rpm and got this log (same problem has audio no video):
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5831735/kodi.log)
