### ISSUE TITLE
NFAuth script error

### ISSUE THREAD

**Issue by npmstart-pray** [CastagnaIT/plugin.video.netflix#1035]
#### Your Environment
- Netflix add-on version: <1.12.1>
- Operating system version/name: <xbian current k5.4.85 -->
- Device model:  <RasPi4 4GB-->

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

my lubuntu desktop will not recognize chrome or brave to run the NFAuth python script.
both are current and have web dev tools installed
 
#### Expected behavior

an Auth code (file?) to login to netflix via this addon

#### Actual behavior

python script fails...no code/file is produced...angry people in my house...

#### Steps to reproduce the behavior

1 Follow directions in the wiki.
2.try again, on a windows machine
3.come here for help

#### Possible fix

on the windows machine, the script tried to open chrome in incognito.
and for brave/chrome on my lubuntu desktop, is it because brave has widevine installed?
Is it possible I can maybe login with the old way if I change to v1.13 of the addon, assuming my port of kodi is close enough to v19 in xbian?  I haven't tried that yet, but I can only assume that since the dev of xbian-kodi is still calling it v18.9, it's not quite the full v19 release, so it may or may not work
### Debug log

The debug log can be found here:

I will attach a log file in the morning

#### Screenshots

see screenshot in issue 1028
![NFAuth-error](https://user-images.githubusercontent.com/18369734/104687552-70760800-56cd-11eb-9093-4d5e4ac77f71.jpg)

**Comment by CastagnaIT** [comment]
have you edited the script?
when you run the script the browser will be opened or not?

**Comment by npmstart-pray** [comment]
I tried with Brave first, after editing the script to point to it, then I reverted back and tried with chrome. Same error both times. And it didn’t work with Chrome on windows 10 either.   
I’ll get a log file up for you later...

**Comment by CastagnaIT** [comment]
Well
i have installed Lubuntu 20.04 + python 3, after
i have installed Chrome by downloading package from Chrome website
then i have run the script, without edit it, after opened Chrome has generated the key file without problems

after this,
i have tried to install Brave browser as website instructions,
i have add the browser path in the script file `/usr/bin/brave-browser`
and have generated the key file without problems also with Brave

you have some type of problem in your Lubuntu
or you still doing something wrong

**Comment by npmstart-pray** [comment]
That’s...above and beyond my expectations...and some bad news. Lol. 
Would you mind sharing what host machine you’ve done this on, spec-wise?  My desktop is Intel Atom - based, which might be a significant part of the problem. 
But that doesn’t explain why it failed on a win10 laptop as well.

**Comment by CastagnaIT** [comment]
mmh sound strange that is architecture depends...
the machine have AMD cpu

on Windows is another different story, need to know/see what happen but is difficult debug because is not like a script

**Comment by CastagnaIT** [comment]
what do you plan to do with this Issue thread?
do you want continue or close it?
