### ISSUE TITLE
Addon crashes on version 1.12.1 in kodi 18.9 (libreelec 9.2.6)

### ISSUE THREAD

**Issue by Thicoxxi** [CastagnaIT/plugin.video.netflix#1039]
Hi
I was running the netflix addon version 1.12.1 on my raspberry pi3 with libreelec 9.2.6. With 720p resolution as was suggested in another issue that I opened here but the addon continues to crash in the video playback. Below is a link to the error log that was generated for analysis.
https://pastebin.ubuntu.com/p/wrmGccQRmZ/
Thanks.

**Comment by CastagnaIT** [comment]
i have no idea whats wrong in your system/device there are different errors
which appear to be related to network problems
we only deal with add-on bugs here, ask in the community forums
