### ISSUE TITLE
Some lists have missing titles, seasons or episodes

### ISSUE THREAD

**Issue by v1ru555** [CastagnaIT/plugin.video.netflix#1044]
#### Your Environment
- Netflix add-on version: 1.6.0
- Operating system version/name: LibreElec 9.2.6
- Device model:  Raspberry Pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

A lot of titles are missing from the add-on library

#### Expected behavior

All shows should be present in the add-on as that of the browser version

#### Actual behavior

Not all shows are present for example (But not th eonly missing title)the Anime library, only 16 are present on the add-on, yet 114 present on the browser.

#### Steps to reproduce the behavior

1. Navigate to TV show genres
2. Select Anime
3. Only 16 are present

### Debug log

The debug log can be found here:
https://paste.kodi.tv/edarapeden

**Comment by hbbernardo** [comment]
I can confirm this issue 

Various folders are showing missing titles or not showing titles at all

**Comment by CastagnaIT** [comment]
the add-on have no control over the data sent by the website,
may be due to a temporary malfunctioning of the website
you can try do clear cache memory/disc from expert settings

wrong results can be happen also if:
-you use VPN/Proxies, are not supported by addon
-you use profiles with different languages

**Comment by v1ru555** [comment]
> the add-on have no control over the data sent by the website,
> may be due to a temporary malfunctioning of the website
> you can try do clear cache memory/disc from expert settings
> 
> wrong results can be happen also if:
> -you use VPN/Proxies, are not supported by addon
> -you use profiles with different languages

English is the default I use.

I understand you dont support VPN and **not asking for support on it**, but I did try it with and without vpn (I know which shows should and shouldn't be present when VPN is on or off.) yet this didn't effect the anime list. I shall completely remove the vpn add-on and retry the clear cache under yours.

**Comment by v1ru555** [comment]
So uninstalling the VPN addon(vpn manager for openVPN) 'fixed' the issue, I guess I am stuck with the content my country has while using my media box.

**Comment by hbbernardo** [comment]
I'm using the latest Matrix Version on the very latest build of Libreelec.

I've have cleaned the cache/disk on the expert settings.

This issue persists.

This is a new install of Libreelec.

I have the latest Leia addon running on OSMC (Vero 4K) and it doesn't seem to be affected with a possible Network problem. 

Ir seems to be affecting only the Matrix addon.

**Comment by hbbernardo** [comment]
Have a look on this log

http://ix.io/2Nf1
