### ISSUE TITLE
Ordering the list of contents

### ISSUE THREAD

**Issue by luizoti** [CastagnaIT/plugin.video.netflix#1047]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

#### Describe the use case

fix season order
#### Describe an alternative

no solution by me

#### Specific details

Good evening,

This is not a problem in itself, but a doubt.

How does the ordering of items in the list work?

Example: if I open a show, with 5 seasons, are you the one who explicitly defines an order of the seasons in the list?

I ask this question because when I use jsonrpc to capture the contents of a directory, on netflix the order is correct, as it appears on kodi, but on amazon, the items come in order, the impression is that in one there is an explicit definition of the order and not on the other.

I don't want to take up too much devs time, but I was left with this doubt, if you can even clarify me, I would be grateful.

**Comment by CastagnaIT** [comment]
this is the behaviour and will not be changed:
for some lists you can change the order from addon "main menu items" settings
for episodes you can change the order by using kodi sidebar
for the seasons the order is definited by netflix website can not be changed

This addon was not designed for use with jsonrpc calls, so if you have problems they will not be accepted

**Comment by luizoti** [comment]
Jsonrpc only serves to list the directories, the point is that the seasons are reversed in the list, the question is whether it is possible to impose that the first season appears at the top and the last at the end.

If that's not possible, okay, patience.

**Comment by CastagnaIT** [comment]
> Jsonrpc only serves to list the directories

for you result only in list of items, but for the addon frontend/service management is another story
and in some situations these calls can cause wrong unexpected behaviours

I have already given the answer above,
no change will be done for jsonrpc calls

**Comment by luizoti** [comment]
I posed the question as how to featere request just because there is a template, I decided to follow.

I don't know if I was clear, but I don't want you to implement anything related to jsonrpc, I just asked if the ordering can be imposed (consequently can it reflect on jsonrpc? Maybe, who knows)  Thanks for listening.

**Comment by CastagnaIT** [comment]
yes i understand,
you should ask for jsonrpc options in the Kodi forum or try read the jsonrpc documentation
but here we only deal with bug requests or feature requests

**Comment by luizoti** [comment]
With all due respect, I said clearly that the question was not about how jsonrpc works so if you ask me to go and ask questions about it in the forum you don't understand.

But ok, the issue is closed.

Thx for attention.
