### ISSUE TITLE
Add posters to seasons

### ISSUE THREAD

**Issue by Paco8** [CastagnaIT/plugin.video.netflix#1048]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request

Currently the seasons don't display any image, as you can see in this screenshot:
https://imgur.com/a/3gFlaaP

This is a problem if I add some seasons of different shows to the favourite section, it's difficult to know which show is which, as you can see here: 
https://imgur.com/a/wYUFjJs

#### Describe an alternative

My suggestion is to add a poster or image for each season. If netflix doesn't provide any, you can use the show's poster.

**Comment by CastagnaIT** [comment]
i was thinking the same thing time ago
but there are no images on seasons query will try to get the tvshow images
of course this change if possible, i remember you that will be done for Kodi 19 only

**Comment by CastagnaIT** [comment]
fyi after the upgrade with the new version,
is possible that you have to remove and readd seasons to favourites in order to get the images
