### ISSUE TITLE
Titles not being listed

### ISSUE THREAD

**Issue by hbbernardo** [CastagnaIT/plugin.video.netflix#1053]
![IMG_20210125_182648545](https://user-images.githubusercontent.com/24485236/105768408-1aaa2700-5f3b-11eb-8a8a-d42f290921e2.jpg)
![IMG_20210125_182703266](https://user-images.githubusercontent.com/24485236/105768438-272e7f80-5f3b-11eb-8a55-7d55c604a9da.jpg)

#### Your Environment
- Netflix add-on version: 1.13+matrix.1
- Operating system version/name: LibreElec Matrix Daily Build, etc... -->
- Device model:  Rpi3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When I try to enter a folder using the newest matrix addon many titles are missing. To give you an idea. The most popular section, only shows one folder/title. And there isn't anything inside of it.

THIS IS ONLY HAPPENING WITH the Matrix addon. I have in the same network another device (Vero 4K) running OSMC with Kodi 18 and the Leia addon isn't showing this behavior

#### Expected behavior

The expected behavior would be listing the titles within a given folder/sub-folder

#### Steps to reproduce the behavior

1. Install today's build from Libreelec Matrix from https://test.libreelec.tv/ on Raspberry Pi.
2. Install the Matrix netflix addon and its dependencies
3. Log in to Netflix and try to browse the folders

### Debug log

The debug log can be found here:

http://ix.io/2Nf1

**Comment by CastagnaIT** [comment]
![image](https://user-images.githubusercontent.com/3257156/105869089-2824e700-5ff7-11eb-8495-4ef83f095c8c.png)
you have filtered the seasons to _Watched_ content... disable the filters from Kodi sidebar

**Comment by hbbernardo** [comment]
Indeed. I have no idea how this got changed. 
And why some titles were appearing and others didn't. 

I suspect that this Libreelec nightly somehow changed itself.

I want to chime-in something else. I'm pretty sure That there are a lot more HD titles being offered and being played on my Rpi3.

What has changed? 1080p is almost playable as well.

Please let me know.

**Comment by CastagnaIT** [comment]
I suggest you to look at Wiki: "Some lists have missing titles, seasons or episodes": https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#some-lists-have-missing-titles-seasons-or-episodes
there is no other way

For HD resolutions suggest you to read the "Reference table of high resolutions" in the Github Readme
HD resolutions on linux environments are not always available
here you cannot make any changes or fixes, you can only contact and complain to the Netflix company about these limitations
