### ISSUE TITLE
S10 Plus Does not work L1 

### ISSUE THREAD

**Issue by edersonmax21** [CastagnaIT/plugin.video.netflix#1054]
#### Your Environment
- Netflix add-on version: <v1.12.2-Leia>
- Operating system version/name: <Android 10>
- Device model:  S10 Plus- SM-G975F

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

L1 widevine does not work, My phone accepts netflix in full hd and this addon does not work HD 

#### Expected behavior
<Operate at the L1 widevine level>

#### Actual behavior
<Does not work on L1 only on L3>

#### Steps to reproduce the behavior

1.  I open the video and this message appears 
Link : https://drive.google.com/file/d/1Aton4LFinzeqc0YqIQyC8MI-Vyuz3HyN/view?usp=drivesdk

#### Possible fix
<Stay on widevine L1>

### Debug log
 https://drive.google.com/file/d/1Aw82pu2NtMjQdfblR_GPHTWEMEUTcl-d/view?usp=drivesdk

**Comment by edersonmax21** [comment]
> ## Bug report
> #### Your Environment
> * Netflix add-on version: <v1.12.2-Leia>
> * Operating system version/name: <Android 10>
> * Device model: S10 Plus - SM-G975F
> 
> Used Operating system:
> 
> * [x]  Android
> * [ ]  iOS
> * [ ]  Linux
> * [ ]  OSX
> * [ ]  Raspberry-Pi
> * [ ]  Windows
> 
> ### Describe the bug
> L1 widevine does not work, My phone accepts netflix in full hd and this addon does not work HD
> 
> #### Expected behavior
> #### Actual behavior
> #### Steps to reproduce the behavior
> 1. I open the video and this message appears
>    Link : https://drive.google.com/file/d/1Aton4LFinzeqc0YqIQyC8MI-Vyuz3HyN/view?usp=drivesdk
> 
> #### Possible fix
> ### Debug log

**Comment by CastagnaIT** [comment]
Apply wiki instructions:
Video Stream only at 540P (SD) on Android device https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#video-stream-only-at-540p-sd-on-android-device

**Comment by edersonmax21** [comment]
Thanks for responding, I just needed to change the ESN as you said, thanks.
