### ISSUE TITLE
HDR Support Raspberry pi 4 Kodi 19

### ISSUE THREAD

**Issue by rjousse18** [CastagnaIT/plugin.video.netflix#1056]
## Feature request
I'm submitting a proposal to ...
  - [x ] new feature
  - [ ] change an existing feature

### Describe your request
if i understood correctly, the HDR will be better supported on kodi 19.
So can we expect Netflix HDR support on raspberry pi 4?

**Comment by CastagnaIT** [comment]
currently HDR on netflix is available only with HEVC codec
the HEVC codec is not available on Widevine for linux
then will not be possible to have HDR on linux

**Comment by rjousse18** [comment]
the hdr will be available in av1 on netflix no? i read that netflix will switch to av1 in the future and kodi 19 will play this codec no ?

**Comment by CastagnaIT** [comment]
I am not aware of HDR profiles on AV1 codecs
and there are 2 problems:
netflix AV1 streams uses CBCS encryption and i do not see this encryption supported by InputStreamAdaptive add-on
i have never seen the AV1 codec played in browsers on which we rely

**Comment by rjousse18** [comment]
It's a new codec and netflix begin to use it on Android for now and later everywhere, I was just wondering if you knew if it will be possible to have it on this add-on in the future :/

**Comment by CastagnaIT** [comment]
all would be possible...
this add-on use InputStreamAdaptive add-on to allow Kodi to handle the streaming content,
but there is lack of developers for this important add-on component that is used by all VOD add-ons
and the development of that component is currently quite stalled

therefore will not be possible to think to try add or test this new codec,
and in the future i have no idea...

**Comment by rjousse18** [comment]
Ok thanks !
