### ISSUE TITLE
Plugin makes Kodi crash during start-up

### ISSUE THREAD

**Issue by szotsaki** [CastagnaIT/plugin.video.netflix#1057]
#### Your Environment
- Netflix add-on version: 1.12.2
- Operating system version/name: openSUSE x64, Kodi 18.9.0

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
As soon as I installed the plugin from the repository according to the readme Kodi crashed. Now, if I start Kodi, two seconds later it crashes.

Kodi was not used on this computer before (so it's a fresh install) and this is the only plugin I installed.

#### Expected behavior
Kodi doesn't crash.

#### Actual behavior
Kodi crashes.

### Debug log
I started Kodi with `--debug` and changed the default log level in the plugin XML because it's not possible start the application.

The debug log can be found here: [kodi_crashlog-20210129_174021.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5895063/kodi_crashlog-20210129_174021.log)

The last lines of the log are:
```
INFO: [plugin.video.netflix (0)] The debug logging level is set as "Verbose"
DEBUG: [plugin.video.netflix (0)] Trying connection to the database nf_local.sqlite3
DEBUG: [plugin.video.netflix (0)] Database connection nf_local.sqlite3 was successful (SQLite ver. 3.34.0)
DEBUG: [plugin.video.netflix (0)] Trying connection to the database nf_shared.sqlite3
DEBUG: [plugin.video.netflix (0)] Database connection nf_shared.sqlite3 was successful (SQLite ver. 3.34.0)
```

### Additional context or screenshots (if appropriate)
I checked the database files (nf_*.sqlite3) but they are have good integrity and all are empty besides `nf_local.sqlite3` which has the following data:

1 | clean_cache_last_start | 2021-01-28 22:03:45.928994
2 | local_db_version | 0.2
3 | shared_db_version | 0.2
4 | service_previous_version | 1.12.2

If I remove the directory `plugin.video.netflix` from `~/.kodi/addons`, Kodi starts up successfully.

**Comment by szotsaki** [comment]
> If you believe it was sent in error, please say so.
I think I used the template correctly. What kind of information is missing?

**Comment by CastagnaIT** [comment]
This is a low level error that can not be handled from this addon

but Kodi 18 is end of life, then no more fixes you can
try ask to Kodi devs if they are able to give some more info
or try install Kodi 19 if available, and if same error occurs report it to Kodi
