### ISSUE TITLE
Some Netflix profiles throw a 500 error when searching videos

### ISSUE THREAD

**Issue by daveseff** [CastagnaIT/plugin.video.netflix#1060]
#### Your Environment
- Netflix add-on version: 1.12.2
- Operating system version/name:  LibreElec 9.2.6
- Device model:  Raspberry Pi4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
My main Netflix profile works just fine, but when my wife searches for her shows using her profile, the addon throws an HTTP 500 api error.

#### Expected behavior
The list of search results should appear. 

#### Actual behavior
500 Internal server error

#### Steps to reproduce the behavior
1.  Star the netflix addon
2.  Choose a secondary profile
3.  Use the search function
4. enter a search term
5. Sit in disappointment as you get the error.

### Debug log

[Debug Log](https://paste.kodi.tv/liqovugedo.kodi)

**Comment by CastagnaIT** [comment]
your log is without debug info,
please follow instruction steps from the Readme and post a new log

**Comment by CastagnaIT** [comment]
if no log will be provided this issue will be closed on next days
