### ISSUE TITLE
Error Contents: 'NoneType' object is not callable on addon launch

### ISSUE THREAD

**Issue by 7opf** [CastagnaIT/plugin.video.netflix#1061]
**Original issue for posterity:**

Currently get [the following stack](https://paste.kodi.tv/tifejawoti.kodi) trace logged to console immediately after starting the netflix addon (`1.13.1+matrix.1`)

The addon worked a couple days ago and then today after changing Kodi's skin to [this one](https://codeload.github.com/beatmasterRS/skin.arctic.zephyr.mod/zip/master) it didn't work, but changing back to Estuary didn't solve the problem. 

Reboot didn't seem to help. I also tried resetting cache through netflix add on configuration. Any pointers?

**UPDATE with template:**

#### Your Environment
- Netflix add-on version: 1.13.1+matrix.1
- Operating system version/name:  Ubuntu 20.04, Kodi 19.0-RC1

Used Operating system:
* [x] Linux

### Describe the bug

Netflix add on crashes immediately if RCB has been installed and opened once. Stack trace shows Netflix add-on attempting to execute python file belonging to RCB lib

#### Expected behavior

Netflix add-on should co-exist with RCB addon

#### Actual behavior

Netflix add-on crashes on start after RCB has been opened once

#### Steps to reproduce the behavior

1. Install Netflix add-on through repo 
2. Install rom collection browser with [zip file(s)](https://forum.kodi.tv/showthread.php?tid=70115&pid=2937200#pid2937200)
3. Open netflix -> works
4. Open RCB -> works
5. Open netflix -> error
6. Open RCB -> works

### Debug log
https://paste.kodi.tv/tifejawoti.kodi

**Comment by 7opf** [comment]
The stack trace is leads to some RCB files - maybe an issue with RCB. All seems to work fine when uninstalling RCB and rebooting.

**Comment by 7opf** [comment]
@CastagnaIT - Actually, I think it may be an issue with this plugin. Do you do any dynamic importing based on filename/paths? As you can see in stack trace above, the execution jumps from
`/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py` to `/home/kodi/.kodi/addons/script.games.rom.collection.browser/resources/lib/gamedatabase.py` which have similar folder structure.

**Comment by CastagnaIT** [comment]
the sqlite implementation in this add-on is standard do nothing of particular
but from what i see your "game collection" register an adapter `sqlite.register_adapter` to the standard str (strings) objects
and for some reason affect other add-ons

in my opinion "game collection" do a wrong python2/3 sqlite implementation, is a wrong thing apply an adapter to str object, means that somewhere his code has other problems to be solved

**Comment by 7opf** [comment]
Looks like you're right, I uncommented this line in their archive, reinstalled and both addons now run happily. Thanks for the pointer, I've submitted a PR with them.
