### ISSUE TITLE
Black screen *with* audio, playback otherwise normal

### ISSUE THREAD

**Issue by jeanlucthumm** [CastagnaIT/plugin.video.netflix#1063]
#### Your Environment
- Netflix add-on version: 1.12.2
- Operating system version/name:
  Operating System: Arch Linux ARM
            Kernel: Linux 5.10.13-3-ARCH
      Architecture: arm
- Device model:  RPI 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
On play back of any title, I get black screen but functional audio

#### Expected behavior
Video should play with image and audio

#### Actual behavior
Video shows no image but does show audio and playback continue normally otherwise

#### Possible fix

I've read that people have a ton of issues with DRM and Widevine on RPI, perhaps it is related in some way? Although I tried testing if Widevine works as per [this guide](https://www.matthuisman.nz/2018/05/kodi-widevine-support.html), and the tester addon reported everything was working correctly. 

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5936376/kodi.log)

#### Other information
The plugin went through Widevine install when I first tried to play a title, but it eventually failed because my system did not have the `nss` package installed and the installer complained about missing `.so` files. I then installed the `nss` package, relaunched kodi, started the netflix app and tried to play a title. This time it did not complain about Widevine but I'm consistently getting black screens.

**Comment by CastagnaIT** [comment]
on the log there are a log of weird graphics render message
are not things that can be solved from this add-on
try ask on RPI community or Kodi community
