### ISSUE TITLE
jsonrpc error

### ISSUE THREAD

**Issue by rafhtl** [CastagnaIT/plugin.video.netflix#1068]
#### Your Environment
- Netflix add-on version: 
1.12.2

Used Operating system:

* [x] Raspberry-Pi
kodi 19.1

### Describe the bug
 File "/home/xbian/.kodi/addons/plugin.video.netflix/resources/lib/common/kodi_ops.py", line 52, in json_rpc
                                                       response['error']['message']))
                                                   OSError: JSONRPC-Error -32602: Invalid params.

Hi I just installed and this is the error I get when trying to play
thank you

[log.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/5978183/log.txt)

**Comment by jakermx** [comment]
please provide the full log

**Comment by rafhtl** [comment]
I found out what the problem was
in my advancedsettings.xml I had wrong settings
thank you
