### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'split'

### ISSUE THREAD

**Issue by sjuk** [CastagnaIT/plugin.video.netflix#1076]
#### Your Environment
- Netflix add-on version: 1.13.1+matrix.1
- Operating system version/name: Ubuntu 20.04.2 LTS (Focal Fossa)
- Device model: Desktop x86_64

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Video streams don't play any more.

#### Expected behavior

Video streams play.

#### Actual behavior

AttributeError: 'dict' object has no attribute 'split'

#### Steps to reproduce the behavior

1. Enter Netflix add-on
2. Enter my list
3. Start any stream

#### Possible fix

Downgrade to Netflix add-on version: 1.13.0+matrix.1
[https://forum.kodi.tv/showthread.php?tid=329767&pid=3010253&highlight=AttributeError%3A+%27dict%27+object+has+no+attribute+%27split%27#pid3010253](https://forum.kodi.tv/showthread.php?tid=329767&pid=3010253&highlight=AttributeError%3A+%27dict%27+object+has+no+attribute+%27split%27#pid3010253)

### Debug log

The debug log can be found here: [https://paste.kodi.tv/sunatezaga.kodi](https://paste.kodi.tv/sunatezaga.kodi)

#### Other information

Kodi upgraded from version 18 to 19.
Before upgrade Netflix add-on worked fine.
After Kodi upgrade Netflix add-on was disabled.
I uninstalled the Lea repository and installed Matrix repository from Readme.
Uninstall and Install of add-on did not help to make streams play.

#### Screenshots

![screenshot00000](https://user-images.githubusercontent.com/5033784/108611900-16a6e300-73db-11eb-8eaf-3522e1790e89.png)

**Comment by CastagnaIT** [comment]
will be fixed on next release
