### ISSUE TITLE
Kodi 19 Matrix - addons including ur Netflix not running and or installing.

### ISSUE THREAD

**Issue by canice86** [CastagnaIT/plugin.video.netflix#1080]
#### Your Environment

- Device model:  Samsung Galaxy S20 Ultra 

Used Operating system:
* [11 ] Android

### Describe the bug

- Netflix add-on version:  any external 3rd party addon not working. And or cannot be installed 

The screenshots below refers to your Netflix plugin for Kodi 19 condition not satisfied 

Kodi update to kodi 19 has introduced alot of security for 3rd party addons asking authors or origin to certify safety and or guidelines. According to the public python 2 is no longer supported.  Python 3 is required by Kodi 19.

I tried another addon the error message threw up "python 2 could not be satisfied." (Means addon called called for python 2 that's nows disabled by kodi 19

Even input stream is no longer supported but this file could be python 2 written. 

No auto update of .zip files
Kodi 19 brought in auto update. 

#### Expected behavior
Addon installed

#### Actual behavior-
Failed to install Addon from zip file
The dependency on script.module.addon.signals version 0.0.6+matrix.1 could not be satisfied. 

#### Steps to reproduce the behavior
1. Install any third party addon on kodi 19 ie..addons install from .zip

#### Possible fix
Replace python 2 file for python 3 as per guidelines from kodi forum. As python version 2 is no longer supported on kodi 19 - matrix

For auto update the install of .zip files need installation from other means.

### Screenshots 
![VideoCapture_20210221-153903](https://user-images.githubusercontent.com/69091508/108630284-e05d7800-745b-11eb-9db8-26f1585d99a9.jpg)
![VideoCapture_20210221-153923](https://user-images.githubusercontent.com/69091508/108630288-e0f60e80-745b-11eb-8fb8-afc4995e8bf7.jpg)
![VideoCapture_20210221-153935](https://user-images.githubusercontent.com/69091508/108630289-e0f60e80-745b-11eb-8f94-b528cdf6be22.jpg)
![VideoCapture_20210221-153959](https://user-images.githubusercontent.com/69091508/108630291-e18ea500-745b-11eb-994a-bf78f0e66b13.jpg)
![Screenshot_20210221-150236_Kodi](https://user-images.githubusercontent.com/69091508/108630313-f23f1b00-745b-11eb-8e57-a03cdbd045bf.jpg)

**Comment by canice86** [comment]
I cannot provide kodi.log file because I'm using Android 11 which restricts access. You have. Access on Android 10 or lower.

**Comment by CastagnaIT** [comment]
Upgrades directly from Kodi 18 to Kodi 19 can lead to unexpected problems due to python migration
i can only suggest you to uninstall Kodi & all Kodi data,
and after install netflix addon from repository for Kodi 19 Matrix zip link on readme

**Comment by canice86** [comment]
I now tested your Netflix Kodi 19 in Kodi 19 on my Nvidia Shield  - Android Tv . It should be advised that your Netflix add-on is targeted for Android Tv operating systems as it didn't encounter the errors found on non- Android Tv devices.. note your Netflix addon requires the native Widevine that comes with Android Tv, I didn't try Widevine in your Netflix add-on settings. I left disabled.
Widevine enables DRM protected content to play on authorised devices but its really aimed at Android Tv OS devices such as Nvidia Shield, Sony Tvs and other android tvs... I would strongly suggest people still own an Nvidia Shield over over any other Android Tv and Microsoft Xbox as Nvidia Shield fully uses the audio passthrough (choose RAW audio track in Kodi 19 System 》 audio 》settings. Located at top and again the audio track setting above the different audio formats listed.  The default doesn't pass the audio as bitstream audio to receiver/soundbar. So do REMEMBER to change this setting. 2nd reason Nvidia Shield Kodi is better than Tv kodi versions,  is it outputs DTS :X. 
And Hence why all the Nvidia Shield 2017/2015 users are here on your add-on to enable Dolby Atmos tracks found on Netflix itself. 

Hope above has informed u all to make a decision and or solved the transition to Kodi 19.x

Kind Regards, 

Canice 

Ps: please fix label ignored rules as issues log files aren't available to Android 11 users.  Your policy on log file for bug reporting will be invalid when everyone is on Android 11.

**Comment by CastagnaIT** [comment]
On android 11 to get a log you need to connect the device via usb to a computer then usually you can browse data folder
or you can use also the Kodi log uploader addon

But i have already answered about the only possible solution, so reinstall Kodi from scratch
i found a different bug on last addon version, then if you will install from scratch you will have to use this zip: [plugin.video.netflix_1.14.0+matrix.1_20210222.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6020750/plugin.video.netflix_1.14.0%2Bmatrix.1_20210222.zip)

For the atmos is also explained on Wiki faq on how enable it (i have improved the faq)
