### ISSUE TITLE
Allow to load custom subtitles / .srt files

### ISSUE THREAD

**Issue by domdorn** [CastagnaIT/plugin.video.netflix#1085]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Use-Case
As a user of the kodi netflix plugin, I want to be able to load my own subtitles in .srt / other formats supported by Kodi.
For this, I want to be able to browse files/folders registered in Kodi (e.g. network shares, local folders) to select the corresponding subtitle.

### Expected behavior
When opening the subtitle menue and browsing for a custom subtitle, I'm able to select folders that are registered within Kodi

### Actual behavior
I'm only able to browse through the virtual folders of the netflix plugin. As these don't contain any files, the loading of custom subtitles is not possible. 

### Alternative behavior
The plugin allows me to upload files to ONE specific directory on my kodi instance which are readable from the plugin, e.g. as media files or similar. 

### Why do I need this? 
My spouse has a native language that is not always supported by Netflix subtitles. I want to be able to load custom subtitles for movies, so we can watch them together.

**Comment by CastagnaIT** [comment]
In my opinion this is a Kodi bug then you have to report this to Kodi devs not here,
the addon cannot do anything with the Kodi menus

as workaround you can export your tvshow to kodi library and use srt from kodi library
