### ISSUE TITLE
Subtitle language option doesn't appear.

### ISSUE THREAD

**Issue by posterpico** [CastagnaIT/plugin.video.netflix#109]
*I'm submitting a ...*
  - [✓] bug report
  - [ ] feature request
  - [x] support request

### Description
The subtitle language option doesn't appear.

[Description of the bug or feature]

### Steps to Reproduce

1. It didn't show the full language subtitle option like previous version (14.3)
2. I tried on some tv series, the subtitle option didn't show up.
**Expected behavior:** It should show same subtitle option as we see on netflix when use browser.

**Actual behavior:** I didn't see any language option on kodi netflix but when i play netflix on browser it showed up 5 subtitle language option (you can see on the screenshoot)

### Installation

* [✓] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [✓ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
I'm using Kodi 18.2 (Leia)

## Debug log
 https://paste.kodi.tv/xotizeseka.kodi

### Screenshots
[Please add a screenshot if that helps understanding your problem]
![image](https://user-images.githubusercontent.com/52008487/59820186-0fe9e200-9355-11e9-8bc9-6e77da07150a.png)
More info from screenshoot. I try in the same episode of TV Series, the subtitle didn't appear like when i open netflix on browser.
And i'm using US VPN and also language profile set to Indonesian to make Indonesian subtitle show up although i'm using US VPN.
If i don't use vpn, the subtitle will show up (Indonesian, English and Chinese)
Note : on the previous version (14.3) it worked fine.

[You can erase any parts of this template not applicable to your Issue.]

**Comment by jakermx** [comment]
Try Disabling None as Preferred Subtitle Language, it worked for me, once playing, select subtitle and set it as default for all media.

**Comment by posterpico** [comment]
It didn't work for me, still in the same problem. it worked fine in previous version, all subtitle option that appear on browser, it also appear on kodi netflix. but for temporary, i'm using subscene to handle it for now.

**Comment by jakermx** [comment]
Rooback to 14.3 and do this

modify  nfsession.py _api_url procedure

def _api_url(component, api_data):
return '{apiroot}{baseurl}/{buildid}{componenturl}'.format(
apiroot=api_data['API_ROOT'],
baseurl=api_data['API_BASE_URL'],
buildid=api_data['BUILD_IDENTIFIER'],
componenturl=URLS[component]['endpoint'])

with

def _api_url(component, api_data):
return '{apiroot}{baseurl}/{buildid}{componenturl}'.format(
apiroot=api_data['API_ROOT'],
baseurl='/shakti',
buildid=api_data['BUILD_IDENTIFIER'],
componenturl=URLS[component]['endpoint'])

and replace 'models/serverDefs/data/API_BASE_URL' with 'models/playerModel/data/config/ui/initParams/apiUrl' in website.py

and tell us what happenned

**Comment by jakermx** [comment]
if it fails, try to compare your manifest..json file when using VPN and when not....it will tell you if your VPN is really working.

**Comment by jakermx** [comment]
remember to reboot after reinstalling

**Comment by posterpico** [comment]
After i modified nfsessions.py and website.py on 14.3 & 14.0 Version. It solve the login (check credentials) problem.
But the subtitle issue is still in problem. So weird because on this version before the credentials issue, it worked.
is the name of the json file manifest_proxy_error.json?
which part do i should check? because it looked the same or i didn't check it clearly.

**Comment by jakermx** [comment]
it is on your C:\Users\YourWindowsUser\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix directory...

manifest.json and manifest.mpd

the .json file is the info you get from Netflix and the MPD one is the info the addon passes to InputStream Adaptive so it can do the playback. 

Did you delete your settings and cache on uninstall process?

the procedure should be, uninstall it, erasing the settings and old data, restart, then install the addon, then modify the files I suggested you, or you can do that on the zip file prior installing it.
then restart and login...it is very important to restart... since the service is running it is on memory, so it needs to be reloaded from disk by rebooting or by disabling and enabling it....

**Comment by posterpico** [comment]
i tried on version plugin.video.netflix.14.0.beta24_20190418.zip (from KODI TV Forum) then i edited the nfsessions.py and website.py, it worked.
when i install the newest version (14.5) again, the subtitle won't appears again and i did it with the same vpn server.
i think it solved. but i will wait for answer, maybe there's another solution with the newest version then i will close this issues.

**Comment by posterpico** [comment]
> it is on your C:\Users\YourWindowsUser\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix directory...
> 
> manifest.json and manifest.mpd
> 
> the .json file is the info you get from Netflix and the MPD one is the info the addon passes to InputStream Adaptive so it can do the playback.
> 
> Did you delete your settings and cache on uninstall process?
> 
> the procedure should be, uninstall it, erasing the settings and old data, restart, then install the addon, then modify the files I suggested you, or you can do that on the zip file prior installing it.
> then restart and login...it is very important to restart... since the service is running it is on memory, so it needs to be reloaded from disk by rebooting or by disabling and enabling it....

yes i delete my settings and cache.

**Comment by jakermx** [comment]
cool, so lets wait for the others, because I am not familiar with the addon as it, I like to help and my expertise is on networking and protocols, so MSL , models and that kind of stuff is my area, playback, is not.. happy that my suggestion worked...

Salud!!!

**Comment by posterpico** [comment]
okay thank you for helping me bro!
i guess i will close this section issue.
