### ISSUE TITLE
Launching any title causes Kodi to restart

### ISSUE THREAD

**Issue by Aldenwil** [CastagnaIT/plugin.video.netflix#1091]
[kodi.old.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6039333/kodi.old.log)
#### Your Environment
- Netflix add-on version: 1.14.0+matrix.1
- Operating system version/name: Xbian / Linux
- Device model:  Raspberry Pi

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [* ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When launching any content, the app loads the stream, creates the inputstream and runs the python, then Kodi reboots to the home screen.

#### Expected behavior

Expected behavior is for the video file to begin streaming.
#### Actual behavior

Kodi crashes, and boots up again.
#### Steps to reproduce the behavior

1. Open Netflix App
2. Choose an episode of a television show

### Debug log

The debug log can be found here:
[kodi.old.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6039339/kodi.old.log)

**Comment by Aldenwil** [comment]
I attached the log but it is not showing up. Log re-attached to this comment.
[kodi.old.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6039300/kodi.old.log)

**Comment by Aldenwil** [comment]
Apologies, did not fully enable debug logging. Attached is the correct log file for the crash. 
[kodi.old.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6039330/kodi.old.log)

**Comment by Aldenwil** [comment]
I am uploading a second error log as well, in case there were any discrepancies with the first. 
[Uploading kodi.old.log…]()

**Comment by CastagnaIT** [comment]
the addon can do nothing with Kodi crashes, you have to report it to Kodi devs
i can only suggest to try disable "mmal" from kodi player settings

**Comment by Aldenwil** [comment]
Thanks for the mmal suggestion, no luck there. I'll keep trying.

**Comment by rafhtl** [comment]
I have the exact same problem same exact log error
tried all settings but kodi keeps crashing
thanks

**Comment by CastagnaIT** [comment]
your problems are not things that can be solved here,
you will have to ask on Kodi or Raspberry community
