### ISSUE TITLE
Issue when playing movies or series from Netflix

### ISSUE THREAD

**Issue by roazhon** [CastagnaIT/plugin.video.netflix#1096]
## Bug report
Hi,

#### Your Environment
- Netflix add-on version: 1.12.3
- Operating system version/name: Libreelec9.2.6 Kodi 18.9 
- Device model:  Raspberry PI 3 B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

Only with Netflix movies or series, the video frame is jerky and then shifted by a few seconds with the audio, or no sound and the image flashes. I have no problem with my kodi media player with all movies when i am connected to my NAS 

#### Actual behavior

I have no problem to connect with my account and access to the Netflix library.
The problem is different depending on the video resolution of the movie. For example, with a film supplied in 540 SD, the video flashes and the sound is cut off and then heard randomly. With 4k movie, no problem with the audio, but sometimes the video is jerky and after the picture is no longer in sync with the audio, and after 30s to one minute it is synced again 

#### Steps to reproduce the behavior

1.  I tried changing various settings in addon config and adaptive input stream settings but it didn't change anything. I don't have an error message so I'm not sure if a debug log is needed ...let me know
2. I searched on your forum and others,  but i didn't find how to resolve this problem. I don't know if the issue is due to the raspberry (not enough RAM, processor...) , the addon settings, ...
2. 
3.

### Debug log

The debug log can be found here:

**Comment by jakermx** [comment]
RPI cannot play  smooth software based encrypted video due memory and proc capabilities.... so you need to set the limit resolution on expert setteings up to 720p
