### ISSUE TITLE
Basic proxy support 

### ISSUE THREAD

**Issue by hammercuba** [CastagnaIT/plugin.video.netflix#1099]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [ ] change an existing feature

### Describe your request

I live in Cuba, as some others countries in some places simply we don't have internet directly, only trough a proxy server, some time ago the proxy works but not now, I already read why, but I just can't use a VPN or another proxy. This was working some versions ago.

#### Describe the use case

unable to access after log-in

#### Describe an alternative

just re-support basic proxy

**Comment by CastagnaIT** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy
