### ISSUE TITLE
Search function doesn't work

### ISSUE THREAD

**Issue by Letalis82** [CastagnaIT/plugin.video.netflix#1109]
#### Your Environment
- Netflix add-on version: 14.1
- Operating system version/name: Windows 10

Used Operating system:
* [ x] Windows

### Describe the bug
On my main Kodi installation the search function doesnt work. When selecting the search option, kodi shows an error message and refers to the log.

#### Expected behavior
Show search screen

#### Actual behavior
Kodi shows error message

#### Steps to reproduce the behavior
1. [First Step]
Open nexflix plugin
2. [Second Step]
Select user
3. [Third step]
Select search menu option, then the error message appears.

### Debug log
https://paste.kodi.tv/xuxajugotu.kodi

**Comment by CastagnaIT** [comment]
this error happen because you have updated from a oldest bugged addon version
you have to uninstall addon and user data and reinstall last version from scratch

**Comment by Letalis82** [comment]
> 
> 
> this error happen because you have updated from a oldest bugged addon version
> you have to uninstall addon and user data and reinstall last version from scratch

Thanks for your answer! 

So in short:
1) Remove current plugin
2) Close Kodi
3) remove dir: %APPDATA%\Kodi\userdata 
4) Start Kodi and reinstall latest plugin

Correct?

**Comment by CastagnaIT** [comment]
> 
> 
> > this error happen because you have updated from a oldest bugged addon version
> > you have to uninstall addon and user data and reinstall last version from scratch
> 
> Thanks for your answer!
> 
> So in short:
> 
>     1. Remove current plugin
> 
>     2. Close Kodi
> 
>     3. remove dir: %APPDATA%\Kodi\userdata
> 
>     4. Start Kodi and reinstall latest plugin
> 
> 
> Correct?

this is too drastic...
remove the addon and when kodi ask to delete user data say YES
then reinstall last version

**Comment by Letalis82** [comment]
Tried that a couple of times (in the v18.x of Kodi), that didnt seem to work.

Problem allready existed when I was using the 18.x version of Kodi (and corresponding version of this plugin).
So yesterday I updated Kodi, and installed the Netflix plugin by hand after. 

However same problem existed, I'm missing something here but cant point out what it is

**Comment by CastagnaIT** [comment]
means that you continue to keep the addon data instead of deleting it

**Comment by Letalis82** [comment]
Worked! Thanks!
