### ISSUE TITLE
"My list" is limited to 92 entries

### ISSUE THREAD

**Issue by NerosTie** [CastagnaIT/plugin.video.netflix#111]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

v0.14.5

### Description

"My list" is limited to 92 entries, everything beyond that number is send into a sub-folder called "next page". The main issue with that, the movies and the series inside the "next page" are not sync with the library (even if you force the synchronization).

### Steps to Reproduce

1. Add more than 92 movies/films
2. See if there is a "next page" sub-folder in "My List"

**Expected behavior:** [What you expected to happen]
No sub-folder "next page" and a complete synchronization of "My list"

**Actual behavior:** [What actually happened]
Sub-folder "Next page" created inside "My list" with movies/series inside and this folder is not synchronized with the library.

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

env: OSMC

**Comment by CastagnaIT** [comment]
I don't understand very well what you're trying to explain
-one thing is to display the next page (eg. page 2)
-one thing is the synchronization with the library

Are you saying that next page (page two) in "my list" does not display any titles?

**Comment by NerosTie** [comment]
> Are you saying that next page (page two) in "my list" does not display any titles?

No, titles in page 2 are not sync with the library.

**Comment by Smeulf** [comment]
Hi.

Sync 'my List' with library works this way:

- If you add a movie from the Netflix addon to the library, it's added to my list
- If you add something to the Kodi library it's added to 'my list'

Any new item added to 'my List' from the website or application won't be synchronized with the library, except if you preform a full sync from the settings menu.

But maybe there's an issue with the full sync, that won't permit full sync to library.

Can you please explain how you add movie/shows to 'my List' and describe all steps to reproduce the issue?

**Comment by CastagnaIT** [comment]
the items in the first page, only half of the elements are synchronized?

**Comment by CastagnaIT** [comment]
in theory there is the possibility to fix this problem, but this will slow down the operations add / remove films-tvshows in the library or my list
when i have more time i will give it a try, I'll let you know

**Comment by CastagnaIT** [comment]
@NerosTie please can you make a try with this test?
[plugin.video.netflix_0.15.3_20190922_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3639605/plugin.video.netflix_0.15.3_20190922_test1.zip)

**Comment by CastagnaIT** [comment]
use this: [plugin.video.netflix_0.15.3_20190922_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3639618/plugin.video.netflix_0.15.3_20190922_test2.zip)
