### ISSUE TITLE
Tester needed to try Netflix add-on on Apple Tv - iPad - iPhone

### ISSUE THREAD

**Issue by CastagnaIT** [CastagnaIT/plugin.video.netflix#1114]
Need some users willing to try if you can play Netflix videos with the add-on,
on the following devices:

* Apple TV **ONLY from 4th generation and later**
* Apple iPad **ONLY from 5th generation and later**
* Apple iPad Pro
* Apple iPhone

### How to do:
- Install the add-on on Kodi 19 by following the instructions
- After download this add-on dependency and install/update it: [script.module.inputstreamhelper-mac.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6216196/script.module.inputstreamhelper-mac.zip)
- Try play a video

**Comment by jakermx** [comment]
Ihave an iphone10 and the emulator.... I wil be available till thurs...so I will check it then pal

**Comment by CastagnaIT** [comment]
currently ISA situation is in WIP
i will reopen this when there will be news
