### ISSUE TITLE
netflix app does not work anymore, but in browser works

### ISSUE THREAD

**Issue by damnms** [CastagnaIT/plugin.video.netflix#1116]
#### Your Environment
- Netflix add-on version:  14.1
- Operating system version/name:  coreelec stable (19.1)
- Device model:   odroid n2

Used Operating system:
* [ ] Android
* [ ] iOS
* [x ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

when i click on any movie or series it looks like as if it would start (the text and playback icon appears in the upper right corner), but then nothing happens. even worse, i have to reboot (by ssh because when i try to reboot after that in Kodi it also freezes) the machine which takes a while, otherwise it completely freezes when i start any other stream (music, tv etc.) 
#### Expected behavior

that the playback starts
#### Actual behavior

the playback icon and the text appears in the upper right but no video
#### Steps to reproduce the behavior

1. start netflix
2. login
3. select any video/serie

### Debug log

The debug log can be found here: https://paste.kodi.tv/qekowiduhe.kodi

**Comment by jakermx** [comment]
Hello. it is codec related, try settngthe resolution limit or in ISA Settings, select Manual Stream Selection....so  you can check what codec is missingof failing

**Comment by CastagnaIT** [comment]
you have enabled HEVC codec under linux this is not supported by widevine

**Comment by damnms** [comment]
thanks but when its not supported in widevine, why should i disable it on linux ?
i have some HEVC videos at my usb drive and i do not want to disable that support only because of netflix 
wouldnt it be better to ignore the HEVC support in that addon and use another codec?

**Comment by CastagnaIT** [comment]
LOL
you have enabled HEVC on this addon settings
you have to disable it on addon settings or you can not use netflix

**Comment by damnms** [comment]
then i misunderstood you, i thought you mean "i enabled that in linux and that addon can not work with that"
why not grey that option out if the addon runs on linux? then i would not waste my time in reporting bugs and get a "LOL" back for misunderstanding smth.

that "LOL" is pretty disrespectful btw. - maybe think about that
