### ISSUE TITLE
Key error : "loco"

### ISSUE THREAD

**Issue by xoleja01** [CastagnaIT/plugin.video.netflix#1124]
#### Your Environment
- Netflix add-on version: 1.12.3
- Operating system version/name: Open Source Media Center 2020.11-1, kernel: Linux ARM 32-bit version 4.19.122-2-osmc
- Device model:  Raspberry Pi 
Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ *] Raspberry-Pi
* [ ] Windows

### Describe the bug

Addon returns  KeyError: u'loco'

The debug log can be found here: [**kodi.log**](https://github.com/CastagnaIT/plugin.video.netflix/files/6239702/kodi.log)

**Comment by Kidlike** [comment]
I can confirm that this happens for me too. 
Kodi Matrix, Linux (Fedora), Netflix Switzerland region.

**Comment by betatester3016** [comment]
Resolved in [bug report 1121](https://github.com/CastagnaIT/plugin.video.netflix/issues/1121)

**Comment by betatester3016** [comment]
Look [here](https://github.com/CastagnaIT/plugin.video.netflix/issues/1121) for the solution.
