### ISSUE TITLE
KeyError in msl_handler.py when trying to play movie

### ISSUE THREAD

**Issue by aleprovencio** [CastagnaIT/plugin.video.netflix#113]
Hello,
As suggested here https://github.com/peak3d/inputstream.adaptive/issues/282 I'm posting this error after trying the daily build as of today.

edited as @Smeulf comment:
~~I hope this is the relevant error: `TypeError: 'NoneType' object has no attribute ['__getitem__'`]~~

Relevant error: `msl_handler.py", line 353, in _decrypt_chunks decrypted_payload = decrypted_payload[1]['payload']`

Here are the logs: http://ix.io/1MDq

**Comment by Smeulf** [comment]
HI.

The error you're pointing is not the revelent one. That first error is because it's a movie, so no episode is following. It's catched as expected.

Here you have an error in msl_handler.py line 353. Unfortunately this is a part of the addon I'm not yet familliar with, so you'll have to wait until @CastagnaIT can have a look, sorry.

Thanks for the report.

**Comment by jakermx** [comment]
YEp, the errror you are pointing is Next Up related, the real issue is while decrypting MSL resonses, My opinion is that you update he AddOn, but you kept the old settings files or you did not reboot after update it, 

Please delete the COOKIE file, msl_data.json, manifest.json and manifest.mpd, disable Up Next by  now, then use default skin and finally reboot and try again.

Please share your findings

**Comment by aleprovencio** [comment]
@jakermx, thanks for helping me out. I'm using the daily build version as suggested by @CastagnaIT, you mean upgrading to which version?

**Comment by CastagnaIT** [comment]
@aleprovencio 
for this problem i need more data,
please install this test version, run addon (with kodi debug info enbled) repeat the operations that cause the problem and post a new log
[plugin.video.netflix_TEST.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3322190/plugin.video.netflix_TEST.zip)

**Comment by aleprovencio** [comment]
done, here you go: http://ix.io/1MKO

**Comment by CastagnaIT** [comment]
thank you but need other test with this new test2,
Unfortunately i was not able to decode the data
[plugin.video.netflix_TEST2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3326849/plugin.video.netflix_TEST2.zip)

**Comment by CastagnaIT** [comment]
Done use this and post the log
[plugin.video.netflix_TEST3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3326880/plugin.video.netflix_TEST3.zip)

**Comment by aleprovencio** [comment]
thanks, here the logs: http://ix.io/1MMm

**Comment by Smeulf** [comment]
"INSUFFICICENT_MATURITY" says the log...
But that's good to know how it behaves in this case.

If you're the owner of the account, you should take a look on your profile settings and unlock the maturity level

**Comment by Smeulf** [comment]
@CastagnaIT does that also means results for categories and search are not filtered by maturity? It shouldn't even be visible if a maturity restriction has been configured.

**Comment by aleprovencio** [comment]
@Smeulf, if you're talking about the parental control, I had not set a PIN until now. I tried setting one up but leaving all content as allowed, ran the tests again and it doesn't work either.

**Comment by Smeulf** [comment]
On NF website, select manage profile, then edit your profile with the pen.

You should see 'allowed tv shows and movies', and you can select the maturity level here. I bet it's not set to 'all maturity levels' but to a lower value.

It's not directly related to the pin code.

**Comment by aleprovencio** [comment]
Ha OK I missed that, but yes, it is already set to all maturity levels. In addiction I'm able to watch this tested movie on the netflix web or the TV app for instance.

**Comment by Smeulf** [comment]
Looks like you have 4 profiles defined on NF. Are you sure you're using the right one with Kodi ? If I'm worrect you"re using 'Xand' profile.

Maybe that's a dumb question, but it worth to ensure ^^

**Comment by aleprovencio** [comment]
Don't worry about asking any questions :)

You're correct, I have 3 profiles and the additional kids profile that netflix creates, and yes, I'm using the 'Xand' one.

**Comment by Smeulf** [comment]
Well, for now, I'm running out of idea...

First, let's get some time to @CastagnaIT to fix the error. Then maybe he can tell what's going on.

NF says it's related to parental control, there's a help link in the logs. But if you're telling me you can see this video with the same profile on some other devices, that's very strange to me... Thanks for all the details!

**Comment by CastagnaIT** [comment]
hi
yes is parental control it looks like netflix thinks your profile is set to a lower level age
try to switch to 'teen' enter, play a video, exit, swith to normal, retry...

nothing can be done at the addon level

I did some cleaning now if it happens again the error popup should appear correctly

**Comment by aleprovencio** [comment]
It's so strange, I still can't manage it to work, Here's what I have done:

* Changed the 'Xand' profile to a lower level age, played a movie (via web), put the maturity level back
* Created a new profile with 'all maturity level' set

Both do play the movie via web but not with the addon.

Crazy! Please help!

**Comment by Smeulf** [comment]
Can you please post screen capture of:
- your profile settings
- your parental management control settings (you can blur the pin code/any personal data if you want, or change the pin before posting)

And can you give us the English name of the movie you're trying to watch?

I wish to try to reproduce the issue with the exact same settings you use.

Parental control can also limit access by name. Please ensure you didn't add it to that list.

**Comment by aleprovencio** [comment]
Sure. I've changed the language to English, this is me watching the tested movie on netflix web:

![2019-06-26-230949_1920x1080_scrot](https://user-images.githubusercontent.com/1352683/60228477-2c13e480-9869-11e9-9a8b-682fe94abf15.png)
![2019-06-26-231124_1920x1080_scrot](https://user-images.githubusercontent.com/1352683/60228478-2c13e480-9869-11e9-8434-9f31f1490cdd.png)
![2019-06-26-231715_1920x1080_scrot](https://user-images.githubusercontent.com/1352683/60228479-2c13e480-9869-11e9-92e7-e67165cdf4cd.png)

**Comment by Smeulf** [comment]
Thanks. It's making me crazy too... Here it's rated 13+ so your settings looks good.

If you don't use the Kodi library export, you still can try to remove the add-on, ensure plugin.video.netflix  folder is deleted in userdata/addons_data or delete it manually, and reinstall the addon.

It will flush all settings for the add-on. I'm not sure it helps but it worth a try regarding the situation.

**Comment by aleprovencio** [comment]
Hello @Smeulf, done that but issue stays.

I've noticed that I can watch the available movies when logged in with the kids profile.  :/

**Comment by Smeulf** [comment]
Well, I'm really sorry but I don't know what to say...

**Comment by aleprovencio** [comment]
Thanks for trying anyway. :)

Taking a close look on the second picture I posted above, I noticed that on the left side of the profile "angry bird" icon there is a "kids" text. 

Do you know what is this or if it is somehow related to the problem?

**Comment by Smeulf** [comment]
I don't think so. It's just a shortcut for the kids profile, I have the same.

**Comment by CastagnaIT** [comment]
> Hello @Smeulf, done that but issue stays.
> 
> I've noticed that I can watch the available movies when logged in with the kids profile. :/

explains better
how do you play a movie available in normal profile from a kid profile?

**Comment by aleprovencio** [comment]
Sorry about not being clear enough @CastagnaIT.

What I meant is the other way around: I can watch all (at least what I have tested) the movies available on kids profile. With some exceptions I've also noticed (i.e. Heal 2017), I am not able to watch all other movies.

Where can I find out the maturity level of a given movie?

**Comment by aleprovencio** [comment]
Here are the logs for `Heal (2017)`, which do work. http://ix.io/1Nwq

**Comment by Smeulf** [comment]
aleprovencio did you enabled PIN code in the addon?

If in Netflix you kept pin protection off, than you don't need the PIN to be enabled in the addon. You should then disable it and try again.

**Comment by aleprovencio** [comment]
The PIN was as default disabled, @Smeulf. Anyways, just in case, I just did the test enabling/disabling this setting both on netflix web and addon but unfortunately leading to no good.

Thanks again.

**Comment by CastagnaIT** [comment]
try install this test version, open netflix using the normal profile not Kid, so put a new log

it is strange that you are the only one having this problem, the only thing that comes to mind is a particular configuration of your profiles that cause some type of unexpected behavior then with this test maybe... i can understand something more 
[plugin.video.netflix_TEST1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3351783/plugin.video.netflix_TEST1.zip)

**Comment by Smeulf** [comment]
@aleprovencio maybe you can also try to disable "Test participation" on your account...

I don't have the same levels of maturity, mine are only "All", "7+", "13+" and "16+", but maybe it's country related.

**Comment by aleprovencio** [comment]
I don't know what is happening but I can't login with my credentials anymore, even after uninstalling answering yes to erase settings and rebooting. Is there other things I must remove for it to work?

**Comment by CastagnaIT** [comment]
I don't know it's very strange...
if you have also confirmed the removal of the settings there should be nothing else.

if web access still works, the problem is elsewhere
are you sure you were connected to the internet after you re-installed the addon?

**Comment by aleprovencio** [comment]
yes, other things from kodi connect :(
I can't think of anything for now...Will keep trying

**Comment by aleprovencio** [comment]
This is just crazy, I just reinstalled LibreELEC from scratch, put on language/timezone settings, then installed the zip you provided and...can't login.

I always receive an email from netflix telling me there's a new access to its account.

And netflix web is still fine.

Summing this up with the main issue, I'm starting to think there's problem with my account on netflix and i might delete and create a new one.

**Comment by jakermx** [comment]
Changing your ESN and deleting the COOKI file, should resolv the issue.

Manifest Loadinng Proccess does not involves Profile ID or Token, it is based on ESN, once the ESN is logged and is associatted with a Profile, it will do anything with the ESN, and since the cooke is set to never expire, it will ask anything to Netflix as the original user, in order to fis this, COOkIE needs to be renewed and I would suggest, set ESN as NFCDH-01-PROFILE_TKN_ID.

**Comment by jakermx** [comment]
The Issue you posted on inputstreamadaptive was locale_id related, then you update your version twice, and the error changed, may I ask... did you uninstall with setttings delete before install the new versions and the TEST versions?...if not, please uninstall, click on yes with asked for delete settings, then reboot your system, install the lasted master build or daily one, and then try again....deleting settings does what I am suggesting.

**Comment by aleprovencio** [comment]
Thanks for trying, @jakermx .

I've changed ESN, but since this is a new installation on a fresh LibreELEC there were no cookie files to delete.

I still can't login, its maybe related to #126.

About your last comment, the error actually did not change, it got just more evident after some adjustments on the plugin's test source. I've always followed the procedure you described on doing new installs, OK.

**Comment by jakermx** [comment]
Did you got a lot of login emails from Netflix during this troblueshooting?

**Comment by aleprovencio** [comment]
Hello @jakermx,
first of all thanks for your time and sorry about taking so long for me to do new tests, I couldn't get to my kodi box until now.

One more time I reinstalled LibreELEC and this addon from this repository from scratch.  I followed your advice to disconnect all my devices, and it worked fine, I can login again now. And yes, I was receiving emails from Netflix.

The parental control issue stays, I only can watch movies for kids. Here are the logs for a movie I can't watch: http://ix.io/1P59

Take note this is latest version from repo, not one of the 'test' versions provided on this thread.

**Comment by CastagnaIT** [comment]
do this:
open netflix page with Google Chrome
login and stop it, in the page of profile selection
Press F12 key to open dev page,
in the html code press CTRL+F to open search box
copy paste:
EFC3PECLRVDDJJNAJVHEDY537A

go down to a big text that starts with netflix.reactContext, then 
right click on the big text to show the context menu and select "Copy Element"

then paste such as "link" same you do with log

**Comment by aleprovencio** [comment]
here you go @CastagnaIT http://ix.io/1P6v

**Comment by aleprovencio** [comment]
Hello @jakermx and @CastagnaIT, still no clues about this? You think I should delete my netflix account start a new one?

**Comment by CastagnaIT** [comment]
sorry unfortunately i didn't have enough time to check maybe over the weekend

**Comment by CastagnaIT** [comment]
your main profile "Lucas" is marked "child" this can be the cause

**Comment by aleprovencio** [comment]
OMG it works !!!

I never knew there was a main profile account, but if it ever existed I would presume it was my profile since it was the first created. Somehow netflix has put my nephew's (child) account as the main one, and this way I could not access movies with higher maturity levels from any profile from this addon (but could from netflix web and other). Maybe this deserve a Readme/FAQ entry?

Anyways, this was such a long standing issue for me and you just nailed it @CastagnaIT, thank you so much!  I must not forget @jakermx who also borrowed a lot of its time trying to help me with this, thank you!
