### ISSUE TITLE
ESN cannot be used, The specified IPC slot perform_key_handshake does not exist

### ISSUE THREAD

**Issue by trohnjavolta** [CastagnaIT/plugin.video.netflix#1131]
#### Your Environment
- Netflix add-on version: 1.15.0+matrix.1
- Operating system version/name: Android Tv
- Device model:  Nvidia Shield TV (2017)

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
I cannot get streams in 4K to work. HDR works but 4k doesn't.
I worked through the troubleshooting in the wiki and ended up in the widevine settings.

Trying to use the set ESN gets me this error:
**ESN cannot be used, The specified IPC slot perform_key_handshake does not exist**

Comparing the Netflix Addon ESN with the ESN from DRM Info App, System Settings and Netflix App (all 3 show the same ESN, 4k playback via Netflix App works) I see that the default ESN in the Netflix Addon seems to be cut off. The last 64 chars after the hyphen are missing. However changing the ESN the the one from the Netflix Addon results in the very same Error message as described above.

#### Expected behavior
4K playback

#### Actual behavior
Playback only up to 1080p, HDR works.

#### Steps to reproduce the behavior
1.Choose a movie or episode in the netflix addon
2. play it back

#### Possible fix

I guess I need to put in another ESN..or change the format somehow?..

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6298523/kodi.log)

**Comment by CastagnaIT** [comment]
this is to fix the error: The specified IPC slot perform_key_handshake does not exist
[plugin.video.netflix_1.15.0+matrix.1_20210413_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6301812/plugin.video.netflix_1.15.0%2Bmatrix.1_20210413_t1.zip)

but usually users with Shield not needed to insert the full ESN to have 4K
make sure that you have set all settings in right way as wiki spec

**Comment by trohnjavolta** [comment]
> this is to fix the error: The specified IPC slot perform_key_handshake does not exist
> [plugin.video.netflix_1.15.0+matrix.1_20210413_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6301812/plugin.video.netflix_1.15.0%2Bmatrix.1_20210413_t1.zip)
> 
> but usually users with Shield not needed to insert the full ESN to have 4K
> make sure that you have set all settings in right way as wiki spec

Thx I'll try it. What do you mean by not the full ESN? Just ESN up to the last hyphen?
I set and checked everything in the wiki.
I have to add that my shield's bootloader is unlocked and it's rooted via magisk..
But then again, 4k playback via netflix app works just fine.

**Comment by CastagnaIT** [comment]
> What do you mean by not the full ESN? Just ESN up to the last hyphen?

yes, similar to this:
Partial: NFANDROID2-PRV-SHIELDANDROIDTV-NVIDISHIELD=ANDROID=TV-6463-
Full: NFANDROID2-PRV-SHIELDANDROIDTV-NVIDISHIELD=ANDROID=TV-6463-**C3432423423423423423423423234234234**

I am not aware of the influence of root
but in theory if you do not change the original ROM everything should be fine

**Comment by trohnjavolta** [comment]
Seems the update had just a "cosmetic" effect. The error message is gone now however still no 4k playback. Also tried with full ESN. Are there reports that 4k playback works on shield tv using kodi matrix?

**Comment by CastagnaIT** [comment]
yes all nvidia shield versions works in 4k with this addon
you can also try run  "configuration wizard" on expert setting, this option automatically change the settings in right way

if not works again, please open esn/widevine settings window on expert setting, and click on "save system info" button and attach here the saved file

**Comment by trohnjavolta** [comment]
I honestly don't know what I may have missed, but after running config wizard I now get 4k playback :) thx
