### ISSUE TITLE
libffi error

### ISSUE THREAD

**Issue by testbughub** [CastagnaIT/plugin.video.netflix#1133]
#### Your Environment
- Netflix add-on version: 1.15.0
- Operating system version/name: Ubuntu 20.10 x64 kernel 5.8.0-49-generic

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
After I've entered my credentials to login, I get the error "`SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)`"
I tried installing the add-on through the repo and directly with the zip.
I've also tried searching for similar errors, but I couldn't find a fix.

#### Expected behavior
A successful login.

#### Actual behavior
Netflix Add-on Error popup with the error mentioned above.

#### Steps to reproduce the behavior
Input credentials > error.

#### Possible fix
Not sure. My first thought would be old versions of some library files, but I'm not competent enough to fix it myself.

### Debug log
The debug log can be found here:
https://paste.kodi.tv/ojuvasociv.kodi

#### Other information
It was working before I updated to Matrix.
Sorry if I missed something obvious.

**Comment by CastagnaIT** [comment]
The error is not related to the add-on,
but a problem in your system or related to your python installation
i cannot help you here, try ask in kodi forum

**Comment by testbughub** [comment]
Yeah, I was afraid of that. Thanks for the quick reply.
