### ISSUE TITLE
NFAuthentication Key Error

### ISSUE THREAD

**Issue by anisingh62** [CastagnaIT/plugin.video.netflix#1137]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: <--Windows 10-->
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

1. Just watch this image. The error is being repeated despite setting Chrome Path in jSON Editor.
2. After logging in and waiting for few seconds I receive this message on browser auto closing.
3. Please see this issue so that I could also login and see netflix the first time as you all are doing!

#### Expected behavior

Sorry I Could not give you the Logs as this topic is not from kodi player!

#### Actual behavior

Due to this I am unable to go further for the Authentication key in Kodi Player
#### Steps to reproduce the behavior

1. Nothing much just after logging I am getting same error.
2. Due to which I cannot get pin and NFAuthentication.key file also.
3. The only thing I am getting is folder of Browser temp data

#### Possible fix

Sir I am not a developer so I seriously sorry but can help out in making videos and other stuffs when required.

### Debug log

The debug log can be found here:

#### Other information

In last after closing the tool I am only getting one folder named Browser Temp Data thats it!

#### Screenshots

![Screenshot 2021-04-16 015959](https://user-images.githubusercontent.com/82613527/114934609-b91d9880-9e57-11eb-9e0d-b1ac2e2089ca.png)

**Comment by CastagnaIT** [comment]
i need more info to try understand what happen
please run login with this test: [NFA_Debug_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6331081/NFA_Debug_t1.zip)
and after it raise the error copy/paste all the "Current status" text here

**Comment by anisingh62** [comment]
I reviewed it again and the account was not completed as it did not have any credit card or debit card in it!.
Finally its working fine after adding the card and completing the whole signup process.
And its working. But just wanted to ask last question will this work after expiration of plan i.e. 30 days

**Comment by CastagnaIT** [comment]
thanks for the info i will try to see if i can put a check,
i think that if you do not renew the account plan the login expire

**Comment by anisingh62** [comment]
If we have to login after paying the account than what is the purpose of this code😅. If you could please explain that would be very well appreciated
