### ISSUE TITLE
"Part" v "Season" on Library Export

### ISSUE THREAD

**Issue by dm2912** [CastagnaIT/plugin.video.netflix#114]
## General information
Conflicts between Netflix and the TVDB over use of "Part" v "Season"
### Addon version used
Latest
### Description

Ok, this is a weird one. Some shows on Netflix have "seasons". This is usually shows that have been on tv networks and have clear seasons each year. 

Then, they have taken to splitting some shows into "Parts", so a 32 episode show may have four parts of 8 episodes. 

A good example is Terrace House.

This comes in 2 "parts" (not seasons)

![image](https://user-images.githubusercontent.com/25871666/59983631-00e78600-961a-11e9-9ebf-a86fb71d37e7.png)

What this means is when you export it to the library it exports as two "Seasons"

But, the TVDB (bless them, they are a strange lot) have it as one season (they only bow to "season" splits not "part" splits)

![image](https://user-images.githubusercontent.com/25871666/59983651-2aa0ad00-961a-11e9-8d87-bb6dca79ec16.png)

im not sure if there is a way the add-on can recognise when things are "parts" as opposed to "seasons" and not split them on export?

at the moment ive found the easiest solution is just going into the Library directory and renaming the files from S02E01 to S01Exx etc.

**Comment by jakermx** [comment]
Try another Info Provider and see the results.

**Comment by dm2912** [comment]
> Try another Info Provider and see the results.

TheMovieDB also ignores Netflix "parts" and just lump them as one season. As generally do IMDB

Is there anyone else?

**Comment by jakermx** [comment]
try enable the metadaa retrival from file on Player Settings...it could help

**Comment by Smeulf** [comment]
Hi,

This is due to Netflix 'special' cuts. Like in Money Heist... Some other shows have 6 episodes as they was originally 3 and the 3 last exported are never detected.

We're working on something to export NFO files for tv show episodes, that will (hopefully) solve the problem.

You won't get all data (ie actors) but at least, you'll see all your episodes :D

That feature is under review now, to ensure we didn't miss something, we're just polishing it.

I hope it gets release soon!

**Comment by dm2912** [comment]
> This is due to Netflix 'special' cuts. Like in Money Heist... Some other shows have 6 episodes as they was originally 3 and the 3 last exported are never detected.

oh dont even start me on Money Heist. Its not helped by the TVDB mods being a sensitive bunch. They insist on following the episode order for the Spanish release "La Case de Papel" for the netflix release for no obvious reason. 


but yeh, when Netflix have "seasons" its fine, because that generally matches tvdb or the moviedb, its when they split things into "parts" it gets messed up. 

as it is, just remote accessing my firetv and quickly changing file names sorted it

**Comment by Smeulf** [comment]
The rename in your case works because you have the same number of episodes, you're lucky.

But if you have S01E01 to S01E06 as it's S01E01 to 03 in TVDB, you'll never solve it ^^ Same for S02 that doesn't exists. The NFO stuff will work with all cases, as NFO have the priority over the scrapper when they exists.

We'll add a new comment as soon as the feature is released!

P.S. I won't discuss TVDB choices here ;)

**Comment by jakermx** [comment]
I think that once you know what you have and how it was stored, it is ok...

I.E. I like a lot InuYasha or DBZ, inthe particular case of InuYasha I bought the DVD directly from Japan, 2 box sets with all the episodes, no seassons, no  parts, no limited series... just episodes and thats it....currently I look for it online and there are a mix of stuff, I have found another series finale, and there are things called OVA and Specials , that Include what I had in 2 box sets... so If Netflix buy some episodes  of a  TV series  as teaser and they tag it as X and then they look the income and decides to buy the comple thing so they called X +Y, Z, on whatever, I think that if we have a tag for identify it, it does not matter, what could happen wrong id the viewable_id of a tittle changes... that will make your exported ids belonging to another stuff or even worst, to nothing......

I would suggest, that you export them as you can identify them and use some keywords so the info wrapper could retrieve something , I.E. dont save Money Heist Seasson 1 as "La Casa de Moneda Temporada 1", try something lile Casa de Moneda 1, or episodes tag them serially .

My mother know me as Alex,  My father as Cesar, My friends as Jaker or Crudo, so when I mesh them, they dont get all, caus they dont know me as they are.....

So  lets hope that the manifest of each show have some id that have  global meaning.

**Comment by Smeulf** [comment]
Using NFO will just export episodes names, seasons, and episodes numbers as in Netflix.

Ie if you see in netflix "That wonderfull show / Part 1 / Episode 27 / That wonderfull 27th episode", you'll see in Kodi "That wonderfull show / Season 1 / Episode 27 / That wonderfull 27th episode" nevermind what the scrapper can get.

The only thing we don't change is "Season 1" to "Part 1". It might be possible, but honestly I think it's very usefull.

**Comment by Smeulf** [comment]
For Meney Heist, you'll see Season 1, 2 anthe d upcomming 3 with the corresponding episodes as in NF

**Comment by jakermx** [comment]
Just to be clear, Terrace House Boys and Girls, just have 1 seasson, but Netflix split it as 2 parts, but the episode numbers are  the same on Netflix, wikipedia, imdb, tvdb, etc etc..... so I dont get your issue at this point...

**Comment by Smeulf** [comment]
Terrace House Boys and Girls with NFO will be 2 seasons.

Anyway, don't worry too much. It will not be mandatory, plus there's an option to ask the user to export or not. So you'll be free to choose for every show, and movies ;)

**Comment by dm2912** [comment]
> Just to be clear, Terrace House Boys and Girls, just have 1 seasson, but Netflix split it as 2 parts, but the episode numbers are the same on Netflix, wikipedia, imdb, tvdb, etc etc..... so I dont get your issue at this point...

Yes, the episode numbers (sometimes) are the same because of the japanese naming conventions. With season 2 they call them season 2 but carry on the episode numbers from season one, so S02E01 is actually S02E13. 

Of course, that causes further confusion when using online scrapers because if thetvdb etc do split a show into seasons, they reset the episode numbers back to 1 again :dagger: 

So Terrace House is for instance:

S01E01
~
S01E08
and then
S02E09
~
S02E10

Which totally confuses any online scrapers because the Episode numbers are correct, but in the case of shows involving "parts" the season number is wrong. 

But actually, If you export Terrace House you will see it exports as 
S01-E01
And then
S02-E02

So the episodes have to be renumbered as well as the season.

**Comment by Smeulf** [comment]
You might want to test with the last master version, the NFO feature has just been pushed ^^

Download the master branch as zip and update manually. Then take a tour on the add-on settings, for the library. You should see an 'export nfo' option. You can set 'For Tv Show' to 'ask' so you'll be free to choose!

Feedback is welcome!

**Comment by Smeulf** [comment]
Or you can get the last [daily build](http://www.mediafire.com/folder/vifnw8ve44bi7/KodiNetflixAddon)

**Comment by dm2912** [comment]
downloaded and just ran a test.

Tested it on Rebellion because thats one tv series where it differs to whats on TVDB etc. (Rebellion was originally on Irish tv. First season called Rebellion, second season called Retribution, but Netflix merged them into one show with two seasons).

Season 1 comes over perfectly to the library.
Season 2 almost does, all the episode info comes across but it doesnt pick up episode titles (so they are just called episode 1, episode 2) genre and release data are wrong, but its pretty solid still. will have a look at the nfo tomorrow and see what it dragged over.

**Comment by Smeulf** [comment]
Thanks for the feedback.

Episodes names are those as seen in NF and exported as is. Remember the NFO will have priority over online data (unless it was scanned before exporting the NFO then it remembers the data unless you refresh the episode)

Genres and cast can't be retreived with that method, it would overload the servers too much in some case so we choose not to add it.

About the release date, we only have the year, and it seems it's not sufficient for Kodi. If someone have an idea, please share.

The NFO feature goal is not to get all the information a scrapper could retreive, but to ensure all episodes are detected by the library and can be played.

**Comment by CastagnaIT** [comment]
can this issue be closed?
