### ISSUE TITLE
[MATRIX] Log Errors

### ISSUE THREAD

**Issue by gavish007** [CastagnaIT/plugin.video.netflix#1140]
#Bug report
LOG ERRORS

LOG: https://paste.kodi.tv/raquvemapa.kodi

**Comment by CastagnaIT** [comment]
Seem that your device is not allowed to the use for netflix, you can try use it with low resolutions,

please update to latest version (1.15.1) and then try follow these instructions on wiki:
[This title is not available to watch instantly](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#This-title-is-not-available-to-watch-instantly)

**Comment by itachi-mxyc** [comment]
![image](https://user-images.githubusercontent.com/57306127/115737817-19c63d00-a352-11eb-9e39-a31bfda8ecf4.png)

**Comment by CastagnaIT** [comment]
i'm sorry but Beelink products are not Netflix approved,
if your model version support dual-boot, you can use Netflix addon on CoreELEC OS.
Instead if you want still use it under Android the only solution is to buy a real certified device

**Comment by CastagnaIT** [comment]
Closed due to no answers
