### ISSUE TITLE
Nvidia shield Playback in SD

### ISSUE THREAD

**Issue by Eike-dotcom** [CastagnaIT/plugin.video.netflix#1143]
Hi,
I noticed yesterday that all Netflix content is playing in 540p. Just a few days ago it was working fine, with everything playing in 1080p. Since then I have not changed anything (not that I know of anyway)
Other streaming addons, like Prime Video that also server DRM protected content work just fine. They play their content in 1080p like intended.

Hardware: nvidia shield 2017
Kodi Version: 19
Addon Version: 1.15.1+matrix.1

**Comment by CastagnaIT** [comment]
it is very likely that you have changed some settings also not related to the addon
suggest you to open addon expert settings
and select "run addon config. wizard"
this will fix all settings in automatic way

if after this it is still at SD, try put the ESN in esn (expert) settings

**Comment by Eike-dotcom** [comment]
Thanks for replying so fast! 
Your fix sadly did not work. I also checked my ESN with the official Netflix addon and the one in the Kodi addon. They match.
Here is my logfile, maybe this helps.
https://pastebin.com/AbD0JcY0

**Comment by jakermx** [comment]
Please enable debugging  on KODI and set debug level to verbose in Netflix Expert Settigs

**Comment by Eike-dotcom** [comment]
> 
> 
> Please enable debugging on KODI and set debug level to verbose in Netflix Expert Settings, then test and share the log file

Here is the log 
https://textbin.net/raw/apwg164ltk

**Comment by CastagnaIT** [comment]
somewhere you still have wrong settings,
open inputstreamadaptive settings and set as:
![immagine](https://user-images.githubusercontent.com/3257156/116057042-b3595b80-a67e-11eb-8ac7-7263509d4a12.png)
![immagine](https://user-images.githubusercontent.com/3257156/116057129-c704c200-a67e-11eb-986f-f4b6cf498bdb.png)

if not works again, i have no idea
try attach here the system info file: from addon expert settings, open ESN Widevine settings, and click on "save sys info" button

**Comment by c0sby** [comment]
I have this same problem,
few days ago was ok.

I don't changed any options.
Next day i run netflix addon and what it is. 

Addon HBO, Youtube it works ok.

Weird :)

Hardware:
Raspberry PI 4 8GB
OSMC - Kodi 19 Matrix
Netflix 1.15.1+matrix1

**Comment by CastagnaIT** [comment]
@c0sby same NVIDIA Shield version?

**Comment by Eike-dotcom** [comment]
> 
> 
> somewhere you still have wrong settings,
> open inputstreamadaptive settings and set as:
> ![immagine](https://user-images.githubusercontent.com/3257156/116057042-b3595b80-a67e-11eb-8ac7-7263509d4a12.png)
> ![immagine](https://user-images.githubusercontent.com/3257156/116057129-c704c200-a67e-11eb-986f-f4b6cf498bdb.png)
> 
> if not works again, i have no idea
> try attach here the system info file: from addon expert settings, open ESN Widevine settings, and click on "save sys info" button

My inputstream is configured exactly as yours, still no luck.
Here is the log file your requested:
https://pastebin.com/dZnq38t7

**Comment by CastagnaIT** [comment]
as far as i can see everything is correct
you could try update with this WIP test: [plugin.video.netflix_1.15.1+matrix.1_20210430_exp.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6403459/plugin.video.netflix_1.15.1%2Bmatrix.1_20210430_exp.zip)

**Comment by Eike-dotcom** [comment]
Sorry to everyone involed. The solution to my problem is as simple as it is dumb . My Netflix membership did not allow me to stream in HD.
Huge sorry to everyone who took time out of their day to help me.
