### ISSUE TITLE
It was not possible to get the data from Widevine Cryptosession

### ISSUE THREAD

**Issue by Tutueti** [CastagnaIT/plugin.video.netflix#1144]
#### Your Environment
- Netflix add-on version: 1.12.4
- Operating system version/name: Android TV 7.1.2

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

- Whenever I try to run the Addon it gives the error: "It was not possible to get the data from Widevine Cryptosession"
- Tried already on Leia 18.9 and on 19.0, with the same results
- Happens in a fresh install of Kodi

#### Expected behavior

The addon starts and shows content

#### Actual behavior

It does not get past the error message

#### Steps to reproduce the behavior

1. Install Kodi on Android TV 7.1.2
2. Install Addon
3. Error shows up

#### Possible fix

No idea, maybe it happens because the system is android tv x86 running on a laptop

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6371111/kodi.log)

### Additional context or screenshots
Screenshot of Netflix app with ESN
![1619315861885](https://user-images.githubusercontent.com/83148242/115978021-5d948e80-a56c-11eb-92b5-dfcfaf91477e.jpg)
Screenshot of [DRMinfo]()
![Screenshot_20210424-225617](https://user-images.githubusercontent.com/83148242/115978043-8d439680-a56c-11eb-8dd5-69d7c53cee7d.png)

**Comment by CastagnaIT** [comment]
This can not be solved here, your device not allow widevine communication to Kodi this could means:
-you are using a custom rom that has broken the original widevine library
-your OS version is too old

**Comment by zhouyunjian** [comment]
> This can not be solved here, your device not allow widevine communication to Kodi this could means (FWIK):
> -you are using a custom rom that has broken the original widevine library
> -your OS version is too old

I have this problem either。 you mean that some device is not possible to play Netflix？

**Comment by CastagnaIT** [comment]
it is no possible use it with kodi
