### ISSUE TITLE
AttributeError: module 'xbmcvfs' has no attribute 'translatePath'

### ISSUE THREAD

**Issue by Khuntza** [CastagnaIT/plugin.video.netflix#1145]
#### Your Environment
- Netflix add-on version: plugin.video.netflix_1.15.0+matrix.1_20210410
- Operating system version/name: Linux version 5.4.51 (milhouse@libreelec.tv) (gcc version 10.1.0 (GCC))
- Device model:  raspberry pi 3b

Used Operating system:
* [X ] Linux  - Libreelec
* [X ] Raspberry-Pi

### Describe the bug
Netflix addon no longer launches. When running the addon the below error is given.
AttributeError: module 'xbmcvfs' has no attribute 'translatePath'
Click ok on dialog closes add-on.

#### Expected behavior
Running the addon should open and proceed to the user selection page.
Logon credentials were previously installed and valid.

#### Actual behavior
Dialog box - "AttributeError: module 'xbmcvfs' has no attribute 'translatePath'"
Suggests checking the error log in Kodi

#### Steps to reproduce the behavior
Reinstalling the addon from repository or zip gives an error notification during installation.
Deleted add-on
Reset all add-on settings to default
reinstalled Inputstream after noticing weird 999.X versioning in the logs.

#### Possible fix
https://forum.kodi.tv/showthread.php?tid=357540 - The user here ended up just reinstalling but its a similar looking error log
https://github.com/robweber/xbmcbackup/issues/166 - Here a user had a similar error and it was resolved by the developer

### Debug log
[01_KODI_CRASH.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6397301/01_KODI_CRASH.log)
Lines 1065 - 1104 seem to be of interest. Named error occurs on line 1085.

#### Other information
Everything was working fine until earlier this week. I've made no significant changes to LibreElec, Kodi or the Netfilx plugins.
The Liberelec version is a custom 'Milhouse' one. This developer stopped working on his builds last year. I am on Kodi 19 alpha and can't really progress forward in version now. Official LibreElec builds are on Kodi v18 and wont be upgraded to 19 for some time. I dont believe going back in Kodi version like that is possible without having to start over, so I'm hoping to not have to reinstall.

#### Screenshots
N/A

**Comment by CastagnaIT** [comment]
we do not give support to unstable Kodi versions,
your solutions are:
- rollback to official release of librelec Kodi 18 and then install the addon for Kodi 18 version
- fork the addon project and fix the problems yourself to suite your unstable kodi version, but you could have also other problems

**Comment by Khuntza** [comment]
I think my build has been very stable and the Netflix plugin has always worked well with it. The Milhouse builds of LibreELEC are widely used, to my understanding. 

All the same, I appreciate you taking a look. I have a spare SD card so I will see what I can work out. Thanks.
