### ISSUE TITLE
now that libwidevinecdm0 is available for RasPi, will anything change?

### ISSUE THREAD

**Issue by npmstart-pray** [CastagnaIT/plugin.video.netflix#1146]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [X] change an existing feature

### Describe your request

will adding this lib to an existing kodi install on a RasPi enhance or break Inpustream?

#### Describe the use case

people running kodi on raspi4 - I'm certain many users with non-smart tvs are using raspi kodi 

#### Describe an alternative

I don't know...maybe it makes developing this add-on easier/faster....something.

#### Development tips

I rather suspect a fork from here may be somewhere on the road ahead...

#### Specific details

now that widevine is approved for raspi hardware...this could potentially be a way forward perhaps?  Not sure what to ask here.

I'm using xbian (latest k5.10.27) on raspi4 4gb

**Comment by npmstart-pray** [comment]
and as an aside, Thonny runs the authentication script...it might be significantly easier for people to edit which browser they use there

**Comment by CastagnaIT** [comment]
> will adding this lib to an existing kodi install on a RasPi enhance or break Inpustream?

RPI widevine is nothing new, just for convenience they distribute the library through their channel
if you have to ask if there will be support on Inpustream Adaptive or Inpustream Helper you will have to ask in their github not here...

this library will not provide additional features to the existing one

**Comment by npmstart-pray** [comment]
Ok.
