### ISSUE TITLE
After Widevines update the video play stopped.

### ISSUE THREAD

**Issue by Rowhdy1337** [CastagnaIT/plugin.video.netflix#1157]
#### Your Environment
- Netflix add-on version:  1.12.4
- Operating system version/name:  LibreElec 9.2.6
- Device model:   RPi3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [✓ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
 

I cannot run any movie, it gives me loading circle and looks like to be played but it stops and dont let the movie play. It happened after an update of Widevine CDM
#### Expected behavior

Watch the movie without problems, be loaded.
#### Actual behavior

I just get loading circle and nothing happends, the movie doesnt play.

#### Possible fix

Widevine update that i installed.

**Comment by decorte** [comment]
i have the same problem after widevine update. raspbery pi

**Comment by sportbilly789** [comment]
I have the same issue, 

    Netflix add-on version: 1.12.4
    Operating system version/name: LibreElec 9.2.6
    Device model: RPi4

Many thanks

**Comment by decorte** [comment]
got it solved by following the workarounds on the previous issue

**Comment by Rowhdy1337** [comment]
> got it solved by following the workarounds on the previous issue

Can you please link me that workaround?

**Comment by decorte** [comment]
there are a couple is different workarounds posted in this issue, for me this was enough:
https://github.com/CastagnaIT/plugin.video.netflix/issues/1154#issuecomment-836668595

**Comment by jakermx** [comment]
Update your InputStream Helper to 0.5.3 then remove your  Widevine  and Install it again, dont use (Re) Install....thats the current working solution.
