### ISSUE TITLE
Netflix menu works fine, but player wont start

### ISSUE THREAD

**Issue by jdrly** [CastagnaIT/plugin.video.netflix#1159]
#### Your Environment
- Netflix add-on version: 14.1.2
- Operating system version/name: LibreElec 9.X
- Device model:  RPI4B

Used Operating system:
 Raspberry-Pi

### Describe the bug
Since yesterday if I try to play anything from netflix. The player will start to load and then instantly crashes.

#### Expected behavior
Well it should play the movie.

#### Actual behavior
The player will start to load and then instantly crashes

#### Steps to reproduce the behavior
1. Load any movie from netflix

### Debug log
https://paste.kodi.tv/axulizaned.kodi

**Comment by Thunderbird2086** [comment]
Same for 1.12.4
