### ISSUE TITLE
Fix name in daily build

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#116]
Last filename is plugin.video.netflix_0.14.**3**_20190623 - should be plugin.video.netflix_0.14.**5**_20190623

**Comment by Smeulf** [comment]
@notoco I must have miss something... Where are those daily built?

**Comment by CastagnaIT** [comment]
thanks yesterday i was really tired...

**Comment by Smeulf** [comment]
You should develop something to build it for you :D
