### ISSUE TITLE
Issue generating NFAuthenticaiton key

### ISSUE THREAD

**Issue by Nadonate** [CastagnaIT/plugin.video.netflix#1160]
## Bug report

When generating the NFAuthenticaitonk key using the script, I get a `unable to connect with the browser` 

#### Your Environment
- Netflix add-on version: **N/A**
- Operating system version/name: **Ubuntu 20**
- Device model:  **N/A**

Used Operating system:
* [ ] Android
* [ ] iOS
* [**X**] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Using the NFAuthentication.py script to generate a key, I get: `Browser startup... (/usr/bin/brave-browser) please wait` _than_ `Establish connection with the browser... please wait` _than_ `Unable to connect with the browser`

The prereqs are satisfied:
-Brave Browser (_/usr/bin/brave-browser_)
-pycryptodomex
-websocket-client
-python3

#### Expected behavior

NFAuthentication key would be generated

#### Actual behavior

No key is generated, error is thrown

#### Steps to reproduce the behavior

1. Download and unzip NFAuthenticationKey_Linux.zip
2. PIP3 Install prereqs
3. execute NFAuthenticationKey.py

#### Possible fix

Possibly a websocket issue?

### Debug log
 no logging built into py script
The debug log can be found here:

**Comment by CastagnaIT** [comment]
have you modified the .py file?
if yes, download it again and try run the py file without modify it

after run the py file, the browser will be automatically opened or not?

**Comment by Nadonate** [comment]
Ok, sorry for the wait...

_have you modified the .py file?_ - Yes, to insert path to browser
_after run the py file, the browser will be automatically opened or not?_ - No

I redownloaded the NFAuthenticationKey.zip and tried to run the script _unmodified_ with the same error resulting.

**Comment by Nadonate** [comment]
I figured out the problem... it was my fault. I was using an SSH terminal, which wouldn't launch the broswer on the PC.

Eerything works as expected when using a local terminal.

Thanks for your help @CastagnaIT & thank you for the great addon!
