### ISSUE TITLE
Force Kodi to select Norwegian, Norwegian Bokmål, Norwegian Nynorsk language regardless of the current norwegian language code

### ISSUE THREAD

**Issue by CastagnaIT** [CastagnaIT/plugin.video.netflix#1161]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

This FR Issue is requested from a forum Kodi user:
https://forum.kodi.tv/showthread.php?tid=329767&pid=3020257#pid3020257
https://forum.kodi.tv/showthread.php?tid=329767&pid=3036883#pid3036883

Kodi make a distinction for Norwegian languages codes:
`no` (Norwegian)
`nb` (Norwegian Bokmål)
`nn` (Norwegian Nynorsk)

Then if you set one of these (on audio or subtitles) e.g. `nb`, and a video has only `no` streams will fallback to the original (audio or subtitles) language, this is right behaviour but a Norwegian user wish to fallback to `no` streams or `nn`

The user has requested force change all language code of the streams, in to the current norwegian language code selected on kodi 
this will trick kodi to select the other norwegian language code available

#### Describe the use case

Play a video with norwegian streams regardless of the language codes

#### Development tips

(Suggested by the user)
```python
def _fix_norwegian(data_list):
    kodi_subtitle_lang = get_kodi_subtitle_language()
    if kodi_subtitle_lang in ["no", "nb", "nn"]:
        for item in data_list:
            if item.get('isNoneTrack', False):
                continue
            if item['language'] in ["no", "nb", "nn"]:
                item['language'] = kodi_subtitle_lang
```

**Comment by CastagnaIT** [comment]
The proposed code change if functional, but i do not like too much, in this ways the language descriptions are mixed
and there are other things to check to prevent other problems:
- Is the "nn" (Norwegian Nynorsk) language used on some videos? If not used is not needed
- There may be videos with both `no `and `nb `languages?

I think any language inclination should respect the correct names other users might be against this

**Comment by boirello** [comment]
- I have never seen "nn" been used anywhere, exept _maybe_ in norwegian streaming services. So it could be ignored.
- All videos on Netflix I have checked seems to use the "nb" code for subtitles. And all videos on Disney+ seems to use the "no" code for subtitles. The normal thing is to use the "no" code - "nb" and "nn" is like an internal thing only used within Norway.
- I have not checked the audio streams, but it is highly likely that Netflix/Disney+ uses the same codes for audio as they uses for subtitles.

There is no difference between "no" and "nb" - it is the same language. It is funny that you only have "English" in the language list to choose from, although "gb", "us", "au" and "nz" all are similar, but not identical. But "no" and "nb" is the same - yet we have to choose one of these as prefered language.

Your suggestion about a fallback system would not be needed if Kodi could let us select more than one prefered subtitle language. Then I could select both "Norwegian" and "Norwegian Bokmaal", similar to the settings for downloading subtitles that says "Languages to download subtitles for".

For now, I suggest you just transforming all "nb" codes to "no" as a simple solution.

**Comment by CastagnaIT** [comment]
I will enforce language code change only as last resort if any other solution not works,
the current one (fix_locale_languages) where you have take ispiration, has been introduced only to overcome a problem where Kodi does not support country codes.

> Your suggestion about a fallback system would not be needed if Kodi could let us select more than one prefered subtitle language. 

this could be another good way to solve the problem, i will take in consideration

> I have not checked the audio streams, but it is highly likely that Netflix/Disney+ uses the same codes for audio as they uses for subtitles.

usually old local video productions, have local audio language,
you could check if some old Norwegian videos sitcom films etc have the Norwegian audio stream
I have noticed that often in the "recentrly added" menu there are old time films,
or you can use in the addon "Search by audio/subtitles language" but i do not know if will be listed all language possibilities
let me know if you will find something

**Comment by Essam311** [comment]
@CastagnaIT This might help.

https://github.com/asciidisco/plugin.video.netflix/issues/580#issuecomment-453848905

**Comment by boirello** [comment]
It seems like Netflix does not have any old norwegian movies or tv series. So I checked 3 newer movies, and they all had "nb" as audio language.

By the way: One of the movies also had subtitles for both "forced" and "captions", where the forced one where selected by default. Both in language "Bokmaal, Norwegian", which is "nb", and I also had Kodi setting for preferred language set to "Norwegian Bokmaal". This behaviour (where forced is the default one) is not the desired behaviour for me as I am hard of hearing and wants everything texted. That is why disabling forced subtitles completely within the plugin is a feature I would like to have.

**Comment by Essam311** [comment]
@CastagnaIT I can confirm this, tested on Kodi Leia and Matrix with the movie Bright, I selected English as my preferred language for the subtitles, if the video has only forced subtitle and closed captions for a language Kodi will select the forced subtitle, if the video has regular subtitle, forced subtitle and closed captions Kodi will choose the regular subtitles like the English subtitles in "Money Heist".

![sub11](https://user-images.githubusercontent.com/59211054/118872420-d925f900-b8e8-11eb-8edb-dff7319fbe73.png)


@boirello You could fix this problem for you by in the settings choose Player and in Accessibility choose "Prefer subtitles for the hearing impaired" and Kodi will choose the "captions" always.

![subs](https://user-images.githubusercontent.com/59211054/118870239-9b27d580-b8e6-11eb-9510-814e1bdb8c23.png)

**Comment by boirello** [comment]
@Essam311 I rather not set "Prefer subtitle for the hearing impaired" to enabled - I guess this will select the captions over regular subtitle in your example "Money Heist". And since I am hard of hearing, not deaf, I don't need the irritating "[twig breaks]" or something like that. I guess that is what captions is. I just want the dialog texted, that's it. ;)

But anyway, this is a major off-track, and the issue with forced subtitles is easily fixed by editing the code my self when needed (after updates). And it also seems only to happen when subtitles and audio is the same language, and this language is your preferred subtitle language. In other words: It only happens when I see a norwegian movie/show, which I rarely do.

**Regarding the issue with "nb" and "no", I don't see any other options than:**
1. Either just transform "nb" code to "no" code (or do as I have in my code suggestion).
2. Or add a settings that can override which subtitle language code you want selected as default. Could be combined with some sort of fallback system, like allowing the user to enter more than one language code: "no,nb,en". In this case: If neither "no" and "nb" exists, the "en" should be selected as default.
3. Or wait for Kodi to eventually allow us to select more than one preferred subtitle language (Kodi 20 or something, which is a forever).
4. Or use a third-party addon to fix this, if it's possible (rather not).

**Comment by CastagnaIT** [comment]
i have also tried so i confirm currently there is no way to fallback with the subtitles
and implement a handled fallback via code it's too demanding 
i have choose the code proposed, slightly modified, as way of convert the macrolanguage codes to his primary lang code

now only the macrolanguages "nb"/"nn" are converted to the primary "no" only if not already present
this to avoid possible duplicate lang code problems

I'm thinking if other languages might have this need as well
then i have implemented in an extensible way

You can try by updating:
[plugin.video.netflix_1.15.1+matrix.1_20210522_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6526441/plugin.video.netflix_1.15.1%2Bmatrix.1_20210522_t1.zip)
and set the "no" as kodi subtitles language

**Comment by boirello** [comment]
I am currently on Kodi 18 (Leia), but planning to upgrade to 19 (Matrix). It is on my TODO-list (just not yet). So I cant test the code changes right now.

**Comment by Essam311** [comment]
@CastagnaIT I tested with some shows with Norwegian subtitles on Kodi 19.1 and it seems to work fine, here is a screenshot with the TV show Norsemen.


![sub33](https://user-images.githubusercontent.com/59211054/119237778-ea684300-bb3e-11eb-9f68-e10c7df4099b.png)

**Comment by Essam311** [comment]
@boirello You could use this portable Kodi 19.1 for the testing, I installed the Netflix plugin https://github.com/CastagnaIT/plugin.video.netflix/files/6526441/plugin.video.netflix_1.15.1%2Bmatrix.1_20210522_t1.zip on it, just put the folder Kodi.19.1.Portable in the C drive C:\Kodi.19.1.Portable and run the shortcut kodi.exe  C:\Kodi.19.1.Portable\kodi.exe, it will not affect your Kodi 18.9, it stores the installed add-ons in C:\Kodi.19.1.Portable\Kodi\portable_data\addons.

https://github.com/Essam311/plugin.video.netflix/raw/test/tests/Kodi.19.1.Portable.rar

**Comment by CastagnaIT** [comment]
I'm sorry but the addon version for Kodi 18 will no longer receive any changes or new features,
will receive maintenance fixes only in order to keep it working

I will keep this issue opened until you can give feedback or others as well

**Comment by Essam3111** [comment]
@CastagnaIT I added the Norwegian language in my account for the audio and subtitles.

![11](https://user-images.githubusercontent.com/84876906/119728282-91b4e500-be73-11eb-9a9e-27156a8b4838.png)

and selected the Norwegian language as my preferred language for the audio and subtitles in Kodi.

![22](https://user-images.githubusercontent.com/84876906/119728470-cfb20900-be73-11eb-9cb7-2512cfaccf13.png)

I installed https://github.com/CastagnaIT/plugin.video.netflix/files/6526441/plugin.video.netflix_1.15.1%2Bmatrix.1_20210522_t1.zip on Kodi 19.1 and played the Norwegian movie "Cadaver", the Norwegian language has been selected for the audio and the subtitle by default, I think its safe to say that your PR is working as it should be.

https://www.netflix.com/title/81203335

![55](https://user-images.githubusercontent.com/84876906/119729024-70a0c400-be74-11eb-9762-fdd306d09ac9.png)


![66](https://user-images.githubusercontent.com/84876906/119729045-7696a500-be74-11eb-95c8-c81fad2d5a1e.png)

**Comment by CastagnaIT** [comment]
Thanks for the feedback, i think the current changes are fine,
please let me know if you prefer these changes to be included in the next release (that will be released on next days - Kodi19)
or you prefer to wait

**Comment by boirello** [comment]
It seems like I have to stay on Kodi 18 for a while since my preferred skin (Transparency!) is not supported on Matrix:
https://forum.kodi.tv/showthread.php?tid=360613

But if you're asking me (about releasing these changes), I would say "go for it", but no stress really since I won't be running Kodi 19 in the nearest future.

**Comment by CastagnaIT** [comment]
usually the Kodi addons have a free source code, if someone else is willing to update the Skin code
surely the skin will work on new Kodi versions as well

often Kodi addons projects are developed by just 1 or 2 people,
unfortunately few people have the time and patience to study how kodi works and help to keep update the things,
so it is easy for projects to die sooner or later...

ok then i will merge the changes

**Comment by CastagnaIT** [comment]
Issue closed, FR implemented in the new release
