### ISSUE TITLE
Installing instructions for OSMC with Kodi 19

### ISSUE THREAD

**Issue by ant9000** [CastagnaIT/plugin.video.netflix#1162]
The latest Widevine update broke playback on OSMC with Kodi Leia (on a RaspberryPi 3B+).

Given you are dropping support for Leia, I decided it was time to upgrade my OSMC to Kodi 19 following https://discourse.osmc.tv/t/testing-kodi-v19-builds-for-raspberry-pi-2-3-4/89152. 

I followed the wiki page but to no avail - until I realized that while Kodi Matrix uses python3, the system default version is still python2. Doh...

For any OS which still defaults to python 2 (Debian Buster and derivatives for sure, maybe others), the wiki instructions for Kodi 19 need to be amended as follows:

```
sudo apt-get update
sudo apt-get install build-essential python3-pip python3-crypto libnss3
sudo pip3 install -U setuptools
sudo pip3 install pycryptodomex
```

Thanks a lot for your work!

Antonio

**Comment by CastagnaIT** [comment]
thanks i update it

**Comment by ant9000** [comment]
I'll do my best in the next few days (during the weekend, likely). I'm quite sure you could get rid of python3-crypto, but not so much about the rest.
For instance, now I'm checking a different system and python3-wheel is recommended by python3-pip, but not necessarily installed; and I see no wheel for pycryptodomex, which makes build-essential necessary (I did have to build it, in fact).

**Comment by zjoasan** [comment]
Just thought I'd chim in, the Netflix-system-prep script on OSMC forums, now checks for Leia  or Matrix, and installs the right pip, etc for the needed python version.

**Comment by CastagnaIT** [comment]
I applied the suggested changes
interesting the OSMC script
it might be an idea to have a unified script for all systems OSMC-raspbian-retropie-linux
