### ISSUE TITLE
No sound but video is working

### ISSUE THREAD

**Issue by wibenjamin** [CastagnaIT/plugin.video.netflix#1163]
#### Your Environment
- Netflix add-on version: <1.12.4>
- Operating system version/name: <LibreElec 9.2>
- Device model:  <Raspberry Pi 4>

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

Video does playback with no issues but there is no sound. When Playback is stoped there is the error message "AMplayback disabled due to exception u'percentage'

#### Expected behavior

Video does playback with sound

#### Actual behavior

No sound and error message

#### Steps to reproduce the behavior

1. Play video
2. No Sound 
3. Error message

### Debug log

The debug log can be found here:
https://paste.kodi.tv/orovawufas

**Comment by CastagnaIT** [comment]
the percentage exception error is not related to your problem
i have no idea whats do not works in your system
but it is quite difficult that this depends from the addon..

**Comment by wibenjamin** [comment]
Thanks a lot for taking your time and having a look into it, the problem was sitting in front of the screen...

It seems at some point I made a wrong setting in the InputStream Adaptive plugin at the item "Media", it was set to "Video" (not quite shure about that) after setting it to "All" sound came back and this issue can be considered closed I guess, Netflix Playback is working flawless again as usual. Thank you by the way for this great work of yours and all the contributers to this project!

So everybody who has the same troubles:

- Set InputStream Adaptive plugin to standard settings 
- Profit!
