### ISSUE TITLE
Previously Watched if logging in through VPN

### ISSUE THREAD

**Issue by wdmlist** [CastagnaIT/plugin.video.netflix#1178]
So from time to time I forget to turn off the VPN and its directed at a different region. When that happens most of all of the titles in the previously watched disappear, and when I do reset Kodi and re-login to without the VPN the titles become no longer playable and or disappear entirely from the app.

Is there any way to reset the cache or database so that we can re-watch or am I reinstalling the addon?

**Comment by CastagnaIT** [comment]
maybe it could help try to go to addon Expert settings and do the "Clean cache on memory and disk"

i'm sorry but we not provide support for side effects caused by this types of connections
https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy
