### ISSUE TITLE
Search fails with DBSQLite error

### ISSUE THREAD

**Issue by aerans** [CastagnaIT/plugin.video.netflix#1186]
#### Your Environment
- Netflix add-on version: 1.12.4
- Operating system version/name: OSMC Kodi 18.9
- Device model:  Vero 4 +

Used Operating system:

* [ ] Linux

### Describe the bug

Everything works except I can't use the search feature. It shows a DBSQLite error.

#### Expected behavior

Should be able to search programs on Netflix.

#### Actual behavior

Error message

#### Steps to reproduce the behavior

1. Select search
2. Database error message shows
3.

### Debug log

The debug log can be found here:

https://paste.kodi.tv/ubequqijif.kodi

#### Screenshots

![PXL_20210609_112914181](https://user-images.githubusercontent.com/35411109/121347584-b5475780-c96a-11eb-8c7e-31323ea0334d.jpg)

**Comment by jakermx** [comment]
please provide the full log file with verbose debug option enable on the Addon Expert section....

**Comment by CastagnaIT** [comment]
this is a problem carried over from the old versions or rollbacks
the only way is full uninstall the add-on and also user data when prompted
the install it again last version

**Comment by aerans** [comment]
That worked. Thanks!!
