### ISSUE TITLE
Authentication key from network share

### ISSUE THREAD

**Issue by CiNcH83** [CastagnaIT/plugin.video.netflix#1187]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request
Can you change the _Authentication key_ browser in a way that the key can be fetched from a network share? I think it is just a matter of calling a different browser from Kodi (like the one in Kodi's _File manager_).

#### Screenshots
Authentication key browser:
![image](https://user-images.githubusercontent.com/24539361/121642169-71e70900-ca90-11eb-8537-d8d1b8b81e33.png)

_File manager_ browser:
![image](https://user-images.githubusercontent.com/24539361/121642134-64ca1a00-ca90-11eb-8086-09b766ef8d8e.png)

**Comment by CastagnaIT** [comment]
yes no problem

**Comment by CastagnaIT** [comment]
Done
