### ISSUE TITLE
Search for "Netflix" crashes Kodi

### ISSUE THREAD

**Issue by clement-analogue** [CastagnaIT/plugin.video.netflix#1189]
#### Your Environment
- Netflix add-on version: v1.16.0+matrix.1
- Operating system version/name: LibreElec 9.95.4
- Device model:  Pine64 ROCKPro64

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I installed repository.castagnait-1.0.0.zip.
After this, when I search for "netflix", Kodi crashes. It cannot be restarted. I need to reboot the ROCKPro64.
If I search another term, it's working fine. Searching "netflix" before installing repository.castagnait-1.0.0.zip was working.

#### Expected behavior

Search will return results associated to the query

#### Actual behavior

Kodi crashes and cannot be relaunch. A reboot is needed.

#### Steps to reproduce the behavior

1. Install repository.castagnait-1.0.0.zip
2. Search "netflix"

### Debug log

The debug log can be found here:

https://paste.kodi.tv/zoliwudiju.kodi

**Comment by jakermx** [comment]
@clement-analogue Once the repository is installed, you need to install the Add On from the new installed repository

**Comment by clement-analogue** [comment]
Afterward, I installed the plugin by browsing the repo.
The issue is really that a search returning an addon from this repo will make Kodi crash for some obscure reason.

**Comment by jakermx** [comment]
I think you may open a ticket on kodi(xbmc)  or Libreelec, caus, it is not this addOn Realted.

Glad to hear that you installled it.
