### ISSUE TITLE
Missing episodes on seasons with long episodes lists

### ISSUE THREAD

**Issue by CastagnaIT** [CastagnaIT/plugin.video.netflix#1190]
#### Your Environment
- Netflix add-on version: 1.12.4 and 1.16.0
- Operating system version/name: Windows / LibreELEC
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

In tvshow's with long list of episodes only the first ~44 are shown

#### Steps to reproduce the behavior

1. Open "La reina del flow" tvshow
2. Open season 1
3. See missing episodes

#### Possible fix

need some investigation to see if it is not a problem of current implementation
or need to do new changes

### Debug log

The debug log can be found here:

Tested by myself
issue reported by a forum user:
https://forum.kodi.tv/showthread.php?tid=329767&pid=3043766#pid3043766

**Comment by Essam3115** [comment]
This was a very old problem in 0.13.XX versions I used to fix it with a workaround by replacing 40 with 200 here.

https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/NetflixSession.py#L1607

"caphm" fixed it here.

https://github.com/CastagnaIT/plugin.video.netflix/commit/25cc155f05495cef5af51a700b12a962c90902de

https://github.com/CastagnaIT/plugin.video.netflix/commit/98b8897db8911d465c7d0fa175bb2462bb9fbed0

This problem is now in Leia too, most likely it caused by changes from Netflix.

**Comment by CastagnaIT** [comment]
the "perpetual" requests is already implemented (derived and improved from caphm work)
but it is not the right way make a single requests for 200 objects or more,
easily will exceed the data limit set by netflix shakti API
the problem must be analysed in current code to understand where the obstacle is

**Comment by Essam3115** [comment]
I know that replacing 40 with 200 is not the right thing to do, I just was trying to inform you that this is an old problem lasted for a long time and we had to use a workaround to fix it, until "caphm" fixed it, I posted the old commits from "caphm" so you might find in them something useful for the origin of this problem.

**Comment by CastagnaIT** [comment]
can you give a try to see if works?
[plugin.video.netflix_1.16.0+matrix.1_20210618_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6676944/plugin.video.netflix_1.16.0%2Bmatrix.1_20210618_t1.zip)

this affect not only season episodes but also submenus lists of:
![immagine](https://user-images.githubusercontent.com/3257156/122559509-bac63100-d03f-11eb-998f-058b55224c5d.png)
try to see if there are all titles listed on some of these

**Comment by Essam31115** [comment]
I tested with "Fullmetal alchemist" it has 51 episodes and "Pablo Escobar el patrón del mal" has 72 episodes and all the episodes are available, and all the movies and TV shows seems to be available in the submenus lists as they are in Netflix site using Firefox.

![11](https://user-images.githubusercontent.com/86118997/122584404-9c216380-d05a-11eb-8c67-5839e150a980.png)


![22](https://user-images.githubusercontent.com/86118997/122584450-a8a5bc00-d05a-11eb-86b2-688a87c7c054.png)

**Comment by CastagnaIT** [comment]
very fast thank you
