### ISSUE TITLE
Hang und restart Kodi after stop a movie in version 1.16.1

### ISSUE THREAD

**Issue by TBSemiotikLE** [CastagnaIT/plugin.video.netflix#1197]
LibreElec Beta 5 and the Netflix addon with version 1.16.1 causes LibreElec to hang when you want to stop the film and the Kodi ends and restarts (x_86) With version 1.15.1 the problem does not exist and everything runs normally

**Comment by CastagnaIT** [comment]
this is a know issue that affect LibreElec/CoreElec not depends from the addon version
