### ISSUE TITLE
Netflix Catalogues & Local library

### ISSUE THREAD

**Issue by rijsab** [CastagnaIT/plugin.video.netflix#1199]
## Feature request
I'm submitting a proposal to ...
  - [X ] new feature
  - [ ] change an existing feature

### Describe your request

What TMDBhelper addon is doing is play local files first instead of files from an addon.

Is it possible to implement an option to prefer the local library as play option instead of Netflix addon. If not found in local Library it should fall back to Netflix addon to play. 

#### Specific details

Please see TMDBhelper from Jurialmunkey how the local library is being used as priority over addon play.

**Comment by CastagnaIT** [comment]
what you describe sounds like a hack
and i don't like adding strange behaviour on playback callback
it is already complex to maintain this project as it is now
