### ISSUE TITLE
Error entering Exported folder

### ISSUE THREAD

**Issue by helviojr** [CastagnaIT/plugin.video.netflix#12]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

Error when you try to enter "Exported" folder, wrong number of arguments passed to function build vídeo_listing.

### Addon version used

13.21 (daily?) (current master branch)

### Description

When you try to open "Exported" folder, Kodi throw this add-on error:
Type Error: build_video_listing() takes exactly 2 arguments (1 given)
As far as I could get, the problem is in "resources/lib/navigation/directory.py", line 132, where the function is called with only one argument:
126:    def exported(self, pathitems=None):
...
130:        if library_contents:
131:            listings.build_video_listing(
132:                **api.custom_video_list(library_contents))**

### Steps to Reproduce

1. Just installed the add-on
2. Entered plugin and entered credentials
3. Entered settings and chose "Perform total sync now"
4. Tried to enter "Exported" folder (all others lists without problem)

**Expected behavior:** List the items exported

**Actual behavior:** Kodi add-on error

## Context (Environment)

Windows 10.0.17134.590, Leia 18.0 (20/01/2019)

### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [X] I'm using a different source (Please tell which)
Cloned 'master' repository

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Windows 10.0.17134.590, Leia 18.0 (20/01/2019)

## Other information

Include the 2nd parameter in the call of function build_video_listing(), inside function exported, line 132 of directory.py

### Screenshots

![image](https://user-images.githubusercontent.com/30601040/53755982-b9849080-3e96-11e9-87de-39dbc0bd6d5e.png)

**Comment by helviojr** [comment]
Solved changing line 132 to:
`api.custom_video_list(library_contents), g.MAIN_MENU_ITEMS['exported'])`

I imagine you don't need a PR for that, right? If you do, please tell me.

**Comment by CastagnaIT** [comment]
thank you my oversight after many hours of testing i was particularly tired
