### ISSUE TITLE
Confirmed fully functional on Chromecast with Google TV

### ISSUE THREAD

**Issue by cromefire** [CastagnaIT/plugin.video.netflix#1207]
Just tested the Addon on my "Chromecast with Google TV" (Android 10) and it's fully functional, I can watch Dolby Vision in 4K without any problems. Didn't test 1080p, HDR10 and Atmos, but as Dolby Vision with 4K and DD+ is pretty much the highest level, I assume it's working too, can test it though if you name a sample. The wiki stated to include a debug log, but as everything is working well I've skipped that.

**Comment by cromefire** [comment]
There's no template for "everything's fine".

**Comment by CastagnaIT** [comment]
hi thank you for the report
i think that if Dolby Vision work should works also HDR
Atmos is not a problem because it's a subtype of DD+
i will add in wiki

**Comment by CastagnaIT** [comment]
a question is working the switch fps/hz?
e.g. played 23fps video screen switch to 23hz
played 50fps video screen switch to 50hz ...

**Comment by cromefire** [comment]
No it doesn't seem to, at least my TV still shows it at 60Hz and Kodi doesn't show options for it. Looks fine though, no stutter or screen tearing and the Frame insertion also seems fine.

**Comment by cromefire** [comment]
Might be just the TV tough

**Comment by CastagnaIT** [comment]
from Chromecast display options there are the possibility to change the refresh hz?

**Comment by cromefire** [comment]
Yes

**Comment by cromefire** [comment]
Okay, just confirmed Atmos is working too.

**Comment by CastagnaIT** [comment]
i was suspecting, i think that for android 10 need to be implemented
this: https://github.com/CastagnaIT/libandroidjni/commit/38eed3c7b13b96ff0d31a519be1da4664be76a64
and related kodi changes,
that devs has put in stand the feature because had no way of testing the changes

**Comment by cromefire** [comment]
Well... I do have a test device...

**Comment by CastagnaIT** [comment]
its good,
but to ask to try implement
you have to open an Issue on Kodi github
i am not equipped for android kodi builds

**Comment by cromefire** [comment]
Well I could probably open an issue if there isn't already one, but I'm equally unequipped of fixing that problem.

**Comment by CastagnaIT** [comment]
i wrong remember sorry, that API i have linked before is for android 11 or above...

is possible that there is other kodi problems, or resolution/refresh change on Chromecast for some reason is not supported by kodi

**Comment by cromefire** [comment]
By the way HDR10+ should also work on the Chromecast, but I'm not sure if Netflix even has HDR10+ content.

**Comment by CastagnaIT** [comment]
FWIK netflix has choose Dolby Vision instead of HDR10+ that is better
maybe in future...

**Comment by cromefire** [comment]
Yeah I mean I haven't checked every single pice of content, might be that they have both or so like Amazon.
