### ISSUE TITLE
WaitTimeError pops up

### ISSUE THREAD

**Issue by kodiuser-xiii** [CastagnaIT/plugin.video.netflix#1208]
#### Your Environment
- Netflix add-on version: 1.16.2+matrix.1
- Operating system version/name: Windows 10
- Device model: N/A

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ X] Windows

### Describe the bug
A pop window displays stating WaitTimeError. I have tried find a solution about this on the FAQ but had no luck finding anything. Its hard to say when this pop up occurs as it is very intermittent. At times this error shows when I am trying to play a Netflix show through TMDB helper player or when the system is in idle.

#### Expected behavior

No pop up should display

#### Actual behavior

WaitTimeError pop up appears

#### Steps to reproduce the behavior
As stated its hard to provide the exact steps as this error pops up when Kodi is on idle.

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6942690/kodi.log)

### Additional context or screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/70888472/128448980-55c40f0c-5427-44cc-8ff5-d2723dcedee5.png)

#### Other information
N/A

#### Screenshots
As above

**Comment by CastagnaIT** [comment]
is possible that you are using a skin with widgets?
if this is the case:
the widgets cause problems with this addon: https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits

in this case the only solution is, try enable IPC over HTTP in addon Expert settings 
but is a workaround that can lead to other service breakage or unexpected problems

or else remove widgets or if skin allow do less widget update like e.g. only at kodi startup

**Comment by hoge6b01** [comment]
in my logs I see the installation wants to curl https://github.com/CastagnaIT/repository.castagnait/raw/master/zip/plugin.video.netflix/plugin.video.netflix-1.12.6.zip and gets an 404. That's proprably because the file does not exist. Any error in an URL?
After that it failed to download special://home/addons/packages/plugin.video.netflix-1.12.6.zip. Which seems to have the cause in the above.
Hope I didn't break any forum rules.

**Comment by CastagnaIT** [comment]
you have installed the netflix repository for Leia(Kodi 18) on your Matrix (Kodi 19)

you have to uninstall the wrong repository from Kodi , and install the good one by downloading it from Github Readme

**Comment by hoge6b01** [comment]
Unfortunately not. I'm using the 1.0.1 Repository for Kodi 18.x (Leia) on my Kodi 18.7 installation.

**Comment by CastagnaIT** [comment]
ah sorry
I thought you were the user who opened this thread
then try install from repo again

**Comment by hoge6b01** [comment]
Now it works! Thanks!

**Comment by kodiuser-xiii** [comment]
> is possible that you are using a skin with widgets?

Yes, I am using Artic Zephyr-Reloaded skin which permits widgets. I used widgets to showcase the meta in Netflix addon. This made it easier to review meta items via the widgets rather then  going through each individual label in the addon.

> if this is the case:
> the widgets cause problems with this addon: https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits
Thanks for sharing this, I have deactivated all widgets linked to the Netflix and that seemed to work. Shame widgets are not compatible with the addon :(

> in this case the only solution is, try enable IPC over HTTP in addon Expert settings
I tried this but this would pop up the 'TimeOutError'.

**Comment by CastagnaIT** [comment]
> Thanks for sharing this, I have deactivated all widgets linked to the Netflix and that seemed to work. Shame widgets are not compatible with the addon :(

the main problem is that no skin developer is willing to collaborate to provide a solution to allow addons to identify widgets calls,
widgets still force access to the addon without permission in any time and this leads to many problems...
