### ISSUE TITLE
kodi 19.x on python 3 wokring ?

### ISSUE THREAD

**Issue by amidevous** [CastagnaIT/plugin.video.netflix#1209]
kodi 19.x on python 3 wokring ?

**Comment by amidevous** [comment]
but there is no need for the details to ask to ask this simple question

i just want to know if the module is compatible with kodi 19 which works in python 3 and not in python 2

to know if I can update to the 19 or if I have to stay on the 18

and if he fakes the 18 when it will be compatible with the 19 if possible

the other modules i use have all been ported for compatibility with phyton 2 and python 3 which makes them 18 and 19 compatible i want to know if this is the case or if not when is what will be expected

**Comment by notoco** [comment]
Just read readme...
https://github.com/CastagnaIT/plugin.video.netflix
