### ISSUE TITLE
"result" Error while trying to Play episode or movie

### ISSUE THREAD

**Issue by Thenin2** [CastagnaIT/plugin.video.netflix#121]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

Latest release from repository (0.14.6)

### Description

Video playback does not work. Popup with error "result".
KeyError: u'result' in Logfile found.

### Steps to Reproduce
1. Log in
2. Choose Profile
3. Try to Play something

### Installation

* [x ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Libreeelec Milhouse 9.1 Build 621

## Debug log

http://ix.io/1Nr6

**Comment by CastagnaIT** [comment]
I need more informations,
please try to install this test and put a new debug log
[plugin.video.netflix_TEST1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3351735/plugin.video.netflix_TEST1.zip)

**Comment by Thenin2** [comment]
Here is the new logfile with your test plugin:

http://ix.io/1NBP

**Comment by CastagnaIT** [comment]
Ther error detail is: Email or password is incorrect

but something doesn't work in the python libraries of your librelec,
could be the main cause that does not make the addon work properly

I suggest you to use Kodi 18 stable version not 19 alpha

**Comment by Thenin2** [comment]
Hello,

i downgraded to Kodi 18.2rc1 with milhouse 9.1 Build 415 and the error persists.

**Comment by jakermx** [comment]
2019-07-01 20:10:36.627 T:140117972858624    INFO: [plugin.video.netflix (0)] Initialized new session
2019-07-01 20:10:36.629 T:140117972858624    INFO: [plugin.video.netflix (0)] Login prefetch: No stored credentials are available

2019-07-01 20:12:33.695 T:140117972858624   DEBUG: [plugin.video.netflix (0)] Failed to load stored cookies: MissingCredentialsError

Looks that your are carrying old version files and cookies.


I would suggest to remove the add and settings as well, uninstall it and check that /sotrage/.kodi/userdata/addon_data/plugin.video.netflix does NOT exists alsodelete request, response and challange files on /storage/.kodi/cdm/

then, reboot your LE, remove the Netflix Repository(Vrey Important) and then install from zip and reboot and finally, try again.

**Comment by jakermx** [comment]
The issue is when usinng this kind of ESN

NFCDCH-LX-FJTJ6H3KV34X4YJA6A72H6LXFNA1QF


Change LX to 01

NFCDCH-01-FJTJ6H3KV34X4YJA6A72H6LXFNA1QF

It should  work

**Comment by jakermx** [comment]
Manifest is being requested fine, but the issue is when requesting a license, it uses a challenge and the esn, the undecoded challenge includes the requested User Agent and Widevine version, something likes this:

architecture_namearm
company_nameGoogle

model_name	ChromeCDM

platform_nameChromeOS"
widevine_cdm_version
1.4.9.10882 ,

Your ESN flavour should match the arch. company. model, platform,version, etc on requested user-agent, if not,it will fail

**Comment by Thenin2** [comment]
I did a clean installation. It is now Librelec 9.0.2 Stable Branch. 
After Installing the Plugin from your Repository i got the same error. Even changing the ESN did not work

**Comment by Thenin2** [comment]
Ok now it works. I uninstalled the repo and the addon, made sure that there are no files left (no files were left) and installed a daily build (plugin.video.netflix_0.14.5_20190624.zip) manually.

**Comment by Smeulf** [comment]
@Thenin2 means you reverted to 0.14.5 instead of 0.14.6...

@CastagnaIT I feel there's something in https://github.com/CastagnaIT/plugin.video.netflix/commit/388fd74b82dd5439271afc947cd6bb465bb22e56 that might cause the issue, but I may be wrong ^^

**Comment by Smeulf** [comment]
@Thenin2 would you get a try on the latest daily build to see if the error come back or not? http://www.mediafire.com/file/c05qz9je1dlr655/plugin.video.netflix_0.14.6_20190708.zip/file

You still can revert to 0.14.5_20190624 if it don't works...

**Comment by CastagnaIT** [comment]
i think the latest daily build works correctly, try as Smeulf suggested

**Comment by Thenin2** [comment]
Hey, sry that answer took so long, i was on vacation..... i just tried Smeulfs suggestion and it works fine
