### ISSUE TITLE
There is a missing step in the installation instructions for OSMC

### ISSUE THREAD

**Issue by josemata00** [CastagnaIT/plugin.video.netflix#1210]
First of all, grateful for your work. I have found a missing step in the OSMC installation instructions, it is the following:

FOR KODI 19 MATRIX:
sudo apt-get update
sudo apt-get install build-essential python3-pip python3-crypto libnss3

***sudo pip3 install setuptools*** Since otherwise pycryptodomex is not installed

sudo pip3 install pycryptodomex

**Comment by CastagnaIT** [comment]
from pycryptodomex setup code it not require setuptools, can use python embedded distutils
can you show the error log?

**Comment by CastagnaIT** [comment]
whats python version?

**Comment by CastagnaIT** [comment]
yes
then open the terminal (or shell) for OSMC
and type `python --version`

**Comment by CastagnaIT** [comment]
and you are using OSMC with Matrix version?
please type aso `python3 --version`

**Comment by josemata00** [comment]
Currently it works perfect, but I give you a little trick that I have used, and I would like if you can add it (for the sake of all users) ... I used the DIsney + add-on from http://k.slyguy.xyz to install Widevine WITHOUT complications or errors of any kind (Raspberry PI4 8GB. Same in OSMC, as in RetroPie + Kodi addon)

**Comment by josemata00** [comment]
> and you are using OSMC with Matrix version?
> please type aso `python3 --version`
 3.7.3

Do you want me to provide Team Viewer for you to review directly?

**Comment by CastagnaIT** [comment]
it's strange that OSMC have two python enviroments (version 2 and 3) at same time, maybe this is the cause of the problem
i will add your tip

> to install Widevine WITHOUT complications 

the only and _official way_ to install Widevine on Kodi, is to use `InputStream Helper` addon
this addon is often a dependency of other addons like this, that use it to automatically check/install/update Widevine "without" other user interactions

**Comment by josemata00** [comment]
> it's strange that OSMC have two python enviroments (version 2 and 3) at same time, maybe this is the cause of the problem
> i will add your tip
> 
> > to install Widevine WITHOUT complications
> 
> the only and _official way_ to install Widevine on Kodi, is to use `InputStream Helper` addon
> this addon is often a dependency of other addons like this, that use it to automatically check/install/update Widevine "without" other user interactions

Ok. Thanks!

**Comment by CastagnaIT** [comment]
thanks for the details
