### ISSUE TITLE
Adding clearart and year to generated nfo

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#1212]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [X] change an existing feature

### Describe your request

When adding a series or movie to the library, clearart / clearlogo information is not created in the nfo file - which is clearly visible, for example, in Netflix-My List.
Not all series / episodes are scrapable by other scrapers - so I use NFO files
#### Describe the use case

With cleart form netflix plugin:
![screenshot00000](https://user-images.githubusercontent.com/36659110/129355255-171f03e4-2d4a-4d5d-b411-e9dc450d6cb3.png)

From library without clearart:
![screenshot00001](https://user-images.githubusercontent.com/36659110/129355448-e58d0466-b165-40bc-9ed7-054546dcc44e.png)

And nfo file for this tvshow (generated by plugin):
```
<?xml version='1.0' encoding='UTF-8'?><tvshow><mpaa>7+</mpaa><plot>Wybierz się w podróż po animowanym świecie Skylanderów i śledź poczynania grupki absolwentów Akademii, którzy muszą znaleźć w sobie odwagę, by stawić czoła złu.</plot><id>80113201</id><showtitle>Akademia Skylanders</showtitle><title>Akademia Skylanders</title><thumb aspect="poster">https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdokhQV5X37tD2fkK9EQi6tXMo4HOuGDfNruz_0Alpy9k0L_0bmQndB-xwD8AM1VvQsZFA-pPyRTSaUuwIJAOZrnjMAqm-jZOhqdqjr7ZR8kXxYgY0J0qgIQ9DOsrg.jpg?r=fe7</thumb><thumb aspect="poster">https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQ7fqfA5eyXIRmmz8oXhvgOQhl86lJTlLnMd5JlhkpiWvihAUuDq-iF0lio6-PlW2AA8z_acCZ83p5NNXmeyEURcwq99wq81uTMOpoiNntcxiD6QSDM9Dp4V5tMWRg.jpg?r=fe7</thumb><fanart><thumb>https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABS1E-cLIwyXMXrAv6D6gV8wKbrHWA6np5d26N2aXRDY7W4E7jvSQwtKYsJqzO6yNR1Zip4F2obcLHdX6qLDtlD7LsXtl.jpg?r=4e8</thumb></fanart><fanart><thumb>https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABSknfmov1D6lVdaOomRhOv3rLZcLouYLNS7gS1LB6WHz7uRDDQwyui76KPBu6Zyasndk83gmHNgn6FHCl2a7vMoMzL-_.jpg?r=4e8</thumb></fanart></tvshow>
```

**Comment by notoco** [comment]
And maybe add information about the year of production? Because it is currently empty and the kodi stubbornly shows 1969, not 2018

**Comment by CastagnaIT** [comment]
the nfo data are based on netflix metadata only, there are limited info, are not the same data as the directories (like MyList)
clearart not exists on metadata

for the "year" is not specified at "show" level data, but maybe i could read the year from the first season
ATM not remember how works all NFO code i will need to check

**Comment by notoco** [comment]
Then you made me sad, my friend. As a penalty, I will finally complete the Polish translation.

**Comment by CastagnaIT** [comment]
please do a test 
[plugin.video.netflix_1.17.0+matrix.1_20210814.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6986150/plugin.video.netflix_1.17.0%2Bmatrix.1_20210814.zip)

**Comment by notoco** [comment]
Theoretically it works. Not at all views, but it's my skin's fault - I have to bury a little in it.

**Comment by notoco** [comment]
Wait!
reading this:
https://kodi.wiki/view/NFO_files/TV_shows
It's better to use premiered instead year!

**Comment by CastagnaIT** [comment]
i think the problem is the date format
we have only the year value not the full date

from your link
> Format as 2019-01-31

and also:

>Release Year.
>Do not use. Use \<premiered\> instead 

i do not know when this change is happened
i do not know if can be solved in some way
if you have time try investigate

**Comment by CastagnaIT** [comment]
i tried investigate better, the `<year>` tag seem has been deprecated in Kodi v18 and removed on v19
so IMO the best thing that we can do is replace it with `<premiered>` and hardcode month/day.
by testing on Kodi 20 appears to works correctly, and in the info screen dialog the year along the title appears correctly
will be fix for next release
