### ISSUE TITLE
Authentication Key approach does not work on OSMC on Raspberry

### ISSUE THREAD

**Issue by exiledonamarginalisland** [CastagnaIT/plugin.video.netflix#1215]
## Bug report
Authentication Key approach does not work on OSMC on Raspberry. Indeed, if you try to generate the key on the machine itself, of course you cannot launch a browser because there is no X environment installed. Installing Links text based browser is not a solution, because Netflix refuses the connection because of "no javascript" 

Any idea of how to make this work in an environment where you do not have the X environment or the browser?

#### Your Environment
Raspberry 4 with 8GB Ram
MicroSD Lexar 64GB
OSMC 2021.08-1 with Kodi 19.X
AndreaCastagnaIT 1.0.0

**Comment by exiledonamarginalisland** [comment]
Dear github actions.

If you look at the bug described you will see there is no need for a log. May I say this is also a colossal waste of time? If you develop an AI based system could you make sure it does understand 1) the context 2) the meaning, before deploying? 

Best,

**Comment by notoco** [comment]
you don't need to run this program on raspberry. Run it on Windows and copy the file to the raspberry.

**Comment by CastagnaIT** [comment]
> f you develop an AI based system could you make sure it does understand 1) the context 2) the meaning, before deploying?

really? If you're here to complain, you can go elsewhere
or else you are welcome to invest your time in implementing a BOT with AI for decoding of the contents of an Issue thread

sidenote, last version 1.17.0 do not need of Authentication Key, can be used username/password

**Comment by exiledonamarginalisland** [comment]
Well, I am actually an OS developer, who uses github, so I am free to complain with github as much as I want, if you do not mind. Also, I am not 100% sure why you care so much about what I tell github. That said, in the last version (which I am currently using) username / password does not work, and return the infamous "wrong password / change password" error. Anyway, I bypassed the problem ....

**Comment by CastagnaIT** [comment]
> Well, I am actually an OS developer, who uses github (among other repositories), so I am free to complain with github as much as I want, if you do not mind (and also if you mind). Also, I am not 100% sure why you care so much about what I tell github.

if you know github, you should know that the bot is based on a github action,
i developed this github action myself, and even if it's not perfect it takes a lot of work off my shoulders
so if you complain, it's directed at my Github Action development, not at the user "Bot"

Anyway, since you've solved it
i close it
