### ISSUE TITLE
NF Authentication key don't give pin and key

### ISSUE THREAD

**Issue by SashoN1913** [CastagnaIT/plugin.video.netflix#1219]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [X ] Windows

### Describe the bug

After I log in Netflix chrome tab doesn't close and after some time I get message you have exceeded the time available for login
#### Expected behavior

Should close the tab and give me file with the key and pin

#### Actual behavior

It doesn't happens anything and tab don't even close

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:

**Comment by CastagnaIT** [comment]
try run the executable as administrator

**Comment by CastagnaIT** [comment]
closed due to inactivity
