### ISSUE TITLE
Stream showing 720x480

### ISSUE THREAD

**Issue by kapad** [CastagnaIT/plugin.video.netflix#122]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## General information
Running this add-on on Kodi on Android TV
*Xiaomi Mi TV 4X Pro*

### Addon version used

0.14.6

### Description

I'm playing a video that's available in 4k, but when I click the video information, I see that the stream that's being played is HEVC, 720x480

**Expected behavior:**
The video should play in 4k. 
I followed a the steps here for 4k streamingand then upgraded my Netflix to a 4k account. 

**Actual behavior:**
The video plays in HEVC, but in 720x480. *see the attached screenshot*

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

## Screenshots
![IMG_20190703_033653](https://user-images.githubusercontent.com/2017355/60550389-56591c80-9d17-11e9-88e8-100c7db712fb.jpg)

**Comment by Smeulf** [comment]
Hi.

Please can you ensure InputstreamAdaptative is not limited for max resolution for secured streams?

Also please provide debug logs, or there's no way we can understand what's going on.

**Comment by Smeulf** [comment]
Plus, ensure your device supports Widewine L1 DRM. I'm sorry I can't confirm it myself, I can't find any information about this for now.

**Comment by kapad** [comment]
The only options that I see for secured streams in the input stream adaptive plugin are 480, 640, 720, 1080 and Max. What does this mean?

Also, where would I find the debug logs? I'm running Kodi on a Xiaomi 4 X Pro TV. 

Finally, I'm guessing that if 1080p streaming is working, then my device widewine L1 DRM. Is that assumption correct?

**Comment by Smeulf** [comment]
Secured streams max resolution is the maximum resolution you allow to be processed with InputStream. IE with a Raspberry Pi3, it must be set to 720p as the software can't decode 1080p fast enough.

If your settings is Max or 1080p, it should process 1080p streams.

In the add-on settings now, you have to enable HEVC (or VP9) in the expert section. Try both one by one, do not enable the two options at the same time.

Last but not least, your device must support L1 drm. Playing a video in 1080p is not sufficient for 4K. If you can play 4K videos with the original Netflix app on you device, then it's compatible. If you can't or if your device is not Netflix certified, then you should ask the manufacturer for details or find the technical sheet and see by yourself.

Hope it helps.

**Comment by jakermx** [comment]
Disable HEVC...your device is asking for it on manifest as HEVC for  Small screen device.

**Comment by kapad** [comment]
> In the add-on settings now, you have to enable HEVC (or VP9) in the expert section. Try both one by one, do not enable the two options at the same time.

@Smeulf I tried disabling HEVC, and enabling VP9, but I still didn't get a 4K, or even and HD stream. 

With HEVC -> 720x480
With VP9 -> 960X540

So haven't even got Full HD working properly with this device yet. 

@jakermx  Is there any way to override what resolution the device asks for in the Manifest?

**Comment by jakermx** [comment]
oooooook

First.

HEVC is a codec used to decode H.265 videos, rememeber that Netflix uses an extra layer to get video, because the stream is decoded, so the device, get the stream, decrypt it and then decode it, so HEVC is one  way to decode HD, UHD, 4K videos via H.265.

Second, to get 4k content from Netflix, you need to have an account that have HD content enabled.

Third

You have to have a device capable to decode 4K content, via any codec you want... so HEVC is ok 

Fourth,

In order to over ride the  resoluton, you have to set your InputStream Adaptive Stream Selection to Manual, if not Kodi wlll decide the Resolution for you.

This way you will able to seect any compatible resolution that Netflix Offers you back when yo request the manifest... so to be sure what you want please enable HEVC and force HDCP 2.2.

This way you will be able to retreive and select the resolution you  are looking for....if your device has limited RAM , you wontbe able to enojoy HD content.....because Netflix uses software based encryption and decoding, so performancedepends on HW, just a few Android devices supports HW based decoding for Netflix....

Good Luck

**Comment by jakermx** [comment]
FYI


https://www.lifewire.com/how-to-stream-netflix-in-4k-1847830

**Comment by kapad** [comment]
> HEVC is a codec used to decode H.265 videos, rememeber that Netflix uses an extra layer to get video, because the stream is decoded, so the device, get the stream, decrypt it and then decode it, so HEVC is one way to decode HD, UHD, 4K videos via H.265.

I already know this and have checked it. 

> Second, to get 4k content from Netflix, you need to have an account that have HD content enabled.

Same as above.

> You have to have a device capable to decode 4K content, via any codec you want... so HEVC is ok

Again, see above. 

Display specifications of my TV -> https://www.displayspecifications.com/en/model/e9631303
It supports HDCP 2.2 and HEVC. 

> In order to over ride the resoluton, you have to set your InputStream Adaptive Stream Selection to Manual, if not Kodi wlll decide the Resolution for you.

I've already tried this and still didn't see the 4K stream in the list of options. In fact, *I didn't even see the Full HD option (1920x1080)*. I've read about a bug in the Input Stream Adaptive plugin about it not selecting the max available stream option and instead selecting the Max - 1 option. I think this could be the issue affecting me. But I'm not sure how to tell if it actually is this issue.

**Comment by Smeulf** [comment]
Please install the 'drm info' app.

Launch it, and in the 'Widevine CMD' section, look at the security level.

If it's L3 as I presume, you'll never get 4K on you device until Xiaomi release a compatible firmware.

If it's L1, please set InputStream Adaptative stream selection to manual again and share your logs.

Please also can you post a picture of the Widevine CMD section from 'drm info'?

Thanks.

**Comment by Smeulf** [comment]
Plus, there's no Xiaomi product referenced on the Netflix support for being compatible with 4K, either on the tv or the Android section...

**Comment by jakermx** [comment]
AFAIK Android Devices are not use as  UHD Devices, they are considered as Mobiles or Tablets, but they could handle CDM as L1 or L3---- the trick is the user agent, they shoud use Safari UA in order to get 4k playback.

**Comment by kapad** [comment]
Have actually installed this and have commented on this issue based on the
results from this app.

Will post a screenshot when I get back home in the evening..

And also add the logs.

**Comment by kapad** [comment]
Yes, I know. But from what I've read online, the only reason for this is
that Xiaomi hasn't included the Netflix button on any of it's remotes.
So hardware and firmware wise, the TV is compatible AFAIK.

See https://beebom.com/xiaomi-mi-tv-pro-lineup-netflix/

**Comment by jakermx** [comment]
What can I say???.....

https://androidpctv.com/netflix-4k-hailstorm-android-tv/

It is what it is...

**Comment by CastagnaIT** [comment]
if you followed the instructions correctly on the main page, in the section: "Can it play HDR?"
and it still does not work, it means that currently your device is not compatible at least through the system used by this addon.

if in the future someone will find a solution it will be welcome, for now close

**Comment by mkaflowski** [comment]
I have the same problem on Nvidia Shield. Last time I have used Netflix addon about 3 weeks ago. Today when I have tried play movie I get black screen and empty screen next. I have reinstalled addon and I have small resolutions only. I have no idea if it is because Netflix addon update, InputStream update, Shiled update to Android P or something else.

**Comment by garzy** [comment]
Mee to, I'm having exactly the same problem in Android box

**Comment by mkaflowski** [comment]
Have you got it work on Xiaomi box? It works on my Shield on version 16 but I have small resolution on Xiaomi Box.
