### ISSUE TITLE
Authentication key problem with LibreElec

### ISSUE THREAD

**Issue by cjgreencorner** [CastagnaIT/plugin.video.netflix#1220]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: LibreElec 10 Beta 1
- Device model:  Raspberry Pi 4B

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I can't log in without the Authentication key, so i tried downloading it and i followed the steps. Because I am using LibreElec there is no webbrowser and pip or apt doesnt work.

#### Expected behavior

I just want to log in again. One way or another.

#### Actual behavior

Because there is no webbrowser i downloaded the file on my desktop and put it on my rpi via filezila. But the next steps seem to be impossible without pip.

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:

**Comment by CastagnaIT** [comment]
read the instructions https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key
