### ISSUE TITLE
Fix for search for use in skins

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#1222]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [X] change an existing feature

### Describe your request

I found a fix that allows to use the search in the AZ2 skin, most likely it would also work with TheMovieDBHelper

#### Development tips
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/36#issuecomment-901637519

**Comment by CastagnaIT** [comment]
try this [plugin.video.netflix_1.17.0+matrix.1_20210907_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7121759/plugin.video.netflix_1.17.0%2Bmatrix.1_20210907_t1.zip)

is untested i do not know if works

the search endpoint is:
`plugin://plugin.video.netflix/directory/search/search/?query=lucifer`

**Comment by nfm886** [comment]
> try this [plugin.video.netflix_1.17.0+matrix.1_20210907_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7121759/plugin.video.netflix_1.17.0%2Bmatrix.1_20210907_t1.zip)
> 
> is untested i do not know if works (to be test also multipages)
> 
> the search endpoint is:
> `plugin://plugin.video.netflix/directory/search/search/?query=lucifer`
> 
> this make a search without touch addon database

Hi,
Thanks for taking challenge to make it working with search feature.
Unfortunately I tested this zip file and it seems does not working: https://streamable.com/6e6zoy
It looks like it return just a results from search directory, so it will be "New search...", "Clear search history", etc.

**Comment by CastagnaIT** [comment]
i have forgot some thing try this
[plugin.video.netflix_1.17.0+matrix.1_20210910_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7143573/plugin.video.netflix_1.17.0%2Bmatrix.1_20210910_t2.zip)

let me know also what happens when you press "next page" item

**Comment by nfm886** [comment]
It works now. Good job.
Pressing next page redirecting to Netflix addon's next page.
https://streamable.com/hrdoog

Will this changes be merged in master branch?

**Comment by CastagnaIT** [comment]
nice video
yes i can add it to master branch

**Comment by nfm886** [comment]
> yes i can add it to master branch

Awesome! Thanks!
So I'm adding default shortcut to my skin :))
Cheers!
