### ISSUE TITLE
Prompted for password after key/pin

### ISSUE THREAD

**Issue by MiggyMan** [CastagnaIT/plugin.video.netflix#1223]
#### Your Environment
- Netflix add-on version:  1.1.7.0
- Operating system version/name: Ubuntu 20.04
- Device model: N/A

Used Operating system:
* [ ] Android
* [ ] iOS
* [ x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
I've installed the plug and generated a NFAuthentication.key as per the documentation in the wiki (using 1.1.4, on an ubuntu 18.04 machine with python 2.7), when the key is copied to the kodi system and key authentication is selected in the plugin it then prompts for the key and pin however after this the plugin prompts for a password and presents an authentication error.

#### Expected behavior
Provide key/pin, profit!

#### Actual behavior
Provide key/pin, asked or password, sad times.

#### Steps to reproduce the behavior
1. Generate key
2. Pick key in plugin
3. Enter pin
4. Be very surprised when you get prompted for a password 

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7100294/kodi.log)

**Comment by CastagnaIT** [comment]
from wiki instructions:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

> With this file+PIN (the password will be still required) you can login on any device

**Comment by MiggyMan** [comment]
Fair enough i didn't spot that, however even with the correct password, pin and key this does not work.

**Comment by CastagnaIT** [comment]
if addon say incorrect password there is nothing can be done from addon side

the only thing i remember, is that there are some stupids skins that force the uppercase in the input text boxes
then all addons receive text's with wrong uppercase text from the user
if this is the case, you have to switch to default kodi skin, then ask to skin developer to not force uppercase text

**Comment by MiggyMan** [comment]
I'm on the default skin, I've verified the password multiple times (but i will admit i am finding the kodi text input...... irritating), regenerated the key and pin multiple times, still no joy.

**Comment by CastagnaIT** [comment]
i have no others solutions

**Comment by MiggyMan** [comment]
Fair enough, I can't really ask any more, I might prod netflix and have them look at my account as it's only ever worked on browser/mobile and has never worked with the client in our cable box so now i'm wondering if the account has an issue!

Thanks for your time regardless :)
