### ISSUE TITLE
Unable to display any show list

### ISSUE THREAD

**Issue by Astaoth** [CastagnaIT/plugin.video.netflix#1228]
#### Your Environment
- Netflix add-on version: 1.17.0+matrix.1
- Operating system version/name: raspbian bullseye with Kodi 19 
- Device model:  raspberry pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
With the Netflix addon, when I go into menu with show list, like "My List" or "New on Netflix", I encounter a "WaitTimeoutError" error.

#### Expected behavior
I should be able to navigate into "My List", "New on Netflix" or any given submenu of this addon.

#### Actual behavior
I have a message displaying a "WaitTimeoutError".

#### Steps to reproduce the behavior
1. Go to the netflix addon
2. Choose a profile
3. Go into "My List" or "New on Netflix"
4. Wait 
5. There is a message with the error

#### Possible fix
N/A

### Debug log
The debug log can be found here: https://paste.kodi.tv/naqiqizuvu.kodi

**Comment by CastagnaIT** [comment]
Seems that your add-on database is corrupted
reinstall the add-on by deleting also user data when prompt

**Comment by Astaoth** [comment]
That worked, thank you for your help !
