### ISSUE TITLE
Netflix throws Exception: Key Error while retrieving episode list

### ISSUE THREAD

**Issue by gary9872** [CastagnaIT/plugin.video.netflix#123]
*I'm submitting a ...*
 
 - [X ] bug report
 
## General information

Throws Exception Key error when retrieving episodes for FairyTail. 
https://www.netflix.com/watch/70263563

### Addon version used

[0.14.6]

### Description

[Description of the bug or feature]

### Steps to Reproduce

Select FairyTail Season 1

**Expected behavior:** Shows List of Episodes
**Actual behavior:** Generates an Error Popup: Execption KeyError.

 [X] I'm using this Netflix Repo

### Operating System

Linux CoreELEC 3.14.29 #1 SMP Sun May 12 15:03:58 BST 2019 aarch64 GNU/Linux

## Debug log

https://pastebin.com/Bqgs90c4

## Other information

So far I haven't been able to reproduce this with other Shows with episodes.

**Comment by CastagnaIT** [comment]
I confirm the problem, I will find a solution

**Comment by CastagnaIT** [comment]
fixed, later you can download the update in the daily build download

**Comment by gary9872** [comment]
Works fine in the updated daily build. Thanks.
