### ISSUE TITLE
Language search not working

### ISSUE THREAD

**Issue by otava5** [CastagnaIT/plugin.video.netflix#1231]
#### Your Environment
- Netflix add-on version: 1.12.6 - Leia
- Operating system version/name: Coreelec 9.2.8

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
After updating to 1.12.6 Leia, you cannot search by audio and subtitle language. Sending log ...
Version 1.12.5 Leia works

### Debug log
https://paste.kodi.tv/arulafapik.kodi

**Comment by otava5** [comment]
Now error message: invalid syntax line 103....
https://paste.kodi.tv/ezenawipay.kodi

**Comment by CastagnaIT** [comment]
you are doing something wrong if that error appears

**Comment by otava5** [comment]
Yes, you were right ... Now it works
Will a partial new version for Leia be released in the beet?
