### ISSUE TITLE
Syncing Netflix and Trakt

### ISSUE THREAD

**Issue by rijsab** [CastagnaIT/plugin.video.netflix#1233]
Hi,

I would like to sync my Netflix with Trakt. This is already possible when using the Netflix addon and I can see Trakt scrobble. However if I use Netflix native App, my Netflix Addon is showing the correct sync with Netflix original app. But I could not find a solution to sync this new content back to Trakt unless I play something directly from Netflix Adeon. 

Am I doing something incorrect or does this option not existing at all?

Thanks for the support!

**Comment by CastagnaIT** [comment]
this is an old question, currently there is no support for Trakt
it will be not add from my part
those who are able can propose changes in a PR that will be evaluated
