### ISSUE TITLE
No add-ons in the repo

### ISSUE THREAD

**Issue by Danjoe4** [CastagnaIT/plugin.video.netflix#1235]
#### Your Environment
- Netflix add-on version: n/a
- Operating system version/name: LibreElec 10.0, kodi 19.1
- Device model:  Raspberry Pi4B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

#### Expected behavior

Addon browser->install from repo->CastagnaIT I expect to see the Netflix addon

#### Actual behavior

Empty! No add-ons appear

#### Steps to reproduce the behavior

1. Add source in file manager
2. Install the CastagnaIT repo from install from zip file
3. Go to install from repo and select CastagnaIT

### Debug log

The debug log can be found here: https://paste.osmc.tv/tucakejiyo

#### Other information

I have installed repos before... Why aren't the add-ons showing up?

**Comment by CastagnaIT** [comment]
i have just tried and work as usual
i think your network has temporarily failed
