### ISSUE TITLE
Updata translation strings PT BR (Portuguese Brazil)

### ISSUE THREAD

**Issue by MediaBrasil** [CastagnaIT/plugin.video.netflix#124]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [ x ] support request

## General information

Please update pt-br language with latest items

https://files.xbmcbrasil.net/PluginsVideo/strings.po

One Request if possible try change in English po file

msgctxt "#30173"
msgid "NETFLIX ORIGINALS"
msgstr ""

to

msgctxt "#30173"
msgid "Netflix Originals"
msgstr ""

It's the only item in the menu items use Uppercase letters

Thanks

**Comment by CastagnaIT** [comment]
I kept uppercase to match the text obtained from netflix query,
but it can be done

**Comment by CastagnaIT** [comment]
@Smeulf you can update these,
and even remove the words "not use with HEVC" from 30137
in every language?

**Comment by Smeulf** [comment]
I'll update PT-br, lower case of 30173, and update 30137 in the evening.

PR will follow :)

**Comment by Smeulf** [comment]
@MediaBrasil don't you want the quotation mark for this translation?

msgctxt "#30191"
msgid "Do you want to export NFO files for the {} added to 'My List'?"
msgstr "Deseja exportar arquivos NFO para o {} adicionado em 'Minha Lista'"

**Comment by MediaBrasil** [comment]
Yes, need add
msgstr "Deseja exportar arquivos NFO para o {} adicionado em 'Minha Lista'?"

**Comment by CastagnaIT** [comment]
thankyou merged
