### ISSUE TITLE
Error "Cannot assign requested address" when trying to bind loopback

### ISSUE THREAD

**Issue by mrfixit2001** [CastagnaIT/plugin.video.netflix#1240]
#### Your Environment
- Netflix add-on version: 1.17.0+matrix.1
- Operating system version/name: ARM Buildroot
- Device model:  ARM RK3328

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Addon does not start due to error. I see it's trying to use the loopback address. I would suggest adding a catch for this error and then trying the local address instead of the loopback
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7297401/kodi.log)

```ERROR <general>: [plugin.video.netflix (0)] Background services do not start due to the following error
ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/home/share//.kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 31, in init_servers
                                                       self.nf_server_instance = NFThreadedTCPServer((self.HOST_ADDRESS, select_port('NF_SERVER')))
                                                     File "/home/share//.kodi/addons/plugin.video.netflix/resources/lib/common/device_utils.py", line 19, in select_port
                                                       port = select_unused_port()
                                                     File "/home/share//.kodi/addons/plugin.video.netflix/resources/lib/common/device_utils.py", line 35, in select_unused_port
                                                       sock.bind(('127.0.0.1', 0))
                                                   OSError: [Errno 99] Cannot assign requested address```

**Comment by CastagnaIT** [comment]
this is not a bug, loopback is used to route addon data between addon instances
it seems that your operating system does not allow you to open network ports,
perhaps too aggressive firewall? or something else has wrong setup

Or another explanation could be that you have a custom loopback address, 
in this case you will have to edit the add-on sources to set your non-standard loopback address

this situation cannot be solved by the add-on

**Comment by mrfixit2001** [comment]
Thank you for the detailed reply! You were right, I had never noticed the loopback address locally wasn't online. Everything else always worked fine until this. But if I fix the loopback it works.
