### ISSUE TITLE
Exception msl_data.json causes Kodi to crash during playback

### ISSUE THREAD

**Issue by Liqianyu** [CastagnaIT/plugin.video.netflix#1258]
#### Your Environment
- Netflix add-on version: v1.18.0
- Operating system version/name: Android 9
- Device model:  Shield TV 2019 Pro

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

At first Netflix Add-On seemed to repeatedly ask for a new login, which I did. I then noticed that once I played any Netflix content, Kodi would immediately crash. (Meanwhile other streaming add-ons such as Hulu\HBO Max\Disney Plus had no problem) After various ineffective attempts, finally reinstalling Netflix Add-On solved the problem. I can now continue to test this issue via Netflix Mod Add-On (Paco8). (I did not reinstall it, so it still crashes immediately when playing).

#### Expected behavior

Normal start of playback

#### Actual behavior

Kodi crashed immediately

#### Steps to reproduce the behavior

1.Open Kodi
2.Open Netflix Add-On
3.Play any content and Kodi crashes.

#### Possible fix

Eventually, based on testing, I found that by deleting msl_data.json under /userdata/addon_data/plugin.video.netflix, the Netflix add-on would regenerate and play properly the next time it was played.
I'm not sure if it's safe to upload the file, after comparing the file the fields have changed except for bound_esn and user_id_tokens.

### Debug log

The debug log can be found here:

https://paste.kodi.tv/robehayupe.kodi

#### Other information

These posts also have the same log endings, and Kodi crashes as well.
https://github.com/Sandmann79/xbmc/issues/120
https://github.com/asciidisco/plugin.video.netflix/issues/505
https://forum.kodi.tv/showthread.php?tid=338000
They both have similar log endings and both result in Kodi crashes.

**Comment by asfixi** [comment]
> #### Possible fix
> 
> Eventually, based on testing, I found that by deleting msl_data.json under /userdata/addon_data/plugin.video.netflix, the Netflix add-on would regenerate and play properly the next time it was played. I'm not sure if it's safe to upload the file, after comparing the file the fields have changed except for bound_esn and user_id_tokens.

@Liqianyu 
This works for me. I had this problem for months. THANK YOU VERY MUCH, man.
