### ISSUE TITLE
No login possible 

### ISSUE THREAD

**Issue by Friesenhahn** [CastagnaIT/plugin.video.netflix#126]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used
0.14.6

[eg. 13.21.0]

### Description
 installed the addon via the repository in version 0.14.5

Until more or less a week ago everything worked pretty great. Then I do not know if it was right after updating to version 0.14.6 (went automatically) I could no longer watch anything. Still I was logged in and could browse all the lists and movies though initially when starting the addon it said to check my credentials. I uninstalled the addon and removed all settings. Then I reinstalled everything but no luck and now I am not even able to login though I am pretty sure the credentials are fine.

### Steps to Reproduce

1. Starting KODI
2. Starting Netflix-Addon
3. Credentials are being asked
4. Correct credentials submitted
5. Returned message "Check credentials"
6. Starting the addon again
7. Same result as in Step 3

**Expected behavior:** [What you expected to happen]
Addons "start screen" shows up with the list of all series and movies

**Actual behavior:** [What actually happened]
Returns message to check the credentials

## Context (Environment)
LibreElec 9.0.2

### Installation

* [ ] I'm using this Netflix Repo
* [X] I'm using other Netflix Repo (Please specify which)
--> installed it via the the repository.castagnait-1.0.0.zip
* [ ] I'm using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
LibreElec 9.0.2
## Debug log
https://friesencloud.ocloud.de/index.php/s/Sq6PGLKDX3Be9rq

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment]
I see so many errors but that do not concern this plugin,
however, debug information is totally missing, you have not enabled it
follow guideline and enable it and post a new log

**Comment by Smeulf** [comment]
Looks very similar to this one don't you think @CastagnaIT ?https://github.com/CastagnaIT/plugin.video.netflix/issues/121

**Comment by jakermx** [comment]
The first time error was about Logged in thing, then , It is failing because locale_id cannot be found, try to fill that stuff on Regionals on Interface Settings.

**Comment by Smeulf** [comment]
I couldn't see the locale_id error, thanks @jakermx 

@Friesenhahn please disable "Export new episodes" in the Library section of the addon settings and report back. It's a known issue i'm working on, and for now the function is not implemented anyway, so it will never work. See this issue for more information https://github.com/CastagnaIT/plugin.video.netflix/issues/78

**Comment by Smeulf** [comment]
Also restart Kodi after you change the option or it will keep pop-up

**Comment by jakermx** [comment]
> locale_id

2019-07-07 16:38:05.688 T:140100654196480   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 47, in do_GET
                                                data = self.server.msl_handler.load_manifest(int(params['id'][0]))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 41, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 238, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 109, in load_manifest
                                                manifest = self._load_manifest(viewable_id, g.get_esn())
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 238, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 162, in _load_manifest
                                                'languages': [g.PERSISTENT_STORAGE['locale_id']],
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/storage.py", line 35, in __getitem__
                                                return self.contents[key]
                                            KeyError: u'locale_id'

**Comment by Smeulf** [comment]
Yes I saw it after you lead the way :)

I know where the problem comes from, but I have to find the best way to fix it now ^^ It's on the top of my list.

**Comment by jakermx** [comment]
As suggestion, add a AddOn Signal that waits until Background Services is ready, it will set and hit the export thinng...

**Comment by Smeulf** [comment]
The locale_id issue is in the _update_running function of lib/kodi/library.py. There's a `g.ADDON.setSetting('update_running', 'false')` that comes in conflict with the services, and somehow some data are flushed.

But, as there's a but, those values are obviously not settings values, it's not the right place to store them. They should be stored in the global storage. Plus the library_updater service can't run correctly the way it's (partially) written.

So I'm still thinking about the best way to rewrite it (using Signal also), and minimise CPU and memory consuming if possible... I'm making progress, slowly ^^

**Comment by jakermx** [comment]
I meant AddOn Signals.....the Addon, not the update_running "Flag" that ensures there is not anotherinstanceof the updater running,  I meant to make a AddOnSignals call, so it hits the update.

**Comment by Smeulf** [comment]
The 'update new episodes' is ment to be a service.

So unless it's called manually, I can't see how Addon Signal would help me to trigger something :/ I'm sorry I'm not understanding what you're thinking about, maybe just because I'm thinking it differently :)

I gonna code something tomorrow if I have sufficient time, have a look on my repo from time to time, and comment. I'm always open to suggestions!

**Comment by jakermx** [comment]
AddOn Signals will help you to trigger the update once it receives a Signal from Netflix AddOn saying it is alive and there is no playback in course, and when a playback starts , if there is an update happening , It will pause it until playback is done... you can do it manually, checking sockets, if the default tcp port for for nfsession and msl open, means netflix is up and running, and monitor for inputstream calls from netflix, so you can pause the  update.... look at libreelec , it pauses when any playback starts, or check tvh server and client, it dont update epg if playback is going.

**Comment by Smeulf** [comment]
For now, the 'wait for 5 minutes idle' option seems good enough for me to ensure the update is not starting while playing.

And the update starts on a datetime basis, as a scheduler would do. So for starting, I'm not sure it's useful.

Pausing the export if a playback starts could be a good idea, but that would mean keeping the export process alive while playing with xbmc.sleep, and restart when idle' again. That might be possible. I think was can discuss this after the export routine is written ^^ Unless @CastagnaIT wants it implement right now ;)

**Comment by Friesenhahn** [comment]
Sorry Guys for letting you wait. I am currently on vacation till the end of the month. I am going to disable the export feature asap. Thanks for your kind Support!

**Comment by Smeulf** [comment]
@Friesenhahn don't worry. As it's an already known error, it's on my to-do list. We'll update the issue when a fix is available.

Have a nice winter!
