### ISSUE TITLE
Video stucks after ESN change

### ISSUE THREAD

**Issue by Sznaf** [CastagnaIT/plugin.video.netflix#1261]
#### Your Environment
- Netflix add-on version: v1.12.7
- Operating system version/name: Android 6.0.1 
- Device model: Xiaomi Mijia Youth Edition (MiProjLED1)

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
On default configuration everything works great except video resolution (only 960x540). According to instruction I manually changed ESN from NFANDROID1-PRV-T-L3-XIAOMMIPROJLED1-XXXX  to NFANDROID1-PRV-T-XIAOMMIPROJLED1-XXXX and it worked. Now video resolution is actually FullHd but after ~2min of watching, loading spinner shows up, loads to 100% and video stucks  (but time is still normally going). The same behaviour if I try to fast-forward video.

#### Expected behavior
Video doesn't stuck

#### Actual behavior
Video stucks on FullHd

#### Steps to reproduce the behavior

1. Change ESN in addon settings
2. Run addon
3. Play video, wait 2min or fast-forward

The debug log can be found here:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7488895/kodi.log)

**Comment by CastagnaIT** [comment]
Unfurnately you are using Kodi 18,
the addon for Kodi 18.x versions is not more mainteined and no more support will be provided,
suggest you to install Kodi 19 from scratch

**Comment by leikeze-max** [comment]
hi, I'm having the exact same problem and I'm using kodi 19.3 for android

**Comment by dhrubo66** [comment]
I have the same issue (in both Kodi 18 and 19). Changed ESN (PRV-T- to PRV-0-T-) for FHD, it works for a while, then video stucks but audio comes through. Please let me know if there's any workaround. :(
