### ISSUE TITLE
black screen mibox3

### ISSUE THREAD

**Issue by ananias47** [CastagnaIT/plugin.video.netflix#1264]
#### Your Environment
- Netflix add-on version: 1.18. 0+matrix.1
- Operating system version/name: android 9,kodi 19.3
- Device model:  mibox 3

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
plays all videos with audio but i have black screen

https://pastebin.ubuntu.com/p/MR8M5ZCJ7D/
#### Actual behavior

black screen
#### Steps to reproduce the behavior

1.i have try many videos and all plays with audio but black screen
2.
3.

#### Possible fix

I have tried to reset esn but still the same problem
### Debug log

The debug log can be found from this link:
https://pastebin.ubuntu.com/p/MR8M5ZCJ7D/
#### Installation
* [ ] I'm using other Netflix Repo  

* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
the log is accessible to ubuntu users only
please put into http://paste.kodi.tv/

**Comment by ananias47** [comment]
https://paste.kodi.tv/heyayuloga.kodi

**Comment by CastagnaIT** [comment]
try follow:
When you playback a video on Android there is no video: https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#When-you-playback-a-video-on-Android-there-is-no-video

**Comment by jakermx** [comment]
Try setting  the Max Resolution to SD, and then go up....

It lookss that your widevine level   library is  holding you down....to check your HW + OS  Widevine Rank Levvel  go Play Store and instal DevCheck app.... it will show you your device level...

Widevine L3: This is the most basic certification supported, consisting entirely of software-based DRM. If you have a Widevine L3 device, the content will often play only at 480p. L3 also means no Trusted Execution Environment (TEE) for DRM encryption.

Widevine L2: The second level is Widevine L2 and it includes either software-based video processing or separate video hardware. If you have a Widevine L2 device you will often see a better resolution output than Widevine L3 at up to 540p, but still not the best quality possible.

Widevine L1: Widevine L1 is the topmost level of DRM protection and in devices supporting L1, video decryption and processing happens completely in the Trusted Execution Environment (TEE). Widevine L1 devices are able to play video at the highest possible resolution.

**Comment by CastagnaIT** [comment]
closed due to inactivity
