### ISSUE TITLE
Sync watched status is not working

### ISSUE THREAD

**Issue by wagnerch** [CastagnaIT/plugin.video.netflix#1266]
#### Your Environment
- Netflix add-on version: 1.18.0+matrix.1
- Operating system version/name: LibreELEC 10.0.1
- Device model:  Raspberry Pi 4B

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Watched status is not synchronizing, it appears there are 2 tracebacks in the log, I think after the 2nd one the am_video_events thread has died so no further events are attempted.

#1
```
2021-11-20 19:34:44.576 T:20393   ERROR <general>: [plugin.video.netflix (0)] [Event queue monitor] An error has occurred: 'locos'
2021-11-20 19:34:44.578 T:20393   ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/events_handler.py", line 58, in run
                                                       self._process_event_request(event_type, event_data, player_state)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/events_handler.py", line 72, in _process_event_req
                                                       self.loco_data = self.nfsession.get_loco_data()
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_ops.py", line 296, in get_loco_data
                                                       if context_name in loco_data['locos'][loco_root]:
                                                   KeyError: 'locos'
```

#2:
```
2021-11-20 19:35:16.605 T:20393   ERROR <general>: [plugin.video.netflix (0)] [Event queue monitor] An error has occurred: 'NoneType' object is not subscriptable
2021-11-20 19:35:16.605 T:20393   ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/events_handler.py", line 58, in run
                                                       self._process_event_request(event_type, event_data, player_state)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/events_handler.py", line 76, in _process_event_req
                                                       self._build_event_params(event_type,
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/events_handler.py", line 179, in _build_event_para
                                                       'lolomo_id': loco_data['root_id'],
                                                   TypeError: 'NoneType' object is not subscriptable
```

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7575585/kodi.log)

**Comment by jakermx** [comment]
I have a RPi2, RPi3, RPi4 (4 and 8 GB), Lastest LibreELEC and Lastest  NF AddOn, I also Have 2 i386/amd64 Laptops working without issues.
From your log I can see that you are tryiing to play 1080p  on RPi, that causes to fall down to  0p , so ...there iis  nothing to sync....try to follow the rules and set the Resolution Limit to  720p....and you will see the Progress  update....
Cheers

**Comment by jakermx** [comment]
Actually on RPi4 with LE Leia, it works as well

**Comment by CastagnaIT** [comment]
Does it happen with every video playback or rarely?

i have already see this error on another user
but to understand better what happens i need more details
please update with this:
[plugin.video.netflix_1.18.0+matrix.1_20211121_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7576006/plugin.video.netflix_1.18.0%2Bmatrix.1_20211121_t1.zip)

reproduce the error and attach here a new log thanks

**Comment by wagnerch** [comment]
@CastagnaIT Every video for me.  I have seen it on TV Shows Locke & Key Season 2, and Biohackers Season 2.  It was last working on 10/24 with Another Life Season 2.

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7576123/kodi.log)

**Comment by CastagnaIT** [comment]
mmh the API call not return the requested data, 
is possible that netflix is starting doing changes again in his API's for some countries, but could be also a temporary problem i do not know
I'll have to do more testing to figure out how to find a possible solution

**Comment by CastagnaIT** [comment]
You have already tried to switch profile twice before play a video?

**Comment by wagnerch** [comment]
> You have already tried to switch profile twice before play a video?

I'll give that a shot, however "continue watching" doesn't show up on the website either.  IIRC that is supposed to show up for partially watched TV Shows -- although I would think it's unrelated?  Also, the watch progress & viewing activity is working on the website.  Anything watched through the add-on is not captured in viewing activity or watch progress, which is the typical behavior when the video/watch progress events are not sent.

**Comment by CastagnaIT** [comment]
> however "continue watching" doesn't show up on the website either. IIRC that is supposed to show up for partially watched TV Shows -- although I would think it's unrelated? Also, the watch progress & viewing activity is working on the website.

to me in website (and also on android official app) the "Continue watching" is shown on all profiles:
![immagine](https://user-images.githubusercontent.com/3257156/142862435-31029fdd-d69c-49b1-8435-a04de3bf7365.png)

if you cannot see it, could be something changed in website or a temporary problem

> Anything watched through the add-on is not captured in viewing activity or watch progress, which is the typical behavior when the video/watch progress events are not sent.

in your case yes the viewing activity / watch progress updates from addon are broken due to the error mentioned because the website not provide the requested data to the addon,
but to me works as expected, so I'll have to figure out what to do in this case

**Comment by CastagnaIT** [comment]
maybe stupid question but your My List is empty?

**Comment by CastagnaIT** [comment]
Should be solved now, try test it:
[plugin.video.netflix_1.18.0+matrix.1_20211122_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7582422/plugin.video.netflix_1.18.0%2Bmatrix.1_20211122_t2.zip)

**Comment by wagnerch** [comment]
> maybe stupid question but your My List is empty?

No, My List has stuff in it.

> Should be solved now, try test it:

Yeah this version (t2) is working now for me.

> to me in website (and also on android official app) the "Continue watching" is shown on all profiles:
> if you cannot see it, could be something changed in website or a temporary problem

Yeah, it has been an off & on problem with Netflix.  I think some of it is the criteria [what they consider in this bucket] & timing.  It seems that things do age out of continue watching if you abandon them, but some TV shows should be in there and they never are.  It might be something they "load shed", not sure what US vs other countries/regions looks like.  I haven't been watching Netflix lately, so it might be a lot of things aged out.

**Comment by CastagnaIT** [comment]
> but some TV shows should be in there and they never are

I don't know exactly, but i see this behaviour:
- what i start to watch it is always add to "continue watching"
- if i leave a tvshow on standby for a long time, could be removed from "continue watching" but:
  - if the title was not included in My list, then the watched status of episodes will be lost
  - if the title was included in My list, then the watched status of episodes is kept saved and you can resume when you want
 - the "continue watching" can contains only few titles (maybe 20 or 30?), so if exceeed the older ones i think will be lost

> Yeah this version (t2) is working now for me.

good!

**Comment by wagnerch** [comment]
> I don't know exactly, but i see this behaviour:
> 
>     * what i start to watch it is always add to "continue watching"
> 
>     * if i leave a tvshow on standby for a long time, could be removed from "continue watching" but:
>       
>       * if the title was not included in My list, then the watched status of episodes will be lost
>       * if the title was included in My list, then the watched status of episodes is kept saved and you can resume when you want
> 
>     * the "continue watching" can contains only few titles (maybe 20 or 30?), so if exceeed the older ones i think will be lost

Continue watching is now working on the website, since I was testing the t2 version.  And it is showing up in the add-on after clearing the cache.   So it's probably the case where they aged out, since I haven't been using Netflix for a while, and I think I watched all of my in progress shows.

I usually thumbs up the shows I watched after removing them from my list, it probably skews Netflix's reality of how good the show is because I will thumbs up even if I didn't care for it (it has to be pretty awful to be a thumbs down, for me).  :)
