### ISSUE TITLE
Playback error MSLError - This title is not available to watch instantly

### ISSUE THREAD

**Issue by desbma** [CastagnaIT/plugin.video.netflix#1271]
#### Your Environment
- Netflix add-on version: 1.18.1
- Operating system version/name: Arch Linux

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Issue similar to #1216. Playback does not work and shows an error.
I try resetting the ESN as mentioned in the issue, and it did not fix the error.

#### Expected behavior

Playback should  work and not show an error.

#### Actual behavior

Playback does not work and shows an error.

#### Steps to reproduce the behavior

1. Play any video

### Debug log

https://paste.kodi.tv/bidenifada.kodi

**Comment by apannetrat** [comment]
Same problem, since yesterday. Running on Librelec.

**Comment by synack-dev** [comment]
Same problem. Kubuntu.
Log file suggests there may be a MSL/Widevinecdm license issue. error code: DEVICE_EOL_FINAL

**Comment by cas--** [comment]
I just found the same this evening. 

That DEVICE_EOL_FINAL error was mentioned on another project so might be worth looking into the suggested fix https://github.com/nohajc/netflix-mitm-proxy/issues/4

**Comment by CastagnaIT** [comment]
DEVICE_EOL_FINAL is a different error from the problem of this issue
please open another issue and fullfill all required info

**Comment by CastagnaIT** [comment]
@desbma please try the steps described here
This title is not available to watch instantly: https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#this-title-is-not-available-to-watch-instantly

**Comment by desbma** [comment]
Sorry I missed the FAQ entry.
I tried logout/login, and reinstalling widevine, same error.

**Comment by cas--** [comment]
I tried logout and login without success but then updated all packages (Kodi Ubuntu PPA), rebooted and working again.

**Comment by hryuk** [comment]
Same on Manjaro, doing a system upgrade and rebooting solved it for me.

**Comment by desbma** [comment]
It started working again today, I don't know why...
A server side change from Netflix ?
Anyway I'm closing this, will reopen if it happens again.

**Comment by CastagnaIT** [comment]
unfortunately this type of error "This title is not available to watch instantly" happens in different situations where the causes are most of the time unknown,
with my experience this can depends also from the type of network used (eg mobile thethering) and if an user use VPN (we do not allow this support)
Luckily you solved it, because seeing the log is ok i wouldn't have had any other solutions to propose
