### ISSUE TITLE
Device crashes when playing Dolby Vision content in Netflix addon

### ISSUE THREAD

**Issue by marc-83** [CastagnaIT/plugin.video.netflix#1276]
#### Your Environment
- Netflix add-on version: 1.18.1
- Operating system version/name: Fire OS 7.2.4.2
- Device model:  Fire TV Cube 2nd Gen

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Whenever playing a video with Dolby Vision in the Netflix add-on the fire cube crashes after a while. The time it crashes varies between videos but within the same video it happens at the same point every time I play it. The time of the crash in different videos varies between a few minutes and 20 minuted. To recover the fire cube has to be restartrd. If I disable Dolby vision in the add-on settings I don't get the crash. It will play normal HDR videos fine. I also use the SlyGuy Disney+ add-on and Dolby Vision videos play correctly from that addon. Apologies if that isn't relevant but I thought it may show it does appear to be an add-on specific issue. Looking at my debug log I'm not sure if it writes anything useful because of the full device crash that happens at the time the video fails.

#### Expected behavior

Play Dolby Vision content without crashing

#### Actual behavior

The video stops playing and the whole device hangs and requires a restart. When it crashes it displays the current video frame and stops responding to all remote  control inputs. It happens on every Dolby Vision video I've played on Netflix. If I play the same video multiple times it crashes at the same point. Different videos crash at different times though. The time of the crash in different videos varies between a few minutes and 20 minutes.

#### Steps to reproduce the behavior

1. Have Dolby Vision enabled in Netflix addon settings
2. Play a video that uses Dolby Vision
3.

#### Possible fix

Only happens with Dolby Vision enabled. Plays normal HDR correctly. Other Dolby Vision content plays fine in other Kodi add-ons.

### Debug log

The debug log can be found here:

[kodi_2.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7660732/kodi_2.log)

**Comment by CastagnaIT** [comment]
crashes usually have to be fixed in Kodi the addon only takes care of providing the video "links" (very short summary)
but i would like to check two things

> If I play the same video multiple times it crashes at the same point.

1) try this:
open addon settings -> Playback -> Ask to skip intro and recap -> turn it off
play a video and see if crash happens

2) on addon Expert settings turn ON: Always show codec info during playback (turn on enable debug logging, if disabled)
when you are in playback you will see this info on screen:
![immagine](https://user-images.githubusercontent.com/3257156/144852956-53b98733-5e3e-4afc-a4d3-e6ee4ee7a0a4.png)

please check if the memory usage is about 100% when the crash occours

**Comment by marc-83** [comment]
> crashes usually have to be fixed in Kodi the addon only takes care of providing the video "links" (very short summary) but i would like to check two things
> 
> > If I play the same video multiple times it crashes at the same point.
> 
>     1. try this:
>        open addon settings -> Playback -> Ask to skip intro and recap -> turn it off
>        play a video and see if crash happens
> 
>     2. on addon Expert settings turn ON: Always show codec info during playback (turn on enable debug logging, if disabled)
>        when you are in playback you will see this info on screen:
>        ![immagine](https://user-images.githubusercontent.com/3257156/144852956-53b98733-5e3e-4afc-a4d3-e6ee4ee7a0a4.png)
> 
> 
> please check if the memory usage is about 100% when the crash occours

Thanks for the suggestions. Tried disabling skip into and recap option but still crashed. Memory usage was at 77% when it crashed. It sounds like one I need to log for the Kodi team to look at then.

**Comment by CastagnaIT** [comment]
yes try open an issue on kodi repository
