### ISSUE TITLE
Stream Type Selector for Resolution Limit

### ISSUE THREAD

**Issue by jakermx** [CastagnaIT/plugin.video.netflix#128]
*I'm submitting a ...*
  - [ ] bug report
  - [x ] feature request
  - [ ] support request

## General information

Theese Mods helps users to define a up to Resolution Limit, it is based on Manifest request, so RPi Users can leave InputStream Adaptive without changes si they can use higher Resolutions on other AddOns

Hope this help

### Addon version used

[eg. 13.21.0]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]
[StreamTypeLimit.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3384715/StreamTypeLimit.zip)

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Smeulf** [comment]
Can be usefull if you need to set Netflix to 480p and an another provider using lighter DRM to 720p indeed. Thanks.

Higher resolution on a RPi3 would be hard to decode IMO (720p can already be hard under some circumstances...)

Btw, you forgot to provide the languages files, so there's no way to tell what the options means...
Tou dropped a lsep on the settings that should not be dropped, and there's also a lot of loggin I can't understand: What does CGS means?

Would you please provide a more complete patch?

As an advice, you should really fork the repository and use Git/TurtoiseGit on your computer, push the changes on your repo, and then provide full PR here on GitHub. That would be very easier to read :D

**Comment by jakermx** [comment]
CGS...nope its CSG that stands for Cesar Salinas Garza.... my name

I will fork that... in a diferent repository, since I support 0.13.x and 0.14.0

Hope it helps... I just addthe languages in the new Zip on this post
[StreamTypeLimit.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3384809/StreamTypeLimit.zip)

**Comment by jakermx** [comment]
btw, I added more base profiles and some tail to them as well...

**Comment by Smeulf** [comment]
@jakermx just to be certain (I'm not very familiar with NF profiles).

If option is 0 (Video Strem Type (Up to...) value), what profiles do you remove?  All or none?

**Comment by jakermx** [comment]
0 is SD
1 os 720p
2 is 1080p
3 is 4k

so if you use 0, it will restrict content up to 719p resolutions

**Comment by jakermx** [comment]
you can verify if you enable manual stream selection inputstream adaptive, and then select Video option while playing something and list all the available streams

**Comment by Smeulf** [comment]
Well, for now I can't make it work under Windows 10, wathever the option I choose, it keeps showing me H264 720p...

**Comment by jakermx** [comment]
there are another ways to do the same

1.-Ask just for needed profiles, so the manifest file, will have lower size and the post processing too. (thisis what i did)
2.-Ask for alll the supported profiles and then remove the ones with video resolutions higher than filtered, this needs to  be done on the convert to dash process. 
3.-Limit the player , s we do via Input Stream Adptive 
4.-Limit the Interface and limit the player by the GUI
5.-Have Manual Stream Selection

**Comment by jakermx** [comment]
if you modify your existing installatiion, you need to set 

<setting id="StreamType">3</setting>

in your C:\Users\............\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix Directory, what I sent if for being modifiying before install it, so user settings files will be created, when open it for first time.

**Comment by jakermx** [comment]
> Well, for now I can't make it work under Windows 10, wathever the option I choose, it keeps showing me H264 720p...

Actually I do all my develptments on windows then migrate to linux x86, libreelec and Android for fine tunning.

**Comment by jakermx** [comment]
![SetSD](https://user-images.githubusercontent.com/45062549/61101979-a4fe6900-a431-11e9-93e4-8aaf6054d127.png)
![Set720](https://user-images.githubusercontent.com/45062549/61101980-a596ff80-a431-11e9-9fe0-44f0c4ebcc6e.png)
![Set1080](https://user-images.githubusercontent.com/45062549/61101981-a596ff80-a431-11e9-8ed0-a3cc488433c7.png)
![View1080](https://user-images.githubusercontent.com/45062549/61101982-a596ff80-a431-11e9-8b5d-909be939d111.png)
![View720](https://user-images.githubusercontent.com/45062549/61101983-a596ff80-a431-11e9-9c56-a4c188a18c7c.png)
![ViewSD](https://user-images.githubusercontent.com/45062549/61101984-a596ff80-a431-11e9-812b-2f776c397581.png)

**Comment by Smeulf** [comment]
I can't make SD working.

SD plays at 720p
720p plays at 720p
1080p plays at 1080p

See partial logs (I changed the debug captions from your original patch): https://paste.kodi.tv/afadawuvuf.kodi

**Comment by Smeulf** [comment]
![image](https://user-images.githubusercontent.com/1092948/61102218-422ac300-a46d-11e9-83ee-a836df09f49a.png)

**Comment by jakermx** [comment]
the power of opeerative comunnities.... I havent tested on vp9... let me try... need to remove L31 or higher to work...

**Comment by Smeulf** [comment]
Can you also add a 640p limit? As in input Stream?

**Comment by jakermx** [comment]
> Stream

ok.... let me do that.

**Comment by Smeulf** [comment]
For the record, I'm using auto stream selection in InputStream. So it will take the best stream avaliable.

For now, this is how the commit looks like: https://github.com/Smeulf/plugin.video.netflix/commit/a14ea0e207b7952f3ab340ccbcce5d3ce5d28239

I'll update it later in the day when you're done, and PR once tested and fully fonctionnal. Unless @CastagnaIT  wants to cherry pick it and do some stuff ;)

**Comment by Smeulf** [comment]
I also changed default to 3 (will be 4 if you can add the 640p limit) so users will have the best (4k) if they don't change that setting ^^ Or we may have complaints about quality ;)

**Comment by jakermx** [comment]
This is done, found a more stable way to do it, with a fallback option.

Look at Pull Requests

**Comment by jakermx** [comment]
Funcionallity added on PR
