### ISSUE TITLE
CFFI Error: Multiple declarations of function SHA256_init (LibreElec 10.0.1 x86/64)

### ISSUE THREAD

**Issue by cooperdk** [CastagnaIT/plugin.video.netflix#1282]
#### Your Environment
- Netflix add-on version: 1.8.2
- Operating system version/name: LibreElec 10.0.1
- Device model:  Intel NUC (x86/64)

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
On running the add-on, the error in the report title appears as attached in the log snippet.
The add-on fails.
Also, some settings in the settings editor are unresposive.
Other video clients work, including HBO Max.

#### Expected behavior
A functioning add-on.

#### Actual behavior
A broken add-on: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed.
An error message is displayed when running the addon.

#### Steps to reproduce the behavior
Install the add-on on LibreElec 10.0.1 Kodi 19.3 Matrix.
PS: Not tested on a clean install as I have no other hardware to do this on. 

#### Possible fix
Fix to handle double declaration. I am not sure what else calls the function and from where, but I would be happy to look deeper into it.

### Debug log
A new version has been uploaded with enabled plugin logging.
The error message is around line 1475.

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7730069/kodi.log)

**Comment by cooperdk** [comment]
The debug log was attached and as far as I can see, the rest of the report looks like the others here...

**Comment by CastagnaIT** [comment]
this error seem not related to addon but from your python package installed
i have not idea whats wrong in your libreelec

**Comment by cooperdk** [comment]
Neither do I as the installed Python package is the one included with LibreElec. There are no modifications to the base software.
I could try to run it in a VM and install Netflix to see if this will also fail..?

**Comment by CastagnaIT** [comment]
I wouldn't know what to suggest, you could try install an older version of LE
there is probably someone on the LE forum who knows best what to do

**Comment by cooperdk** [comment]
I did since this was an issue, and it didn't change anything in the default installation. The plugin doesn't work.
