### ISSUE TITLE
Unable to set English subtitles

### ISSUE THREAD

**Issue by jhonny-oliveira** [CastagnaIT/plugin.video.netflix#1283]
Hi!

I'm unable to set English subtitles. The only option available is Dutch, which I believe it is related to my language/locale settings.
In Netflix I have only configured English.

Any ideas on how to overcome this issue?

#### Environment
- Netflix add-on version: 1.18.2+matrix.1
- Operating system version/name: LibreElec 10.0.1
- Device model:  Raspberry-Pi 4

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7739045/kodi.log)

#### Screenshots
![IMG_20211218_101021261_MP](https://user-images.githubusercontent.com/10480527/146635924-690a97d0-c29c-4a1b-9342-6178d89b6043.jpg)

Thank you!
Jhonny

**Comment by CastagnaIT** [comment]
are you sure that this film is provided in several languages?
have you check if languages set in each netflix profile (in account settings) are right?
if these are not the cases, if you have not already done so try reboot the device

**Comment by jhonny-oliveira** [comment]
Dear @CastagnaIT ,

You are totally right! I crosscheck on the website and it also only shows Ducth. My bad! I should have cross checked it in advance.

Thank you very much for such an excellent plugin!
