### ISSUE TITLE
Plugin Error/Exception within Linux (Arch) and Python 3.10.1

### ISSUE THREAD

**Issue by patchedsoul** [CastagnaIT/plugin.video.netflix#1284]
#### Your Environment
- Netflix add-on version: 1.18.2+matrix.1
- Operating system version/name: 5.15.10-arch1-1
- Device model:  Kodi "Matrix" 19.3.0

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Plugin is causing latest Kodi "matrix" to crash due to Python 3.10.1 changes. This appears to possibly be part of a larger issue then just this plugin: 
https://bbs.archlinux.org/viewtopic.php?id=272121 for additional details.

#### Expected behavior

Plugin installs and works as expected

#### Actual behavior

Installing plugin crashes Kodi

#### Steps to reproduce the behavior

1. Install plugin on up to date archlinux system

### Debug log

The debug log can be found here:
(https://paste.kodi.tv/zubulohaxi.kodi)

#### Other information

Attempted to downgrade python from 3.10.1 to 3.10.0 as purported workaround. Kodi no longer crashes, but the following error is thrown within the plugin:
https://paste.kodi.tv/ubigapiqad.kodi

**Comment by putridpete** [comment]
In my case, under Arch, Kodi starts just fine with python 3.10.1, but the Netflix plugin does not. Even after reinstalling the aforementioned python dependencies. This plugin itself is not offered in the official packages or even the AUR so I'm not sure where to report it on the Arch side. Although I do suspect this is more likely a python issue like you've said.

**Comment by CastagnaIT** [comment]
same issue have others addons that use same py module
seem to confirm that the bug is somewhere in the python version

**Comment by TheJackiMonster** [comment]
In my case the repository installed. The video addon was installed as well but if I try to start the addon, it crashes kodi with a segfault. [kodi_crashlog-20211228_172056.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7785579/kodi_crashlog-20211228_172056.log)

**Comment by putridpete** [comment]
So I've found a solution (as per [here](https://bbs.archlinux.org/viewtopic.php?pid=2012681#p2012681) and [here](https://bbs.archlinux.org/viewtopic.php?pid=2013955#p2013955)) to get the plugin working again under Arch. If you go into `/usr/lib/python3.10/sqlite3` and uncomment the following lines:

>     #register_adapter(datetime.date, adapt_date)
>     #register_adapter(datetime.datetime, adapt_datetime)
>     #register_converter("date", convert_date)
>     #register_converter("timestamp", convert_timestamp)
the plugin doesn't crash anymore.

**Comment by CastagnaIT** [comment]
python bug has been fixed in python 3.10.2-1
