### ISSUE TITLE
[Chromebook] MSLError: This title is not available to watch instantly CHROMEBOOK ONLY

### ISSUE THREAD

**Issue by nonobio** [CastagnaIT/plugin.video.netflix#1286]
#### Your Environment
- Netflix add-on version: 1.18.2+matrix.1
- Operating system version/name: Chrome OS 96.0.4664.111 (Build officiel) (32 bits)
- Device model:  Acer Chromebook R 13 CB5-312T-K62F

Used Operating system:
* [x] Android (Android app support but the operating system is "Chrome OS")
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Hello,

When I try to play a video, I have the "MSLError: This title is not available to watch instantly"
Please try another title.
To try to solve this problem you can force "Widevine L3" from the add-on Expert settings.

I tried to apply the L3 ESN but the issue is the same.

The ESN isn't the same than the one in my Netflix Android app so i tried to enter it manually in the add-on ESN setting but it said "ESN cannot be used" or something like this. But maybe I made an error : it's a very long code and the copy paste doesn't work.

Thanks :)

#### Expected behavior

The video should be played :) .

#### Actual behavior

I have an MSLError.

#### Steps to reproduce the behavior

1. Open the add-on
2. Browse Netflix
3. Launch a video

### Debug log

The debug log can be found here:

https://paste.kodi.tv/denuyenate.kodi

[### Additional context or screenshots (if appropriate)

#### Other information

Actually I have two issues with the Netflix add-on I just installed on my Chromebook, this is the second:

https://github.com/CastagnaIT/plugin.video.netflix/issues/1285

**Comment by betatester3016** [comment]
Confirmting "MSLError: This title is not available to watch instantly" persists after latest Netflix Addon update.

**Comment by heini** [comment]
Same here, Kodi 19 (LibreElec). Tried to follow instructions to force L3 in `ENV/Widevine` settings, but that's not even selectable/changeble (is set to "Disabled").

**Comment by gc-robotics** [comment]
Same here, Kodi 19 on RPi4. And I confirm the lack of option to force L3 in the plugin.

**Comment by betatester3016** [comment]
I ran into the same issue with CoreELEC 19.3. A clean install of CoreELEC and Netflix Addon fixed the issue.

**Comment by CastagnaIT** [comment]
i suspect that the esn generation could be wrong for the chromebook, i need more info:
- on expert setting open "Widevine/esn settings", then "save system info" and attach here the file
- install the official nfx app take a screenshot of the esn from the app settings (censure only few last chars)

**Comment by nonobio** [comment]
Hi @CastagnaIT :),

Sorry for my late reply.

This is the SystemInfo file:

[NFSystemInfo.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/7821297/NFSystemInfo.txt)

And this is the screenshot:

![image](https://user-images.githubusercontent.com/7425799/148373393-2910c5f7-2da8-47ec-b712-503c0e73e669.png)

Thanks

**Comment by Tijger362** [comment]
Same issue here on Windows 10

**Comment by dommy67** [comment]
Plugin worked until 25th Jan 2022, tried to use it tonight 28th and no joy kept getting the same MSLError , but no indication of how to fix it. Only extra info is from CCurlFile::FillBuffer - Failed HTTP returned error 500.
Kodi v 18.9 running on PC on Linux Mint 20.3 64bit version, Intel Core 2 Quad cpu 2.4GHz
Plugin video netflix v1.12.8

Rgrds Peter

**Comment by CastagnaIT** [comment]
@nonobio sorry for the big delay, but this is not the only project i follow
you are the first user to notify me of chromebook use, i am not sure that this fix test will works:

1) uninstall the addon and also remove settings when prompt
2) install this test [plugin.video.netflix_1.18.3+matrix.1_20220128_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/7961316/plugin.video.netflix_1.18.3%2Bmatrix.1_20220128_t1.zip)
3) try play

let me know what happens, and if fails provide also a new NFsysteminfo file

----

to all other users this issue is a special case for Chromebook device, other cases will not be taken into account

**Comment by lameventanas** [comment]
> Plugin worked until 25th Jan 2022, tried to use it tonight 28th and no joy kept getting the same MSLError , but no indication of how to fix it. Only extra info is from CCurlFile::FillBuffer - Failed HTTP returned error 500. Kodi v 18.9 running on PC on Linux Mint 20.3 64bit version, Intel Core 2 Quad cpu 2.4GHz Plugin video netflix v1.12.8
> 
> Rgrds Peter

Same here, but with an Odroid C2 (arm) running the netflix plugin 1.12.8
Tried with different versions of widevine that were backed up, tried logging out & in, nothing works :(

**Comment by nonobio** [comment]
Hi @CastagnaIT ,

Don't worry about the delay, it isn't urgent and I understand you don't have only my problem to solve ;) . By the way, thanks again for this add-on.

I did what you said but the issue is the same.
This is the new NFsysteminfo file : 
[20220201_NFSystemInfo.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/7978897/20220201_NFSystemInfo.txt)

Thanks :)

**Comment by b4zyl** [comment]
Got same MSLError error since today's morning on two devices (Android Projector and raspberrpi 4 - Raspbian GNU/Linux 10 (buster)).

**Comment by Tudwall** [comment]
Got it too at about the same time, I'm running LibreElec with Kodi 18.9 on a raspberry pi 4

**Comment by lymon66** [comment]
Also have this error as of today, on several different devices running Libreelec and Coreelec , both Kodi 18.9

**Comment by Sholander** [comment]
@b4zyl, @Tudwall , @lymon66  - Try with [this solution](https://github.com/CastagnaIT/plugin.video.netflix/issues/1281#issuecomment-1026597384). It worked for me OdroidN2/CoreElec

**Comment by cormacwilcox** [comment]
I can confirm that this error started today on Raspbian buster, Kodi 18.7 on a raspberry pi 4

**Comment by CastagnaIT** [comment]
please stop spam this thread for kodi 18

**Comment by daggs1** [comment]
I'm not sure it is a chromebook issue, I ahve the same issue o rpi4, LE 9.2.8, netflix v1.12.8

**Comment by heini** [comment]
So do I, see above.

**Comment by tschabha** [comment]
The same is happening with my installation: LE 9.2.8 w Netflix plugin v1.12.8 (the latest in Leia repository). Attached is the debug log. 
Why Netflix is doing it to its service....???
[kodi20220202.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7997320/kodi20220202.log)

**Comment by CastagnaIT** [comment]
@nonobio please try install from scratch (same steps above)
[plugin.video.netflix_1.18.4+matrix.1_20220213_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8055234/plugin.video.netflix_1.18.4%2Bmatrix.1_20220213_t2.zip)
 
 If it still does not work, unfortunately i have no other solutions,
 out of curiosity the "Playback specification" on ntfx android app say HD or SD?

**Comment by nonobio** [comment]
Hi @CastagnaIT ,

I just tried the 1.18.4 : I have this error : "MSLError: Request failed validation during key exchange."

"Playback specification" say "SD".

Thanks for your help.
