### ISSUE TITLE
Unable to watch in 1080p

### ISSUE THREAD

**Issue by dmu7004** [CastagnaIT/plugin.video.netflix#1287]
Hi CastagnaIT,

Happy Xmas :) 
Sorry for my english...

This is my config :
- Netflix add-on version: v1.18.2
- Operating system version/name:  LibreElec 10.0.0 (Kodi 19.1.0)
- Device model:  Raspberry pi4+ 8Go

I can't watch videos in 1080p i have only 540p.
I have found an explanation about ESN number  and then I have tried to change the ESN but I don't know what I must do.
The actual ESN is : NFCDCH-01-xxxxxxxxx....... If I change NFCDCH to NFCDCH1 I h"ave an error from Widevine.

Can you help me ?

Thanks

Dan

**Comment by Thunderbird2086** [comment]
looks like the same issue as #1281

**Comment by dmu7004** [comment]
oups thank you
