### ISSUE TITLE
Kodi close unexpectedly after few minutes, usually 5 or 10 minutes

### ISSUE THREAD

**Issue by chrisnikol** [CastagnaIT/plugin.video.netflix#1288]
#### Your Environment
- Netflix add-on version: 
1.18.2+Matrix.1, Kodi version 19.3 64bit
- Operating system version/name: 
Win11 64 bit
- Device model:  
pc

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [X ] Windows

### Describe the bug

When i watch something with Netflix addon after a while usually 5 with 10 minutes the kodi just close with no error code.
This is happening only with netflix addon and not with any other addon.

#### Expected behavior

The addon to keep playing the video and kodi not to close unexpectedly.

#### Actual behavior

The kodi close unexpectedly after a while, usually after 5 with 10 minutes.
I included the link from a 30 sec video who show the behavor at screenshoot section

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:

I enable the debug log at kodi open kodi and use only the netflix addon but the produced kodi log is to big to be able to use the paste.kodi.tv service. The whole log you can found it here: https://1drv.ms/u/s!Akob19GUPpoBj5lblsrK0oxtnfW1hw?e=VA7rLN
[kodi(1).log](https://github.com/CastagnaIT/plugin.video.netflix/files/7783692/kodi.1.log)

#### Screenshots

A small video about 30 sec who show the problem. The Kodi in reality close after 10 minutes but i just kept the part who show the kodi to close unexpectedly

https://youtu.be/pbIRP4GHfHc

**Comment by CastagnaIT** [comment]
this is something of unmanaged on Kodi side that cannot be fixed by this addon
suggest you to open an issue on Kodi repository

**Comment by chrisnikol** [comment]
After some trial and error i think i found why this was happening.

I am using the advanced settings file and there i had set the cache to be made at the hd. the tag memorysize was set to 0.

After your response to my bug report, i tried not to use the advance settings file at all, by change the extension.
Like this i managed to see an 1 hour episode without the kodi to close unexpectedly.

Then i use the advanced settings but  i disabled all the cache block by make all the block comment. Like that i used the addon with no problem.

After, i set the memoryy size at 500Mb my pc has 16Gb Ram. Like that the kodi closed unexpectedly at 30 minutes.

At Last i tried to set the cache size at 100 Mb. Like that i watched so far 4 episodes without any issue.

So right now it seems that the cache setting was causing the problem.

Thank you for your help, but mostly thank you for all your dailly hard work to make and support the addon. I founed much more convinient than the official apps from Netflix.

**Comment by CastagnaIT** [comment]
thanks for sharing your solution
