### ISSUE TITLE
Filtering based on sub-categories' IDs

### ISSUE THREAD

**Issue by NZ-Git** [CastagnaIT/plugin.video.netflix#1289]
## Feature request
I'm submitting a proposal to ...
  - [X] new feature
  - [ ] change an existing feature

### Describe your request

Add "Filter by Genre ID" item to incorporate filtering based on the various sub-categories' IDs ( https://www.netflix-codes.com )
Such item could be listed on the main user-screen and  show the following

* Movie genres
* TV Show genres
* ...
* ...
* Filter by Genre ID
| - - **Action & adventure (1365)**
| - - Action comedies (43040)
| - - Crime action & adventure (9584)
| - -  [ . . . ]
| - - Anime (7424)
| - - Anime Sci-Fi (2729)
| - - Anime action (2653)
| - - [ . . . ]

#### Describe the use case

I recently came across the IDs of the various genre subcategories. Using these IDs and the "Search" function one can "filter" the results to that specific sub-category. The plugin's search function seems compatible with the IDs so it would be nice is there was a "Filter by Genre ID" option alongside "Movie genres", "TV Show genres", etc

#### Describe an alternative

Alternative would be to use the ID directly in the "search" but remembering, or storing and retrieving these IDs makes it unpractical. 

#### Development tips

Each sub-category item can simply call the "search" function with the appropriate ID.

**Comment by CastagnaIT** [comment]
what you describe is already done in the Search menu, where you can add your favourite ID's and the appropriate name is automatically retrieved,
if you do not want browse by ID you can use all other menus no new menu will be add

**Comment by NZ-Git** [comment]
Fair enough. Many thanks for the fab work so far!
