### ISSUE TITLE
Fix watch next continous play of tv shows

### ISSUE THREAD

**Issue by loggin** [CastagnaIT/plugin.video.netflix#1292]
You need to fix the watch next continous playback of tv show episodes, either by removing the completely redundant pop up that asks for your netflix (you already set it for the import) or cache the setting at the start of a viewing session.

It's gotten to the point I've given up with the plugin to watch tv shows and have reverted back to the app on the tv.

**Comment by CastagnaIT** [comment]
please provide exaclty steps you doing to start the playback (what menus used)
and provide a debug log by follow the instructions in github main page readme

**Comment by ValentijnDemeyer** [comment]
Hi,
Thanks for answering. 
Best to mention up front that the Up next addon is up to date, also the feature that already watched episodes and playlist is enabled.

I activated the addon accordingly: Settings --> Addon -->My addons --> Netflix --> configure --> Playback (left menu) --> enable Up Next integration (bottom)

start watching an episode: Addons (main menu) > Netflix  -->select profile  --> my list --> Brooklyn Nine Nine --> season that I haven't watched (6) --> first episode --> watch  --> after the episode Kodi returns to the main menu.

Log file attached.
[log-2022-02-13-22.03.25.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8056771/log-2022-02-13-22.03.25.zip)

Kind regards,
Valentijn

**Comment by CastagnaIT** [comment]
@ValentijnDemeyer appears to be an UpNext addon bug
we have to wait they release the new version

**Comment by ValentijnDemeyer** [comment]
Great, thanks for the support.

**Comment by theoden11** [comment]
Hi. UpNext will have a release in the next days I suppose. I've tried the beta 1.1.6 release (for Leia and old python) with little mod for matrix with success on my Vero OSMC, and now the notifications work and the Next episode too. As many people, UpNext was not working anymore with Netflix and so on, with the 1.1.6 it seems to work. So be patient.

**Comment by CastagnaIT** [comment]
elapsed long time but finally has been published a new upnext version 1.1.8 with many fixes
i think this can be now closed
