### ISSUE TITLE
Can you set the added to kodi library to that set in netflix?

### ISSUE THREAD

**Issue by loggin** [CastagnaIT/plugin.video.netflix#1293]
## Feature request
I'm submitting a proposal to ...
  - [ x] new feature
  - [ ] change an existing feature

### Describe your request
If the date an item is added to the netflix watch list, set the strm files created/modified dates to this

#### Describe the use case
I've recently had to reimport my netflix library and can see some repeat offenders being added as new during subsequent updates this bumps newer items down in the recently added screen (My first port of call when choosing what to watch), it is my understanding that kodi uses the file dates to determine the added to library date so if you can access the netflix added to watchlist would it be possible to set strm files dates to this?

**Comment by CastagnaIT** [comment]
is possible that set a oldest "modified file date/time" to the STRM files could works
but i dont know if kodi have a python module interface to change date/time to files
is needed to check and test it
