### ISSUE TITLE
No module named 'Cryptodome'

### ISSUE THREAD

**Issue by pal7769** [CastagnaIT/plugin.video.netflix#1294]
#### Your Environment
- Netflix add-on version: 1.18.3+matrix.1
- Operating system version/name: Kodi 19.3
- Device model:  Raspberry Pi 3 Model B+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Opening Netflix Add-on leads to the following screen :
Netflix Add-on Error

The add-on encountered the following error:
The background services cannot be started due to this problem:
In you system is missing some required library to run Netflix.
Read how to install the add-on in the GitHub Readme.
Error details: cannot import name 'Padding' from 'Crypto.Util'
(/usr/lib/python3:dist-packages/Crypto/Util/__init__/py)

#### Expected behavior
Netflix add-on opening.

#### Actual behavior
Error page displayed

#### Steps to reproduce the behavior
Following CastagnaIT installation guidance and launch add-on from Add-on browser.

### Debug log

The debug log can be found here:
[kodi.old.log](https://github.com/CastagnaIT/plugin.video.netflix/files/7829066/kodi.old.log)

### Additional context or screenshots (if appropriate)

Thanks a lot for your help !

**Comment by mattiasdh** [comment]
I confirm this bug, on a fresh install of the latest OSMC version, 2021-12.1.

The OSMC log files can be found here: https://paste.osmc.tv/popagoqevu

Previously the Netflix plugin worked on this setup (installed on previous version, upgraded to 2021-12.1). 

PS: Building pycryptodomex gives an error, but completes succesfully:
`sudo pip3 install pycryptodomex
Collecting pycryptodomex
  Using cached https://files.pythonhosted.org/packages/f6/06/e2ad9e93210790be86d36c6e2d5524ba54928c3ed27dd0be9b2ced7c57f1/pycryptodomex-3.12.0.zip
Building wheels for collected packages: pycryptodomex
  Running setup.py bdist_wheel for pycryptodomex ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wnyjtklo/pycryptodomex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-pz0u3xes --python-tag cp37:
  Testing support for clang
  Target does not support clang
  Testing support for gcc
  Target does support gcc
  Testing support for stdint.h header
  Target does support stdint.h header
  Testing support for 128-bit integer
  Target does not support 128-bit integer
  Testing support for cpuid.h header
  Target does not support cpuid.h header
  Testing support for intrin.h header
  Target does not support intrin.h header
  Testing support for posix_memalign
  Target does support posix_memalign
  Testing support for SSE2(intrin.h)
  Target does not support SSE2(intrin.h)
  Testing support for SSE2(x86intrin.h)
  Target does not support SSE2(x86intrin.h)
  Testing support for SSE2(emmintrin.h)
  Target does not support SSE2(emmintrin.h)
  Testing support for gcc
  Target does support gcc
  Warning: compiler does not support AESNI instructions
  Warning: compiler does not support CLMUL instructions
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pycryptodomex
  Running setup.py clean for pycryptodomex
Failed to build pycryptodomex
Installing collected packages: pycryptodomex
  Running setup.py install for pycryptodomex ... done
Successfully installed pycryptodomex`

**Comment by JarCme** [comment]
I also confirm this bug. I received the same output as @mattiasdh during the pycryptodomex build on the latest OSMC.

**Comment by mattiasdh** [comment]
> Had the same issue today on my Raspverry Pi 4 after an upgrade to Kodi 19.3 and Castagna's Netflix 1.18.3. This is how I was able to fix it:
> 
> * `sudo pip install pycryptodome`
>   followed by
> * `sudo pip3 install pycryptodomex`
> * `reboot`
> 
> Hope that helps in your case too.

I confirm this worked. Had to install setuptools for python2 first, so pycryptodome could install. There must still be some python2 dependencies.. 
Thanks!

**Comment by pal7769** [comment]
> Had the same issue today on my Raspverry Pi 4 after an upgrade to Kodi 19.3 and Castagna's Netflix 1.18.3. This is how I was able to fix it:
> 
> * `sudo pip install pycryptodome`
>   followed by
> * `sudo pip3 install pycryptodomex`
> * `reboot`
> 
> Hope that helps in your case too.

Workfing fine, thanks so much !

**Comment by PackElend** [comment]
how to you got pip to work?
I get 
```
osmc@osmc:~$ pip 
-bash: pip: command not found
osmc@osmc:~$ pip3
-bash: pip3: command not found
```

**Comment by PackElend** [comment]
> is a problem of the python module or something on OSMC

is that reported to the upstream projects as it still exists?
