### ISSUE TITLE
TypeError init missing two keywords request and response

### ISSUE THREAD

**Issue by gc-robotics** [CastagnaIT/plugin.video.netflix#1296]
Is this plugin working? It stopped a long while ago for me

**Comment by maretodoric** [comment]
You're probably trying to run it from main menu instead from Addons then Netflix directly.
If that's the case, you also probably at some point switched netflix account or deleted a profile and your menu is configured to access profile that is no longer there so it errors out.

Try to recreate the menu option from skin settings.

**Comment by CastagnaIT** [comment]
If you have a bug to report please fullfill the bug template form
this cannot be accepted
