### ISSUE TITLE
TypeError missing 2 required keyword-only arguments when launching from main menu

### ISSUE THREAD

**Issue by maretodoric** [CastagnaIT/plugin.video.netflix#1297]
#### Your Environment
- Netflix add-on version: 1.18.3+matrix.1
- Operating system version/name: LibreELEC 10
- Device model:  Raspberry Pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
I have a shortcut to netflix addon added to main menu of Aeon Nox skin. Occasionally, when running Netflix from main menu i get python exception TypeError missing 2 required keyword-only arguments request and response

#### Expected behavior
Should open Netflix

#### Actual behavior
Get TypeError

#### Steps to reproduce the behavior
1. Run netflix from main menu

#### Possible fix
Cannot figure it out but it appears that once i launch Netflix addon normally and choose my profile (enter pin) i can then launch Netflix just fine from main menu. Until some time or next reboot.

### Debug log

The debug log can be found here: https://paste.kodi.tv/ulademibar.kodi

**Comment by maretodoric** [comment]
I spoke too soon. My menu was created so when i enter Netflix it will open a specific profile.
That profile is no longer there as i now use another netflix account so when i try to access it i get HTTP 500.
Not sure why it works after i open Netflix addon specifically, probably caches the current active profile then works

**Comment by CastagnaIT** [comment]
The widget shorcuts are not fully supported with this addons and no support will be provided
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits

**Comment by Joshyakadamien** [comment]
This is a big BS.
Been using it with widgets now for the 2nd year almost.
And the issue started to pop up only a week ago.
I dismantled the widgets attached to the addon due to the explanation.
rebooted, even reinstalled starting from repo level, and still get the error.
Try to look into it rather than bouncing the error down blaming the widget structure.

**Comment by Joshyakadamien** [comment]
Let's try this again as my comment vanished.
This is a big BS
Using the addon for the second year now with widgets no probs.
Now suddenly this error pops up since the last week.

Have only one profile, never changed it.
Disabled the widgets, reinstalled from the repo level, and still the error is present regardless that it is being launched from the addons menu.
 The issue needs to be fixed rather than blaming it on the widget structure.

**Comment by Joshyakadamien** [comment]
and yeah i'll keep on posting this as the removal suggests that it is annoying.
It is just as annoying that the addon cannot be used.

**Comment by farkaslory** [comment]
I have the same issue. Until now, the addon worked perfectly, today do not start. I have multiple accounts and my widgets can select from the accounts. The selection appears correctly but no account can start.
 I says:
"TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response' "

**Comment by farkaslory** [comment]
My system was a LibreElec on Rpi4...

**Comment by Joshyakadamien** [comment]
i am running libreelec 10.0.2 official
on intel x86_x64
Changed even skins back to factory and did a clean install still the same error.

**Comment by 0oWeZo0** [comment]
This also started randomly for me about a week ago... but I am running on Windows.

I restored a full kodi backup from before the error and still has a problem....

This issue is definitely upstream.

**Comment by Joshyakadamien** [comment]
@CastagnaIT you might want to reconsider the closure and will not be worked on thing now i suggest

**Comment by GTP95** [comment]
I'm also facing the same problem, it doesn't happen always but when it happens it seems to not work for a long time (the error keep occurring, also after rebooting my raspberry pi 3). Here is the full [log](http://ix.io/4bVM), but this is the stack trace of the error taken from them:
```
ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 245, in run
                                                       success = route(pathitems)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 87, in lazy_login_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 127, in route
                                                       _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 156, in _execute
                                                       executor(pathitems=pathitems)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 28, in set_custom_viewmode
                                                       override_content_type = func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 102, in home
                                                       dir_items, extra_data = common.make_call('get_mainmenu')  # pylint: disable=unused-variable
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 115, in make_http_call
                                                       _data = pickle.loads(received_data)
                                                   TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'
```
@CastagnaIT do you have any idea how we could fix this? I'm inclined to think it's a bug as multiple people are facing it now, but maybe we all did some mistake without realizing it. 
Thank you for your help,

GTP

**Comment by 0oWeZo0** [comment]
> @CastagnaIT you might want to reconsider the closure and will not be worked on thing now i suggest @farkaslory , @0oWeZo0 can you confirm that you have dismantled widgets as well if you used any please?

I do not use any widgets etc. I'm on Windows, don't even know how I would get one on Windows version.

Restoring backups usually resolves errors.....🤷

**Comment by Joshyakadamien** [comment]
seems like we have already 3 bugs for the same error reported:
This seems the most active:
https://github.com/CastagnaIT/plugin.video.netflix/issues/1425#issue-1388217285
 and we have this as well:
 https://github.com/CastagnaIT/plugin.video.netflix/issues/1432#issue-1392875748
 
 Let's not complicate the dev's work and stick to the most active thread i suggest.

**Comment by 0oWeZo0** [comment]
> seems like we have already 3 bugs for the same error reported: This seems the most active: [#1425 (comment)](https://github.com/CastagnaIT/plugin.video.netflix/issues/1425#issue-1388217285) and we have this as well: [#1432 (comment)](https://github.com/CastagnaIT/plugin.video.netflix/issues/1432#issue-1392875748)
> 
> Let's not complicate the dev's work and stick to the most active thread i suggest.

Understood. Which one should we follow?

**Comment by Joshyakadamien** [comment]
#1425 is the most productive
https://github.com/CastagnaIT/plugin.video.netflix/issues/1425#issue-1388217285

**Comment by 0oWeZo0** [comment]
👍

**Comment by Joshyakadamien** [comment]
this test build seems to work so far, please try it and report your findings in the corresponding thread
https://github.com/CastagnaIT/plugin.video.netflix/issues/1425#issuecomment-1263436335

**Comment by farkaslory** [comment]
I confirm that the bug is present, even without any widgets.
