### ISSUE TITLE
Playback services frozen

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#130]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information
Playback services are frozen if the skip section is not clicked but closed by alarm.

### Addon version used
Last master at today.

### Steps to Reproduce

1. Play any episode, the skip dialog pops up
2. Don't click, let it get closed by alarm
3. Stop the episode
4. Play another episode -> skip dialog won't show, StreamContinuity won't work anymore, any services won't pass _on_tick anymore.

## Context (Environment)
Platform independent

## Debug log

I added som extra debug code so we can see it better: 
once `dlg.doModal()` in xmldialogsshow_modal_dialog is called, the services won't keep ticking,, it's locked on this instruction until the dialog is clicked. If the dialog is closed by alarm, the service remains frozen.

Search for "_on_tick" in the logs to get it faster. Sorry about the log format, it's over limits.

[kodi.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3388823/kodi.zip)

**Comment by CastagnaIT** [comment]
it is not beautiful but i think it can go well

**Comment by Smeulf** [comment]
No sure it's more a hack than anything, bit at least it works. Thanks.
