### ISSUE TITLE
While attempting to "Play From Here" via Kore, "Due of Kodi 19 bug has been disabled..."

### ISSUE THREAD

**Issue by sdaau** [CastagnaIT/plugin.video.netflix#1301]
#### Your Environment

- Netflix add-on version: v1.18.3+matrix.1
- Operating system version/name: Android 9.0.0 API level 28
- Device model:  

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I'm using Kore on Android, with Kodi 19.3 on Android (different device), and Netflix addon.

Kore can retrieve Netflix episodes as a list, for entries of which Kore gives several options: "Queue", "Play", "Play Locally", "Play from Here".

I want to use "Play from Here", as then it should play all the episodes thereafter in sequence one after another (at least, that is how it seems to work in CuriosityStream addon).

If I hit "Play from Here" on a Netflix video (episode in a series) while nothing is playing in Kodi, Kodi crashes - this is not what this report is about.

Namely, I can workaround that, by first hitting "Play" on an episode, wait for it to start playing, and then afterward do "Play from Here", which then indeed starts playing the episode.

However, once the time comes to switch (I guess), the Netflix addon breaks, I guess, and puts this message as a notification in Kodi:

> Due of Kodi 19 bug has been disabled: Ask to skip dialog, remember audio/subtitles preferences and other features

I did manage to capture the log from when this breakage happens, it is here: https://paste.kodi.tv/toricunena.kodi

I've tried to also the UpNext addon, in hopes that it would help with this situation, but no ...

Btw, considering the mesage speaks of "disabling" functionality - is it possible to somehow enable it again, without uninstalling and reinstalling the addon?

#### Expected behavior

If I press "Play from Here" from an episode in Netflix addon via Kore, episode should start playing, and once its done, all the subsequent episodes should also play.

#### Actual behavior

Netflix addon breaks with a notification, and upon that, playback stops (thereafter, playback always exits after the first episode is done playing.

#### Steps to reproduce the behavior

1. Open Netflix addon in Kore
2. Tap Content tab, search for a series
3. Tap on the series, a list of episodes is shown
4. Tap on hamburger menu of an episode, hit Play (to workaround the crash bug described above)
5. Once episode is playing, tap on hamburger menu again (either of same or of different episode), hit "Play From Here"
6. Wait until addon fails, and playback stops after first episode

#### Possible fix

Don't know

### Debug log

The debug log can be found here:

https://paste.kodi.tv/toricunena.kodi

**Comment by CastagnaIT** [comment]
> Due of Kodi 19 bug has been disabled: Ask to skip dialog, remember audio/subtitles preferences and other features

this message is due to an unresolved bug in Kodi 19 cannot be solved by the addon and there is not way to workaround this

> Kore can retrieve Netflix episodes as a list, for entries of which Kore gives several options: "Queue", "Play", "Play Locally", "Play from Here".

can you explain me where are these options in Kore? and/or steps on how get them?
because on mine, only the option to "play" is presented on the episode list

**Comment by CastagnaIT** [comment]
closed due to inactivity
