### ISSUE TITLE
Kodi 18 (Leia): MSLError: This title is not available to watch instantly - RasPi

### ISSUE THREAD

**Issue by tschabha** [CastagnaIT/plugin.video.netflix#1304]
## Bug report
This is to separate the issue from a similar issue experienced on CHROMEBOOK, Kodi 19 (https://github.com/CastagnaIT/plugin.video.netflix/issues/1286)

#### Your Environment
- Netflix add-on version: 1.12.8
- Operating system version/name: LibreElec 9.2.8, Kodi 18
- Device model: RasPi, but according to comments in bug report https://github.com/CastagnaIT/plugin.video.netflix/issues/1286 , this is not device specific, 

Used Operating system: neither it is operating system specific
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Since 2nd February 2022 I have been experiencing the next issue: when I try to play a video, I have the "MSLError: This title is not available to watch instantly. Please try another title."
Before that date everything had been working fine. Did not change anything in configuration....

#### Expected behavior
Should play the title...

#### Actual behavior
"MSLError: This title is not available to watch instantly. Please try another title."

#### Steps to reproduce the behavior

    1. Open the add-on
    2. Browse Netflix
    3. Launch a video

### Debug log

The debug log can be found here:
[kodi20220202.log](https://github.com/CastagnaIT/plugin.video.netflix/files/8000585/kodi20220202.log)

**Comment by kdmdcjf** [comment]
Open addon Expert settings and Change "MSL manifest version" setting to original value.

**Comment by krom54** [comment]
watch here : https://github.com/CastagnaIT/plugin.video.netflix/issues/1300

**Comment by bpilsl** [comment]
working workaround:
https://github.com/CastagnaIT/plugin.video.netflix/issues/1300#issuecomment-1029561650

**Comment by tschabha** [comment]
Thanks go to krom54 and bpilsl for reacting! The proposed solution is https://github.com/CastagnaIT/plugin.video.netflix/issues/1300 did work!
Closing the issue....
