### ISSUE TITLE
Add support to proxy

### ISSUE THREAD

**Issue by et2010** [CastagnaIT/plugin.video.netflix#1315]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

Add an option to enable proxy so that users can set up proxy in kodi settings and visit Netflix through the proxy. (The youtube plugin has this ability.)

#### Describe the use case

In some countries like mainland China, Netflix is banned by the gov. Proxy/VPN is the only way for us to access Netflix. Could you consider adding an option to enable proxy so that those who have to visit Netflix from those countries can enjoy this excellent plugin at their own risk?

#### Development tips

If you agreed, I would love to help. But since I didn't have too many experiences in this domain, any pointers will be appreciated.

**Comment by CastagnaIT** [comment]
your answer here:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy
