### ISSUE TITLE
Lags of Video & Audio / many interruptions in video stream

### ISSUE THREAD

**Issue by neukrisz** [CastagnaIT/plugin.video.netflix#1321]
#### Your Environment
- Netflix add-on version: v1.12.9-Leia
- Operating system version/name: CoreElec v9.2.8 (standard and ng too) Kodi 18.9 Leila
- Device models:  
Minix Neo U1 (S905 SoC - huge lags)
Odroid C2 (S905 SoC - huge lags)
Khadas VIM3L (S905D3 SoC - minor lags)

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
We have playback problems when playing movies from Neflix :(
Many interruptions in video stream (and audio as well)
During payback when we check the codec info display [Ctrl+Shift+O] CPU/Mem. usage there's nothing strange until the lagging . when the #4 CPU core will be almost 100%. (on both tested S905 devices)
On the VIM3L device with much stronger SoC (S905D3) the phenomenon is less visible - but there's lags too - so the picture isn't fluent and not enjoyable 
I tested all three different hardware in different internet connections too / different places - with several reinstalled (fresh) CE OS too.
The problem is existing everywhere - for me and my two friend too.

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:

**Comment by CastagnaIT** [comment]
seem to be a recent Widevine problem, you can follow this thread to try revert back to an old widevine version
https://github.com/xbmc/inputstream.adaptive/issues/877
If this solution doesn't work, it's not something that this addon can solve

**Comment by neukrisz** [comment]
> seem to be a recent Widevine problem, you can follow this thread to try revert back to an old widevine version [xbmc/inputstream.adaptive#877](https://github.com/xbmc/inputstream.adaptive/issues/877) If this solution doesn't work, it's not something that this addon can solve

Many - many thanks for your help!
This method worked fine for us:
"Install any add-on from Slyguy Repo (https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html)
And then go to Add-ons > services > slyguy common > advanced > re(install) widevine CDM
Then select 4.10.2252.5"

The picture is fluent again ;)

**Comment by qurm** [comment]
This downgrade of Widevine also fixed the lagging problem for me on Raspbian, Pi 3B, Kodi 19.3.

**Comment by aannenko** [comment]
Installed SlyGuy Common add-in directly, then downgraded Widevine to 4.10.2252.5 - no change. Video stream still goes slower then the audio, visually stuttering, and the difference between audio and video grows longer and longer with time. When I put it all on pause, the video stream keeps playing until it reaches a point when it's in sync with the audio.

The above is true for a fairly clean LibreELEC 10.2 with Kodi 19.4 and 1.18.8+matrix.1
