### ISSUE TITLE
Sound and picture out of sync

### ISSUE THREAD

**Issue by kocicky** [CastagnaIT/plugin.video.netflix#1324]
#### Your Environment
- Netflix add-on version: v1.18.4+matrix.1
- Operating system version/name: Open Source Media Center 2021.12-1, Kodi 19.3
- Device model:  Vero 4K+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

About a week ago Netflix plugin on Vero 4K+ started to behave odd, sound was quicker than video.

#### Expected behavior

Play sound and picture in sync.

#### Steps to reproduce the behavior

1. Start Kodi
2. Play anything on Netflix

#### Possible fix

According to [discussion](https://discourse.osmc.tv/t/unusable-constant-buffering-since-2021-12-1-latest-widevine/92209/14) the problem is new Widevine and http2 protocol. I disabled http2 and problem is gone.
Other users use older version of Widevine with better luck. 
< network >
< disablehttp2 > true < /disablehttp2 >
< /network >

### Debug log

The debug log can be found here:

My log is here https://paste.osmc.tv/yemajicile
2022-02-25 12:58:58.893 T:2714     INFO <general>: Log level changed to "TRACE"
But there`s nothing there

**Comment by CastagnaIT** [comment]
disable http2 it is not a good thing to do and netflix servers works with http2, the regular http its only a fallback nowadays
it is know that last versions of widevine have problems on ARM devices
the last stable version seems to be 4.10.2252.0

you can read on #1321 to have some help to revert back
but this is nothing that this addon can solve

**Comment by kocicky** [comment]
Widevine 4.10.2252 works fine. Thanks

**Comment by PeterDaveHello** [comment]
I'm getting the same issue on Raspberry Pi but no problem at desktop 😅

**Comment by matti008** [comment]
Same problem here on raspberry Pi with LibreELEC. Was working fine until a week ago.
