### ISSUE TITLE
InputStream Helper Add-on error

### ISSUE THREAD

**Issue by zoltan-k81** [CastagnaIT/plugin.video.netflix#1330]
### Netflix add-on version

1.12.9

### Operative systems used

LibreELEC

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

As of today, when trying to play any video I get this error message:

"The operation has been cancelled.
InputStream Helper has generated an internal error:
'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
Please report it to InputStream Helper github.

Debug log linked.

### Debug log - mandatory

http://ix.io/3S1K

**Comment by CastagnaIT** [comment]
not an addon problem

**Comment by zoltan-k81** [comment]
Thanks, can you advise what might be the issue then if it's not an addon problem please?
The url opens fine here.

**Comment by CastagnaIT** [comment]
the posted link say only: server connection aborted

> Thanks, can you advise what might be the issue then if it's not an addon problem please?

just read what it is written in the error message...

**Comment by zoltan-k81** [comment]
Just tried the link again and still opens fine here...

Yeah I'm not an expert to know how to solve the problem which is why i'm here...

**Comment by CastagnaIT** [comment]
sorry but i cannot help here because it is clear that:
InputStream Helper addon is not Netflix addon

so it is not a task that can be solved from this github

**Comment by zoltan-k81** [comment]
okay I managed to fix the issue by disabling the InputStream Helper addon inside the Netflix addon.
Not sure what it does and how it was installed in the first place...

**Comment by CastagnaIT** [comment]
removing it you will lose the auto-updating of widevine component
then when your WV version installed will be deprecated you cannot watch videos anymore becouse you have broken the addon
also in this case is not thing that you have to ask here but in InputStream Helper

**Comment by tschabha** [comment]
You don't need to disable Widevine update at all. See the workaround here: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/495
