### ISSUE TITLE
Inaccurate search results

### ISSUE THREAD

**Issue by ShadityZ** [CastagnaIT/plugin.video.netflix#1333]
### Netflix add-on version

1.12.9

### Operative systems used

Raspbian

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

When searching using the Search option, the results are innacurate and come up with other shows irrelevant to the search.

### Steps to reproduce the behavior

1. Start Lodi
2. Open the Netflix add-on
3. Choose a profile
4. Head down to the search option
5. Create a new search, type in a show/movie
6. See irrelevant search results

### Debug log - mandatory

Find the debug log here:

### Possible fix

I believe that the issue maybe down to an update on how Netflix structures their search data. A fix could be looking at the new search data structure and adapting the add-on for this.

### Additional context

It used to work fine, but a few weeks ago its been acting up.

**Comment by CastagnaIT** [comment]
As specified in readme there is no more support for Kodi 18 version

just tried on Kodi 19 but here i have same results of website
