### ISSUE TITLE
[Feature request] Dual language Subtitles support. 

### ISSUE THREAD

**Issue by joopdo** [CastagnaIT/plugin.video.netflix#1334]
**Feature request:**
Fetch _multiple_ subtitles from NetFlix, based on Kodi's Language preferences. 

Suggestion a:
Then allow these subtitles to be displayed at the same time. One language top of screen, another bottom.

Suggestion b:
Then store these subtitles as to disk, allowing third party plugins (subtitle plugin) to view double subtitles by navigating to the locally downloaded file and combining them.

**Case:**
1. Multi-language families, language learners and visitors would benefit from the ability to view multiple subtitles.
2. NetFlix offerers subtitles in many languages. 
3. plugin.video.netflix has the ability to fetch a single subtitle. I couldn't find a local cache of these files.

Thank you for your consideration and/or pointers.

![multi language Kodi](https://i.imgur.com/e8RpVjO.png)

**Comment by aktolu** [comment]
+1 it's would be awesome.

**Comment by CastagnaIT** [comment]
the support to display two subtitles depends on Kodi core only,
the addon do not handle subtitles only provide stream links

moreover the type of subtitles used in netfx sometimes make use also of positional metadata,
which cannot always be removed without creating side effects, then if you force remove it, will results in a corrupted dialog style subtitles or sentences with wrong order

in short no solution from the addon

**Comment by joopdo** [comment]
there is a browser addon now: https://frogly.app/
