### ISSUE TITLE
No HD playback after the latest Widevine  update

### ISSUE THREAD

**Issue by hbbernardo** [CastagnaIT/plugin.video.netflix#1339]
### Netflix add-on version

1.18.4

### Operative systems used

LibreELEC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

After the latest update of Widevine + Input Stream Adaptive there's no HD playback.

 I'm running the latest beta of Libreelec (Nexus 20) on my Raspberry Pi 3

Netflix addon version is 1.18.4

InputStream Adaptive 20.2.0.1 

### Debug log - mandatory

http://ix.io/3X9C

**Comment by CastagnaIT** [comment]
please post the log at http://paste.kodi.tv/
that link not allowed in my country

**Comment by CastagnaIT** [comment]
and specify what widevine version installed

**Comment by hbbernardo** [comment]
Here's the log: https://paste.kodi.tv/pugeruduti.kodi
Netflix addon version is 1.18.4
InputStream Helper: 0.5.10+matrix.1
InputStream Adaptive 20.2.0.1
**Widevine: 4.10.2449.0** 

Hope that helps.

**Comment by CastagnaIT** [comment]
is more likely a problem of last InputStream Adaptive 20.2.0.1

is possible that SD are played?
if you dont know how to, do this:
on InputStream Adaptive settings, set Stream selection to "ask quality"
play a video and select a low quality video

**Comment by hbbernardo** [comment]
Here's your answer. I think.

![IMG_20220507_053300755.jpg](https://user-images.githubusercontent.com/24485236/167246370-a9219c0e-1066-4257-8c86-40ade6245c22.jpg)

**Comment by CastagnaIT** [comment]
yes thanks
so you will have to wait next InputStream Adaptive version release

or if you are an expert
you can build yourself ISA from Nexus branch: https://github.com/xbmc/inputstream.adaptive
that include already the fix

**Comment by hbbernardo** [comment]
Thank you for letting us know. Since I'm no expert, guess am gonna have to wait.

**Comment by hbbernardo** [comment]
Since there's no ISA update incoming with the fix. I'm afraid it can take months. 

How can I build a version myself?

**Comment by CastagnaIT** [comment]
the new version will be released in the coming days

**Comment by CastagnaIT** [comment]
closed since ISA has been released
