### ISSUE TITLE
Download speed throttled by remote end

### ISSUE THREAD

**Issue by gnif** [CastagnaIT/plugin.video.netflix#1346]
### Netflix add-on version

1.18.6+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Seemingly at random some videos will start buffering every few seconds. Checking the kodi log it's clear that the download speed from the Netflix content servers has dropped from ~6.3mb/s to ~150kb/s.

Streaming on other platforms including a Linux PC via Chrome does not exhibit the same behaviour.
The network is not congested with 100mbit of available bandwidth for download.
The device (RPi 4) is wired into the network.
Other services on Kodi such as YouTube and Disney+ do not suffer the same issue.

### Steps to reproduce the behavior

There is no exact steps, simply playing content on Netflix is all that is needed. It's seemingly random what shows/media formats cause this and can be fine for an episode or two and then bad again. It seems very much like Netflix are detecting the unofficial client and are performing throttling.

### Debug log - mandatory

https://paste.kodi.tv/equjepixib.kodi

**Comment by CastagnaIT** [comment]
there is nothing that can be done on addon side
more likely your network node used in your area has some problems
the only thing i can suggest is trying change CDN:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/Expert-settings#open-connect-cdn

**Comment by gnif** [comment]
Thanks for the quick reply, I will try this and report back.

It does seem odd that it would be the node in my area as the desktop streaming I would think would also be affected.

Also reviewing the curl code (note I am an inactive TeamXBMC member) it feels like the buffering code there could use some attention, but this does fall outside the scope of your plugin.

**Comment by gnif** [comment]
> nice but i dont remember your nick, what Kodi area was in your focus when you was in team?
Audio, was quite a while back:
https://kodi.wiki/view/AudioEngine#Three_years_of_work

> the buffering is another problem not related to python addons like this, 

Yup, understood, which is why I said it's out of scope :)

**Comment by CastagnaIT** [comment]
a lot of works done congrats
