### ISSUE TITLE
No e-mail password login possible

### ISSUE THREAD

**Issue by Ronny-nerd** [CastagnaIT/plugin.video.netflix#1349]
### Netflix add-on version

1.18.6+matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hardware: Nvidia Shield TV 2015
Existing: InputStream Adaptive Version 20.2.1

No e-mail - password login possible in the Netflix addon version 1.18.6+matrix.1 as of the Kodi 20 ( 64 Bit ) Nexus Build 
kodi-20220523-1aa506e3-master-22914-arm64-v8a.apk
but with this build it was still possible without problems
kodi-20220521-43b96fc2-master-22881-arm64-v8a.apk

### Debug log - mandatory

https://paste.kodi.tv/ufeqopipog.kodi

**Comment by CastagnaIT** [comment]
Confirm its a kodi bug

**Comment by Ronny-nerd** [comment]
Thanks for the info...CastagnaIT and that this is a Kodi bug.

**Comment by Ronny-nerd** [comment]
Since today the login in the Netflix Addon works again with the Kodi 20 ( 64 Bit ) Nexus Build...so my thanks go to CastagnaIT and the Kodi Team. :)

kodi-20220529-89ffc5d8-master-23044-arm64-v8a.apk

mirrors.kodi.tv/nightlies/android/arm64-v8a/master/
