### ISSUE TITLE
TV Shows display as completed after watching a few episodes

### ISSUE THREAD

**Issue by mcdamo** [CastagnaIT/plugin.video.netflix#1351]
### Netflix add-on version

1.18.6+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

In the addon TV Shows are displayed as completed after watching only part of a season. For example watching half the episodes of season 1 of a show and the addon will display it as completed in Kodi. This has the effect of hiding the show if the Kodi view option is "Unwatched only".

In Kodi a TV show should only display as completed when all episodes in all seasons are watched. If a new episode or new season is added it should also cease to display as completed.

### Steps to reproduce the behavior

1. Watch a few episodes of a show
2. View any listing with that show, such as My List, Continue watching, Search, etc
3. Show will display as completed (with Tick icon), and will be hidden when the Kodi sidebar is set to "Unwatched only" view.

### Debug log - mandatory

https://paste.kodi.tv/ugihafivar.kodi

**Comment by CastagnaIT** [comment]
this is not a bug is intended as it is
netflix api do not provide information about partial or completed on tvshow type
then we know only if a tvshow is started, then kodi think is completed, and will be add the tick "as completed"

some users prefer it that way others like you don't like it

from my POV the only solution are:
-remove the support to tvshow to get the tick "as completed", but i think other users will start complaining
-add another addon setting to disable the tick on tvshow type

**Comment by mcdamo** [comment]
I think the current behaviour of marking all watched shows as 'Completed' will continue to confuse users because it is the opposite of how Kodi works. For example [this discussion about shows disappearing from 'Continue Watching' menu](https://github.com/CastagnaIT/plugin.video.netflix/discussions/1110).

An addon setting to change this behaviour would be welcome. I feel it would be less confusing for this to be the default behaviour and have an addon setting to mark in progress shows as 'Completed' for those users that want the alternative.

**Comment by CastagnaIT** [comment]
@mcdamo i have add a new addon setting in "General" page,
now started tv shows are not marked by default

test build: [plugin.video.netflix_1.18.6+matrix.1_20220610_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8879779/plugin.video.netflix_1.18.6%2Bmatrix.1_20220610_t1.zip)

let me know
