### ISSUE TITLE
Netflix Problem with email and password or the NFAuthenticationKey for Login

### ISSUE THREAD

**Issue by jlcueto** [CastagnaIT/plugin.video.netflix#1352]
I am having the same problem of being able to login to Netflix since I installed a few days ago. I enter the email and password, which are correct but the netflix says it is incorrect. I have tried NFAuthenticationKey and it has loggged in but when I try to play a movie, it states error you must login. It asks me for my email and password or the NFAuthenticationKey again but never lets me play any movie. I have tried uninstalling, re-installing, checking my network router, and cryptodomex but to no avail. I am running on rasspberry pi 4b buster OS with Kodi 18.7. I have also been looking at the kodi log errors. The errors are  ipc.py, logging.py, access.py, __init__.py, http_server.py, msl_utils.py, and msl_handler.py from the kodi log.  I would upload my Kodi log but I don't know where to upload it for assistance. I have tried fixing the files but it still brings the same errors. I would like some advice or way to resolve the issue.  

_Originally posted by @jlcueto in https://github.com/CastagnaIT/plugin.video.netflix/issues/917#issuecomment-1148189287_

**Comment by CastagnaIT** [comment]
im sorry but i do not provide support for Kodi 18 anymore: https://github.com/CastagnaIT/plugin.video.netflix/issues/975
i leave the Issue opened for some days to see if someone else want try help you

**Comment by jlcueto** [comment]
Since you don't provide support for Kodi 18, do you provide support for Kodi 19.4  because I have that on another sim car and Netflix works fine. But the problem with Kodi 19.4, aka Matrix, is that IPTV simple client necessary inputstream addon still does not exist. I have installed

**Comment by movikbence** [comment]
I have exactly the same problem, @jlcueto maybe have you find a workaround for that problem for 18.x track?

**Comment by jlcueto** [comment]
Netflix installs and logins fine with LibreELEC RPI4 9.2.8. The problem with trying to login in Netflix is with Raspberry Pi Buster because it is Raspberry Pi's creation of the Kodi 18.7 as an addon to their OS. The only way to by pass is by installing a RetroPie that also has Kodi 18.7 or 18.8 included with their installation into the Buster OS. I had done that before and it logged into Netflix without a problem but I had forgotten.
