### ISSUE TITLE
subtitles on Wrong position and order

### ISSUE THREAD

**Issue by jjplano** [CastagnaIT/plugin.video.netflix#1361]
### Netflix add-on version

1.18 6

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

only on the Netflix addon, where's more than one single line of subtitles, the bottom lines appear above the first one, and to the left of the screen. I've tried to modify the setup, but nothing changes. this doesn't happen on any other add-ons I use (HBO, Amazon, Paramount, Disney, etc), and it doesn't happen with the downloaded subtitles either, just with this addon

### Steps to reproduce the behavior

just using the Netflix subtitles

### Debug log - mandatory

I'm using a raspberry pi as a player, I don't really know how to get the log, sorry

### Possible fix

no idea

### Screenshots

![IMG_20220612_015203513](https://user-images.githubusercontent.com/59522625/173215275-204c07a4-b772-4e1a-aa1d-1c3725f51d26.jpg)

**Comment by CastagnaIT** [comment]
this is a know kodi bug, already fixed in kodi 20
