### ISSUE TITLE
No e-mail password login possible 2

### ISSUE THREAD

**Issue by Ronny-nerd** [CastagnaIT/plugin.video.netflix#1369]
### Netflix add-on version

1.18.7+matrix.1 from repo version 2.0.0

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hardware: Nvidia Shield TV 2015
Existing: InputStream Adaptive Version 20.2.2

No e-mail - password login possible in the Netflix addon version 1.18.7+matrix.1 as of the Kodi 20 ( 64 Bit ) Nexus Build
kodi-20220611-a7f66f24-master-23202-arm64-v8a.apk = Not OK
kodi-20220613-daa96893-master-23226-arm64-v8a.apk = Not OK
kodi-20220615-5776c974-master-23254-arm64-v8a.apk = Not OK

but with this build it was still possible without problems 
kodi-20220609-26061502-master-23182-arm64-v8a.apk = OK

### Debug log - mandatory

https://paste.kodi.tv/jazapufejo.kodi

### Additional context

Is this a similar problem?

https://github.com/CastagnaIT/plugin.video.netflix/issues/1349

**Comment by CastagnaIT** [comment]
thanks will be fixed in next kodi nightlies
