### ISSUE TITLE
Black screen when resuming playback

### ISSUE THREAD

**Issue by eyalgm** [CastagnaIT/plugin.video.netflix#137]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

0.14.6

### Description

RPI3 + LibreELEC 9.0.2
Whenever I try to resume playback of a video I've partly watched so far, I only get the audio and a black screen. 

### Steps to Reproduce

1.Starting KODI 
2.Starting Netflix-Addon
3.Resume playback of a video I've partly watched

**Expected behavior:** [What you expected to happen]
Get the stream video & audio.

**Actual behavior:** [What actually happened]
 Get audio and a black screen. 

## Context (Environment)
RPI3 + LibreELEC 9.0.2

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Reset to factory/Reinstall  LibreELEC 9.0.2 didn't fix the issue.
## Debug log

https://paste.kodi.tv/wedavoqoza.kodi

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Smeulf** [comment]
Hi,

This is an issue I can confirm, and IMO it's not related to this addon nor InputStream.

I think (but may be wrong) it's related to some patches in Kodi for Raspberry, as I never could reproduce the issue under Windows, nor LibreELEC for x86.

But I had the same issue with OSMC and Kodi 18.2.

For now, the only way I could fix it was to revert to LE 9.0.1.
LE 9.2.0 beta has the same issue, no need to try ^^

I'll gonna investigate on LibreELEC forums/IRC and keep you in touch.

**Comment by eyalgm** [comment]
Thanks

**Comment by Smeulf** [comment]
Opened a thread on LE forum: https://forum.libreelec.tv/thread/17898-le-9-0-2-netflix-issue-on-rpi3-black-screen-when-resuming-a-video-sound-only/

**Comment by eyalgm** [comment]
After Updating the InputStream Helper to version 0.3.5 & updated the Widevine  
The issue was fixed. 
Thank You.

**Comment by eyalgm** [comment]
After Updating the InputStream Helper to version 0.3.5 & updated the Widevine  
The issue was fixed. 
Thank You.

**Comment by Smeulf** [comment]
That's good to know. Thanks!

**Comment by Smeulf** [comment]
Well, I have no idea why after upgrading it's necessary to install Widevine again. I confirm it fixes the issue.

My test process: 

- force install of Widevine on LE 9.0.1 (this should be the last version). Resume working.

- upgrade to LE 9.0.2 (Widevine should still be latest). Resume not working.

- force Widevine install again. Resume working.
