### ISSUE TITLE
Error Contents: invalid literal for int() with base 10: '0+matrix' during background service startup

### ISSUE THREAD

**Issue by osiris86** [CastagnaIT/plugin.video.netflix#1373]
### Netflix add-on version

1.18.7+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

After startup of Kodi the UI shows an error message that the background services for the plugin could not be started. I downgraded to version 1.18.6+matrix.1 of the plugin where everything still works.

Debug Log hopefully gives all relevant insights in what is going on. Let me know if further information are needed. Imho: Timestamp of relevant error: 2022-06-16 22:26:54.274 T:1003

### Steps to reproduce the behavior

Have Libreelec 10.0.2 (Kodi 19.4.0)
Install 1.18.7+matrix.1 of the plugin
Startup Libreelec 
:)

### Debug log - mandatory

https://paste.kodi.tv/bezusacecu.kodi

**Comment by mkreisl** [comment]
I have/had the same problem with my Raspberry PI 3B+/4B with XBian/Debian Bullseye, Kodi 19 and 20.

I had done some troubleshooting in the routine in question using a
try: 
   ...
expect:
  return True

and the service started without any problems. Even after deleting the change, it still works. So I can't reproduce this again.

Everything is very strange

**Comment by CastagnaIT** [comment]
already received a similar report from other user the problem is weird,
the repository appears with a version string that is different from the original repo version string

from your log,
`repository.castagnait v2.0.0+matrix installed`
has `+matrix` suffix appended in version string
then return version `v2.0.0+matrix`

instead the repo file have the version without suffix, so:
`repository.castagnait v2.0.0 installed`
then return version `v2.0.0`

in my tests i am not able to reproduce this problem,
to me not append the suffix, i will try again
looks like a kodi bug in to manage version strings
sometimes append `+matrix` suffix other times no
or there are a particular situation when this is appied that i dont know

remove the suffix via code will fix the problem
but i would like to understand the reason why happens only in some cases

**Comment by MarcusRoeckrath** [comment]
Same problem here on Raspi 4 with libreelec 9.2.8 (Leia).

Kodi-Log:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ValueError'>
Error Contents: invalid literal for int() with base 10: '0+leia'
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.netflix/service.py", line 15, in <module> run(sys.argv)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 170, in run check_service_upgrade()
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/upgrade_controller.py", line 54, in 
    check_service_upgrade_perform_service_changes(service_previous_ver, service_current_ver)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/upgrade_controller.py", line 98, in
    _perform_service_changes migrate_repository()
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/upgrade_actions.py", line 106, in migrate_repository
if not is_less_version(Addon('repository.castagnait').getAddonInfo('version'), '2.0.0'):
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 181, in is_less_version
      return list(map(int, version.split('.'))) < list(map(int, max_version.split('.')))
      ValueError: invalid literal for int() with base 10: '0+leia'

I deinstalled the repo which solves the problem.

**Comment by CastagnaIT** [comment]
someone that has this problem on Kodi19 can update with this:
[plugin.video.netflix_1.18.7+matrix.1_20220618_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8933191/plugin.video.netflix_1.18.7%2Bmatrix.1_20220618_t1.zip)
and let me know if works?

**Comment by MarcusRoeckrath** [comment]
On Leia its Kodi 18 and netflix addon 1.12.11. Do you have a bugfix for this version.

**Comment by CastagnaIT** [comment]
@MarcusRoeckrath 
leia test: [plugin.video.netflix_1.12.11_20220618_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8933244/plugin.video.netflix_1.12.11_20220618_t1.zip)

**Comment by MarcusRoeckrath** [comment]
Thanks; no crash anymore on leia.

**Comment by alexv1v** [comment]
> someone that has this problem on Kodi19 can update with this: [plugin.video.netflix_1.18.7+matrix.1_20220618_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8933191/plugin.video.netflix_1.18.7%2Bmatrix.1_20220618_t1.zip) and let me know if works?

Tested on Kodi19 and works again. Thanks!

**Comment by Yavos** [comment]
> someone that has this problem on Kodi19 can update with this: [plugin.video.netflix_1.18.7+matrix.1_20220618_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/8933191/plugin.video.netflix_1.18.7%2Bmatrix.1_20220618_t1.zip) and let me know if works?

I can verify it works with this one but did not with the automatically updated one (Kodi19).

**Comment by CastagnaIT** [comment]
released the version fixed

**Comment by osiris86** [comment]
Can confirm everything working again after installing the update.

**Comment by MarcusRoeckrath** [comment]
Upgraded to 1.12.12 - no problem at start of app.
