### ISSUE TITLE
No module named 'contextvars'

### ISSUE THREAD

**Issue by akuntzagk** [CastagnaIT/plugin.video.netflix#1378]
### Netflix add-on version

1.18.7

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Netflix plugin doesn't start. Error message says that module "contextvars" is missing. 
Log says the same:
```
...
                                                     File "/home/murple/.kodi/addons/plugin.video.netflix/packages/sniffio/_impl.py", line 1, in <module>
                                                       from contextvars import ContextVar
                                                   ModuleNotFoundError: No module named 'contextvars'
```

pip3 says that contextvars is installed:
```
murple@nuc:~$ pip3 list|grep context
contextvars             2.4    
```             

I can also import the module on commandline
```
murple@nuc:~$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import contextvars
>>>
```

### Steps to reproduce the behavior

Start 

### Debug log - mandatory

https://paste.kodi.tv/muzudiqode.kodi

**Comment by CastagnaIT** [comment]
this is not a bug
but misconfiguration in your python packages
there are many issues on this topic please search in the old closed issues or asking in forum
