### ISSUE TITLE
NoneType error in kodi 20

### ISSUE THREAD

**Issue by Sparh4wk** [CastagnaIT/plugin.video.netflix#1380]
### Netflix add-on version

1.18.8

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Netflix is unable to start with NoneType Error.

### Steps to reproduce the behavior

Just run netflix addon.

### Debug log - mandatory

https://paste.kodi.tv/evixekojar.kodi

### Screenshots

![image](https://user-images.githubusercontent.com/7014826/175771365-6299d64a-a2e2-4b43-8ba0-b774634bb377.png)

**Comment by CastagnaIT** [comment]
provide a full log with debuggin enabled as explained in Github Readme

**Comment by Sparh4wk** [comment]
> provide a full log with debuggin enabled as explained in Github Readme

https://paste.kodi.tv/ceqibalife.kodi

**Comment by CastagnaIT** [comment]
> 20.0-ALPHA1 (19.90.701) Git:20220609

please update the nightly to the last one
in recent weeks there have been bug in Kodi
after that, delete in full the addon and also user data when prompt
then reinstall the addon

**Comment by Sparh4wk** [comment]
Thanks, works fine now
