### ISSUE TITLE
Kodi crashes upon opening Netflix plugin

### ISSUE THREAD

**Issue by thekswenson** [CastagnaIT/plugin.video.netflix#1384]
### Netflix add-on version

1.18.8+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

After updating to Ubuntu 22.04, the Netflix now fails.
It almost always freezes upon opening the plugin.  Once in a while, the plugin will load yet Kodi will freeze while choosing other menu items. 

### Debug log - mandatory

https://paste.kodi.tv/adotiwejiw.kodi

**Comment by CastagnaIT** [comment]
more likely your ubuntu version ship a broken python version
what is the py version?

**Comment by thekswenson** [comment]
```
=> python3 --version
Python 3.10.4
```

**Comment by thekswenson** [comment]
I just noticed this line in your installation instructions:
"For Linux operative systems, Python version 3.7 or higher is required (warning python 3.10.3 / 3.10.4 is bugged)"

Do you have a good workaround?  I may try to install an older version of python, but last time I did that I ran into many headaches.

**Comment by thekswenson** [comment]
The workaround at [https://forum.kodi.tv/showthread.php?tid=368069&pid=3100638#pid3100638](https://forum.kodi.tv/showthread.php?tid=368069&pid=3100638#pid3100638) worked for me.

**Comment by CastagnaIT** [comment]
yes it is a possible solution
