### ISSUE TITLE
MSL ERROR: this title is not available to watch instantly 

### ISSUE THREAD

**Issue by dilshad217** [CastagnaIT/plugin.video.netflix#1385]
Netflix plugin has been working fine till yesterday, all of sudden it started to gove this error

https://paste.kodi.tv/eyematizaw.kodi

**Comment by CastagnaIT** [comment]
All known solutions to this error message are in the Wiki:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-(Errors)#This-title-is-not-available-to-watch-instantly
as explained in the wiki on this no further support will be provided

**Comment by dilshad217** [comment]
Thank you for the the plugin and support.
