### ISSUE TITLE
AUTHENTICATOR PROBLEM WINDOWS NO OUTPUT

### ISSUE THREAD

**Issue by mtmtmt123** [CastagnaIT/plugin.video.netflix#1389]
### Netflix add-on version

newest

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

AUTHENTICATOR PROBLEM

I use the Toool
Login in netflix in browser and now nothing does over 5 minits
#  :( plese help me

### Debug log - mandatory

https://paste.kodi.tv/ataxeluquq

### Possible fix

???

### Additional context

Fix it please

**Comment by mtmtmt123** [comment]
logged in but only
*  Chrome startup... please wait
*  Establish connection with Chrome... please wait
*  Opening login webpage... please wait
-> Please login in to website now ...waiting for you to finish...

**Comment by mtmtmt123** [comment]
can i use this only with Paid Accounts?

**Comment by CastagnaIT** [comment]
What means exactly only with paid accounts? this is not free service
make sure you have paied the month before try login

**Comment by CastagnaIT** [comment]
closed due to inactivity
