### ISSUE TITLE
STRM Resume doesn't work

### ISSUE THREAD

**Issue by XxAcielxX** [CastagnaIT/plugin.video.netflix#1400]
### Netflix add-on version

1.18.8, 1.18.9

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

When I try to resume any episode of shows Exported to Library, the resume option disappears as soon as I exit from that show's episode list. It plays the episode from the start every time. 

### Steps to reproduce the behavior

1. Play any episode
2. Watch more than 10 mins
3. Stop it
4. Come back to same episode again
5. Try to resume it (there is no resume marker for it)

### Debug log - mandatory

https://paste.kodi.tv/godurumuvu.kodi

### Additional context

`Enable STRM resume workaround` is ticked.
`Ask to resume the video` doesn't matter if ticked or not.

**Comment by CastagnaIT** [comment]
you have to enable kodi scrapers in library folders

**Comment by XxAcielxX** [comment]
> you have to enable kodi scrapers in library folders

The Shows are scanned to Kodi Library using Local Information Scapper. If that is what you're saying above.

**Comment by CastagnaIT** [comment]
`Local Information` is not a real scraper and not always works
you have to set something like TMDB

**Comment by CastagnaIT** [comment]
as the name of the setting says its a workaround, this is an ancient Kodi bug,
but people over the time always would rather complain with addons like this than open a problem ticket in Kodi to give more importance...
in any case, no other solutions will be possible here

**Comment by XxAcielxX** [comment]
I tried with the TMDB Scapper as you suggested and thing result is same. Resume still doesn't work.

Now I'm wondering, how it was working perfectly and then suddenly stopped working 🤔

**Comment by CastagnaIT** [comment]
i tried on a clean kodi 19 and out of 3 times it worked
i have no idea what problems have your kodi
nothing that i can solve since this problem must be solved in Kodi core

**Comment by CastagnaIT** [comment]
just to let you know
i have fixed STRM resume on Kodi core
then for the next Kodi 20 beta 1 you will have the fix on board
but you will have to use LibreELEC "Nexus" version

i will try to make a backport of the fix for Kodi 19
but i am not sure that will be accepted, and or published another kodi 19 version
