### ISSUE TITLE
InvalidProfilesError

### ISSUE THREAD

**Issue by moderaterocker** [CastagnaIT/plugin.video.netflix#1406]
### Netflix add-on version

1.18.9+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Tried both ways (pwd and authkey) with same output after entering credentials/pin: 

_L'addon ha riscontrato il seguente errore:
InvalidProfilesError:

I dettagli dell'errore sono stati scritti nel file log di Kodi. Se il messaggio di errore non fornisce indicazioni su come risolvere il problema o se l'errore continua a presentarsi, si prega di segnalarlo tramite GitHub seguendo le istruzioni nel readme_ 

I checked Kodi's log, looks like there are some messy errors starting from line 523, up to a _                                                   resources.lib.common.exceptions.InvalidProfilesError_ at line 600, but I really don't know where to put hands. My distro is Ubuntu 22.04.1 LTS. Would you help me understan what's happening please? Thank you.

### Debug log - mandatory

https://paste.kodi.tv/dugowodufo.kodi

**Comment by CastagnaIT** [comment]
you see InvalidProfilesError but above that there is:

sqlite3.DatabaseError: database disk image is malformed

seems addon database has been corrupted for some external reason,
so uninstall addon completely, also delete user data when prompt

possible causes:
-you have too little space on your storage
-your storage is unreliable and/or has bad sectors
-or other things that i dont know

**Comment by moderaterocker** [comment]
Thanks, will try asap and let you know

**Comment by moderaterocker** [comment]
A simple uninstall/reinstall solved as you suggested. Thanks! And.. sorry for bothering you xD! Closing the issue.
