### ISSUE TITLE
NFAuthenticationKey.py

### ISSUE THREAD

**Issue by unclehowell** [CastagnaIT/plugin.video.netflix#1409]
### Netflix add-on version

1.0.3

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

NFAuthenticationKey.py doesn't work. I believe the solution is to use the following code `_create_websocket_connection` instead of what's currently there. 

### Steps to reproduce the behavior

1. Download your Dropbox file (NFAuthenticationKey.py)
2.  Install recommended dependencies 
3. Run the script 

### Debug log - mandatory

None

**Comment by CastagnaIT** [comment]
what operative system?

**Comment by CastagnaIT** [comment]
also the current linux version is 1.1.4 so suggest you to download the current version from https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

**Comment by unclehowell** [comment]
I figured if out. It wasn't what I mentioned above so pay no notice. Forgot how I solved the issue, but awesome work. Thanks
