### ISSUE TITLE
Video not opening

### ISSUE THREAD

**Issue by SPRSheep** [CastagnaIT/plugin.video.netflix#141]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General information
When I open a video I get a error message. The message is no more than send a debug log. So.. here it is.

https://paste.kodi.tv/muraguviwe.kodi
## Addon version used
The latest version 

### Installation

* [x ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by jakermx** [comment]
Try rebooting, and try again

**Comment by SPRSheep** [comment]
Tried that, didn't work

**Comment by Smeulf** [comment]
Can you please enable debug, reboot, try again on 2 or 3 different videos including the one you already had an error and post your logs again? There's something I'd like to check. Thanks.

**Comment by jakermx** [comment]
If you are using DailyBuilds, Please uninstall netflix repository , and disable autoupdate...

This could did some mess with the installation, so I would suggest to uninstall netflix addon, reinstall it, and then reboot, after that, without having autoupdate on, it should work.

**Comment by Smeulf** [comment]
@jakermx @SPRSheep:

Just remembered, can you please try this daily build(http://www.mediafire.com/file/c05qz9je1dlr655/plugin.video.netflix_0.14.6_20190708.zip/file) (or later)? If it's the issue I'm thinking about, it should be fixed.
