### ISSUE TITLE
Trying to add any content to an empty user list ('My List') causes an noneType error

### ISSUE THREAD

**Issue by b-jesch** [CastagnaIT/plugin.video.netflix#1413]
### Netflix add-on version

1.18.9+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

If you try to add any content to a user that starts with an empty personal list causes an none type error.

### Steps to reproduce the behavior

1. Be sure your peronal list is empty
2. Navigate to any of the content
3. select from content menu "add to my list"

### Debug log - mandatory

https://paste.kodi.tv/huluqazeli

### Screenshots

![Bildschirmfoto von 2022-09-22 22-06-56](https://user-images.githubusercontent.com/10152384/191841113-ac9ab251-1e5d-4c6b-88f6-438a5f0c2afc.png)

**Comment by b-jesch** [comment]
Addendum: Although the error message appears, items are added to the personal list. However, these are only visible after a Kodi restart (and the associated activation of the background services).

**Comment by CastagnaIT** [comment]
thanks i addressed it
