### ISSUE TITLE
python3-crypto is no more available in BullEye (OSMC latest version, september)

### ISSUE THREAD

**Issue by dantahoua** [CastagnaIT/plugin.video.netflix#1416]
### Netflix add-on version

1.18.9

### Operative systems used

OSMC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

After OSMC update,  the addon complain of the lack of python3-crypto. Tried to install it with apt install but it seems after research this package is deprecated in Debian BullEye...

### Debug log - mandatory

https://paste.kodi.tv/

**Comment by CastagnaIT** [comment]
seem that exists `python3-cryptodome` although somewhat old but you can try install it

**Comment by dantahoua** [comment]
Any sudo apt install python3-crypto or cryptodome do not work. My system is an update so maybe it works because of the reboot and previous install.  I was able to make 
sudo pip3 install setuptools wheel
sudo pip3 install pycryptodomex
And now it works after reboot.

**Comment by CastagnaIT** [comment]
yes is what it is written in install instructions
