### ISSUE TITLE
email or password incorrect .. again

### ISSUE THREAD

**Issue by lerutis** [CastagnaIT/plugin.video.netflix#142]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

latest daily 14.6 - 2019-07-08

### Description

i have re-installed everything many times, but i always get the error about email and password incorrect when i try to play video, it all worked before on versions 13.xx before something just broke.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://paste.kodi.tv/ocanexofov.kodi

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Smeulf** [comment]
Can you please try last daily build: http://www.mediafire.com/folder/vifnw8ve44bi7/KodiNetflixAddon

**Comment by lerutis** [comment]
Hi, Thanks, gives me same error :), tried all different builds including this.

Regards

**Comment by Smeulf** [comment]
You can try to remove the encrypted email and password values in addon_data/plugin.video.netflix/settings.xml

It will ask for your credentials again.

Also can you please enable debug, reboot, and try to play a video again? I'd like to see the all debug from the beginning, including service startup. Thanks.

**Comment by lerutis** [comment]
thanks,

https://paste.kodi.tv/avewidumag.kodi

i think this is the correct log file
if not

https://paste.kodi.tv/izofuvelol.kodi

regards

**Comment by CastagnaIT** [comment]
seem you have the same problem of this issue:
https://github.com/CastagnaIT/plugin.video.netflix/issues/67
read and try to apply the solutions described

**Comment by CastagnaIT** [comment]
try to install the new release 15.0 and let me know if change something

**Comment by hllizi** [comment]
Hi, I'm continuing here because it's not clear whether the issue had been resolved and because mine is exactly the same. The addon used to work but now does not anymore in the same way as described by the OP. I cannot say exactly which version the problems started with but they persist with 15.2.

Differently from the OP I employ a Raspberry Pi (running LibreELEC).

The debug log can be found here: https://paste.kodi.tv/okirovuzox.kodi

BTW the old repo allowed for downgrading to earlier versions effortlessly inside of Kodi while the present one only ever offers the most recent version of the addon. If the possibility to downgrade could be provided that might be very helpful.

**Comment by lerutis** [comment]
It is still the same for me :/

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Smeulf** [comment]
@hllizi 

>  If the possibility to downgrade could be provided that might be very helpful.

I just opened a specific issue for this so we can track it separately: hzttps://github.com/CastagnaIT/repository.castagnait/issues/11

**Comment by CastagnaIT** [comment]
Fixed on 0.15.3 release
