### ISSUE TITLE
msl error: user authentication data does not match entity identity

### ISSUE THREAD

**Issue by grega74** [CastagnaIT/plugin.video.netflix#1421]
Hello

i get error msl error: user authentication data does not match entity identiy when 
I try to watch anything. I enabled Force L3 in widevine settings. Do I have to edit MSL if force l3 is enabled?

thanks for help

**Comment by DarkMetatron** [comment]
I had the same error and it seems to be with the update from today. 
I downgraded to a older version and the issue is gone.

**Comment by shorti1996** [comment]
Same issue.

**Comment by joansalvaje** [comment]
Same here with v1.18.10 I downgraded to a older version and then works, but now max resolution is 540 😓

**Comment by CastagnaIT** [comment]
please open the Issue correctly
