### ISSUE TITLE
MSL Error user authentication data does not match entity identity on L3 device

### ISSUE THREAD

**Issue by neliosilva** [CastagnaIT/plugin.video.netflix#1424]
### Netflix add-on version

version 1.18.10

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I can loggin to netflix addon but when i try to watch a movie this erros appears: "MSL Error user authentication data does not match entity identity"

It works fine on previous version

### Debug log - mandatory

https://paste.kodi.tv/uzoqadaxaj.kodi

**Comment by CastagnaIT** [comment]
i need full log or/and specify device model

due to last website changes this is now a big problem,
in theory i can revert in some way the related code part,
but this means that _you can playback only from owner profile_, and that _all other profiles will become unusuable_,
at current state this situation cannot be fixed, unless someone else understands how to change profile using MSL ID tokens
or re-implement android addon part to use android netflix app endpoints

**Comment by neliosilva** [comment]
I send the full log file.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CastagnaIT** [comment]
there is not log in your message,
if you use email client to publish answers to github website you are allowed to send plain text only

**Comment by neliosilva** [comment]
https://paste.kodi.tv/etecosuzox.kodi

**Comment by Shaz2472** [comment]
Same problem; will follow..

**Comment by CastagnaIT** [comment]
you keep addon log setting disabled so i cannot get more info
i need to know if your device is widevine L3
if you dont know it, go to addon expert setting->widevine settings-> press save system info button and attach the saved file here

**Comment by neliosilva** [comment]
https://paste.kodi.tv/dalusegodu

**Comment by neliosilva** [comment]
It works!!!



Enviado do meu Galaxy



-------- Mensagem original --------
De : Stefano Gottardo ***@***.***>
Data: 30/09/22 14:45 (GMT+00:00)
Para: "CastagnaIT/plugin.video.netflix" ***@***.***>
Cc: neliosilva ***@***.***>, Author ***@***.***>
Assunto: Re: [CastagnaIT/plugin.video.netflix] MSL Error user authentication data does not match entity identity (Issue #1424)


Please try this test build:
plugin.video.netflix_1.18.10+matrix.1_20220930_t1_l3.zip<https://github.com/CastagnaIT/plugin.video.netflix/files/9684651/plugin.video.netflix_1.18.10%2Bmatrix.1_20220930_t1_l3.zip>

please note that you can play videos only from main/owner profile

**Comment by grega74** [comment]
Same error with latest test build still ... Force L3 enabled

**Comment by CastagnaIT** [comment]
new test build t4 here:
https://github.com/CastagnaIT/plugin.video.netflix/issues/1425#issuecomment-1264977616

@grega74 try open official netflix app and goto settings
and copy the original ESN number
to the kodi addon on Expert setting "Widewine/ESN" by ignoring all chars after `-13482-`
and disable forced L3

**Comment by grega74** [comment]
> new test build t4 here: [#1425 (comment)](https://github.com/CastagnaIT/plugin.video.netflix/issues/1425#issuecomment-1264977616)
> 
> @grega74 try open official netflix app and goto settings and copy the original ESN number to the kodi addon on Expert setting "Widewine/ESN" by ignoring all chars after `-13482-` and disable forced L3

Thanks for suggestion but it don't work. I got ESN from Netflix version 4 and I disabled L3 - I get error: Sorry, this account can't be used on this device.
If I force L3: this title is not available to watch ...

Your plugin's ESN: NFANDROID2-PRV-CHOTT0102-CHANGCHOTT0102-13482- (error: this title ...)
Netflix app ESN is: NFANDROID2-PRV-0-CHANGCHOTT0102-13482- (with this I get error: Sorry, this account can't...)

Tried both, no luck ...

**Comment by CastagnaIT** [comment]
@grega74 what type of netflix account you have?

**Comment by grega74** [comment]
> @grega74 what type of netflix account you have?

Premium. Works on every other device certified. And 5 users on it and I try everything on my, base account.

**Comment by CastagnaIT** [comment]
@grega74 please try update with this:
[plugin.video.netflix_1.18.10+matrix.1_20221003_t4_mod_grega.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9697156/plugin.video.netflix_1.18.10%2Bmatrix.1_20221003_t4_mod_grega.zip)
and use
NFANDROID2-PRV-CHOTT0102-CHANGCHOTT0102-13482-
without force L3

> Premium. Works on every other device certified. And 5 users on it and I try everything on my, base account.

this is not an official app and since we dont use netflix android endpoints its difficult solve this type of problems
last website changes has make also more complex situation and in some cases can be unsolvable

**Comment by grega74** [comment]
> @grega74 please try update with this: [plugin.video.netflix_1.18.10+matrix.1_20221003_t4_mod_grega.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9697156/plugin.video.netflix_1.18.10%2Bmatrix.1_20221003_t4_mod_grega.zip) and use NFANDROID2-PRV-CHOTT0102-CHANGCHOTT0102-13482- without force L3
> 
> > Premium. Works on every other device certified. And 5 users on it and I try everything on my, base account.
> 
> this is not an official app and since we dont use netflix android endpoints its difficult solve this type of problems last website changes has make also more complex situation and in some cases can be unsolvable

This title is not is not available to watch instantly ....

I opened kodi and I updated existing plugin with this one. Or should I remove it and reinstall?

**Comment by CastagnaIT** [comment]
netflix website has rejected to access videos in all ways that i know
i dont have other solutions for you sorry

just two last questions
on the official app in the Playback specification settings is specified max resolution SD or HD?
before netflix broken the addon you was watching videos at 1080p or 4k?

for now will have to hope for new future changes from the website

**Comment by grega74** [comment]
> netflix website has rejected to access videos in all ways that i know i dont have other solutions for you sorry
> 
> just two last questions on the official app in the Playback specification settings is specified max resolution SD or HD? before netflix broken the addon you was watching videos at 1080p or 4k?
> 
> for now will have to hope for new future changes from the website

I could not watch at all - I first installed I think version 1.18.9 and it was not working, even not SD.
In offical app 4.0.0. there is not Playback specification settings ...

Thanks for all your hard work.

**Comment by sheogorat96** [comment]
> @grega74 please try update with this:
> [plugin.video.netflix_1.18.10+matrix.1_20221003_t4_mod_grega.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9697156/plugin.video.netflix_1.18.10%2Bmatrix.1_20221003_t4_mod_grega.zip)

works for me!!!!!!!!! testing

**Comment by sheogorat96** [comment]
I confirn mod_grega works fine, i have 6ch audio in settings (and i can choose it), but netflix dont want to work fine on all my devices and started all videos with 540p :)
