### ISSUE TITLE
TypeError:_init_() missing 2 required keyword-arguments:'request' snd 'response'

### ISSUE THREAD

**Issue by canice86** [CastagnaIT/plugin.video.netflix#1427]
### Netflix add-on version

1.18.9+matrix.1.zip 1.18.10+matrix.1.zip

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Cannot get beyond selecting profile as there is a TypeError:_init_() missing 2 required keyword-arguments:'request' snd 'response'

On a different note I've pinpointed your add on effect streaming of all other apps Netflix, Amazon Prime, Disney+.  They try load the the movie or episode getting to 20% and nothing or sometimes asks try again.  Two ways have fixed this 1. uninstalling kodi restart nvidia shield. Or 2. Head to your Netflix plugin expert settings and reduce all TTL cache to minimum,  it upsets the addon a small bit but pushes through and plays fine. Other .apks  Netflix,  Amazon Prime and Disney+ play fine again as there's no background demand...Force stop app, clear data and cache in apps themselves dosnt work. At that point you have to uninstall kodi to get rid of your addon as processes persist regardless. Again I say points to your addon and the amount of cache it uses. Now lowering TTL cache may have caused TypeError:_init_() missing 2 required keyword-arguments:'request' snd 'response' when I physically started up my Nvidia Shield 2017 again to run your addon.

### Debug log - mandatory

https://paste.kodi.tv/cejicudecu

**Comment by MPParsley** [comment]
See https://github.com/CastagnaIT/plugin.video.netflix/issues/1425.

**Comment by gilbertoferreira** [comment]
I am facing this very same error.

**Comment by u2020bullet** [comment]
Same issue here, running the latest Kodi and addon on the newest version of Ubuntu that i fully updated.

**Comment by gilbertoferreira** [comment]
> Same issue here, running the latest Kodi and addon on the newest version of Ubuntu that i fully updated.

Just edit this file 
/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py
Open if on the line 112 and 127.
Change is not to !=, like this
Before:
    if ret_data is not None:

After:
    if ret_data != None:

salve and open kodi.
Here works as a charm.
Kubuntu 22.10 
kodi 20

**Comment by gilbertoferreira** [comment]
Ouch! Works a moment.
Then after close and open Kodi doesn't work anymore.

**Comment by Firesphere** [comment]
That sadly didn't work for LibreELEC...

**Comment by CastagnaIT** [comment]
dupicate of #1425
