### ISSUE TITLE
Black screen when and no audio when playing video

### ISSUE THREAD

**Issue by tommyfinn** [CastagnaIT/plugin.video.netflix#143]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used
0.14.6
[eg. 13.21.0]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. start kodi
2. open netflix addon
3. select a series and navigate to episode
4. start episode, get play symbol, loading wheel, black screen, no audio and timestamp progresses but nothing plays
**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x ] Android
https://paste.kodi.tv/poxeherene.kodi
#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]u

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Smeulf** [comment]
Please enable debug logging in Kodi and post logs again.

**Comment by tommyfinn** [comment]
https://paste.kodi.tv/fifupuhuwa.kodi

**Comment by Smeulf** [comment]
Can you try enabling HEVC in settings/expert? It may solve the problem.

Also, is it your first attempt or is it after any upgrade (addon, kodi, or even Android) ?

**Comment by tommyfinn** [comment]
I tried enabling it. Closed kodi and reopened but same results.

This is my 1st attempt no updates

**Comment by jakermx** [comment]
Try deleting .kodi/cdm and addona/inputstream.adaptive/cdm contents , basically find libwidevinecdm.so and delete it....
Si it will install Widevine again.
Also disable OMX Codec, I have had very frustaring times trying OMX. I have to use pa or MMAL
