### ISSUE TITLE
TypeError missing 2 required keyword-only arguments

### ISSUE THREAD

**Issue by 0oWeZo0** [CastagnaIT/plugin.video.netflix#1432]
### Netflix add-on version

1.18.10+matrix.1

### Operative systems used

Windows

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Netflix addon worked perfectly for ages. Nothing changed or updated on system.

About a week ago, the type error mentioned happens when you login and select the profile. It thinks for a while then spits out the error. Netflix on the pc app works fine.

I restored a full kodi backup taken days before the error started and still the error persists. 

This must be upstream from my pc. 

You have a closed case of this description which alot of people are commenting on over the past 24 hours. 

### Steps to reproduce the behavior

1.start Netflix on kodi.
2. Select profile.
3. Error appears. 

### Debug log - mandatory

Uploading log failed. 

### Possible fix

None.

**Comment by Joshyakadamien** [comment]
Bump
as stated in:
https://github.com/CastagnaIT/plugin.video.netflix/issues/1297#issue-1111713296

**Comment by CastagnaIT** [comment]
issue already opened #1425

**Comment by lemanu38** [comment]
Hi That Manuel from France , yesterday i've encounterd exactly the same problem with lauching Netflix under Kodi . I'm not under Windows and PC , but with my Xgimi Mogo pro projector running with android TV. 
Evrything was right before for many months and suddently without any reason ( no upgrade , update or something like that)  it is not possible to log my profile. 
If anybody got a solution to fix that error i'm really interested . I've re-installed everything and it does work. thje error seems impossiblie to fix easily. 
 Error Message is :
The add-on encounterd the followoing type error:_init_() missing 2 required keyword-only arguments'resquest and response'.
Thanks for your help.
