### ISSUE TITLE
Netflix browsing account request and response error

### ISSUE THREAD

**Issue by hbbernardo** [CastagnaIT/plugin.video.netflix#1433]
### Netflix add-on version

1.18.10+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When I try to browse under my profile using Netflix Add-on I'm getting this request and response error 

### Steps to reproduce the behavior

Open Netflix Add-on.

Try to browse your profile.

An error message appears.

### Debug log - mandatory

https://paste.kodi.tv/kesalosuze.kodi

### Screenshots

https://user-images.githubusercontent.com/24485236/193363330-d2388ddd-89ab-4902-8256-509e5e739659.jpg

**Comment by hbbernardo** [comment]
![IMG_20220930_183857502](https://user-images.githubusercontent.com/24485236/193363330-d2388ddd-89ab-4902-8256-509e5e739659.jpg)

**Comment by somrandomMF** [comment]
Same on Windows 10, kodi 19.4.

**Comment by pinello97** [comment]
Also me! Same error
![Uploading image.jpg…]()

**Comment by CastagnaIT** [comment]
issue already opened #1425

**Comment by sharonnnnnnnn** [comment]
Same problem
What should I do?

![7AE7E546-26C3-4D54-BC53-9410F51F33CF](https://user-images.githubusercontent.com/114872564/193464655-6dd36288-64a5-47c1-86ce-d9c9a73fb28b.jpeg)

**Comment by ACMadeira** [comment]
Same problem here..
