### ISSUE TITLE
Crash when start profile

### ISSUE THREAD

**Issue by rardcode** [CastagnaIT/plugin.video.netflix#1435]
### Netflix add-on version

1.18.8+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Bug appear when insiede Netflix plugin i choose anyone of my netflix profile.

### Steps to reproduce the behavior

1. navigate to add-on - Netflix
2. select one of profile available

### Debug log - mandatory

https://paste.kodi.tv/ivifuxopak.kodi

**Comment by UUInc-co** [comment]
This is a repeat of these two recent problems: https://github.com/CastagnaIT/plugin.video.netflix/issues/1425 && https://github.com/CastagnaIT/plugin.video.netflix/issues/1428 

Fix is here: 

This is the new test build (Kodi v19+): [plugin.video.netflix_1.18.10+matrix.1_20221001_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9690307/plugin.video.netflix_1.18.10%2Bmatrix.1_20221001_t3.zip)

**Comment by haplo67** [comment]
Hi 
Thanks for your answer.
My raspberry pi runs on Retropie, so I only have Kodi 18.7
Is there a fix for this version of Kodi?

Thanks in advance.
Matthieu

**Comment by rardcode** [comment]
> This is a repeat of these two recent problems: #1425 && #1428
> 
> Fix:
> 
> > This is the new test build (Kodi v19+): [plugin.video.netflix_1.18.10+matrix.1_20221001_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9690307/plugin.video.netflix_1.18.10%2Bmatrix.1_20221001_t3.zip)

tks!!
it works!! "))))
