### ISSUE TITLE
TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response

### ISSUE THREAD

**Issue by urlaub33** [CastagnaIT/plugin.video.netflix#1436]
### Netflix add-on version

1.18.10

### Operative systems used

LibreELEC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

I start Netflix, then I select my profile, now the error message comes up

### Debug log - mandatory

https://paste.kodi.tv/wetusaxiya

### Possible fix

No

**Comment by silvacraig** [comment]
same kodi 19 on ubuntu

**Comment by lemn8** [comment]
Kodi from debian 19.1 with Netflix 1.18.10 version addon suddenly has the same issue. I'm the third so i think we can officially state that netflix changed something!

**Comment by AvivAvital2** [comment]
Same with LibreElec 10.0.2, worked fine and suddenly shows this error.
Tried removing the addon and reinstall it, choose an earlier version, same error.
@lemn8 A change from Netflix side is the most reasonable scenario IMO

**Comment by rardcode** [comment]
Fix is here:

This is the new test build (Kodi v19+): [plugin.video.netflix_1.18.10+matrix.1_20221001_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9690307/plugin.video.netflix_1.18.10%2Bmatrix.1_20221001_t3.zip)

**Comment by lemn8** [comment]
> Fix is here:
> 
> This is the new test build (Kodi v19+): [plugin.video.netflix_1.18.10+matrix.1_20221001_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9690307/plugin.video.netflix_1.18.10%2Bmatrix.1_20221001_t3.zip)

Thnx! This right here is what i enjoy the most. Those little collabs! Now this Netflix-Git has a good clear/findable description of the problem, and a solid solution the the problem in reach for everyone in need of help! 

Thnx @rardcode for the info!

**Comment by CastagnaIT** [comment]
issue already opened #1425
