### ISSUE TITLE
Netflix issue when trying to switch profiles

### ISSUE THREAD

**Issue by cappsie** [CastagnaIT/plugin.video.netflix#1437]
### Netflix add-on version

CastagnaIT Repo: 2.0 (Netflix: libdev + jojo+ asciidisco + caphm + castagnait - 1.12.14)

### Operative systems used

LibreELEC

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

LibreELEC: 9.2.8
Kodi: 18.9

Looks like a 404 error that the Netflix plug-in is attempting to call.

### Steps to reproduce the behavior

Using default skin in Kodi.

1. In Kodi, navigate to Add-ons menu item
2. Under Video add-ons, select/click the Netflix icon
3. (Signed into the account previously) select any profile and select OK/click
4. Netflix fails with error

### Debug log - mandatory

https://paste.kodi.tv/usufesicop.kodi

### Possible fix

Could be a simple manual code update to repoint the 404 URL?

### Screenshots

![image](https://user-images.githubusercontent.com/114855552/193447704-1a590110-2a58-409d-8307-d738be537af6.png)
![image](https://user-images.githubusercontent.com/114855552/193447709-60e036c8-c447-40ae-8266-314f76bc407b.png)

**Comment by CastagnaIT** [comment]
despite different error shown at screen its the same of issue #1425 
i keep this opened only to redirect new users to right issue #1425

before i need to be sure that works without problems on Kodi 19+
then after that can be possible think to backport the fix to Kodi 18
