### ISSUE TITLE
404 error when calling shakti api

### ISSUE THREAD

**Issue by AriLer** [CastagnaIT/plugin.video.netflix#1438]
### Netflix add-on version

2

### Operative systems used

Mac OSX

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

there seems to be a problem with calling the netflix shakti api. this is not specific to this project. I'm developing a project where i take my netflix viewing activity and yesterday my project started throwing 404's at my. i haven't changed any of my code so it looks like the endpoints of the shakti api have changed. i hope this helps with your project and if you find a way around this problem i would greatly appreciate it if you'd reply and explain your solution. 
Cheers 

### Debug log - mandatory

i have no link

**Comment by sunnylars** [comment]
Hi, just found the same in my logs.

For the sake of completeness, the url, which returns 404.

https://www.netflix.com/api/shakti/vbb9fbeef/pathEvaluator?drmSystem=widevine&withSize=fals
e&materialize=false&routeAPIRequestsThroughFTL=false&isVolatileBillboardsEnabled=true&isTop10Supported=true&categoryCraversEnabled=false&original_path=%2Fshakti%2Fvbb9fbeef%2FpathEvaluator

IPC callback raised exception: 404 Client Error

but in my case it is on raspberry4 with libreelec 10.0.2

**Comment by CastagnaIT** [comment]
Issue already opened #1428 so refer to that issue
