### ISSUE TITLE
Add option to remember PIN on locked profiles

### ISSUE THREAD

**Issue by 3v1n0** [CastagnaIT/plugin.video.netflix#1439]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

It would be nice to add an option to keep an user PIN saved for the device

#### Describe the use case

I share my account with other family members living in different locations, so it's safe for me to keep the PIN saved in my devices, while I don't want to share it with other people using the same account

**Comment by CastagnaIT** [comment]
a bit strange this request but reasonable
i will try to think of a solution when all ongoing problems will be resolved

**Comment by CastagnaIT** [comment]
I have implemented the requested feature,
please update with this and let me know: [plugin.video.netflix_1.19.1+matrix.1_20221022_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9843895/plugin.video.netflix_1.19.1%2Bmatrix.1_20221022_t1.zip)

The feature can be enabled by opening the context menu on the preferred profile and selecting "Remember PIN"

**Comment by 3v1n0** [comment]
Works great, thanks!

**Comment by CastagnaIT** [comment]
included on new release
