### ISSUE TITLE
MSLError: Message expired and not renewable or missing key request data. Rejected

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#144]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

Randomly, on two 24/7 running RPis, I have this error:

` MSLError: Message expired and not renewable or missing key request data. Rejected. `

The only way to get rid of it is to restart the addon or the system. Then everything works again as expected.

For now, I have no idea of the root cause.

### Addon version used

0.14.5 / 0.14.6 + export episodes features

## Debug log
Sorry logs are not in debug as it's my main install and it's pretty hard to determine when it will pop-up. It's cut to the revelent error, nothing interesting before or after.

https://paste.kodi.tv/ragabefiqo.kodi

**Comment by CastagnaIT** [comment]
to "restart addon" would you say is exit kodi's main menu and so reopen netflix addon?

**Comment by Smeulf** [comment]
restart addon = disable/enable addon

**Comment by CastagnaIT** [comment]
I have some ideas but I have to study better how to do it
for now remains on hold

**Comment by godfath3r** [comment]
I'm getting the same error on kodi 18 on rpi2 after updating to neftlix addon 0.15.3. Logout/login from addon doesn't help, rebooting rpi didn't solve it either.

I've tried what @Smeulf suggested, (disable/enable addon) and it worked.
