### ISSUE TITLE
The add-on encountered the following error: TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'

### ISSUE THREAD

**Issue by bradleygrayhall** [CastagnaIT/plugin.video.netflix#1441]
### Netflix add-on version

1.18.8+matrix.1, 1.18.9+matrix.1, 1.18.10+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

When attempting to access any profile including the one currently being shown as the currently used profile i get a pop up saying: "The add-on encountered the following error: TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'"

I have included the kodi.log below for more details 

### Steps to reproduce the behavior

1. Navigate to app
2. Enter app
3. attempt to enter any profile
4. load for a few seconds to 30 seconds
5. error pop-up

### Debug log - mandatory

https://paste.kodi.tv/pacehucesi.kodi

**Comment by Liqianyu** [comment]
Repeat question, please move to #1425
