### ISSUE TITLE
Stream fails to start with v1.19.0 - License update not successful (no keys)

### ISSUE THREAD

**Issue by peterprusi** [CastagnaIT/plugin.video.netflix#1444]
### Netflix add-on version

1.19.0

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Starting a stream fails with error: One or more items failed to play check the log for more information about this message.
There seems to be a problem with adaptive Inputstream.

### Debug log - mandatory

https://paste.kodi.tv/nahiwipire.kodi

**Comment by CastagnaIT** [comment]
i hope it is due to a transient problem due to all recent changes on website backend
because its unclear the reason why this error happens only on linux
however for now this should works: [plugin.video.netflix_1.19.0+matrix.1_20221004_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9708686/plugin.video.netflix_1.19.0%2Bmatrix.1_20221004_t1.zip)

**Comment by fsiegert** [comment]
I had the same issue on RPi3 with OSMC and `1.19.0+matrix.1_20221004_t1.zip` fixes it for me :tada:. Thanks a lot!

**Comment by chinenual** [comment]
FWIW - I had the same error even after updating to latest adaptive inputstream.  "Solved" it by rebooting my Kodi - works fine now.

Librelec 10/kodi 19.4/RPi4

**Comment by Boose** [comment]
> i hope it is due to a transient problem due to all recent changes on website backend because its unclear the reason why this error happens only on linux however for now this should works: [plugin.video.netflix_1.19.0+matrix.1_20221004_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9708686/plugin.video.netflix_1.19.0%2Bmatrix.1_20221004_t1.zip)

This build has fixed all my playback issues on my RPi4 running LibreELEC 10 with Kodi 19, been playing flawlessly for at least 2 hours now and counting. 
Thank You!

**Comment by peterprusi** [comment]
With 1.19.0+matrix.1_20221004_t1 everything works fine. Thank you!

**Comment by zaurik** [comment]
I'm facing this issue on Windows 10 with Kodi 19. 

I tried [plugin.video.netflix_1.19.0+matrix.1_20221004_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9708686/plugin.video.netflix_1.19.0%2Bmatrix.1_20221004_t1.zip) and even tried restarting Kodi but I'm still facing the issue.

Incase it's of any help, here's my log file https://paste.kodi.tv/eruvoqumiq.kodi

**Comment by andyong79** [comment]
Thanks this build fixed issues for me too on coreelec. Had tried resetting widevine and clearing cache and reinstalling the addon but was still getting errors starting streams but all good now.

**Comment by Alacika** [comment]
The license problem is back with the last version (v1.20.0). I get an error message after starting playback. Restored plugin.video.netflix_1.19.0+matrix.1_20221004_t1 version and all is good again. But when I upgrade to 1.20.0, the playback does not start, there is an error. (Sorry for my poor english!)
