### ISSUE TITLE
[plugin.video.netflix (0)] IPC callback raised exception: 404 Client Error: (Kodi 18)

### ISSUE THREAD

**Issue by VAttila965** [CastagnaIT/plugin.video.netflix#1446]
### Netflix add-on version

 plugin.video.netflix v1.12.14 

### Operative systems used

LibreELEC

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

Netflix starts, 
logs in
after clicking on the addon the profile list is shown as before but:
Clicking on Owner profile the error immadiately occurs

ERROR: 404 Client Error: Not Found for url: https://www.netflix.com/api/shakti/vbb9fbeef/pathEvaluator?m

### Steps to reproduce the behavior

Video Addons
Netflix
select the profile

### Debug log - mandatory

https://paste.kodi.tv/xojevusoqu.kodi

**Comment by CastagnaIT** [comment]
This is same problem of #1425,
read by comment here: https://github.com/CastagnaIT/plugin.video.netflix/issues/1425#issuecomment-1266535143
