### ISSUE TITLE
MSLError User authentication cannot be handled during failover

### ISSUE THREAD

**Issue by edersonmax21** [CastagnaIT/plugin.video.netflix#1447]
### Netflix add-on version

1.19.0

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

After updating the addon to version 1.19.0 I get this error when I try to watch a video: MSLError User authentication cannot be handled during failover

### Steps to reproduce the behavior

1. Open addon
2. I select a video for me to watch
3. the error appears

### Debug log - mandatory

http://paste.kodi.tv/olutovosaz.kodi

**Comment by CastagnaIT** [comment]
First make sure that you have done the Step Two specified here:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#video-stream-only-at-540p-sd-on-android-device

**Comment by CastagnaIT** [comment]
Please try this test: [plugin.video.netflix_1.19.0+matrix.1_20221007_t1_esn.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9731280/plugin.video.netflix_1.19.0%2Bmatrix.1_20221007_t1_esn.zip)
after update addon,
goto Expert settings -> ESN / Widevine settings on the window opened press button "Reset" then apply changes

**Comment by edersonmax21** [comment]
I did this and it didn't work I tried using my netflix esn and it didn't work either.

**Comment by edersonmax21** [comment]
![Screenshot_20221007-211833_Kodi](https://user-images.githubusercontent.com/52547471/194695065-f2c9f308-1f47-4aa5-bf73-ce03b5004cd1.jpg) I used the update from another comment but netflix only works on one profile, the rest of the profiles give this error here.

**Comment by edersonmax21** [comment]
my device is L1

**Comment by CastagnaIT** [comment]
This is last try: [plugin.video.netflix_1.19.0+matrix.1_20221008_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9738855/plugin.video.netflix_1.19.0%2Bmatrix.1_20221008_t3.zip)
After update goto Expert settings you will find a new setting called `Force MSL with idtoken authentication` enable it before play a video

**Comment by edersonmax21** [comment]
didn't work, I'll wait for the next updates to see if it works. Thank you very much.
