### ISSUE TITLE
MSLError User authentication data does not match entity identity

### ISSUE THREAD

**Issue by Yaqwa** [CastagnaIT/plugin.video.netflix#1448]
### Netflix add-on version

1.19.0

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

After updating the addon to version 1.19.0 I get this error when I try to watch a video: MSLError User authentication data does not match entity identity

### Steps to reproduce the behavior

1.Open the addon,
2. I select a video for me to watch
3. the error appears

### Debug log - mandatory

https://paste.kodi.tv/efuqudoceh

### Additional context

All is working fine under Coreelec or Windows- so it is only a Android Problem

### Screenshots

![photo_2022-10-05_12-52-35](https://user-images.githubusercontent.com/62119058/194045294-272f6ee4-9b22-4e7b-bfaf-f26959d2945c.jpg)

**Comment by ersin1903** [comment]
Version 1.19.0 with msl_handler.py, msl_request_builder.py, msl_requests.py & msl_utils.py from version 1.18.9 works on Android. If the device has a Google certification (Widevine L1) without a Netflix license, then the ESN for HD must be NFANDROID1-PRV-C or E , P, T (tested).

**Comment by Yaqwa** [comment]
I tried it with C, E, P, T and none of them are working.
NFANDROID1-PRV-0-KM6-VS===KM6-19773-
worked 3 days before also with 1080 p
So again, if I change the pvr-0 to any other letter it does not work. 
OK if I try to set it to widivine l3 it is running but only with 540p but.... It worked before

**Comment by ersin1903** [comment]
You need a changed 1.19.0 (msl files from 1.18.9)

**Comment by ersin1903** [comment]
@Yaqwa 
Try this, should be OK on your KM6
[plugin.video.netflix_test_android.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9718657/plugin.video.netflix_test_android.zip)

**Comment by Yaqwa** [comment]
Sorry, but there are no settings in the app. So I can't take a screenshot. Also I do not use the official app. I used the coreelec version before I switched to android /km6 and was happy that I could see Netflix on kodi. So all I can say is/was that the ESN settings where like I said before and they worked until 3 or 4 days ago.
If I can help in other ways I will be happy to do so.

**Comment by CastagnaIT** [comment]
i need that you install the official app as temporary way and take the requested screenshots
otherwise i cannot help you

**Comment by CastagnaIT** [comment]
if you install official app for android tv, you will find the page on "Get help" -> device, so take only this

**Comment by Yaqwa** [comment]
OK will do it tomorrow. I will teke the version 9.01 from September 10th. Is this OK? Next version is from Oktober 2nd but I think this is too late? Last is 9.03

**Comment by CastagnaIT** [comment]
if you can use last one 9.03

**Comment by Yaqwa** [comment]
My problem is....... I have a modified version of Netflix at Android because my km6 is not able to use the normal version.
When I install the original app I get the message at start

This version of the Netflix app is not compatible with your device.

So I really do not know how I can help

**Comment by CastagnaIT** [comment]
your device is not approved by netflix there is no much we can do

make a try with this: [plugin.video.netflix_1.19.0+matrix.1_20221007_t1_esn.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9732728/plugin.video.netflix_1.19.0%2Bmatrix.1_20221007_t1_esn.zip)
after update addon,
goto Expert settings -> ESN / Widevine settings
turn off forced security level L3
and press button "Reset" then apply changes

**Comment by Yaqwa** [comment]
Then I get the same message as before.
Data does not Mach entity........

**Comment by CastagnaIT** [comment]
make a last try with this: [plugin.video.netflix_1.19.0+matrix.1_20221007_t2_esn_auth.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9732858/plugin.video.netflix_1.19.0%2Bmatrix.1_20221007_t2_esn_auth.zip)
just update and play

**Comment by Yaqwa** [comment]
Working. Yay. Thanks a lot.

**Comment by CastagnaIT** [comment]
i will have to add a new expert setting for these problematic devices
because there is no safe way to make this change automatic

**Comment by CastagnaIT** [comment]
can you say me what is the max video stream resolution that you see?

**Comment by Yaqwa** [comment]
Max resolution is 1080p but from my account I can view 4k. I do not have a 4k TV so it is useless at the moment (for me) but in the future it would be great to have also 4k if possible

**Comment by CastagnaIT** [comment]
When you update to new addon release you will have to enable on Expert settings `Force MSL with idtoken authentication`
