### ISSUE TITLE
Flatten Seasons 

### ISSUE THREAD

**Issue by SoulTV** [CastagnaIT/plugin.video.netflix#145]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## General information
Can you flatten seasons so that netflix skins work as expected?
### Addon version used
0.14.6
[eg. 13.21.0]

### Description

Flatten Seasons

### Steps to Reproduce

Flatten Seasons

**Expected behavior:** [What you expected to happen]

Flatten Seasons

**Actual behavior:** [What actually happened]

Not flattened seasons

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [x] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional informatin on the environment

Kodi 18.2 and 18.3

## Debug log

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment]
explains better or close

**Comment by dm2912** [comment]
if you go into a show, instead of it showing folders for season 1, season 2, etc, it just shows all the episodes

**Comment by Smeulf** [comment]
`if you go into a show, instead of it showing folders for season 1, season 2, etc, it just shows all the episodes lumped together`

I'd like to know how it helps, when it what case it can be usefull? What's the problem with the current presentation?

Try to convince me! For not, I can't see any benefit, so I wouldn't do the job.

**Comment by Smeulf** [comment]
Just saw it's for the 'netflix' skin... It's a lot of work just for a skin

**Comment by dm2912** [comment]
> Try to convince me! For now, I can't see any benefit, so I wouldn't do the job.

Not going to try, I dont see any real benefit.

And its achievable anyway by just exporting series to the library. You can then set your library view to flatten seasons.

**Comment by Smeulf** [comment]
`Not going to try, I dont see any real benefit.`

The 'try' was not ment directly to you but to anyone who would ;)

And yes library can be a workaround in this case.

**Comment by CastagnaIT** [comment]
I agree you can use the external library,
changing the entire ecosystem for this is counterproductive
both for the work to be done
both for the multiple requests at same time

**Comment by SoulTV** [comment]
@CastagnaIT @dm2912 @Smeulf Netflix UI on Xbox, Android TV, Smart TV's all use flattened seasons. I'm using Titan Bingie but this is true of all Netflix type skins. In order to mimic Netflix season/ episode view on non web UI's, Kodi addons have to flatten seasons. Netflix flattens seasons. All the episodes are in a single row and the box to the left changes season numbers as you scroll through episodes. In order to do this, there has to be an option in an addons settings to flatten seasons. I'm not asking for an overhaul, just a setting that can be toggled for those who are using Netflix style skins. It would be really, really helpful. 
The irony is almost every addon has a flatten seasons option except for the addon used to access content of the company that made it useful. Hope you guys change your mind on this.

**Comment by Smeulf** [comment]
@SoulTV I'm using Kodi since ages, before Netflix ever exists. I love having episodes by season, and Kodi isn't Netflix, it's Kodi and I like it that way. As said it's a lot of work we're not ready to do.

If you can convince me it's usefull, then I can change my mind. If it's just to seems like Netflix, it doesn't worth the work.

But if you want to fork the repo, work on it and propose something, please do!

**Comment by SoulTV** [comment]
@Smeulf fair enough. Thanks for your hard work on the plugin. Love everything else about it

**Comment by CastagnaIT** [comment]
if you believe it is so simple to make the change that you would like so much, you are free to develop it
I know enough the problems that could be there, I am not willing to follow this way
