### ISSUE TITLE
1.19.0+matrix.1 inputstream.adaptive: Initialize failed

### ISSUE THREAD

**Issue by srhubbed** [CastagnaIT/plugin.video.netflix#1451]
This is in response to Rework for new website endpoints #1429
  Raspberry Pi 4,  Raspbian OS Lite:  GNU/Linux 11 (bullseye), kernel 5.15.61-v7l+
  KODI 19.04.0,  InputStream adaptive 19.0.3,  repository.castagnait-2.0.0

The latest 1.19.0+matrix.1 fails to initialize inputstream.adaptive, and errors out
see log:  CastagnaIT_Version_1.19.0+matrix.1 Err kodi.log
2022-10-05 13:07:57.755 T:1210    ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)

BUT lowering version to 1.18.10+matrix.1 does and plays netflix video
see log:  CastagnaIT_Version_1.18.10+matrix.1 OK kodi.log
2022-10-05 13:17:51.514 T:1227    DEBUG <general>: AddOnLog: inputstream.adaptive: GetStream(1001): initalizing crypto session
[CastagnaIT_Version_1.19.0+matrix.1 Err kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/9718730/CastagnaIT_Version_1.19.0%2Bmatrix.1.Err.kodi.log)
[CastagnaIT_Version_1.18.10+matrix.1 OK kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/9718731/CastagnaIT_Version_1.18.10%2Bmatrix.1.OK.kodi.log)

**Comment by CastagnaIT** [comment]
your error is the same of #1444
so follow that issue
