### ISSUE TITLE
Add support to a local proxy

### ISSUE THREAD

**Issue by Astaoth** [CastagnaIT/plugin.video.netflix#1455]
## Feature request
I'm submitting a proposal to ...
  - [X] new feature
  - [ ] change an existing feature

### Describe your request
In first, I would like to state that I've read [this issue](https://github.com/CastagnaIT/plugin.video.netflix/issues/1315) and [this page](https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy).
However my purpose is actually to be compliant to the Netflix rules. I don't need to access to an external proxy on some external network, but only to one on my local network, or even on the localhost. Please read the use case part before writting an answer.

#### Describe the use case
On my home LAN, my whole traffic go through a network firewall. On this firewall, I have setup external VPN in which will be routed my whole home traffic. However, for Netflix, I have to route the traffic outside of the VPN.
Usually, I would simply make a firewall rule with the IP addresses of the service provider. However, Netflix is hosted on AWS, and they have dynamic IP address pool. One can't create a rule dedicated to the Netflix traffic, it would have to be a rule for every traffic going to AWS servers.
My Kodi device is not dedicated to Netflix traffic only. Making a firewall rule for routing the whole traffic coming from this device outside of the VPN would nullify the first purpose of having VPN tunnels on my firewall.

The best solution for me is to be able to route only the Netflix traffic either on a dedicated proxy on my LAN or a dedicated interface of my Kodi device, and then make a rule on my network firewall for bypassing the VPN tunnels.

#### Describe an alternative
That's actually my last idea for routing only the Netflix traffic outside of the network VPN and be compliant to the Netflix rules.

#### Development tips
I understand that you don't want to be accused to let users to bypass the Netflix rules. A compromised could be to block the proxy configuration to either a LAN addres, or even to the localhost. This way, you don't allow an external proxy, and what would be done on the local LAN or device would be the user responsability.

#### Specific details
On [this page](https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy) there is written "In compliance with the rules of the Kodi platform and members of its foundation and to avoid legal problems, this add-on does not support the use of VPN or Proxy."
However, Kodi allows users to define a proxy server : https://imgur.com/a/6Bj1vnq
But I can't use this, because it will catch the whole Kodi traffic and not only the Netflix one.

**Comment by CastagnaIT** [comment]
everyone has their own motivations to make any type of request
but the responsibility for the addon is on my shoulders here.

I personally don't want to implement something that somehow annoys the Netflix company,
is already happened in the past for different reasons that Netflix's lawyers sued a previous developer of this addon,
so i am not going to risk receiving warning letters from lawyers

if you want to implement any kind of proxy or VPN support in a limited or not form,
you will have to do it outside this official addon channel
therefore possible risks derived from a different use will not be attributed to me as current developer maintainer
