### ISSUE TITLE
Key error trackid

### ISSUE THREAD

**Issue by Yaqwa** [CastagnaIT/plugin.video.netflix#1458]
### Netflix add-on version

 plugin.video.netflix_1.19.0+matrix.1_20221007_t2_esn_auth

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

When I am on my watchlist (and only there) and try to remove a title from the list, I get this error message.
When I go to (sorry if the English one is different)" look further with the profile of......." there I can delete/remove the title. Works perfect. So the problem is only in "my list" 

### Steps to reproduce the behavior

1. Go to my list/watchlist
2. Remove a title from the list
3. Message occures

### Debug log - mandatory

https://paste.kodi.tv/raw/bunayakoci

### Screenshots

![IMG_20221010_134858_714](https://user-images.githubusercontent.com/62119058/194860023-109040c1-2bd4-48e9-a4e5-51aec925b157.jpg)

**Comment by CastagnaIT** [comment]
update addon with official release
