### ISSUE TITLE
MSLError: Sorry, your account can't be used on this device.

### ISSUE THREAD

**Issue by TooLazyToChangeAccounts** [CastagnaIT/plugin.video.netflix#1462]
### Netflix add-on version

1.19.1

### Operative systems used

Android, Other (specify in description)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Android 9 (TV)

When trying to play anything, I get the error:
MSLError Lo sentimos, pero tu cuenta no se puede usar en este dispositivo

(Translates to: MSLError Sorry, your account can't be used on this device)

Looking for the error online gets me this netflix help page
https://help.netflix.com/en/node/110819

### Debug log - mandatory

https://paste.kodi.tv/unatezaruk.kodi

### Screenshots

![IMG_20221011_222608](https://user-images.githubusercontent.com/115601985/195250005-91331f06-e3e6-450b-9f62-4c2bb2f770ec.jpg)

**Comment by CastagnaIT** [comment]
First try enable on Expert setting `Force MSL with idtoken authentication` and try play a video

if still now works try follow instructions explained here:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#This-title-is-not-available-to-watch-instantly

if after all that the message still to be the same, then there are no other solutions

**Comment by TooLazyToChangeAccounts** [comment]
alright thanks

i managed to made it work in 2 different ways

i either 
1 change the esn to the one in my phone 
2 leave the Widevine - Force security level to deactivated
3  set Force MSL with idtoken authentication to on

or i
1 change the esn to the one in my phone 
2 set the Widevine - Force security level to Force L3
3 leave Force MSL with idtoken authentication to off

what would you recommend is the better option

**Comment by CastagnaIT** [comment]
the first one is better (Force security level disabled)

**Comment by CastagnaIT** [comment]
can you show me your ESN used?

**Comment by TooLazyToChangeAccounts** [comment]
Alright Thanks

The only thing i changed from the ESN is change "NFANDROID2" to NFANDROID1"

everything else i left the same

do you need the rest of the ESN?

**Comment by djkiranvarma** [comment]
MSLError Sorry, your account can't be used on this device.

Are you able to resolve this issue now? 

Please help me with the steps if any procedure is available. 

Thank you,
Jitendra

**Comment by Alpuemed** [comment]
Hi!, I have this issue with a Mecool KM1 with Kodi 20. I can't find the option "Force MSL with idtoken authentication" to set it to false... any help?.
