### ISSUE TITLE
Exception : Due to changes to the Netflix website , on Android L3 devices videos can only be played from the main / owner profile .

### ISSUE THREAD

**Issue by edersonmax21** [CastagnaIT/plugin.video.netflix#1463]
### Netflix add-on version

1.19.1

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

My device is widevine L1 and I get this error after trying to watch a video in my usage profile, in a profile (which is not mine) It works without any problems.

### Steps to reproduce the behavior

1. open netflix addon
2. I select my profile
3. I select a video
4. The error appears as in the image below

### Debug log - mandatory

https://paste.kodi.tv/omatobasaj.kodi

### Screenshots

![Screenshot_20221007-211833_Kodi](https://user-images.githubusercontent.com/52547471/195259824-e1ad1d2e-9035-42ab-8163-34b14387b356.jpg)

**Comment by CastagnaIT** [comment]
you have enabled `Force MSL with idtoken authentication` the setting description explain this
and there is no other solutions

**Comment by CastagnaIT** [comment]
Seem that website has restored the profile switching
so at least my first test on my L3 android playback works on my second profile

i dont know if it is a case i need a confirm from others please
OFC on android devices only

Test build: [plugin.video.netflix_1.19.1+matrix.1_20221022_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9844366/plugin.video.netflix_1.19.1%2Bmatrix.1_20221022_t1.zip)

maybe can give me a feedback also @ltai0001 @George-R-Young ?

**Comment by George-R-Young** [comment]
With the new t1 plugin, I get a different error, Recursion Error, maximum number of recursions etc.

**Comment by kedarz** [comment]
> With the new t1 plugin, I get a different error, Recursion Error, maximum number of recursions etc.

I have the same error

**Comment by CastagnaIT** [comment]
woops sorry after cleanup things i have made a infinite loop, follow fixed build:
[plugin.video.netflix_1.19.1+matrix.1_20221022_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9844681/plugin.video.netflix_1.19.1%2Bmatrix.1_20221022_t2.zip)

**Comment by edersonmax21** [comment]
It worked, thank you very much, everything is fine now.

**Comment by kedarz** [comment]
It's working great for me. Thanks a lot

**Comment by George-R-Young** [comment]
The t2 plugin works fine in my non-main profile. So now I can go back to enjoying dolby digital plus sound which is not available from the cursed netflix app.

**Comment by ltai0001** [comment]
> Seem that website has restored the profile switching
> 
> so at least my first test on my L3 android playback works on my second profile
> 
> 
> 
> i dont know if it is a case i need a confirm from others please
> 
> OFC on android devices only
> 
> 
> 
> Test build: ~[plugin.video.netflix_1.19.1+matrix.1_20221022_t1.zip]~
> 
> EDIT, FIXED BUILD: [plugin.video.netflix_1.19.1+matrix.1_20221022_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9844686/plugin.video.netflix_1.19.1%2Bmatrix.1_20221022_t2.zip)
> 
> 
> 
> 
> 
> maybe can give me a feedback also @ltai0001 @George-R-Young @sheogorat96?

Seems to be working again I see the kids profile menu - I am still on your version from October 9th 1.19.1

**Comment by CastagnaIT** [comment]
thank you
i will merge the change
