### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by CHJ85** [CastagnaIT/plugin.video.netflix#1465]
Can you please try and come up with an easier way to login? Email and Password is not working and I don't know how to get the auth key thing because my Kodi is installed as Flatpak.
Perhaps you could use Netflix's device activation code: netflix.com/tv8.
And it'd help if the login info was readable from the settings.xml file. That ways I can paste in my credentials without having to use Kodi. Thank you.

**Comment by CastagnaIT** [comment]
instructions here https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

**Comment by CHJ85** [comment]
@CastagnaIT  This method requires sudo access though.
And Flatpak is sandboxed.

**Comment by CastagnaIT** [comment]
does not require anything, can be run on any computer with linux (e.g. ubuntu) or windows operating system,
no `sudo` needed, could be a problem only if you have particular setup with restricted linux users profiles privilegies

this addon takes care of security to prevent unauthorised access to the account by malicious software or addons
if credentials were saved on plain-text xml, any Kodi addon could read them and disclose them without your knowledge
then if you don't like that this addon encrypt credential it is not our problem

**Comment by CHJ85** [comment]
Well. I'm using the Steam Deck. So system wide installations are restricted, hence Flatpak.
However. I just ran the script and it turns out that all the python dependencies were already installed.
Thanks for your help.

**Comment by CastagnaIT** [comment]
you have to use a real computer system not a console game

**Comment by CHJ85** [comment]
Nah, it worked fine.

**Comment by Acelya-9028** [comment]
> you have to use a real computer system not a console game is also written in instructions:
> 
> > You can create the NFAuthentication.key file from any Personal Computer (desktop / laptop)

Sorry to react but the Steam Deck is a real linux computer system who use Arch Linux... It's just a laptop in a different shape...
