### ISSUE TITLE
Add support to unlock pre-release content with PIN

### ISSUE THREAD

**Issue by misterkoat** [CastagnaIT/plugin.video.netflix#1472]
There is some early preview content that requires 4 PIN numeric code before they can be played. Currently, the addon gives the error "content not available for instant playback." It would be of much help if you can add the option to input the code.

**Comment by misterkoat** [comment]
Something from the kodi log reads: Pre-release content authorization requires a user-initiated request.

**Comment by CastagnaIT** [comment]
i need you provide a pratical example on how test this otherwise no idea what to do

**Comment by misterkoat** [comment]
I didn't know how to create a HAR log, but I've tried it. Take a look. I input the wrong pin while recording the session and I hope it's enough.
[Log.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9874874/Log.zip)

**Comment by CastagnaIT** [comment]
yeah the log is perfect seem website its using only encrypted way then i cannot see nothing, but at least i have excluded something
i will try prepare a test hoping it works, then i will need you to provide me Kodi logs
I will let you know later with instructions

**Comment by CastagnaIT** [comment]
Can you explain me how you get account enabled for pre-release?
is there a special website section for pre-release content?

This a the test build: [plugin.video.netflix_1.20.0+matrix.1_20221027_t1_pin.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9881256/plugin.video.netflix_1.20.0%2Bmatrix.1_20221027_t1_pin.zip)

just update and play,
if works please also test with a wrong pin
so see if it show to you the right error message and allow you to try put PIN again at same time

**Comment by misterkoat** [comment]
Pre-lease content is privileged for tv journalists. For said content, it appears in its own section and also appears in search.

I have updated the test build and tested it with the wrong pin; it didn't work and gave me the option to input the PIN again.

Unfortunately, when I entered the correct one, it gave me the same error it did before.

**Comment by CastagnaIT** [comment]
i tried change data type,
try this: [plugin.video.netflix_1.20.0+matrix.1_20221028_t2_pin.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9885696/plugin.video.netflix_1.20.0%2Bmatrix.1_20221028_t2_pin.zip)

**Comment by misterkoat** [comment]
Still gives the same error after inputting correct pin.
________________________________

**Comment by CastagnaIT** [comment]
unfortunately there is nothing more i can do
since my account is not enabled to prerelease content
i cannot analize browser network with mitmproxy to try understand what is missing or what change is needed
otherwise you should try analize network yourself if you are experienced enough

**Comment by misterkoat** [comment]
Well, thanks for trying.

I'm not experienced enough to do that. I'll stick with the browsers as they
seem to be doing the job though I'd have preferred watching everything on
kodi for a few reasons.

Again, thank you for your efforts.

**Comment by CastagnaIT** [comment]
I add a note if in the future someone else with pre-release content enabled account want investigate
i have add a branch with the changes needed: https://github.com/CastagnaIT/plugin.video.netflix/tree/prerelease_content
but OFC need to be fixed how PIN data is added in manifest

**Comment by misterkoat** [comment]
Do you think that if you had access to an account with pre-release content, you might be able to figure it out?

**Comment by CastagnaIT** [comment]
yes it will allow me to analyse the network flow of the website more in depth,
ofc its an attempt then i cannot guarantee that it will work

**Comment by misterkoat** [comment]
I don't mean to trivialise what you do, I don't think it's really complicated.

I used this basic app that can actually decrypt the content. A log in page would show up and after inputting the pin, it would work.
________________________________

**Comment by CastagnaIT** [comment]
> I used this basic app that can actually decrypt the content. A log in page would show up and after inputting the pin, it would work

i am not able to full understand what you mean in your last comment,
maybe you have attached to the message something? if no, please explain better
if you use emails to reply to comments on github website you are limited to plain-text only

**Comment by CastagnaIT** [comment]
i have add this to Project section,
so for now i close the Issue
