### ISSUE TITLE
Error on netflix addon startup

### ISSUE THREAD

**Issue by Saskya99** [CastagnaIT/plugin.video.netflix#148]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Addon version used
0.14.6

### Description
Error on Kodi start up : "headerdata"
And I can't open netflix addon, I get this error : "AddonSignals call timed out" 

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional informatin on the environment
I'm using a Formuler Z8 box with android 7

## Debug log
https://paste.kodi.tv/ekehoropur.kodi

**Comment by CastagnaIT** [comment]
I need more info try this,
install this test and extract a new debug log
[plugin.video.netflix_TEST1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3439444/plugin.video.netflix_TEST1.zip)

**Comment by Saskya99** [comment]
Ok installed and the new debug log : https://paste.kodi.tv/ewetudatuj.kodi

**Comment by CastagnaIT** [comment]
I suspect that this device is part of the andoird boxes not completely authorized to use netflix
I believe nothing can be done

**Comment by Saskya99** [comment]
ha ok
I didn't pay attention to this... when I buy this box... I'm disappointed.

Thanks for the help

**Comment by CastagnaIT** [comment]
if there is an firmware upgrade to android 8 you can try to do it
it is possible that updating it with more recent android then it works

**Comment by Saskya99** [comment]
I checked and this box is only compatible with WIDEVINE L3... not L1... :/

And I can't upgrade to android 8 on this box
