### ISSUE TITLE
Add video auto bitrate

### ISSUE THREAD

**Issue by godshades** [CastagnaIT/plugin.video.netflix#1483]
Hi, thanks for your awesome plugin
I have xiaomi tv and can watch 1080p
But some movie have very high bit rate so the frame will drop Do you have any solution for this 🙏
Maybe auto bit rate or can select lower bit rate in video tab

**Comment by CastagnaIT** [comment]
the only solutions for devices with low end CPUs are specified on wiki:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-(Audio,-Video,-Subtitle,-Other)#video-playback-problems-like-frame-drops-slowdown-stuttering
