### ISSUE TITLE
RESOLVED! Stream buffers(?) , pauses then catches up or pauses the stops

### ISSUE THREAD

**Issue by markosjal** [CastagnaIT/plugin.video.netflix#1486]
### Netflix add-on version

1.20.0+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Using LibreElec x86_64 Generic on Intel hardware (Asus CN60 Chromebox with MrChromebox.info)

Playing most any  show or movie system pauses, and seems to buffer. Other addons such as Hulu, Paramount+ , etc do not have this issue. I have tried disabling VP9 and still have the same issues. Have a tried many other options as wall and unable to find a fix. This occurs even when I set resolution to 720P (in Inputstream Adaptive) to keep CPU use even lower  .Happens with VP9 or h264

This may have to do with "Large Audio Sync Errors" seen in log

THIS IS NOT AN INTERNET SPEED ISSUE

THIS IS NOT A MAX CPU ISSUE (DUE TO SOFTWARE DECODE)

### Steps to reproduce the behavior

Play most any Movie or TV series for more than 30 minutes or so

### Debug log - mandatory

https://paste.kodi.tv/kanotudiji.kodi

**Comment by CastagnaIT** [comment]
This is not a network speed issue and not a CPU problem,
by looking at log there are tons of network errors of different types
this leads me to think these possibilities:
you are connected to a wrong configured network,
or you have installed an bad developed addon that corrupt in some way network traffic,
or your network provider has a malfunction and provide you a unstable connection,
or you are behind an unstable VPN or Proxy (both not supported by this addon)

the `ActiveAE - large audio sync error` warnings always starts when InputStream Adaptive is not able to download the stream,
after that ofc the stream results stalled, also in this case means a kind of connection problem

is not a problem related to this addon

**Comment by CastagnaIT** [comment]
you can also try force change CDN server from the add-on Expert settings
but i don't think it is a good solution given all the errors

**Comment by markosjal** [comment]
I did try to force that CDN change that you recommend but it did not fix the issue. 

What you are saying is semi consistent with another error that I have seen in the netflix Kodi GUI that something about an "Internet connection..."  when I go to launch playing a video that does not launch. However I have Many other addons that I use that do not exhibit this behavior nor anything like it, including PVR which is usually the first thing to balk at a poor Internet connection, and neither server nor clients do. By the way I also have this same netflix issue on a completely different system Which is based on a Mission One (Intel hardware) .

Note that this same machine was until 2 days ago serving as my Samba HDD server until only a few days ago and was consistently available to all other machines on the network. I only recently changed that because as a test I took it off the 5Ghz WIfi and moved it to slower 2.4 Ghz WiFi , and have even tested with a completely different access point 

The Internet provider is Comcast Xfinity and running hour long ping ( on either 2.4 Ghz or 5Ghz to google.com I see no dropped packets!

Also, according to my testing  other connections such as SAMBA and SSH to this same machine can remain active during this freeze time, even with active file transfers, and remain connected to the Internet. I know this because I can set this as a record destination (via SMB Share) on My Pi running a DVR software and the Pi keeps recording a stream from the internet to this same machine's samba share via the LAN without interruption while the netflix client freezes as if it (and it alone), has lost internet access.

It seems to me to be more related to the server connection either getting busy or becoming unavailable.

**Comment by CastagnaIT** [comment]
im sorry but with this addon there is nothing that can help you

**Comment by markosjal** [comment]
Just FYI, As I was beginning to suspect something on the wireless network....I ran it with a WIRED ethernet connection tonight and Netflix gave me the same issues.

**Comment by markosjal** [comment]
I believe I found the solution for this problem but not sure exactly which adjustment caused it to work but I believe it was the first item below after doing a reset of the addon.

In LibreElec 
I had IPV6 disabled, so I set it to "auto"

In Netflix addon
Disabled VP9 Profiles (VP9 seems to require greater CPU to software decode)
Enable IPC over HTTP

I must  say also that turning VP9 off also allows for smoother pause/unpause and jump forward.

**Comment by CastagnaIT** [comment]
> I had IPV6 disabled, so I set it to "auto"

good to know
