### ISSUE TITLE
Stream fails to start with v1.20.0 - License update not successful (no keys) - Problem is return

### ISSUE THREAD

**Issue by Alacika** [CastagnaIT/plugin.video.netflix#1487]
### Netflix add-on version

v1.20.0

### Operative systems used

Raspbian

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Starting a stream fails with error: One or more items failed to play check the log for more information about this message.

The license problem is back with the last version (v1.20.0). I get an error message after starting playback. Restored plugin.video.netflix_1.19.0+matrix.1_20221004_t1 version and all is good again. But when I upgrade to 1.20.0, the playback does not start, there is an error. I use it on Raspberry PI 4 with Raspbian. (Sorry for my poor english!)

### Debug log - mandatory

https://paste.kodi.tv/eqatajevil.kodi

**Comment by theoden11** [comment]
Good evening. I can confirm, same problem with my Vero at home, since update yesterday. Coming back to 1.19.1 release.

**Comment by CastagnaIT** [comment]
the code on: plugin.video.netflix_1.19.0+matrix.1_20221004_t1 its the same of current 1.20
i need to check from 1.19.1 release again

Netflix these days work like shit and make server bugs...that fix after a week or so
they make new changes and after they restore old ways
gives you a headache!

**Comment by theoden11** [comment]
Headache of course I mean. plugin.video.netflix_1.19.1+matrix.1 is working, verified again this morning. Unfortunately, several other plugins like CatchupTVandMore and Netflix are simultaneously buggy after recent update, so it's a continous headache ! A little disappointed as plugins should be seriously verified and tested in severe conditions before releasing.

**Comment by CastagnaIT** [comment]
> A little disappointed as plugins should be seriously verified and tested in severe conditions before releasing

in this case the problem is that netflix itself make continuos changes on its servers
so its really impossible have a stable addon

i found the problem, this should works: [plugin.video.netflix_1.20.0+matrix.1_20221030_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/9895623/plugin.video.netflix_1.20.0%2Bmatrix.1_20221030_t1.zip)

Given the oddity of the change required, I am not surprised if a new fix is needed in a few days' time

**Comment by Alacika** [comment]
> 

Yes, it works perfectly. Thank you! :-)

**Comment by CastagnaIT** [comment]
new addon version released
