### ISSUE TITLE
Exception: AddonSignals call timed out

### ISSUE THREAD

**Issue by leosmeira** [CastagnaIT/plugin.video.netflix#149]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

## General information
Error when try play vídeo

### Addon version used
v0.14.6

### Installation

* [X ] I'm using this Netflix Repo

### Operating System

* [X ] Linux (ARM)

#### Additional informatin on the environment
LibreELEC 9.1.001 Kernel 4.19.50 (RPI3)
Kodi 18.3
InputStream Adaptive 2.3.22.1
script.module.requests 2.12.4
script.module.pycryptodome 3.4.3
script.module.inputstreamhelper 0.3.3
script.module.addon.signals 0.0.3
script.module.urllib3 1.22
script.module.chardet 3.0.4
script.module.idna 2.6
script.module.certifi 2017.07.27.1
script.module.kodi-six 0.0.2

## Debug log

https://paste.kodi.tv/enunalukaw.kodi

**Comment by Smeulf** [comment]
error: [Errno 98] Address already in use

Sounds like to port for MSL (35879) is already used by something else (maybe started after it was selected by the addon). 

The port is computed on each startup, so maybe if you restart you won't see the error again.

You can try to determine what's using it using  lsof | grep 'xxxxx' with xxxxx the port number in the log (see [MSL] Picked Port: 35879)

@CastagnaIT if the port is already in use, maybe it would be interesting to pick an another port and try again?

**Comment by Smeulf** [comment]
@leosmeira You're using an Alpha version of LibreELEC. Don't expect everything to work fine yet ^^

**Comment by leosmeira** [comment]
Thank you for your support

For some reason the router was having problems with wifi and cable connections were working.

I would like to suggest a ping test for Netflix addresses and an error message if they are not currently accessible.
