### ISSUE TITLE
You are using a bugged Kodi version, please update to Kodi 20 or above

### ISSUE THREAD

**Issue by tommeier666** [CastagnaIT/plugin.video.netflix#1492]
### Netflix add-on version

1.20.1+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

First: I'm getting this message when starting any video from netflix addon:
WARNING <general>: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2022-10-07 00:14:10.024 T:14624   ERROR <general>: [plugin.video.netflix (0)] You are using a bugged Kodi version, please update to Kodi 20 or above: All Netflix add-on features has been now disabled and cannot be used.

The video will be played but there is no sound. I wonder why. I did look at the source code, but do not undestand why this problem shows up.

Second: There is a typo in this message, it should be "All Netflix add-on features have been now disabled" instead of "has been"

I'm using a Raspberry Pi 3 with libreelec 10.3.

Source code from am_stream_continuity.py:
```

if (player_state.get(STREAMS['subtitle']['current']) is None and
                player_state.get('currentvideostream') is None):
            # KODI BUG! All Kodi v19 Matrix versions have the playlist bug, full fixed in version 20
            # These versions set a wrong playlist id and corrupt the response data in JSON-RPC calls.
            self.enabled = False
            LOG.error('You are using a bugged Kodi version, please update to Kodi 20 or above: '
                      'All Netflix add-on features has been now disabled and cannot be used.')
            ui.show_notification(title=common.get_local_string(30105),
                                 msg='A Kodi bug prevent to use Netflix features, please update to Kodi 20 or above.')
            return
```

### Steps to reproduce the behavior

Happens to all videos I start from netflix addon

### Debug log - mandatory

is this needed?

**Comment by CastagnaIT** [comment]
the error

> You are using a bugged Kodi version, please update to Kodi 20 or above ...

has nothing to do with your audio problem

more likely you have a wrong audio setup somewhere could be Kodi and/or OS and/or AV-TV

the playlist bug affect all kodi versions until v19 included, and cannot be fixed by our part,
this bug not allow to use addon features, so most of addon settings will not works
