### ISSUE TITLE
No HDR on some Films/Series in 4K

### ISSUE THREAD

**Issue by semool** [CastagnaIT/plugin.video.netflix#1493]
### Netflix add-on version

1.20.1

### Operative systems used

Android, Other (specify in description)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Shield 2019.
In the last Days i noticed that some Videos played fine in 4k but without HDR.
Examples: The Watcher and actual Enola Holmes 2

### Debug log - mandatory

-

### Possible fix

After looking at the latest changes in the code i get this one:
https://github.com/CastagnaIT/plugin.video.netflix/commit/6a0d09e7706fcc3aec82a4ff0eb2e1bca5f4a4af

I have changed the hdr part to the old values:
```
'hdr':
        _profile_strings(base=HDR,
                         tails=[(LEVELS_3 + LEVELS_4 + LEVELS_5, CENC),
                                (LEVELS_3 + LEVELS_4 + LEVELS_5, CENC_PRK),
                                (LEVELS_3 + LEVELS_4 + LEVELS_5, CENC_PRK_DO)]),
```
And now the 4K Videos have HDR again.

**Comment by CastagnaIT** [comment]
please test with this:

```
'hdr':
        _profile_strings(base=HDR,
                         tails=[(LEVELS_3 + LEVELS_4 + LEVELS_5, CENC_PRK),
                                (LEVELS_3 + LEVELS_4 + LEVELS_5, CENC_PRK_DO)]),
```
                                
the following tail do not exists on website

> (LEVELS_3 + LEVELS_4 + LEVELS_5, CENC),

**Comment by Liqianyu** [comment]
After testing, this restores 4K HDR display. The test movie was Enola Holmes 2.

**Comment by semool** [comment]
> please test with this:
> 
> ```
> 'hdr':
>         _profile_strings(base=HDR,
>                          tails=[(LEVELS_3 + LEVELS_4 + LEVELS_5, CENC_PRK),
>                                 (LEVELS_3 + LEVELS_4 + LEVELS_5, CENC_PRK_DO)]),
> ```
> 
> the following tail do not exists on website
> 
> > (LEVELS_3 + LEVELS_4 + LEVELS_5, CENC),

Yes this is working fine here.
