### ISSUE TITLE
Error playing any Netflix Stream on Matrix / Android

### ISSUE THREAD

**Issue by entonjackson** [CastagnaIT/plugin.video.netflix#1498]
### Netflix add-on version

v1.20.1+matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Unable to play any Netflix stream. Always resulting in error attached in kodi.log.

### Steps to reproduce the behavior

1. Open Netflix-addon
2. Choose my profile
3. Open "my list"
4. Choose a show
5. Choose a season
6. Press ok on an episode
7. Getting Error

### Debug log - mandatory

https://paste.kodi.tv/nenefoxojo.kodi

### Screenshots

  ![photo_2022-11-10_13-22-05](https://user-images.githubusercontent.com/372369/201066324-e66ffaa0-1d1e-4be3-b66d-1f4a13fb0718.jpg)
  
  ![photo_2022-11-10_13-22-13](https://user-images.githubusercontent.com/372369/201066341-052aa04c-9ec2-4acd-823b-080494164961.jpg)

**Comment by CastagnaIT** [comment]
for libreelec the problem its the same of #1497 so follow that issue
for android you have not provided log nor device model nor os version...
