### ISSUE TITLE
Errors on b22 - menu_title 

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#15]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
In version 22b, when going to different menu items, the error "menu_title"  will appear
### Addon version used
14b22
[eg. 13.21.0]

### Description
In version 22b, when going to different menu items (or searching), the error "menu_title"  will appear. Sometimes he throws away the error from the addon. Sometimes, after several attempts, you will be able to enter a given menu item

### Steps to Reproduce

1. Go to main menu
2. Go to Netflix Originals (ex)
3. The error appears
4. Somatimes going again to Netflix Originals working

**Expected behavior:** [What you expected to happen]
Working like b21
**Actual behavior:** [What actually happened]
Not working like b21 - cannot for example use widget to my list in skin - the widget is not loading
### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [] I'm using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Windows 10, k18.1
Arch Linux k18.0
Coreelec 9.0.1

## Debug log
https://pastebin.com/TfFV4czN

**Comment by CastagnaIT** [comment]
I saw this error too, i made several attempts but i have not yet been able to reproduce it to make a debug

**Comment by ciwy85** [comment]
I get the same error

**Comment by CastagnaIT** [comment]
can you show me some screenshots of what you mean by widgets?

**Comment by notoco** [comment]
Widget on main screen in kodi skin Aura:
![screenshot001](https://user-images.githubusercontent.com/36659110/54072180-5ff5da80-4277-11e9-9d77-165ffd7a354f.png)
Leads to my list, and in 21b works. In version 22b I have errors and the widget does not load. It is sometimes shown, as it is sometimes possible to enter the menu.
To reproduce the error, the easiest way is to clear the plugin settings in the profile, restart the kodi, log in to netflix and try to enter the menu - some time this error will pop up and the plug comes out sometimes to the main library window

**Comment by notoco** [comment]
BTW - I uploaded the 21bfixed + pl version to the repository. The repository is nowhere advertised, it is only given to users of the forum kodiwpigulce.pl - which would be easier for non-English speakers in PL. I do not give a link here, so as not to make unnecessary confusion. If you do not agree, I'll make a private repository.

**Comment by ciwy85** [comment]
Where do you get en version of the repository from?

**Comment by CastagnaIT** [comment]
I'm modifying the menu function code again,
I don't think I'll finish today, but when I'm ready I'll post a test version here, to get your feedback

**Comment by notoco** [comment]
@ciwy85 - there is no repository - look here for different version: https://www.mediafire.com/folder/vifnw8ve44bi7/KodiNetflixAddon
@CastagnaIT -thx

**Comment by CastagnaIT** [comment]
after hours i found the caause whore, kodi reinitializes the addon for each operation, and lost the global data in the modules, fixed in the latest DailyBuild, try it out

**Comment by notoco** [comment]
Everything works now. Maybe it's a placebo effect, but it seems to me that it's all a lot faster.
A great job. Thx

**Comment by notoco** [comment]
The only "mistake" I noticed is the need to re-set the widgets in the skin. When leaving the old, the "queue" error popped up.

**Comment by ExpatUK** [comment]
Getting this issue for the first time today on one system only (fresh install) - other 2 work as expected.

Seems inconsistent as I was watching an episode fine, quit out to change subtitle background settings and got the error when going back into the plugin. Restarting/etc doesn't help.
