### ISSUE TITLE
Allow poster to be exporter to library

### ISSUE THREAD

**Issue by jvisser** [CastagnaIT/plugin.video.netflix#150]
*I'm submitting a feature request

Would love to have an option for the netflix poster be exported to the library so it can be shown in the kodi library using the original netflix poster.

Thanks

**Comment by Smeulf** [comment]
Enable NFO export in the addon settings/library. Ensure 'full informations' (last option) is enabled.

Et voilà, you should see the posters.

**Comment by Smeulf** [comment]
Have to mention that seasons posters doesn't exist, so can't be exported.

**Comment by jvisser** [comment]
Cool totally missed that. Thanks!
