### ISSUE TITLE
Background service cannot start (Crypto.Util & python 3.11)

### ISSUE THREAD

**Issue by r2rX** [CastagnaIT/plugin.video.netflix#1504]
### Netflix add-on version

1.20.2

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Hello there,

I recently updated Fedora KDE from v36 to v37. Subsequently. After the upgrade, attempting to run the Netflix plugin results in an error where the Background Service cannot be started (Crypto.Util error w/ python 3.11).

Prior to the upgrade, it was working fine. So I uninstalled and reinstalled the plugin as well as double-checking that the python and python-libs packages are installed. Kodi is installed from the Fedora repo.

### Steps to reproduce the behavior

1. Run Fedora 37 (or other Linux OS) with python 3.11 & libs package installed. (For Fedora, it's _python3-3.11.0-1.fc37_ & _python3-libs-3.11.0-1.fc37_)
2. Run Kodi 19.4 w/ Netflix 1.20.2 plugin installed.
3. Try run plugin in Kodi.

### Debug log - mandatory

https://paste.kodi.tv/ohavuvobac.kodi

**Comment by CastagnaIT** [comment]
you have installed pycrypto
but instead you should install pycryptodomex

**Comment by r2rX** [comment]
Thanks @CastagnaIT. Not sure why this lib was removed during the Fedora upgrade process but it was not installed. After installing pycryptodomex, it works! Thanks alot!
