### ISSUE TITLE
NFAuthenticationKey.py script - Not found cookies

### ISSUE THREAD

**Issue by klopster** [CastagnaIT/plugin.video.netflix#1506]
Hi, I was trying to run this authentication script from Linux Mint machine on both Chromium and Brave web browsers, both without success. I'm stuck getting error: "Not found cookies".
In both browsers I did allowed cookies and they are stored after normal session login, even in incognito mode.
But the script can't locate it. Is there any way to copy all cookies into a text file and let the script to read from it? 
Cheers for help!

Chromium: Version 106.0.5249.119 (Official Build) for Linux Mint (64-bit)
Brave: Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (64-bit)
Linux Mint: Linux Mint 20.3, core-11.1.0ubuntu2-noarch

**Comment by antonioxerez** [comment]
Good afternoon, same issue here. I have granted cookies for all websites and more configs tried with no success... could be some change at Netflix level... Let's see if someone can help us :)

**Comment by CastagnaIT** [comment]
i will try check on next days

**Comment by CastagnaIT** [comment]
found time, please try with this updated: [NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/10083130/NFAuthenticationKey.zip)
and let me know

**Comment by klopster** [comment]
...now works perfectly on Chromium Version 106.0.5249.119 (Official Build) for Linux Mint (64-bit). 
Thanks for fixing that so fast!

With my Brave browser ( Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (64-bit))  it doesn't redirect to Netflix login page but ends instead in Incognito mode home page.  After timeout the script exits with "No data received from browser" error. 
"
Opening login webpage... please wait
Please login in to website now ...waiting for you to finish...
No data received from browser
"

Cheers

**Comment by CastagnaIT** [comment]
yeah new versions of Brave browser do not works anymore
i tried investigate but they have do some changes to the remote debugging
and seems they also have forgot to update documentations
so now i have no idea how to fix the connection to Brave browser

if someone know how to do please explain how to do,
meantime i will remove Brave browser support

**Comment by antonioxerez** [comment]
I am sorry but I did not have python installed (the .zip uploaded by @CastagnaIT is a .py file)
I have installed it but now I can't run it because of ModuleNotFoundError
Could you please upload it in .exe?
Thanks!

**Comment by CastagnaIT** [comment]
i upload soon

**Comment by CastagnaIT** [comment]
now you can download from wiki: https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

**Comment by gilbertoferreira** [comment]
> found time, please try with this updated: [NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/10083130/NFAuthenticationKey.zip) and let me know

Works as a charm.
