### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'publickey'

### ISSUE THREAD

**Issue by feliscat** [CastagnaIT/plugin.video.netflix#1511]
### Netflix add-on version

1.20.2+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

If I log in, everything works (can play back video, see lists).  Once I restart Kodi, I can still open the addon and browse, but trying to play back a video results in an error

`AttributeError: 'NoneType' object has no attribute 'publickey'`

### Steps to reproduce the behavior

Install Netflix addon.
Log in.
Restart Kodi
Try to play back video

### Debug log - mandatory

https://paste.kodi.tv/isubavejef.kodi

**Comment by CastagnaIT** [comment]
i tested your steps without having experience of that error,
the error mentioned is so strange that more likely this is a result of another type of previous error which is not visible in the log as it was cut off and has no debug infos, therefore it is impossible for me investigate on what happened,
so i can only suggest you to reinstall from scratch the addon
