### ISSUE TITLE
AMBEO Spatial Audio

### ISSUE THREAD

**Issue by ThreeDeeJay** [CastagnaIT/plugin.video.netflix#1514]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

https://help.netflix.com/en/node/126405
Apparently, Netflix offers a new stereo audio track that is mixed using Sennheiser AMBEO  to "bake-in" spatial audio (similar to Dolby Atmos for Headphones) so we don't need any special hardware or software or even the premium plan to hear 3D sound, just a pair of regular stereo headphones and [select titles](https://www.netflix.com/search?q=Spatial+Audio&suggestionId=Collection%3A81623796).
The problem is that this addon seems to only request/list/use the regular, plain stereo downmix instead of the AMBEO track. Though I should point out that I'm not completely sure they actually rolled out the feature because I haven't gotten it to work on any other device/app I've tried, despite the feature apparently having been out for months.

#### Describe the use case

It basically allows hearing 3D audio on regular headphones (doesn't work that well on stereo speakers though) without a specific subscription/plan, hardware or software (well, I guess other than an app/addon that can play the AMBEO track)

#### Describe an alternative

I can select the Dolby Digital Plus 5.1 Surround track and use virtual surround software like [HeSuVi](https://airtable.com/shrtTsUtiAJQ7wFGI/tblNOTdmp5nHXfFGU/viwjDPuKOjBnIQunv/recBObxaXxVU9SepF) to [hear front and rear speakers using headphones](https://i.imgur.com/BfBPsEz.mp4), but there is no height/verticality (sounds mixed at listener's ear height sound the same as sounds above), unlike AMBEO (or Dolby Atmos, for that matter) which do have height.

### Additional details or screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/71472458/206873122-444c8f04-f3a3-481f-9564-a10891a0cf24.png)

#### Specific details

I'm currently on Windows 11 and a somewhat recent Kodi build (v20)

**Comment by CastagnaIT** [comment]
i have not found audio streams for the spatial audio that can be requested,
there are no such specific distinctions between audio profiles of website

spatial audio usually works from a stereo track,
by reading the linked page, you should disable dolby digital to have it,
so from Expert settings disable "dolby digital plus"
but also they say that is available only on specifics videos
i have no idea, no way to know if it is really available

**Comment by ThreeDeeJay** [comment]
Yeah, I already tried disabling Dolby Digital Plus from the settings, but neither the AAC nor the DD+ stereo track is using spatial audio in Stranger Things Season 4, which is the one that's been advertised having AMBEO since July. 
![image](https://user-images.githubusercontent.com/71472458/206924256-8c0018fb-a5e5-4c83-9919-c29d08fbf8e5.png)
> On select titles, like Season 4 of Stranger Things, Netflix has made AMBEO 2-Channel Spatial Audio the default stream for any two-channel usage. Netflix viewers watching on a stereo system will automatically receive an improved and enhanced spatial experience – no user changes required.
https://en-us.sennheiser.com/newsroom/new-audio-experience-now-streaming-on-netflix

That's why I thought it was up to the client to request it, but I guess AMBEO hasn't really been rolled out yet, despite official documentation, or they just forgor 💀

Anyhow, I think that label's fair so I'll just go ahead and close this issue, and reopen it if I ever notice AMBEO actually working on other devices/clients but not this addon. 👌
