### ISSUE TITLE
Won't play title "Title is unavailable for direct play"

### ISSUE THREAD

**Issue by TriBallscom** [CastagnaIT/plugin.video.netflix#1515]
### Netflix add-on version

1.20.2+matrix1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

When selecting a title to play the pop-up shows "Title is unavailable for direct play, for error check the kodi.log" (translated from the local language)
The title starts playing and you can watch but stops after a view minutes.

It only happens with playing Netflix, other plugins work fine. 

### Steps to reproduce the behavior

1 navigate to title list
2 select title to play
3 that's it

### Debug log - mandatory

https://paste.kodi.tv/gobeqijoha.kodi

**Comment by TriBallscom** [comment]
After I added this issue I found out that re-installing the Widevine CDM library resolved the issue.

**Comment by CastagnaIT** [comment]
yes could happens
