### ISSUE TITLE
Video gets stuck after 2 minutes

### ISSUE THREAD

**Issue by the-isz** [CastagnaIT/plugin.video.netflix#1525]
### Netflix add-on version

v1.18.10+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

- Any netflix video played through the plugin starts playing normally.
- After pretty exactly 2 minutes, video playback gets stuck, audio keeps playing.

### Steps to reproduce the behavior

1. Start any netflix video
2. Let it play for 2 minutes

### Debug log - mandatory

https://paste.kodi.tv/umixihigem.kodi (original upload)
https://paste.kodi.tv/yigifohiza.kodi (new reproduction with debug logging enabled)

### Additional context

Everything used to work before a recent system update.

**Comment by CastagnaIT** [comment]
first thing update addon to last version 1.20.3

after update if problem persist,
provide an uncut log, with debug-enabled, instructions on github main page readme

**Comment by the-isz** [comment]
Hi @CastagnaIT,

thanks for your fast response!

I had the auto-update feature enabled for the addon, but for some reason, it didn't get updated.

The latest version you suggested was available through the user interface, so I manually updated to it and the issue immediately disappeared.

So, again: Thank you very much! Both for your quick support and for providing this great addon :)
