### ISSUE TITLE
explain why Pi cannot hardware decode

### ISSUE THREAD

**Issue by PackElend** [CastagnaIT/plugin.video.netflix#1529]
## Feature request
I'm submitting a proposal to ...
  - [x] change an existing feature

### Describe your request
explain why Pi cannot hardware decode

#### Describe the use case
fewer question marks in my mind :)

#### Describe an alternative
copy or reference https://forum.kodi.tv/showthread.php?tid=367263

**Comment by CastagnaIT** [comment]
because DRM Widevine library dont provide hardware video decoding for linux devices
