### ISSUE TITLE
TypeError: Cursor() argument 1 must be sqlite3.Connection, not sqlite3.Connection

### ISSUE THREAD

**Issue by TyrionWarMage** [CastagnaIT/plugin.video.netflix#1530]
### Netflix add-on version

1.20.3+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Netflix addon kann not be started with error: TypeError: Cursor() argument 1 must be sqlite3.Connection, not sqlite3.Connection. 

OS is Ubuntu 22.04 with Python 3.10.6

### Steps to reproduce the behavior

1. Install Plugin
2. Restart Kodi
3. Open Netflix video-addon

### Debug log - mandatory

https://paste.kodi.tv/lagowagiqi.kodi

### Additional context

- Identical with #1503 
  - Have included a debug log
  - I also use an AEON skin (https://forum.kodi.tv/showthread.php?tid=358382), but the error also occures with stock skin (AEON addons still installed)
  - Disabling the AEON widget did not fix it
- Reinstalling the addon or rebooting the system (not kodi) fixes the issue
  - Possibly temporarily, some indeterminisms happen here (Had the message occure without kodi restart, but addon seemed to still work)
  - Restarting kodi (graceful) triggers the bug
- Seems reproducible (at least today it was over several trials)  

Edit: Seems not to be Netflix Addon specific: https://github.com/trakt/script.trakt/issues/586

**Comment by CastagnaIT** [comment]
i already tried investigate in the previous closed issue
and found any way to fix it
my initials suspects was of a python library regression like seems to be by reading the discussion on https://github.com/trakt/script.trakt/issues/586

i read that on last python v3.11.1 release there are more sqlite fixes seems also around this connection problem,
so you should try update your installed python library to v3.11.1 and make it the default

**Comment by TyrionWarMage** [comment]
> i already tried investigate in the previous closed issue and found any way to fix it my initials suspects was of a python library regression like seems to be by reading the discussion on [trakt/script.trakt#586](https://github.com/trakt/script.trakt/issues/586)
> 
> i read that on last python v3.11.1 release there are more sqlite fixes seems also around this connection problem, so you should try update your installed python library to v3.11.1 and make it the default

Replacing the default python3 version on an Ubuntu OS breaks apt-get as well as the gnome-terminal, but i did run some tests with 3.11.1 and 3.9. Both do not resolve the issue. Futhermore, running the flatpak version with copied settings/addons has the same problem. It seems like an compatibility issue with another addon, because running a "fresh" kodi with only netflix is not subject to the problem. I will update in case i can find the culprit.

**Comment by TyrionWarMage** [comment]
As also mentioned by #1503, there is some relation to the "Netflix: Continue Watching" widget. Disabling it fixes the problem in my minimal-trial-setup (but not in my full setup). I also observed a behaviour change in contrast to older plugin versions: The plugin connected on Kodi startup, now it seems to be triggered by opening the plugin? This may be related, because the widget does not trigger Netflix connect - The widget will show nothing until the plugin was opened once. May it be, that the widget uses some unconventional means to access the netflix data, that does not trigger some relevant functions? (Even if the widget shows something, using it usually results in strange problems and messages)

**Comment by CastagnaIT** [comment]
> It seems like an compatibility issue with another addon

each addon live on a separate enviroment cannot be in conflict

> I also observed a behaviour change in contrast to older plugin versions: The plugin connected on Kodi startup, now it seems to be triggered by opening the plugin?

services are always loaded automatically at startup without user iteraction, just removed the annoying message
if services are not loaded you will see an explicit error message

Widgets are not supported on this addon and i dont provide support for them
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits

> The widget will show nothing until the plugin was opened once

This sound weird, but it is possible you do not wait long enough for the service to be fully loaded,
until the service is fully loaded, nothing will be shown.
I will try test a widget on next days just to check a kind of possible regression on addon opening code
although there should be no change

**Comment by CastagnaIT** [comment]
found a bit of time, and tested with same software configuration
kodi 19.4 on Ubuntu 22.04.1 LTS with python 3.10.6

by using skin "Aeon Nox: Silvo" (official)
add a widget that point to "Continue watching" folder of addon
addon works as expected without errors
the widget if loaded/filled of data after about 10 seconds after that kodi is running, without the need to open the addon
and widget is kept after kodi restart
so this confirm that there is no problems on addon opening code

i tried install Aeon MQ 8 Matrix Mod, but for me its too confusing skin... not intuitive
lost 15 minutes just to add a widget that disappeared after restarting kodi for unknown reasons, i never try this skin again.

however skins has no relation with this error
and i have no idea how to replicate locally this error

**Comment by TyrionWarMage** [comment]
Thanks very much for the support, especially considering widgets are explicitly excluded. But it seems like it is time to admin, this specific skin is simply broken. (upon closer inspection, i found it depends on some very outdated and beta addons ...)

For everyone having the same problem: Aeon MQ 8 Matrix Mod Skin seems broken and will not fully work with this Addon.

**Comment by guneysus** [comment]
First of all, I have similar issue and willing to help this issue by replicating and providing logs if I am assisted.


I found a workaround for this.

- When I disable and enable the addon
- Or downgrade and upgrade the current version it works, until I restart Kodi.

| Info | Value |
| - | - |
| **Netflix add-on version** | 1.22.3+matrix.1 |
| **OS** | Linux Mint 21.2 |
| **Kodi version** | Kodi Media Center 21.0-ALPHA1 (20.90.101) Git:20230401-847a347839 |
| **Python version on my system:**| Python 3.10.12 |


I have other addons. Read the comments and will try some possible suspected addons.

Not sure when it introduced (Have a hunch it started when I upgraded some packages on my system)

Thanks,
