### ISSUE TITLE
SQLite3 : database is locked

### ISSUE THREAD

**Issue by Whenrow** [CastagnaIT/plugin.video.netflix#1533]
### Netflix add-on version

1.20.3+matrix.1

### Operative systems used

OSMC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I have an issue with the SQLite3 database at the startup of the addons. I get the `database is locked` message when the DB is initialized.  This issue (I guess) produces another error if I try to relaunch the addon ` AttributeError: 'GlobalVariables' object has no attribute 'LOCAL_DB' in the `check_credential` method.
Check the linked traceback to have more details.

Thanks 

### Steps to reproduce the behavior

Launch the add-on the 1st time, you will get the 
`resources.lib.common.exceptions.DBSQLiteConnectionError` -> `database is locked`

Launch the add-on after this issue you will alwaus get the 
` AttributeError: 'GlobalVariables' object has no attribute 'LOCAL_DB'`

### Debug log - mandatory

https://paste.kodi.tv/dexipuyafa.kodi

**Comment by CastagnaIT** [comment]
please attach a full _debug_ log not cut, instructions are in the main page Readme
you may need additionals steps to exract it from OSMC so refer to OSMC wiki

**Comment by Whenrow** [comment]
> please attach a full _debug_ log not cut, instructions are in the main page Readme you may need additionals steps to exract it from OSMC so refer to OSMC wiki

I udpdated the debug log link. Hope it's complete

**Comment by CastagnaIT** [comment]
no its always cut and without debug enabled

**Comment by Whenrow** [comment]
Enabling the global kodi debug logging make the addons working fine for no reason
