### ISSUE TITLE
Raspberry Pi 4 Support

### ISSUE THREAD

**Issue by tiagoboldt** [CastagnaIT/plugin.video.netflix#154]
*I'm submitting a ...*
  - [x] support request

The documentation states that raspberry pi decoding is capped at 720p due to hardware limitations. The latest rpi4 has H.265 4K decode in hardware available. would that improve performance? If so, should the documentation be updated accordingly?

**Comment by Smeulf** [comment]
Hi.

Even if the Raspberry Pi 4 is more powerful than a Pi3, the decoding process is still software.

That means there's a large probably it won't decode 4k.

For 1080p and H265, as I didn't test yet, I can't confirm, just say 'maybe'... From what I could read, some people were a bit frustrated with the performances on Netflix, bit once again I can't confirm.

If you plan to by one, I would advise to wait: there's currently some issues with processor heat, and with the USB type C ports. For the heat, it seems a firmware update fixes the problem. But for the USB one, only a hardware rev2 will fix it, it's planned but I don't know the date.

Plus for Netflix, I'd buy a case with fan, as I did for the Pi3 ^^

If someone did test, would you please share your experience? Thanks.

**Comment by dagwieers** [comment]
I don't have a Premium account, but I can confirm that 1080p playback works fine on a Raspberry Pi 4 using LibreELEC v9.1.0002 ALPHA. This is indeed decoding in software.

Hardware decoding is possible for content flagged `SW_SECURE_CRYPTO`, however Netflix content is flagged `SW_SECURE_DECODE` which requires decoding in software.

See also: https://github.com/asciidisco/plugin.video.netflix/issues/422
