### ISSUE TITLE
No event data received from browser

### ISSUE THREAD

**Issue by mr-ominous** [CastagnaIT/plugin.video.netflix#1549]
### Netflix add-on version

2.0.0

### Operative systems used

Raspbian

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

When I try to run the python script so I can get my authentication key I get the error "No event data received from browser"

{
Browser startup... (/usr/bin/chromium-browser) please wait
Establish connection with the browser... please wait
Opening login webpage... please wait
Please login in to website now ...waiting for you to finish...
No event data received from browser

}

### Steps to reproduce the behavior

1. run the script
2. login on window popup
3. browser exits
4. error shows in terminal and no file is produced

### Debug log - mandatory

N/A

### Possible fix

N/A

**Comment by CastagnaIT** [comment]
what version of chromium browser?
make sure you are using last script version 1.1.5

**Comment by podfinkx** [comment]
Same issue here, tried with Chromium 109.0.5414.119 built on Debian 11.6, running on Debian 11.6 also lastest version of google-chrome, no luck

**Comment by CastagnaIT** [comment]
i tested with Debian 11 in this way:
- Installed chromium from store (now its 110.0...)
- installed pip requirements as explained in to wiki
- run the script

but to me works good and the key file is generated
im not able reproduce your problem

**Comment by jakermx** [comment]
I guess  you aren not executing the key grabing script,  some devices gets the key from a current session on other device in the same network if so.... make sure that you run the script and the browser fro the same user, to be sure...open 2 terminal consoles and  call your browser and then run the script in parallel...or just run the script as your user.. no su , sudo, etc....no incognito or private windows and accept all cookies....

I used email/password...usually it fails the first time and the next time....it works, its a Geo Localization DNS issue, but once the systems know the endpong ip, the  next call doesnt  need to be redirected and it goes great!

hope it helps

**Comment by oneohthree** [comment]
Sorry to be late here. I had the same problem as the OP. I have a really poor internet connection so I changed  lines 184 and 195 with: `if time.time() - start_time > 100:` I simply increased the time a little more.

**Comment by frankt66** [comment]
oneoh three: Thank you for that. I tried with the changes in lines 184 and 195 - it worked! i got the key.

**Comment by krissen** [comment]
@oneohthree Worked for me as well, thanks.

macOS, current version of Chrome (stable).
