### ISSUE TITLE
Fallback for android

### ISSUE THREAD

**Issue by wintuxx** [CastagnaIT/plugin.video.netflix#155]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

I have seen the amazon prime video addon has a fallback option for android. Is it possible to intergrat this option in this addon?

**Comment by Smeulf** [comment]
Can you describe? I don't use Amazon addon.

**Comment by wintuxx** [comment]
sure, i hope you understand my english ;)

in the options of the amazon addon you can choose a playoption Browser, Script/Batch, Android, Input Stream

as an alternative to inputstream for the Android devices for the shield user (me included)

see here:
https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon/resources/settings.xml

here the play.py  rows 126 to 149 (i think this is call the android option)  

I hope you understand what I mean

**Comment by Smeulf** [comment]
I got you. Start the Netflix app to play the video as an external player.

Don't know yet if it's possible with Netflix, must be verified.

**Comment by CastagnaIT** [comment]
is it really necessary? I can't find it very simple
I see the thing of doubtful utility
describe some usage examples

**Comment by wintuxx** [comment]
> is it really necessary? I can't find it very simple
> I see the thing of doubtful utility
> describe some usage examples

I think so. At the moment it looks like that  inputstream with the Netflix addon did not work on Android pie. Perhaps as backup fallback.

Sorry about my bad english 😑

**Comment by Smeulf** [comment]
My question may sound idiot, but... What's the advantage of Kodi + Netflix add-on on a shield v.s. the Netflix official app ?

**Comment by wintuxx** [comment]
Because Kodi is a one in all solution.   
The question could also be, why should you use Kodi at all?
You can also use the official Youtube app, VLC for local Videos, the apps from the networks and so on.
I think the most advantage is the library  of Kodi and the sync addon of trakt.

**Comment by C-O-D** [comment]
Chromecast as an external player option (e.g. for the files that not play in 1080p) would also be VERY nice...

**Comment by Smeulf** [comment]
> Chromecast as an external player option

There's no Chromecast support in Kodi, so that just won't be possible.

**Comment by wintuxx** [comment]
What about tubecast?

gesendet mobil

Smeulf <notifications@github.com> schrieb am Di., 20. Aug. 2019, 20:08:

**Comment by wintuxx** [comment]
Okay it is only for the YouTube app

**Comment by xnappo** [comment]
This would be great if it is possible.  I like using Kodi to track what I have watched and see across platforms, but honest prefer the Netflix player for video quality.

**Comment by CastagnaIT** [comment]
after almost a year no one is interested to integrate this
then Issue is closed
can be reopened in case of evolutions
