### ISSUE TITLE
Argument "name" for method "Actor" must be unicode or str

### ISSUE THREAD

**Issue by b-jesch** [CastagnaIT/plugin.video.netflix#1554]
### Netflix add-on version

1.20.6+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

> 2023-02-12 12:21:45.122 T:8294    error <general>: [plugin.video.netflix (14)] Traceback (most recent call last):
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
>                                                        func(*args, **kwargs)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 265, in run
>                                                        success = route(pathitems)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 90, in lazy_login_wrapper
>                                                        return func(*args, **kwargs)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 130, in route
>                                                        _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 159, in _execute
>                                                        executor(pathitems=pathitems)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
>                                                        return func(*args, **kwargs)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 28, in set_custom_viewmode
>                                                        override_content_type = func(*args, **kwargs)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 164, in video_list
>                                                        dir_items, extra_data = common.make_call('get_video_list', call_args)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
>                                                        return func(*args, **kwargs)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 94, in make_call
>                                                        return make_http_call(endpoint, func_name, data)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 115, in make_http_call
>                                                        _data = pickle.loads(received_data)
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/common/kodi_wrappers.py", line 71, in __setstate__
>                                                        video_info.setCast([xbmc.Actor(name) for name in cast_names])
>                                                      File "/home/jesch/.kodi/addons/plugin.video.netflix/resources/lib/common/kodi_wrappers.py", line 71, in <listcomp>
>                                                        video_info.setCast([xbmc.Actor(name) for name in cast_names])
>                                                    TypeError: argument "name" for method "Actor" must be unicode or str

### Steps to reproduce the behavior

If you choose some items from main list this bug appears on different menu items.

### Debug log - mandatory

https://paste.kodi.tv/ruyimejibu.kodi

**Comment by jakermx** [comment]
Setup a default profile, it is happening cus your skin or theme is requesting something about a title without being fully logged in...  I resolved it installing all the visual and operational plugins first...and at the end, the content sources,  NOT THE CONTENT PROVIDERS

**Comment by CastagnaIT** [comment]
@jakermx dont comment an Issue if you dont know what are the real reasons behind a problem

this was a website problem solved a few days ago

**Comment by jakermx** [comment]
oooook Sir...

I just shared how I resolved it... " I resolved it installing all the visual and operational plugins first...and at the end, the content sources, NOT THE CONTENT PROVIDERS"

If you read the log, you will notice what Im saying is happening..

**Comment by CastagnaIT** [comment]
suggest you to learn a bit of basic english language structure because your sentences that you are writing are incomprensible...google translator can also help you

**Comment by jakermx** [comment]
I wrote it as I learned when I went to the USA for work .... and I just
confirmed the google translator suggested to me exactly the same I
wrote....BTW, you missed to use the right  sentence structure, you missed
the "I" at the beginning of your reply...JK...if you mistyped or did a typo
, or your translator change something....I figure it out...first before
complaining, Anyway... I will be be muted some more months

Bytes! ---- As an IT Engineer I say Bytes instead of Bye.... I'm not that
strict ortodox

**Comment by CastagnaIT** [comment]
then good luck
