### ISSUE TITLE
Unable to read video

### ISSUE THREAD

**Issue by mplu** [CastagnaIT/plugin.video.netflix#1555]
Installation and connections were OK, or I think so. i have a doubt on a big google chrome related stuff, that took long to install. How Can i check if the whole installation went properly ? 
But when i try to open a video, i got two quick loading screen, and nothing happen.
I got a fresh 720p netflix account, could this be an issue ? As every video is written as available in 1080p at the bottom of thé screen.

I use kodi 18 on a raspberrypi 3 running retropie.

**Comment by CastagnaIT** [comment]
sorry but Kodi 18 is deprecated, no support will be provided
go ahead with Kodi 19 or 20
