### ISSUE TITLE
In kodi 20 Video has audio stutters and takes a long time to start, downgrade to 19 solves the issue

### ISSUE THREAD

**Issue by RobVerduijn** [CastagnaIT/plugin.video.netflix#1556]
### Netflix add-on version

1.20.6+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hi,

I'm running kodi using the flatpak version on fedora kinoite.
When kodi was upgraded to 20 bij flatpak the netflix videos started to give issues
- long time to start
- audio stutter
downgrading to the last kodi 19 flatpak version solved the problem
For those who wonder which version:
```bash
flatpak update --commit=e15d861c08f40a370b16efe0a999b59f85727032077f6c4bdc7102336387154d tv.kodi.Kodi
```

there are also a lot of the following errors in the logs:
 error <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
and even more warnings:
warning <general>: ActiveAE - large audio sync error: -25496.991293

The workaround is to  downgrading the kodi version back to 19.1
Everything works smoothly again after that.

Rob 

### Steps to reproduce the behavior

install fedora kinoite on a nuc
install flatpak kodi
install netflix plugin from castagnait
try to view any movie (will work but the audio will be very annoying)

downgrade to kodi 19.1
 ```bash
flatpak update --commit=e15d861c08f40a370b16efe0a999b59f85727032077f6c4bdc7102336387154d tv.kodi.Kodi
```

everything will work fine again

### Debug log - mandatory

https://paste.kodi.tv/opulirizaz.kodi

### Possible fix

downgrade to kodi 19.1 as a workaround

**Comment by CastagnaIT** [comment]
this is not an addon problem:

```
2023-02-19 19:47:41.551 T:17      error <general>: ActiveAE::InitSink - failed to init
2023-02-19 19:47:41.551 T:17    warning <general>: CActiveAE::StateMachine - signal: 11 from port: OutputControlPort not handled for state: 2
2023-02-19 19:47:41.551 T:17    warning <general>: CActiveAE::StateMachine - signal: 12 from port: OutputControlPort not handled for state: 2
```

you have to ask to kodi community
