### ISSUE TITLE
NFAuthenticationKey Software isn't working

### ISSUE THREAD

**Issue by KneesDev** [CastagnaIT/plugin.video.netflix#1561]
Hey there,
That software for the Authentication Key login method isn't opening on Windows.

![image](https://user-images.githubusercontent.com/74821251/223120689-cfe2a49c-be18-4dbe-a8aa-6092209b32f3.png)

**Comment by CastagnaIT** [comment]
ii cannot reproduce the problem so i have no idea what problem on your computer
however this software requires the .NET 3.8 framework maybe your .NET library is broken/missing
