### ISSUE TITLE
TypeError: sequence item 0: expected str instance, dict found

### ISSUE THREAD

**Issue by lekma** [CastagnaIT/plugin.video.netflix#1563]
### Netflix add-on version

1.20.8

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Error when using the addon

### Steps to reproduce the behavior

Navigate to My List

### Debug log - mandatory

https://paste.kodi.tv/cupivagubi.kodi

**Comment by tsioukas** [comment]
If you added to your list this show "Chris Rock: Selective Outrage" (https://www.netflix.com/browse?jbv=80167499), remove it and it will be fixed. Otherwise remove one by one you latest additions (maybe there are other shows with the same problem)

For some reason this show marked as "live" and even if you try to played from Continuue Watching it will produce an error also.

**Comment by u2020bullet** [comment]
> If you added to your list this show "Chris Rock: Selective Outrage" (https://www.netflix.com/browse?jbv=80167499), remove it and it will be fixed. Otherwise remove one by one you latest additions (maybe there are other shows with the same problem)
> 
> For some reason this show marked as "live" and even if you try to played from Continuue Watching it will produce an error also.

Can confirm this works. Thank you.

**Comment by tsioukas** [comment]
Nice, maybe  @CastagnaIT, can manage it somehow to ignore this type of TV Show to avoid crashes.

**Comment by lekma** [comment]
@tsioukas: you were absolutely correct, thanks for the pointer

**Comment by bierbaron2** [comment]
I receive the same error **sequence item 0: expected str instance, dict found**, but I can't open New on Netflix, Recently added or the search function (see https://forum.kodi.tv/showthread.php?tid=329767&pid=3145147#pid3145147 for log)

**Comment by CastagnaIT** [comment]
confirm there is an internal website server bug that crashes when retriving some metadata
