### ISSUE TITLE
64-bit ARM Widevine CDM

### ISSUE THREAD

**Issue by totoCZ** [CastagnaIT/plugin.video.netflix#1564]
https://forums.raspberrypi.com/viewtopic.php?t=347736

There is now a 64-bit widevine CDM for ARM and it works on the 64-bit Chromium browser in Raspberry Pi OS.
What can be done to make it work with this plugin?

toto@keyboard:~$ file /opt/WidevineCdm/_platform_specific/linux_arm64/libwidevinecdm.so
/opt/WidevineCdm/_platform_specific/linux_arm64/libwidevinecdm.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b71fd3342a03fdb140e1f7a757960df219d63625, stripped

**Comment by CastagnaIT** [comment]
adding that support has nothing to do with this addon

Kodi team is already working to add widevine arm64 support to their ISAdaptive addon
will be available for Kodi 20 and next 21

**Comment by Basfoppele** [comment]
> https://forums.raspberrypi.com/viewtopic.php?t=347736
> 
> There is now a 64-bit widevine CDM for ARM and it works on the 64-bit Chromium browser in Raspberry Pi OS. What can be done to make it work with this plugin?
> 
> toto@keyboard:~$ file /opt/WidevineCdm/_platform_specific/linux_arm64/libwidevinecdm.so /opt/WidevineCdm/_platform_specific/linux_arm64/libwidevinecdm.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b71fd3342a03fdb140e1f7a757960df219d63625, stripped

if you take/copy manifest.json and libwidevinecdm.so from rasp os x64 /opt/WidevineCdm folder and you paste into the cdm folder in .kodi you have a working widevine! works even great on ubuntu x64 for raspberry
