### ISSUE TITLE
NFAuthenticationKey: A problem prevented the opening of the websocket

### ISSUE THREAD

**Issue by MolotThora** [CastagnaIT/plugin.video.netflix#1565]
### Netflix add-on version

last

### Operative systems used

Windows

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

What could be the problem? A couple of days ago, it turned out to create a key the first time. I'm trying to repeat from 2 devices, such an error.

### Debug log - mandatory

https://paste.kodi.tv/okuqigicop

**Comment by alanmilinovic** [comment]
I can confirm same.

**Comment by Jositoleyre** [comment]
Como solucionarlo??

**Comment by Air-w0lf** [comment]
I have the same issue just now.

**Comment by CastagnaIT** [comment]
there is a new security fix on last Chrome version that prevent a direct connect
i will fix soon

**Comment by Air-w0lf** [comment]
> there is a new security fix on last Chrome version that prevent a direct connect i will fix soon

Thanks - I was just about to suggest that the issue might have been a new Chrome update!

**Comment by CastagnaIT** [comment]
fixed download new version from wiki page

**Comment by CastagnaIT** [comment]
not updated? i will check
