### ISSUE TITLE
Vertical Shift value is not correctly loaded when resuming a video

### ISSUE THREAD

**Issue by Badsheep** [CastagnaIT/plugin.video.netflix#1568]
### Netflix add-on version

1.20.2+matrix 1

### Operative systems used

Mac OSX

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When you set a vertical shift for a video, it isn't loaded when you resume that video.
But the value exist, if you change it, the image "jumps" to the stored vertical shit value plus the change you just made.
So the value is correctly stored, it' just that it's not loaded when the video starts.

### Steps to reproduce the behavior

It's what I did in the joined log file :

starts a movie
change the vertical shift (remember the value in your head...)
stops the movie
restart the movie : the image is placed at the default value (vertical shift = 1)
change the vertical shift (I do it with a keystroke) : the image jumps to the vertical shift saved (the value you remember) plus the change you just made.

### Debug log - mandatory

https://paste.kodi.tv/yutirikera.kodi

### Additional context

This bug wasn't happening in Kodi 19.

**Comment by CastagnaIT** [comment]
netflix videos are not cropped have embedded black bands
so the vertical shift cannot works

**Comment by Badsheep** [comment]
Hello !

I'm not sure to understand your answer : in my Kodi, the vertical shift works nice, for all videos (with or without black bars).
It's just when you resume a video...
Did you try to reproduce the issue ?

**Comment by CastagnaIT** [comment]
its not now thing to me, with kodi 19/20/21 vertical shift to me works for cropped videos only,
i have always seen this behaviour at least on Windows, i dont have macos, if not the same maybe there is a kodi bug,
from my part i cannot say if there is a problem on kodi or not,
but for sure this cannot be fixed by this addon

**Comment by CastagnaIT** [comment]
try check if you have enabled "force reset view mode" in addon playback settings
maybe could influence this

**Comment by Badsheep** [comment]
Hi, yes when I set it to "No", it works !
I don't remember having enabled it, maybe it the case ? Anyway thanks for your help, it's working.

And I did some tests, on my "Mac OS Kodi" vertical shift is working with all the videos (included the one non-cropped).

**Comment by CastagnaIT** [comment]
i found that was enabled by default i dont remember anymore why, now i changed to disabled by default
i dont know why but on Windows vertical shift dont works as you described for macos, so probably a bug i will try ask to kodi team
