### ISSUE TITLE
App stuck at max 720p (after correct config)

### ISSUE THREAD

**Issue by GemeenAapje** [CastagnaIT/plugin.video.netflix#157]
*I'm submitting a ...*
  - [X ] support request

## General infomration
App stuck at max 720p

### Prerequisites

* [X ] Are you running the latest version?

### Description
Hi guys

Please can someone help me?

I cannot get Netflix via Koda plugin to run at more than 720p even though in the main Netflix app I can get normal 4k.

I really want 4k + Atmos. Via the Kodi App plugin I can get Atmos working fine but only max 720p. Via Netflix app I can't get Atmos via Shield.

I've configured the settings as advised but that doesn't help (also tried playing around with the settings but nothing helps).

When I manually select from the streams, there are 4 listed and the max is 720

It also has to be manually zoomed otherwise I have a black border all around the screen (above/below and sides).

Versions:
Nvidia Shield 8.0.0
Kodi 18.3
InputStream Adaptive 2.3.22
Netflix 0.14.6

Internet: 500mb/s glass fibre

Plugin Settings:
VP9: DIsabled
HEVC: Enabled
HDR Profiles: Enabled
Force HDCP 2.2: Enabled
ESN: Automatic (tried manual without success)

InputStream settings:
Min bandwidth 8,000,000
Max bandwidth: Tried everything from 0 to 99,999,999
Resolutions: Both max
Stream selection: Manual
Override HDCP: Enabled
Ignore display resolution: Enabled

Any help really appreciated.

Thanks
Matt

## Context (Environment)
Nvidia Shield

### Installation
* [X ] I installed the plugin via zip from the Releases page

### Operating System
* [X ] Android (Nvidia Shield latest firmware)

**Comment by Smeulf** [comment]
NVidia shield 8.0.0 currently suffers a large bug: https://github.com/CastagnaIT/plugin.video.netflix/issues/152

I do think it's very related...

**Comment by GemeenAapje** [comment]
> NVidia shield 8.0.0 currently suffers a large bug: #152
> 
> I do think it's very related...

Thanks. I think you're right. Sorry I didn't see that earlier.  I don't know much about codecs and I only have the Shield remote so don't think I can help much more than posting my settings above.  But if I can do anything to help please let me know.

Thanks
Matt

**Comment by CastagnaIT** [comment]
Ignore display resolution better "disabled"
so for news refer to the other "issue" post
