### ISSUE TITLE
TypeError: Cursor() argument 1 must be sqlite3.Connection, not sqlite3.Connection

### ISSUE THREAD

**Issue by staeglis** [CastagnaIT/plugin.video.netflix#1571]
### Netflix add-on version

1.21.0

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Addon crashes on Ubuntu 22.04 (Python 3.10) when opening it

### Steps to reproduce the behavior

Open the Netflix addon

### Debug log - mandatory

https://paste.kodi.tv/wasatimiba

**Comment by staeglis** [comment]
Sorry I haven't seen that there is already an issue for kodi 19
https://github.com/CastagnaIT/plugin.video.netflix/issues/1530

**Comment by CastagnaIT** [comment]
i dont have solutions for this problem

**Comment by guneysus** [comment]
Hi, sorry for duplicating my messages into here (from https://github.com/CastagnaIT/plugin.video.netflix/issues/1530#issuecomment-1826750016)


---

First of all, I have similar issue and willing to help this issue by replicating and providing logs if I am assisted.


I found a workaround for this.

- When I disable and enable the addon
- Or downgrade and upgrade the current version 

The bug disappers, addon starts working, until I restart Kodi.

| Info | Value |
| - | - |
| **Netflix add-on version** | 1.22.3+matrix.1 |
| **OS** | Linux Mint 21.2 |
| **Kodi version** | Kodi Media Center 21.0-ALPHA1 (20.90.101) Git:20230401-847a347839 |
| **Python version on my system:**| Python 3.10.12 |


I have other addons. Read the comments and will try some possible suspected addons.

Not sure when it introduced (Have a hunch it started when I upgraded some packages on my system)

Thanks,
