### ISSUE TITLE
KeyError: lists, summary when integrating it as Widget

### ISSUE THREAD

**Issue by vitorgrs** [CastagnaIT/plugin.video.netflix#158]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information

The add-on is working great here, but if I try to integrate it as a widget on Aura or Titans Bingie, I keep getting these errors 

![you can see here](https://i.imgur.com/RU3elEs.png)

### Addon version used

[14.6]

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Kodi 18.3. It happens using Titans Bingie, Aura... 

## Other information

This is random. It happens with some widgets and sometimes it doesn't.

**Comment by Smeulf** [comment]
Does it appears at startup? If so, it might be because the widget starts before the service.

Then, there's not much to do...

**Comment by CastagnaIT** [comment]
the widgets are not managed by addons change skin,
some users have found a workaround that doesn't always seem to work, is explained in the Kodi forum, but i don't remember where

**Comment by vitorgrs** [comment]
The thing is, this just happens with this add-on. I have plenty of others, and it works fine.

**Comment by Smeulf** [comment]
For the record, the 'KeyError: List' is an error I already saw on my own setup, without relationship with any widget.

However, with the lasts daily builds, I didn't see it since a while... You still can try.

If you encounter the error again, please provide logs, even normal logs.

**Comment by vitorgrs** [comment]
Will try the latest daily. Also, I don't want to create another issue, so I will ask here. Netflix Kodi HEVC's doesn't work on Windows? When I enable, it just loads....

And if it doesn't work, will AV1 experimental work?

**Comment by vitorgrs** [comment]
Hi there. Here is the debug log. https://paste.kodi.tv/kadusosipi.kodi

**Comment by CastagnaIT** [comment]
VP9 quality is equivalent of HEVC, the difference is that VP9 is royalty-free
despite this, netflix creates streams with different qualities, based on the codec, and the type of video tvshow/movie, oldest and newest, and makes it available also according to the device, app, type of browser etc...

so,
HEVC to now works on android and maybe mac
AV1 is still being implemented by netflix

I reopen to investigate this last error

**Comment by CastagnaIT** [comment]
so in the last log missing debug infos are disabled

**Comment by Smeulf** [comment]
If it's the one I think, it's so random it's pretty hard to catch it in debug :(

**Comment by vitorgrs** [comment]
It's too big to send on Kodi paste lol here it is https://gist.github.com/vitorgrs/7d927b030921abd2be576b1238965246

**Comment by CastagnaIT** [comment]
in practice seem but i am not sure, it goes into error because i didn't put a verify that checks if the data in self.data are missing as done in VideoListSorted

**Comment by CastagnaIT** [comment]
Try this test
install over the existing one addon
[plugin.video.netflix_TEST1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3501348/plugin.video.netflix_TEST1.zip)

**Comment by Smeulf** [comment]
I've got a SQLite error. Looks like it doesn't even try to connect to MySQL (MariaDB).

I tried to rename the old 'nf_shared.sqlite3' to 'nf_shared.sqlite3.bak' too, no change.

https://paste.kodi.tv/uqelifovid.kodi

**Comment by vitorgrs** [comment]
Ok, I tried with the new version. It doesn't show show any errors (like in the screenshot that I sent), but is not working properly.
It's showing just some widgets, random. https://imgur.com/a/slaxAdy
If I restart "restart" the skin  or reboot kodi, it shows 3 widgets, other times, 2, etc.  

I have 5 categories. https://imgur.com/a/RRiw0Kz

**Comment by CastagnaIT** [comment]
> I've got a SQLite error. Looks like it doesn't even try to connect to MySQL (MariaDB).
> 
> I tried to rename the old 'nf_shared.sqlite3' to 'nf_shared.sqlite3.bak' too, no change.
> 
> https://paste.kodi.tv/uqelifovid.kodi

you are using WIP this is not WIP

**Comment by CastagnaIT** [comment]
> Ok, I tried with the new version. It doesn't show show any errors (like in the screenshot that I sent), but is not working properly.
> It's showing just some widgets, random. https://imgur.com/a/slaxAdy
> If I restart "restart" the skin or reboot kodi, it shows 3 widgets, other times, 2, etc.
> 
> I have 5 categories. https://imgur.com/a/RRiw0Kz

why didn't you post a new log?

**Comment by Smeulf** [comment]
@CastagnaIT

> > I've got a SQLite error. 
> you are using WIP this is not WIP

No it's my bad, I posted the comment on the wrong thread then deleted it. Please forgive me and forget about it!

**Comment by vitorgrs** [comment]
> > Ok, I tried with the new version. It doesn't show show any errors (like in the screenshot that I sent), but is not working properly.
> > It's showing just some widgets, random. https://imgur.com/a/slaxAdy
> > If I restart "restart" the skin or reboot kodi, it shows 3 widgets, other times, 2, etc.
> > I have 5 categories. https://imgur.com/a/RRiw0Kz
> 
> why didn't you post a new log?

Sorry, forgot! https://gist.github.com/vitorgrs/1defcfc6997e381808448c2cc338d2a9

**Comment by CastagnaIT** [comment]
so i see nothing in particular in the log...
try to delete all category widgets
and recreate them

**Comment by vitorgrs** [comment]
No luck. Also tried on Titans Bingie, same problem. This problem doesn't happen to you? You couldn't repro?

**Comment by CastagnaIT** [comment]
this is an old problem of the widgets, already discussed also in the forum
in the past i asked for someone to request help from a skin developer but no reply,
i have no solutions
