### ISSUE TITLE
Cant enable AV1 codec

### ISSUE THREAD

**Issue by Yankees4life** [CastagnaIT/plugin.video.netflix#1581]
### Netflix add-on version

Version 1.21.0+matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

I can't enable the AV1 codec on the latest version of the addon. It's not even there
![20230408_164549](https://user-images.githubusercontent.com/39246923/230741998-0660c02a-c8f9-495d-bf2f-7c9881cca365.jpg)

### Debug log - mandatory

Null

**Comment by CastagnaIT** [comment]
Kodi 20 cannot support DRM AV1
so to get AV1 you need Kodi 21

**Comment by Yankees4life** [comment]
> Kodi 20 cannot support DRM AV1 so to get AV1 you need Kodi 21

Yikes. I don't to break my add-ons in half so I'll just until kodi 21 becomes stable. I guess I'm keeping my Netflix app up and running ATM 🤣😂
