### ISSUE TITLE
Netflix can't play 1080P video on Android 11 And my device supports VP9 and HEVC decoding

### ISSUE THREAD

**Issue by yanik2333** [CastagnaIT/plugin.video.netflix#1584]
### Netflix add-on version

1.22.0

### Operative systems used

Android

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

I can't play 4K video or even **1080P** video in my **Kodi 21** Omega version, and it's limited to **960P** video streams, I reset my **ESP code** and logged back in, the problem still exists, then **I lowered my Kodi version to 20 and 19**, the problem still exists, I can't understand what the problem is, maybe it's an internal architecture problem of the plugin, maybe a dependency library has a compatibility error or can't be called, etc. **_I hope I can get a reply soon to solve this problem, thanks for looking at the technical staff!_**

### Debug log - mandatory

I don't have a journal, and I can't find one

**Comment by CastagnaIT** [comment]
as first specified above Kodi 18 but no more support are provided for that old version

anyway i dont see any debug log attached, so i cannot give you no advices,
follow github Readme instructions to provide debug log and attach it here
