### ISSUE TITLE
Error unable to find falcorCache data.

### ISSUE THREAD

**Issue by Axachi** [CastagnaIT/plugin.video.netflix#1595]
### Netflix add-on version

1.22.0+matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

I get this when running NF Authentication key exe on windows 11, using latest chrome??

Any fix... for this?

### Debug log - mandatory

http://paste.kodi.tv/

**Comment by Axachi** [comment]
this worked. on previous build. but after uppgrade kodi on Android it asks for re-auth.

**Comment by CastagnaIT** [comment]
im not able to reproduce
ensure that you are using last NF Authentication version
