### ISSUE TITLE
"Due to a MSL error you cannot playback videos with this device" after latest update to 1.22.1

### ISSUE THREAD

**Issue by helour** [CastagnaIT/plugin.video.netflix#1597]
### Netflix add-on version

1.22.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hi,

I can't play any Netflix content after the last update. I get an error message: Due to a MSL error you cannot playback videos with this device. This is a know problem due to a website changes. This problem could be solved in the future, but at the moment there is no solution.

In the previous version 1.22.0 everything was fine.

Thx.
====================================================
Android TV, KM6 Deluxe. Kodi 20.1, Netflix addon 1.22.1+matrix.1

### Debug log - mandatory

https://paste.kodi.tv/udijuyewal.kodi

**Comment by CastagnaIT** [comment]
the error message already give an explanation
