### ISSUE TITLE
Librelec Nightly (21.0 alpha) Netflix resolution 540p max

### ISSUE THREAD

**Issue by hbbernardo** [CastagnaIT/plugin.video.netflix#1598]
### Netflix add-on version

1.22.1

### Operative systems used

LibreELEC

### Kodi version used

Other (specify in description)

### Description of the bug

Hi. 
Since last Friday I have been limited to a resolution of **540p** on Netflix.

I'm running the Latest **Librelec Test Build. Kodi 21.0 alpha.**

**InputStream Adaptive: 21.1.2.1**

### Steps to reproduce the behavior

Open Netflix Addon.

Select any title and try to play it.

Max resolution available is only up to 540p

### Debug log - mandatory

https://paste.kodi.tv/arosifolen.kodi

### Screenshots

![feem_dbb65f367209e802_IMG_20230630_185105087](https://github.com/CastagnaIT/plugin.video.netflix/assets/24485236/dec81a83-14d5-40ec-a524-cee31a2b707e)
![feem_dbb65f367209e802_IMG_20230630_185924614](https://github.com/CastagnaIT/plugin.video.netflix/assets/24485236/745765cf-a573-4d93-b287-5402af370056)

**Comment by hbbernardo** [comment]
I have another piece of information.

I do own a Vero 4K (OSMC) running Kodi 20.1 and I went to test with it since it has been a while since I haven't used it for Netflix playback.

I updated to the latest Widevine mandatory and it still running Kodi **Netflix Addon version 1.22.0.**

The resolution being offered goes up to 1080p.

I noticed that an update to Netflix Addon is being offered to the same version I'm already running on LibreElec **v 1.22.1** 

I will update this bug report with new informations after upgrading the addon to the latest version.

**Comment by hbbernardo** [comment]
I have updated Netflix Addon to the latest version 1.22.1 on my Vero 4K (OSMC) running Kodi 20.1

It didn't affect the resolution. I'm still getting max res up to 1080p.

![feem_dbb65f367209e802_IMG_20230703_233530993~2](https://github.com/CastagnaIT/plugin.video.netflix/assets/24485236/31c882f8-3aae-4dbc-a630-da620159145c)

It seems to be only affecting LibreElec running the latest 21.0 alpha.

As of now, that is all I can report. 

Hope this helps.

**Comment by Gujal00** [comment]
Same max 960x540 behaviour observer on CoreElec 21 NE nightly too

**Comment by CastagnaIT** [comment]
reset ESN should works
anyway no other solutions
