### ISSUE TITLE
Migrating library to new format throws UnicodeDecodeError

### ISSUE THREAD

**Issue by helviojr** [CastagnaIT/plugin.video.netflix#16]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

UnicodeDecodeError migrating to new format

### Addon version used

14.0 [master commit f798118]

### Description

Trying to migrate library to new format, in settings, **if movie/series name has a non ASCII character**, the script will stop with a UnicodeDecodeError as the files are written in UTF-8, but read() method seems to load it as ASCII.

### Steps to Reproduce

1. Have in your library directory files in old format that have non-ascii characters in its name
2. Enter Addon Settings
2. Choose page Collection
3. Click on "Migrate Library to new format"

**Expected behavior:** All strm files are migrated from old format url to new format

**Actual behavior:** In old format, url is on second line, and the first line is a comment with the movie's name. If it is a foreign name, chances are there are non-ASCII characters. If so, and UnicodeDecodeError appears in a popup window (Addon Error), and the migration stops on that folder.

## Context (Environment)
Leia 18.0, Windows 10

### Installation

* [X] I'm using this Netflix Repo (Git Clone)
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

Sorry, I erased the log, when I got to fix it.

## Other information

Just a decode('utf-8') on the file read string solved for me. Probably in old style, the file is written in UTF-8, but the .read() method reads as ASCII, so the method .split() throw errors on non-ASCII chars. Will send a PR.

**Comment by CastagnaIT** [comment]
merged
