### ISSUE TITLE
NFAuth file not showing up

### ISSUE THREAD

**Issue by Yami-Sam** [CastagnaIT/plugin.video.netflix#1600]
### Netflix add-on version

lastest version

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When trying to log in with authentication key, after putting the file in download and tried root, when choosing the option of logging in with auth key it does not find the file. only shows the folders but no nfauth file. but in a normal file explorer i find the file. do you know what i did wrong or if it is a bug`?

### Debug log - mandatory

i do not think the log is neccessary

**Comment by CastagnaIT** [comment]
this is not addon bug
you have wrong android permissions set to your Kodi app that hide files
