### ISSUE TITLE
Playback error due to website changes

### ISSUE THREAD

**Issue by Warprein** [CastagnaIT/plugin.video.netflix#1603]
### Netflix add-on version

1.22.1+matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Device: Mi Stick
Current Kodi version: v20.2 (but the same error is also being encountered with v19 for several weeks 

Netflix Add-on error
Due to a msl error you cannot playback videos with this device. This is a know problem due to a website changes. This problem could be solved in the future, but at the moment there is no solution

Playback failed
One or more items failed to play. Check the log for mor information about this message.

### Debug log - mandatory

https://paste.kodi.tv/dewaramatu.kodi

**Comment by cache-sk** [comment]
I had identical error on Xiaomi Mi Box 3, Xiaomi Mi Box S (first gen) and Xiaomi Mi Tv Stick (old FHD model).

As i know, all three are L1 and Netflix certified. All three have AndroidTV 9 and disabled Netflix app.

I have tried addon version 1.22.0, as suggested in #1597 and it worked.

So i have done some tinkering and this is result:

Version: 1.22.3 on Kodi 20.2 from play store, all three mentioned Xiaomi devices.

Logged in with key and password, playback shows this "msl website changes" error.

In expert settings, i have disabled atmos (don't have HW for it), enabled vp9 and hevc.

Then in ESN / Widevine settings, turned off 540p limit, set Force L3 and hit OK.

Now playback works, even in 1080p (only FHD tv's, can't test 4K).

I don't understand why, because all three are L1 devices..

**Comment by cache-sk** [comment]
I hopefully managed to solve it. My previous comment was complete bullshit, so I crossed it out. I tried the addon for the first time then..

Reason why this MSL error shows on Xiaomi devices is wrong ESN.

On my Nvidia Shield "tube" is prefix of ESN same for official app and addon.

But on my Xiaomi devices not.

(Is it OK and safe to publish this?)

Xiami Mi Box 3 (pretty old, but still working)
Official ESN: NFANDROID2-PRV-XIAOMIM12TRIAL-....
Addon ESN: NFANDROID1-PRV-T-...

Xiaomi Mi Box S (1st gen, same HW as Box 3):
Official ESN: NFANDROID2-PRV-M19-....
Addon ESN: NFANDROID1-PRV-T-...

Xiaomi Mi Tv Stick (first HD model, own it twice):
Official ESN: NFANDROID2-PRV-AQUAMAN-....
Addon ESN: NFANDROID1-PRV-T-...

Addon have same wrong ESN on all 4 Xiaomi devices i own.

@Warprein - try it, just check your official app ESN and edit ESN prefix in addon, keep other ESN settings at default, it works for me, few days so far 😊

@CastagnaIT - maybe it will help as a hint for other devices with the same error from version 1.22.1, I don't know how the ESN is generated in the addon, but at least it doesn't work correctly on Xiaomi devices.

**Comment by osdieman** [comment]
Hi All..
I had the same on some xiami boxes and sticks..
What worked for me to get arround this was as following :
Reset the whole netflix addon and inputstream.. then re-login and all should work again.. 
Hope this helped

Kind regards

**Comment by CastagnaIT** [comment]
> Oh crap, I have found why is addon generating T - ESN.. Because (on Box 3) value for ro.build.characteristics is literally default..

@cache-sk exact tv boxes with andoird tv OS should always have "TV" on ro.build.characteristics

if you can confirm that on all your 4 xiaomi devices
the `ro.com.google.clientidbase` have `android-xiaomi-tv` value,
then i can add a special case to force generate the NFANDROID2 when that value match

**Comment by cache-sk** [comment]
@CastagnaIT 

I finally found time to check it on all these devices and I confirm that on all four named xiaomi boxes/tv sticks with Android TV 9 is `ro.build.characteristics` == `default` and `ro.com.google.clientidbase` == `android-xiaomi-tv`

Checked with qute terminal and `getprop` command.

**Comment by CastagnaIT** [comment]
thanks i will add this check

**Comment by ProtonWolf** [comment]
When i try to change the ESN prefix from NFANDROID1-PRV-T to my device NFANDROID1-PXA-T it says Wrong ESN format, i also tried  NFANDROID2-PRV it chnges without any error but when i try to play a video i get logout problem

**Comment by ProtonWolf** [comment]
Can anyone help? @CastagnaIT

**Comment by trybik** [comment]
I'm seeing this error too; the add-on version is 1.23.3+matrix.1 and I'm running it in netflix.kodi.edition 1.26 (Kodi 19.4 fork; I'm guessing this doesn't matter - please correct me) on Android 9. The add-on generated ESN for my XGIMI Mogo Pro+ device starts with `NFANDROID2-PRV-0-CHENGP` prefix (tried also replacing 2 with 1 to no success). Any ideas how to go about it / if this is solvable?
