### ISSUE TITLE
Matepad 10.4 msl error

### ISSUE THREAD

**Issue by Pandasnake** [CastagnaIT/plugin.video.netflix#1604]
### Netflix add-on version

1.22.1+ matrix1

### Operative systems used

Android

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

When i select a serie it show me
"due to MSL error you cannot playback video with this Device.
This is a know problem due to a website changes.
This problem could be solved in the future, but at the momento there is no solution"
Se c'è qualche novità ti prego di fornirmi indicazioni, magari in italiano così che possa seguirle al meglio, grazie in anticipo 

### Debug log - mandatory

Logs show nothing

**Comment by CastagnaIT** [comment]
if there was news it would have been released

la descrizione dell'errore è esaustiva,
se ci fossero novità sarebbero state rilasciate
