### ISSUE TITLE
Netflix plugin doesn't install on fresh OSMC install due to not finding signals

### ISSUE THREAD

**Issue by thiagohp** [CastagnaIT/plugin.video.netflix#1608]
### Netflix add-on version

Latest

### Operative systems used

OSMC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When trying to install the Netflix plugin from the repo in Kodi on a freshly-installed OSMC (latest version), it says dependency script.module.addon.signals version 0.0.6+matrix.1 cannot be satisfied, so installing the plugin fails. This issue is similar to #1410, but I tried its solution and it didn't work due to overlap between kodi-repository-kodi and rbp2-mediacenter-osmc.

Thanks in advance.

### Debug log - mandatory

No log involved

**Comment by thiagohp** [comment]
I ended up fixing this by manually downloading and installing the signals addon. Maybe the Netflix repository could also deliver signals, since it doesn't seem to be in the main repository anymore?

**Comment by PiJunkie** [comment]
Have the same issue. Additionally I cannot connect to the kodi addons repository although it appears in the list of repositories. How did you load the signals addon manually. Down load a zip file?

**Comment by PiJunkie** [comment]
p.s redid full load from scratch today and everything worked. Not sure if it was because I had more than one osmc loader on my laptop and maybe an old loader version still let me attempt to load 20.2.

did install of osmc and a disttro upgrade straight after. Followed CastagnaIT instructions for kodi 19+ and all dependencies available.

**Comment by CastagnaIT** [comment]
i check and from what i can tell addon.signals addon library its available on kodi repository as before and so has not been removed
so the problem not depends on this addon, but something not working on your kodi or kodi server temporary was not working good
