### ISSUE TITLE
NFAuthenticationKey source

### ISSUE THREAD

**Issue by mrwensveen** [CastagnaIT/plugin.video.netflix#1609]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request

I'm pretty new to Kodi and the Add-on ecosystem. While the source for this plugin itself is available, I couldn't find the source code for the (as per now unfortunately mandatory) NFAuthenticationKey program. I'm very grateful for all the work, but I'm unsure if I can trust this program.

This isn't because of the warning Windows shows before running the program, but because of the theoretical possibility of the program recording my username and password when it is filled into the login form, or even by using a keylogger.

I have no reason to suspect any wrongdoing, but healthy mistrust is healthy. It would be wonderful if the source of NFAuthenticationKey would be available so people can see what's going on.

#### Describe an alternative

I've tried looking at the cookies and request headers that are sent after logging in, using Chrome DevTools, but I don't know the format of NFAuthentication.key.

#### Development tips

Maybe an alternative/manual method could be provided for those who are technical enough to use devTools or use Postman or some other tool.

**Comment by mrwensveen** [comment]
There is some useful info on how the key is read in resources/lib/common/credentials.py. It looks like I need to create a JSON file with some fields and the encrypt it using the PIN (any string repeated 4 times)?

**Comment by CastagnaIT** [comment]
NFAuthenticationKey sources are already available on this github repository
you have just to open the right project (and branch) that its clearily named as NFAuthenticationKey

**Comment by mrwensveen** [comment]
You're right, I'm so sorry. Thanks!

For those with similarly weak perception skills:
[CastagnaIT/NFAuthenticationKey](https://github.com/CastagnaIT/NFAuthenticationKey)
