### ISSUE TITLE
Netflix open on too many devices

### ISSUE THREAD

**Issue by fatm4n** [CastagnaIT/plugin.video.netflix#1610]
### Netflix add-on version

1.18.8+matrix.1

### Operative systems used

Other (specify in description)

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

I am no longer receiving an error message when my Netflix account is being used on another device. Is this the correct behavior for this plugin moving forward?

arm v7 jeOS

### Steps to reproduce the behavior

1. Have a single screen Netflix account
2. start up movie in one room
3. start a TV show in my room
4. show starts without the error message

### Debug log - mandatory

https://pastebin.com/zfQDQsz5

**Comment by CastagnaIT** [comment]
im sorry but nothing will be done for this

**Comment by fatm4n** [comment]
Okay, thank you for getting back to me.
