### ISSUE TITLE
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'

### ISSUE THREAD

**Issue by daktak** [CastagnaIT/plugin.video.netflix#1611]
### Netflix add-on version

1.22.0+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

AttributeError: module 'httpcore' has no attribute 'NetworkBackend'

Backend service unable to run with python error (python 3.11)

### Steps to reproduce the behavior

Load Netflix plugin

### Debug log - mandatory

https://paste.kodi.tv/ukuyexetex.kodi

### Possible fix

Upgrade to the following package versions
httpcore-0.17.3
httpx-0.24.1
h11-0.14.0

**Comment by jiminorris** [comment]
I'm getting this error and my httpcore and h11 packages are already at the suggested version, so chances are the issue is with httpx, perhaps??

**Comment by CastagnaIT** [comment]
looks like someone has already investigated
https://medium.com/@pourya.mansouri/fixing-the-attributeerror-module-httpcore-has-no-attribute-networkbackend-issue-in-python-44c6286f1670

> upgrading your `httpcore` package to version 0.15.0 or higher.

now i will have to understand if we can also update whole httpx and deps instead of a single component,
because my last attempt (#1485) has failed due to other unknown bug/problems

**Comment by CastagnaIT** [comment]
i have update whole deps but i havent time to test on different operative systems
please try to see if works, or some errors like "BlockingIOError" happens

[plugin.video.netflix_1.22.1+matrix.1_20230913.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/12598042/plugin.video.netflix_1.22.1%2Bmatrix.1_20230913.zip)

**Comment by jiminorris** [comment]
Yes, that seems to fix it for me.

**Comment by CastagnaIT** [comment]
yesterday i tested on android system,
and unfurnately this test update cause a lot of `Server disconnected` errors and addon its not usable...

i tried investigate but i have no idea how to solve "server disconnected" errors
im thinking to try rollback to default python "request" module despite it dont support http2 hoping dont cause other problems

**Comment by CastagnaIT** [comment]
i have full removed httpx and replaced with Requests module
testing on android seem to works good, please test following
[plugin.video.netflix_1.22.1+matrix.1_20230917_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/12642289/plugin.video.netflix_1.22.1%2Bmatrix.1_20230917_test2.zip)
and let me know if you find regressions/problems

**Comment by Dubeyji1233** [comment]
any solution for this error
module 'httpcore' has no attribute 'SyncHTTPTransport'
