### ISSUE TITLE
File "NFAuthenticationKey_Windows.zip" does not exist (Error 404)

### ISSUE THREAD

**Issue by marmic-hub** [CastagnaIT/plugin.video.netflix#1612]
### Netflix add-on version

na

### Operative systems used

Windows

### Kodi version used

Kodi 20

### Description of the bug

On the page "Login with Authentication key" (https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key) the URL of the NFAuthenticationKey doesnt exist (Error 404), It seems, that the File does not exist on droppbox any more, for windows and mac/linux.

### Steps to reproduce the behavior

Click on the corresponding URL

### Debug log - mandatory

n.a.

**Comment by CastagnaIT** [comment]
i think was a dropbox problem, i tried now and i can download as usual

**Comment by marmic-hub** [comment]
It seems still to be a Problem. 
![Error404](https://github.com/CastagnaIT/plugin.video.netflix/assets/53650933/739a8f5f-b6c3-4569-892e-cd82fb2ab5f8)

**Comment by CastagnaIT** [comment]
its a problem from your device not here
things to check antivirus firewall browser vpn

**Comment by marmic-hub** [comment]
i have tried with different devices. I also changed the firewall settings. Access from a mobile device (via 4G, without WLAN) did not work either. Also with different browsers...  And also using VPN to bypass any country restrictions....
I wonder what else I can do now....

**Comment by neomateo** [comment]
I've the same issue. Maybe it depends on localisation. I'm from Poland (EU).

**Comment by marmic-hub** [comment]
I am from Switzerland; but i tried also the VPN-Setting in the Opera-browser. But it didnt work either.

**Comment by CastagnaIT** [comment]
looks like there are dropbox service problems
im trying recreate the download links but give a weird error for a non-existent folder

**Comment by rainman74** [comment]
> looks like there are dropbox service problems im trying recreate the download links but give a weird error for a non-existent folder

Could you maybe provide the file temporarily in a Telegram channel?

**Comment by EscandeIsaya** [comment]
> > looks like there are dropbox service problems im trying recreate the download links but give a weird error for a non-existent folder
> 
> Working NFAuthenticationKey_Windows_1.2.2.1.zip https://ru.files.fm/u/mh2qxfggu

Hi, same error here, do you have the .py file as well, I'm on ubuntu ?

**Comment by rainman74** [comment]
> > > looks like there are dropbox service problems im trying recreate the download links but give a weird error for a non-existent folder
> > 
> > 
> > Working NFAuthenticationKey_Windows_1.2.2.1.zip https://ru.files.fm/u/mh2qxfggu
> 
> Hi, same error here, do you have the .py file as well, I'm on ubuntu ?

NFAuthenticationKey-linux-1.1.6.zip
https://ru.files.fm/u/hq2fpptku

**Comment by rainman74** [comment]
> Hi, same error here, do you have the .py file as well, I'm on ubuntu ?

I only have Windows and have just successfully created an NFAuthentication.key using Chrome Portable Browser 116.0.5845.111.

The login with the key file in plugin.video.netflix-1.22.1+matrix.1 worked.

I can't say anything about Linux, but if you need to, quickly create a Windows VM with VirtualBox.

**Comment by rainman74** [comment]
> for ac is not working the link, can you shared please?

ac?

**Comment by CastagnaIT** [comment]
i doscovered why dropbox for windows give weird errors,
dropbox introduced new rules for shared files
now are not possible share executables and scripts files like python
so all my files has been permanently banned... so that shit of rules

**Comment by rainman74** [comment]
> i doscovered why dropbox for windows give weird errors, dropbox introduced new rules for shared files now are not possible share executables and scripts files like python so all my files has been permanently banned... so that shit of rules EDIT: my account banned what bullshit is this

use a free account at https://ru.files.fm

**Comment by Collin01** [comment]
Both links (windows, linux) dosnt work. Not from windows machine, not from linux machine.

**Comment by rainman74** [comment]
> Beide Links (Windows, Linux) funktionieren nicht. Nicht von Windows-Rechnern, nicht von Linux-Rechnern.

both links do work, just verified
![Screenshot_20230831_215349_Edge](https://github.com/CastagnaIT/plugin.video.netflix/assets/16306963/15fac5c3-08b6-48bc-a3fc-3b4a9e84d0d8)

**Comment by CastagnaIT** [comment]
i have replaced links on wiki hope these works
