### ISSUE TITLE
Sources for NFAuthenticationKey have stopped being listed?

### ISSUE THREAD

**Issue by sdbbs** [CastagnaIT/plugin.video.netflix#1614]
### Netflix add-on version

v1.22.1

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I wouldn't call this really a Netflix add-on bug, but there is not a more appropriate place to report it.

So everything was working fine, and yesterday suddenly I cannot log in to Netflix addon anymore. So, I run `python3 NFAuthenticationKey_1.1.6.py` today, do the routine,  get a new `NFAuthentication.key` - and I copy it to the same NFS share I've always copied it to. I removed Netflix addon, closed Kodi, reopened Kodi, reinstalled Netflix addon, tried the usual login/pass it failed, tried again, and chose "Authentication key" login method - and I get this as next screen:

![image](https://github.com/CastagnaIT/plugin.video.netflix/assets/48317456/6fc30a43-3a84-4c2b-a0c6-7c0ec7ab4e94)

So, note that I have just `nfs://` there, without a server - and when I click it, nothing happens.

Precisely for those reasons, I have made a File Manager NFS share in the past, the one prefixed with Media in the screenshot below:

![image](https://github.com/CastagnaIT/plugin.video.netflix/assets/48317456/dd3e3764-2c4a-42fa-a9dc-07e18d689278)

... which is exactly what I have used until now, to copy the NFAuthentication.key over (and to find it) in Kodi!

And this share is still otherwise accessible in Kodi ... except, as shown in the first screenshot, it does not appear as an option in the "Search: NFAuthentication.key" in first screenshot ?! 

And that means, that I - somehow - cannot navigate to the location of the NFAuthentication.key anymore ?!?!

Up to now, I would have had the "Media*" share listed in the "Search: NFAuthentication.key", I would have clicked there, found the key, no problem ....

Now I don't have that share listed anymore - I only have `nfs://` option without a server, which does nothing when clicked.

The weirdest thing is, of course, that neither the Netflix addon got updated in the past days, nor have I updated Kodi in the past months - so I really understand where could this problem (a Kodi file manager share not being listed) come from ?!

Anyways - if anyone has a suggestion on how to debug this further, it would be much appreciated ...

### Debug log - mandatory

https://paste.kodi.tv/vizecazudi.kodi

**Comment by CastagnaIT** [comment]
i have no idea, the file browser dialog is a built-in kodi feature and not an addon dialog implementation
this dialog is already enabled for local and shared sources, so there is something wrong in your kodi configuration or a kodi bug
nothing that can be done from addon

**Comment by RandomGithubUsername** [comment]
I have the same issue. Did you figure out a solution?
