### ISSUE TITLE
Can login to Netflix, get logged out upon attempt to play video

### ISSUE THREAD

**Issue by sdbbs** [CastagnaIT/plugin.video.netflix#1615]
### Netflix add-on version

v1.22.1

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I hate Netflix the company so much.

Yesterday, I could not login to Netflix via add-on anymore.

Today, I uninstalled plugin, closed Kodi, reopened Kodi, reinstalled plugin, try to login via normal email/password - couldn't; re-ran NFAuthenticationKey_1.1.6.py on my Linux PC, got a new NFAuthentication.key; went back to Kodi, used the key - and I could log in, and get to the lists of movies (e.g. "New on Netflix")

But once I click on play a movie, something gets broken, and I'm logged off, and if I want to get to the lists, I have to log in via NFAuthentication.key again ... 

So, in all - I can log in to Netflix, but as I get logged out whenever I try to play anything - I cannot actually watch anything either.

### Debug log - mandatory

https://paste.kodi.tv/ahiverukix.kodi

**Comment by boeschy** [comment]
I can confirm the described behavior with the latest CastagnaIT release. But this version works though on my shield: https://github.com/CastagnaIT/plugin.video.netflix/issues/1589#issuecomment-1595581706

**Comment by CastagnaIT** [comment]
the attached log is without kodi debug and with no addon debug enabled, also shrinked, its not useful

**Comment by boeschy** [comment]
It seems like this was a temporary issue (on Netflix's side?). I cannot reproduce the issue anymore.

**Comment by CastagnaIT** [comment]
there are a lot of weirdness due to recent website changes,
and also often happens that there are temporary non working things due to website
so i havent an answer, there is no way to have a perfect working addon

**Comment by sdbbs** [comment]
Hi again,

>  so i havent an answer, there is no way to have a perfect working addon

No problem, understood - just wanted to post some new info, as I still have the same problem:

> the attached log is without kodi debug and with no addon debug enabled, also shrinked, its not useful

Sorry about that; I finally had some time, and enabled kodi / Settings / System / Logging / Enable debug logging and Enable component-specific logging; as well as Addons / Netflix / Settings / Expert / Enable debug logging; and I got a new log:

I had uninstalled Netflix addon, and Input Stream Helper, then reinstalled Netflix addon; again same problem, this time captured on this log:

https://paste.kodi.tv/waqawixumi.kodi 

* Netflix addon here will not accept username/password login, only NFAuthentication.key works
* upon entry to Netflix addon, authentication with NFAuthentication.key passes
* Upon trying to watch anything after that, process fails, and then I'm automatically logged off from Netflix (so I have to do the  NFAuthentication.key again)

The log shows successful authentication upon entry to Netflix addon, and then the failure upon attempting to watch anything thereafter ...

As far as I can tell, the problem is "MSLError: Email or password is incorrect." upon "Requesting manifest (version default)" (likely the "Executing POST request to" `https://www.netflix.com/msl/playapi/cadmium/licensedmanifest?reqAttempt=1&reqName=prefetch%2FlicensedManifest...`) - which is of course bizarre, because a few moments before that, there is "[plugin.video.netflix (0)] Login successful" ?!

Btw https://github.com/CastagnaIT/plugin.video.netflix

> Do not cut, edit or remove parts of the log (there are no sensitive data)

Well, with all of the debug enabled, it did dump my Netflix username, which I consider sensitive, and the locales for my Netflix accounts, which might be even more revealing - so at least I censored those (though all that JSON data returned for the movies is in the profile language, that might be enough to expose me, but eh...)

**Comment by Paco8** [comment]
In an android device I was still using kodi 18, the Netflix addon worked fine. But after installing kodi 19 I'm getting this problem. Is there any solution?

**Comment by 3v1n0** [comment]
Same issue here, authentication key works for browsing, once you play, you get out.

I also tried using an auth key from my main browsers profiles, after having played things there. No joy in kodi :cry:.
