### ISSUE TITLE
NFAuthenticationKey_Windows.zip Not Available from OneDrive Folder

### ISSUE THREAD

**Issue by PrSinister** [CastagnaIT/plugin.video.netflix#1616]
### Netflix add-on version

1.22.1

### Operative systems used

Windows

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

The NFAuthenticationKey_Windows.zip is not in the OneDrive folder linked in the Wiki

### Debug log - mandatory

paste.kodi.tv

**Comment by CastagnaIT** [comment]
link replaced
hoping onedrive dont complain again

**Comment by gively92** [comment]
onedrive complained again. there is no any files
