### ISSUE TITLE
AMPLAYBACK disabled due to percentage. Problems while playing Netflix's One Piece 

### ISSUE THREAD

**Issue by 27hectormanuel** [CastagnaIT/plugin.video.netflix#1617]
### Netflix add-on version

1.22.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

A day after I was watching Netflix's One Piece I come back to finish watching and encounter odd playback issues with only this title. I tried everything uninstalling log out/log in etc.

### Steps to reproduce the behavior

In my case start One Piece and then notice nothing is playing (sometimes sound) and UI starts glitching

### Debug log - mandatory

log wont save in pastebin/pase.kodi (https://archive.org/details/kodiNetflix2023)
[LOG.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/12546926/LOG.txt)

**Comment by CastagnaIT** [comment]
its possible that all problems are related to errors

`2023-09-06 19:15:32.011 T:20937   debug <general>: AddOnLog: inputstream.adaptive: DecryptAndDecodeVideo: Returned CDM status: 5`

that means video decoding error
reasons behind this could be again new website changes or a temporary fails

**Comment by 27hectormanuel** [comment]
Have you encountered the same error?

**Comment by CastagnaIT** [comment]
no, testing on Ubuntu linux i dont have this problem with any title
but could be a website change rolledout for some accounts only
atm i have no idea

**Comment by CastagnaIT** [comment]
closed since i have no solutions
