### ISSUE TITLE
NFAuthenticationKey_Windows.zip Not Available from OneDrive Folder

### ISSUE THREAD

**Issue by gively92** [CastagnaIT/plugin.video.netflix#1618]
### Netflix add-on version

1.22.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

The NFAuthenticationKey_Windows.zip is not in the OneDrive folder linked in the Wiki
I think OneDrive deleted your file

![image](https://github.com/CastagnaIT/plugin.video.netflix/assets/39806750/b9394bd7-5681-4c96-bc2d-bca71f499ea3)

### Debug log - mandatory

paste.kodi.tv

**Comment by CastagnaIT** [comment]
links updated
