### ISSUE TITLE
Error while starting Netflix addon - Missing Crypto library

### ISSUE THREAD

**Issue by vkasotis** [CastagnaIT/plugin.video.netflix#1619]
### Netflix add-on version

1.22.1+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hi, 

after a clean installation of Kodi to version 20.2 (OSMC installation) I've tried to use the Netflix add on, however, after the installation I get an error

which mentions : In your system is missing some required library to run Netflix. Error Details : No module named 'Crypto'.

However pycryptodome-3.18.0 is successfully installed. Is there another fix that I could use apart from uninstalling and reinstall  pycryptodome-3.18.0 because I've already tried that.

### Steps to reproduce the behavior

After installation I've just tried to start the Netflix add-on.

### Debug log - mandatory

https://paste.kodi.tv/woyixacobo.kodi

**Comment by CastagnaIT** [comment]
this is not an addon bug more likely in your system there are installed two versions of same library
you can find on old closed Issues a differents solutions
I don't go over the same things every time
