### ISSUE TITLE
Cannot start playback: Request failed validation key exchange

### ISSUE THREAD

**Issue by foegra** [CastagnaIT/plugin.video.netflix#1624]
### Netflix add-on version

1.22.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

I can login successfully, however when i try to play any video, i get this error:
Request failed validation during key exchange.
Would really love to use this plugin, let me know if you need more info from my side.

### Debug log - mandatory

https://paste.kodi.tv/raw/ogaboxafed

**Comment by CastagnaIT** [comment]
in the wiki the opnly solutions:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#msl-error-Request-failed-validation-during-key-exchange

**Comment by foegra** [comment]
> in the wiki the only solutions: https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#msl-error-Request-failed-validation-during-key-exchange

I see. I am sure - my device is not certified. So in that case - no chance plugins would work, or?
