### ISSUE TITLE
Error when running add-on

### ISSUE THREAD

**Issue by Xoppop** [CastagnaIT/plugin.video.netflix#1633]
### Netflix add-on version

v1.22.1+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Running the add-on ends with an error. Tried reinstalling different versions, doesn't help.

### Debug log - mandatory

https://paste.kodi.tv/ijuvafujoz.kodi

**Comment by CastagnaIT** [comment]
log has been cut so i cannot understand nothing more
the root of error is not netflix addon, but the dependency component `script.module.myconnpy`

i could theorize that you could have a too old python version on your system not compatible with that dependency
or you have upgraded kodi versions and so messedup kodi user data files
and so you need delete kodi user data folder to start from scratch

**Comment by willem640** [comment]
It’s asking for annotations from __future__, which you need at least Python 3.7 for ([PEP 563](https://peps.python.org/pep-0563/#enabling-the-future-behavior-in-python-3-7)). Maybe try (in this order) uninstalling Kodi, deleting Kodi’s user files, updating Python and then reinstalling Kodi
