### ISSUE TITLE
netflix addon logs out when using netflix account in wrong country

### ISSUE THREAD

**Issue by RichardBeisser** [CastagnaIT/plugin.video.netflix#1636]
### Netflix add-on version

1.22.3+matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hello,

Problem:
Addon logs out automatically when using Account in wrong country.

Reproduce:
Create a new account at Netflix Turkey, for example with vpn, pay with gift card.
In the first 30 days, the account cannot be used outside Turkey.

In official app / Browser, netflix shows a message that you use netflix in wrong country

Kodi netflix addon shows a message that login would be wrong.
After that, addon deletes credentials.
You have to enter it again.

In my case, I used NFAuthentication.key method

### Steps to reproduce the behavior

Create a new account at Netflix Turkey, for example with vpn, pay with gift card.
In the first 30 days, the account cannot be used outside Turkey.

Start try without a turkey ip.
Create NFAuthentication.key, open it in addon.
You can browse through categories.

Problem occurs when you try to start something, a movie/episode

### Debug log - mandatory

https://paste.kodi.tv/xuzukitize.kodi

### Screenshots

![netflixTurkeyInGermany](https://github.com/CastagnaIT/plugin.video.netflix/assets/47367173/e25d35c7-da80-4c43-a308-09b2a5767588)

**Comment by CastagnaIT** [comment]
i assume so,
netflix has defined rules for account usage between different countries and i think this will not work with the addon that is not a webbrowser, nor an app with a framework,
also given the recent changes introduced by netflix aimed at sharing and usage limits of accounts, this is a particular use case difficult to test and find a kind of solution given also the current addon login problems,
given above statements i will not invest time on this

moreover here we dont provide any kind of VPN/Proxy support with this addon, due to differents laws imposed by countries

**Comment by RichardBeisser** [comment]
> i assume so, netflix has defined rules for account usage between different countries ...use case difficult to test and find a kind of solution ...
> moreover here we dont provide any kind of VPN/Proxy support with this addon, due to differents laws imposed by countries

Thanks for fast reply.
As I decribed, a new netflix account can only be used in the country of activision within the first 30 day.
I agree with you, this is nothing that the addon has to handle.

The first intension of my bug report:
Is it possible to make differences in the responses of netflix's servers, if credentials are wrong, or the reason is another one?

The second intension:
There should be a option do disable automatically logout when returning PW wrong.
The login is not wrong. When you start the addon again, it can use the same credentials.

--> at the moment, when I use the same NFAuthentication.key with same PIN-Code with same Account-PW, the Addon can login successfully

**Comment by CastagnaIT** [comment]
> Is it possible to make differences in the responses of netflix's servers, if credentials are wrong, or the reason is another one?

by reading your log
its a common wrong credential error i dont see differences

> There should be a option do disable automatically logout when returning PW wrong.
> At the moment, the addon automatically sign out / dismiss credentials.

nope, if has been implemented in this way there are good reasons behind this,
if you want do this and remove this "logout" you can make your custom changes in the addon source code,
ofc it may cause you other side effects when something else goes wrong
