### ISSUE TITLE
Adding language menus

### ISSUE THREAD

**Issue by test01203** [CastagnaIT/plugin.video.netflix#1639]
Hi on the computer version in the browser
It is possible to choose a whole category of series in Turkish
or in any other language in the world
And here the option does not exist and in the search there is also no option to search by language (doesn't work)
I would love for you to add it
![image](https://github.com/CastagnaIT/plugin.video.netflix/assets/104188844/77b1016f-c269-478a-bf18-8580c528354f)

**Comment by CastagnaIT** [comment]
yes search by language menu is broken due to website api query changed
i will try check if possible fix it

**Comment by test01203** [comment]
> yes search by language menu is broken due to website api query changed i will try check if possible fix it



> yes search by language menu is broken due to website api query changed i will try check if possible fix it

Can you check the option of categories?
of languages?
