### ISSUE TITLE
Feat. Req. : Manage Netflix library from inside Kodi library

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#164]
*I'm submitting a ...*
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## General information

I propose once our database work is done to create a new feature: a context menu on movies and tvshows in the Kodi library that will allow to:

- Refresh
- Remove show or movie
- Export new episodes (shows only)
- Include/Exclude from auto update (shows only)

In my idea, it will be based on tags. A tvshow (or movie) exported from the Netflix addon will be tagged "netflix_addon", and if this tag is present, the context menu items will appear.

To avoid a too large list on Kodi, it will be one context menu item named "Netflix" with sub items for all options.

I hope it can make the library management more convinient.

Comments are welcome.

**Comment by Smeulf** [comment]
I'm wondering if having the 'exported' folder from the add-on in the favorites wouldn't be enough, then no need of an extra dev...

**Comment by Smeulf** [comment]
@notoco As I know you use the library a lot, any comment on this? Thanks!

**Comment by notoco** [comment]
I'm on vacation now, if I get to the box, I'll check it out

**Comment by Smeulf** [comment]
It's not done yet ^^ it's just an idea I have.
If implemented, would you use it? Do you think it can really be interesting? Thanks.

And have a nice vacation by the way!

**Comment by dm2912** [comment]
i use the add-on only via my library (now that the nfo downloads for the weirdly structured series). 

importing fresh episodes 
remove show/movie from library

would certainly both be useful

download nfo might also be useful (for those who didnt use the nfo with the original import), although that might come under "refresh"

**Comment by Smeulf** [comment]
> download nfo might also be useful (for those who didnt use the nfo with the original import), although that might come under "refresh"

It's already implemented with a refresh. If you set NFO export to 'yes' or 'ask', a refresh will use those settings.

The auto export new episodes will use the last choice: if you said 'yes export nfo' the all new episodes will have their NFO.

Back to the main topic, I think I won't implement it, at least now very soon, as it will complexity too much the library management in the code, and may cause too much issues using tags.

So I'm closing this feature request.
