### ISSUE TITLE
Kodi 21 beta crashes on playback 

### ISSUE THREAD

**Issue by matejdro** [CastagnaIT/plugin.video.netflix#1643]
### Netflix add-on version

1.22.3

### Operative systems used

Android

### Kodi version used

Other (specify in description)

### Description of the bug

It seems like Netflix has trouble with Kodi 21 beta. Starting any playback will result in entire Kodi crashing.

### Steps to reproduce the behavior

1. Start playing any Netflix content
2. Kodi will crash

### Debug log - mandatory

https://paste.kodi.tv/ucekagacab.kodi

### Additional context

Before upgrade to 21 beta, playing Netflix works fine. Downgrading back to 20 also fixes the issue.

This is on Nvidia Shield 2019 (non-Pro) on Android 11.

**Comment by CastagnaIT** [comment]
fix on the road, you will have to wait next ISAdaptive release

**Comment by meletispanoliaskos** [comment]
Good day, i try to activate netflix with authentication key method in kodi 21 last beta version and i always receive the message that passwords do not match despite that password is correct
