### ISSUE TITLE
Weird flashing while watching video

### ISSUE THREAD

**Issue by DDQW** [CastagnaIT/plugin.video.netflix#1644]
### Netflix add-on version

1.22.3 matrix1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Blackbars are flashing between light grey and dark gray colors are flashing between saturated and unsaturated.

Problem does not exist with youtube, disney or prime

### Steps to reproduce the behavior

open netflix addon
play anything

### Debug log - mandatory

https://paste.kodi.tv/nufefeduqi.kodi

**Comment by CastagnaIT** [comment]
looks like a LibreELEC or Kodi problem
its not a thing can be solved by the addon itself

**Comment by DDQW** [comment]
it happens exclusivly wit netflix addon. You sure it is a elec/kodi problem? any hints/ideas?
