### ISSUE TITLE
Remove packages from Makefile

### ISSUE THREAD

**Issue by sveyret** [CastagnaIT/plugin.video.netflix#1646]
### Netflix add-on version

1.22.3

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Since commit c56dc6de10ce5b612ed1587f1a1ead83434cde82 the packages directory has been removed, but it is still used in the variable `include_files` of the Makefile.

### Debug log - mandatory

n/a

### Possible fix

In the Makefile, change the line
include_files = addon.py addon.xml LICENSE.txt README.md resources/ service.py packages/
to
include_files = addon.py addon.xml LICENSE.txt README.md resources/ service.py

**Comment by CastagnaIT** [comment]
forgot, thanks
