### ISSUE TITLE
Default Netflix addon subtitles act like my kodi presets

### ISSUE THREAD

**Issue by ananias47** [CastagnaIT/plugin.video.netflix#1649]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x ] change an existing feature

### Describe your request

I have my kodi presets on subs to show at the bottom of the video.Is there an option on the default Netflix subs as well??

**Comment by CastagnaIT** [comment]
you need to enable Kodi subtitles override settings to force change position of webvtt subtitles
