### ISSUE TITLE
Backup Netflix

### ISSUE THREAD

**Issue by ananias47** [CastagnaIT/plugin.video.netflix#1650]
## Feature request
I'm submitting a proposal to ...
  - [x ] new feature
  - [ ] change an existing feature

### Describe your request

Hi i have my own built and i use it on 5-6 devices(android box ,phone coreelec and windows).Because i make changes on my built i must do fresh install many times.It would be great if it is  an option to backup the settings of netflix addon withought backup entire built 
Thank you in advance

**Comment by CastagnaIT** [comment]
this addon encrypt credentials by using "hardware" encryption
so if you copy/restore the backupped data to another device will invalidate the login credentials previously stored

you can try disable "use system-based encryption for credentials" from addon Expert setting (if changed you have to re-login),
in this way the login will be stored without higher encryption and if you restore the backupped data to another device in theory shoud not ask to login again

**Comment by ananias47** [comment]
Ok i understand so is it an option to authenticator last forever??

**Comment by CastagnaIT** [comment]
as already said above the only chance is turn off "use system-based encryption for credentials"

**Comment by ananias47** [comment]
I try it to disable the option of hardware encryption but still no luck

Never mind thank you again for your great work
