### ISSUE TITLE
error when entering the correct password in the addon 

### ISSUE THREAD

**Issue by edersonmax21** [CastagnaIT/plugin.video.netflix#1651]
### Netflix add-on version

1.23.0

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

I try to log in to the addon and my password is correct, but when I try to log in it says that the password is incorrect, I can't use authenticationkey because I don't have a computer 

### Steps to reproduce the behavior

1. open the addon 
2. enter the password 
3. the error appears 

### Debug log - mandatory

https://paste.kodi.tv/zasosiwori.kodi

### Screenshots

![Screenshot_20231214_154506_Kodi](https://github.com/CastagnaIT/plugin.video.netflix/assets/52547471/1aa9654c-97c2-48e6-a549-14a776432b73)

**Comment by CastagnaIT** [comment]
explained on wiki
https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon#the-login-could-cause-incorrect-password-error

**Comment by edersonmax21** [comment]
Could you tell me how to do this without a PC?
