### ISSUE TITLE
Webbrowser wouldn't come up with NFA skript

### ISSUE THREAD

**Issue by bread-on-toast** [CastagnaIT/plugin.video.netflix#1654]
### Netflix add-on version

3.0

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When trying to generate a NFA key, the script starts but the browser is not coming up. 

### Debug log - mandatory

none, not a kodi error

### Possible fix

unknown

### Additional context

Linux Mint 20
Python 3.8.10 and 2.7.18

**Comment by bread-on-toast** [comment]
still open problem for me

**Comment by CastagnaIT** [comment]
more likely your OS have a different executable name for the browser
you can add the missing browser name on this line on your file

https://github.com/CastagnaIT/NFAuthenticationKey/blob/7c49d72fc634788fba9d49fbfdbd1a6f1612ce4a/NFAuthenticationKey.py#L244

Then if you let me know the executable name, i can add them in the original repo file

**Comment by CastagnaIT** [comment]
its possible that the solution has been already fixed
but i have no idea of what happens on your OS
i can only suggest you to try download the updated NFA script
