### ISSUE TITLE
Problems with Profile Selection

### ISSUE THREAD

**Issue by arturo-mayorga** [CastagnaIT/plugin.video.netflix#1658]
### Netflix add-on version

v1.23.1 (2023-12-16)

### Operative systems used

LibreELEC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

I logged into my Netflix account, and I was presented with multiple profiles.  These profiles match the profiles in my Netflix account but when I drill into any of these profiles, I always see the content for the first profile in the list.

### Steps to reproduce the behavior

Before starting, make sure your Netflix account has multiple profiles.

1. Start the Netflix add-on and observe multiple profiles such as
```
Videos/Netflix

* ..
* ProfileA
* ProfileB
* ProfileC
```

2. Click into `ProfileB` and observe the menus change to:
```
Videos/Netflix/ProfileA - Main Menu

* ..
* My List
* Continue Watching
```
....

3. Note that we are looking at the menue for `ProfileA` instead of the desired `ProfileB`

### Debug log - mandatory

NA

**Comment by CastagnaIT** [comment]
i have tested but unfurnately im not able to reproduce your issue

its possible a temporary problem or bad data parsed,
you can try go to Expert addon settings, and select Clear inmemory and on disk cache, after to be sure restart also Kodi

if this dont fix it, its possible that your account fall in to some new A-B test changes of website
and so there is needed to wait the worldwide update release of website to fix it

**Comment by arturo-mayorga** [comment]
Thanks for taking a look.  This is on a device that I set up for my parents so I don’t have access to logs. We’ll try to find a workaround, thanks again and happy new year!
