### ISSUE TITLE
4k content not working on linux libreelec

### ISSUE THREAD

**Issue by SoulTV** [CastagnaIT/plugin.video.netflix#166]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [x] support request

## General information
I can play content in vp9 but only up to 1080p. I can't play anything in HEVC even though my Nvidia 1030 supports it. I'm able to play HEVC through other add-ons no problem. Force hdcp 2.2 is enabled in Netflix settings and in inputstream adaptive. Widevine is installed. I'm kind  of at a loss
### Addon version used

0.14.6

### Description

See above ^

### Steps to Reproduce

Install libreelec on anything and try 4k video

**Expected behavior:** [What you expected to happen]

4k content will play

**Actual behavior:** [What actually happened]

4k content does not play
## Context (Environment)

Libreelec 9.1

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

Let me know if this helps, will provide on

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment]
on linux you can only use VP9, HEVC working only to android, some apple devices, and should on xbox
4k working only to android due to current widevine limitations
