### ISSUE TITLE
An update for NFAuthenticationKey_Windows.zip

### ISSUE THREAD

**Issue by ttchampi** [CastagnaIT/plugin.video.netflix#1662]
### Netflix add-on version

Last one

### Operative systems used

Windows

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

hi everybody,
the NF authentication key generator for windows browser seams to be old. the login page says : 
 Update required
Looks like your browser, operating system, or device is not supported. Please make some updates to access Netflix. Learn more about updates and requirements [here](https://help.netflix.com/node/133344).

Can't access your account? [Contact us](https://help.netflix.com/contactus).

thanks for all.

### Debug log - mandatory

no log

### Screenshots

![login page](https://github.com/CastagnaIT/plugin.video.netflix/assets/49229858/a30385ea-53ff-42f5-b194-5139208307cd)

**Comment by Falke-Design** [comment]
@ttchampi can you please share more information. 
* Which windows version (7,8,10,11)?
* Which browser is opened?
* What version does the browser have? (120.0.6099.130) 

For me it works fine with Windows 10 and Chrome 120.0.6099.130

**Comment by ttchampi** [comment]
I found something that works...

If I understand correctly, when I open the NFAuthenticationKey.exe file, the settings.json file is extracted and when I press start, a browser is extracted in the BrowserTempData file. But this one is no longer up to date.

...on the other hand, by opening the settings.json file, you can force NFAuthenticationKey.exe to use another browser by replacing the sentence: 
"* Remove me and specify here the browser path with .exe extension, only if not recognized ( e.g. C:\\mypath\\chrome.exe) *" 
by "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" (the path to a more up-to-date downloaded Chrome Browser with \\  and not just \ )

Anyway, but the fact remains that the browser provided with the NFAuthenticationKey.exe file is out of date... isn't it? (version appears to be number 78.0.3904.97)
