### ISSUE TITLE
Netflix Error tvq-pb-103

### ISSUE THREAD

**Issue by Ylioni** [CastagnaIT/plugin.video.netflix#167]
*I'm submitting a ...*
  - [x] bug report

## General information
This title cannot be played because it exceeds the maximum maturity rating set in your parental controls

### Addon version used
 15.0

### Description
despite parental control being deactivated, i can´t watch most content

### Steps to Reproduce
play any content with a rating

**Expected behavior:** [What you expected to happen]
play content

**Actual behavior:** [What actually happened]
get Netflix Error tvq-pb-103

## Context (Environment)
Rpi3b+, german language
### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log
uploader doesn´t work either

## Other information
https://help.netflix.com/en/node/60845

**Comment by CastagnaIT** [comment]
if your main profile is set as "Kid" you can't watch videos

**Comment by Smeulf** [comment]
Just wondering... Is it possible we're using the main profile to play the video instead of the current active profile?

**Comment by CastagnaIT** [comment]
there is something i don't understand well
for example if you choose a child profile (so the profile switch is applied), then exit to main kodi page and from the kodi library if open a horror film is watchable...
and i do not understand why, we did sitch to the main profile, maybe something escapes..

it seems that everything is reproduced only with main profile where isAccountOwner=true
but the switch works at least for get the lists

**Comment by Smeulf** [comment]
I didn't look deeply, bit I think we're sending wrong (or partial) data when requesting the manifest

**Comment by Smeulf** [comment]
Or maybe something related to some cookies? Or when passing data to InputStream

**Comment by CastagnaIT** [comment]
the data passed to inputstream is the manifest data,
we use the cookie only to login it does not seem to me that they are used for anything else
I do not know...

**Comment by Smeulf** [comment]
I'll run some debug session then ^^ hopefully I'll find something...

**Comment by CastagnaIT** [comment]
sidenote for future:
reading msl documentation it is possible that we have to implement the "user ID token"
https://github.com/Netflix/msl/wiki/User-Authentication#user-id-tokens

could explain the behavior we have from which the various problems derive
I'm not 100% sure why i'm not an expert, but this is also used in the website
it could be a starting point also for future developers

**Comment by CastagnaIT** [comment]
@Ylioni
you have same problem with latest nf addon version?

**Comment by CastagnaIT** [comment]
Closed for inactivity
