### ISSUE TITLE
NFAuthentication Key Linux Unable to connect with the browser

### ISSUE THREAD

**Issue by Arndorferd** [CastagnaIT/plugin.video.netflix#1671]
When I run Python NFAuthenticationKey I get error "Unable to connect with the browser", tried with google chrome and chromium. Using 6.6.8-2-MANJARO. Using NFAuthenticationKey 1.1.6. and google-chrome 120.0.6099.216-1 or ungoogled-chromium-bin 120.0.6099.216-1.

**Comment by Elkropac** [comment]
Hi, same  for me. Fixed it by specifiing 
`LOCALHOST_ADDRESS = '127.0.0.1'` instead of `LOCALHOST_ADDRESS = 'localhost'` , chrome listens on ipv4 localhost only

**Comment by CastagnaIT** [comment]
thanks changed by default to 127.0.0.1
