### ISSUE TITLE
PLAYBACK ERROR - MSLError: The title is not available to watch instantly...

### ISSUE THREAD

**Issue by Tallguy298** [CastagnaIT/plugin.video.netflix#1675]
### Netflix add-on version

1.23.2+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

I am receiving this error when playing ANY netflix video.
The video plays after I click on OK.

![screenshot00002](https://github.com/CastagnaIT/plugin.video.netflix/assets/148932062/da0f3a20-fbbd-4c15-bafe-937575ce0e1b)

### Debug log - mandatory

https://paste.kodi.tv/nuduzuxume.kodi

**Comment by Kampfader** [comment]
Im on kodi omega beta2, i have the same error

**Comment by tsioukas** [comment]
I have also the same problem. When I enable HDR or Dobly Vision problem I get "AMPlayback disabled due to exception: u'percentage". When I disable HDR/Dobly Vision, it freezes after 2minutes. Also time seeking isn't available.

My System Specs : KODI 20.3 on Google TV / Android 10 (Sony Bravia). My Netflix plan is Premium.

**Comment by yobionekanobi** [comment]
Same here!

**Comment by em1soldier** [comment]
Looks like an issue with widevine. Manually setting it to 540p or lower seems to play just fine, any higher and it freezes around 2 minutes in.

**Comment by etgecata** [comment]
Same here!
Kodi 20.3, Nvidia Shield Pro, Premium Ultra HD subscription.

**Comment by vwgolfo74** [comment]
Same here!
Kodi 20.3 
Fire Stick Tv 4K Max

**Comment by wajo666** [comment]
Same

Kodi 21beta-2
Philips 58PUS7304/12

**Comment by sjpark-hongik** [comment]
Exactly same problem as DocSniper's.
Kodi 21 beta on Shield TV Pro 2019

**Comment by sangju41** [comment]
> I have a problem that is very similar to this one, maybe it's the same thing, that's why I'm posting it here.
> 
> About 2 minutes after starting a video it freezes / stops playing. If I then stop the video and try to play it again from exactly this position, then I get the error: "AMVideoEvents disabled due to exception: nf_is_ads_stream".
> 
> My setup: Xiaomi TV F2 with Fire OS 7 / Kodi 21 beta 2 (Android) / Netflix add-on version 1.23.2+matrix.1 / Netflix Premium Ultra HD
> 
> ![nf_is_ads_stream_error](https://private-user-images.githubusercontent.com/3104188/300927597-147c974a-6a18-4917-921c-3a3b24acc9ad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODMxNTAsIm5iZiI6MTcwNjc4Mjg1MCwicGF0aCI6Ii8zMTA0MTg4LzMwMDkyNzU5Ny0xNDdjOTc0YS02YTE4LTQ5MTctOTIxYy0zYTNiMjRhY2M5YWQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTAyMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMzMTUwYzRhNTA4ZGQwNGRlMzdiOGVhOGE1OTg3OGJlOTUzYmQ0YzVmNmQyNWE1NjAwNTc2ZmM0YzQzY2I0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J8XcqtqRr74KB4WLSTffyD-km9aRua8eUSM65pVxL_Q)

Same problem.
Shield TV Pro 2019 / Kodi 21 beta 2 (Android) / Netflix add-on version 1.23.2+matrix.1 / Netflix Premium Ultra HD

**Comment by tsioukas** [comment]
I manage to get a 4K resolution without errors on my Google Chromecast with TV / Android 12 (Connected on Sony Bravia)

I played a video for over 10 minutes without any freeze, and I can seek at specific time. Also, I get Dolby Atmos Audio.

The only option that I can't get is Dobly Vision / HDR videos. KODI with an MKV (HDR10 enabled) video can play it at HDR but through Neflix Addon it was impossible to play HDR content. But I will try later to connect Google TV directly to my Denon AVC to see if I get HDR/Dolby Vision.

I am not sure if the problem is on Netflix Addon or on Input Stream adaptive. On my Sony Bravia (Google TV / Android 10) that I have the problem I am on Kodi 20.3 with Inputstream Adaptive 20.3.16. 

KODI Version: 21.0 BETA2 (20.90.821)

Input Stream 21.4.1 
- Stream Selection Type: Fixed Resolution (*on non 4K content select the highest available)
- Maximum resolution: 4K
- Maximum resolution for DRM videos: 4K
- Ignore HDCP Status: True

Netflix Addon: 1.23.2+matrix.1 (login with Auth key)
	Expert Settings:
		-  Dolby Digital plus codec: True
		-  VP9 Codec: False
		-  HEVC Codec: True
		-  AV1 Codec: False

I hope that it helps

**Comment by josefede** [comment]
> I have a problem that is very similar to this one, maybe it's the same thing, that's why I'm posting it here.
> 
> About 2 minutes after starting a video it freezes / stops playing. If I then stop the video and try to play it again from exactly this position, then I get the error: "AMVideoEvents disabled due to exception: nf_is_ads_stream".
> 
> My setup: Xiaomi TV F2 with Fire OS 7 / Kodi 21 beta 2 (Android) / Netflix add-on version 1.23.2+matrix.1 / Netflix Premium Ultra HD
> 
> ![nf_is_ads_stream_error](https://private-user-images.githubusercontent.com/3104188/300927597-147c974a-6a18-4917-921c-3a3b24acc9ad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjM2NTYsIm5iZiI6MTcwNjgyMzM1NiwicGF0aCI6Ii8zMTA0MTg4LzMwMDkyNzU5Ny0xNDdjOTc0YS02YTE4LTQ5MTctOTIxYy0zYTNiMjRhY2M5YWQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2MzMzExNjJlYTdjMmRjNWEwYjViNGM3OTY2NzQ5ZmQzMWZhNzEyMGVjMzk2YTVlOTY2MzMxNGQzMTE0ZTVjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._lavxZUEG3nW8Mno9eebxIZObs8yzPgnl_Pi-wy-TmE)

Same here

**Comment by nroets1** [comment]
> I manage to get a 4K resolution without errors on my Google Chromecast with TV / Android 12 (Connected on Sony Bravia)
> 
> I played a video for over 10 minutes without any freeze, and I can seek at specific time. Also, I get Dolby Atmos Audio.
> 
> The only option that I can't get is Dobly Vision / HDR videos. KODI with an MKV (HDR10 enabled) video can play it at HDR but through Neflix Addon it was impossible to play HDR content. But I will try later to connect Google TV directly to my Denon AVC to see if I get HDR/Dolby Vision.
> 
> I am not sure if the problem is on Netflix Addon or on Input Stream adaptive. On my Sony Bravia (Google TV / Android 10) that I have the problem I am on Kodi 20.3 with Inputstream Adaptive 20.3.16.
> 
> KODI Version: 21.0 BETA2 (20.90.821)
> 
> Input Stream 21.4.1
> 
> * Stream Selection Type: Fixed Resolution (*on non 4K content select the highest available)
> * Maximum resolution: 4K
> * Maximum resolution for DRM videos: 4K
> * Ignore HDCP Status: True
> 
> Netflix Addon: 1.23.2+matrix.1 (login with Auth key) Expert Settings: - Dolby Digital plus codec: True - VP9 Codec: False - HEVC Codec: True - AV1 Codec: False
> 
> I hope that it helps

I have the same issue on MiBox S 4k and also on another Android tv box (HAKU). Both have the same error. Playback freezes after 2 minutes. Newer releases on Netflix just give the MSLError and does not play at all.

I have installed KODI Version: 21.0 BETA2 on the MiBox S 4k to test. I still get the exact same issues. Nothing changed.

I also have the PriveVideo add-on installed, which also use InputStreamAdaptive and everything works without an issue. I get 4k with Dolby Atmos playback.

This error started to occurr at around the middle of January. Before that, everything was fine.

I also have kodi 20.3 installed on ubuntu 22.04 and there I get 1080p with Dolby Atmos playback without an issue.

**Comment by tsioukas** [comment]
Today I tried to play again from my Google Chromecast with TV usb stick, as described in my last post. But even if yesterday worked normally, without any change on settings, I got the MSLError on some episodes. It was possible to play some episodes from other show, but they freeze after 2min. The strange is that I got MSLError on Seinfeld S09E11 but not on S01E01 (that of course freeze after 2min). Yestereday was a fresh install/login with auth key. I don't know if this affect today behaivor.

KODI Version: 21.0 BETA2 (20.90.821)
Input Stream 21.4.1
Netflix Addon: 1.23.2+matrix.1

**Comment by nroets1** [comment]
** Temporary Fix with decent looking 960x540 playback **

Tested on kodi 21 Omega beta 2. Should work for 20.3

Input Stream 21.4.1

Stream Selection Type: Fixed Resolution (*on non 4K content select the highest available)
Maximum resolution: 4K
Maximum resolution for DRM videos: 4K
Ignore HDCP Status: True

Netflix add-on settings

Codecs
 Enable Dolby Digital Plus codec (Atmos on Premium account):  true
 Enable VP9 codec: true
 - Enable VP9 Profile 2 : true
 Enable HEVC codec: false   (960x540 looks horrible with hevc enabled)
 Enable AV1 codec: false

Playback
  Override stream selection type:     Fixed video quality
  Limit video stream resoloution to  SD  576p


With these settings I can still watch PrimeVideo in 4k and watch Netflix in kodi with decent looking 960x540.

Not and ideal solution but it works for now.

**Comment by tsioukas** [comment]
@nroets1, yes I notice that when I was playing with InputStream settings. That's I am wondering if this is InputStream or maybe ESN problem again. Maybe the random ESN dosen't work anymore. Because Google Chromecast with Google TV isn't my main KODI device I install Netflix Addon yesterday for first time (after factory reset). In less than 24h I wasn't able to play again.

**Comment by nroets1** [comment]
@tsioukas , I don't think it's an ESN error. With the ESN error, 4k was not possible at all. In my case it plays 4k but freezes after 2 minutes. For some other titles it does not play at all with anything enabled above 576p.

**Comment by Paco8** [comment]
I think the first 2 minutes are unencrypted. That's why they play fine.
I guess there's some kind of problem with the license key and Kodi can't decode the video stream.

**Comment by CastagnaIT** [comment]
@MauriceW67 hi i havent had time to try investigate on this in these days
my suspect is that the license request dont provide the decryption keys

**Comment by MauriceW67** [comment]
@CastagnaIT Ok, thanks.

For now I will revert to using the Netflix app on my Philips TV then, since the one on my Shield is still limited to 540p because of the Netflix block 😄

**Comment by shinguebai** [comment]
Hi
Same here. Netflix premium.  
On NVIDIA Shield, it happened with the kodi upgrade from 20.2 to 20.3. It freezes after 2.11 minutes exactly. 
I then switched to my Pi4 that’s still on kodi 20.2 and there it’s still ok with the same Netflix credentials.

**Comment by tsioukas** [comment]
> Hi Same here. Netflix premium. On NVIDIA Shield, it happened with the kodi upgrade from 20.2 to 20.3. It freezes after 2.11 minutes exactly. I then switched to my Pi4 that’s still on kodi 20.2 and there it’s still ok with the same Netflix credentials.

I was thinking about this update but this isn't explain Kodi 21 behaivor (even if this happened to me after 1 day as I wrote above). I hope CastagnaIT to find time to check it. Unfotunnatelly I can't go to older version on Android TV.

**Comment by CastagnaIT** [comment]
problem is not relative to kodi versions, because all kodi versions use the same inputstream library to manage drm.

the 2 minuts playback its normal because the first 2 minuts are unencrypted,
and so after that time the DRM cannot do the decryption and playback its ofc broken.

i tried investigate but i have zero ideas of whats changed on netflix servers...
website data looks the same as before, but device drm result in a weird error relative to initialize the drm session
i have not found any info about this error on the web
```
02-04 10:54:50.228  3364  3406 E oemcrypto_cenc: OEMCrypto_LoadDRMPrivateKey: error in te_launch_operation: 0x1e
02-04 10:54:50.229  5400  5834 W System.err: android.media.NotProvisionedException: Failed to open session
```

**Comment by shinguebai** [comment]
Ok, DRM handling is probably involved. But the thing is: What does it still work on Linux? (with a previous kodi version). If there had been a change on Netflix servers, we should get the same behaviour on Android and Linux, shoudn’t we? There’s Google of course…I could try upgrading the kodi that runs on linux but if it’s finally linked to the kodi version, I’ll have to reinstall kodi in 20.2 😓Le 4 févr. 2024 à 12:47, Stefano Gottardo ***@***.***> a écrit :﻿
problem is not relative to kodi versions, because all kodi versions use the same inputstream library to manage drm.
the 2 minuts playback its normal because the first 2 minuts are unencrypted,
and so after that time the DRM cannot do the decryption and playback its ofc broken.
i tried investigate but i have zero ideas of whats changed on netflix servers...
website data looks the same as before, but device drm result in a weird error relative to initialize the drm session
i have not found any info about this error on the web
02-04 10:54:50.228  3364  3406 E oemcrypto_cenc: OEMCrypto_LoadDRMPrivateKey: error in te_launch_operation: 0x1e
02-04 10:54:50.229  5400  5834 W System.err: android.media.NotProvisionedException: Failed to open session

**Comment by nroets1** [comment]
@shinguebai , I have kodi 20.3 installed on linux and it plays back netflix shows / movies at 1080p without an issue. Obviously an Android issue.

**Comment by shinguebai** [comment]
@nroets
Thanks for the hint! 
I'll give it a try.

**Comment by MauriceW67** [comment]
I don't think it's blacklisting. The issue is with 4K content, which requires Widevine L1. Linux simply does not support 4K or Widevine L1.

**Comment by nroets1** [comment]
@MauriceW67 , it also stops playing when you limit the playback to 1080p on Android.

**Comment by Tallguy298** [comment]
This problem has been fixed.
Widevine was updated to current build.
Kodi-inputstream.adaptive was updated to current build.
Netflix plays in all screen resolutions without staggering, or freezing.

**Comment by shinguebai** [comment]
Thanks a lot!

**Comment by MauriceW67** [comment]
@Tallguy298 I guess for Linux the issue is solved, but on Android the addon still won't play any 4K videos.

@CastagnaIT Should we open a separate issue for 4K on Android? Or should we continue in issue #1678 ?

**Comment by tsioukas** [comment]
I don't think that they fixed for all. I am still have problem with both Google TV Devices

Google TV (Sony Bravia)

KODI Version: 20.3
Input Stream 20.3.17
Netflix Addon: 1.23.2+matrix.1

and Google Chrome

KODI Version: 21.0 BETA2 (20.90.821)
Input Stream 21.4.1
Netflix Addon: 1.23.2+matrix.1

**Comment by josefede** [comment]
> @Tallguy298 I guess for Linux the issue is solved, but on Android the addon still won't play any 4K videos.
> 
> @CastagnaIT Should we open a separate issue for 4K on Android? Or should we continue in issue #1678 ?

Maybe we should open another issue as you say because this one was originally opened regarding Linux OS. Still, it's interesting that the issue was finally solved on Linux but not on other platforms

**Comment by nroets1** [comment]
I confirm that the inputstreamadaptive update did nothing to resolve the issue on Android. I still have the same issue on both my TV boxes. MiBox S 4k and HAKU.

**Comment by kokobokoroko** [comment]
mi box s problem is same

**Comment by em1soldier** [comment]
Also still occurring for me on Chromecast with Google TV. 

KODI: 20.3
Input Stream: 20.3.17
Netflix Addon: 1.23.2+matrix.1

**Comment by buenosaires84veg** [comment]
Hi, I tried uninstalling and reinstalling the addon again, changing versions, updating everything related and nothing... Only at the lowest resolution does it play normally for more than 2 minutes! Thanks To those who are working to solve it

Android TV 11

**Comment by yobionekanobi** [comment]
Can confirm that 540p is the only resolution that works..if I implement the 540p limit workaround (i.e change ESN) to play 1080p or 2160p content..freezing occurs. 

Kodi 20.3, Nvidia Shield Pro, Premium Ultra HD subscription.

**Comment by Razem** [comment]
@CastagnaIT Could you please reopen this issue (if it's the same problem), or unlock #1678 so we can move the discussion there?

**Comment by tsioukas** [comment]
If this bug fixed on Linux with an update of InputStream adaptive, I think that something is wrong with that on Android TV, so I think that it's better to open an issue there (refering in this issue thread and Netflix Addon).

@CastagnaIT, did you find time check it better? I missed already this addon, I hate Netflix "stupid" app :(

**Comment by CastagnaIT** [comment]
unlocked https://github.com/CastagnaIT/plugin.video.netflix/issues/1678 for android

**Comment by sanzoghenzo** [comment]
Just to be sure, does the fix also include the nf_is_ads_stream issue? because I'm still having troubles on linux (NixOS unstable)

Kodi 21.2
InputStream Helper 0.7.0
Inputstream Adaptive 21.5.13
Widevine 4.10.2891.0 installed 2 days ago

it worked for an episode that day, after a reboot it keeps returning the error message.

```
025-07-22 19:13:31.882 T:1474  critical <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
2025-07-22 19:13:31.882 T:1474  warning <general>: [script.module.inputstreamhelper] Widevine update check was made on 2025-07-21 20:54
2025-07-22 19:13:32.382 T:968      info <general>: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/70158331/season/70018234/episode/70178163/?profile_guid=G57WDUBLGZB4DOE7NDN376WG3M
2025-07-22 19:13:32.397 T:2039     info <general>: Deleting settings information for files plugin://plugin.video.netflix/play/show/70158331/season/70018234/episode/70178163/?profile_guid=G57WDUBLGZB4DOE7NDN376WG3M
2025-07-22 19:13:32.400 T:1518     info <general>: Creating InputStream
2025-07-22 19:13:32.400 T:1518  warning <general>: AddOnLog: inputstream.adaptive: Warning "inputstream.adaptive.manifest_type" property is deprecated and will be removed next Kodi version, the manifest type is now automatically detected.
If you are using a proxy remember to add the appropriate "content-type" header to the HTTP manifest response
See Wiki page "How to provide custom manifest/license" to learn more about it.
2025-07-22 19:13:32.401 T:1518     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2025-07-22 19:13:32.454 T:1083    error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
File "/nix/store/jsb01qzs21x869k4bjs3f71y3vh0hizs-kodi-21.2-env/share/kodi/addons/plugin.video.netflix/resources/lib/services/playback/action_controller.py", line 358, in _notify_managers
notify_method(data)
File "/nix/store/jsb01qzs21x869k4bjs3f71y3vh0hizs-kodi-21.2-env/share/kodi/addons/plugin.video.netflix/resources/lib/services/playback/action_manager.py", line 100, in call_on_playback_stopped
self._call_if_enabled(self.on_playback_stopped, player_state=player_state)
File "/nix/store/jsb01qzs21x869k4bjs3f71y3vh0hizs-kodi-21.2-env/share/kodi/addons/plugin.video.netflix/resources/lib/services/playback/action_manager.py", line 105, in _call_if_enabled
target_func(**kwargs)
File "/nix/store/jsb01qzs21x869k4bjs3f71y3vh0hizs-kodi-21.2-env/share/kodi/addons/plugin.video.netflix/resources/lib/services/playback/am_playback.py", line 88, in on_playback_stopped
if player_state['nf_is_ads_stream']:
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'nf_is_ads_stream'
```

**Comment by Marietto2008** [comment]
> This problem has been fixed. Widevine was updated to current build. Kodi-inputstream.adaptive was updated to current build. Netflix plays in all screen resolutions without staggering, or freezing.

I've installed kodi + the netflix addon on ubuntu 24.04. I can't play any video due to the error : playback failed. One or more items failed to play.
