### ISSUE TITLE
NFAuthenticationkey login method always reports: E-Mail fied not specified

### ISSUE THREAD

**Issue by JohnBlackcrow** [CastagnaIT/plugin.video.netflix#1676]
### Netflix add-on version

1.23.2+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When using login method AuthenticationKey, Kodi reports on screen error: no email specified

### Steps to reproduce the behavior

1. Start Addon
2. Click Button AuthenticationKey
3. Specify key file
4. Enter PIN
5. Enter Password

### Debug log - mandatory

https://paste.kodi.tv/ezijidivid

### Additional context

Same results if script uses chrome or chromium

### Screenshots

![DeepinBildschirmfoto_Bereich auswählen_20240201003218](https://github.com/CastagnaIT/plugin.video.netflix/assets/158371131/87e8d446-61cf-4c78-a9cd-dcb25f52da35)

**Comment by MauriceW67** [comment]
Already being discussed here: https://github.com/CastagnaIT/plugin.video.netflix/issues/1674#issuecomment-1916288672

I think it's because Netflix changed their Account Overview page and the e-mail address is now shown in the Security sub-section.

**Comment by CastagnaIT** [comment]
cloase since its duplicate issue
already answered here: https://github.com/CastagnaIT/plugin.video.netflix/issues/1674#issuecomment-1925773481
