### ISSUE TITLE
CastagnaIT repository netflix addon issue

### ISSUE THREAD

**Issue by srdjanmayer** [CastagnaIT/plugin.video.netflix#1680]
### Netflix add-on version

1.23.2+matrix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Kodi Netflix addon doesn`t work. It`s inposible to log in with authentication key. Addon gives error:  "WbsiteParsingError:E-maol field not found". I have seen solution with shanging the line in py.accses file, but I am unable to find it. Is it any other posible solution, or -will be any update of addon to solve this issue.

            Thanks in advance
               Srdjanmayer

### Steps to reproduce the behavior

Any steps?

### Debug log - mandatory

Don` know what to do?

**Comment by CastagnaIT** [comment]
cloase since its duplicate issue
already answered here: https://github.com/CastagnaIT/plugin.video.netflix/issues/1674#issuecomment-1925773481
