### ISSUE TITLE
WebsiteParsingError: E-mail field not found

### ISSUE THREAD

**Issue by leone007** [CastagnaIT/plugin.video.netflix#1682]
### Netflix add-on version

1.23.2+martix.1

### Operative systems used

Android

### Kodi version used

Other (specify in description)

### Description of the bug

Using Kodi 21.0-BETA2 (20.90.821) Git 20231209-e7a94ebde8 quietvoid build

Cannot login ot Netflix using the authentication key method. After entering Netflix password an error message is prompted: 

WebsiteParsingError: E-mail field not found

NFAuthentication.key version 1.2.2.2 (win11)

### Steps to reproduce the behavior

Create NFAuthentication.key file
Start Netlfix addon
Log in using authentication key method
Browse for NFAuthentication.key file
Enter Pin
Enter Netflix password

### Debug log - mandatory

https://paste.kodi.tv/axidilijol.kodi

**Comment by temporaldoom** [comment]
You can fix this temporarily by the fix in this issue https://github.com/CastagnaIT/plugin.video.netflix/issues/1674

Modify the file located here 

/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py

line 127 needs to be your email address for exampe email = 'john.smith@gmail.com'

**Comment by TFCresset** [comment]
Any update on if/when this will be fixed?

Two months since `1.23.2+matrix.1`.

**Comment by FransUrbo** [comment]
Any news on if/when this will be fixed?

It's now two months (and counting) since `1.23.2+matrix.1`.

**Comment by CastagnaIT** [comment]
fix on new release

**Comment by Nedjohh** [comment]
Thanks for the fast reply. On the new release 1.23.3 im getting "Unable to extract reactContext" (LibreElec) after entering my pin and password. Maybe im missing something ?

**Comment by CastagnaIT** [comment]
more likely you have used more time the same auth.key file
create a new one

**Comment by behemoth38** [comment]
Funktioniert bei mir leider noch nicht. Nach erfolgreicher Anmeldung bei Aufruf eines Films:
MSLError: Email or Password ist incorrect

**Comment by Nedjohh** [comment]
> more likely you have used more time the same auth.key file create a new one

That did it for me. Thanks a lot !

**Comment by behemoth38** [comment]
@Nedjohh , danke für die Hilfe. Aber ich denke mir stets etwas Besonderes aus. Schlüsseldatei und PIN waren neu beschafft.
Ich wurde erfolgreich angemeldet ! Drang vor bis zu einem Film, dessen Wiedergabe mit genannter Meldung verweigert wurde.
Ob ich  ein neues Problem aufmachen sollte ? Danke.
