### ISSUE TITLE
Kodi Netflix log in on andoid tab

### ISSUE THREAD

**Issue by srdjanmayer** [CastagnaIT/plugin.video.netflix#1687]
Hello,
   I have became a member of this forum recently, so I don`t know is there any word about log in kodi netflix addon on android tablet. I can`t watch Netflix on android app, because my Lenovo tab M8 is less and less supportive to a new uptades on Netflix. For Desney+ and other simmilar apps reproduction is much better on Kodi. So, I am wondering is it possible to log in Kodi Netflix on android:

  - I can`t find any NFAKey for Android. Is there any?
  - I was trying with linux key and android python. It `s inpossible.
  - Is there any tutorial how to login Kodi Netflix on android?
  
Thanks in advance.
     Srdjan

**Comment by cromefire** [comment]
You just need to get one on PC and then transfer it to your android device and import it from there (for example with a USB Stick and USB OTG). It uses browser automation, so you can't really do it on Android directly.
