### ISSUE TITLE
Invalid Pin on Windows and on Mac

### ISSUE THREAD

**Issue by xidius82** [CastagnaIT/plugin.video.netflix#1690]
### Netflix add-on version

latest

### Operative systems used

Mac OSX

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hi, hi have the last version of Castagna's plugin and last version of kodi, If i generate the Authenticator key and i execute this with the showed pin, kody says that the pin is incorrect. I also retry many times and generate other key with Windows and with Mac. Same result.

### Debug log - mandatory

s

**Comment by xidius82** [comment]
i tried also with a 19.5 version of kodi, same result

**Comment by CastagnaIT** [comment]
for sure you are writing a wrong PIN
since auth pin code works as expected

**Comment by xidius82** [comment]
> for sure you are writing a wrong PIN
> since auth pin code works as expected

@CastagnaIT  i have retried 6 times with different 6 auth key....

**Comment by dmnmsc** [comment]
I have this same issue. Tried several times with several generated keys. I always type the PIN protection given by the script. Fails in my FireTV.

**Comment by xidius82** [comment]
@CastagnaIT can you help us?

**Comment by dmnmsc** [comment]
> @CastagnaIT can you help us?

Worked fine after sending the file to my fireTV using adb.

Failed several times using Telegram to send the file to my mobile and using "easy fire tools" app afterwards to send the file to the fireTV.

**Comment by xidius82** [comment]
@dmnmsc thank you, it worked for me; i have pushed the key from adb. For the failed retries, i had uploaded the file in many host websites...
