### ISSUE TITLE
NF authentication not working

### ISSUE THREAD

**Issue by tyshiro** [CastagnaIT/plugin.video.netflix#1691]
### Netflix add-on version

V1.23.2+mateix.1

### Operative systems used

Android

### Kodi version used

Other (specify in description)

### Description of the bug

Using Cody 21 omega 
When logging in with NF authentication, it’s giving the following error.
WebsiteParsingError: 
E-mall field not found

### Steps to reproduce the behavior

1 - login with authentication key
2 - Password
3- Receive Error message

### Debug log - mandatory

2024-04-14 22:12:58.736 T:30228 error < general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed 2024-04-14 22:12:58.721 T:30381 error < general>: GetDirectory - Error getting plugin://plugin.video.netflix/ 2024-04-14 22:12:38.216 T:30228 info < general>: Loading skin file: DialogConfirm.ml, load type: KEEP_IN_MEMORY resources.lib.common.exceptions.WebsiteParsingError: E-mail field not found raise _data File careposury Skinit

### Screenshots

![image](https://github.com/CastagnaIT/plugin.video.netflix/assets/70737955/d3e6951d-b477-4fe1-98ba-2c7b52b38c58)

**Comment by CastagnaIT** [comment]
fix on new release

**Comment by tyshiro** [comment]
Thank you so much for all your hard work! It’s working great again!Have a fantastic day,KokimoSent from my iPhoneOn Apr 16, 2024, at 04:31, Stefano Gottardo ***@***.***> wrote:﻿
Closed #1691 as completed.

**Comment by tyshiro** [comment]
Hi there,Can you please help me out? Tell me how I could fix this problem, nothing is loading to play. I probably reinstalled the add-on seven times already and still cannot get anything to load.Please advise, thanks in advance!KrisSent from my iPhoneOn Apr 16, 2024, at 08:37, Kris Madhu ***@***.***> wrote:﻿Thank you so much for all your hard work! It’s working great again!Have a fantastic day,KokimoSent from my iPhoneOn Apr 16, 2024, at 04:31, Stefano Gottardo ***@***.***> wrote:﻿
Closed #1691 as completed.
