### ISSUE TITLE
MSLFehler: Email oder Passwort ist falsch

### ISSUE THREAD

**Issue by behemoth38** [CastagnaIT/plugin.video.netflix#1695]
### Netflix add-on version

Vers. 1.23.3+Matrix.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Nach Generieren eines neuen NFAuthentification.key, Anmeldung mit entspr. PIN und PW.
Meldung 'erfolgreich angemeldet'.
Bei dem Versuch einen Film aufzurufen, obige Meldung.

### Debug log - mandatory

http://pastę.kodi.tv/joguxujidi

### Additional context

Das Netflix PW stimmt nicht mit dem PW der Telekom überein (wäre absurd, ich weiß)

**Comment by Barri-G** [comment]
Same issue here

**Comment by behemoth38** [comment]
Hallo Barry-g, 
ich wusste der zusätzlich Kontext würde nur verwirren. Bei der Anmeldung von Netflix wird ein zu verifizieren des Mail-Account verlangt. Da ich Netflix natürlich nicht das PW des Kontos gebe stimmt das Netflix PW nicht mit dem T-Online PW überein.
Nur die Verzweiflung/Hilflosigkeit läßt solche Erwägungen zu. ;-)

**Comment by DarkMetatron** [comment]
Same issue with Kodi on Android TV (Mecool KM6 Deluxe) with Kodi 21.
Login with Key works but nothing plays and wrong email or password error is shown.

**Comment by behemoth38** [comment]
What means "unplanned closed" ? The Problem still exists. It seams, that only Android ist concerned. Ubuntu and libreelec do not run into an error. I am feeling disrespected by this uncommented Close of a problem.

**Comment by CastagnaIT** [comment]
no solutions
if someone is able to find one can create a PR to propose changes
