### ISSUE TITLE
Netflix not loading

### ISSUE THREAD

**Issue by tyshiro** [CastagnaIT/plugin.video.netflix#1696]
### Netflix add-on version

V 1.23.3+matrix.1

### Operative systems used

Android

### Kodi version used

Other (specify in description)

### Description of the bug

Kodi 21 Omega
Once I go into my Netflix add-on, I click onto a show that I want then it only stays on the loading process. It does not go any further will not open the show to play meaning it’s stuck on loading.  It’s stays on “please wait loading”. 

### Steps to reproduce the behavior

1- click on Netflix add on icon
2-Click on continue watching
3-Click on the show I want to watch
4-It says “please wait loading”
5-nothing happens it’s just stay on “Please wait loading.”

### Debug log - mandatory

It doesn’t give me a debug log on this

### Possible fix

Not sure how to fix it that’s why I’m creating a ticket. Thank you for all your hard work though. I really love this. Add on when it works.

### Additional context

https://github.com/CastagnaIT/plugin.video.netflix/assets/70737955/ec03a4ba-596e-42bc-a4ad-76099439f03e

### Screenshots

![IMG_8019](https://github.com/CastagnaIT/plugin.video.netflix/assets/70737955/15d6990f-39e2-4869-8b47-7d8bd580b9ff)
![IMG_8018](https://github.com/CastagnaIT/plugin.video.netflix/assets/70737955/6bae4ced-46cd-4af1-bdc6-0cecf11ad898)

**Comment by tyshiro** [comment]
Any update on fixing this? Thanks

**Comment by tyshiro** [comment]
Obviously, I really don't know what I'm doing, but all I know is it's not loading anything I want to watch and I have no idea how to fix it. I don't know if I did this log correctly either but here you go: https://paste.kodi.tv/ocovahufak

I hope this helps or you can tell me how I could fix why nothing is loading once I'm logged in. Thank you and I'm so sorry for bothering you. 🙏🏼

**Comment by Gujal00** [comment]
Cannot be fixed. The addon cannot be used on Android. Windows and MacOS platforms for now
https://github.com/CastagnaIT/plugin.video.netflix/issues/1627

**Comment by tyshiro** [comment]
Just curious, where does this add-on work now?Sent from my iPhoneOn Jun 13, 2024, at 17:59, gujal ***@***.***> wrote:﻿
Cannot be fixed. The addon cannot be used on Android. Windows and MacOS platforms for now
#1627

**Comment by Gujal00** [comment]
Works on linux and linux based LibreElec and CoreElec for now

**Comment by tyshiro** [comment]
ThanksSent from my iPhoneOn Jun 14, 2024, at 19:26, gujal ***@***.***> wrote:﻿
Works on linux and linux based LibreElec and CoreElec for now
