### ISSUE TITLE
Video freeze with Playback setting set to Auto

### ISSUE THREAD

**Issue by bwibwi13** [CastagnaIT/plugin.video.netflix#170]
Hello,

With some series, I experience video freeze on a Raspberry Pi 3.

When changing the [video playback setting in Netflix](https://help.netflix.com/en/node/87) to reduce bandwidth, freezes do not occur.
If i set it to auto, freezes are systematic with some series.

Should the auto mode be supported?
Can I do anything to help you spot the problem?

Thanks for your help :)

**Comment by CastagnaIT** [comment]
in the readme the start page explains the playback problems of RPI

**Comment by bwibwi13** [comment]
Ho sorry.
I missed that in the page.

Thanks a lot for the quick response.
And thanks a lot for this great plug-in :)

**Comment by bwibwi13** [comment]
My point is not that 1080p is not supported by RPI.
I am surprised that the system selects a resolution that is not supported.
Shouldn't it select a resolution it actually supports?

**Comment by Smeulf** [comment]
It's not a matter or resolution by itself. It's a matter of processor speed. The Pi3 is not powerful enough to decode more than 720p. Even at this resolution, you may have to limit the bandwidth to 3500000bps, or it may stutter.

Every system is different, so must be tuned manually.

**Comment by bwibwi13** [comment]
OK. I understand.
Thanks again for your help.
I'll look for the parameter and configure the system.
Thank you
