### ISSUE TITLE
issues while playing some titles 

### ISSUE THREAD

**Issue by Ahhydri** [CastagnaIT/plugin.video.netflix#1700]
### Netflix add-on version

1.23.3+matrix.1

### Operative systems used

Other (specify in description)

### Kodi version used

Other (specify in description)

### Description of the bug

while playing some titles the video starts normally and after 2 minutes of the play the video stops and then never continues. i tried multiple times but still the issue persists.

example title: Madame Web

I'm using kudi 21.0

### Steps to reproduce the behavior

select the title madame web and play
it will stop after  2 to 3 mins of playing

### Debug log - mandatory

There is no pop-up generated for logs during this issue

**Comment by Kampfader** [comment]
is the same https://github.com/CastagnaIT/plugin.video.netflix/issues/1678
