### ISSUE TITLE
No video plays on Batocera Linux

### ISSUE THREAD

**Issue by CrazyH2** [CastagnaIT/plugin.video.netflix#1703]
### Netflix add-on version

Latest

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When I successfully login and pick a movie it will not play. It comes up for about half a second with the playback controls and then gives an error dialog and logs this.

### Steps to reproduce the behavior

1. Install
2. Login
3. Click on movie

### Debug log - mandatory

https://paste.kodi.tv/lebatavifi.kodi

**Comment by CastagnaIT** [comment]
> 2024-06-18 06:35:13.340 T:2579    error <general>: AddOnLog: inputstream.adaptive: Initialize: Failed to load library: /userdata/system/.kodi/cdm/libwidevinecdm.so: DT_RELR without GLIBC_ABI_DT_RELR dependency
> 2024-06-18 06:35:13.340 T:2579    error <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/userdata/system/.kodi/cdm/libwidevinecdm.so)
> 2024-06-18 06:35:13.340 T:2579    error <general>: AddOnLog: inputstream.adaptive: PreInitializeDRM: OpenDRMSystem failed

this is not ISA bug, on linux arm64 you cant run widevine contents as is,
first you need to provide required library symbols to your OS

on wiki you can find some hints and links on how to solve
https://github.com/xbmc/inputstream.adaptive/wiki/Widevine-ARM64-support
here we cannot help more than this
