### ISSUE TITLE
Support for Kodi 18.9

### ISSUE THREAD

**Issue by swimm3r** [CastagnaIT/plugin.video.netflix#1704]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request

Please add support for Kodi 18.9 used in LibreElec 9 for Raspberry pi 3.

#### Describe the use case

Use of Raspberry Pi 3.

**Comment by CastagnaIT** [comment]
kodi 18 is too much obsolete framework also python version used is obsolete and not maintained
