### ISSUE TITLE
Addon breaks library scanner

### ISSUE THREAD

**Issue by conker-de** [CastagnaIT/plugin.video.netflix#1705]
### Netflix add-on version

1.23.3

### Operative systems used

LibreELEC

### Kodi version used

Kodi 22 (Omega)

### Description of the bug

Always if the netflix addon is activated it breaks the library scanner. There is a timeout error in kodi.log for themoviedb.org python script and no new content will added to the library. 

Library scanner works fine without error with netflix addon deactivated or removed.

### Steps to reproduce the behavior

1. Navigate to series
2. Choose any series (with new episodes)
3. Choose context menu
4. Search new content
5. Kodi is scanning, find new episode and run in timeout

### Debug log - mandatory

https://paste.kodi.tv/uxohetujiw.kodi

**Comment by CastagnaIT** [comment]
a shrinked log is not so useful show
however there are only themoviedb errors with no involved netflix addon

this addon dont perform any operation when not used,
the only operation that this addon could do in background is the sheduled library update,
but it needs to be enabled manually from addon settings however i dont see activity in the log

TimeoutError's have something to do with network problem
