### ISSUE TITLE
Update to v0.15.1 causes "Error parsing MSL encodable"

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#173]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
After updating to v0.15.1 I received the following error on screen:
```error
Netflix returned the following error:
Error parsing MSL encodable.
Error details have been written to the Kodi log file. If the error
message does not provide guidance on how to resolve the issue
or you continue to receive this error, to receive this error, please report it via GitHub.
Please provide a full debug log with your error report (enabled "Debug Logging" in Kodi settings).
```

And in the logs:
```log
2019-08-27 13:12:47.648 T:1672389488   ERROR: [plugin.video.netflix (0)] Mastertoken has expired
2019-08-27 13:12:50.891 T:1672389488   ERROR: [plugin.video.netflix (0)] Full MSL error information:
2019-08-27 13:12:50.891 T:1672389488   ERROR: [plugin.video.netflix (0)] {"entityauthdata": {"authdata": {"pubkeyid": "MSL_TRUSTED_NETWORK_SERVER_KEY", "identity": "Netflix"}, "scheme": "RSA"}, "errordata": "3yJpMlcm5hpGNvZGUiOjEwMDAwMCwibWVzc2FnZWlkIjoxLCJlcnJvcmNvZGUiOjEsImVycm9zbXNnIjopyB2IgcGFyc2luZyBNU0wgZW5jb2RhYMkLiIsInRpbWVzdGFtcCI6MTUkwNDM9MH0=", "signature": "et+ZCegsvD068lr8r3zkCUkAuT4sXp2e28txV29cpcrV43WWpp+/ORYGLEbLlvBo8mzzd8mZHa9lbbhgunaInEnPmP3cmH2//git41H1Yt2jyd+SCOGlXtjc+sRYhWudIP8e+bB+tvnpFwFVuq0XLnftDZKfOYp0b6ap2c8XcUJauWzLm/7QfQ0V1yPlxa65IbUIdb551pvnxWPPuQsCLSsFY+8PnbpgxeeVedWYGm37DwmEj2EFsCw0wlAXpXtes6V4xDXLZvVrjV640mVqHi2hvc6TfqBUUlQFL3ugMwtJjBaHceFFJs4lIYd/nRpWEGtII8jtA=="}
```

The errordata is scrambled on purpose.

### Addon version used

v0.15.1

### Description
See General Information

### Steps to Reproduce
Starting the addon after upgrade.

**Expected behavior:** [What you expected to happen]
It starts, like it did on my other Kodi box (identical build).

**Actual behavior:** [What actually happened]
It fails as reported.

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
LibreELEC 9.0.2 on Raspberry Pi.

## Debug log
TBD

## Other information
N/A

### Screenshots
N/A

**Comment by dagwieers** [comment]
Copying the msl_data.json from a working system to the non-working system did not help.
Then rebooting did fix the issue.

So I have a feeling that the upgrade process has a bug that may corrupt or uses old/invalid data.
What is also weird is that after a reboot I have to re-enter my credentials. Has been like this as long as I can remember.

**Comment by Smeulf** [comment]
> What is also weird is that after a reboot I have to re-enter my credentials

This is a normal behavior after 0.15.x update. We're now using a database to store the data. It should appears only once.

**Comment by rmellema** [comment]
Where can I find an `msl_data.json` from a working system? I only have kodi + netflix installed on one machine, do I cannot just grab it from a different one.

**Comment by Smeulf** [comment]
@rmellema try to enter the add-on, your credentials will be asked. Then restart Kodi or system, and try again. The issue should be solved.

**Comment by dagwieers** [comment]
@Smeulf You cannot enter the add-on. You have to "right-click" on the add-on and go to **Settings**, then you can update your credentials. However that did not work for me.

Also removing the `msl_data.json` did not work.

**Comment by rmellema** [comment]
I have restarted the system multiple times since re-entering my credentials, but it keeps throwing the same error as in the first post and the log data is also the same (except for the scrambled parts of course)

**Comment by Smeulf** [comment]
@dagwieers if credentials are not set, trying to enter the add-on will ask for them...

@rmellema please provide full debug logs

**Comment by dagwieers** [comment]
@Smeulf If you say so/ I am saying that it didn't help in my case. That's why I was looking to remove that file, and eventually fixed it by replacing it with the file on a system that was not affected.

**Comment by rmellema** [comment]
@Smeulf I turned on debug logging and reboot the system, and when kodi booted again the error popped up almost immediately. The debug log can be found here: https://pastebin.com/B4hT5agX

**Comment by Smeulf** [comment]
Is it a first install or an update ? I'd bet for a first install.

**Comment by rmellema** [comment]
It is from an update actually, I've updated from a different repository to this one a few months ago since the older one stopped receiving updates.

**Comment by Smeulf** [comment]
Can you try to rename 'settings.xml' to anything in the userdata/addons_data/plugin.video.netfix folder and try again?

**Comment by rmellema** [comment]
That solves the issue of not being able to log in, so I can now browse through the plugin again. Playback still does not work, since I get the same error as in #171, so that is probably related in some way.

I have the debug log, but pastebin won't let me upload it because it is to big for their site.

**Comment by Smeulf** [comment]
Now that you can login, just restart Kodi or the system, and the video should start.

**Comment by Smeulf** [comment]
> I get the same error as in #171, so that is probably related in some way.

Yes both issue are very related. It's a matter of ESN and encryption, but we'll fix it no doubt!
