### ISSUE TITLE
Cannot get this to work with a VPN??

### ISSUE THREAD

**Issue by riccy123** [CastagnaIT/plugin.video.netflix#180]
*I'm submitting a ...*
 bug report
  

General information

 Addon version used

latest  (.15.1)

Description

I cannot get a VPN to work with this addon- I have tried three different providers.
Find enclosed log when connected to a UK server - even though I am in the UK!
Problem does not exist when connecting to Netflix via browser, only with the addon?
[Description of the bug or feature]

 Steps to Reproduce

1. Connect to VPN server
2.Open netflix addon- gui appears, navigate to a film/show
3.When pressing play, play sign appears in top right , but then disappears, and video does not play.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

 Operating System

 Windows (x64)

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

 Debug log

https://pastebin.com/pQymHGm4

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Smeulf** [comment]
InputStream Adaptive: Download http://198.38.114.170/?o=AQOUTrkFeTSn0gkUb5_p6wVks_HH-otqg74r_iDf2yA3EXieYp_zjEyyArAJ5YnG_0l4kGDP11o0w6COwYLybldWRSuww9sdHUwLR-peB25Sjz3oFom2_x2zTtpDuN38W5-KEWXkwj5pLdDyPBVb-gBZIMVgeH_w7Q&v=5&e=1567147748&t=VH4fEN0fkWdBGV0_QmVtzskJQ2M failed with error: 420

Network (configuration most probably) issue, but can't say more.

The add-on seems to work fine as it gets the manifest and send data to InputStream.

We know it can work through a VPN, some already did with success.

I agree it's not helping a lot...

**Comment by CastagnaIT** [comment]
I follow kodi rules: https://kodi.wiki/view/Official:VPN_policy
however error 420 is a particular error almost certainly for the network configuration
