### ISSUE TITLE
Ca'nt connect with a VPN- AGAIN.

### ISSUE THREAD

**Issue by riccy123** [CastagnaIT/plugin.video.netflix#181]
*I'm submitting a ...*
 

Why is it that anyone using a VPN is treated like a pirate!!

I support Kodis  vpn policy, but as mentioned to their mods, don't tar everyone with the same brush.
I travel a lot, I have a UK subscription to Netflix.
I want to login to my Uk netflix from  different countries- I am having no success using this plugin.
I provide logsand report an error-  and all I get back is- it might be a network config!!
The case is then closed
I use a VPN
I wont Bite
I AM NOT A PIRATE.

Jeez

**Comment by Smeulf** [comment]
@riccy123

1st, try the add-on without a VPN when at home. I'd bet it will perfectly work.

2nd, the 420 error is a response from the server, saying it a network related error. The streams are correctly sent to InputStream stream but the server refuses the connection, most probably because it detects the VPN.

3rd, nobody said you're a pirate, just saying Kodi policy is not to use one.

4th, we're just a very few people working on this addon, and we can't even if we want try every situation for every hardware with every internet provider or solutions (VPN, proxies, or whatever).

There's no obvious error in the logs unless the 420, so it is as said most probably a network error. And please stop screaming!

**Comment by riccy123** [comment]
Thank you for taking the time to provide a little more info- I wish Kodi devs could be as helpful
Yes- the addon does work at home without the VPN
When I  connect at home ( UK ) to a UK server- no video.
From your reply , it would appear Netflix will not respond to my VPN, even though it is set to a server from the the same country.

Aplogies for shouting

**Comment by Smeulf** [comment]
So definitely a VPN issue, and there's nothing we can do to help, we're not specialized into VPN.

We're not Kodi either btw, just a few people trying to maintain this addon on their free time...

**Comment by riccy123** [comment]
Sorry Smeulf, - but did you read my edited version?

Surely this suggests otherwise?

Btw your free time is greatly appreciated

**Comment by Smeulf** [comment]
If it works with Chrome, it *should* work with the add-on.

Microsoft EDGE is using a different way. So depending on the browser it's possible it work with one and not with an another, or the add-on.

Most probably, it's a configuration issue on your computer regarding Kodi.

And if it's not, then there's nothing we can do now to make it work as there's nothing in the logs to help us but the 420 error.

**Comment by riccy123** [comment]
Thanks for replying.

Deeper into the rabbit hole-----

Never used Chrome - or Edge, but nevertheless, downloaded Chrome, and tried Edge.

Both work accessing Netflix website without  - AND WITH -  vpn
I have several pc's at home and all have no custom configurations, and all show the same behaviour?

Ah well - Have a nice day/evening, depending where you are (  if you can point me in the direction of a group/forum that might be able to help, I'd be grateful)
As mentioned, Kodi forum don't want to know
Cheers
Keith

**Comment by CastagnaIT** [comment]
This addon follow kodi rules: https://kodi.wiki/view/Official:VPN_policy
Don't keep asking for VPN requests here

**Comment by lpuglia** [comment]
I feel you on this, i have the exact same problem on the Pi3/4.
`inputstream.adaptive` has not problem by itself with vpn. In fact i can use vpn with other plugins without any problem. My guess is that Netflix has some code in place that makes `intputstream.adaptive` leaks during connection/hand-shake, a leak that doesn't happen in chromium.
