### ISSUE TITLE
Superfluous code?

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#183]
I can't find any reference to this SaveStreamSettings class. I think it's a former version of StreamContinuity. Can you confirm? If so, I'll remove it in a future 'CodeCleanup' PR.

https://github.com/CastagnaIT/plugin.video.netflix/blob/dd8bc57fd116c5279e3016a0e1e7f8eabf35600e/resources/lib/kodi/ui/xmldialogs.py#L67

**Comment by CastagnaIT** [comment]
mmh yes it seems to me the old implementation that was used with the request dialogue to save the current change of language or subtitles, it should be dead

**Comment by CastagnaIT** [comment]
you can delete this code, so we can close this issue
