### ISSUE TITLE
1080p works on one account, doesn't on second

### ISSUE THREAD

**Issue by 23doors** [CastagnaIT/plugin.video.netflix#185]
#### Your Environment
- Netflix add-on version: 0.15.2
- Operating system version/name: Ubuntu / Mac (tested on both)

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [X] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

Got an account on Premium Ultra HD plan. 1080p wasn't working for me so I tried my friend's account (also Premium Ultra HD) - aaand it works there. Same settings, same everything, same episode, just logged out and logged back in with new creds. Tried going back on forth - always the same.

Logfile from account that doesn't work with full hd:
https://pastebin.com/zQ3MH1sU

Logfile from account that does work with it without issues:
https://pastebin.com/DngeSSTJ

I am completely boggled by what's causing it.

Account works just fine e.g. through ChromeCast.

**Comment by Smeulf** [comment]
Did you try this? https://github.com/CastagnaIT/plugin.video.netflix#it-only-plays-videos-in-480p720p-why-is-that

**Comment by CastagnaIT** [comment]
the logs are not very clear too many operations done since kodi started however i dont see nothing rilevant thing
it is a strange behavior which i don't find any logical meaning
i don't know what to tell you at the moment
are you sure you still have a Premium account? for safety recheck

**Comment by CastagnaIT** [comment]
also check that your video resolution is at least 1920x1080

**Comment by Smeulf** [comment]
> are you sure you still have a Premium account? for safety recheck

For the record, no need of a Premium account to get 1080p. I do have a standard account and 1080p is avaliable.

Basic = 480p max / 1 screen simultaneous
Standard= 1080p max / 2 screens
Premium = 4K / 4 screens

**Comment by 23doors** [comment]
@Smeulf I did. And it works fine on one account, doesnt on another one.

@CastagnaIT I only put there logs starting just before re-log to another account. I am sure about Premium, triple+ checked ;) And I am using that account right now on Chromecast with 1080p just fine. Resolution is 1920x1080, as I said, everything works with one account. Relog to 2nd -> doesnt work. Relog to 1st -> works.

It seems that in logs I get 20 streams from account that doesnt work, and 32 streams for another for CDVDDemuxClient. Dunno if this is of any meaning. When I set stream selection to Manual, full hd streams are not even there for that 1 account.

I also tried a 3rd account - one on Standard plan. Everything works fine there as well. So it's just that one account with weird behavior.

I should have a Shield TV to test it with tomorrow, maybe with Android ESN it will behave differently.

**Comment by Smeulf** [comment]
@23doors Can you exit Kodi, rename the  plugin.video.netflix folder (not delete so we can restore it after for more tests if needed)  in userdata/addon_data, and restart Kodi?

This will reset the add-on settings as for a first install. Then try with the problematic profile again please.

I wonder if something in the settings can cause this...

**Comment by 23doors** [comment]
@Smeulf renamed, logged back in, disabled hevc as I am on macos and with it on no videos work, tried some episode thats available in 4k - got only 2 streams, both are h264 768x432 with different bitrate.

**Comment by Smeulf** [comment]
Ok....... Let's try something else please.

Exit Kodi, delete the newly created plugin.video.netflix folder, and restore the previous one.

Then backup the settings.xml file inside anywhere you want. Once done, edit settings.xml in the plugin.video.netflix folder, and remove the line "esn" if it exists (if not existing then tell me please).

And then, try the add-on again.

I'm sorry beein so 'directive' but I don't know how much you know Kodi or the add-on ;)

**Comment by 23doors** [comment]
esn exists there, default value:
`<setting id="esn" default="true"></setting>`
started gain, same result. esn default=true was re-added to settings.xml as well

**Comment by Smeulf** [comment]
Same result? You mean only 2 streams?

I thought it was something like 9 before...

**Comment by 23doors** [comment]
Never said I have 20 streams in UI. But there is a mention of 20 streams in logfile. I can choose between 2 streams in UI. On 2nd account: 32 streams in logfile, I can choose from 7 streams in UI.

**Comment by Smeulf** [comment]
Ok now I understand you're stucked at 480p.

Let's think:
- It's not addon related, as it's working with an another account
- So it's account related... But not account plan as you can get 1080p elsewhere.

It can be related to the main profile settings.

In your browser, login to Netflix, and select the main profile (not yours, the MAIN one, I think it's rdobro45 from logs).

Then go to 'account' and in 'Playback settings' in the 'My Profile' section. Try with 'auto' or force it to something else if it's not working with 'auto'.

If at the end it's still not working, then I fear I can't understand what's going on. You can still try to force your profile, but the way the add-on is built, it shouldn't change anything.

**Comment by 23doors** [comment]
@Smeulf you were right! That was it If I change playback settings on main profile - it works just fine. Is this something that can be fixed somehow though? As main profile prefers to use low quality for playback as he's usually on his phone anyway.

**Comment by Smeulf** [comment]
This is an issue we're aware of and related to https://github.com/CastagnaIT/plugin.video.netflix/issues/167 

We're trying to change that behavior, but for now we couldn't find how. If you have any idea btw, help is always welcome ^^

@CastagnaIT if you can take a look on hangouts, I have a pending question regarding the issue. Thanks.

**Comment by Smeulf** [comment]
> As main profile prefers to use low quality for playback as he's usually on his phone anyway.

Setting it to auto should use the best quality regarding the phone resolution. Not perfect I agree, but that's all I have for now

**Comment by 23doors** [comment]
Don't know much about netflix "API". But as manifest is skipping some streams already, it must already know which profile it is for. There are no unique per profile GET params so I thought it's in cookies.

Switching profile sets: NetflixId, SecureNetflixId, memclid, nfvdid. I tried passing these cookies to manifest call - didn't change anything. And they are not required for main profile anyway. So maybe something in MSL request points to specific profile?

I tried dumping MSL requests from the browser but I wasn't able to get RSA key and couldn't see actual payload to check for any differences when requesting manifests from different profiles.

**Comment by Smeulf** [comment]
@23doors same here :((

**Comment by 23doors** [comment]
Tried debugging scripts to console.log MSL requests - and still nothing there profile-specific. ESN doesn’t change. In scripts there are some references to MSL_PROFILE_ID (if I remember right) in app local storage and API calls with action=regdevice that includes profile id during profile switching but I wasn’t able to capture any calls like that. Maybe there is something to pursue.

**Comment by CastagnaIT** [comment]
Closed for inactivity
