### ISSUE TITLE
Widevine update: "TypeError: execv() arg 2 must contain only strings"

### ISSUE THREAD

**Issue by JohannesZwart** [CastagnaIT/plugin.video.netflix#188]
#### Your Environment
- Netflix add-on version: 0.15.2
- Operating system version/name: OSMC/Kodi 18.3
- Device model: Vero 4K+

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

Hi,

When running Netflix yesterday, a message appeared indicating Widevine needed updating. Upon doing that, I got the message:

"TypeError: execv() arg 2 must contain only strings"

I have absolutely no clue as to what could be the problem here... Tried rebooting, reinstalling, etc. Didn't clear anything up...

Log file can be found here: https://paste.osmc.tv/omayutamaf 

Hopefully that helps. Hope to hear from you guys!

**Comment by Smeulf** [comment]
Update InputStream helper to 0.4.2 will solve your issue.
https://github.com/emilsvennesson/script.module.inputstreamhelper/releases

**Comment by Smeulf** [comment]
Same as 

https://github.com/CastagnaIT/plugin.video.netflix/issues/187

emilsvennesson/script.module.inputstreamhelper#146

**Comment by JohannesZwart** [comment]
Works, thank you!
