### ISSUE TITLE
Default audio in some TV-Series not working correctly

### ISSUE THREAD

**Issue by nt74** [CastagnaIT/plugin.video.netflix#189]
#### Your Environment
- Netflix add-on version: 0.15.2
- Operating system version/name: Open Source Media Center 2019.07-1
- Device model:  ARMv7 Processor rev 4 (v7l)

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Some TV-series defaults to German audio when my Kodi system language settings are set to Swedish.
One series that I can give as an example of this behavior is Greanleaf.

#### Installation
Through the recommended repo on your github.

**Comment by Smeulf** [comment]
I remember that issue from ascidisco repo, the default stream was always German, in "Outlander" as an example.

Maybe because there's no default flag on the manifest and then it uses the first track avaliable?

Must be checked.

**Comment by Smeulf** [comment]
@nt74: 

- What's your prefered audio language? Original?
- Can you post a screenshot of the audio track selection while playing an episode?
- Is it with some specific episode or all? I couldn't reproduce the issue with S01E01.
- Did you already see that episode? If yes, it's possible Kodi remembers the tracks used and then override the system settings with the file settings.

**Comment by CastagnaIT** [comment]
the debug log and manifest.json from addon data folder after played the episode it would be useful
if there will be no response in the coming days, the issue will closed
