### ISSUE TITLE
Fixed PL file

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#19]
As my knowledge github, however, is too weak and I make a lot of clutter, I am sending an improved strings.po file for Polish.
[strings.po.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/2948396/strings.po.txt)

Once again, I'm sorry ... The first time went quickly, the second time worse;)

**Comment by CastagnaIT** [comment]
fix merged
