### ISSUE TITLE
KeyError: mylist

### ISSUE THREAD

**Issue by nokodi** [CastagnaIT/plugin.video.netflix#20]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

Can't navigate through the Netflix navigation. For example when I go to "Recently added" a popup appears with an addon error message KeyError: mylist

### Addon version used

0.14.0~beta22

### Description

Can't navigate through the Netflix navigation. For example when I go to "Recently added" a popup appears with the an addon error message KeyError: mylist
This only happens in my profile. If i switch to my wife's profile, I can browse the Netflix navigation and watch movies.

### Steps to Reproduce

1. Launch Netflix addon
2. Select my profile (we have four profiles)
3. Select any of the sub navigation items, for example "Recently added"

**Expected behavior:** Content of the sub navigation should be displayed.

**Actual behavior:** Popup appears with Addon Error. KeyError: mylist. Content of the sub navigation is not displayed. --> Can't select a movie to watch...

## Context (Environment)

Raspberry Pi 3
LibreElec 9.01
Kodi 18.1

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec 9.01
Kodi 18.1

## Debug log

https://pastebin.com/2TLwGzcP

**Comment by nokodi** [comment]
It seems like this error occurs when "my list" is empty...
I logged in to Netflix in my web browser, added a movie to "my list", switched to Kodi and now navigating through the Netflix addon navigation works...

**Comment by CastagnaIT** [comment]
Fixed in the latest DailyBuild
