### ISSUE TITLE
Get rid of Enum

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#204]
### Describe your request
So I would like to discuss replacing enum with something simple.

Currently the issue is that Python 2.7 requires another enum module (enum34) that fails for Python 3.4+ (Which ships with enum by default). So if we add it as a dependency, and it is pulled in, enum fails to work on Python 3 (3.4+).

For the time being I added it to our own tree as **enum34** so there's no conflict and we can do:
```python
try:
    from enum import Enum
except ImportError:
    from resources.lib.enum34 import Enum
```
But honestly, we use it for a very simple case (*resources/lib/database/db_utils.py*) where we could come up with something else.

I do like enum from my C years and it's nice it is part of Python, but as long as we are using Python 2, I don't think it is worth the trouble.

**Comment by dagwieers** [comment]
This is related to #198

**Comment by Smeulf** [comment]
> But honestly, we use it for a very simple case (resources/lib/database/db_utils.py) where we could come up with something else.

A fast analysis: That would mean add 6 methods to `db_shared.py`, 1 get and 1 set for each property, and make `get_tvshow_property` and `set_tvshow_property` private.

Also `get_tvshows_id_list` needs to be refactored, as for now we can filter agains one of the field.

Also it means adding new methods every time we may add a new field in the table, and that will make maintenance a little more complicated.

Just exposing facts ;)

**Comment by dagwieers** [comment]
@Smeulf The idea is that we replace it with something that offers the same functionality. Python didn't have Enum for 20 years and people were able to do what they did, maybe not as convenient as Enum. That said, we could keep it included as-is (as enum34 for Python 2) but I am not certain this will be accepted...

**Comment by Smeulf** [comment]
@dagwieers I'm not a Python expert, so I'll have a close look on the code once done, and learn from that!

**Comment by CastagnaIT** [comment]
why should it not be accepted?
it is pure python from official source other addon use enum module..
I don't see any problems with the list of rules to be respected

**Comment by dagwieers** [comment]
The problem is that if the module would be accepted, it only works on python 3.3 and older, but breaks python 3.4+ if it is available. Kodi does not have a way to say some requirement is only needed on older python versions.

So if you have Python 2, if it is installed it works, but if not we fail.
And on Python 3.4+, if it is installed it fails, but if not it works.

**Comment by Smeulf** [comment]
What if using sys.version_info?

**Comment by dagwieers** [comment]
I don't see how that would help, but feel free to test it first and come up with a solution.
My current solution is to ship it as enum34 and that's IMO the best option.
But given we don't really use the functionality big time, I'd rather get rid of it, it's not crucial to the function of the add-on.

**Comment by Smeulf** [comment]
I forgot you have it now as a required module... So indeed sys.version_info can't be used in this case.

**Comment by dagwieers** [comment]
We now include it as part of our code, which I don't think we should do. Because the code doesn't follow PEP8 and others, but also because when Retrospect did this, the plugin was not accepted and it needed to be "packaged".

**Comment by Smeulf** [comment]
Does 3 simple public constants of a class could replace the enum in our case?

**Comment by CastagnaIT** [comment]
Module deleted with #211 pull request
