### ISSUE TITLE
Entity used incorrect user authentication data type.

### ISSUE THREAD

**Issue by trilias** [CastagnaIT/plugin.video.netflix#209]
#### Your Environment
- Netflix add-on version: 0.15.2
- Operating system version/name: LibreElec 9.1.501
- Device model:  Old Toshiba Notebook and a Raspberry Pi 2

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

Since yesterday Play nothing always the same error on Video start Entity used incorrect user authentication data type. on Pi and x86 
#### Expected behavior

Play Videos
#### Actual behavior

Instant Error on Video start
#### Steps to reproduce the behavior

1. Start LibreElec
2. Start Netflix Addon
3. Go to Video and start it

### Debug log

The debug log can be found here: 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3603742/kodi.log)

### Additional context or screenshots (if appropriate)
![20190912_062422](https://user-images.githubusercontent.com/34447044/64754809-21dcba80-d529-11e9-8b3b-76cba5fdc446.jpg)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by nouman8** [comment]
same error on my end as well.

**Comment by mattreecebentley** [comment]
Same here, Win10, Kodi standard release, using the Castaetc Repo.
Logs into account fine, shows movies fine, won't play movies, gives the same error.

**Comment by easycool** [comment]
Hello...
Same for me on RPI3 whith kodi 18.2, using the Castanait Repo.
All ok but cant read video.

**Comment by easycool** [comment]
Hello everyone, it works again for me ...
I did not change anything...
Probably a problem inherent to netflix ...
I think that may come back ...
Thank you all and the addon creators to be on the spot to help us ...
Sorry, it's a google translation ..
I am French...

**Comment by StyleHack** [comment]
My problem hasn't solved itself yet.
[#207 ](https://github.com/CastagnaIT/plugin.video.netflix/issues/207)

**Comment by CastagnaIT** [comment]
it seems that this time it was netflix fault and it solved the problem
also on my part everything works well

**Comment by maxence59110** [comment]
For me it s ok
I don t reboot

**Comment by nouman8** [comment]
Fixed for me as well.
Off topic : can rpi4 play netflix 1080p smoothly ?.

**Comment by dagwieers** [comment]
Off topic: Yes

**Comment by eX00r** [comment]
Hey folks,

I get the same error and unfortunately nothing changed after updating to the latest version of the addon 0.15.5. Do I need to reinstall anything else than the netflix addon itself?
