### ISSUE TITLE
TypeError while searching

### ISSUE THREAD

**Issue by nokodi** [CastagnaIT/plugin.video.netflix#21]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

TypeError while searching

### Addon version used

0.14.0~beta22

### Description

When fire up a search, a popup appears displaying an error message TypeError: unsupported operand types(s)

### Steps to Reproduce

1. Start Netflix addon
2. Select profile
3. Select "Search" --> Search dialog appears
4. Enter search term and hit "Ok"

**Expected behavior:** Search results should be displayed

**Actual behavior:** Popup with error message appears TypeError: unsupported operand type(s). No search results...

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Raspberry Pi 3
LibreElec 9.01
Kodi 18.1

## Debug log

https://pastebin.com/82fpgYfG

**Comment by CastagnaIT** [comment]
Please install latest dailyBuild http://www.mediafire.com/file/mob2zj025z6bcdj/plugin.video.netflix_20190308build2.zip/file
After, if the error persist, i need the full log with kodi debug active, this is totally not very useful

**Comment by nokodi** [comment]
The problem still persists... but not with all profiles. It seems it is dependent on the profile... Maybe a caching issue? We have four profiles and search works in one profile but not in the other.

Here is the debug log for the search term "batman"
https://pastebin.com/1HivF59q

**Comment by CastagnaIT** [comment]
interesting details, i'll give it a try

**Comment by CastagnaIT** [comment]
I need you to install this modified version for debugging, 
and then send me the new log with active debugging.
so I can probably solve your problem.

[plugin.video.netflix_DEBUG.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/2975548/plugin.video.netflix_DEBUG.zip)

**Comment by nokodi** [comment]
Cannot reproduce it... Now search works with all profiles. Strange...
