### ISSUE TITLE
Profiles management at logon/logoff (low priority)

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#210]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [X] change an existing feature

### Describe your request
I'd like to submit 2 enhancements to the profile management.
At logout, profiles, profiles config, and all related data with the profiles are not deleted fr om the database => We could ask if the user wants to delete them and perform the cleanup.

At login, if I read the code well, every profiles not related to the current user are deleted, with the related data. We shouldn't if the user wants to keep them.

#### Describe an alternative
A warning in the readme about loosing data when connecting with an another profile, i.e. for some test. And encourage people to save their data before performing such operation.

#### Development tips
A bit tricky, as we may need to associate every profile with an account. And maybe it's not a good idea... Discussion opened.

**Comment by CastagnaIT** [comment]
I realized too late that the profile account association was missing
it would be interesting to add a multiple account management
but it would start to become difficult to manage everything, for something that might be used by one or two people...

i think that the simplest thing (as you said) is to ask to user what to do before logout (only first time)
and save the preference, so make it configurable in expert settings if an user want to change behaviour after the choice

**Comment by CastagnaIT** [comment]
Forgot that this cause a big problem with profiles
the profiles of other account will showed also in other accounts...

**Comment by CastagnaIT** [comment]
you could just do that for those who want only to logout, so then re-login with same account (eg. only because a person doesn't want others to enter... and not to use netflix addon with multiple different account)

**Comment by Smeulf** [comment]
Am I correct if I say "the profile list is built at every addon start (for any route)"?

If yes, then it means the only data we may want to keep are the ones in the shared database for stream continuity.

Is there any other data for a profile we may keep?

**Comment by CastagnaIT** [comment]
not all routes, and not at every addon py execution,
updating profile data occurs first start and when the login has expired
at least that should work...

currently stream_continuity is in table relation with profiles for delete/update actions
yes, it is the only user data that is automatically deleted

**Comment by CastagnaIT** [comment]
at the end all profile data is restored at login
no other data is deleted,
We do not save anything in the profile tables, it is only for convenience of retrieving data

**Comment by CastagnaIT** [comment]
i close this issue, the loss of stream continuity data at logout it's not a big loss
i can however add a warning message
