### ISSUE TITLE
Widevine DRM is unfortunately not available on this system

### ISSUE THREAD

**Issue by TheProgramableTurtle** [CastagnaIT/plugin.video.netflix#215]
## Bug report
2019-09-15 20:07:20.768 T:2669671152   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 109, in <module>
                                                route(filter(None, g.PATH.split('/')))
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 50, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 70, in route
                                                player.play(pathitems=pathitems[1:])
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 287, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 57, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 103, in get_inputstream_list$
                                                raise InputstreamError('inputstream.adaptive is not available')
                                            InputstreamError: inputstream.adaptive is not available

#### Your Environment
- Netflix add-on version: 0.15.2
- Operating system version/name: Rasbian Stretch Lite
- Device model:  Raspberry Pi Zero

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

When running the Netflix Add-on, I am able to navigate to any programme, but when I try to watch it it gives the error message "Widevine DRM is unfortunately not available on this system". 

#### Expected behavior

Presumably, the video should begin to play.

#### Actual behavior

The add-on gives the above error message.

#### Steps to reproduce the behavior

1. Open the add-on installed on a Raspberry Pi Zero running Kodi for Rasbian Stretch Lite.
2. Login to Netflix and navigate to a TV show or film.
3. Click to watch the programme or film.

#### Possible fix

Installing Widevine DRM?

### Debug log

I have followed the instructions, but the Kodi Logfile Uploader does not work and I cannot access the file system via anything but ssh. If the entire log is required I can copy and paste from the command line nano tool. 

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by zjoasan** [comment]
The Pi Zero is armv6l. This is not supported, as Widevine libraries are not available for this architecture

**Comment by Smeulf** [comment]
Please, can you enable debug, reboot your system, try to play a video again, and post full log? I'd like to check something. Use paste.kodi.tv to post your logs, do not copy the log here.

**Comment by TheProgramableTurtle** [comment]
I got as much as I could with copy and paste, I think this shows the log from the final button press. 
https://paste.kodi.tv/imuciqodic.kodi
Thanks for the quick reply

**Comment by TheProgramableTurtle** [comment]
I also noticed that you have to reenter the email and password each time you open the program, not a huge issue but thought it might be worth mentioning.

**Comment by Smeulf** [comment]
I need the full logs. I need to know what are the extensions installed. From the issue template: "- Do NOT CUT the log".

So if the logs are still cutted, we won't be able to help you and close the issue. Your choise :)

**Comment by TheProgramableTurtle** [comment]
I found another way to copy the log. This is the full one:
https://paste.kodi.tv/lenivivamo.kodi

**Comment by Smeulf** [comment]
Ok thanks!

First, as I guessed, you miss "InputStream Adaptative". But even if you can find it, @zjoasan is right, Windevine is not supported for ARM V6.

See log: `[script.module.inputstreamhelper-0.4.2]: Unsupported Widevine architecture found: armv6`

So I'm sorry but you won't be able to make it work on your Pi0.

**Comment by TheProgramableTurtle** [comment]
Oh well, that's a shame. Thank you very much for the help though!

**Comment by Smeulf** [comment]
> that's a shame

Well, google choice...
