### ISSUE TITLE
smart-download

### ISSUE THREAD

**Issue by nahemoth33** [CastagnaIT/plugin.video.netflix#216]
#### Your Environment
- Netflix add-on version: 0.15.3
- Operating system version/name: raspbian stretch
- Device model:  RaspberryPi 3B+

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

Is it possible to pre-download files like in the Netflix Android App?
My bandwith is to low for directly watching streams. I need to download the file before watching it.

**Comment by yoshimo** [comment]
https://kodi.wiki/view/HOW-TO:Modify_the_video_cache doesn't work here?

**Comment by nahemoth33** [comment]
I think, that's not the solution I'm searching for. I wan it to download the file I'm watching and, if possible, the next Episode if it's a series. My bandwith is to low for watching streams :-/

**Comment by Smeulf** [comment]
For the record: https://help.netflix.com/en/node/306

You shoud setup InputStream max resolution regarding your bandwidth.

I'm aware this is not an anwser to the main question.

**Comment by nahemoth33** [comment]
The android Netflix app, for example, is downloading the whole episode, so I can watch it offline. It would be nice, if such a feature would be supported by the plugin.

**Comment by CastagnaIT** [comment]
this function will not be implemented
it's not just about saving an encrypted stream here

**Comment by yoshimo** [comment]
Isn't it still using widevine and asking the License-Server for help with decryption  regardless of the source? Is it more than just "even more work required" that blocks this?
