### ISSUE TITLE
Audio & subtitles working but no video netflix v0.14.0~beta22 

### ISSUE THREAD

**Issue by JanV123** [CastagnaIT/plugin.video.netflix#22]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General information
Sound and subtitles work but there is no video. Video is all black.

### Addon version used
v0.14.0~beta22

### Description

Just installed the latest beta22 today Mar-13-2019. When selecting a series or movie, the sound and subtitles work fine but there is no video. Video is all black.

### Steps to Reproduce

1. Run Netflix for Kodi App
2. Select Netflix User account
3. Choose Movie/TV Series
4. Play Movie/TV Series

**Expected behavior:** [What you expected to happen]
Video, Audio and Subtitles work correctly.

**Actual behavior:** [What actually happened]
Audio and Subtitles working immediately. Video is all black.

## Context (Environment)
Windows 10 Pro x64
AMD Ryzen 5 2400G (Latest Vega 11 Graphics Driver installed)
16GB DDR4 RAM
Panasonic VT60 Plasma TV (1080p)
128GB Samsung 840 Pro
Gigabit ethernet to FreeNAS storage (28TB)
 

### Installation

* [ x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment
Youtube works fine including 1080p and beyond. Inputstream installed.
Dependencies should be installed unless i missed something?

## Debug log

Click [here](https://paste.kodi.tv/vafuqofaja) for logs

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/) or [https://pastebin.com/](https://pastebin.com/)) or similar, please do not paste]

## Other information

Originally had the asciidisco Netflix on Kodi 0.13.22 plugin installed using repo. Could not get it to work as when I click on a video nothing happens at all (tries to load but nothing happens). I uninstalled that and installed from this repo (download and installed from zip). 

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment]
reading the log seen not related to addon seem a wrong configuration of kodi, or a problem with kodi and your graphics card

The only thing I can make you try is:
If you have changed the InputStream Settings:
-Disable Override HDCP
-Enable automatic stream selection

In the Netflix Addon if is enabled, then turn off Force HDCP 2.2 in expert settings

**Comment by CastagnaIT** [comment]
Am i about to close this issue, any news?

**Comment by JanV123** [comment]
> Am i about to close this issue, any news?

Unfortunately no progress. I installed new AMD drivers but still no progress. Last thing I haven't tried is to reinstall Kodi.

**Comment by Smeulf** [comment]
In settings/player/videos, is OMXPlayer acceleration is enabled ? If yes, you can try to disable it.

Just keep MMAL acceleration.

I had this problem on a Rapsberry PI, maybe it's the same with Windows 10.

**Comment by JanV123** [comment]
> In settings/player/videos, is OMXPlayer acceleration enabled ? If yes, you can try to disable it.
> 
> Just keep MMAL acceleration.
> 
> I had this problem on a Rapsberry PI, maybe it's the same with Windows 10.

Unfortunately Kodi on Windows 10 does not have OMXPlayer in it's videos setting. I did try to disable "Allow hardware acceleration - DXVA2" but it did not resolve the issue.
![image](https://user-images.githubusercontent.com/13656971/55301322-95ed3f80-546e-11e9-9637-411646fa0eb2.png)

**Comment by JanV123** [comment]
Interestingly enough I have just discovered that some of my low quality videos that are locally available (480 and non-HD) do have playback issues. The issue is the same as the one i'm experiencing in the Netflix plugin where only audio and subtitles work and video is all black. This may be related to it. I do not have any issues with any HD videos though.

**Comment by Dnkhatri** [comment]
> Interestingly enough I have just discovered that some of my low quality videos that are locally available (480p and non-HD) do have playback issues. The issue is the same as the one i'm experiencing in the Netflix plugin where only audio and subtitles work and video is all black. This may be related to it. I do not have any issues with any HD videos though.

What kodi version are you using there have been many bug fixes for the kodi video player in the last month for 18.2 nightlies  try one of the latest nightlies it might fix your problem

**Comment by JanV123** [comment]
> > Interestingly enough I have just discovered that some of my low quality videos that are locally available (480p and non-HD) do have playback issues. The issue is the same as the one i'm experiencing in the Netflix plugin where only audio and subtitles work and video is all black. This may be related to it. I do not have any issues with any HD videos though.
> 
> What kodi version are you using there have been many bug fixes for the kodi video player in the last month for 18.2 nightlies try one of the latest nightlies it might fix your problem

I am using latest 18.1 stable release.

**Comment by jakermx** [comment]
It is not Netflix Addon issue, it is codec related issue, AFIK it could be resolved disabling  "Override HDCP" in Input Stream Adapter Settings  and enabling automatic stream selection, I would reccomend to set a Bw limit as well

**Comment by jakermx** [comment]
Dont enable Ignore Display  Resolution, and be sure you have sync and your audio source is configured correctyly

**Comment by JanV123** [comment]
> It is not Netflix Addon issue, it is codec related issue, AFIK it could be resolved disabling "Override HDCP" in Input Stream Adapter Settings and enabling automatic stream selection, I would reccomend to set a Bw limit as well



> Dont enable Ignore Display Resolution, and be sure you have sync and your audio source is configured correctyly

I've tried the above and it's still not working for me unfortunately.

**Comment by jakermx** [comment]
ok

Let's do something...

Uninstall KODI, delete Program Files KIdi dir and AppData\Roaming\Kodi  dir as well

then

Download this file
http://mirrors.kodi.tv/releases/windows/win64/kodi-18.1-Leia-x64.exe and once done, install it, then configure the minimal ooptionns, then , disable system update and add on updates, then install input stream adaptive... restart and get the log
Once done install pluging from zip, I would suggest download it again

https://m.mediafire.com/folder/tnu4623j66c66

then install from zip the netflix addon
once done... wait 5 mins and then restart...then go addons netflix ... type your credentials, wait for succesful login, and browse for a title... It should work
if not, share your complete log pls
