### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by deboshond** [CastagnaIT/plugin.video.netflix#224]
[Hello,](url
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3642964/kodi.log)
)

I am running retropie 4.5.1. with Kodi 18.2
I installed the netflix addon 0.13.23 , whenever I start it I get the message: netflix error
When I go to settings I can browse all settings, I can not choose logout, then I get the same error. It I never get the popup for the login screen. I have already removed the addon and reinstalled it, with the same effect. I am not sure how I extract the logfile for this addon, I hope attached kodi.log is all that is needed.?

**Comment by notoco** [comment]
Install stable version from this repo. It's 15.3 for now.

**Comment by deboshond** [comment]
Oooops, I am far behind. I will install the latest version and report back. Thx.



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: notoco <notifications@github.com>
Datum: 23-09-19 18:26 (GMT+01:00)
Aan: "CastagnaIT/plugin.video.netflix" <plugin.video.netflix@noreply.github.com>
Cc: deboshond <bas@greydanus.net>, Author <author@noreply.github.com>
Onderwerp: Re: [CastagnaIT/plugin.video.netflix] can not login (#224)


Install stable version from this repo. It's 15.3 for now.

**Comment by deboshond** [comment]
Unforunately the same behavior. Any ideas?



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Bas Greydanus <bas@greydanus.net>
Datum: 23-09-19 19:52 (GMT+01:00)
Aan: "CastagnaIT/plugin.video.netflix" <reply@reply.github.com>, "CastagnaIT/plugin.video.netflix" <plugin.video.netflix@noreply.github.com>
Cc: Bas Greydanus <bas@greydanus.net>, Author <author@noreply.github.com>
Onderwerp: Re: [CastagnaIT/plugin.video.netflix] can not login (#224)

Oooops, I am far behind. I will install the latest version and report back. Thx.



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: notoco <notifications@github.com>
Datum: 23-09-19 18:26 (GMT+01:00)
Aan: "CastagnaIT/plugin.video.netflix" <plugin.video.netflix@noreply.github.com>
Cc: deboshond <bas@greydanus.net>, Author <author@noreply.github.com>
Onderwerp: Re: [CastagnaIT/plugin.video.netflix] can not login (#224)


Install stable version from this repo. It's 15.3 for now.

**Comment by Smeulf** [comment]
Seems like from your logs that you miss Cryptodomex.

You have to install it manually.

**Comment by deboshond** [comment]
Where do I find "Cryptodomex"? Is it a package?

**Comment by furkangkhsn** [comment]
I installed Cryptodomex manualle but still cannot login. The same error with @deboshond.

**Comment by Ekopalypse** [comment]
Had a similar, can't say for sure if it was the exact error, issue on RPi3.
Somehow I missed an Widevine update, after forcing an update via the Inputstreamhelper and restarting the RPi it is working again.

**Comment by Smeulf** [comment]
Please share your logs if you have the same error. Without logs, no way to say what the problem is.

**Comment by Ekopalypse** [comment]
@Smeulf - I assume you are requesting that info from @furkangkhsn, don't you?
If this was addressed to me, then sorry, after fixing the issue for me, I deleted the old logs.
Next time such a thing happens, I will keep them for reference.

**Comment by Smeulf** [comment]
Yes @Ekopalypse you're right, sorry I didn't mention @furkangkhsn for the log request.

**Comment by furkangkhsn** [comment]
I just used the wrong version of the pip. Using the version 2.7 did solve my problem.

**Comment by Jick9536** [comment]
Same problem here. 

OSError: Cannot load native module 'Cryptodome.Has._BLAKE2S' raise ISError("Cannot load native module '%s"" % name)

**Comment by CastagnaIT** [comment]
for those who need help, open their own issue page,
to linux (like rpi) install Cryptodome module is needed in order to run netflix addon
see the readme in first page
