### ISSUE TITLE
Crash on Kodi/Netflix add-on startup with outdated msl_data/COOKIE

### ISSUE THREAD

**Issue by CiNcH83** [CastagnaIT/plugin.video.netflix#228]
#### Your Environment
- Netflix add-on version: 0.15.3
- Operating system version/name: Android TV 8.0 Oreo
- Device model:  Sony BRAVIA KD-65XF9005

Used Operating system:
* [x] Android

### Describe the bug
I use the [Backup add-on](https://kodi.wiki/view/Add-on:Backup) to take Kodi config snapshots (including add-on settings) which I restore in case of problems. I now stumbled over a problem, causing Kodi to crash on startup after restoring from backup. The stack trace points to DRM. So I deleted msl_data and COOKIE files which solved the crash.

I logged into Netflix, took another backup and restored from that backup which did not result in a crash. So I assume that the crash is due to outdated msl_data and/or COOKIE files.

I wonder whether this also happens if Kodi has not been run for several days, also leaving you with old msl_data/COOKIE files.

#### Expected behavior
Kodi does not crash on startup.

#### Actual behavior
Kodi crashes on startup.

#### Steps to reproduce the behavior
1. Take backup via Backup add-on (don't forget to also enable add-on settings to be included)
2. Wait some time (days?)
3. Restore from backup
4. Restart Kodi

You can probably also save today's msl_data and COOKIE file and copy/replace them later on.

### Debug log
The debug log can be found here: [[logcat](https://www.dropbox.com/s/6xk0qx3mpr6j708/kodi_netflix_crash.log?dl=0)]

Debug logging has not been enabled inside Kodi. I could however alter the backup somehow to enable it in case it is required. The log however includes the stack trace of the crash.

**Comment by CastagnaIT** [comment]
Cookie file do not cause this type of error, 
deleting the msl_data you have forced the recreation of that file by establishing a new handshake,
in any case if msl_data had expired or corrupted, do not cause a unhadled error, the code is protected from exceptions at least in the addon, but
in logcat the error starting from a kodi library, it's kodi that communicate with android drm not the addon directly

it is also possible that the backup app does not work properly, and that the restore you actually do, not restore the files in the correct way

we could understand something more only by having the kodi log with debug infos

**Comment by CiNcH83** [comment]
> it is also possible that the backup app does not work properly, and that the restore you actually do, not restore the files in the correct way

Don't think so. It basically only copies the userdata folder. msl_data.xml from backup looks sane. And as I already wrote, restoring a recent backup works. It only crashes for older msl_data.xml files.

> we could understand something more only by having the kodi log with debug infos

Will provide one as soon as I can reproduce the issue again. I deleted some old backups so I can't reproduce the issue at the current time.

**Comment by CastagnaIT** [comment]
it is possible that with the last addon release not happen again, but being a kodi library error depends also on factors external to the addon
here i close the issue because i don't know what else to do

**Comment by CiNcH83** [comment]
Trying to replicate the crash every day by restoring a backup from 02.10. So far without  „success“. I updated to latest version of the add-on. I‘ll keep trying and attach a log in case of error.

**Comment by CastagnaIT** [comment]
you have to backup the latest version release, otherwise you restore the old version of the addon that works differently,
however if you want to attach an upcoming log, attach the log of kodi not that of the operating system

**Comment by CiNcH83** [comment]
My plan is to let it break with previous version. I will then replace the add-on in the backup to see whether it fixes the crash.

Yes. Will attach kodi log..

**Comment by CastagnaIT** [comment]
do you have anything else to say or i can close?

**Comment by CiNcH83** [comment]
You can close it. I still can't reproduce it with a backup from Oct. 2nd, so one that is exactly one month old. I can still write to a closed issue and you will receive the notification. So you can re-open it in case I am able to reproduce the issue.
