### ISSUE TITLE
Nvidia Shield widevine version not found

### ISSUE THREAD

**Issue by herbalizer404** [CastagnaIT/plugin.video.netflix#229]
Hi,
I have shield experience 8.0.1
ish 0.4.3
Netflix plugin 0.15.3
But ish don't find widevine, have you an idea?
Thanks

**Comment by Dnkhatri** [comment]
can you use the netflix and amazon apps

**Comment by herbalizer404** [comment]
yep both work 
widevine version: not found
widevine cdm location: /data/user/0/org.xbmc.kodi/apk/assets/addons

**Comment by herbalizer404** [comment]
Screenshot here https://imgur.com/a/JzMF8Ut

**Comment by Dnkhatri** [comment]
> Screenshot here https://imgur.com/a/JzMF8Ut

Looks like a inputstream addon problem try asking them

**Comment by CastagnaIT** [comment]
sorry this it is not about netflix addon
