### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by alv000h** [CastagnaIT/plugin.video.netflix#23]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Kodi 18.1 & builtin inputstream

## Addon version used
plugin.video.netflix_20190308build2

### Description
Installation and login ok, after reboot never login again (requires reinstall).

I cannot reproduce any video... only menu navigation

Error printed is:
Error returned by keyexchange service

### Steps to Reproduce

1. Install
2. Login
3. Reboot tvbox

**Expected behavior:** 
Login and reproduce content

**Actual behavior:** 
i cannot reproduce any content and after reboot never loggin in

### Installation

* [ x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ x] Android ARM

#### Additional informatin on the environment
Android 8 with mx10 tvbox

Android is supported by the plugin?
I see several errors during test with release and daily versions

Errors like:
Widevine CryptoSession getKeyRequest failed!

https://github.com/asciidisco/plugin.video.netflix/issues/606

**Comment by CastagnaIT** [comment]
The debug log file is missing.

It is not new that a chinese android device does not work as it should.

At most you can extract the logcat immediately after you start netflix addon, to see what happens in your android system. But still at the addon level it is difficult to do something

**Comment by CastagnaIT** [comment]
no logcat provided for verification purposes, closing
