### ISSUE TITLE
After hugarian localization I can not use the addon

### ISSUE THREAD

**Issue by SpentRocket** [CastagnaIT/plugin.video.netflix#236]
Hello,

Netflix made full hungarian localization a few days ago. After that I set language to hungarian. Now in the addon the menus (My list, Continue watching etc.) are in hungarian language, but when I click on them, I get an error message.

Could you please fix this problem?

**Comment by CastagnaIT** [comment]
Please open an: Issue "Problem report"
so fill the required informations with a log file attached
