### ISSUE TITLE
Sync My List and Kodi Library on startup

### ISSUE THREAD

**Issue by elbowz** [CastagnaIT/plugin.video.netflix#237]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request
I'm trying to keep in sync **Netflix My List** with **Kodi Library**.

I see there are these settings:
* Keep My List and Kodi Library in sync: *enable feature?*
* Perform full sync now: *clear all an restart the process?*
* Purge library: *clear all?*

...but I have not understood how they do

#### Describe the use case
* Select some Movies and Tv Series on Netflix (by app / web interface) 
* Start Kodi and see Netflix plugin pull new selected movies (and clean the removed ones) in my Library (creating/deleting STRM files).

I see we can auto-update by time scheduling, but It strange this approach on a player that non running all day. Maybe, I'm missing something?

**TL;TR** as for Kodi setting "Update library on startup", allow Netflix plugin to "Sync My List and Kodi Library on startup" 

Thanks! 

p.s. I have try to [post on forum](https://forum.kodi.tv/showthread.php?tid=329767&pid=2889206#pid2889206) without answer

**Comment by CastagnaIT** [comment]
if you set to example: sync daily with time 21:00
the sync can start from 21:00 in forward, if the device is switched on at other time example 22:00 the sync start at 22 becouse at 21 not done

yes there is the possibility to add an new option "Sync library on startup"
but i can not guarantee when it will be done

**Comment by elbowz** [comment]
Thanks for the answer. Now, I have understand!

It's look like the difference between Cron and Anacron on Linux.

But in any way, it does not seem works on my PC.

I have enabled daily sync (at 8:00), but after 2 days my library is not synched with Netflix "my list".

I have tried to execute "update library" and "clean library" on Kodi without success.

I have added (and removed) movies on "my list" on Netflix, but these are not added (and removed) on my Kodi library.

I talking about films and series.

I can post Kodi log, but what (inter)action have to do on Kodi?!

p.s. I don't think we need another feature (keep sync on startup), now you have explained how the scheduling works

**Comment by CastagnaIT** [comment]
I'll do some tests to verify

**Comment by elbowz** [comment]
This is the log if can be usefull: https://pastebin.com/LHVR2gDi

**Comment by CastagnaIT** [comment]
I'm checking, but it's gonna take longer.
seem that with the last changes made earlier it there is no longer a check on what has been added/deleted from my list

practically only what is exported locally via the kodi interface is synchronized, but if you add a new TV series to my list from the website, it is not automatically exported

while the button for the initial synchronization is working but only works after closing and reopening the settings, for this can do a quick fix

**Comment by CastagnaIT** [comment]
if you do initial synchronization, then the synchronization at startup works like i explained at first post,
so at startup nf addon check if there is new seasons/episodes for every tvshow exported at this moment.

To make sure that addon automatically exports at kodi startup the tvshows added to my list (outside of kodi, ie example from website/other apps) it is necessary to make changes to the source code of addon. I'm working, when i finish the changes will be available to everyone

Ps. the library sync works only with tvshows not films,
but if you want you can export the films manually

**Comment by elbowz** [comment]
> if you do initial synchronization, then the synchronization at startup works like i explained at first post,
> so at startup nf addon check if there is new seasons/episodes for every tvshow exported at this moment.
I have missed this...now I figure out :)

> To make sure that addon automatically exports at kodi startup the tvshows added to my list (outside of kodi, ie example from website/other apps) it is necessary to make changes to the source code of addon. I'm working, when i finish the changes will be available to everyone
 
Are you working on this feature?! Really?! Great!!

> Ps. the library sync works only with tvshows not films,
> but if you want you can export the films manually

By redo an initial synchronization, right?

p.s. I'm the only one that have this this request?! ...and all others guys how anderstand the "particular l" meaning of synching options (only New seasons/episodes)

**Comment by CastagnaIT** [comment]
should now be fine, in case you reopen issue

**Comment by elbowz** [comment]
Thanks for your hard works!

I think to miss something...
Now, all my films and series that appear in "My list" are removed from Kodi library.

If I try to run "Perform full sync now" I get "you can start synchronization only by selecting the owner profile".

Obviously, I'm not the owner (main profile on Netflix), so I cannot sync anymore, like the previous version of Netflix plugin?!

**Comment by mackal** [comment]
Before I was at least able to sync a non-owner library, but auto sync didn't work. This was better than just being able to sync owner :/

**Comment by CastagnaIT** [comment]
in reality, things are different.

initially the addon allowed synchronization only from the main profile.

following recent changes by netflix a bug was introduced in the addon to perform synchronization from any profile by switching profile.

but this however it may seem nice, but in realty caused a bigger problem with auto-synchronization and other api request for wrong permissions to get/post data from netflix.

that's why now I put the warning message forcing the use of the main profile to ensure the correct operation of the auto-sync.

I have no fun limiting things, there's a reason i did it this way.

in the future you can allow yourself to select from which profile to make the synchronization, but this requires lot of work to fix things, and you can not do it in a short time.

**Comment by elbowz** [comment]
I understand...

So now only the main profile can do manual and auto-sync.

All others profiles can only use "manual navigation" through the Netflix plugin interface.

Is it right?

**Comment by CastagnaIT** [comment]
to now:
"Keep My List and Kodi Library in sync" & "Export new episodes" options, work only with main profile

if "Keep My List and Kodi Library in sync" is disabled: you can do manual export by using context menu from any profile

I specify that on "Keep My List and Kodi Library in sync" option when enabled, there is still a bug that I haven't solved yet, it should happen when you add something from a non-main profile to My List.
too many things to fix, need more time following days

**Comment by mackal** [comment]
Is there any way to not have to manually export each show on My List from my non-owner profile? I couldn't find a way :(

**Comment by elbowz** [comment]
If I knew this, I had not opened the issue ;)

Don't matter, I know what mean develop and take care of a open source project...and this is a big one.

I hope then in future all profiles will be able to (auto)sync.

As I have already said, thanks for your hard work and your time!
