### ISSUE TITLE
Profile missing (workaround found)

### ISSUE THREAD

**Issue by kl3sk** [CastagnaIT/plugin.video.netflix#239]
# __For other users__
The solution (for me, until a fix) was:
- removing all extension and data from 0.15.4
- installing 0.15.3 from Zip
- Log in
- update extension

#### Your Environment
- Netflix add-on version: 0.15.4
- Operating system version/name: OSMC 18.3 stable
- Device model:  Rpi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe your help request

Impossible to login, `Profile missing` raised error
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3719771/kodi.log)

**Comment by kevlugli** [comment]
Happened to me as well. Downgrading to 0.15.3 fixes it. Once login in, I updated to last version and everything work as expected.

**Comment by CastagnaIT** [comment]
I'm looking for the problem, unfortunately in my tests it never happened..
this log has no debug information, a complete debug log would be more useful

**Comment by kl3sk** [comment]
@kevlugli I'll try it
@CastagnaIT  Sorry how could I provide a better log ?

**Comment by CastagnaIT** [comment]
how enable debug is explained here:
https://kodi.wiki/view/Log_file/Easy

**Comment by kl3sk** [comment]
@CastagnaIT Ok thank you i'll provide it as soon as i can. But just for information @kevlugli solution work for me too.

**Comment by kl3sk** [comment]
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3720350/kodi.log)
@CastagnaIT  Does this log better ? (Sorry I though the logging was active)

**Comment by CastagnaIT** [comment]
yes this time is good thanks

**Comment by kl3sk** [comment]
Ok, hope you found a solution. Because (as @kevlugli said) upgrading from `0.15.3` does not raise this exception.

**Comment by CastagnaIT** [comment]
I'm verifying... it is a problem of a variable that i have not taken into consideration

**Comment by kl3sk** [comment]
I'll try the next release I you want

**Comment by CastagnaIT** [comment]
@kl3sk can you test this?
can you also confirm if browsing lists is faster?
[plugin.video.netflix_0.15.4_20191012.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3720836/plugin.video.netflix_0.15.4_20191012.zip)

**Comment by kevlugli** [comment]
I tried, it is working well. And yes, the listing is a lot faster!
That's great man. Thank's for the good work @CastagnaIT !

**Comment by huibw** [comment]
Was having the same issue with 0.15.4. The version in the ZIP file works like a charm.

**Comment by ruschinator** [comment]
hello.. i use this version on a shield.. it works only in SD (540p) 
can U help?

**Comment by CastagnaIT** [comment]
@ruschinator 
this does not concern the issue of this post
go to "Shield v8.0.0 (Pie) killed Kodi Netflix" issue

**Comment by ruschinator** [comment]
roger..

**Comment by kl3sk** [comment]
Hello @CastagnaIT, thx for the quick fix. I can confirm this working perfectly on my device.
About browsing list, yes it look likes a bit faster. But anyway this is working and that is great.

Thanks again ! And good job.

I'll close this issue when your official release came out.
