### ISSUE TITLE
list' object has no attribute 'get on windows

### ISSUE THREAD

**Issue by SeyedMahmoudian** [CastagnaIT/plugin.video.netflix#24]
*I'm submitting a ...*
  - [x]  bug report
  - [ ] feature request
  - [ ] support request

## General information
Windwos 10
### Addon version used
0.14.0~beta22

### Description
When trying to watch a movie I get an error

### Steps to Reproduce

1. Launch the app
2. Choose the user
3. choose any category
4. choose any movie or tv show

**Expected behavior:** Watch the movie

**Actual behavior:** Error display

### Installation

* [x]  I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x]  Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://pastebin.com/8sVd5Wkn

### Screenshots

https://imgur.com/tnE9SCU

**Comment by pushezmadame** [comment]
Hi, look at the line 1049 of your log file.

**Comment by lekma** [comment]
possible quick and dirty fix (untested):

```diff
--- msl_handler.py.old	2019-03-11 20:51:11.000000000 +0100
+++ msl_handler.py	2019-03-13 12:53:15.386631322 +0100
@@ -290,7 +290,7 @@
         raise MSLError(_get_error_details(decoded_response))
     if isinstance(decoded_response, list):
         if decoded_response[0].get('error'):
-            raise MSLError(_get_error_details(decoded_response))
+            raise MSLError(_get_error_details(decoded_response[0]))
     return decoded_response
 
 
@@ -303,9 +303,8 @@
         return decoded_response['result']['errorDisplayMessage']
     elif decoded_response.get('result', {}).get('errorDetails'):
         return decoded_response['result']['errorDetails']
-    elif isinstance(decoded_response, list):
-        if decoded_response[0].get('error', {}).get('errorDisplayMessage'):
-            return decoded_response[0]['error']['errorDisplayMessage']
+    elif decoded_response.get('error', {}).get('errorDisplayMessage'):
+        return decoded_response['error']['errorDisplayMessage']
     return ''
 
 
```

@CastagnaIT: am I correct to assume _get_error_details() is a remnant of the past? If yes, may I suggest the following (also untested):

```diff
--- msl_handler.py.old	2019-03-11 20:51:11.000000000 +0100
+++ msl_handler.py	2019-03-13 13:59:42.391528926 +0100
@@ -287,26 +287,20 @@
     if 'errordata' in decoded_response:
         common.error('Full MSL error information:')
         common.error(json.dumps(decoded_response))
-        raise MSLError(_get_error_details(decoded_response))
+        raise MSLError(_decode_errordata(decoded_response['errordata']))
     if isinstance(decoded_response, list):
-        if decoded_response[0].get('error'):
-            raise MSLError(_get_error_details(decoded_response))
+        error = decoded_response[0].get('error')
+        if error:
+            try:
+                message = error.get('errorDisplayMessage', '')
+            except AttributeError:
+                message = str(error)
+            raise MSLError(message)
     return decoded_response
 
 
-def _get_error_details(decoded_response):
-    if 'errordata' in decoded_response:
-        return json.loads(
-            base64.standard_b64decode(
-                decoded_response['errordata']))['errormsg']
-    elif decoded_response.get('result', {}).get('errorDisplayMessage'):
-        return decoded_response['result']['errorDisplayMessage']
-    elif decoded_response.get('result', {}).get('errorDetails'):
-        return decoded_response['result']['errorDetails']
-    elif isinstance(decoded_response, list):
-        if decoded_response[0].get('error', {}).get('errorDisplayMessage'):
-            return decoded_response[0]['error']['errorDisplayMessage']
-    return ''
+def _decode_errordata(errordata):
+    return json.loads(base64.standard_b64decode(errordata))['errormsg']
 
 
 @common.time_execution(immediate=True)
```

**Comment by SeyedMahmoudian** [comment]
> Hi, look at the line 1049 of your log file.

I checked and can login with my chrome it

**Comment by SeyedMahmoudian** [comment]
I did not change anything but the new issue is when I click to play a video the Kodi crashed and closed 
kodi log: https://pastebin.com/uQw0hRva
memory dump : https://pastebin.com/pzvsh39K

**Comment by CastagnaIT** [comment]
I will recheck the error handling to handle this exception as well,
but your real problem is:

"Your Netflix account is in use on too many devices. Please stop playing on other devices to continue."

**Comment by SeyedMahmoudian** [comment]
> I will recheck the error handling to handle this exception as well,
> but your real problem is:
> 
> "Your Netflix account is in use on too many devices. Please stop playing on other devices to continue."

so I was looking around and this is what I found out I am running Kodi on windows but for some reason, Kodi IP address is different from my computer address, for example, my computer IP is 192.168.0.1 but in Kodi, it says 172.30.175.225, it seems to be a virtual address that is why I can not add my netflix account

**Comment by CastagnaIT** [comment]
yes that's another thing, the wrong ip it's a kodi bug that has been handed down for many months and have never solved... just activate Windows 10 Miracast wireless display and kodi goes crazy...

**Comment by SeyedMahmoudian** [comment]
Alright then this seems to be kodi fault not the addons so no need to keep the issue open as nothing can be done
