### ISSUE TITLE
Incorrect password msg

### ISSUE THREAD

**Issue by dvdbaro** [CastagnaIT/plugin.video.netflix#240]
#### Your Environment
- Netflix add-on version: 0.15.3
- Operating system version/name: LibreElec 9.1.501
- Device model:  Raspberry Pi 4   4 Go

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Add-on installed
When asked for the credentials to log in. the message 'Incorrect password' appears. But password is the good. I verified on another device.

#### Expected behavior
log in

#### Steps to reproduce the behavior

1. Install add-on
2. Log-in to netflix
3. 

### Debug log
The debug log can be found here: http://ix.io/1Yq6

Thanks for your help
David

**Comment by CastagnaIT** [comment]
Hi,
uninstall netflix addon also confirm to delete userdata
after try to install this:
[plugin.video.netflix_0.15.4_20191012.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3720844/plugin.video.netflix_0.15.4_20191012.zip)

let me say if work

**Comment by CastagnaIT** [comment]
i have also noticed you have twice netflix app versions installed
2019-10-12 14:21:29.699 T:2871161712  NOTICE: ADDON: plugin.video.netflix v0.13.10 installed
2019-10-12 14:23:06.182 T:2871161712  NOTICE: ADDON: plugin.video.netflix v0.15.3 installed
you have to uninstall both

**Comment by dvdbaro** [comment]
Thank you for your answer.
It doesn't work. The message is still the same

David

Le sam. 12 oct. 2019 à 17:33, Stefano Gottardo <notifications@github.com> a
écrit :

**Comment by CastagnaIT** [comment]
I don't see anything relevant in the log,
the login error code returned comes directly from the server response
so you have some problems with your credential access or your device have been banned
you can also try to change your password... i can't do anything else

**Comment by guysoft** [comment]
Getting the same issue. Worked fine for a while. Now it says credentials are wrong.  I can log in to the website fine with them. 
What logs should I provide?

**Comment by guysoft** [comment]
Okx upgrading to the latest version fixed the issue for me. It didn't show up in the repo, had to download the zip manually

**Comment by dvdbaro** [comment]
I changed the password... and it works with the plugin
plugin.video.netflix_0.15.4_20191012.zip
<https://github.com/CastagnaIT/plugin.video.netflix/files/3720844/plugin.video.netflix_0.15.4_20191012.zip>
Thank you for your help.

David

Le sam. 12 oct. 2019 à 20:35, Stefano Gottardo <notifications@github.com> a
écrit :

**Comment by guysoft** [comment]
Suggest you close the issue. Seems like both OP and mine is reserved.
