### ISSUE TITLE
Not all audiostreams are available

### ISSUE THREAD

**Issue by shtrom** [CastagnaIT/plugin.video.netflix#243]
#### Your Environment
- Netflix add-on version: 0.15.3
- Operating system version/name: LibreElec 9.0.2
- Device model:  WeTek Core

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Different languages are offered between the Netflix web UI, and the addon. See for example
“Super Monsters”, Season 3, “05. Green with Envy / Oops, We shrunk the Cars”.

In Kodi, the available audio streams are (ignoring 2/6 channels duplicates)
Greek, English, Italian, Vietnamese, Chinese

In the Netflix Web UI there are (ignoring audio description duplicates)
English, French, Italian, Vietnamese, Mandarin

I'm after French, which is definitely available in the Web UI, and I have confirmed that Greek is not a mis-labelled French (it is definitely Greek to me!).

#### Expected behavior
All available audio streams should be displayed, i.e., including French.

#### Actual behavior
French is not available. Oddly enough, Greek is, which the Web UI didn't have, but that's OK.

#### Steps to reproduce the behavior
Check the audio streams for “Super Monsters”, Season 3, “05. Green with Envy / Oops, We shrunk the Cars”.

### Debug log
The debug log can be found here: 
https://gist.github.com/shtrom/a40f90ac3f60bcb1ce13650c5825ddee

#### Installation
* [ ] I'm using other Netflix Repo [using CastagnaIT Repository]
* [ ] I'm using a different source

**Comment by shtrom** [comment]
Sounds like https://github.com/asciidisco/plugin.video.netflix/issues/715, which seems to be due to https://github.com/peak3d/inputstream.adaptive/issues/192

**Comment by Mark9011** [comment]
Try opening Netflix in Google chrome or Firefox and in Account change Playback Settings to low or medium.

**Comment by CastagnaIT** [comment]
Tried “Super Monsters”, Season 3, ep. 5
To me all audio streams language are present
![image](https://user-images.githubusercontent.com/3257156/66734429-5367df00-ee63-11e9-8966-6b21045d7343.png)
![image](https://user-images.githubusercontent.com/3257156/66734432-55ca3900-ee63-11e9-8604-c16b1bde2acf.png)
![image](https://user-images.githubusercontent.com/3257156/66734592-ffa9c580-ee63-11e9-8703-0200388c59c2.png)

But if you choose "stream selection" to Manual in InputStream Adaptive, the tracks are wrong... seem a bug in InputStream Adaptive not in netflix addon:
![image](https://user-images.githubusercontent.com/3257156/66734891-1e5c8c00-ee65-11e9-880c-0400cd555bea.png)

**Comment by shtrom** [comment]
I just tried dropping the quality in the WebUI account settings to Medium, then Low, and only got the same selection of languages (albeit with different combinations of quality).

**Comment by shtrom** [comment]
I see something different here (Australia) ![netflix_audio_streams](https://user-images.githubusercontent.com/160280/66742056-87beb800-eec2-11e9-93e1-a6005373e6fb.png)

**Comment by peak3d** [comment]
It's this one which limits the amount of streams which can be xchanged between kodi and inputstream basted addons: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h#L98

**Comment by CastagnaIT** [comment]
but this not explain why there is a wrong list of audio language, in the last my screenshot to example you can see a lot of German audio tracks where should be only two

**Comment by CastagnaIT** [comment]
however if you want to attach an upcoming log, attach the log of kodi not that of the operating system

**Comment by shtrom** [comment]
This one (from the issue) was from Kodi: https://gist.github.com/shtrom/a40f90ac3f60bcb1ce13650c5825ddee

**Comment by peak3d** [comment]
@CastagnaIT correct, the multiple DE seems wrong, will look at it

**Comment by shtrom** [comment]
From my tests yesterday, the multiple streams for the same language _is_ from https://github.com/peak3d/inputstream.adaptive/issues/192, when using the Manual mode. But that's not what I use the rest of the time, so I'm not sure it's linked.

**Comment by peak3d** [comment]
ok, thx @shtrom

**Comment by peak3d** [comment]
@CastagnaIT looked into the manifest and there I can find DE stereo (2 representations) and DE 5.1 (5 representations) -> all fine from this point.

**Comment by shtrom** [comment]
From a user's perspective, it seems to not make much sense to have both 2 and 5.1 channel options. Perhaps this could be a global choice in the (Netflix) plugin? That would limit the number of offered streams some more. That said, once again, no sign of French ever being offered in the logs, so maybe something else is at play.

Anyway, happy to provide logs and run more tests if needed.

**Comment by peak3d** [comment]
Manual is a debug option, it was not implemented to fulfill any "user experience"
The answer to the 12 -> 16 streams is already some posts above.

**Comment by CastagnaIT** [comment]
@peak3d suggest to move the debug settings of inputstream adaptive to another panel for that purpose, becouse creates confusion for different users and me too...

**Comment by peak3d** [comment]
@CastagnaIT may I ask why you use manual stream selection?

**Comment by CastagnaIT** [comment]
personally i dont use this option, but however following the forum and github, i often read that several users use it to be able to manually select the video resolution

**Comment by peak3d** [comment]
I pushed a commit for "manual video" in the master branch, but this should be said: its even not normal user firndly too, because of the duplicate video resolutions which only differ by bandwidth.

**Comment by CastagnaIT** [comment]
thank you this is a good idea
however the bandwidth is visible in the selection sso the most novice at best ask what it means different bps not big problem

**Comment by shtrom** [comment]
> Manual is a debug option, it was not implemented to fulfill any "user experience"

Yup, I get that. The “user's experience” thing was more to preemptively limit the number of different streams for the same language, based on audio setup.

> The answer to the 12 -> 16 streams is already some posts above.

Hum, I might have misunderstood that part. The Kodi code _seems_ to limit the number of supported streams to 16. This is why I was pointing the 12 out, as a lower number that would not have been impacted by that limit. I've just re-read your comment https://github.com/CastagnaIT/plugin.video.netflix/issues/243#issuecomment-541652443, but that confirmed my understanding.

Doesn't matter much though, but I thought it was worthwhile to flag.

**Comment by shtrom** [comment]
For completeness, here's the list of streams in Kodi (turns out you can't take a screenshot through the API). It matches what the logs show.

![IMG_20191014_214514](https://user-images.githubusercontent.com/160280/66829070-47cd0300-ef9e-11e9-9493-c62152bbbaa4.jpg)
![IMG_20191014_214524](https://user-images.githubusercontent.com/160280/66829072-47cd0300-ef9e-11e9-83a1-d230cc6d5894.jpg)

**Comment by shtrom** [comment]
Any idea about a potential resolution or workaround, or is this issue deemed invalid?

**Comment by CastagnaIT** [comment]
you have to wait for the next inputstream addon update, if after the future update there are still problems open an issue again

**Comment by shtrom** [comment]
On Mon 21 Oct 2019 at 23:37:29 -0700, Stefano Gottardo wrote:
>you have to wait for the next inputstream addon update, if after the future update there are still problems open an issue again

Cool. Will do. Cheers.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.
