### ISSUE TITLE
KeyError: u'licenseResponseBase64' on every video

### ISSUE THREAD

**Issue by ironashram** [CastagnaIT/plugin.video.netflix#248]
#### Your Environment
- Netflix add-on version:  15.5
- Operating system version/name:  Manjaro Linux latest, kodi latest stable 18.4
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Just installed the addon on my new new media center with Manjaro Linux and kodi 18.4 and every video i try to reproduce gives the error KeyError: u'licenseResponseBase64'

#### Expected behavior

Video reproduction starting

#### Actual behavior

KeyError: u'licenseResponseBase64' given

#### Steps to reproduce the behavior

1. Open the addon
2. Start any video

### Debug log

The debug log can be found here: 
http://dlsys.r1-it.storage.cloud.it/kodi.log

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Install this and give me a new log
let's see if i find anything useful

[plugin.video.netflix_0.15.5_20191019.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3746878/plugin.video.netflix_0.15.5_20191019.zip)

**Comment by ironashram** [comment]
New log here:
http://dlsys.r1-it.storage.cloud.it/kodi2.log

**Comment by CastagnaIT** [comment]
it is possible you have changed playback settings in website preferences?

**Comment by ironashram** [comment]
no i don't think so, i also just tried all playback settings on the website with absolutely no behaviour change

**Comment by CastagnaIT** [comment]
have you tried to uninstall addon and reinstall it?

**Comment by ironashram** [comment]
actually i already tried that but maybe i kept local config last time, this time i deleted all configuration and also done the same with inputstream.adaptive and now it works.
Thanks and sorry to have bothered you.
