### ISSUE TITLE
Exception: HTTPError when saving to "My List"

### ISSUE THREAD

**Issue by brainfork** [CastagnaIT/plugin.video.netflix#251]
#### Your Environment
- Netflix add-on version: 0.15.5
- Operating system version/name: Windows 7
- Device model:  ThinkPad E550

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

Error is thrown when attempting to save media to "My List"

#### Expected behavior

Selecting "Add to 'My List'" in context menu should add media to "My List"

#### Actual behavior

Modal/error notice is displayed indicating an HTTPError exception has been thrown

#### Steps to reproduce the behavior

1. Open context menu on media
2. Select "Add to 'My List'"

### Debug log

The debug log can be found here: [https://pastebin.com/ic3cLucn](https://pastebin.com/ic3cLucn)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
reboot kodi and try again

**Comment by brainfork** [comment]
Issues persists after rebooting Kodi as well as rebooting Windows.
Here is the full Kodi log after rebooting the computer: [https://pastebin.com/VYnMAj3N](https://pastebin.com/VYnMAj3N)

**Comment by brainfork** [comment]
I also get the same error when selecting "Export to Library" but it doesn't appear to prevent the files from being exported.

**Comment by Thunderbird2086** [comment]
It started happening yesterday and still persistent.

**Comment by CastagnaIT** [comment]
the logs provided are without debug infos, before to take any actions you have to enable kodi debug and reboot

**Comment by CastagnaIT** [comment]
I also found this error, the first time some day ago, but the folowing day it had disappeared
and just now in the dev pc, unfortunately after deleting esn in order to force the login, no longer appeared, i still can't figure out exactly what's going on

but i have also noticed that netflix introduced new system to add/remove to mylist
to use this new system there is need to do many changes and study how to make

to study a solution i need this problem happen to me i do not know when it happens again..

**Comment by brainfork** [comment]
> the logs provided are without debug infos, before to take any actions you have to enable kodi debug and reboot

I'll re-test later with Kodi debug enabled and post the resulting log.

**Comment by CastagnaIT** [comment]
i have noticed that this happen changing profile
please try to install this test

before try to add/remove, to first time:
enter to one profile, now return to profile list and enter with another profile, then try to add/remove

[plugin.video.netflix_0.15.5_20191022_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3757944/plugin.video.netflix_0.15.5_20191022_test1.zip)

**Comment by CastagnaIT** [comment]
someone can do a try?

**Comment by Thunderbird2086** [comment]
It's working!  To test it, I needed to log out from existing session.  Thanks!

**Comment by CastagnaIT** [comment]
Thank you for confirming!
