### ISSUE TITLE
Some series appear to be missing in all lists

### ISSUE THREAD

**Issue by TimSchneider42** [CastagnaIT/plugin.video.netflix#256]
#### Your Environment
- Netflix add-on version: 0.15.5
- Operating system version/name: Raspbian Stretch with Kodi 18.2
- Device model: Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Some series appear to be missing in all lists. Tested with "Dark" and "Bodyguard". In case of "Dark", I tried to search for it and got many results but not "Dark" itself. I also tried adding "Dark" to "My list" on another device, but it would only show movies and no series. 

#### Expected behavior
Searching for series by name should result in the series showing in the result list like on any other device.

#### Actual behavior
Only movies and no series are showing up in the search result and any other list.

#### Steps to reproduce the behavior
1. Navigate to "Search"
2. Search for "Dark"
3. Realize that it is not present

**Comment by CastagnaIT** [comment]
inconsistent description:
> Some series appear to be missing
...
> Only movies and no series are showing up

i tried to search dark/Bodyguard to the lists/search and are listed as it should
i don't know what happen with your device no log provided
i can only suggest to try reinstall addon

**Comment by CastagnaIT** [comment]
Update the addon with the new version just released
and let me know

**Comment by TimSchneider42** [comment]
I will try that as soon as I have time. What kind of log do you need?

**Comment by CastagnaIT** [comment]
To now update the addon and see if you have correct results.
The problem you mentioned is really weird is hard believing that it doesn't yield results.

Instructions for provide a log are here:
https://kodi.wiki/view/Log_file/Easy

**Comment by CastagnaIT** [comment]
Closed for inactivity
