### ISSUE TITLE
The plugin stopped working

### ISSUE THREAD

**Issue by pablogarin** [CastagnaIT/plugin.video.netflix#259]
#### Your Environment
- Netflix add-on version: 0.15.5
- Operating system version/name: Raspbian GNU/Linux 9 (stretch)
- Device model:  Pi 2 Model B (Revision a21041)

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

The Netflix addon suddenly stoped working. As far as I can tell, the problems started after an update on InputStream. The app starts up normally, but the it prompts a dialog with a time out message and the suggestion to check the Kodi Log. Nothing else happens.

Now, sometimes I can see the profiles screen, that is it shows all the users in the account, but sometimes it just fails from the start.

#### Expected behavior

The plugin should load and show all the netflix categories.

#### Actual behavior

It prompts a dialog with a time out message.

#### Steps to reproduce the behavior

1. Reboot the raspberry.
2. Start Kodi.
3. Open Netflix Plugin.

### Debug log

The debug log can be found here: https://raw.githubusercontent.com/pablogarin/netflix_log/master/kodi.log

**Comment by pablogarin** [comment]
If I'm doing something wrong, please help me solve it by pointing me on the right direction. I have another rpi with the plugin working fine, and on the rpi that's not loading, it used to work fine.

Thanks!!

**Comment by CastagnaIT** [comment]
currently there are no updates on inputstream
it seems that the netflix addon local database does not work well, or is corrupted or fails to access properly for other reasons
you can try to reinstall the addon (remember to delete also user data when prompted)

**Comment by jawn** [comment]
Had same issue and uninstall and reinstall fixed it.

**Comment by pablogarin** [comment]
I already re-installed and nothing... I even deleted the whole ".kodi" folder and used a backup but that didn't worked either... 

The update I was refering to was a WideVine update (which is a dependency of InputStream), but this was a couple of months ago, maybe 3 or 4... 

I still have this issue and I don't seem to be able to solve it... I will go through the code to check what can be causing this problem... it seems to me it can a be a socket or connection timeout, or something similar, so if you can point me on the right direction I can take from there...

Please help me :/

**Comment by CastagnaIT** [comment]
the problem you had above should be solved in the way that other user have told you
if you now have other types of problems are not able to help you if you do not publish new logs with DEBUG info enabled.

In anly case you are using a old version of Kodi:
23:57:22.349 T:1899437328  NOTICE: Starting Kodi (18.0 Git:20190130-aa48862e98). Platform: Linux ARM 32-bit
you have to update to 18.4

**Comment by pablogarin** [comment]
I did what the other user suggested BEFORE posting this issue... I did a full kodi reinstall from the same source it was working and nothing, I even deleted the ".kodi" folder and did a full "apt purge kodi" and then reinstalled it with the plugin... and only then I created this issue... It's not like I didn't tried to solve this before leaving this post... If you want to I can leave another log, cause sinse the last one I did upgrade kodi to 18.2 (which is the only version available AFAIK for my processor instruction set/arquitecture).

And as I said before, I had done a full reinstall before this post, and that did nothing... the only thing I haven't tried yet is a full OS reinstall... but that seems a bit drastic...

I have started debugging the problem by myself, so any pointers would be apretiated, but if not, I'll let you know how it goes...

**Comment by CastagnaIT** [comment]
I can't do anything if your device loses the data writed...
the cause are elsewhere
