### ISSUE TITLE
Possible subtitle bug when stream on manual

### ISSUE THREAD

**Issue by RH1CK** [CastagnaIT/plugin.video.netflix#265]
#### Your Environment
- Netflix add-on version: 0.15.5
- Operating system version/name: Android 8
- Device model:  Mibox

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
First of all thank you very much for this addon.
I'm only able to get to 4k if set the stream to manual on inputstream adaptive addon, i tried to set Min Bandwidth to over 16,000,000 (I guess it should be enough to get 4k, if not how much???), but if i do that I'm not able to select any subtitle

#### Expected behavior
On subtitle setings it should be able to choose among subtitles languages

#### Actual behavior
It doesn't show any subtitle avaliable

#### Steps to reproduce the behavior
1. Enable all setings to be able to run in 4k
2. Set inputstream adaptive addon stream selection to manual
3. Try to choose a subtile

#### Possible fix
Disabling doubly digital seems to "fix" but it doesn't show all the subtitles that are available, if u change to auto it does 

Thanks again

**Comment by CastagnaIT** [comment]
You have a wrong inputstream configuration
Stream selection > Auto (manual is only to debug scope and if ON cause problems with streams)
Override HDCP > ON
Ignore display resolution > ON if kodi resolution is less than 4k else OFF

**Comment by RH1CK** [comment]
ill try that, how much should i set Min Bandwidth to get 4k? If I set it to auto i can't get 4k, I need to check if kodi resolution is 4k or try to ignore display. Thanks for the fast reply and for the amazin job with this addon

**Comment by RH1CK** [comment]
Worked like a charm, the kodi was set as 1080, i changed ignore display to on set the stream to auto and 18,000,000 for min Bandwidth, sorry for my ignorance and thanks for your patience

**Comment by CastagnaIT** [comment]
can you tell me the exact model of your Mibox device?
I would like to make a list of devices that work in 4k

**Comment by RH1CK** [comment]
Of course, Mibox MDZ-16-AB global version

**Comment by CastagnaIT** [comment]
would you have time to help me with ESN?
can you send to my email your ESN in use? (my email on first github page)
Thanks, i need it only to understand the structure
