### ISSUE TITLE
Error on last daily - Can only construct a VideoId from a show or movie item

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#27]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

daily-20190313

### Description
At the entrance to your profile the error is shown, and the plug does not go to the next position. Playing the shortcuts from the skin works correctly
### Steps to Reproduce
Go to Netflix - [your profile name] - error

**Expected behavior:** [What you expected to happen]
Working
**Actual behavior:** [What actually happened]
Not working ;)
### Installation
Using daily builds

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Coreelec and ArchLinux

## Debug log
https://pastebin.com/t0PqgyLW
### Screenshots
https://ibb.co/jzhBFTZ

**Comment by CastagnaIT** [comment]
logs cuted without debugging are useless

I need to know if with estuary skin works with profile access

**Comment by zaphod24** [comment]
I’m using estuary (default skin) and it does not work

**Comment by notoco** [comment]
I'm sorry, I thought that would be enough. full log - clean kodi profile, only netflix installed.
http://ix.io/1DGJ - full log.

**Comment by zaphod24** [comment]
And now it is working, no reboot

**Comment by CastagnaIT** [comment]
after an hour of tests i found the problem, it happens rarely because it depends on the order in which netflix sends the objects, in practice in the new folder "Love, Death & Robots", netflix has inserted an episode in the list without inserting it in its own seasons folder, maybe a mistake on their part or yet another fucking change to the system...

**Comment by notoco** [comment]
It's strange, but today everythings works.

**Comment by CastagnaIT** [comment]
fixed
