### ISSUE TITLE
Running netflix addon on KODI. Error: InputStream not installed. 

### ISSUE THREAD

**Issue by byruda** [CastagnaIT/plugin.video.netflix#275]
#### Your Environment
- Netflix add-on version: 0.15.7
- Operating system version/name: Raspbian GNU/Linux 10 (buster), kernel: Linux ARM 32-bit version 4.19.75-v7l+

- Device model: RPi4 with ARMv7 Processor rev 3 (v7l), with Neon enabled.

Used Operating system: Raspbian GNU/Linux 10 (buster),

### Describe the bug

Installed KODI from Raspbian sources using apt.
Installed netflix plugin from within KODI using Castagna repository.
Configured netflix plugin with valid Netflix account data.

#### Expected behavior

Opened netflix addon.
All operations performed as expected with exception noted below.
#### Actual behavior

After clicking on series episode name to play, immediately received message saying, "InputStream is not installed." 
#### Steps to reproduce the behavior

1. Duplicate install operations on RPi4 as provided above.
2. Configure netflix addon with valid netflix account.
3. Browse to a Netflix content element and attempt to play.

#### Possible fix

Provide instructions as to how to install appropriate InputStream module manually directly from a zip file or repository.

### Debug log
 Being 
The debug log can be found here: 
https://www.dropbox.com/home/Netflix
File is 320KB
If you do not have a free dropbox account, please advise how to post the log file. I am using github for the first time.

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
wrong link to log..
howewer on kodi addons menu,
-install from repository
-Kodi repository
-VideoPlayer InputStream
and install: InputStream Adaptive

If is only disabled: so to enable open context menu and select Enable

**Comment by dagwieers** [comment]
@CastagnaIT Normally **inpustream.adaptive** is enabled automatically by **script.module.inputstreamhelper**. The problem here IIRC is that the **inputstream.adaptive** add-on needs to be installed using apt separately as it is not available.

See: https://forum.kodi.tv/showthread.php?tid=341053

**Comment by CastagnaIT** [comment]
oh thank you
no having an RPI i could not know

**Comment by CastagnaIT** [comment]
@byruda any news? otherwise this can be closed

**Comment by CastagnaIT** [comment]
Closed for inactivity
