### ISSUE TITLE
Add to My List function broken

### ISSUE THREAD

**Issue by CharlieDestroyerOfTacos** [CastagnaIT/plugin.video.netflix#277]
#### Your Environment
- Netflix add-on version: 0.15.7
- Operating system version/name: Windows 10
- Device model:  PC

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x ] Windows

### Describe the bug

An HTTP error is given when attempting to add any TV Show or Movie to My List

#### Expected behavior

Movie or Show should be added to My List without error.

#### Actual behavior

HTTP error is thrown and nothing is added to My List

#### Steps to reproduce the behavior

1. Browse to Any show or movie
2. Open Menu and Select "Add to My List"

### Debug log

The debug log can be found here: 

https://pastebin.com/2i8UkJgE

**Comment by CastagnaIT** [comment]
missing debug info in log

**Comment by CastagnaIT** [comment]
weird that this mistake still happened
since i applied the fix no longer happened to me and other users

do you use exporting to the kodi library?
I will also need to know in detail which operations you do
before that error begin happen

**Comment by CastagnaIT** [comment]
with 15.8 addon update the problem persist?
have you tried to switch profile twice before try again add/remove to my list?

**Comment by CastagnaIT** [comment]
Closed for inactivity
