### ISSUE TITLE
 Some series do not working with upnext (from library)

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#278]
#### Your Environment
- Netflix add-on version: 0.15.7
- Operating system version/name: Coreelec 9.2, Windows 10
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [X] Windows

### Describe the bug
The problem occurs when using the library, but not on every series. An example of a non-working serial https://www.netflix.com/title/70155581 - when you choose the option in Up Next- watch next - returns to the window with a list of episodes - nothing happens.
There is an error in the logs:
```
`2019-10-29 08:24:34.543 T:3766571904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xf3' in position 81: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.addon.signals/lib/AddonSignals.py", line 52, in onNotification
                                                self._slots[sender][signal](_decodeData(data))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 533, in play_callback
                                                common.play_media(data['play_path'])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/kodiops.py", line 120, in play_media
                                                xbmc.executebuiltin('PlayMedia({})'.format(media))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 81: ordinal not in range(128)
                                            -->End of Python script error report<--`
```
Full log (watched non-working series first, then other normally working) http://ix.io/2077
When watching the same series directly via the Netflix plug-in, the problem does not occur.

#### Expected behavior
Integration with Upnext is the same for both the library and the plugin

#### Actual behavior
Not working on some series

### Debug log
The debug log can be found here:  http://ix.io/2077

#### Installation
* [X] I'm using other Netflix Repo: Your repo :)
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
have you another title?
at this moment this is not available in my country

**Comment by CastagnaIT** [comment]
logs are without debug so not much useful

**Comment by notoco** [comment]
Of course - I tried on other series - and this error does not occur (at least on the dozens that I have on my list).
I am sending the full log - from windows - with coreelec I could not send to ix.io (it was to big) - I am connecting to it now remotely via vnc to generate the error.
https://paste.kodi.tv/xelutoweju.kodi - from windows

**Comment by notoco** [comment]
Interesting fact - with integration with Upnext turned off (in Netflix settings) everything works fine - of course, with the difference that moint is displayed not at the beginning of the payroll, but at the time set at upnext.
It's something on the combination of UpNext, Signal Addons and Netflix

**Comment by CastagnaIT** [comment]
i'm testing with the official https://github.com/im85288/service.upnext 
but of course same issue

however seem the data dict passed from nf addon to upnext addon
that contains "play_info" with "play_path" value
is returned to nf addon with a wrong encoding

I've tried several cases with decode, encode but to now nothing works...
(data returned in nfsession.py, play_callback())

PS if someone else wants to test:
tv show: Cabañas extraordinarias en Gales
with a profile in spanish language

**Comment by notoco** [comment]
I checked with the official UpNext version, the git version, with any patches that were in the official UpNext repo - the same issue.

> however seem the data dict passed from nf addon to upnext addon
that contains "play_info" with "play_path" value
is returned to nf addon with a wrong encoding

So is this UpNext bug?
Maybe I'll call @dagwieers  - I see that it is actively improving both the Netflix and UpNext plugins

**Comment by CastagnaIT** [comment]
it is possible that this problem has always been there
i've never tested tvshow titles that have special characters

in netflix addon regarding upnext no changes were made

**Comment by notoco** [comment]
I have also never tested series with special characters. It happened quite by accident when reinstalling kodi and adding a few series that I didn't have before.

I also reviewed changes in Netflix and UpNext - and everything indicates that this error has simply been there for centuries

**Comment by CastagnaIT** [comment]
i think found the problem are in nf addon missing an decode + encode
You do a test yourself to confirm:
[plugin.video.netflix_0.15.7_20191029_test.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3783905/plugin.video.netflix_0.15.7_20191029_test.zip)

let me know

**Comment by notoco** [comment]
BTW for several weeks I was fighting with UpNext not working randomly, with not marking episodes as viewed ... After this patch everything works

**Comment by CastagnaIT** [comment]
i'm glad another bug solved 😊
sometimes it happens to me to not understand why something does not work for a long time...
