### ISSUE TITLE
Sorting Movies and Series by "Added" Date

### ISSUE THREAD

**Issue by christiancloudibility** [CastagnaIT/plugin.video.netflix#279]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature

### Describe your request
I'd like to know, if there is the chance to get a list of items sorted by last added or something similiar, as it could be hard to scroll through stuff, wenn it is starting with "a" and has multiple sites

WAF would get much more higher in my case :P 
When checking categories in Netflix, they are sorted by a algorythm made by netflix, which should be shown first.
That should make find a pleasant movie easier than scrolling from "a" down

If I simply did not find that point to sort it the correct way, simply close the issue again :D 

If I can help you anyhow, let me know!

Greetings,

Chris

**Comment by CastagnaIT** [comment]
In addon settings you can choose the sort method for some lists
in "Main menu items" settings page
netflix api does not offer other sorting systems
at least i do not know about it because there is no documentations

**Comment by christiancloudibility** [comment]
Ok, I have to check that, when I am at home again, thank you so far.
I know, that in the old Netflix-Addon, the sorting was different and not alphabetical.
Maybe that can be a hint?
Or Netflix simply removed the api for that feature :/

**Comment by CastagnaIT** [comment]
you can not compare with the old addon
becouse the old addon has many feature lacks and not api updated
so, the result lists in old addon are not paginated
and the results are limited to a certain number of items

**Comment by CastagnaIT** [comment]
here the results are paginated, and requested with a different method that allows thousands of results.
so the sort order is executed by netflix servers and not made by Kodi's methods

**Comment by christiancloudibility** [comment]
Ok I understand.
Maybe the pagination is leading to the different sorting mechanism?
But in that case, there will be no chance to change that, checked the api results given back by netfllix and it seems, that there is nothing useful for different mechanism :/

If you don't have any idea how to get it working, feel free to close it again.

Nevertheless thank you, that addon is realy great :) :+1:

**Comment by CastagnaIT** [comment]
I know how it works, otherwise I didn't implement it. What I meant was that I don't know if there are any other request commands for different sort orders
To now this sorting methods are implemented:
![image](https://user-images.githubusercontent.com/3257156/67845136-40aa0700-faff-11e9-8e37-b9d3925a1d5e.png)

on api request this sort order types are coded as:
['az', 'za', 'su', 'yr']

since there is no documentation I am not able to tell you if there are other working types of sort orders

**Comment by christiancloudibility** [comment]
Ok but the first seems to be what I am looking for!

so I have to use " su " as sorting type, will try that, thanks :)
