### ISSUE TITLE
[Feature] Release using GIT Release or Kodi Repository

### ISSUE THREAD

**Issue by guindous** [CastagnaIT/plugin.video.netflix#28]
## General information
It will be a lot easier to keep updated to release using [release github page
](https://github.com/CastagnaIT/plugin.video.netflix/releases) or, even better, using Kodi Repository, instead of releasing by mediafare external page.

If you explain how is your release/packaging process maybe I could help you.

**Comment by CastagnaIT** [comment]
it would be nice to have automatic releases, i can not do everything, it is already so much what I do in the short time I have. Here so many people ask and no one helps.

from what I've seen, but i could be wrong, someone needs to manage a repository with its own configuration of files, where the releases are inserted, maybe it's simpler than I think, 
but i don't have time to study how it works.

if you are able to create this repository or use an existing one like kodinerds (but I don't know who manages it and if they agree) there's no problem.

of course those who take responsibility will have to do so constantly and find a solution in the case no longer want to continue.

My releases are simple, when i establish the commit "version bump" is the next release.

through git shell you can get the repo files and go back to the commit "version bump" in case i publish other commits after the "version bump" commit

**Comment by Dnkhatri** [comment]
The 13 version branch developers don't seem to be interested in this branch. So currently we have 2 different branches. Maybe this branch should be renamed to something else and we can request the other branch maintainers to add it to their repo as well.

**Comment by notoco** [comment]
Fast and dirty:
Be better - create a new CastagnaIT repository (ex. repository.CastagnaIT). Upload the current contents of the plugin.video.netflix repository and move there with all the work (or throw sources that you want to share as a final job)
Put the generator.py script in repo https://github.com/notoco/univ/blob/master/generator.py  (python3 - with my modification - does not remove old versions of zip files) and after changing the version in addon.xml in plugin.video.netflix, run it - it will generate the proper zip, addons.xml, addons.xml.md5
This way you have files that are necessary to create your own repo.

Then create the repository.CastagnaIT directory in CastagnaIT/repository.CastagnaIT/ and add the following file after obvious modifications:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="repository.CastagnaIT" name="CastagnaIT repository" version="1.0.0" provider-name="CastagnaIT">
		<extension point="xbmc.addon.repository" name="CastagnaIT repository">
			<dir>
				<info>https://raw.githubusercontent.com/CastagnaIT/repository.CastagnaIT/master/addons.xml</info>
				<checksum>https://raw.githubusercontent.com/CastagnaIT/repository.CastagnaIT/master/addons.xml.md5</checksum>
				<datadir zip="true">https://github.com/CastagnaIT/repository.CastagnaIT/raw/master/zip</datadir>
			</dir>
		</extension>
		<extension point="xbmc.addon.metadata">
			<summary>CastagnaIT repository</summary>
			<description>Description</description>
			<platform>all</platform>
			<assets>
				<icon>icon.png</icon>
			</assets>
		</extension>
</addon>
```

Then start again the generator.py 

You will have created a zip file for the repository, zips for the plugin, and automatically update all data required for the kodi repository. You can transfer the /zip/repository.CastagnaIT/repository.CastagnaIT-1.0.0.zip file to the main folder
At the next change in the plugin and the desire to release a new version, eg 14b23-daily20190320 - you change the numbering in addon.xml for the plugin and run the script again.

**Comment by guindous** [comment]
Hi @CastagnaIT! First you're right: it's a hard work to keep this project working, so **thanks for your efforts and time!**. 
Sorry for lagged response, but it was for a good reason. Following @notoco's **GREAT** Q&D instructions i've built a custom repository to make it easy installation and update of the plugin at https://github.com/guindous/repository.guindous
Also, to KISS maintenance process, I @[ developed a bash script](https://github.com/guindous/repository.guindous/blob/master/updaterepo.sh) that automatically detects last "version bump" and update the Kodi repo. 
So if you wish:
1) Link the repo plugin to README install process.
2) I could make you collaborator of github repo, so you could publish version (ASAP), as I said, just running a shell script (tested only on linux). Or, alternatively, contact me when you generate a new version and I help you keep Kodi repo updated.

**Comment by notoco** [comment]
@guindous - to autoupdate please change version number to similar:
14b23-daily2019032 - for daily builds
14b24 - for betas

**Comment by guindous** [comment]
Hi @notoco, are you talking about Netflix plugin version number (https://github.com/guindous/repository.guindous/blob/master/addons.xml#L21), isn't it? If so, to make process fully automatic this is something that we could coordinate with @CastagnaIT, instead of manually change it.
@CastagnaIT if you wan't we could coordinate to make next version number "update compatible" and testing repo before make it public. Maybe we could evolve versioning to non beta versioning. So far this is the only 0.14 fork that is actively developed. Maybe is time to release 0.14! 😄

**Comment by CastagnaIT** [comment]
I can't change the version format, that is the versioning format of kodi

I don't understand how you split daily updates and releases.
if a user only wants releases without daily build how should he do it?

if this file is ready i can add it in the repository: https://github.com/notoco/univ/blob/master/generator.py

**Comment by CastagnaIT** [comment]
To exit from the beta you must complete the objectives that you can find in the projects tab...is not a short ride :( :)

**Comment by notoco** [comment]
@CastagnaIT - In my repo, I give the daily version - it's a polygon for users of the Polish forum kodiwpigulce.pl - used only by me and a few people from there. Version numbering yes - it does not correspond to the numbering required by kodi. But ... but it works;) When the next beta is released, using the numbering 14b23.20190330 and 14b24 - as the version to be updated, kodi will select 14b24.
You can also make 2 separate repositories - for the daily version and for the beta / official version. Then whoever wants, will use the daily version (like me in my repo) and who less brave will be able to use the beta / official version. Look at my github:  https://github.com/notoco/univ/tree/master/zip/plugin.video.netflix - there are versions - the last one is always visible in the repo. yes - a few days ago I realized that I have an incorrect numbering - but now it's ok. As I said - this is a "private" repo used by several people from the forum kodiwpigulce.pl and my friends. If you like - you can use them as a testing ground for easier installation of the daily version.

**Comment by guindous** [comment]
@CastagnaIT let's try to figure out how to help you to make this process easy and effortless as posible.
Following this [version guidelines](https://kodi.wiki/view/Addon.xml#version_attribute) we can keep nowadays versioning and Kodi _should_ auto detect new beta versions and auto update. My ideas of simplify versioning for support Kodi's auto update was based on @notoco experience. As he pointed out in different post in this thread it doesn't work as expected. Changing versioning is not a short ride: is a posible workaround to simplify plugin install and update. 
IMHO the simple way to test my repo and validate the publishing scripts and autoupdate process is to wait your next beta25.
After validating correct working of autoupdate, my offer of using that repo for official publishing keeps open.
Thanks @notoco for all your explanations and experience.

**Comment by CastagnaIT** [comment]
thanks to your examples i finally managed to create my own repository for updates,
i prefer to leave to you the repositories for the daily build,
i only commit to releases

**Comment by notoco** [comment]
Great news. Everything works perfectly. Very good decision on the repository only with beta versions. If anyone wants, then the daily versions can be sucked in from me or from mediafire.

**Comment by guindous** [comment]
Good to hear this @CastagnaIT! Just to give some feedback to @notoco about versioning, I tried autoupdate using original versioning number (0.14.0~beta24) on my own repo and everything works great.

**Comment by notoco** [comment]
I have numbering
plugin.video.netflix-0.14.0 ~ beta23.20190407build2.zip has updated to
plugin.video.netflix-0.14.0 ~ beta24 this beautifully updated to
plugin.video.netflix-0.14.0 ~ beta24.20190414.zip
Także wszystko działa...

**Comment by ludi113** [comment]
I can confirm that the update from beta23.20190407build2.zip to beta24 by using the new CastagnaIT kodi repo worked here, too. 

By the way, the kodi repository is available here: 
https://github.com/CastagnaIT

Finally, I would suggest to reopen (if possible) this bug thread and edit the title with the keyword resolved: it might help increasing the visibility of the kodi repository.

**Comment by CastagnaIT** [comment]
I don't reopen the issue, the readme on the main page is used for this purpose.
The issue pages have other purposes and there's also the kodi forum

**Comment by ludi113** [comment]
I did not notice that you updated the Readme with the information about the kodi repository and you are right: the readme is a more appropriate location for the information than a resolved bug thread. 

Sorry for the noise and thanks for the great effort you are putting in the plugin.
