### ISSUE TITLE
Playback fails with "This title is not available to watch instantly. Please try another title."

### ISSUE THREAD

**Issue by generalks** [CastagnaIT/plugin.video.netflix#282]
#### Your Environment
- Netflix add-on version: 0.15.8
- Operating system version/name: Recalbox for Rockpro64 190603 (mrfixit) (Buildroot 2018.02.03 (kernel: Linux 4.4.180) , Kodi 18.0-Alpha 3
- Device model:  Rockpro64 RK3399

Used Operating system:
* [ ] Android
* [ ] iOS
* [x ] Linux (kind of)
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
 When attempting to view a netflix stream, the wheel spins for a while before displaying "This title is not available to watch instantly. Please try another title."

Log: https://pastebin.com/wvW0daCs

#### Expected behavior

Video begins to play

#### Actual behavior

Video does not play. Error is presented.

#### Steps to reproduce the behavior

1. Install addon from repo
2.  Login to Netflix
3.  Attempt to view stream

### Debug log

The debug log can be found here: https://pastebin.com/wvW0daCs

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source <

**Comment by CastagnaIT** [comment]
is often due to the fact that the quality playback settings in the settings of the netflix site have been changed, try to put the settings to "Auto".

if it continues to do so, try the expert settings of addon to enable VP9 profile

**Comment by generalks** [comment]
Hi,

Tried changing playback quality to 'Auto' and received the same error. Then tried enabling VP9 too, no change.

Thanks

**Comment by CastagnaIT** [comment]
in the addon expert settings try also do disable DolbyDigital
Press OK to save settings,
reopen expert settings and try Reset ESN

**Comment by CastagnaIT** [comment]
check also if in your country netflix is not in trouble:
https://help.netflix.com/en/is-netflix-down

**Comment by generalks** [comment]
Thanks for that. Disabled DD & reset ESN, no change.

Netflix is working in web browser with no issues + no reported issues in my country.

**Comment by CastagnaIT** [comment]
you have already tried to switch to oher profiles? incuded kids?

**Comment by generalks** [comment]
Just tried it then. Same result.

**Comment by CastagnaIT** [comment]
if you don't use VPN or Proxies that can create problems
i don't have any other solution at the moment

**Comment by CastagnaIT** [comment]
you can also try to delete two files (with Kodi closed):
in: ~/.kodi/userdata/addon_data/plugin.video.netflix
one like: "COOKIE_" .........with a series of characters
one: msl_data.json

**Comment by generalks** [comment]
Done, same result.

I will post a new log later today if that helps.

I did notice a missing dependency- script.module.win_inet._pton

Would that contribute to this issue?

**Comment by CastagnaIT** [comment]
it is a component for windows doesn't seem to have any relationship with the addon,
so you are using a very old and unstable version of kodi
it would be appropriate to update kodi to the current version
to have all components up to date

**Comment by Badsheep** [comment]
Hello Castagnal,

I'm sorry but I have the same issue here...
Mac OS
Leia 18.4 (up to date)
Netflix 0.15.8

Log is [here](https://controlc.com/90009f3c)

Thanks !

**Comment by CastagnaIT** [comment]
you have tried to disable HEVC profile in expert settings?

**Comment by Badsheep** [comment]
I just did - same result.
I tried to enable VP9 too, same result.

**Comment by CastagnaIT** [comment]
have you set a manual ESN?

**Comment by Badsheep** [comment]
No...
Do I have to ? On Mac OS ?

**Comment by CastagnaIT** [comment]
please provide a new log

**Comment by Badsheep** [comment]
OK

**Comment by Badsheep** [comment]
[Here it is](http://78.194.163.41:30916/share/VYL_jmY_YmWbOYe2/KodiLog191111.rtf).
(sorry, too big for pastebin)

**Comment by CastagnaIT** [comment]
lenght is not a problem, but for next times use service like hastebin:
https://paste.kodi.tv/tocakonahu.kodi

parts are still missing in the log and this is making me suspicious..

Are you playing video through a widget of an skin?
Are you playing video from your library without ever opening the add-on?

**Comment by Badsheep** [comment]
Answers are no and no...
I’m using the Pellucid skin (since always and it’s been working not too bad)
I’ll try without the skin and will tell you

**Comment by Badsheep** [comment]
I just tried with Estuary : same result.

**Comment by CastagnaIT** [comment]
the log?

**Comment by Badsheep** [comment]
[Here](https://paste.kodi.tv/eluyeqeyuk.kodi)

**Comment by Badsheep** [comment]
Wait ! I tested on a more recent macbook, and everything works fine...
With Leia 18.4, Netflix 0.15.8 and same Mac OS

So the problem must be mine.

Sorry for that... I'll search what's going on by my side.

Thanks for your help !

**Comment by CastagnaIT** [comment]
[plugin.video.netflix_0.15.8_20191111.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3833158/plugin.video.netflix_0.15.8_20191111.zip)
can you test with this?

**Comment by Badsheep** [comment]
I had a problem to install it.
I refused saying I needed a dependancy "Script module future"
After a quick search I found it on the web, installed it.
Then I could install your Netflix Add-on.

But 1st bug :
When I enter the mail of the account it makes an ASCI mistake.
Then when I try to launch it I have a Add-on Signal Call Time Out error
See Log [here](https://paste.kodi.tv/tazacuniba.kodi).

**Comment by CastagnaIT** [comment]
Sorry here
[plugin.video.netflix_0.15.8_20191112.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3836200/plugin.video.netflix_0.15.8_20191112.zip)

**Comment by Badsheep** [comment]
Hi !

Sorry but I won’t be home for a few days, I’ll let you know as soon as I can... Thanks !

**Comment by Badsheep** [comment]
Hello,

I just tried your last test (20191112) : same error...

**Comment by Badsheep** [comment]
Hello, some fresh news : 

I just tried a "from scratch" installation, by renaming my "Kodi" folder in my library, install just your plugin : it works perfectly. So the bug seems definitely to come from my configuration (which is a bit complicated).

For now let me do my tests and don't worry about my problem, I'm sure I'll come in a few days to tell  you the bug is located (I hope)

Thanks for your help !!

**Comment by CastagnaIT** [comment]
good, perhaps reconfiguring a little at a time as it was before you will probably find the problem

**Comment by CastagnaIT** [comment]
@generalks suggest you to try to reinstall all with latest Kodi build
and install Netflix addon but the Daily build, link on main page

module.win_inet._pton should only be needed on Windows

**Comment by Badsheep** [comment]
Hello,

Well I keep my good'old 18.4 version, because it's a custom version with some modifications in the ways it handles the video upscaling.

And it was definitely my old installation that was corrupted (too many tests/installations/unsinstalls of addons probably...).

With this sane reinstall, everything works fine.

Thanks again for your help CastagnalT !

**Comment by ryangodammit** [comment]
I've got exactly the same error on Libreelec

It started when I was running 15.3, out of the blue. I upgraded to 15.8 and the error persists

Here is my log  https://paste.kodi.tv/ajijexubus.kodi.

I've tried intalling 15.9 and 15.10, but there is an error about script.module.future, which stops it from updating. The log for that is https://paste.kodi.tv/acowedudar.kodi

I'll try the version of 15.8 you posted in the comment above

**Comment by ryangodammit** [comment]
Managed to install script module future so updated to 15.10, but still same playback error

**Comment by ryangodammit** [comment]
> Hello, some fresh news :
> 
> I just tried a "from scratch" installation, by renaming my "Kodi" folder in my library, install just your plugin : it works perfectly. So the bug seems definitely to come from my configuration (which is a bit complicated).
> 
> For now let me do my tests and don't worry about my problem, I'm sure I'll come in a few days to tell you the bug is located (I hope)
> 
> Thanks for your help !!

Can you elaborate on what you did here? It sounds like that's what I need to do too

**Comment by ryangodammit** [comment]
Got it!!

My Libreelec wasn't set to auto update all addons.

I enabled it and all of a sudden a whole lot of different updates came flooding in, then it prompted me to download a new version of widevine. Then it worked!

**Comment by CastagnaIT** [comment]
closed for inactivity of author

**Comment by Paco8** [comment]
I've got the same problem since last friday in my nvidia shield but the official netflix app doesn't work either, same error.
