### ISSUE TITLE
T95Z PLUS black screen when play 1080p videos

### ISSUE THREAD

**Issue by basha1963** [CastagnaIT/plugin.video.netflix#287]
#### Your Environment
- Netflix add-on version: 15.8
- Operating system version/name:  androin 7.1.2
- Device model:  T95Z PLUSE                           

ON KODI 18.4 i GETTING BLACK SCREEN WITH 1080 AND NO SOUND

**Comment by CastagnaIT** [comment]
First, make sure that in the website settings streaming quality is set to High
In the addon settings use these settings, go to Expert page and set:
Enable VP9 profiles to OFF
Enable HEVC profiles to ON
Force support to HDCP 2.2 to OFF

Press Ok to save settings

After reopen settings and go to Expert page:
Open InputStream Adaptive settings and set:
Override HDCP status to ON
Stream selection to Auto
Ignore Display Resolution to OFF
Min Bandwidth to 0
Max Bandwidth to 0

In the end always in expert settings click to Reset ESN and wait the addon return to profiles page,
so try to play a video

**Comment by basha1963** [comment]
thank you for ur help but still getting black screen and no sound

**Comment by basha1963** [comment]
and mt tv box on still on L3

**Comment by CastagnaIT** [comment]
i have found this old discussion: https://github.com/asciidisco/plugin.video.netflix/issues/394
it is possible that the firmware of that device has an problem

it would be better to see a full kodi debug log and also an adb logcat as described in that discussion taken from a fresh boot and after played a video

and also, there is an netflix ESN showed in some android settings of device?
if it is present, send me a screenshot to my private email in the first page of github, that I'll check how is composed.
if it is not present, send the ESN displayed in the official Netflix app settings

**Comment by notoco** [comment]
# #

**Comment by basha1963** [comment]
mail had been send to your help will appreciated

**Comment by CastagnaIT** [comment]
you are using the oldest addon version:
> 2019-11-08 16:14:36.577 T:23409  NOTICE: ADDON: plugin.video.netflix v0.13.8 installed

remove this addon, and remove also user data when prompt, so install the latest version.

So after:
- Do what i wrote above again for the settings.
- Here there is the instructions to get a right Kodi log file: https://kodi.wiki/view/Log_file/Easy

And also:
- You didn't send me ESN as requested above ONLY the ESN send to my email NOT the LOGS,
the logs must be attached here
- You have not extracted the android logcat

**Comment by CastagnaIT** [comment]
closed for inactivity
