### ISSUE TITLE
Only 25 audio channels are availables

### ISSUE THREAD

**Issue by gsurelle** [CastagnaIT/plugin.video.netflix#288]
#### Your Environment
- Netflix add-on version: v0.15.8
- Operating system version/name: XUbuntu

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
The plugin fetch only 25 audio langage types. When there is more, the user cannot select the langage he want. Maybe (it's seems) that subtitles are not availables in that case.

#### Expected behavior
All of the langages availables for the video can be selected. 

#### Actual behavior
Only 25 langages are available.

#### Steps to reproduce the behavior
1. Select a video with a lot of english langage channel (for example : S01E01 of The Crown).
2. Try to select the french audio channel.

**Comment by CastagnaIT** [comment]
in the Crown there are 12 audio language not 25.

you have surely enabled the debug mode of the streams selection in the InputStream Adaptive settings.
you do not have to set the `Stream selection` to `manual` mode is only to debug scope
must always be left on Auto

**Comment by gsurelle** [comment]
That was that. Sorry for the disturb.
