### ISSUE TITLE
Library syncing only syncs from primary profile, not the auto login profile

### ISSUE THREAD

**Issue by brainfork** [CastagnaIT/plugin.video.netflix#289]
#### Your Environment
- Netflix add-on version: 0,15.8
- Operating system version/name: Windows 7
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

#### Expected behavior

When the option to enable syncing is enabled, content that is saved in "My List" of the currently selected auto login profile should be synced to the local library

#### Actual behavior

When the option to enable syncing is enabled, content that is saved in "My List" of the primary account profile is synced to the local library

#### Steps to reproduce the behavior

1. Set auto Login to a secondary account
2. Enable library syncing
3. Watch as content from the primary account is synced

#### Possible fix

Set the library syncing script to use the auto login profile, not the primary profile

### Debug log

The debug log can be found here: 

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
> Set the library syncing script to use the auto login profile, not the primary profile

is not so simple, between saying and doing there is the sea..
I'm working on it,
it was enough to read the right post: https://github.com/CastagnaIT/plugin.video.netflix/issues/285

**Comment by brainfork** [comment]
> between saying and doing there is the sea..

That is a great phrase.  I didn't realize #285 was the same issue- I was searching for "syncing" instead of "auto-update."  If you want to close this ticket, feel free since it looks like it's covered under the earlier one.

**Comment by CastagnaIT** [comment]
do you have a possibility of helping to run tests?

**Comment by brainfork** [comment]
I can help with tests

**Comment by CastagnaIT** [comment]
Good, try this and let me know

if needed instructions are here
https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-to-export-and-sync-tv-shows-and-movies-in-Kodi-library

[plugin.video.netflix_0.15.8_20191112_libtest1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3836280/plugin.video.netflix_0.15.8_20191112_libtest1.zip)

**Comment by CastagnaIT** [comment]
PR merged
