### ISSUE TITLE
Unable to play some shows

### ISSUE THREAD

**Issue by Astra3** [CastagnaIT/plugin.video.netflix#290]
#### Your Environment
- Netflix add-on version: 0.15.8
- Operating system version/name: Ubuntu 18.04.3
- Device model:  HP 15-db0xxx laptop

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

Region: Czech republic

### Describe the bug

I can't play some shows, i.e. Black Mirror, Milada, The End of the F***ing World but there are also show I can play, like Peppa Pig. I can play everything in browser. When I try to play for example Black Mirror, it loads forever.

#### Expected behavior

I should be able to watch everything that's available in my region.

#### Actual behavior

Playing something like The End of the F***ing world results in infinite loading. When I press Esc to cancel this loading, Kodi is showing that the episode I chose is playing in background. When I try to stop it, Kodi freezes and I have to kill it. At the end of the report I included a video.

#### Steps to reproduce the behavior

1. Launch Netflix addon
2. Choose some random show or movie
3. Wait if it plays or not

#### Possible fix

I wasn't able to find anything that would help resolving the bug.

### Debug log

The debug log can be found here: [important.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3827276/important.log)

#### Installation
* [x] I'm using the official CastagnaIT repo 
* [ ] I'm using a different source 

#### Videos

I've created a video showing the problem: [Youtube video link](https://youtu.be/X29PKvflJ7c)
You can see there I can play something and at the end I showed how I can freeze Kodi by stopping the video.

**Comment by wintuxx** [comment]
Hi,
Which inputstream is installed?

gesendet mobil

Astra3 <notifications@github.com> schrieb am Sa., 9. Nov. 2019, 13:39:

**Comment by Astra3** [comment]
Hi,
I have InputStream Adaptive 2.4.2 by peak3d

**Comment by wintuxx** [comment]
I had the same problem. You need inputstream 2.4.2.

There is a small problem, you can get it not seperatly. You must install
the nightly of Kodi 18.4


gesendet mobil

Joerg <wintuxx@gmail.com> schrieb am Sa., 9. Nov. 2019, 13:56:

**Comment by wintuxx** [comment]
Okay that's the right inputstream.

That was my problem.

Hopefully someone others can help.



gesendet mobil

Astra3 <notifications@github.com> schrieb am Sa., 9. Nov. 2019, 13:58:

**Comment by CastagnaIT** [comment]
seem you have wrong settings
turn off HEVC
turn on VP9
turn off - force support HDCP 2.2

try to play

if again not work, in inputstream
turn off override HDCP status

**Comment by Astra3** [comment]
Yes, thank you it worked. I shouldn't dig in these settings anymore. Sorry fot the disturb.
