### ISSUE TITLE
Update to python3 support

### ISSUE THREAD

**Issue by ezar** [CastagnaIT/plugin.video.netflix#293]
Original repo migrate to python3:
https://github.com/asciidisco/plugin.video.netflix

>> https://github.com/asciidisco/plugin.video.netflix/commit/ecdd4821cae1db45c25303b42f57dcb01e2d66c8

**Comment by CastagnaIT** [comment]
This, what does it mean?

**Comment by ccope** [comment]
That commit could have been a good starting point for the python 3 conversion but it doesn't seem relevant now that #211  is almost done.

**Comment by CastagnaIT** [comment]
I understand but here the conversion began before that commit, the problem is that it has remained blocked due to Kodi 19 that currently is not yet fully ready, except for LibreELEC build
