### ISSUE TITLE
My List sorted as on the Netflix web UI?  

### ISSUE THREAD

**Issue by chinenual** [CastagnaIT/plugin.video.netflix#295]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [X] change an existing feature

### Describe your request

Reading issue #279 I see that Netflix supports 4 different sort methods - "Suggested for you" "date added", A-Z and Z-A.   Is it possible to retrieve the list in the order as displayed and managed via the Netflix web UI?  (perhaps by requesting "unsorted" data?)

#### Describe the use case

My wife and I use our laptops to managed My List on Netflix's website -- we drag things we'd like to watch "soon" to the top, and let less urgent things fall to the bottom of the list.   We'd like to preserve that order when visiting My List on the Kodi add-on.

**Comment by CastagnaIT** [comment]
In the addon setting
go to Main menu items page
for some lists there is the possibility to sort order items like website

**Comment by chinenual** [comment]
That would be great!   However, I only see the four options (Suggestions, Date Added, A-Z, Z-A) on all the sort drop downs in my configure menu.

FWIW, I'm using 0.15.8 of the add-on - is this "like website" option available in that version?

**Comment by CastagnaIT** [comment]
I don't understand how you can order "my list" through the website

**Comment by chinenual** [comment]
Select My List from the netflix.com main menu, then "drag" a list item up or down, or hover over a list item and select "Move to Top".

**Comment by CastagnaIT** [comment]
![image](https://user-images.githubusercontent.com/3257156/68620387-a4540d00-04cd-11ea-9e79-040cf4fde3de.png)
I have this but i can't drag items and no move to top... What am i doing wrong?

**Comment by chinenual** [comment]
Interesting!   My My List is displayed as a vertical list (as below).   In my account profile, there is an item "Order in my List" -- it supports two values "Netflix Suggests" and "Manual Ordering" -- i have Manual ordering selected - maybe that's not the default?

![Screen Shot 2019-11-11 at 3 58 39 PM](https://user-images.githubusercontent.com/1839327/68620854-5d99ef00-049c-11ea-9d2c-ed17466f6865.png)

**Comment by CastagnaIT** [comment]
wow! i don't have any of this options... :(
there is nothing even in the account configuration...
I can try an experiment for you tomorrow, I'll let you know when it's ready

**Comment by chinenual** [comment]
FWIW, account config for me is the right-most dropdown (looks like a smiling avatar) on the main menu, then Account, then towards the bottom there's a group of items with group time "My Profile" -- the "Order in my List" link is in that group.

**Comment by CastagnaIT** [comment]
i understand but nothing to me...

**Comment by notoco** [comment]
It is not possible for me either.

**Comment by CastagnaIT** [comment]
i have tried some experiments but nothing worked,
the only way is to wait for this feature to be available to everyone
What country are you from?

I have thought to remove the order, if it works it is a temporary solution only for you.
Obviously if you update the add-on in the future you will lose this workaround
[plugin.video.netflix_0.15.8_20191112.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3835278/plugin.video.netflix_0.15.8_20191112.zip)

**Comment by chinenual** [comment]
It works!   Thank you!

FWIW: I'm in the US.

Perhaps you can just conditionalize this unordered display as a new enumeration in the sort order dropdown in the next mainline release?

**Comment by CastagnaIT** [comment]
I'll try to take a look if and how you can do it

**Comment by CastagnaIT** [comment]
I don't understand why netflix doesn't offer the same service in other countries as well....

**Comment by chinenual** [comment]
For anyone stumbling on this issue and wondering where the manual ordering config is set for me, this is what my Account settings page looks like:

![Screen Shot 2019-11-12 at 9 39 56 AM](https://user-images.githubusercontent.com/1839327/68681137-dba7d580-0530-11ea-9fb7-454e4b5c4840.png)

and these are the options you get after clicking on "Order in My List":

![Screen Shot 2019-11-12 at 9 44 13 AM](https://user-images.githubusercontent.com/1839327/68681215-07c35680-0531-11ea-9e15-f2861928d36a.png)

**Comment by CastagnaIT** [comment]
From netflix faq
![image](https://user-images.githubusercontent.com/3257156/68683564-496ef400-0567-11ea-91c5-072a75bed0ca.png)
this is allowed only on US 😑

**Comment by chinenual** [comment]
We that really sucks -- it's a very useful feature and there's nothing region specific about it!

If you'd like, I'll take a stab at creating a pull request that conditionalizes this functionality(?)

**Comment by CastagnaIT** [comment]
give a try, now you can configure it by addon settings
[plugin.video.netflix_0.15.8_20191112.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3837081/plugin.video.netflix_0.15.8_20191112.zip)

**Comment by chinenual** [comment]
Works!

**Comment by CastagnaIT** [comment]
good i'm glad, now i merge changes
