### ISSUE TITLE
Feature: Add an option to disable subtitles

### ISSUE THREAD

**Issue by sks316** [CastagnaIT/plugin.video.netflix#3]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?
Yes.
### Description

In my experience, every time you play a video through this add-on, it will have subtitles. I don't like that, so I'd like to have a way to disable them.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [x] I´m using a different source (Please tell which)
I downloaded the ZIP via the Clone or download option at https://github.com/CastagnaIT/plugin.video.netflix
### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Running on Raspberry Pi 3 Model B

**Comment by wintuxx** [comment]
That is not a addon issue.
you can deactivate the subtitles via kodi in the settings.

**Comment by sks316** [comment]
@wintuxx Thanks, I couldn't find it when I made this issue. I found it now.

**Comment by CastagnaIT** [comment]
In general, you should set the kodi player to "force-only" subtitle setting.
In this way the subtitles are displayed only when strictly necessary (e.g. place descriptions).

In any case now i fixed the problem with saving audio/subtitle preferences in netflix addon, now when you turn them off they should always remain off.
