### ISSUE TITLE
KeyError "lolomos"??

### ISSUE THREAD

**Issue by chewvodka** [CastagnaIT/plugin.video.netflix#30]
I am using this plugin on 2 Raspberry Pi 3's.  I had reported a few weeks ago, I believe, that the current build at the time (v0.14.0~Beta22 `20190308build2`) was working fine.  It was good for a few days, then something changed and it stopped working right.  I'm not sure how or where.  Because I have 2 Pi's, the problem is very bizarre because it works on the device in my bedroom (primary profile) but not the one in the living room (secondary profile/for Dad).  Both devices are on the exact same OS, using the exact same skin, and the exact same credentials.  The only difference is that he's using his own profile.  

When he reboots and starts up the Pi, it starts LibreELEC (latest version `9.0.1`) and then Kodi.  After a short while, maybe 10 seconds, it pops up a notice that the Netflix Background Services had started.  I had to enable this for him because he's impatient and wasn't waiting long enough for Netflix to login before going and trying to watch something.  Anyway, after that pop up, he'll go and try to open the Netflix addon.  After maybe 2 seconds, he gets this error:
```
KeyError: lolomos
```
It then reports that it logged this to the Kodi log file, and his only option is to press [OK] button.  After doing so, he's back on the main screen.  Netflix never loads.  He's been trying this over and over again for like 3-4 days now.  At first I thought maybe it lost my login credentials, so I had him go into the settings and sign out.  We then rebooted and signed back in.  It says `Login Successful` on the screen at that point.  The Netflix addon then loads up the list of available profiles.  Once he selects a profile though, the error pops up again.  Just today I came home from work and we tried again with forcing a new login with my credentials.  Then I thought maybe the problem is with his secondary profile, so I had him pick mine instead.  Once again, the error pops up.  I'm completely lost on how to fix this now.  I mean, it works fine for me!

I had him turn on the debug logging then reboot.  Once up I had him go and try Netflix again so the error would get logged.  We then shutdown.  Here is the log in it's entirety:

https://paste.kodi.tv/jonirusuvi.kodi

The first line of `lolomos` comes in on 1323, with the full blown crash at 1333.  Any ideas on what could be causing it?  Anything I can do to fix it?  I'm actually going to try a down and dirty uninstall/reinstall again (after uninstalling, verify no paths remain).

Any help here would be greatly appreciated.  Not just from my Dad (so he can watch his shows again) but from me as well (so I don't have to keep listening to him complain about it every day lol!).

**Comment by chewvodka** [comment]
Fixed?

I just saw you had posted a version bump to beta 23.  We uninstalled the beta 22 and installed this one in it's place.  Looks like it's working now.  I'll leave this open for another day just in case he has issues again.  Thanks!

**Comment by CastagnaIT** [comment]
yes that's an error of previous releases, already corrected

**Comment by chewvodka** [comment]
Still working great. Thanks!
