### ISSUE TITLE
Mobile plan cannot watch with this add on

### ISSUE THREAD

**Issue by sardan91** [CastagnaIT/plugin.video.netflix#303]
#### Your Environment
- Netflix add-on version: 0.15.8
- Operating system version/name: android 
- Device model:  mi Max 3,mi pad 4,s9+

Used Operating system:
* [ ✔️] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Using kodi latest version,cannot play video on mobile plan,  nothing comes out when select movie to play mybe its detect as a pc because this plan supposed to play on mobile  & tablet only..in other hand im tried using my mothers plan which basic plan can play movie while in Mobile plan can't.

**Comment by CastagnaIT** [comment]
Need the log to do with Kodi debug enabled,
How to get the log? Read Kodi wiki: https://kodi.wiki/view/Log_file/Easy
