### ISSUE TITLE
Locale_id

### ISSUE THREAD

**Issue by CyberExplorer** [CastagnaIT/plugin.video.netflix#31]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

beta23

### Description

Pluging cant open after update to beta23. It says locale_id. My lang at netflix is Turkish.

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec 9.0.1 on RPi3

## Debug log

https://paste.ee/p/hZOAD

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

**Comment by CastagnaIT** [comment]
my mistake, fixed, later you can download the dailybuild
