### ISSUE TITLE
Addon not work

### ISSUE THREAD

**Issue by yabba235** [CastagnaIT/plugin.video.netflix#312]
#### Your Environment
- Netflix add-on version: 0.15.9
- Operating system version/name: Ubuntu 19.04 disco
- Device model:  ZBOX MI553

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Expected behavior
Can't login in Netflix account

#### Actual behavior

Error textbox appears

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

https://paste.ubuntu.com/p/xm3RFv2Srv/

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by yabba235** [comment]
Can't login in Netflix account after  install addon.

**Comment by CastagnaIT** [comment]
You can't use Kodi 19 is not yet ready to run nf addon

**Comment by yabba235** [comment]
And when will be ready ?
Now is time to testing it.


W dniu sob., 16.11.2019 o 11:11 Stefano Gottardo <notifications@github.com>
napisał(a):

**Comment by CastagnaIT** [comment]
We're already working, if you want to help, you have to follow the full PR situation not shoot randomly...

I think you missed out on the fact that currently Kodi is in the ALPHA phase and not beta.
It is not for end users.

**Comment by yabba235** [comment]
I'm not end user - I always use pre- and alpha,beta version :)
BTW
I get you my error:
"a bye-like object is required, not 'str' "
 and attach kodi.log, but you ignored it.

sob., 16 lis 2019 o 11:41 Stefano Gottardo <notifications@github.com>
napisał(a):

**Comment by CastagnaIT** [comment]
I ignored it because i wrote to you, "you have to follow the full PR situation"
this means you need to know the situation not only to NF PRs, but also of Kodi PRs and other components PRs
If you were a real tester, you wouldn't open an issue here about this problem,
that means wasting time not helping..

**Comment by yabba235** [comment]
How do you improve the plugin to work if you ignore reported errors?
But ok, if you see it that way...
