### ISSUE TITLE
Playing Exported items fails with python3

### ISSUE THREAD

**Issue by mackal** [CastagnaIT/plugin.video.netflix#315]
#### Your Environment
- Netflix add-on version: 0.15.10
- Operating system version/name: gentoo

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Playing an exported video fails due to: https://github.com/CastagnaIT/plugin.video.netflix/blob/23f0927d01f9e627fb4c719d113ebc1b79b627ab/resources/lib/navigation/player.py#L158
xbmc.translatePath returns a str like object that lacks a decode method in python 3.

#### Expected behavior
Video plays

#### Actual behavior
Errors

#### Steps to reproduce the behavior

1. Export to library
2. Try to play from library

#### Possible fix
Removing the decode does fix the issue for python 3, no idea if it causes issues for python 2.

### Debug log

The debug log can be found from this link:

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Thanks fixed,
I warn you that i do not know if the build on linux works properly i tested only LibreELEC
