### ISSUE TITLE
Plugin won't start anymore

### ISSUE THREAD

**Issue by ilPeo** [CastagnaIT/plugin.video.netflix#316]
version 0.15.8 doesn't start anymore.
Using Kodi 19beta on raspberry pi3. Is this a Python-related issue?

see attached log
[kodi-log.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3856194/kodi-log.txt)

**Comment by notoco** [comment]
There is no kodi 19 beta. 19 is still the Alpha version. So not suitable for normal use. It is intended only for developers who can not only determine the error, but also fix it.Work on the k19 version is ongoing, as a developer using the nigthly version, you should notice this when looking at working on github.

**Comment by notoco** [comment]
BTW:
`Error Contents: No module named Cryptodome`
https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon

**Comment by CastagnaIT** [comment]
Thanks notoco,
I suggest you don't use Kodi 19 is unstable,
only when it is officially announced by the Kodi team the end users will be welcome to use it.

you can use it only for development purposes or experiments tests
