### ISSUE TITLE
Some of the series/movies start with arabic audio language

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [CastagnaIT/plugin.video.netflix#322]
#### Your Environment
- Netflix add-on version: 0.15.10
- Operating system version/name: LibreElec 9.1.502 (Generic.x86_64)
- Device model:  MINIX Neo Z64 W

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Some of the series/movies start with `ara` language. So every time I have to switch the audio language to `eng` for every episode/movie. Subtitles are in `eng` language by default. Settings -> Player -> Language shows english everywhere.

#### Expected behavior

If there is `eng` language available it should remember my choice for my preferred language (based on addon settings or system settings) and start episode/movie with `eng` language by default.

#### Actual behavior

Some of the episodes/movies start with `ara` language.

#### Steps to reproduce the behavior

1. Go to Netflix
2. Search for `Peppa`
3. Go to Peppa Pig -> Season 3 -> 3x05 Granny Pig's Chicken
4. It starts with `ara` language.

#### Possible fix

¯\_(ツ)_/¯

### Debug log

Sorry guys I could not find how can I get that log file you are asking. The page (https://kodi.wiki/view/Log_file/Easy) does not explain it easy. I went to Event Log in Settings and there is nothing.

If you could please provide the easy way to get the log I would attach it to the issue. Thanks.
The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

I don't remember. I installed the addon 6 month ago. How can I find which repo is that???

#### Screenshots

![IMG_20191119_201747](https://user-images.githubusercontent.com/13495631/69182930-e0a8ee00-0b09-11ea-8e32-e5b44aff7cb1.jpg)

**Comment by CastagnaIT** [comment]
This is strange probably caused by a wrong setting..
make sure that in the InputStream Adaptive settings (goto expert settings) the `Stream selection` is on `Auto`

**Comment by denis-pujdak-adm-it** [comment]
Checked. It is `Auto`.

**Comment by CastagnaIT** [comment]
try uninstall addon (also user data when prompt) and install it again

**Comment by denis-pujdak-adm-it** [comment]
![IMG_20191120_115747](https://user-images.githubusercontent.com/13495631/69237319-54400f00-0b8d-11ea-9731-5e0448e4e14d.jpg)

![IMG_20191120_115821](https://user-images.githubusercontent.com/13495631/69237325-573aff80-0b8d-11ea-817b-d9b6bd2444ff.jpg)

**Comment by denis-pujdak-adm-it** [comment]
ok. will do that and then let you know guys if it fixes the issue.

**Comment by denis-pujdak-adm-it** [comment]
Still the same issue for that particular example I pointed out, some of the episodes of "Peppa Pig" are started in English, some of them not.
Just in case checked my account language too:
![image](https://user-images.githubusercontent.com/13495631/69239864-1ba33400-0b93-11ea-99c9-3421b9ea5c33.png)

**Comment by denis-pujdak-adm-it** [comment]
Looks like if I switch audio language to `eng` next time it starts with `eng` now. Will see later if the problem remains. Please feel free to close the issue if you cannot reproduce the problem.
Thanks for your help.

**Comment by CastagnaIT** [comment]
in my country are reproduced exactly, it is possible that i receive data different from you
i can't help you better, i need to see more deeper
1 - get the log:
-install Add-on "Kodi Logfile Uploader"
-In netflix add-on settings, in Expert page change "Debug logging level" to "Verbose"
-In https://kodi.wiki/view/Log_file/Easy only point 2.1
-reboot and reproduce problem
-use Add-on "Kodi Logfile Uploader" to upload and provide log web link

2 - more important, get the manifest file after playback the problematic episode:
file is contained in userdata\addon_data\plugin.video.netflix\manifest.json
but with LibreElec is not simply get the file
you need to browse the user folder from device through a pc
in case, how to with smb: https://wiki.libreelec.tv/how_to/share_additional_folders

**Comment by denis-pujdak-adm-it** [comment]
I got the logs. Please find attached zip file. I live in UK. I don't use any VPN.
[log-2019-11-20-14.14.08.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3869662/log-2019-11-20-14.14.08.zip)

**Comment by denis-pujdak-adm-it** [comment]
This log file is taken after the reproduced issue. So after I restarted the device the episode `Peppa Pig -> Season 3 -> 3x05 Granny Pig's Chicken` started in `ara` language.
https://paste.kodi.tv/xupefujoqu

**Comment by CastagnaIT** [comment]
sorry but the log is totally incomplete,
i think you have miss to do some steps:
1-In netflix add-on settings, in Expert page change "Debug logging level" to "Verbose"
2-In https://kodi.wiki/view/Log_file/Easy only point 2.1, so >>> (Enable the setting Enable debug logging in the settings page located at Settings > System Settings > Logging)
3-reboot
4-reproduce problem
5-use Add-on "Kodi Logfile Uploader" to upload and provide log web link

**Comment by denis-pujdak-adm-it** [comment]
I am not sure if that's exactly what you need. I tried to reproduce the problem and the the log uploader said the file is too big. Then I restarted and reproduced the problem again and the log uploader is not doing anything when I run it. So I went to the folder `Logfiles` from my PC and found the file bellow. Everything looks very complicated. I don't how typical user would provide you with the error information. I probably must switch back to Windows and forget about all of this bugs. :-(
[log-2019-11-20-15.11.52.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3869892/log-2019-11-20-15.11.52.zip)

**Comment by denis-pujdak-adm-it** [comment]
Can't your addon just sent errors to you? Like every program in every system does?

**Comment by CastagnaIT** [comment]
now the log is complete, i'll need some time to review it...

Unfortunately, users that use LibreELEC for Kodi, have to take into account that solving problems requires more work to get information...is an entire operating system do not just manage addon

if you want simple things use windows or mac. Also android but in some cases even there to solve problems is difficult for novice users

**Comment by denis-pujdak-adm-it** [comment]
Thanks for you help. The manifest file is in the first log file if you are missing it.
Regards.

**Comment by CastagnaIT** [comment]
in the manifest there is no Arabic language, maybe you took it after you played episodes that didn't have Arabic.
in the log is specified of an episode with Arabic language, but it is also specified that it has been reproduced with English language...

usually it's kodi to choose the language, not the add-on,
only in the following case is the add-on to change language instead of Kodi:
->In addon settings >Playback >Remember audio/subtitle to ON
In this case when you watch a video, and manually change the audio/subtitle language the addon save the selected language and it's applied to all the episodes played of the tvshow

there's one known problem:
is a Kodi issue that does not provide an adequate language selection system via code,
for example, if an episode has fewer languages than another episode, it may happen that the language selection is wrong. This only if "Remember audio/subtitle" is ON

I can only tell you to try disable this feature

**Comment by denis-pujdak-adm-it** [comment]
Thanks for your effort. You guys are doing a great job. I hope every day there will be more and more people using the addon and LibreElec will be a real alternative of giant corpo media systems.

**Comment by CastagnaIT** [comment]
i made a new request to Kodi devs,
i hope that one day they will take you into consideration..
