### ISSUE TITLE
Cannot launch external player

### ISSUE THREAD

**Issue by devidin** [CastagnaIT/plugin.video.netflix#323]
#### Your Environment
- Netflix add-on version: current
- Operating system version/name: Windows 10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ x] Windows

### Describe the bug
Playing Netflix content works fine with Kodi's internal player, but when I try with an external one, like MPC-HC or VLC, it does not work.
With MPC-HC I receive a message saying that it cannot read the stream.
With VLC I get some more details in the logs, see at the bottom of the message

#### Expected behavior
Show the movie

#### Actual behavior
Cannot read stream
#### Steps to reproduce the behavior

1. configure any video to be read by an external player
2. launch a Netflix movie from the addon

### Debug log

The debug log can be found from this link:
(logs from my specific configuration, see below)
[startvlc.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3870330/startvlc.log)
[vlc.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3870329/vlc.log)

### Additional context or screenshots (if appropriate)

vlc logs seem to report a format error from widevine stream:
"xml error: XML parser error (line 1) : Namespace prefix widevine on license is not defined"

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
[playercorefactory.xml.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3870335/playercorefactory.xml.txt)
[startvlc.bat.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3870339/startvlc.bat.txt)

#### Other information

Using external players like MPC-HC would allow to have better image and sound

**Comment by CastagnaIT** [comment]
the addon not handle the playback

the addon only provides a netflix manifest data to inputstream addon. so inputstream addon manage the streams, and communicate to Kodi what streams link to use

you have to ask in the forum kodi if exsists a way to manage externally the DRM streams
i have some doubts that this may work

**Comment by devidin** [comment]
Hello,

Thank you for your feedback Stefano.
I followed your advice, and posted a question on Kodi forum.

Just in case, here is the link: https://forum.kodi.tv/showthread.php?tid=349435

And thank you for your add-on, very useful!

Kind Regards,

Yves ADAM

________________________________
