### ISSUE TITLE
Sometimes no video only audio

### ISSUE THREAD

**Issue by sigjak** [CastagnaIT/plugin.video.netflix#324]
I have been trying the Netflix add-on (0.15.11) with Kodi 18.2 Leia on a  Minix Neo U1 box running Android 5.1.1 (Quad-Core Cortex A53 and Penta Core Mali-450 GPU) with mixed results. Some videos play well while sometimes there is audio but no video and the log file shows;
ERROR: CDVDVideoCodecAndroidMediaCodec:: Failed to create Android MediaCodec
ERROR: CDVDVideoCodecFFmpeg::Open() CryptoSessions unsupported
ERROR: CVideoPlayerVideo::OpenStream - could not open video codec
The log file is here (https://paste.kodi.tv/asihulezat.kodi)
Is this a bug or is this this due to the android 5.1.1 version used on the Minix and is thera a workaround?
All the best

Sig
This happens to only certain videos. For example, in The Crown Season 3, all episodes except the first one can be played

**Comment by mackal** [comment]
When I've had this happen, it didn't work on my browsers on desktop Linux either (tried Chrome and Firefox) but videos worked fine on Windows. I assumed there was something missing from DRM.

**Comment by CastagnaIT** [comment]
android 5 is quite old

first try to reinstall widevine
in expert settings> imputstream helper> reinstall

i think only android logcat can be something of useful

being only some videos that do not start could also be a codec problem
you have tried to change in expert settings:
VP9 to OFF
HEVC to OFF

or else

VP9 to OFF
HEVC to ON

**Comment by sigjak** [comment]
I could not figure out how to reinstall widevine but disabling VP9 solved the problem. Having HEVC ON or OFF makes no difference.
Thank you for your swift reply and thanks for a very useful plug!

Sig
