### ISSUE TITLE
Entity used incorrect key exchange data type

### ISSUE THREAD

**Issue by leifclaesson** [CastagnaIT/plugin.video.netflix#325]
#### Your Environment
- Netflix add-on version: 0.15.11
- Operating system version/name: Windows 10 x64 14393

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug
An error message appears when starting kodi and when trying to play any netflix video:
Entity used incorrect key exchange data type

### Debug log
The debug log can be found from this link:
https://paste.kodi.tv/avaxotoxep.kodi

#### Installation
I was using 0.15.10 (installed from the CastagnaIT repository) which has worked perfectly.
It failed suddenly without warning, suggesting something changed at the Netflix server end.
I updated to 0.15.11 after it failed, no improvement.
I also updated Widevide, also no improvement.

**Comment by CastagnaIT** [comment]
with kodi closed, try to delete this file at this path:
C:\Users\[your user name]\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix\msl_data.json

if it does not work again, wait at least 1/2 days, months ago something similar happened, it was a problem of netflix

**Comment by leifclaesson** [comment]
Thank you for the quick answer. I tried your suggestion. Did not help.
I will give it a day and see if it magically starts working again. :)

**Comment by leifclaesson** [comment]
It magically started working again! Weird. Anyway, thank you kindly.
