### ISSUE TITLE
In the subtitle selection list only a small list of available subtitles appears

### ISSUE THREAD

**Issue by b247** [CastagnaIT/plugin.video.netflix#329]
#### Your Environment
- Netflix add-on version: 0.15.11
- Operating system version/name: LibreElec 9.+
- Device model:  Raspberry-Pi 2 B+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

In the subtitle selection list only a small list of available subtitles appears (eg German and German forced) although when using browser html player (on PC) this list is larger, including my prefered subtitle language, Romanian (eg romanian, english, german, spanish, etc)

#### Expected behavior

Display / download all available subtitle languages.

#### Actual behavior

Empty or limited list of subtitles.

#### Steps to reproduce the behavior

1. Play a movie in browser, subtitle defaults to Romanian and other languages are also available.
2. Play same movie using Kodi Netflix, subtitle selection lists shows only German, German forced or empty selection list .

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Before check:
make sure that in Expert settings "Disable WebVTT subtitle support" is turned OFF, often this is the cause.

Then:
1) play the problematic episode
2) extract the file called: manifest.json
from the path:
\userdata\addon_data\plugin.video.netflix\[file here]
to browse the path you need to read LibreElec guide
3) Specify what tv show and what season/episode

**Comment by b247** [comment]
Thank you, actually the problem is generated by DDPlus HQ and Atmos expert setting when enabled. Have disabled this and now the subtitles are all in place 😁

**Comment by CastagnaIT** [comment]
what is your nf account plan?

**Comment by b247** [comment]
Premium ultrahd

-----Original Message-----

**Comment by Harvie** [comment]
> Thank you, actually the problem is generated by DDPlus HQ and Atmos expert setting when enabled. Have disabled this and now the subtitles are all in place grin

I can confirm this! Disabled DDPlus/Atmos option and subtitles are available!
Will this be fixed? (or at least mentioned in the menu, that it causes SOME subtitles to disappear)
