### ISSUE TITLE
Unable to start addon due to newlines in reactContext JSON

### ISSUE THREAD

**Issue by ekdahl** [CastagnaIT/plugin.video.netflix#33]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Netflix addon fails to start

### Addon version used
0.14.0beta23_20190325

### Description
Starting the addon always prompts the login screen
After entering login details a screen shows "Check your credentials"

## Context (Environment)
Swedish Netflix subscription
Linux NUC 5.0.4 #1 SMP Sun Mar 24 21:08:22 GMT 2019 x86_64 GNU/Linux
LibreELEC (Milhouse): devel-20190324210257-#0324-g5ccaa74 [Build #0324]
Kodi (18.2-RC1 Git:98d18d0). Platform: Linux x86 64-bit

### Installation
* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

## Debug log
DEBUG: [plugin.video.netflix (0)] Extracting userdata from webpage
DEBUG: [plugin.video.netflix (0)] Extracting reactContext JSON
ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 167, in extract_json
                                                return json.loads(json_str)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
                                            ValueError: **Invalid control character** at: line 1 column 73808 (char 73807)

Full debug log: https://pastebin.com/XLPMqbPc

## Other information
The problem appears to be the occurrence of two **newline** characters in the above mentioned JSON. See the two \n below:

"added.in.the.last.day":"\x3Cb\x3E{lastAddedNum,\x20number}\x3C\x2Fb\x3E\x3Cbr\x3Eserier\x20och\x20filmer\nhar\x20lagts\x20till\x3Cbr\x3E\x20{numDays,\x20plural,\x20one\x20{det\x20senaste\x20dygnet}\x20other\x20{de\x20senaste\x20\x23\x20dagarna}}."

"added.in.the.last.week":"\x3Cb\x3E{lastAddedNum,\x20number}\x3C\x2Fb\x3E\x3Cbr\x20\x2F\x3Eserier\x20och\x20filmer\nhar\x20lagts\x20till\x3Cbr\x20\x2F\x3E\x20{numWeeks,\x20plural,\x20one\x20{den\x20senaste\x20veckan}\x20other\x20{de\x20senaste\x20\x23\x20veckorna}}."

Replacing the newline with something else just before https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/api/website.py#L167 fixes the problem:
json_str = json_str.replace('\\n', '\\x20')  # Replace newline with space

**Comment by CastagnaIT** [comment]
please put the full file log

**Comment by ekdahl** [comment]
Added full debug log. What information was missing?

**Comment by CastagnaIT** [comment]
Line feed is supported in json, please test this:

        json_array = recompile(JSON_REGEX % name, DOTALL).findall(content)
        json_str = json_array[0]
        json_str = json_str.replace('\"', '\\"')  # Escape double-quotes
        json_str = json_str.replace('\\s', '\\\\s')  # Escape \s
        json_str = json_str.replace('\n', '\\n')  # Escape line feed <---------
        json_str = json_str.decode('unicode_escape')  # finally decoding...
        return json.loads(json_str)

**Comment by CastagnaIT** [comment]
h\x20filmer\nhar\x20lagts  <-- this "\n" is not escaped
after this:
json_str = json_str.replace('\n', '\\n')

become
h\x20filmer\\nhar\x20lagts  <-- this "\n" is escaped

so json.loads doesn't complain,
and returns string like:
h filmer\nhar lagts ti

**Comment by CastagnaIT** [comment]
I need you to send me again what you put on the Other information section, because it is possible that github has truncated all the characters "\\"
you have to make a txt file like I did and attach it to the comment

**Comment by ekdahl** [comment]
[Other information.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3091400/Other.information.txt)

After a bit more testing this is what I found (I just can't understand why I couldn't get that working last I tested):

This works
`json_str = json_str.replace('\\n', '\\\\n')  # Escape line feed`
before the decode line
`json_str = json_str.decode('unicode_escape')  # finally decoding...`
And this works after the decode line
`json_str = json_str.replace('\n', '\\n')  # Escape line feed`

[Working example with log output.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3091508/Working.example.with.log.output.txt)

**Comment by CastagnaIT** [comment]
Thank you for doing all the necessary tests
now i'm going to apply the fix
