### ISSUE TITLE
Media player, browse for subtitle, how to access a subtitle stored in a usb stick or other file system location?

### ISSUE THREAD

**Issue by b247** [CastagnaIT/plugin.video.netflix#330]
#### Your Environment
- Netflix add-on version: 0.15.11
- Operating system version/name:LibreElec 9.+
- Device model:  Raspberry-Pi 2 B+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe your help request

Media player, browse for subtitle, how to access a subtitle stored in a usb stick or other file system location?

**Comment by CastagnaIT** [comment]
This does not depend on the addon but is an option of the Kodi player
you have to ask in the forum
