### ISSUE TITLE
Netflix do not starting on Raspbian (Pi3) py module problem?!

### ISSUE THREAD

**Issue by lukacsarpad** [CastagnaIT/plugin.video.netflix#332]
#### Your Environment
- Netflix add-on version: 0.15.2
- Operating system version/name: Raspbian, Kodi 18.2
- Device model:  Raspberri Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

After starting kodi, I get an error message, and it tells me to check debug log. When trying to use netflix addon, there is an error message (after a long wait), addon exception timeout.

#### Expected behavior

Start Netflix Addon

#### Actual behavior

Error message displayed.

#### Steps to reproduce the behavior

1. Start kodi
2. wait for first error message
3. start kodi netflix addon

### Debug log

The debug log can be found from this link:
https://drive.google.com/open?id=1IF1LdQnjsfvvBoTn4fTh1H5CnJ3t5_xP

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
I'm using the CastagnaIT repo.

**Comment by CastagnaIT** [comment]
seem your system have a problem with pyasn1 module
also youtube addon is broken with same error
i don't know this system maybe someone else can help you

**Comment by lukacsarpad** [comment]
Yes, I am also experiencing a problem with the youtube addon.

**Comment by CastagnaIT** [comment]
one user said to try this from the terminal:
sudo apt update
sudo apt install python-pip
sudo apt install python-setuptools
sudo apt install build-essential
sudo pip install wheel
sudo pip install pycryptodomex

let me know

**Comment by efralvarez** [comment]
Hey there!
I'm using the 15.11 version and I'm having the same time out problem.
I already have installed pycryptodomex and previous dependencies and still having the problem.

**Comment by CastagnaIT** [comment]
@efralvarez you have to put an your log here

**Comment by lukacsarpad** [comment]
I updated raspbian from stretch to buster, and now it seems to work.
