### ISSUE TITLE
UpNext support broke due to Addon Signals update

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#333]
### Describe the bug
Just to inform you that a recent update of Addon Signals (changing from **hex**-encoding to **base64**-encoding) broke UpNext integration.

More information at: https://github.com/im85288/service.upnext/issues/91

**Comment by dagwieers** [comment]
Easiest solution for now is to go back to:
https://mirrors.kodi.tv/addons/leia/script.module.addon.signals/script.module.addon.signals-0.0.3.zip

**Comment by CastagnaIT** [comment]
this becouse upnext addon do not use addonsignal in right way
instead to use addonsignals as dependency
there is an own implementation, and this means that upnext will always break when changes are made to addonsignals...

**Comment by dagwieers** [comment]
Up Next is not using Addon Signals at all. This could have been communicated better.

**Comment by CastagnaIT** [comment]
does not use it because it has been preferred the custom implementation than using the dependency,
the code is clear...
