### ISSUE TITLE
The library and skip intro not working

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#345]
#### Your Environment
- Netflix add-on version: 0.15.11
- Operating system version/name: Windows 10, Coreelec 9.2,
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [X] Windows

### Describe the bug

Using the library, information to skip intro appears only on the first episode. In the next one, played with UpNext, it no longer appears.

#### Expected behavior

The question about skipping intro appear every time

#### Actual behavior
The question about skipping intro does not appear every time

#### Steps to reproduce the behavior
1. Start playing any series (e.g. Family Guy)
2. Skip the intro for the first episode you watched
3. Scroll almost to the end
4. In the UpNext window, select play next
5. Playback starts
6. The question about skipping intro does not appear

### Debug log
The debug log can be found from this link:
[kodi.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3900236/kodi.txt)
(file to big for any pastebin)

#### Installation
* [X] I'm using other Netflix Repo CastagnaIT
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
I think you made me discover the famous problem that made @smeulf crazy, that he could not find the cause for which the skip sometimes did not work...
Fixed in master branch

**Comment by notoco** [comment]
The best part is that I discovered it for 3-5 months but it did not yesterday that pissed me off again. I look forward to the next stable :)
