### ISSUE TITLE
Audio playback only for some titles

### ISSUE THREAD

**Issue by carbotzergling** [CastagnaIT/plugin.video.netflix#347]
#### Your Environment
- Kodi version: <18.5 Git:20191118-20191116-37f51f6 Media Center Kodi
>
- Netflix add-on version: <0.16.0>
- OS : Opensuse Tumbleweed x86_64

### Describe the bug
The playback doesn't work at all after installation until the PV9 profile is enabled (and dolby digital plus profile disabled ) 

On AMD based machine (Ryzen 1700 + Vega 64) some title like "Z nation" only playback audio  and other title like "The stranger things" have no such problem 

There is no such problem on Intel+NV (i3 4gen + Geforce 860M) based machine. (Tested in same OS and other environment) 

I discovered the titles that have no problem on playback show PV9 on video setting and problematic titles show x.264 on video setting (on Intel+NV machine)

#### Expected behavior
x.264 decode work normally

#### Actual behavior
x.264 decode doesn't work

#### Steps to reproduce the behavior
1. change profile from dolby digital plus to PV9
2. watch titles with x.264 like "Z nation"
3. No video playback  (acc decode only)

#### Possible fix
NO

### Debug log

PV9 profile enabled and dolby digital plus profile disabled
https://nextcloud.daelaam.com/index.php/s/T4Yo4kLjC3pxYm7

dolby digital plus profile enabled or both enabled
https://nextcloud.daelaam.com/index.php/s/z32MxmwqzkzjKy7

#### Screenshot

![screenshot001](https://user-images.githubusercontent.com/58357857/69899325-bc6dcc80-13a7-11ea-9590-1f7c476a6a6c.png)

**Comment by RobinClowers** [comment]
I'm running into this as well, is there a fix?
