### ISSUE TITLE
Netflix Error Notification at Kodi startup with skin Widgets

### ISSUE THREAD

**Issue by Joostzilla** [CastagnaIT/plugin.video.netflix#348]
- Netflix add-on version: 0.16.0
- Operating system version/name: Windows 10

### Describe the bug
Since updating to version 0.16.0 Netflix addon notifies just after Kodi starts:
"Netflix addon error
The Background services may not yet be available if you just started kodi/addon.
In this case try again in a moment."

#### Expected behavior
This is not necessary since Kodi doesn't even had the chance to properly load all services. And the addon wasn't even triggered for use.
Normally i always saw the text at the bottom of the screen: Netflix is starting services.

#### Actual behavior
Netflix addon notifies just after Kodi starts:
"Netflix addon error
The Background services may not yet be available if you just started kodi/addon.
In this case try again in a moment."

#### Screenshots
[https://imgur.com/Ltwv6F7](url)

**Comment by CastagnaIT** [comment]
this message is only displayed if you try to open the addon before starting the service

**Comment by CastagnaIT** [comment]
What's your problem? I don't understand

**Comment by Phigen** [comment]
Is it possible to add a delay to load Netflix addon ?
Thank you.

**Comment by CastagnaIT** [comment]
explain in detail the reasons and the cases of use

**Comment by CastagnaIT** [comment]
if i remove this check, in slow devices it will cause always error in starting the addon, this is because it is mandatory to have the service full started BEFORE the frontend

**Comment by Phigen** [comment]
RPI4 + Aura skin : I use a widget for Netflix and I have the notification "Netflix addon error
The Background services may not yet be available if you just started kodi/addon.
In this case try again in a moment."
Sorry, but my English is very limited.

**Comment by CastagnaIT** [comment]
you use Aura or Aura-notoco?

Widgets always cause problems...i will run some tests

will not be a short-term remedy, surely i will have to wait for an answer from the author of the skin to find a solution. Currently the skins that use widgets forcing the addons to start without respecting the services, this also causes other problems, such as list updates that do not work

**Comment by notoco** [comment]
BTW. The aura-notoco and arctic-zephyr2-notoco skins have no such changes compared to the original. If there are changes in the original, it also appears in mine.

**Comment by CastagnaIT** [comment]
thanks notoco i hope we can find a good solution to all

**Comment by notoco** [comment]
As you probably remember, it was my first note to the plugin that there is a problem with widgets. I started to use the library, etc ...

**Comment by Phigen** [comment]
Do you know another skin that works fine with Netflix addon ?

**Comment by Phigen** [comment]
> you use Aura or Aura-notoco?
> 

I use Aura


> will not be a short-term remedy, surely i will have to wait for an answer from the author of the skin to find a solution...
> 
> [jurialmunkey/skin.aura#77](https://github.com/jurialmunkey/skin.aura/issues/77)

Thank you for your help.

**Comment by CastagnaIT** [comment]
This problem will remain unresolved indefinitely,
I have tried a temporary solution, which has not been accepted at the moment

If one day the developers of the projects related to the skins will work together for a global solution in order to work with all the skins, we can consider how to implement a right solution

**Comment by CastagnaIT** [comment]
Due to too many fragmented projects/forks that manage the skins and lacked help and solutions from other devs, i decided to include a workaround,
It is a solution that will not work 100% of the cases, so it is possible that this message will be displayed in some cases

will be included in the next release
