### ISSUE TITLE
Streams don't start on 2017 Shield

### ISSUE THREAD

**Issue by Freakaa** [CastagnaIT/plugin.video.netflix#349]
#### Your Environment
- Netflix add-on version: 0.16.0
- Operating system version/name: Kodi 18.5
- Device model:  2017 Shield 8.0.1 on Plasma TV in 1080p (no 4K)
 
Used Operating system:
* [x] Android

### Describe the bug
When trying to start a stream, the circle shows shortly, but the stream doesn't start. Amazon VOD Addon is working perfect.
Tried downgrading to 0.13.22 but didn't help.

### Debug log

https://pastebin.com/4Me7S9xb

**Comment by CastagnaIT** [comment]
now you have mixed the configuration of the old add-on with the new one
first uninstall add-on and ALSO USER DATA when prompt,
so reinstall it.

Before opening the addon:
Go to add-on settings, in Expert page and change "Debug logging level" to "Verbose"
then extract log after reproduce the problem

**Comment by Freakaa** [comment]
Thanks for your feedback! Did everything as described, but having still the same behaviour. :(

Here's the log with Verbose=on

https://pastebin.com/sb8seuT5

**Comment by CastagnaIT** [comment]
Go to in expert settings,
Turn off VP9
turn on HEVC
with no dolby vision and no hdr
try again

**Comment by Freakaa** [comment]
Unluckily same behaviour. All I left on in expert settings is:

- DDPlusHQ
- HEVC

https://pastebin.com/HWBynWCg

**Comment by CastagnaIT** [comment]
Install this test, is not a fix i need to get more info
[plugin.video.netflix_0.16.0_20191130_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3907227/plugin.video.netflix_0.16.0_20191130_t1.zip)
so get a new log

**Comment by Freakaa** [comment]
Here you are. 

Settings:

- DDPlus HQ on
- VP9 on
- rest off

https://pastebin.com/MXac0FjM

Settings:

- DDPlus HQ on
- HEVC on
- rest off

https://pastebin.com/DszrCxRX

**Comment by CastagnaIT** [comment]
From Expert settings go to InputStream adaptive addon settings, is Override HDCP status to ON ?
you have a direct internet connection or use VPN or Proxy?

**Comment by Freakaa** [comment]
Yes HDCP status is set on. And I have direct internet connection without any VPN or Proxy. 
Do you think it's a Kodi bug? Is it possible to setup a 2nd Kodi instance as test environment next to the one I'm using?

**Comment by CastagnaIT** [comment]
I don't understand what kind of problem happens but it doesn't depend directly from Kodi
There's something happen of wrong with Netflix addon or in InputStream Adaptive add-on
i am not sure, from how i see InputStream does not send data to netflix addon
or something else is affecting the outcome

@peak3d Sorry about the ping, maybe you could suggest something, see "DATA:" print near the error, is empty, and prevents from getting the license

**Comment by CastagnaIT** [comment]
have you tried to rollback to an old version of Kodi?
try 18.4
http://mirrors.kodi.tv/releases/android/arm64-v8a/

**Comment by Freakaa** [comment]
I tried a rollback to 18.4, which was not possible - unlucky me... So I completely uninstalled the 18.5 and did a clean install of it (18.5) again. Then the only App I installed, was your Netflix Addon (0.16.0) through your Repo and it worked like a charm. 
Thanks a lot CastagnaIT - seems, that there was something wrong with Kodi.
