### ISSUE TITLE
Timeout error pops up.

### ISSUE THREAD

**Issue by safoelc252** [CastagnaIT/plugin.video.netflix#354]
#### Your Environment
- Netflix add-on version: v0.16.0
- Operating system version/name: LibreELEC v9.2.0 (Kodi v18.5)
- Device model:  Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
A timeout error always popup every time I try to run Netflix

#### Expected behavior
Netflix should run just fine

#### Actual behavior
Popup dialog shows up with the following message:

> The addon encountered the following error:
> timeout:timed out
> Error details have been written to the Kodi logfile. If the error message does not provide guidance on how to resolve the issue or you continue to receive this error, please report it via GitHub. Please provide a full debug log with your error report(enable "Debug Logging" in Kodi settings.)

 

#### Steps to reproduce the behavior

1. Start Kodi
2. Navigate to Netflix addon
3. Select any Profile.
4. Error pops. The same error pops up after closing the first one. 
5. If I open Neftlix again, the same error popsup again. But this time, I am unable to select a Profile.

#### Possible fix
N/A. I'm still trying to learn Kodi addon development in my spare time.

### Debug log

The debug log can be found from this link: http://ix.io/23mM

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
* [x] I'm using your addon. I followed your installation instructions (i.e. installed from CastagnaIT repo zip file in Kodi as instructed)

#### Other information

- I tried logging out and back in, and it didn't resolve the issue.

**Comment by CastagnaIT** [comment]
turn OFF in expert setting Enable IPC over HTTP
and if not work put a new log

**Comment by safoelc252** [comment]
turning OFF Enable IPC over HTTP resolved this issue. Thanks so much!

**Comment by 8** [comment]
Thanks, this also fixed the same error when downloading the crome OS recovery image on widevine installation for me!
