### ISSUE TITLE
Can't connect to Netflix

### ISSUE THREAD

**Issue by W2009** [CastagnaIT/plugin.video.netflix#355]
Hi,

I have configuration:

Debian 10 (buster)
Kodi 18.5 (Lea)
Addon 0.16

I can't connect to Netflix and I see in log:

ConnectionError: HTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /profiles/manage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff2edb86c90>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Same time with Chrome no problems.

Anybody can help?

**Comment by CastagnaIT** [comment]
Not follow issue rules
