### ISSUE TITLE
Cannot get Dolby Atmos on Shield

### ISSUE THREAD

**Issue by mkaflowski** [CastagnaIT/plugin.video.netflix#359]
#### Your Environment
- Netflix add-on version: v0.16.0
- Operating system version/name: Android 9
- Device model: Nvidia Shield

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

I cannot get Dolby Atmos on my Shield. Tried everything. There are only DD+ on stream selects and AV says that it is dolby digital+. Am I missing something?

**Comment by CastagnaIT** [comment]
Before turn on Shield, turn on the Tv (and the amplifier if you use an amplifier)
so there is a shield setting to permanently enable high quality audio tracks
i don't remember where i don't have shield

**Comment by CastagnaIT** [comment]
not all netflix content has Dolby atmos

**Comment by mkaflowski** [comment]
Didn't worked.
It looks like this: [https://photos.app.goo.gl/yRgWoT6o4tJPvL7u9](https://photos.app.goo.gl/yRgWoT6o4tJPvL7u9)

**Comment by CastagnaIT** [comment]
In first screenshot all streams are named DD+ it is right, becouse Kodi use "DD+" to all Dolby types
i found the shield setting path:
Shield setting -> Display & Sound -> Advanced settings -> Surround Sound -> Set to Always

in Kodi make sura that hd sound system setting are enabled:
https://user-images.githubusercontent.com/47712881/52913589-b34fbb00-32bf-11e9-9297-49293c517952.JPG

Are you sure the TV or amplifier has a Dolby Atmos decoder?

**Comment by mkaflowski** [comment]
Thank you.
It has Dolby Atmos. It works with Dolby Atmos. I think that after updates shield has different settings but tried to change them and doesn't help.
What TV box do you use? Does it support Dolby Atmos?

**Comment by CastagnaIT** [comment]
I use an Onkyo amplifier but not support Atmos only up to Dolby True HD, the photo is of another netflix addon user.
if not depending on this, can be then it concerns the cable connection or the hdmi port, don't know..
you have to ask to other user that have Shield

**Comment by mkaflowski** [comment]
Ok. Thank you.

**Comment by CastagnaIT** [comment]
Closed for inactivity
