### ISSUE TITLE
Netflix addon Error during logon

### ISSUE THREAD

**Issue by mcitew** [CastagnaIT/plugin.video.netflix#360]
Get an error "UnicodeError ....." after entering email and password.
Log file included.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3916295/kodi.log)

**Comment by CastagnaIT** [comment]
install the daily build

**Comment by mcitew** [comment]
same error after installed the daily built.
[kodi2.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3917459/kodi2.log)

**Comment by CastagnaIT** [comment]
i need more info so install this:
[plugin.video.netflix_0.16.0_20191203_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3917516/plugin.video.netflix_0.16.0_20191203_t1.zip)

and before open the addon:
Open add-on settings, go to in Expert page and change "Debug logging level" to "Verbose"

so reproduce the problem than put a new log

**Comment by mcitew** [comment]
New log.
[kodi3.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3918774/kodi3.log)

**Comment by CastagnaIT** [comment]
see if this solves the problem:
[plugin.video.netflix_0.16.0_20191204_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3920949/plugin.video.netflix_0.16.0_20191204_t2.zip)

**Comment by mcitew** [comment]
Got a different error now.
Still crash.
[kodi4.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3921291/kodi4.log)

**Comment by CastagnaIT** [comment]
a problem seem to be solved now install this:
[plugin.video.netflix_0.16.0_20191204_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3921353/plugin.video.netflix_0.16.0_20191204_t3.zip)

**Comment by mcitew** [comment]
Okay. Login and navigation problem is fixed. However, on this box, there is no video and no sound. The same version of plugin installed it on my mobile phone, there is sound and video. I guess there is still something unique to this box.

**Comment by CastagnaIT** [comment]
if you put a log we can try to understand what happen

**Comment by mcitew** [comment]
Collected this log. Sometimes a some sound at the intro. Other than that, there is no video and no sound for the movie.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3924172/kodi.log)

**Comment by CastagnaIT** [comment]
this log is not useful, you have forgotten to enable addon debug and kodi debug:
Open add-on settings, go to in Expert page and change "Debug logging level" to "Verbose"
Enable the Debug log in your Kodi settings

**Comment by mcitew** [comment]
I remembered turning that on already. Is it also I have to turn debug log on at the Kodi Settubg/System->Logging ? Looks like that was the reason for the reduced info.

**Comment by CastagnaIT** [comment]
Look at your file, no debug info at all, and your log is also incomplete

**Comment by mcitew** [comment]
I will redo it when I get back home in about 2 hours time.

**Comment by mcitew** [comment]
Log resubmit, tried playing two different videos.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3925932/kodi.log)

**Comment by CastagnaIT** [comment]
This is a good log,
so this confirm that your device have a problem with video codecs,

try to disable this Kodi settings (if exists) need to swith to "Expert" see below
![image](https://user-images.githubusercontent.com/3257156/70221750-33f58000-1749-11ea-9648-1489d1b172e2.png)

try and if not work again, you can try this:
go to in addon expert settings, then enable VP9 profile
you can also try HEVC, but i don't know if these in your case are worse

but having MPEG that doesn't work is critical..

**Comment by mcitew** [comment]
I turn on the expert mode for kodi/settings/players/video, seems the two settings on the hardware acceleration are already defaulted. Anyway, I went ahead to test, there is no improvement. After that I actually turn off the two hardware acceleration settings, I managed to get the voice, but the video is still not displayed, only got one static backdrop image.

Log attached to see if it is useful.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3926281/kodi.log)

**Comment by CastagnaIT** [comment]
nothing to do seem your device has a codec problem in the firmware
is something that often happens with chinese android box.. i can't do anything

**Comment by mcitew** [comment]
I just want to report that I rename the liboemcrypto.so on the system, thereby causing the box to downgrade from DRM L1 to DRM L3, both video and voice are now working in Kodi under this plugin. 

My TV is only capable of maximum 1080p. As of now, the displayed resolution seems satisfactory.

**Comment by CastagnaIT** [comment]
you can also try this combination:
mediacodec - surface TURN ON
mediacodec TURN OFF
and in InputStream Adaptive settings TURN ON > HDCP override

**Comment by mcitew** [comment]
I tried it, it didn't work. I guess since nothing much can be done more, we can close this.
