### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by W2009** [CastagnaIT/plugin.video.netflix#363]
## Help request

I assume not bug but problem with configuration.

#### Your Environment
- Netflix add-on version: 0.16
- Operating system version/name: Debian 10, Kodi 18.5
- Device model: 

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Expected behavior
Addon normally connect Netflix.

#### Actual behavior
Addon does not connect Netflix and return error (see debug log section for full debug log).

raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /profiles/manage (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5f96e0cdd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

#### Steps to reproduce the behavior
Addon installed accordingly to manual. 

### Debug log
The debug log can be found from this link:

https://www.dropbox.com/s/5hp2tdoz3rv89ko/kodi.log?dl=0

#### Installation
Debian 10, Kodi 18.5, standard repo used, plugin installed manually.

**Comment by CastagnaIT** [comment]
the log in incomplete you have to enable verbose logging
Open add-on settings, go to in Expert page and change "Debug logging level" to "Verbose"

but this is a connection problem not a bug in addon

**Comment by W2009** [comment]
Hmm... debug level was/is set to verbose. How to recognize in the log that is in verbose? I will come back with new log but I want to be sure is OK. 

On Chrome I have access to Netflix, on Kodi and on Firefox not (just checked). It has to be something specific to Netflix as HBO works.

**Comment by W2009** [comment]
OK, I digged deeper - it was DNS issue.
