### ISSUE TITLE
Netflix addon error at choosing profile

### ISSUE THREAD

**Issue by knieselpriem** [CastagnaIT/plugin.video.netflix#364]
#### Your Environment
- Netflix add-on version: v0.16.0
- Operating system version/name: LibreELEC (official): 9.2.0, kernel: Linux x86 64-bit version 5.1.16
- Device model:  Intel(R) Atom(TM) CPU D510 @ 1.66GHz

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
The Netflix addon starts and shows the two icons of the profiles:
1. netflix
2. Kids

When I choose any profile, an error message appears with the information "timeout: timed out". After closing this message, nothing happens and the profiles to choose are shown again. Sometimes even the GUI of the addon disappears and only a list of the main menu items are shown. By pressing "ESC" the main window is shown again.

#### Expected behavior
The netflix addon shall open the profile.

#### Actual behavior
Only an error message appears.

#### Steps to reproduce the behavior
1. start the netflix addon
2. try to open a profile

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3923691/kodi.log)

**Comment by CastagnaIT** [comment]
why you have enabled IPC?

**Comment by knieselpriem** [comment]
I didn't knew that IPC (interprocess communication?) is enabled or even installed. Please give me a hint how to disable it in LibreElec.
Btw: How did you find out that IPC may be enabled or is installed? The only incidence of the string "ipc" is in the traceback of the Python exception of the netflix addon.

**Comment by CastagnaIT** [comment]
In addon settings, go to expert page,
there is enable http ipc, so turn OFF

if do not work again, follow the instruction to get a right log:
https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

**Comment by knieselpriem** [comment]
Thank you for the hint, that helped!

Fell free to fix the exception and close this issue.
