### ISSUE TITLE
in input adaptive settings for 4k contents, i can not use subtitles 

### ISSUE THREAD

**Issue by taxdriver4u** [CastagnaIT/plugin.video.netflix#365]
#### Your Environment
- Netflix add-on version: v 0.16.0
- Operating system version/name: android pie
- Device model:  shield TV(2017)

Used Operating system:
* [o ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
i use this plugin, thank you

but i recognized some problem

in input adaptive settings for 4k contents, i can not use subtitles 

![image](https://user-images.githubusercontent.com/44728502/70241443-64bdcf80-17b2-11ea-8d26-9d4563a64342.png)

![image](https://user-images.githubusercontent.com/44728502/70241459-6b4c4700-17b2-11ea-9406-bbf794a94d28.png)

![image](https://user-images.githubusercontent.com/44728502/70241395-4eb00f00-17b2-11ea-85a5-d9aeb8233388.png)

in input adaptive settings for hd contents, everything's ok

![image](https://user-images.githubusercontent.com/44728502/70241612-ababc500-17b2-11ea-8a5a-37a5f0c4a86a.png)

![image](https://user-images.githubusercontent.com/44728502/70241626-b36b6980-17b2-11ea-99a7-0c8be26e98ba.png)

**Comment by CastagnaIT** [comment]
you have a wrong setting, `stream selection` **must always be Auto**
Manual is only for development scope, and cause problems with all the streams

**Comment by taxdriver4u** [comment]
thanks

but if stream selection be Auto, max display resoiution is supported to HD

**Comment by CastagnaIT** [comment]
Is better set kodi screen resolution to 4k
if you can't
Enable Ignore display resolution on ISadaptive

**Comment by taxdriver4u** [comment]
I miss this option (Is better set kodi screen resolution to 4k)
ok thank you
all problem was solved

**Comment by frodo19** [comment]
> 
> 
> you have a wrong setting, `stream selection` **must always be Auto**
> Manual is only for development scope, and cause problems with all the streams

Hi dear CastagnaIT , when thats true, why not delete/hide that option from isadaptive?  I read lot of forum , who the users set to manual, than have issues, and they not understanding that. 
Can you write to the is developer, please hide that setting, users cannot set manual anymore, and all wiill be good. Thanks :)

**Comment by CastagnaIT** [comment]
hehehe people shouldn't touch things they don't know, cut the hand! :)
I've already made this request to the ISA developer, but hasn't been accepted, 

as a compromise in the next version of ISA you will be able to select "video manual":
![image](https://user-images.githubusercontent.com/3257156/72274619-d3e9d780-362c-11ea-939c-94258ef7e957.png)
this mode allows you to manually select the video track quality, without causing the problems with the streams (of "Manual")

**Comment by frodo19** [comment]
> 
> 
> hehehe people shouldn't touch things they don't know, cut the hand! :)
> I've already made this request to the ISA developer, but hasn't been accepted,
> 
> as a compromise in the next version of ISA you will be able to select "manual video":
> ![image](https://user-images.githubusercontent.com/3257156/72274619-d3e9d780-362c-11ea-939c-94258ef7e957.png)
> this mode allows you to manually select the video track quality, without causing the problems with the streams (of "Manual")

Thats mean, people select no more the streams, but the resolutions?

**Comment by CastagnaIT** [comment]
Works as before but without side effects on the other streams type:
![image](https://user-images.githubusercontent.com/3257156/72275661-a43bcf00-362e-11ea-8d46-043d5099fb46.png)
