### ISSUE TITLE
Limited Audio language list

### ISSUE THREAD

**Issue by redboyhun** [CastagnaIT/plugin.video.netflix#366]
It does not matter, which region I set on the LibreElec, I only get the same audio language list (English, German, Turkish, Russian, French(?)). If I use other devices, I can see others too, e.g. Hungarian.

Could you help me please, how to get the others too?

**Comment by CastagnaIT** [comment]
follow here: https://github.com/CastagnaIT/plugin.video.netflix/issues/365

**Comment by redboyhun** [comment]
> 
> 
> follow here: #365

isn't that one only subtitles related?
this one is only for Audio Language

**Comment by CastagnaIT** [comment]
same solution

**Comment by redboyhun** [comment]
This is my setup, only available languages: German, English, Russian, French, Turkish
![IMG_20191206_172236236](https://user-images.githubusercontent.com/34648596/70338781-d9921780-184d-11ea-9fb3-8e6bbd4a2537.jpg)
![IMG_20191206_172304076](https://user-images.githubusercontent.com/34648596/70338782-d9921780-184d-11ea-95d8-6eef622bdc04.jpg)
![IMG_20191206_172340611](https://user-images.githubusercontent.com/34648596/70338783-d9921780-184d-11ea-9d17-0e51b8500c0b.jpg)

**Comment by CastagnaIT** [comment]
provide a full debug log instruction in below main github page
provide the name of tvshows with season episode, with in detail the languages missing

**Comment by frodo19** [comment]
Same here. **You** season 1 all episodes, missing hungarian lang.

**Comment by frodo19** [comment]
![ass](https://user-images.githubusercontent.com/1296125/70739027-37bf6e80-1d16-11ea-9db0-18fe0176c3f0.JPG)
![adss](https://user-images.githubusercontent.com/1296125/70739037-3e4de600-1d16-11ea-81b6-5942a3611402.JPG)
In Kodi coreelec netflix missing German and Hungarian Lang.

**Comment by frodo19** [comment]
All available IS / NF  setting ha tried, no luck.

**Comment by CastagnaIT** [comment]
Now that you've mentioned a tvshow, I can investigate the problem
at a glance is not immediate to resolve this

**Comment by CastagnaIT** [comment]
I've tried a few things, but i haven't found the cause of the problem
at the moment i don't know how to proceed to find a solution

Notes for future devs investigations:
-tried to perform msl manifest post request from nfsession
-tried hardcode languages to manifest
-tried multiple profile variations
-tried update agents (on windows)
-not found relevant difference to manifest request from nf player

**Comment by JackDean2** [comment]
@CastagnaIT
In `msl_handler.py` changing to `'showAllSubDubTracks': True,`  may be a possible workaround for this problem, but it may cause a problem with the subtitles with your version of plugin.video.netflix, this problem does not occurs with the original plugin.video.netflix 0.13.26, your add-on may show less subtitles languages when using `'showAllSubDubTracks': True,`.

https://github.com/truedread/netflix-1080p/issues/3

![11](https://user-images.githubusercontent.com/58781207/70866484-e7911800-1f72-11ea-8214-00cb950ab6bd.png)

**Comment by frodo19** [comment]
> 
> 
> I've tried a few things, but i haven't found the cause of the problem
> at the moment i don't know how to proceed to find a solution
> 
> Notes for future devs investigations:
> -tried to perform msl manifest post request from nfsession
> -tried hardcode languages to manifest
> -tried multiple profile variations
> -tried update agents (on windows)
> -not found relevant difference to manifest request from nf player

Ok, I hope  you, or another developers will find the issue. Currently its a problem for many users, in my coutry. Thanks

**Comment by ghbeta** [comment]
I have a similar issue that the subtitle list is different compared to the subtitle list from the Android app.
How can I hardcode a subtitle language as you suggested?

**Comment by CastagnaIT** [comment]
no, is not suggested to anyone, there are only note for devs
to now no solutions

**Comment by farbenh** [comment]
Any progress about it?

**Comment by CastagnaIT** [comment]
yes will be is fixed for the next release

**Comment by farbenh** [comment]
Thanks, fingers crossed :)

**Comment by CastagnaIT** [comment]
New release is out, i hope this release solves your problems

**Comment by service-paradis** [comment]
I also just encounter this problem. French is not available for Peaky Blinders, Season 5, Episode 1.

**Comment by service-paradis** [comment]
@CastagnaIT Should I open a new issue or you prefer to reopen this one?
