### ISSUE TITLE
Full HD Support for L1 Mecool KM9 Pro

### ISSUE THREAD

**Issue by 2-much-loop** [CastagnaIT/plugin.video.netflix#367]
#### Your Environment
- Netflix add-on version: Latest version
- Operating system version/name: Android TV 9.0
- Device model:  Mecool KM9 Pro

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
With a Standard (HD Available) Netflix subscription and my Mecool KM9 Pro (that is Google certified and Widevine L1), I can't get any video to run above 960x540.
The plugin displays a little label showing 1080p 5.1 Dolby before selecting the video but when I watch the thing and look at the informations, it always shows VP9 or H264 960x540, not anything above.

#### Expected behavior
The box should be able to display 1080p videos with Widevine L1.

#### Actual behavior
The box only displays 960x540 videos, not Full HD.

**Comment by M2k80** [comment]
open you native netflix app and take a look what ESN is listed there, and compare it the one is set in the plugin settings. it should be the same, but without the numbers in the native app

**Comment by mcitew** [comment]
The plugin has manual netflix ESN. Give that a try maybe ?

**Comment by CastagnaIT** [comment]
I can't do anything
