### ISSUE TITLE
Fails on playback with 'Email or password is incorrect'

### ISSUE THREAD

**Issue by robinc64** [CastagnaIT/plugin.video.netflix#368]
#### Your Environment
- Netflix add-on version: 0.16.0 (+ daily)
- Operating system version/name: Debian Stretch (RetroPi) / Kodi 2:18.2-1~stretch
- Device model:  Raspberry pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

This is a fresh install onto an existing Retropi installation. The addon installs fine and I'm able to login and browse Netflix content as expected. However, on attempted playback I get the error 'Email or password is incorrect'.
I've found and read closed issues on this particular problem and have tried the following without avail:
- logout, reboot, then login
- remove the plugin, manually remove all addon files, reinstall
- start fresh with the latest daily build
Perhaps I missed something?

Thank you.

#### Steps to reproduce the behavior

1. Fresh install of the netflix plugin using the install instructions
2. login
3. attempt to play Netflix content

### Debug log

The debug log can be found from this link:

https://1drv.ms/u/s!AgIMW_4kujbwgbglyW6gtokcDqReEA?e=l5SYAx

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
this has returned from the site, i can not do anything,
you can only try to change your password

**Comment by robinc64** [comment]
Hello,
I can try that, if that works I'll reply back here.
Thanks for the quick response.

**Comment by Skuriles** [comment]
I have had the same problem with raspberry pi and Kodi and a fresh installation. I changed password and it did not work.
What worked for me was when I sent the PW via Kore App with my smartphone instead with a keyboard. Maybe the keyboard entry adds some not visible signs or something?

Maybe it was coincidence, but I've tried it at least 5 times with new and old password each by keyboard and it didn't work. Sending text with Kore app worked

**Comment by CastagnaIT** [comment]
if i could reproduce this problem I could work on it, but it's very rare
some example of the non working passwords?
perhaps you use some type of specia chars?

**Comment by Skuriles** [comment]
Hey,
yes hard to reproduce. I had no problems the first time I installed Libreele. Then I tried another OS and reinstalled Libreelec and the problem occured. 
Both PWs are only letters (upper and lower case) and numbers. No special signs.
