### ISSUE TITLE
Missing a lot movies from the list

### ISSUE THREAD

**Issue by usphil** [CastagnaIT/plugin.video.netflix#37]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Addon version used

[0.14.0 beta23]

### Description
[I can not get full list of movies from every item in the menu. EX: in Netflix Originals I just get 337 movies sort A B C, start with "#realityhigh" and the last movie is "Fre Rein: Valentine's Day. Missing a lot movies]

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional information on the environment

[I am using LibreELEC 9.0.1 on S905X TV box]

## Other information

[Movies playing very good with 720p (set from Inputstream Adaptive), get lag if set to 1080p]

**Comment by CastagnaIT** [comment]
It's not an error, it's a limitation that i imposed because getting more than 300 results means to weigh down the data request, which generates inputstream timeout error.

If you want to experiment with more results in the lists, change the setting to:
Expert settings -> limit list results
