### ISSUE TITLE
A way to copy and paste manual ESN

### ISSUE THREAD

**Issue by mcitew** [CastagnaIT/plugin.video.netflix#372]
## Help request
A way to copy and paste manual ESN

#### Your Environment
- Netflix add-on version: 0.16.0
- Operating system version/name: Android 9
- Device model: 

Used Operating system:
* Android

### Describe your help request
I need to configure the manual ESN. I am perfectly ok if I can just open a file and copy and paste.

**Comment by CastagnaIT** [comment]
this not depend from addon but from Kodi funtionality
you can connect a keyboard to the device or try use yatse app
or make a request in Kodi forum for implement a paste button
