### ISSUE TITLE
Export only seasons to library

### ISSUE THREAD

**Issue by loeffelpan** [CastagnaIT/plugin.video.netflix#378]
Thanks for all your work.
I really like you addon.

Is there any way to export just seasons to library?
I watched most of some show and would like to export just the last season instead of the whole show.

**Comment by CastagnaIT** [comment]
depends on how you set up the library configuration,
if you use auto update in manual mode you can export single seasons

**Comment by loeffelpan** [comment]
Just tried that but I didn't get it. There is just "Add to favorites" in my context menu when selecting a season.
Can you show that configuratio

**Comment by CastagnaIT** [comment]
you are right this option (export single season) was removed a long time ago
i can add it in next release

**Comment by loeffelpan** [comment]
I would be very appreciated.
Thank you.

**Comment by CastagnaIT** [comment]
Done

**Comment by loeffelpan** [comment]
Works for me.
Thanks.

**Comment by loeffelpan** [comment]
Just a little thing to this:
I noticed that "Exported" show the whole show, even when I exported only one season.
Maybe you should fix this.

**Comment by CastagnaIT** [comment]
'Exported' menu is only used to modify the objects in the library manually not to browse

**Comment by loeffelpan** [comment]
I got that.
But if I want to refresh my exported season on library, it shows me the whole show. And from there I can „refresh“ the whole show or another season I had not exported before.
So, it‘s not clear what is really exported and can be refresh without exporting something new.

If you won‘t fix that, I‘m fine with that.
But maybe you can improve that function of your addon.

**Comment by loeffelpan** [comment]
Oh, I have just activated „planed“ refresh of the library. Any every season of the exported show has been exported.
