### ISSUE TITLE
Resume Not Working As Expected

### ISSUE THREAD

**Issue by mattspew** [CastagnaIT/plugin.video.netflix#379]
#### Your Environment
- Netflix add-on version: 0.16.0
- Operating system version/name: Windows 10 & nVidia Shield
- Device model:  

Used Operating system:
* [ X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ X] Windows

### Describe the bug
I have the same behavior on both machines:

- If I go into a show folder, play something, stop it, press play, it will prompt to resume

- If I go into a show folder, play something, stop it, leave the show folder, go back, press play, it doesn't prompt and just starts from the beginning.

#### Expected behavior
Resume, like any local media.

#### Actual behavior
Not resuming as described above.

#### Steps to reproduce the behavior
As above.

### Debug log
The debug log can be found from this link: https://paste.kodi.tv/uxakinufab.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
This option is only a _workaround_ can not work if Kodi not provide the resume info, not depend from the add-on

in order to have a possibility this to work you have to set to the tv show folder a "information provider"
How to: Open context menu of the folder, select Edit, then press Ok, so set a "information provider"

**Comment by mattspew** [comment]
But the information provider is set and Netflix content is scanned into my library.

Kodi shows the resume icon, but it still doesn't work if you leave the show and come back.

**Comment by CastagnaIT** [comment]
what you mention is a Kodi bug that has existed for many years
I repeat, here we offer a workaround, does not depend on the addon if it does not work

**Comment by mattspew** [comment]
Sorry, I undertake there might be language barrier, but how is this a Kodi bug?

Resume works perfectly for local media. It's only Netflix via the Netflix plugin that doesn't work.

**Comment by CastagnaIT** [comment]
Yes it is a bug in the Kodi library specified for strm files...

**Comment by mattspew** [comment]
Right, so including Netflx in my Kodi library is totally pointless. Great add-on.
