### ISSUE TITLE
TV Show not removed from library

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#38]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

Removing an exported tvshow doesn't remove it from the Library

### Addon version used

[0.14.0.beta23]

### Steps to Reproduce

1. Export a TV Show
2. Remove the exported tv show

**Expected behavior:** [What you expected to happen]

TV show removed from library

**Actual behavior:** [What actually happened]

strm files are deleted
folders are deleted
tv show is not removed from the library

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Issue is platform independant, same problem on LibreELEC 9 or under Windows 10

## Debug log

https://pastebin.com/u5JFWtfT

**Comment by CastagnaIT** [comment]
download the zip of addon from github master branch, I've already fixed the problem

**Comment by Smeulf** [comment]
I'm sorry but the issue remains :(

I also uninstalled the addon, reinstalled it from the master version, still the same issue.

The show is removed from the exported items list, but not from the Kodi library itself.

I can see many "Cannot automatically remove a season from Kodi library, please do it manually" every time I try, plus the log says "Cannot remove u'tvshowid' from Kodi library, Kodi does not support this (yet)". I doubt this is the normal behavior, but maybe I'm wrong ;)

A new log maybe : https://pastebin.com/vs8eHnRi

Cheers.

**Comment by CastagnaIT** [comment]
by "kodi library itself" you mean "Favourites"?
I tried several times but I could not reproduce your error

especially the Arrow TV series mentioned in your log is not on the netflix list...at least here in italy there isn't

I export a TV show, it appears on the exported list,
then I'm adding in favorites, 
now if i delete it from the exported list, in the favorites remains, and that's normal, there is the appropriate menu to remove from the favorites.

do you take any different steps?

**Comment by Smeulf** [comment]
I don't use favorites, I use only the Kodi library.

Here's the steps:

- Export TV show -> it appears in the exported list
- Go to TV Show in Kodi main screen -> the exported tv show appears (as I added the show folder from the plugin addon_data folder to my sources list)
- Go back to netflix addon, remove the show from library -> the strm files and folders are deleted
- Go back to TV show in Kodi main menu -> the show is still there, but should have been removed automatically

Nevermind the show, "Arrow", "The O.A", or any other, the issue is the same ;(

If I'm correct, it should use JSON-RPC to perform a "VideoLibrary.RemoveTVShow", but I can't see this call anywhere in the logs.

**Comment by CastagnaIT** [comment]
I've had a different problem...

I tried to add lucifer and The o.a. 
then i only removed The oa.

in netflix plugin when I removed The OA, also removed Lucifer ?!? I do not know why....
on the kodi library, instead result correct, The OA removed and lucifer is still present

there's a little study to be done to solve this problem...
when i have more free time, i'll do some tests

**Comment by Smeulf** [comment]
I ran the same test with The O.A first and Lucifer then. Removed The O.A.

Strm files were removed for the O.A. but Lucifer files are still there.

Both shows are still in the library.

No hurry on this, I still can remove them manually. Take the time you need!

Feel free to ask for any test you want, on this issue or any other.
