### ISSUE TITLE
Please add namespace to the root of the DASH manifest for widevine tag

### ISSUE THREAD

**Issue by rgainza** [CastagnaIT/plugin.video.netflix#384]
<MPD mediaPresentationDuration="PT3428.0.00S" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:widevine="JUSTWRITEANYTHING" xmlns:cenc="urn:mpeg:cenc:2013">

This is to get rid of the error in browsers so that the xml can be properly read when debugging.

Change converter.py

def _mpd_manifest_root(duration):
    root = ET.Element('MPD')
    root.attrib['xmlns'] = 'urn:mpeg:dash:schema:mpd:2011'
    root.attrib['xmlns:cenc'] = 'urn:mpeg:cenc:2013'
    root.attrib['xmlns:widevine'] = 'Whazupheretogetridofnamespaceproblems'
    root.attrib['mediaPresentationDuration'] = duration
    return root

Or just skip using namespace solutions when showing the license

I don't understand the need for this to be written like this otherwise? It's shown just once anyway

<widevine:license robustness_level="HW_SECURE_CODECS_REQUIRED"/>
like this
<license robustness_level="HW_SECURE_CODECS_REQUIRED"/>
or
<widevine robustness_level="HW_SECURE_CODECS_REQUIRED"/>

**Comment by CastagnaIT** [comment]
How you try open this file?
this file is only for debugging not to open
the data inside `ContentProtection` are custom data for InputStream Addon

**Comment by rgainza** [comment]
I open it by using http://localhost:portnumber?manifest=id

The service makes my laptop crash when trying to play the stream so I debugged the addon this way.

**Comment by CastagnaIT** [comment]
The link is wrong, should be:
http://localhost:[port]/?id=[video_id]

and you should not use the browser, but a tool like curl

**Comment by rgainza** [comment]
Sorry just mixed id and manifest up since I don't have the files in front of me now.

Either way I don't see the reason why making faulty xml design. Inputstream still works anyway if this is corrected and then the manifest can be properly read and shown when debugging through a browser.

![image](https://user-images.githubusercontent.com/29674018/71084959-b42ed300-2196-11ea-9124-c62dba088553.png)

**Comment by CastagnaIT** [comment]
Again this is not intended for the browser scope,
what you want to add has not been added because the dash structure does not provide it

the file can be easily read from the data folder and in any case don't need to consult that file, 
if it is necessary do a debug for some problem, direct reference is made to the original netflix manifest not the converted one

**Comment by rgainza** [comment]
I do not believe for one second that the dash structure provided widevine:license as a tag without the use of namespace. I haven't even seen this particular tag in any dash structure from the big companies... 

But yes it was not a big issue. I just figured that it would be good to actually have a non-faulty dash structure in the case of inputstream relying on other ways to read the xml structure. I'll just add it myself when using the addon then...
