### ISSUE TITLE
Stream does not start

### ISSUE THREAD

**Issue by Philipp-prog** [CastagnaIT/plugin.video.netflix#387]
#### Your Environment
- Netflix add-on version: 0.16.1
- Operating system version/name:  LibreELEC 9.2.0
- Device model:  RasberryPi 3 Model B

Used Operating system:
* [ ] Raspberry-Pi

### Describe the bug

I use a rasberry Pi3 under LibreELEC 9.2.0 and the Netflix addon 0.16.1. The addon starts and I can use the library but the streams do not start. Sometimes the rasberry restarts. I have updated the addon several times but no changes so far. Thanks for your support and a merry christmas time.
#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/kehukipifa.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
the only error is the widevine library, possible it is corrupted
try reinstall it from inputSream helper settings, you can acces from Expert settings

thanks merry christmas also to you

**Comment by AndrewK528** [comment]
I use the same setup and had the same issues with 0.16.1. I re-installed 0.16.0 (which was still in the repo)- this runs without errors. I suspect a dreaded intermittent fault was introduced in 0.16.1

Merry Christmas to all 

and thanks for a great addon

**Comment by AndrewK528** [comment]
After some investigation it seems the dependency on the requests module was causing the issue. I forced an update to the latest release 2.22.0 and everything now works. Hope this may help anyone still having problems.
