### ISSUE TITLE
Addon fails to start

### ISSUE THREAD

**Issue by nzsjb** [CastagnaIT/plugin.video.netflix#388]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ x] Windows

### Describe the bug

I click on Addons, then Netflix icon, spinning wheel for a short while then Netflix error in the top right. This used to work although I haven't tried it in a while.

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3985872/kodi.log)

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
you're using the old addon version
uninstall the addon including user data when prompt
so install the new version as described in the readme guide

**Comment by Bestevaer** [comment]
I am having the same issue.
Reinstalled several times with your repository.
Also tried updating through an older version. To no avail.

I use it with android TV latest version. Netflix version 16.1
