### ISSUE TITLE
Removing a movie with accentuated caracters : UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 98: ordinal not in range(128)

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#39]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

Trying to remove a movie named "Elizabeth : l'âge d'or (2007)" from library triggers an error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 98: ordinal not in range(128)"

The accentuated character " â " is causing the problem, as " é " or " à ". I assume all accentuated caracters are.

Maybe tv shows have the same problem? Couldn't try yet.

### Addon version used

[0.14.0.beta23]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Find a movie with an accentued caracter, like " à ", " é ", "è", " â " and so on
2. Export the movie to the library
3. Remove the movie from the library -> triggers an exception

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Issue is platform independant, same on LibreELEC 9 or Windows 10.

## Debug log

https://pastebin.com/6MME9vCX

**Comment by CastagnaIT** [comment]
fixed

**Comment by Smeulf** [comment]
Thanks!

Main error is fixed, but some remains. The files are deleted, but the movie can't be removed from the library because(?) of a new error (in logs only): 

library.py:81: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              if os.path.normcase(library_item['file']) == exported_filepath:

https://pastebin.com/RPKvS67w

Hope you don't gonna hate me for so many bug reports ;)

**Comment by CastagnaIT** [comment]
I do not hate you, but i really hate this feature, it is disgusting has always problems of all kinds, is tiring me

**Comment by CastagnaIT** [comment]
Please test with this and report
[plugin.video.netflix_TEST.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3026832/plugin.video.netflix_TEST.zip)

**Comment by Smeulf** [comment]
This is working! Thanks!

Btw, I love this feature, mostly with TV show. So much pleasent when you have multiple sources and Kodi stations.
