### ISSUE TITLE
Cannot not play video

### ISSUE THREAD

**Issue by nzsjb** [CastagnaIT/plugin.video.netflix#390]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x ] Windows

### Describe the bug

1. Click on a movie in the Netflix addon.
2. Get categories up.
3. Select a category and then a movie.
4. Wheel circles for 30 seconds with background greyed out.
5. Wheel disappears and display no longer greyed out. Still just shows list of movies.

The log suggests ISA could not read the manifest.

There is also an earlier error at time 10:55:55:100 where the AddonSignals call timed out. As you can see I just retried at this point and it worked.

PS Apologies for MY previous post. Rookie mistake not checking for the latest version. 

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3991890/kodi.log)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
why you still using an old version of the addon?

**Comment by nzsjb** [comment]
Used the wrong zip. Now using 16.1 from 14/12/19 and the same thing happens. Log supplied.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3993097/kodi.log)

**Comment by CastagnaIT** [comment]
you have to set debug to verbose as described on readme otherwise you can't see anything in the log

**Comment by nzsjb** [comment]
Here you go. Thank you for your patience.

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3996356/kodi.log)

**Comment by CastagnaIT** [comment]
nf addon doesn't seem to be receiving requests for communication
this error doesn't sound right:
2019-12-24 10:10:30.268 T:5660   DEBUG: JSONRPC Server: Failed to bind IPv4 serversocket
2019-12-24 10:10:30.268 T:5660   ERROR: JSONRPC Server: Failed to create serversocket(s)

it's possible that some program is blocking Kodi socket ports
or also firewall or internet security software

**Comment by nzsjb** [comment]
Do you know what socket number(s) it uses or is it dynamic?

**Comment by CastagnaIT** [comment]
is set at first startup of the addon on fresh installation,
dynamic, the first free port that the operating system provides
is visible in the log

**Comment by nzsjb** [comment]
The log indicates that ports 16250/16251 were used.

Presumably if I get as far as trying to play a video the NF port will have been used successfully and it's the MSL port that is failing when trying to get the manifest. Is that right?

I'm pretty sure nothing is blocking the port. The only security software I have is Windows Firewall and that's set to allow Kodi thru.

**Comment by CastagnaIT** [comment]
I have no idea what's interfering in your computer
