### ISSUE TITLE
Empty folders / actual movies not showing

### ISSUE THREAD

**Issue by g-mike** [CastagnaIT/plugin.video.netflix#391]
#### Your Environment
- Netflix add-on version: 0.16.1
- Operating system version/name: Android 8.0 / Kodi Leia 18.5
- Device model: Nvidia Shield TV 2015

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
TLDR; Netflix login successful, but the addon is listing empty directories

I've tried different ESNs, various HDCP / streaming options with no luck.
I'm using Embuary Skin, howerver problem persists even on default Estuary.

#### Expected behavior
Addon should list movie / episode inside each folder.

#### Actual behavior
Addon shows empty folders.

#### Steps to reproduce the behavior
1. Installed Netflix Addon following these instructions: [https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon](url)
2. Enabled Input Steam Adaptive from addons
3. Successfully logged in to Netflix 
4. Addon lists shows correctly (titles, descriptions and images next to folder), however after entering folder is empty

### Debug log
The debug log can be found from this link: [http://bit.ly/2ETmk9f](url)

### Additional context or screenshots (if appropriate)
Screenshots: http://bit.ly/3964JJh

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

n/a

**Comment by CastagnaIT** [comment]
I see no errors in the log
have you tried reinstalling Kodi from scratch?

**Comment by g-mike** [comment]
After reinstalling KODI movies are displayed properly. However I cannot get 4k display on shield with Pie and 18.5 kodi / 0.16.1 NF. Atmos works.

I've read the whole discussion here on 4k in issues however no matter which setting I choose I cannot get 4k to work - Kodi changes rea/refresh rate and after that stucks switch loading icon. When in auto mode in adaptive streaming videos load only in 1080p with atmos. Tested on the Witcher

**Comment by CastagnaIT** [comment]
instruction for 4k problems is in readme
https://github.com/CastagnaIT/plugin.video.netflix#my-android-device-supports-4k-but-does-not-playback-at-4k

**Comment by g-mike** [comment]
I already did everything from the readme, checked all the configs, checked NF website for settings:

Expert Settings:
HEVC: on
Force HDCP: on

Adaptive:
Override HDCP: on
Min. Bandwith: 18.000.000
Stream Selection: auto
Ignore Display Resolution: read below 

Kodi:
Adjust display refresh rate: On start
MediaCodec (Surface): on
MediaCodec: on
Resolution: 3840x2160p
Refresh rate: 30.00
Delay after change of refresh rate: off
Number of buffers used by graphics driver: 3


Basically, I've reinstalled Kodi 18.5, added only Netflix plugin (0.16.1), and got it working with 1080p.

With Stream Selection: auto:
* Ignore Display Resolution: off - I'll get only 1080p with atmos
* Ignore Display Resolution: on, and Min. Bandwith 18.000.000 - video never loads, instead Kodi shows loading spinner infinitely.

Here's log: https://drive.google.com/open?id=1GUnssW_BPt0XG-thz4rnojC2SwlY7lL0

If I switch to Stream Selection: manual  and Ignore Display Resolution: off same thing happens: 
https://drive.google.com/open?id=1iH7My0J-cKi7R_SjrLYyztvJ6_oaOk5Y

My hardware is:

Shield TV 2015
Panasonic 65AX800
Pioneer SC-LX59

Also, 4k movies (when available) in the original NF app work fine.

Side note: when experimenting with different settings I got 4k working with Netflix plugin for a short time, but it was when Sync to Playback was enabled, and then Atmos wasn't working (only PCM).

Thanks for your support! :)

**Comment by CastagnaIT** [comment]
so in the log "Here's log:" the error come from a Kodi library
there's nothing i can do on my part
you have to report the problem to the Kodi team

the last log "If I switch to Stream Selection: manual",
i don't even look at it because, switch to manual, is only for debugging InputStream and is cause of problems with all netflix streams.
