### ISSUE TITLE
Playback error: Request failed during key exchange

### ISSUE THREAD

**Issue by Lerbiq** [CastagnaIT/plugin.video.netflix#392]
#### Your Environment
- Netflix add-on version:  16.1
- Operating system version/name:  Android TV (7.0)
- Device model:   Vivax 40LE78T2S2SM

Used Operating system:
* [*] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When trying to play movie playback error appears. No instructions found inside the log.

#### Expected behavior

Play movie/TV series without any issues

#### Actual behavior

Playback error window appears instead.

#### Steps to reproduce the behavior

1.Open netflix add-on, select profile, open Continue with watching folder
2.Select any movie or tv series
3.Get playback error ("Request failed during key exchange")

#### Possible fix

I don't have an idea.

### Debug log

The debug log can be found from this link:
https://drive.google.com/open?id=1AfIYs-KuQldMgXMNmurxnPSkxpCm25J0

### Additional context or screenshots (if appropriate)
Nothing

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

![IMG_20191224_190248](https://user-images.githubusercontent.com/57460117/71423750-beb40580-268b-11ea-9e8f-3f16d5d70c15.jpg)

**Comment by CastagnaIT** [comment]
This could means of wrong esn
you can try to write the esn from netflix app, or the one supplied with the device
in the expert settings of addon

Unfortunately, the log is incomplete and has been taken with unnecessary information
1) Go to add-on settings, in Expert page and change "Debug logging level" to "Verbose"
2) Enable Kodi debug: go to Kodi Settings > System Settings > Logging, and enable "Enable debug logging", disable "Component-specific logging" 

then create a new log

**Comment by Lerbiq** [comment]
There is a new log file: https://drive.google.com/open?id=1TGSo-dL_7sVaoaisiaAdth3F6DlWeRjI

**Comment by CastagnaIT** [comment]
i see some database errors htere is possible some broken data
so first remove addon with also user data when prompt, so reinstall

then, check if this esn:
NFANDROID2-PRV-ANDROIDTVREFERENCEMT5595-MTK==SMART=TV
is same of your device

**Comment by Lerbiq** [comment]
I've reinstalled the addon, but the issue still persists. And the esn is the same, but after 'TV' there is a lot of other numbers and letters. Does it matter?

**Comment by CastagnaIT** [comment]
yes, you can try insert the full esn, or also you can try use this
NFANDROID1-PRV-T-L3-MTK==SMART=TV

**Comment by geaddict** [comment]
I have the same issue. Where exactly would I insert this ESN?

**Comment by geaddict** [comment]
I should add that it is happening on 3 different devices. Two Minix boxes with different Kodi and Android versions and a Sony smart TV.
