### ISSUE TITLE
Launch Netflix App on Windows as an external player

### ISSUE THREAD

**Issue by smoothquark** [CastagnaIT/plugin.video.netflix#393]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

Just wondering... is it possible to launch the Windows Netflix app as an external player for a netflix movie or tv show instead of the built-in player?

#### Describe the use case

In windows, this could possibly allow playback in UHD/Atmos if it is passed to the Netflix App

**Comment by CastagnaIT** [comment]
This request is similar to: https://github.com/CastagnaIT/plugin.video.netflix/issues/155

This functionality must work with every operating system
its implementation is not simple and immediate, require work
and few rare users require it, it is not a priority

I close this issue as a double, and i keep the other one
