### ISSUE TITLE
Leaking Passwords?!

### ISSUE THREAD

**Issue by instreamer** [CastagnaIT/plugin.video.netflix#396]
I've installed the castagnaIT repro and netflix addon on Kodi (LibreELEC - RaspberryPI - fresh install)

Installation of netflix addon + dependencies worked, login + test stream of a movie as well.

10 Minutes later I tried to login into my netflix account from a new device - password wrong.

I'm still logged into netflix in chrome - tried to change password - current password incorrect.

What's up with that?? This seems more than just fishy.

**Comment by Essam311** [comment]
Most likely that Netflix changed the password by itself, check your email and you might find an email from Netflix asking you to reset the password.

**Comment by CastagnaIT** [comment]
Ref from Essam: https://help.netflix.com/en/node/56461

The addon does not reset passwords and being opensource software, anyone can actually understand its secure work. As Essam says, it's definitely been changed by netflix.

In this addon the credentials are encrypted with a moderate level of security that is associated with the device in use.
The only way for a thief to steal your credentials is to take possession of your device. It's a very rare and difficult eventuality that happens. If this has happened, it means that every data on your device has already been compromised.
