### ISSUE TITLE
Netflix can browse, but will not play movies

### ISSUE THREAD

**Issue by TheB1000** [CastagnaIT/plugin.video.netflix#398]
#### Your Environment
- Netflix add-on version: 16.1 on Kodi version 18.2
- Operating system version/name: RetroPie
- Device model:  Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe the bug
I can log in and browse Netflix, but when I try to play a movie, I get an error message.  Sometimes it will tell me that my email or password is incorrect and other times it says Exception: ProfilesMissing.

Exception:  ProfilesMissing.

Email or password is incorrect

https://paste.kodi.tv/kixalobofi

#### Expected behavior
Movie should begin to play normally

#### Actual behavior
Receive error message

#### Steps to reproduce the behavior

1.  Start Netflix Add-on
2.  Browse to My List
3.  Attempt to play movie

### Debug log
The debug log can be found from this link:
https://paste.kodi.tv/kixalobofi

**Comment by CastagnaIT** [comment]
the log is incomplete follow the instruction to get a right log file from the  readme

**Comment by TheB1000** [comment]
Sorry, I had debugging turned off.  The Kodi log viewer is not cooperating at the moment.  As soon as I can get a proper log pulled I'll post it.  Thanks!

**Comment by TheB1000** [comment]
Here is the new log: http://paste.kodi.tv/eguwezeyov

Let me know if that's what we're looking for.

**Comment by CastagnaIT** [comment]
i see some errors from database, try delete addon with also delete user data, so reinstall it

**Comment by TheB1000** [comment]
That worked for me.  Thanks for looking into it and for this great add-on!
