### ISSUE TITLE
Wrong ESN for Xiaomi Mi Box.

### ISSUE THREAD

**Issue by mkaflowski** [CastagnaIT/plugin.video.netflix#399]
There is wrong ESN for Xiaomi Mi Box. I have tried change it according to info from settings and now it works:
[https://photos.app.goo.gl/fcSctq2ZG52WMHgf7](https://photos.app.goo.gl/fcSctq2ZG52WMHgf7)

I have typed:

> NFANDROID2-PRV-XIAOMIM12TRIAL-XIAOMMIBOX3

Could you update it?

**Comment by CastagnaIT** [comment]
the esn is generated, but the generation is not always precise

I can only try to see if something can be done if you give me the output of "getprop" command from the shell or adb shell

Or in alternative you can give me from the getprop results, only these values:
ro.product.manufacturer
ro.product.model
ro.build.characteristics
ro.nrdp.modelgroup

**Comment by mkaflowski** [comment]
Ok, thank you. I thought that it is hardcoded.
