### ISSUE TITLE
No ListItem.Season infolabel at Seasons level of TvShow.

### ISSUE THREAD

**Issue by jurialmunkey** [CastagnaIT/plugin.video.netflix#400]
#### Your Environment
- Netflix add-on version: 0.16.1
- Operating system version/name: Win 10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug
`$INFO[ListItem.Season]` infolabel is not filled at season level of a tvshow.

ListItem.Season will ensure better integration with TMDbHelper's player function. Currently I am forced to select the season item at the position matching the season number - which is error prone if a season is missing from Netflix or there are special seasons.

See comment here for example:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/24#issuecomment-569165434

#### Expected behavior
ListItem.Season should return the season number of the season at both the Season level and the Episode level of a TvShow

#### Actual behavior
ListItem.Season is empty at the Season level and is only filled at Episode level.

#### Steps to reproduce the behavior
1. Open Plugin and Search for a Tvshow (e.g. Stranger Things)
2. Click Tvshow to open Seasons view of TvShow.
3. ListItem.Season is empty.

**Comment by CastagnaIT** [comment]
I'll check the return data
I'll let you know

**Comment by CastagnaIT** [comment]
The only way i know is to filter the shortName field,
in principle it should be fine, unfortunately netflix also assigns particular names so i don't know if the value will be obtained 100% of the cases..

Please test the PR

**Comment by CastagnaIT** [comment]
Remember to do Purge cache on memory and disk in expert settings before test

**Comment by jurialmunkey** [comment]
Seems to be working well. Thanks! 😁

**Comment by CastagnaIT** [comment]
well well
