### ISSUE TITLE
Searches return no results

### ISSUE THREAD

**Issue by nubjub** [CastagnaIT/plugin.video.netflix#402]
#### Your Environment
- Netflix add-on version: 0.16.1
- Operating system version/name: Devuan (beowulf)
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

The search function from the main menu return no results. I had the same behavior in 0.15.2, I was hoping this would be fixed in an up coming update. Log as follows shows no error:
`INFO: CPythonInvoker(6, /home/xbmc/.kodi/addons/plugin.video.netflix/addon.py): script successfully run`

#### Expected behavior

Searches return results. By the way, everything else seems to work satisfactorily, I'm just surprised this issue isn't open already.  

#### Actual behavior

Searches return nothing, (an empty folder).

#### Steps to reproduce the behavior

1. Start with a fresh install of the addon, no userdata.
2. Successfully login to Netflix.
3. Search for something from the main menu Search item.

### Debug log

The debug log can be found from this link:
https://drive.google.com/open?id=14XkKsoYntQYbpVbTkApkAwMjwguQ9_hX

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Nobody opened issue because it works for other people... and also to me...
from what I see from the log you installed a modified version of the Addon
only by installing the original version from my repository i can investigate

**Comment by nubjub** [comment]
My point in saying I was surprised the issue didn't already exist was that I had just assumed it was something that was coming in the future, realizing the issue didn't exist indicated to me that this is not a common problem. 
There's nothing modified about it I installed this https://github.com/CastagnaIT/repository.castagnait/blob/master/zip/plugin.video.netflix/plugin.video.netflix-0.16.1.zip
Is that not the version from your repository? As i said repeatable with a fresh install.

**Comment by CastagnaIT** [comment]
this is from my repository
but the log you attached contains information that is not related to the version of my addon
so i don't know what you did, but these are the facts...

**Comment by nubjub** [comment]
I just removed everything i know to be related. Installed this repo https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.0.zip. Then installed the addon from repository. 
https://drive.google.com/open?id=1eM8Dz5ScFNTOEXI8E9PwL5ZkbqWIAQ4V
Hopefully we can agree this is your addon now. If not perhaps you can be more precise about what isn't related.

**Comment by nubjub** [comment]
I'm swinging in the dark here, but if your parsing the log for interesting things perhaps:
https://drive.google.com/open?id=1KZiwF7rpYQ0aOZBqNJT15Sltaaj-BbB6

**Comment by CastagnaIT** [comment]
I don't see anything unusual in the log
but all profile ids and guids have strange values

After pressing OK on search dialog, it is indicated that you have pressed shift and then another command that i don't know, it happens before the addon starts to get the data and then it stops

**Comment by nubjub** [comment]
The keyboard inputs are `t` `e` `s` `t` `return` then the search returns no results:
```
DEBUG: [plugin.video.netflix (1)] Cache commit successful
INFO: CPythonInvoker(6, /home/xbmc/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
DEBUG: ------ Window Deinit (DialogBusy.xml) ------
```
At this point the app has returned no results (empty folder), nothing's about to start getting data.
```
DEBUG: Thread BackgroundLoader start, auto delete: false
DEBUG: Thread BackgroundLoader 139726468138752 terminating
```
Six seconds pass, then I input `exclaim (0xf021)` (the exclamation point) which I have bound to RestartApp. Shutting down kodi as that's all there is to see here.

**Comment by Essam311** [comment]
@CastagnaIT Hi, your version of the Netflix plugin had some minor problems with the search for some single words from the days when caphm was working on it, which I do not think he solved them properly,  see here.

https://github.com/asciidisco/plugin.video.netflix/pull/519#issuecomment-436040999

**Comment by nubjub** [comment]
I did a complete reinstall of kodi, netflix addon went in first and the same result, no search results. Then I tried it from the chorus2 webui and it works! So I tried another skin, (I've been using the default estuary) the new skin works as well. The new skin required the addon script.skin.helper.service. I think the absence of this addon may be the culprit, I'm still investigating though.

**Comment by CastagnaIT** [comment]
can you update to lastest Kodi version? 18.5?

**Comment by CastagnaIT** [comment]
Closed due to inactivity
