### ISSUE TITLE
Request failed validation during key exchange

### ISSUE THREAD

**Issue by Lasagnemitglas** [CastagnaIT/plugin.video.netflix#404]
#### Your Environment
- Netflix add-on version: 18.5
- Operating system version/name: Android 8.1
- Device model: some china TV Box 

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Hey :),
first sorry for my bad english 

I install the addon from the official Repo
Login are working but when i select a movie it says : „ Request failed validation during key exchange“

Pls help thank you
#### Expected behavior
Play a movie
#### Actual behavior
Error 

#### Steps to reproduce the behavior

1.login
2.play a movie
3.

Log : https://paste.kodi.tv/utipagewux.kodi

Screenshot : 
![image](https://user-images.githubusercontent.com/59346424/71563997-412c3300-2a99-11ea-9081-e41bff4e601f.jpg)

**Comment by CastagnaIT** [comment]
it may be that the device is not officially approved by netflix
this is the esn that cause problem: NFANDROID2-PRV-TVBOX-ROCKCTVBOX

you can try to insert manually an esn in expert page setting,
by copy it from netflix official app (if it is different)

or you can also try to insert this:
NFANDROID1-PRV-T-L3-TVBOX-ROCKCTVBOX
but if you use 4k, the 4k will not work

**Comment by Lasagnemitglas** [comment]
It works with your esn :) thx

**Comment by kripper** [comment]
Using `NFANDROID1-PRV-T-L3-TVBOX-ROCKCTVBOX` I get: "Wrong ESN format"
