### ISSUE TITLE
background services

### ISSUE THREAD

**Issue by Sc4res** [CastagnaIT/plugin.video.netflix#405]
#### Your Environment
- Netflix add-on version: v0.16.1
- Operating system version/name: OSMC
- Device model:  Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ x] Raspberry-Pi
* [x] Windows

### Describe the bug

When i start my Raspberry it just tells me Netflix error and then I try to start Netflix and it just says" Netflix Addon Error : The background services may not yet be available if you just started Kodi/the addon. In this case, try again in a momen." but i can wait like 3 hours still wont work.

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/amimatoyet

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
missing library, follow instruction to how install on OSMC
https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon

**Comment by Sc4res** [comment]
I am a retard xD thx 4 the help and Happy new year!
