### ISSUE TITLE
Extension hangs on login

### ISSUE THREAD

**Issue by matejdro** [CastagnaIT/plugin.video.netflix#406]
#### Your Environment
- Netflix add-on version: 0.16.1
- Operating system version/name: Windows 10 1803
- Kodi version: 18.2

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ X ] Windows

#### Expected behavior
Extension should login properly and display the menu.

#### Actual behavior
After entering login information, extension displays "Login Success" notification and then hangs on infinite loading spinner.

#### Steps to reproduce the behavior
1. Install extension from scratch
2. Open extension
3. Enter your email and password

### Debug log
The debug log can be found from this link: [logs.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/4010950/logs.txt)

This appears to be the cause, from logs:

`ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'ui', u'initParams', u'apiUrl']`

#### Installation
From CastagnaIT repo

**Comment by CastagnaIT** [comment]
log incomplete, read the readme to get a right log

**Comment by matejdro** [comment]
Sorry, you are correct. I  forgot to enable in-add-on debugging.

Attaching logs: 
[logs2.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/4013113/logs2.txt)

**Comment by CastagnaIT** [comment]
again wrong log
and DO NOT EDIT the log or i close the issue
what are you afraid someone steal what a useless hash code?

**Comment by matejdro** [comment]
Can you please be more specific on what exactly is missing?

**Comment by CastagnaIT** [comment]
are you kidding???
he instructions are clearly written when you open an new post ISSUE:
> 1) Go to add-on settings, in Expert page and change "Debug logging level" to "Verbose"
> 2) Enable Kodi debug: go to Kodi Settings > System Settings > Logging, and enable "Enable debug logging"
> 3) How to get the log file? Read Kodi wiki: https://kodi.wiki/view/Log_file/Easy
> RESPECT THE RULES!
> - A DEBUG LOG IS ALWAYS MANDATORY WHEN CREATING AN ISSUE. PROVIDE A LINK TO THE LOG!
> - DO NOT PASTE THE CONTENT OF THE LOG HERE
> - DO NOT CUT THE LOG
> - If the log file is really huge (more 1Mb) in Kodi settings disable "Component-specific logging" then create a new log

**Comment by matejdro** [comment]
This is exactly what I did. I just trimmed the log because there was a lot of useless plex-related entries bloating the log size before and after that. There are NO netflix-related entries before and after that.

**Comment by matejdro** [comment]
Just a heads up if anyone else finds this from Googling: The issue was skin. After switching to another skin, addon started working.

@CastagnaIT Since issue was skin-related, there was no relevant log entry. I understand the frustration since information appears to be missing from logs, but that was not a very nice reaction. Thanks for the add-on regardless, it seems to be working great now.
