### ISSUE TITLE
Trakt Integration

### ISSUE THREAD

**Issue by fjrider** [CastagnaIT/plugin.video.netflix#411]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

Great plugin!  Would love to be able to integrate Trakt.tv scrobbling/syncing with Netflix viewing in this Kodi Addon.

#### Describe the use case

Could be useful for anyone who likes to use Netflix and Trakt

#### Development tips

Unfourtunately I can't write code (yet), but am technical.

I could text on Linux, Mac, Windows, LibreELEC machines that I tinker on etc.

**Comment by notoco** [comment]
Trakt.tv integration works great with a plug-in from the kodi repository. Yes, it's one-sided -, but it works - the tract page shows you what you're watching right away.

**Comment by kidforpm** [comment]
If shows or movies are added to your collection (either automated or manual) the standard Trakt.tv plugin will even sync both ways. Also it will mark the series as collected when added to your library.

When you just watch through the plugin it will only scrobble and mark watched.

Please do note, in the settings from the TRAKT plugin, you have to disable "Exclude HTTP sources". I have configured the plugin a long time ago, so I'm not sure, I think it is enabled by default. This means by default it will not scrobble HTTP (Netflix) streams.

**Comment by fjrider** [comment]
Thanks notoco and kidporpm.

I have the normal Kodi repository Trakt.tv plugin already, doesen't seem to be syncing.

I will have to tinker with the HTTP settings as you mention!

**Comment by CastagnaIT** [comment]
I do not provide support for Trakt
if you need help with it ask for help in the Kodi forum
thanks
