### ISSUE TITLE
Shield 2017: 4K titles won't play, others are fine.

### ISSUE THREAD

**Issue by farhanito** [CastagnaIT/plugin.video.netflix#415]
#### Your Environment
- Netflix add-on version: 0.16.0
- Operating system version/name: ANDROID TV Pie
- Device model:  Nvidia Shield TV 2017

Used Operating system:
* [X ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

4K titles won't stream, just spinning wheel. Non-4k titles works fine.

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

https://paste.kodi.tv/ijariwijom.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
First i suggest to update addon to last version available
so read 4k problem instructions to the readme
