### ISSUE TITLE
Thumbs up/down and remove/add from "My List", doesn't work anymore.

### ISSUE THREAD

**Issue by jotakswe** [CastagnaIT/plugin.video.netflix#419]
#### Your Environment
- Netflix add-on version:  plugin.video.netflix_0.16.1_20200101_t2
- Operating system version/name:  LibreELEC 9.2.0
- Device model:   HTPC

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

It no longer works to rate or remove/add a movie from "My List" or in any other list.

#### Steps to reproduce the behavior

1. Standing on a movie in "My List" or in any other list, open up "Context Menu", and then select "Rate movie" or "Remove from My List" rendering an error message.
2.
3.

### Debug log

The debug log can be found from this link: https://github.com/CastagnaIT/plugin.video.netflix/files/4023932/kodi_crashlog_20200105171504.log

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
I think something broke in your installed addon
this error should disappear by login in to another nf profile and after return to the previous profile

**Comment by jotakswe** [comment]
@CastagnaIT 
Ok, I'll try to make another profile and switch back and forth and see if it helps.

**Comment by jotakswe** [comment]
@CastagnaIT 
It worked. Thanks for the help.
I'll close the case after you read this.

**Comment by CastagnaIT** [comment]
very well
