### ISSUE TITLE
Background service not available / AddonSignals timed out

### ISSUE THREAD

**Issue by JeroenTuinstra** [CastagnaIT/plugin.video.netflix#42]
*I'm submitting a ...*
  * bug report
  - [ ] feature request
  - [ ] support request

## General information
disabling or enabling IPC over HTTP generates two different addon errors. 
Disabled (standard) it generates the error AddonSignals call timed out.
Enabled it generats the error the background services may not yet be available

### Addon version used

0.14.0~beta 23

### Description

With the standard settings (IPC over HTTP disabled) it generates the error "AddonSignals call timed out" (kodi_log1). So I decide to enable IPC over HTTP. At startup it generates the error "The Background Services may not yet be available" (kodi_log2).

### Steps to Reproduce

1. disable IPC over HTTP
2. reboot: "AddonSignals call timed out" (kodi_log1)
3. enable IPC over HTTP
4. reboot: "The Background Service may not yet be available". (kodi_log2)

**Expected behavior:** [What you expected to happen]
No errormessages ;-)

## Context (Environment)
PC with LibreELEC 9.0.1
### Installation

[*] I'm using this Netflix Repo
[ ] I'm using other Netflix Repo (Please specify which)
[ ] I'm using a different source (Please tell which)

### Operating System

[*] Linux (x86/x64)
[ ] OSX (x86/x64)
[ ] Windows (x86/x64)
[ ] Linux (ARM)
[ ] Android

#### Additional informatin on the environment
LibreELEC 9.0.1

## Other information

kodi_log1: https://www.dropbox.com/s/ckrk5rym8fzy1yj/kodi_log1.log?dl=0
kodi_log2: https://www.dropbox.com/s/mypoxw53dni17oj/kodi_log2.log?dl=0

### Screenshots

![screenshot001](https://user-images.githubusercontent.com/47460053/55356715-ae3f7780-54cb-11e9-85d4-399f0ee495cd.png)
![screenshot000](https://user-images.githubusercontent.com/47460053/55356722-b13a6800-54cb-11e9-9d16-fa8532bef46f.png)

**Comment by jakermx** [comment]
try modifying the ipc.py file line 76

from this
urllib2.urlopen(url=url, data=json.dumps(data)).read(),

to this line
urllib2.urlopen(url=url, data=json.dumps(data), timeout=60).read(),

On my RPI2B+ I have to I disabled AddOnSignals and go with IPC option , but on my RPI3 have it enabled withou issues.

**Comment by CastagnaIT** [comment]
the log suggests a communication problem with the server is possible that you have some wrong settings on your network, or nat / proxy / vpn

**Comment by jakermx** [comment]
try delaying the widget and skin, so netflix addon backgroud services could start....

In order to test this hteory, remove any home widget or change to default skin, disabling widgets...

**Comment by mac1202** [comment]
Hi also had this issue, very annoying error message popup several time a day even when I'm not using netflix. Except for this error the plugin work perfectly fine when I use it.  Is there anyway to make the popup less intrusive, I have enable the setting "show notification instead of modal dialog for error" but it doesn't seem to apply to this error message. Thank

**Comment by JeroenTuinstra** [comment]
Just a quick update, I have changed to "show notification instead of modal dialog for error", so now I only get a small error message. IPC over HTTP is disabled. So the background service does start. The error AddonSignals remains but not visible. Netflix seems to work.
I am not sure what the error in the communication is, as all other addons are working fine it seems. Can you extract from the logfil which server it tries to communicate to?

**Comment by JeroenTuinstra** [comment]
@jakermx If this theory is right, how would I delay the skin and the widgets?

**Comment by CastagnaIT** [comment]
Widgets skins are causing a lot of problems i do not recommend its use, widgets force the addon to work incorrectly

**Comment by JeroenTuinstra** [comment]
, @CastagnaIT So the solution is to run this addon only in a basic setup of kodi? What is actually causing the problem. As it seems "you're damned if you do and you're damned if you don't".

**Comment by CastagnaIT** [comment]
widgets often force the content to load before the addon completes its initial configuration, there were other people who found a workaround, maybe you find something in the closed issues

**Comment by JeroenTuinstra** [comment]
Tried the suggestion with timeoout=60 @jakermx but doesn't make a difference, with both settings (IPC over HTTP enabled or disabled) the error occures still. The workaround is that I enable the "show notification instead of modal dialog for error" and basically ignore the error. Not very elegant and strangely in previous versions it was working fine. Hopefully there will be a version that keeps widgets in mind as I am sure I am not the only one facing this issue. Anyway thanks for all the work on this. I'll keep it open, as it is not resolved.

**Comment by CastagnaIT** [comment]
in the closed issues not this...

**Comment by JeroenTuinstra** [comment]
None of the closed issues seem to talk about it. I generally search first before I would report a bug.

**Comment by jakermx** [comment]
what happen if you use default skin or if you disable netflix addon and once kodi finishes the startup, you eneble it?

**Comment by jakermx** [comment]
or try removing ssl verification

**Comment by CastagnaIT** [comment]
try to change the skin you're using, and use the default kodi skin

**Comment by CastagnaIT** [comment]
if within 3 days there are no more answers,
i close it
