### ISSUE TITLE
Version 16.1 frequentlly crashes kodi or gives error when starting stream

### ISSUE THREAD

**Issue by George-R-Young** [CastagnaIT/plugin.video.netflix#420]
#### Your Environment
- Netflix add-on version: 16.1
- Operating system version/name: Android 7.1.2

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When trying to play a video stream from MyList in Version 16.1, I often get an error message or Kodi crashes. When I revert back to version 16.0, this problem does not occur.

#### Expected behavior

The video stream should play in Version 16.1.

#### Actual behavior

When trying to play a video stream in Version 16.1 from MyList, I often get an error message or Kodi crashes. 

#### Steps to reproduce the behavior

1. Click on title in MyList
2.
3.

#### Possible fix

This problem does not occur in Version 16.0

### Debug log

The debug log can be found from this link:
Debug log for Version 16.1 crash:
https://paste.kodi.tv/emepazexoc.kodi

Debug log for successful Version 16.0 operation:
https://paste.kodi.tv/tazagomodo

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
there is no errors in the logs,
read the readme to get a right debug log

**Comment by George-R-Young** [comment]
Alrighty, I re-installed Version 16.1 and in Expert, set Debug logging to Verbose,
In Kodi, I enabled debug logging.
I restarted Kodi, ran the add-on, clicked on the first item in MyList and it ran successfully. I stopped it and clicked on the second item in MyList and Kodi exited to the operating system. The kodi.log file can be found at https://paste.kodi.tv/jurisakodi.kodi

**Comment by CastagnaIT** [comment]
unfortunately the log is same of previous the logging is not set to verbose,
but your problem sound like an already opened issue: https://github.com/CastagnaIT/plugin.video.netflix/issues/403

**Comment by CastagnaIT** [comment]
new version released,
if the update resolve the problem close the issue

**Comment by George-R-Young** [comment]
Humble apologies, I discovered that in addition to setting Verbose, you have to press ok or the setting is cancelled when you escape. In this trial, the first 3 movies played happily, the fourth caused a crash.
Log file: https://paste.kodi.tv/ohicihutan.kodi

**Comment by CastagnaIT** [comment]
update the addon

**Comment by George-R-Young** [comment]
Updated to 16.2 and all is well. Thanks a bunch.
