### ISSUE TITLE
No Full-HD streams available on Linux

### ISSUE THREAD

**Issue by mrblond18** [CastagnaIT/plugin.video.netflix#422]
#### Your Environment
- Netflix add-on version: 0.16.2
- Operating system version/name: Ubuntu 18.04
- Device model:  Intel NUC 8i3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ x ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ x ] Windows

### Describe the bug
When I use the netflix addon in Linux I get less video streams to choose from. The higher resolution (and bitrate) ones are not available. When I use Kodi on the exact same system (dualboot) I do get the Full HD versions for the exact same video.

I use a vanilla kodi install on both with only the netflix addon installed.

In Linux I have the following streams:
(vp9, 480x270, 13144bps)(1/7)
(vp9 608x342, 134144bps)(2/7)
(vp9 768x432, 190464bps)(3/7)
(vp9 960x540, 282624bps)(4/7)
(vp9 960x540, 425984bps)(5/7)
(vp9 960x540, 569344bps)(6/7)
(vp9 960x540, 844800bps)(7/7)

In Windows I have the following streams:
(vp9, 480x270, 13144bps)(1/10)
(vp9 608x342, 134144bps)(2/10)
(vp9 768x432, 190464bps)(3/10)
(vp9 960x540, 282624bps)(4/10)
(vp9 960x540, 425984bps)(5/10)
(vp9 960x540, 569344bps)(6/10)
(vp9 960x540, 844800bps)(7/10)
(vp9 1280x720, 1335296bps)(8/10)
(vp9 1920x1080, 2464768bps)(9/10)
(vp9 1920x1080, 4582400bps)(10/10)

#### Expected behavior
I expect the same streams to be available in both Linux and Windows.

#### Actual behavior
Linux has less streams available, only the low res, low bitstream ones

#### Steps to reproduce the behavior
see above

#### Possible fix
Don't know, please help

### Debug log
The Linux debug log can be found from this link:
https://pastebin.com/fWs3p8Rq

#### Screenshots

**Comment by CastagnaIT** [comment]
read the readme, i can not do nothing

**Comment by mrblond18** [comment]
> read the readme, i can not do nothing

Hi CastagnaIT, thanks for the very quick reply.

If I understand correctly, what you refer to is the "Reference table of high resolutions" in the FAQ of the addon. I think I read there that in Windows and Linux (distros) the same resolutions should be available. Do I misunderstand?

**Comment by CastagnaIT** [comment]
Windows and Linux + 1080P are linked to point *1

> *1 With Software decoding not all videos could be at 1080P.

it doesn't say they have to have the same resolutions

**Comment by mrblond18** [comment]
> Windows and Linux + 1080P are linked to point *1
> 
> > *1 With Software decoding not all videos could be at 1080P.
> 
> it doesn't say they have to have the same resolutions

Ok thanks, too bad.
