### ISSUE TITLE
SQLite deadlock

### ISSUE THREAD

**Issue by 23doors** [CastagnaIT/plugin.video.netflix#425]
## Bug report

https://github.com/CastagnaIT/plugin.video.netflix/commit/3392a7e8c579a251dfd91aec530a62bd41777110 commit created a deadlock.

### Describe the bug

When exporting items you get a deadlock. To reproduce, enter a series, open context of one season and run "Update inside library". 

Commit that I mentioned above created it as it handles thread local connection incorrectly.
For example:
`g.SHARED_DB.insert_season` which is defined here: https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/database/db_shared.py#L285 is decorated with handle_connection and it then calls `season_id_exists` which also is decorated with it.

Which after this commit results in:
1. mutex lock
2. create connection
3. enter insert_season
4. call season_id_exists
5. in season_id_exists decorator: again mutex lock - but well, we cant. We haven't unlocked previous one.

#### Possible fix

Revert that commit and make is_connected a thread local. Easiest way out. Until then 0.16.2 and master versions are not usable with sqlite database.

**Comment by mackal** [comment]
Was having some issues with doing full syncs etc, downgraded to 0.16.1 and it works again. Probably same issue. Log files, even with extra logging on didn't provide any better details to me either.

**Comment by notoco** [comment]
I have exactly the same mistake - I've been sitting on it for three hours because I thought it was due to the transfer of my library to a network resource...

**Comment by 23doors** [comment]
fixed in master by https://github.com/CastagnaIT/plugin.video.netflix/pull/426

**Comment by 23doors** [comment]
@CastagnaIT this is still a breaking bug in current latest version and only fixed on master. Could you issue a new release?

**Comment by CastagnaIT** [comment]
I wanted to wait a while to try apply the solution to the problems with android devices but it seems to take longer
I'll be making a new release soon

**Comment by 23doors** [comment]
I guess you mean android devices other than shield? Causs I use shield 2017 for quite some time without a hitch so I wasn’t aware of any issues.

**Comment by CastagnaIT** [comment]
yes, i think netflix is turning off the taps for the use of "generic" ESNs for Android
and here we only generate generic ESNs, so without the last part
