### ISSUE TITLE
Netflix language learning

### ISSUE THREAD

**Issue by lameventanas** [CastagnaIT/plugin.video.netflix#428]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

There's a [Chrome extension](https://soranews24.com/2020/01/12/free-language-learning-with-netflix-extension-makes-studying-japanese-almost-too-easy/) that allows learning foreign languages by showing subtitles in the local and foreign language at the same time (among other features).  It would be great to be able to do this with Kodi too!

#### Development tips

The Chrome extension is out there, so how hard can it be? ;)

#### Screenshots

![Sample image](https://sociorocketnewsen.files.wordpress.com/2020/01/lln-04.png?w=640&h=312)

**Comment by CastagnaIT** [comment]
I am not aware that kodi supports two subtitles at the same time, i only saw specially edited subtitles,
in any case the operation is totally different from the browser,
this should be requested to the kodi team as a new feature (and also cooperate with inputStream addon)

when will be introduced, you can give me references on how to implement it, in the meantime i'm closing
