### ISSUE TITLE
Can not add item to My List anymore

### ISSUE THREAD

**Issue by mrblond18** [CastagnaIT/plugin.video.netflix#429]
#### Your Environment
- Netflix add-on version: 0.16.2
- Operating system version/name: Ubuntu 18.04
- Device model:  Intel NUC 8i3

Used Operating system:
* [ ] Android
* [ ] iOS
  [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
When I try to add a show to my list via the contect menu and "Add to 'My list'" I get an error:
The addan encountered the following error:
Exception HTTPError.
...

#### Expected behavior
I expected the show to be added to My List and not give such an error.

#### Actual behavior
I get the error as described above.

#### Steps to reproduce the behavior
Open Netflix app, choose account, search for a show/movie (I searched for The Perfection), open the conext menu on a movie and press "Add to 'My List'"

#### Possible fix
Don't know.

### Debug log
https://paste.ubuntu.com/p/fPzCgrQk24/
Error at 2020-01-12 20:11:11.249 T:140041342928640

**Comment by CastagnaIT** [comment]
fixed install the daily build

**Comment by mrblond18** [comment]
Thanks, works like a charm. You can close this one.
