### ISSUE TITLE
Can't play Videos under Le 9.0.2

### ISSUE THREAD

**Issue by Coolzero82** [CastagnaIT/plugin.video.netflix#432]
## Bug report
Hello,
i can't see Videos on LibreElec 9.0.2 with the Netflix addon,
#### Your Environment
- Netflix add-on version: netflix v0.16.2
- Operating system version/name: LibreElec 9.0.2
- Device model:  I86x64

Used Operating system:
* [ ] Linux

### Describe the bug
When i want to see a Film, a become a error message, that the video can't play, see the Kodi Log attaeched
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4055423/kodi.log)

**Comment by CastagnaIT** [comment]
log incomplete, read the readme to get a right log

**Comment by Coolzero82** [comment]
Hi,
here is the Debug Log, the log is everytime more then 1 MB.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4060899/kodi.log)

Here two pictures of the error
![Uploading Netflix_2.jpg…]()
![Uploading Netflix_1.jpg…]()

**Comment by Coolzero82** [comment]
Can you tell me anything about my problem?

**Comment by CastagnaIT** [comment]
I don't understand the root cause
there is a lot of addon instance opened at same time
and this can be the cause of your problems

in the log i see a lot of skin helper, perhaps you use a lot of widgets?

You can try to install this updated version (so the next 0.16.3), but if is a widget problems there is nothing that i can do
[plugin.video.netflix_0.16.2_20200116.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4073219/plugin.video.netflix_0.16.2_20200116.zip)

**Comment by Coolzero82** [comment]
I will test the update soon.
The log directly after a reboot and i didn't start anything except Netflix.  The Rapir Skin has some widgets , but thats all i use.

I will post the resultat of the update soon
Thank you

**Comment by Coolzero82** [comment]
I just tested it and the problem is bigger than before, now the error message usually comes when I want to select a film area (genre).

**Comment by CastagnaIT** [comment]
switch to estuary Kodi skin and reboot
so try again

**Comment by Coolzero82** [comment]
I switch to estuary Kodi skin and reboot, but the problem is still the same.
Attached a new debug log with the estuary skin 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4073686/kodi.log)

**Comment by CastagnaIT** [comment]
This time the addon work good there is only one instance
i see some network error from different addons,
this can means you have connected to internet after turn on the device, or you have unstable connection or wrong network configuration

Other than that i don't see any other specific errors
you can try also update to latest libreelec 9.2
then if after update LE do not work again, try delete nf addon with all user data and reinstall it

seeing no other errors, i have no other solution to propose to you

**Comment by Coolzero82** [comment]
The problem is fixed, the soluten was the attribut "IPC Over http" to enable, i don't what this make, but now everythink works.
Thanks for your help

**Comment by CastagnaIT** [comment]
Yeah, I know you can use that,
but seem you have a problem with the "addon.signals" addon component or is there something that's preventing it from working properly

**Comment by moraisaugusto** [comment]
I changed the attribute "`IPC over HTTP`" to `enable` and created a connection bypass to not use VPN. Worked like a charm. 

thanks @Coolzero82
