### ISSUE TITLE
Playback doesn't work (black screen)

### ISSUE THREAD

**Issue by Witos** [CastagnaIT/plugin.video.netflix#433]
#### Your Environment
- Netflix add-on version: 0.16.2
- Operating system version/name: LibreELEC 9.2
- Device model:  Raspberry PI3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Video doesn't play after launching any item - black screen, sometimes audio plays. It used to work, stopped out of sudden.

#### Steps to reproduce the behavior
 Launch any video

### Debug log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4061250/kodi.log)
Looking at the log I suspect DRM problems... tried reinstalling widevine - didn't work.
#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information
Widevine updated recently in InputStream Adaptive.
Kodi version: 18.5
InputStream Adaptive - 2.4.2.1
InputStream Helper - 0.4.3
Widevine version: 4.10.1610.6

**Comment by CastagnaIT** [comment]
There is a lot of these errors:

`ERROR: OMXVideo::Decode timeout`
`INFO: Output - renderer not configured`

I do not know the meaning,
seem a GPU problem,
this should be presented at LibreELEC forum not here

**Comment by Witos** [comment]
Indeed, switching OMXVideo to SW decoding in LibreELEC menu helped, thanks.
