### ISSUE TITLE
New menu with audio/subtitle based research

### ISSUE THREAD

**Issue by otava5** [CastagnaIT/plugin.video.netflix#434]
Could you add this offer by audio language?
 https://www.netflix.com/browse/audio

**Comment by CastagnaIT** [comment]
yes i think it is possible, but this require some study and enough work

so also need to create a custom xml research window that get the list of parameters needed,
an then elaborate the requests with the user selected parameters.

I can't do that right now i have other work in progress at the moment

**Comment by otava5** [comment]
Will you not deal with this development?
On the contrary, the **audio description** is unnecessary ...

**Comment by CastagnaIT** [comment]
Developing what you ask requires many hours of work, for me this and other tasks are extra jobs that i take in my spare time.

The solutions are:
- For free - ETA requests are not accepted
It will be taken into account, based on my free time and on what is considered the most priority in the development. This may mean that it could be developed in a few days or even several months

- For free - by other devs
Other developers can take on the task for free, by informing me before starting work, then once proposed the PR will be evaluated and implemented

- Priority on payment - immediate development
After the payment, the task will be started immediately always in my free time, for details contact me only by e-mail

this to inform other people too

**Comment by otava5** [comment]
I sent you an email with no response ....

**Comment by jakermx** [comment]
What I do...is browse on chrome...look for titles and add to My List what I would like to watch...then... refresh my List on Kodi addon...and thats it

Remember that this addon issupported for free, and as there is a lot of feautures needed.... special request requires motivation or patience... @CastagnaIT  and his team are doing a real good job...and dont forget @asciidisco who started this project

**Comment by otava5** [comment]
@jakermx : Yes, that's how I solved it too

**Comment by CastagnaIT** [comment]
I have implemented the new Search menu,
when you do a new search you can try select the type of search

please try update and let me know
[plugin.video.netflix_1.6.0_20200630_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4853086/plugin.video.netflix_1.6.0_20200630_t1.zip)

**Comment by otava5** [comment]
I chose according to audio czech - functional. But sorting is according to "Suggestions for you", can you add a submenu with sorting according to "Year released"?thnx

**Comment by CastagnaIT** [comment]
change order from the settings under "main menu items" (not works for search by term)
i noticed a bug when you change order you need to "clear cache" to see the changes
i will fix

**Comment by otava5** [comment]
Are the search results stored somewhere, or is there always a new result? I would like to save the link "search-audio-czech" to a widget ... Thanks

**Comment by CastagnaIT** [comment]
like all lists the results are always queried to netflix server, and cached in memory for some time then nothing is saved,
you can try add the path of search item to widged

**Comment by otava5** [comment]
Could this be added to the "main menu" rather than the "search"?

**Comment by CastagnaIT** [comment]
after about 8 hours to implement everything i not waste more time on this
