### ISSUE TITLE
Next Page link in My List not at the end of list

### ISSUE THREAD

**Issue by CharlieDestroyerOfTacos** [CastagnaIT/plugin.video.netflix#439]
When browsing "My List" of movies and shows, the "Next Page >>" link appears in the middle of the list instead of at the very end of the list. This appears to be because it is sorted alphabetically causing it to appear in the middle near the titles beginning with the letter "N". The "Next Page" link should always appear at the end of the list, regardless of what titles have been added to "My List", otherwise, the user is forced to scan back up through the list to find the link for the next page of titles.

**Comment by CastagnaIT** [comment]
i know,
but this is a limitation between Kodi and also Netflix

- Kodi does not support natively the paginated lists, the method used is a kind of hack
- Netflix does not provide the "my list" list data in alphabetical order

but you can disable the Kodi alphabetical order, in this way:
-Open addon settings
-Go to: Main menu items
-In the "My list", go to "Sort results by" and select "Disabled" 

this way you'll have the list in the native order of Netflix,
the next button at the end of the list,
_but_ you won't be able to get the list sorted alphabetically
