### ISSUE TITLE
WARNING: ActiveAE - large audio sync error

### ISSUE THREAD

**Issue by Vitocorl** [CastagnaIT/plugin.video.netflix#44]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

## General information
 Xiaomi Mibox S, Android TV 8.1

### Addon version used
plugin.video.netflix_0.14.0beta23_20190331

### Description

[Description of the bug or feature]
Audio gets out of sync and video starts stuttering

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

## Debug log
https://hastebin.com/linudedize.php

The problem occurs at the same videos and at the same time of the video each time, for example, at Luce Cage TV Show, episode "Manifest" after 30 seconds  of play. If i scroll backwards or forward the video then it resumes playing normally. I suspect it is some kind of buffering problem, but it only occurs on the Kodi Netflix plugin and not in the Android app. I am not sure if it is a Netflix plugin error or an inputstream adaptive error

**Comment by jakermx** [comment]
have you tried to clean cache?, maybe it was stored that way

**Comment by Vitocorl** [comment]
Yes, i did clean cache of Netflix plugin, but afterwards the same happens

**Comment by jakermx** [comment]
Looks that you have a memory/proc issue, have you seen the % of cpu used?
I  would  disable Emby , enable audio sync to display, reduce video resolution then check
after that I would increase resolution until the error appears again, if not happens I would disable audio sync and finally enabled downmix, because you are selecting 6 channels output on a 2 channel pipe...

hope it helps

**Comment by Vitocorl** [comment]
Thanks for the advice, however this problem started a few days ago, my setup has not changed at all and the problem does not happen at all videos, it occurs at the same videos, same play time!

**Comment by Vitocorl** [comment]
I have posted this at peak3d/inputstream.adaptive, as after searching i have seen that peak3d has already provided fixes for similar errors in Kodi & inputstream adaptive plugin.
Thus, i am closing this issue here and continuing at https://github.com/peak3d/inputstream.adaptive/issues/249 for anyone who wants to follow...
