### ISSUE TITLE
Closed Captions messed up

### ISSUE THREAD

**Issue by jacoghi** [CastagnaIT/plugin.video.netflix#441]
Subtitles are messed up when closed captions are chosen.
First line always shows centered below the second line, which shows on the top and offset. See Friends for instance.

**Comment by CastagnaIT** [comment]
This is a known Kodi bug, Netflix addon doesn't handle these things

You can post your report complete with instructions on how to reproduce it to Kodi forum in the right section

**Comment by tyrion** [comment]
Hello, I have this exact same issue but I am having problems finding it on Kodi's issue tracker. Does anyone have a link?

@jacoghi did you manage to solve this issue?

Thanks :)

**Comment by jacoghi** [comment]
@tyrion, Nah, not yet man. I learned to live with it, lol.
