### ISSUE TITLE
After running kodi, Netflix needs to be logged in again.

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#45]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

0.14.0~beta23.20190331
### Description

Every time I run kodi, or when the widget (a shortcut to my list) refreshes, I need to log in again. the problem appeared in the last or the last but one version of the daily. 
The widget starts up before the information about logging in to netflix appears

**Expected behavior:** [What you expected to happen]
Logged in
**Actual behavior:** [What actually happened]
still required login
### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [x] I'm using a different source (Please tell which)

0.14.0~beta23.20190331
### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Coreelec 9.0.1

##  log
Log after restart Kodi
http://ix.io/1Feg
```
2019-04-03 15:54:56.498 T:3842044784   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 120, in make_return_call
                                                result = call(instance, func, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 140, in call
                                                return func(instance, **data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 57, in ensure_login
                                                raise NotLoggedInError
                                            NotLoggedInError
```

I think it may be related to these changes
https://github.com/CastagnaIT/plugin.video.netflix/commit/9eed811744dbf9c200e91f0911bc4d6fdfaf40e8

**Comment by CastagnaIT** [comment]
the mentioned commit does not affect any functionality, it only updates the settings when you close the settings screen

in your log lacks debugging information... activate kodi debug and reboot

**Comment by jakermx** [comment]
I think it is because the widget is starting before background service, so Netflix is not ready to refresh.

**Comment by notoco** [comment]
It will be difficult to capture because it does not happen regularly. For now, I changed the widget settings (I removed the refresh every 10 minutes) and somehow works. Yes, after the startup does not load the widget immediately, but overloading the skin, as Netflix will start, helps.

**Comment by jakermx** [comment]
Well, Maybe it is not the widget, It could be because some other things, since we dont have your complete log file, we can just think on different causes... it could be some exports, library things, remaining items on playlist, etc.. If you would like to improve the AddOn, please help us, sharing your complete log so we can reproduce the issue.

Thanks!

**Comment by notoco** [comment]
Of course I will put the log in debug mode. I left Kodi on today and see if it's possible to repeat the error. At the moment I have manually adjusted the widgets and the problem does not appear.

**Comment by notoco** [comment]
I found a almost identical problem in version 13 of the extension. The solution for me is the delay in the creation of widgets by the skin
https://github.com/asciidisco/plugin.video.netflix/issues/627
so ... it's not a plug-in problem, but the skin itself, actually the widget creation system.
I will leave this thread open as if someone came up with a solution before me.

**Comment by notoco** [comment]
Ok - i've found!
With netflix everything is ok - on a similar machine, but with fewer widgets and services, including without iptv, the problem does not occur - the netflix service starts before the widget is created. On the machine on which the error appeared, first iptv simple cilient starts, then widgets and in the background only netflix - if it starts before the widgets, then there are no errors or problems with logging. The solution is either delaying the start of widgets or delaying the start of the iptv client.
@jakermx - thx for the tip


 
--

**Comment by jakermx** [comment]
No problem man!..

I think you should look at this...

https://github.com/kodi-community-addons/script.skin.helper.service

**Comment by notoco** [comment]
After many hours of testing various settings of both the netflix plugin, as well as manual changes in the skin / widget code / script.skin.helper.service, I managed to find a solution, completely illogical ...
Change the menu order in kodi - move to the first position / screen and change the format of the widget from landscape to poster. incredible. If something is stupid and it works, it's not stupid ...
