### ISSUE TITLE
Netflix says 'This title is not available to watch instantly.'

### ISSUE THREAD

**Issue by Renetrox** [CastagnaIT/plugin.video.netflix#450]
#### Your Environment
- Netflix add-on version: 0.16.3>
- Operating system version/name: raspbian stretch
- Device model:  Raspberry pi   3b

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ x] Raspberry-Pi
* [ ] Windows

### Describe your help request

"Netflix says 'This title is not available to watch instantly."
Every time I want to see a content I get this message. On the flaw, Netflix gives the following guidance: https://help.netflix.com/en/node/109329. What can I do to fix this in the addon? 
Nothing specific is performed for the failure to occur, directly the message appears when you try to play a video.
log file: https://tgho.st/TYV8w
#### Screenshots
https://tgho.st/h6J08

**Comment by TheBigRigZA** [comment]
Hi there,

Also experiencing this on Kodi 18, android TV 8, using 0.16.3 version of plugin. 

Thanks

**Comment by CastagnaIT** [comment]
Now is good, but unfortunately in your log i don't have the information i need

First steps:
- Update your Kodi to Kodi 18.5 (you use the old 18.2)
- Update nf addon to latest version 0.16.3 (you use the old 0.16.1)
- Now reboot

Only after do this:
- Open nf addon (so don't play things from library o widgets)
- Open a tvshow or movie from one list
- Get a new log

**Comment by Renetrox** [comment]
new log: https://tgho.st/Q2SeS

**Comment by CastagnaIT** [comment]
now the log is good, the profile data is ok
are you using vpn or proxies? if yes disable it

> What can I do to fix this in the addon?

This is easy, open addon settings, then select on `Logout`

After Logout, do this:
Open again the addon settings (by context menu on the addon icon), goto `Expert` page and choose `InputStream Helper settings`
a new window is opened, then choose `(Re)install Widevine CDM`

**Comment by Renetrox** [comment]
many thanks! you're very kind! sorry about the mess of the report, I deleted the guide text and didn't know how to describe it the right way. Indeed, that solves the problem! 👍

**Comment by CastagnaIT** [comment]
so did the Logout resolve the problem?

**Comment by Renetrox** [comment]
Effectively log out and reinstall widevine

**Comment by CastagnaIT** [comment]
so good
