### ISSUE TITLE
error installing Widevine CDM - stops on 5% on extracting screen

### ISSUE THREAD

**Issue by lpt2007** [CastagnaIT/plugin.video.netflix#454]
#### Your Environment
- Netflix add-on version: 0.16.3
- Operating system version/name: raspbian from docker container
- Device model:  raspberry pi 2

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
error when try to auto install Widevine CDM
[kodi-log.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/4112113/kodi-log.txt)

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
this problem not depend from this addon
you have to open an issue here:
https://github.com/emilsvennesson/script.module.inputstreamhelper
