### ISSUE TITLE
Netflix Request Failed During Key Exchange

### ISSUE THREAD

**Issue by spacex97** [CastagnaIT/plugin.video.netflix#455]
#### Your Environment
- Netflix add-on version:  16.3
- Operating system version/name:  Android 10
- Device model:   OnePlus 6T

Used Operating system:
* [ x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Netflix Request Failed During Key Exchange

#### Expected behavior

With correct esn key exchange request should complete

#### Actual behavior

Key exchange request failed

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
https://www.dropbox.com/s/3sld629gjq7fe1d/kodi.log?dl=0

**Comment by CastagnaIT** [comment]
issue already opened
