### ISSUE TITLE
Multiple subtitles simultaneously

### ISSUE THREAD

**Issue by hcordobes** [CastagnaIT/plugin.video.netflix#461]
## Feature request
I'm submitting a proposal to ...
  - [X] new feature
  - [ ] change an existing feature

### Describe your request

I am considering the recently published Chrome plugin "Language Learning with Netflix" (http://languagelearningwithnetflix.com) and I presume implementing something similar on this plugin should be feasible.

This plugin allows the user to present on the screen subtitles in different languages so it be of help to foreign language learners. The chrome plugin is kind of feature intensive, but a useful functionality would need to go that far.

#### Describe the use case

User wants to see at the same time subtitles in more than language.

Thus, the interface should allow to select more than one subtitle.
Other option could be having the user make a selection of the local language within the plugin conf and the subtitles are shown in this language and the media's original one.

**Comment by CastagnaIT** [comment]
Kodi do not support multiple subtitle at the same time,
if you want to request support, you have to do it in Kodi forum

**Comment by hcordobes** [comment]
That's true. 

Would it be possible to combine both subtitles dinamically within the plugin and provide one unified stream to Kodi?

Very workaround-ish, but maybe feasible. 

I will take a look at Kodi forum as well, in any case. :)
