### ISSUE TITLE
Video fails to play on Shield TV / Android Pie

### ISSUE THREAD

**Issue by lhassell** [CastagnaIT/plugin.video.netflix#464]
Playing video fails and stream plays audio only. Other streaming apps (SlingTV, Amazon VOD) working.

Log attached.

https://paste.kodi.tv/axodosezot.kodi

**Comment by CastagnaIT** [comment]
seem that try to play a strange stream,
I need to check two files then:
- before open again the same video of the log
- After use a file browser like Solid Explorer to find this two files in this path:

[INTERNAL SD]/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.netflix/manifest.json
[INTERNAL SD]/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.netflix/manifest.mpd

* if some folders are missing goto the file browser options and click on Show hidden files

copy here this two files

**Comment by lhassell** [comment]
[manifest.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4132078/manifest.zip)

**Comment by CastagnaIT** [comment]
are you use 4k?

**Comment by lhassell** [comment]
No. My TV is only 1080.

**Comment by CastagnaIT** [comment]
Then, check this settings:

On InputStream Adaptive settings:
Ignore Display Resolution to OFF
Override HDCP status to ON
Stream selection to Auto

On Netflix addon Expert settings:
Limit video stream resolution to ---> **shoud be value** "--"
Force HDCP 2.2 to OFF

After this, if you haven't already update addon to latest version 0.16.4
let me kwow

**Comment by acixx** [comment]
First let me thank you for your excellent work on that addon!

I am experiencing a similar problem, kodi thinks it's playing something but actually I see only a blank screen; or I see artefacts (looks similar to encrypted analogue tv in the nineties) and hear stuttering audio. I am running the latest version and tried the settings you suggested (with 720p resolution). Before doing so, I have reset Netflix addons' and inputstreams settings to default and also made sure that widevine is the latest version. I also only have a 1080p-tv but I also have the cheap account only allowing 720p. 

I'll attach a log where I tried to watch "28 Days Later" at 12:04 for 15 seconds (blank screen, no audio) and "28 Weeks Later" for about 15 seconds (resulting in "encrypted" artefacts, stuttering but recognizable audio). 

[log-output.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/4142464/log-output.txt)

I also tried version 0.16.4 and your current master-branch with no luck and the same results.

**Comment by CastagnaIT** [comment]
@acixx here the issue concern Nvidia shield then open a new issue,
with also a new debug log after rebooted device, that one provided missing some info

**Comment by shkope** [comment]
hello, I have the same problem on shield TV, no image but only sound

https://www.youtube.com/watch?v=A_RsdAcqoQI&t=5s

**Comment by CastagnaIT** [comment]
the video posted is totally useless doesn't even show the configuration used in the addon, nor on inputstream addon... no display info, no log provided...
how do you think i should understand your problem?...

**Comment by shkope** [comment]
[https://www.transfernow.net/files/?utm_source=83gfz9u3v004&utm_medium=&utm_content=fr](url)

**Comment by shkope** [comment]
https://www.transfernow.net/files/?utm_source=83gfz9u3v004&utm_medium=&utm_content=fr

**Comment by CastagnaIT** [comment]
bad log, instruction here: https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

**Comment by shkope** [comment]
http://www.mediafire.com/file/eo52833gl22483e/kodi.log/file

**Comment by CastagnaIT** [comment]
good, 
now go to Netflix addon Expert settings:
turn OFF - VP9 profile
turn ON - HEVC profile
should be working

**Comment by shkope** [comment]
it does not work, I tried all possible combinations nothing helps

**Comment by CastagnaIT** [comment]
The only right combination is the one i wrote,
Check also this settings:

On InputStream Adaptive settings:
Ignore Display Resolution to OFF
Override HDCP status to ON
Stream selection to Auto

On Netflix addon Expert settings:
Force HDCP 2.2 to OFF

**Comment by shkope** [comment]
it still does not work

**Comment by shkope** [comment]
I don't have to install widevine CDM for it to work?

**Comment by shkope** [comment]
well, i uninstall and reinstall kodi, install add on netflix and it works!

**Comment by shkope** [comment]
I found where the bug came from, you must activate MediaCodec (surface) in the kodi options otherwise the video will not start ...
if it helps those with the same bug.

**Comment by CastagnaIT** [comment]
Thank you for finding the problem
I will update the FAQ

**Comment by CastagnaIT** [comment]
Closed due to inactivity of issue author
