### ISSUE TITLE
Configuration option for Audio-systems (2.0 - 5.1)

### ISSUE THREAD

**Issue by Dschogo** [CastagnaIT/plugin.video.netflix#465]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature (new configuration option)

### Describe your request
 - Add an option (in the configuration) to select the audio system. (2.0 [2 Channel audio] and 5.1 [6 channel audio]). Based on that configuration the selection of audiostreams should be filtered (only show the selected type [with fallback if 5.1 for example isn't available]). 
 - Instead of an extrea configuration in the plugin it could just read the kodi audio settings.

#### Describe the use case
 - To filter the audiostreams. (Because for me is automatically selects an 5.1 stream on a 2.0 system)

Hope you understood what i meant, if not write back...

**Comment by CastagnaIT** [comment]
this would only make sense if netflix provides high quality DD2.0 audio, but it's not.

netflix provide all 2.0 audio format types (DD, AAC) at same bitrate quality

most of the time 96 and 128kbps, even when comparing the file sizes there is a really very small difference, so i really doubt you can hear the audio difference

Then to get only 2.0 streams you can simply disable DolbyDigital from addon expert settings

**Comment by Dschogo** [comment]
All right.

Disabling DolbyDigital in expert settings done exactly what i wanted.

Thx
