### ISSUE TITLE
Playback fails Kodi 18.1 (Widevine CryptoSession getkeyrequest failed)

### ISSUE THREAD

**Issue by DanteN1991** [CastagnaIT/plugin.video.netflix#467]
[kodi_netflixlog_31_01_2020.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4136856/kodi_netflixlog_31_01_2020.log)
## Bug report

When I try to play any video it gives me Playback error saying "Widevine CryptoSession getKeyRequest failed".

#### Your Environment
- Netflix add-on version: 0.16.3
- Operating system version/name:  Android 10.0.0 API level 29, kernel: Linux ARM 32-bit version 4.9.170
- Device model:  TV Android Box T95
All the information of the system is in the log file.

Thanks in advance!!

**Comment by CastagnaIT** [comment]
Install the latest addon version 0.16.4
then go to addon `Expert settings` and select `Reset ESN`

**Comment by DanteN1991** [comment]
Thanks for the response. I did as suggested, and I still get the same error.
Please find the new debug log attached.
Thanks.
[kodi_new_log_31012020.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4139572/kodi_new_log_31012020.log)

**Comment by CastagnaIT** [comment]
you have to enable debug as explained in the readme otherwise is not much useful

**Comment by DanteN1991** [comment]
Sorry for that. Enabled. And here is the new log if needed.
[kodi_new_log.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4139631/kodi_new_log.log)

**Comment by CastagnaIT** [comment]
this is same as before...
https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

**Comment by DanteN1991** [comment]
Oh..the log continued in the same file. Okay, I deleted the first. 
[kodi_new_log.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4139671/kodi_new_log.log)

**Comment by CastagnaIT** [comment]
unfortunately nothing is changed
debug verbose is not enabled
after enabled it suggest you to reboot device

**Comment by DanteN1991** [comment]
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4139801/kodi.log)
As suggested. 
I also tried without the 4k even though my Tv Box supports 4k and the account is for 4k too.
Thanks for the help.

**Comment by CastagnaIT** [comment]
now it is good
but here in your log your device name is: Google Pixel 2
you have specified : TV Android Box T95

this is strange...

**Comment by CastagnaIT** [comment]
You're also using a very old version of Kodi
this is the first thing to do update Kodi to latest version

**Comment by DanteN1991** [comment]
The Kodi version is 18.1 ( that's what it says in the app) .
The TV Box is the following [``](https://www.aliexpress.com/item/4000589778002.html?spm=a2g0o.productlist.0.0.5d5a447amqAyDM&algo_pvid=148c1ca7-dc0f-457a-9407-259ec12c73ee&algo_expid=148c1ca7-dc0f-457a-9407-259ec12c73ee-16&btsid=fe4a3b59-4b34-4eb1-8546-17416f5b2e26&ws_ab_test=searchweb0_0,searchweb201602_2,searchweb201603_53)

**Comment by CastagnaIT** [comment]
you chinese product seem to use a bad hacked android firmware
that's why it doesn't work

to figure out what you can do, you have to give me more information:
1) send me the screenshot of the ESN showing in the official Netflix app in the settings
2) Install DRM Info app, send me a screenshot of every pages of this app

Send all to my e-mail: gottardo.stefano.83@gmail.com
certain information is best not to divulge here

**Comment by DanteN1991** [comment]
Awesome! I figured....should have gone for the Xiamoi Mi S box.... thanks again! will send you asap

**Comment by DanteN1991** [comment]
sent.

**Comment by CastagnaIT** [comment]
this device is not compatible with Netflix 4K, for the reason that it has not been certified with Widevine L1, probably due to the strange firmware

another thing, the addon has not been able to get widevine information and this could be a problem
unfortunately this depends on another Kodi component and to now i can't say why it can't get them

you can try entering this ESN in to addon Expert settings, Manual ESN:
`NFANDROID1-PRV-T-L3-GOOGLPIXEL=2-8158-`

if it does not return error, **please restart the device first**
and provide me a new log after you try to start a video

**Comment by CastagnaIT** [comment]
the problem of widevine can be becouse you are using the old version of Kodi
you have to update Kodi with latest 18.5 version available on Playstore

**Comment by CastagnaIT** [comment]
Please update Kodi before insert the ESN manually

**Comment by DanteN1991** [comment]
[kodi_18_5_working.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4140766/kodi_18_5_working.log)
It is working!! I installed 18.5 , was afraid isn't going to run, but it ran.
Now it is working. 
Thank you a lot!!

**Comment by CastagnaIT** [comment]
you have insert the ESN manually or not?

**Comment by DanteN1991** [comment]
The ESN manually , the one you gave me.

There is one issue though,
I can’t get Full HD to stream. The max it gives is 960*570 or something  and are blurry ... worse than than the android app.

**Comment by CastagnaIT** [comment]
can you give me a last log after you have rebooted?
because there's a lack of information on the last one

yes non L1 devices has limited resolutions

**Comment by CastagnaIT** [comment]
it would be important for me if you provide me with this log after reboot device, so that i can solve a possible problem discovered with your issue request
thanks

**Comment by DanteN1991** [comment]
[kodi_netflix_log_31_01_2020.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4140977/kodi_netflix_log_31_01_2020.log)
Set up the debug ON in Kodi and Netflix.
Rebooted.
Opened Kodi, opened Netflix and played a movie.

This is the log from those actions.

**Comment by CastagnaIT** [comment]
Thanks
