### ISSUE TITLE
Easier way of installing Netflix

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#468]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
Find easier means of installing the Netflix repository now that it is clear it won't be part of the official Kodi repo.

#### Describe the use case
I think it could be useful to make it easier for users to install the Netflix repository. Depending on the device/platform certain skills are needed (e.g. the ability to transfer a file to the device). Currently there are a few installation procedures:
- Downloading to the device itself
  - If the device is a laptop/tablet, one can simply download from a browser
  - If the device is another box, you need to know how to log on to that device and the command to download
- Transferring to a device
  - For some devices a USB storage device could be useful
  - For some device only SCP/SFTP (SSH) is possible
  - Other devices have a Samba share to copy it to
  - In some cases bluetooth is an option
- Finding the repository ZIP file
  - When the file has been transferred or downloaded you also need to able to find that location

I think we can reduce this complexity for end-users by offering a (simple-to-type) location that can be added as a source. Ideally a source that is not just used for Netflix, but could be reused by other trusted 3rd party add-ons. (e.g. kodi.sw.be)

Adding a source seems like a rather big/permanent step for an action that only has to occur once (installing the repository) but it is by far the easiest, is performed within Kodi and works for every situation ! And it also offers other possibilities (e.g. include test packages for other branches).

If we could set up a community of add-on developers, this single source could be reused for multiple projects (related to e.g. VOD add-ons) for installing but also testing releases. So this big/permanent action could be useful for a much wider audience.

#### Describe an alternative
Another option for Netflix is LibreELEC (which is likely the most used Kodi distro for RPi). I reinstalled LibreELEC recently, and it ships the Kodinerds repository as part of the base installation. The @kodinerds repository includes [a Netflix repository](https://github.com/kodinerds/repo/tree/master/repository.netflix) that no longer works (points to @asciidisco), it could be worthwhile to update their references or include the Netflix repository in the Kodinerds repository.

**Comment by CastagnaIT** [comment]
I will think about this later at this moment i have other things

**Comment by dagwieers** [comment]
Sure, and it would be useful to have a wider discussion around this IMO.

**Comment by CastagnaIT** [comment]
I was doing some thinking about KodiAddons org.

I was theorizing about moving the entire project within the organization
but there are things I'd like to understand first,

currently (It seems to me, but I didn't get a good look) the category (team) "developers" have access to all the repositories

is it possible to make a more refined selection? theory example:

i move my repo in the org then:
-_only_ the organization managers and the developer in charge of the project, can have full access to modify all parts of the repository
-The developer in charge, can also have the power to add new member to the project, and set permissions e.g. full access to the repository or only "Issues" management or only wiki manteiner

is that a workable thing?
So you would have a future-oriented management

So that if the main manteiner of the project, leaves the project, there may already be another developer, and the project is not lost on a private repository

**Comment by dagwieers** [comment]
@CastagnaIT We do not expect collaborating add-ons to move their repository. But one important reason for us to have this organisation is to have a fixed location for add-ons, so add-ons are not seen as a personal project, but a community effort. (We have some examples where the original developer is no longer actively involved)

We opted to work with Members for people that are collaborating, we could also have opted to work with outside collaborators (e.g. for translators) but we do not think that makes a real difference and prefer an inclusive environment. A member (like Developers or Translators) only have read-access to collaborating repositories.

There is one exception currently, the **translators** repository is "owned" by team "Translators" which means all translators have access to it (this is because we want to open the Wiki to all Translators for collaborating).

The organization is currently configured to *only* give repository admins full access to their repositories. (Only exception is organization owners). So I think that is what you expect.

We still need to think about policies, governance and possible other features, like our own repository, but our priority is to upstream our add-ons as much as possible, so this adds little value (except maybe for Netflix). A *testing* repository could be very useful for all kinds of testing though.

**Comment by CastagnaIT** [comment]
>  I reinstalled LibreELEC recently, and it ships the Kodinerds repository as part of the base installation

today i have reinstalled libreelec (kodi 19) and updated libreelec (kodi 18) to my virtualbox machines but i do not have Kodinerds repository included, where is hidden?🙄😅

**Comment by dagwieers** [comment]
@CastagnaIT I cannot find it anymore. This system was a clean installed LibreELEC. And I think it either shipped as an Add-on repository in either **LibreELEC Add-ons** or the **Zach Morris Add-ons**.

But it still is listed as a broken repository from the **Kodinerds Add-ons** repository. So I would contact them to get it updated: https://github.com/kodinerds/repo/tree/master/repository.netflix

**Comment by CastagnaIT** [comment]
> I cannot find it anymore. This system was a clean installed LibreELEC. And I think it either shipped as an Add-on repository in either LibreELEC Add-ons or the Zach Morris Add-ons.

I just asked to LibreElec developers
they replied that Kodinerds is not included by default is needed manual installation
it could be included on unofficial LibreElec builds

I can request to update the repository link it is not problem
but first i have to do the matrix branch

**Comment by dagwieers** [comment]
It was not an unofficial build, it definitely was there, but not directly included, but indirectly through another repository. And you needed to enable it explicitly. I never transferred it myself, or added anything myself. This was a demo-setup for a presentation so it was vanilla when I discovered and enabled it. It might have been removed in the meantime.

I cannot find where it was coming from, but the timestamps on the files prove they have been installed very early when used. Only a few minutes after the installation.
```
LibreELEC:~ # ls -ld .kodi/addons/repository.*
drwxr-xr-x    2 root     root          1024 Feb  1 15:38 .kodi/addons/repository.castagnait
drwxr-xr-x    3 root     root          1024 Jan 31 15:58 .kodi/addons/repository.kodinerds
drwxr-xr-x    2 root     root          1024 Jan 31 16:01 .kodi/addons/repository.kodinerds_RPi2
drwxr-xr-x    2 root     root          1024 Jan 31 16:00 .kodi/addons/repository.netflix
drwxr-xr-x    2 root     root          1024 Feb 11 14:18 .kodi/addons/repository.vtm.go
drwxr-xr-x    3 root     root          1024 Jan 31 15:58 .kodi/addons/repository.zachmorris
```

**Comment by dagwieers** [comment]
Almost certainly through **Zach Morris Add-ons**:
```
LibreELEC:~/.kodi/addons/packages # stat repository.kodinerds-9.0.103.103.zip repository.zachmorris-1.0.
0.zip
  File: 'repository.kodinerds-9.0.103.103.zip'
  Size: 82148     	Blocks: 162        IO Block: 1024   regular file
Device: b302h/45826d	Inode: 1573786     Links: 1    
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-01-31 15:58:12.000000000
Modify: 2020-01-31 15:58:13.000000000
Change: 2020-01-31 15:58:13.000000000
  File: 'repository.zachmorris-1.0.0.zip'
  Size: 393683    	Blocks: 770        IO Block: 1024   regular file
Device: b302h/45826d	Inode: 1573783     Links: 1    
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-01-31 15:58:08.000000000
Modify: 2020-01-31 15:58:08.000000000
Change: 2020-01-31 15:58:08.000000000
```

**Comment by CastagnaIT** [comment]
i also have tried install Zach Morris repo but nothing... if there was anything they removed it

**Comment by dagwieers** [comment]
That is what I said. It is definitely no longer there. In any case, fixing it in (or removing it from) Kodinerds is probably useful.

**Comment by drinfernoo** [comment]
The file source for `repository.castagnait` is https://castagnait.github.io/repository.castagnait/.
