### ISSUE TITLE
Enable Up Next by default

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#469]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
I would enable Up Next support by default. If people have it installed it makes more sense it works out of the box, rather than having another switch to enable it.

This also means that everyone who installed the Netflix versions with it disabled by default, still have to enable it after this is enabled by default.

**Comment by CastagnaIT** [comment]
the setting to enable/disable does not remove it because i also need it for debugging
but it seems to me that you can make the default value dynamic based on whether an addon is installed or not, i will give a try

**Comment by dagwieers** [comment]
Well, there is a difference between having it installed and enabling or disabling it.
Obviously if it is not installed, the entry (and settings entry) should be grayed-out (I didn't test this).
But if it is installed, the default IMHO ought to be enabled.

**Comment by CastagnaIT** [comment]
use a dynamic "default" value in the settings xml does not work,
then i added it in the startup addon auto-configuration
https://github.com/CastagnaIT/plugin.video.netflix/pull/466

**Comment by CastagnaIT** [comment]
I changed the setting in this way, it makes me easier to handle via xml without subsettings
![image](https://user-images.githubusercontent.com/3257156/73643861-90571c00-4674-11ea-9a67-74edf8e905b0.png)

**Comment by Xamyrz** [comment]
I have installed the Up Next addon, but unfortunately the "Enable Up Next integration" is grayed out and I can't enable it. What may be the fault of that?

**Comment by nasicion** [comment]
> I have installed the Up Next addon, but unfortunately the "Enable Up Next integration" is grayed out and I can't enable it. What may be the fault of that?

Same here, just installed both plugins but cannot enable the integration
