### ISSUE TITLE
Keep track of search queries

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#470]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
It would be nice if there was a history of search queries where you can edit previous search queries, remove them or empty the search history.

#### Describe the use case
Often when you look for something you want to edit a previous search, rather than start over. Also previous search queries tend to be needed later to refind the same thing (e.g. check if a new season is available). The Netflix add-on is not as convenient for finding something specific, which makes searching quite important in this add-on.

**Comment by CastagnaIT** [comment]
yes i could memorize the last searched text

**Comment by dagwieers** [comment]
Not just the last searched text, but all previous texts.
We do this in the VRT NU add-on, you can test the interface to see if you like it.

**Comment by CastagnaIT** [comment]
you have made a custom search interface?
can you give a screenshot?

**Comment by dagwieers** [comment]
Here is what you can see starting from the main menu.
![screenshot000](https://user-images.githubusercontent.com/388198/73594839-5241e700-4512-11ea-8920-8150c80421e2.png)

If you press **Search** you enter the search history.
![screenshot001](https://user-images.githubusercontent.com/388198/73594843-5ec63f80-4512-11ea-94f5-7245b4d3c5a5.png)

When you search for a new search string, you get:
![screenshot003](https://user-images.githubusercontent.com/388198/73594851-79001d80-4512-11ea-83c2-afac40e9b657.png)

When you search (new, or existing query) you get the overview of results:
![screenshot002](https://user-images.githubusercontent.com/388198/73594866-91703800-4512-11ea-854d-28021f778711.png)

Obviously, the results could change over time and we sort them based on when the content became available, so the recent stuff is on top.

If you go back, you return to the search history.

**Comment by CastagnaIT** [comment]
it is nice
there is some work to be done to implement it but it can be done

**Comment by dagwieers** [comment]
What you don't see is that the list is ordered but unique (using a python Set).  So the latest additions are always on top, even when the item was already in the list. And if you re-search an existing query (e.g. at the end of the list) it re-appears at the top.

**Comment by CastagnaIT** [comment]
I understand, here i store in the database i will have to see how best to implement it
perhaps a dedicated table for search data is best thing

**Comment by CastagnaIT** [comment]
I have implemented the new Search menu,
when you do a new search you can select the type of search

before you say, i know there is no "Edit" context menu, i want avoid code complexities

if you want try, update and let me know if works good
[plugin.video.netflix_1.6.0_20200630_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4853099/plugin.video.netflix_1.6.0_20200630_t1.zip)

**Comment by dagwieers** [comment]
@CastagnaIT Did you know you do not have to actually make a ZIP file, you can point directly to your branch for getting a recent package: https://github.com/CastagnaIT/plugin.video.netflix/archive/new_search.zip

I tested this and it works very well. If you do not want to provide an edit context menu, that is fine. One option we implemented elsewhere is that selecting old search text gives you always an edit dialog with that search text, if you press enter without modification that will redo the original search, but if you modify it, you will get a new search in your search history. This IMO is the best of both worlds (for just an extra click for previous searches).

The reason to be able to modify an earlier search is that when you make a typo, or want to make a slightly different search, you don't have to enter everything again (using a remote control). So some way to edit a previous search is always going to be handy.

**Comment by CastagnaIT** [comment]
> Did you know you do not have to actually make a ZIP file, you can point directly to your branch for getting a recent package:
oh nice
what are stored the rules that use to build the zip?

> The reason to be able to modify an earlier search is that when you make a typo, or want to make a slightly different search, you don't have to enter everything again (using a remote control). So some way to edit a previous search is always going to be handy.

i agree it is boring without a bluetooth keyboard..

thanks for the report!

**Comment by dagwieers** [comment]
@CastagnaIT The ZIP file is an exact copy of the files in your branch, except the files from *.gitattributes* that have the `export-ignore` attribute.

**Comment by CastagnaIT** [comment]
> The ZIP file is an exact copy of the files in your branch, except the files from .gitattributes that have the export-ignore attribute. Anyone can click through from a PR to the branch and download a ZIP file to test.

interesting
in the end i have added also the edit option

**Comment by dagwieers** [comment]
I documented updating to the master branch ZIP or any branch for testing here:
- https://github.com/add-ons/plugin.video.vrt.nu/wiki/Updating#running-the-latest-development-branch-master-branch
- https://github.com/add-ons/plugin.video.vrt.nu/wiki/Testing#test-the-master-branch-or-any-other-branch

The documentation mostly hints that this is possible, but if you don't have experience with Git or GitHub you would probably need screenshots to understand what you need to do :disappointed:

**Comment by CastagnaIT** [comment]
users who commit todo manual updates are enthusiasts or for some issue that causing rolling balls :)
do not happen often that inexperienced people use complicated ways, especially when they don't even know what github means and his various terminology

**Comment by dagwieers** [comment]
Thanks!
