### ISSUE TITLE
Include Netflix into EPG as a kind of "Channel"

### ISSUE THREAD

**Issue by Mannshoch** [CastagnaIT/plugin.video.netflix#472]
## Feature request
I'm submitting a proposal to ...
  - [X] new feature
  - [ ] change an existing feature

### Describe your request
I detected that I like the EPG overview in Classic TV.  So may you could add some Netflix content as EPG channel.

#### Describe the use case
I'm a fan of the list of new releases. 
1. It would be nice If could open the contextmenue on the folder "New releases" 
1. Click on "Add to EPG". 
1. This would result in a new TV-Channel 
1. you can name it yourself and setup some settings like how long( e.g. 1 or 2 hours) an entry in EPG should be.
1. Open EPG and you could see your pseudo channel filled with the next releases.

**Comment by CastagnaIT** [comment]
besides the point that this addon doesn't run tv channels also there is no timetable, i don't see it adequate for this purpose

I'm not going to spend time implementing this,
if someone else wants to do it, present an example of the results with a PR and implementation will be evaluated

**Comment by Mannshoch** [comment]
The Idea is to actively misuse the Timetable. I do not propose to use Netflix as TV channel because I think it is. That's right, Netflix is not a TV channel.
I simply like the timetable appearance
