### ISSUE TITLE
Can't retrieve WideVine (UnicodeDecodeError)

### ISSUE THREAD

**Issue by Delan168** [CastagnaIT/plugin.video.netflix#473]
#### Your Environment
- Netflix add-on version: 16.4
- Operating system version/name: Raspbian
- Device model:  Raspberry Pi 4 B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
After a fresh install of Raspbian and Kodi (from repo), addition of your repo, Netflix add-on and log-in, I launched the first video. The add-on ask to get WideVine, downloads Chrome OS, uncompresses it, then fails to use it with error below.

#### Expected behavior
Get WideVine and launch videos afterwards :-)

#### Actual behavior
an error message appear with "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)", which recommends to get the log and report issue if no obvious solution is proposed in the error mesage.

#### Steps to reproduce the behavior
I guess do a fresh install with said hardware and OS.

#### Possible fix
No idea, sorry :-/

### Debug log
The debug log can be found from this link:
https://www.dropbox.com/s/g3baj7rysn3bsvu/kodi.log?dl=0

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
* [x] From your repo (zip file)

#### Other information
n/a

#### Screenshots
None, sorry.

**Comment by CastagnaIT** [comment]
this is not an error of this addon,
you have to open an issue here: https://github.com/emilsvennesson/script.module.inputstreamhelper
