### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by drmodem** [CastagnaIT/plugin.video.netflix#474]
#### Your Environment
- Netflix add-on version: 0.16.4
- Operating system version/name: Rasbian Buster + Xcfe desktop (linux-arm)
- Device model:  Raspberry Pi 4 4GB aarch64/aarch32 jKernel v7+ and Kernel v8+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
We are able to enter in the addon, see the list of users and access to categories.
When we start a video, the video will not start and give a error message: The error - This title is not available to watch instantly.

This issue does not happen if we use Raspbian Buster + desktop from Raspberry team. The condition happen only when installing Xcfe desktop on Raspbian lite. We tried under "pi" account and "root" account as well. 

Error log #1 can be found here: https://pastebin.com/hJndMEYm
Error log #2 can be found here: https://pastebin.com/wiuFcsBM

#### Expected behavior
The video should start without error message.

#### Actual behavior
When we start a video, the video will not start and give a error message: The error - This title is not available to watch instantly.

#### Steps to reproduce the behavior

1. Open Kodi, open Netflix addon
2. Select any video to play

#### Possible fix

What i have tried already:

- Uninstall and reinstall the addon
- Reset ESN code
- Uninstall Widevine and reinstall it. I suspect Widevine do not install correctly under Xcfe versus Raspian regular desktop.
- Tried the logout and log back in as suggested by Netflix site.

### Debug log
The debug log can be found from this link: https://pastebin.com/hJndMEYm
Debug + verbose log: https://pastebin.com/wiuFcsBM

#### Installation
* [x] I'm using Netflix Repo (CastagnaIT repo)
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
you've already done what i usually recommend
and the main profile seems to me correct, it does not seem to have set age limit

the widevine library is installed by this addon:
https://github.com/emilsvennesson/script.module.inputstreamhelper
but i don't know if you can find some answer

**Comment by drmodem** [comment]
> you've already done what i usually recommend
> and the main profile seems to me correct, it does not seem to have set age limit
> 
> the widevine library is installed by this addon:
> https://github.com/emilsvennesson/script.module.inputstreamhelper
> but i don't know if you can find some answer

I have found a way to fix it.  Though i am not sure if it was about the first thing or second thing i have tried.

Here is what i did:
1- Unstalling the add-on and deleting add-on profile. Install the version before the 0.16.4. Start the addon, it will make a error saying netflix profile not loaded, the add-on will crash. Update add-on to 0.16.4. The netflix user menu choice should work normally. And video will now play without errors.

2- Force download PySocks.py, it wasn't installed as it said optional for install.

Widevide was okay finally. For some reason when you install 0.16.4 directly the user list of netflix load corrupted. It

**Comment by CastagnaIT** [comment]
the result would have been the same even if you had installed the current version of the addon, because that part of the code hasn't been changed between the two versions, and the loading of the profiles list has no relation with widevine

but if some errors had happened before loading the list, that error could be produced

i am happy you solved it, unfortunately we don't know exactly what was wrong, it could have been useful to others

**Comment by drmodem** [comment]
Yes, i can reproduce it at any time with a fresh install. Rasbian Lite + Xfce. I really do not know why this type of setup would corrupt the profile list. Though it was showing the list correctly in the add-on but just not start video. Could a debug+verbose while doing a fresh install of the app help find out?

**Comment by CastagnaIT** [comment]
perhaps yes we can try, after install from scratch, you can enable app verbose logging before entering the credentials, by open app settings by context menu on app icon

**Comment by CastagnaIT** [comment]
Closed due to inactivity

**Comment by alexdawn** [comment]
> 
> 
> > you've already done what i usually recommend
> > and the main profile seems to me correct, it does not seem to have set age limit
> > the widevine library is installed by this addon:
> > https://github.com/emilsvennesson/script.module.inputstreamhelper
> > but i don't know if you can find some answer
> 
> I have found a way to fix it. Though i am not sure if it was about the first thing or second thing i have tried.
> 
> Here is what i did:
> 1- Unstalling the add-on and deleting add-on profile. Install the version before the 0.16.4. Start the addon, it will make a error saying netflix profile not loaded, the add-on will crash. Update add-on to 0.16.4. The netflix user menu choice should work normally. And video will now play without errors.
> 
> 2- Force download PySocks.py, it wasn't installed as it said optional for install.
> 
> Widevide was okay finally. For some reason when you install 0.16.4 directly the user list of netflix load corrupted. It

I've got a similar issue but I can't seem to reproduce step 1. The only version of the InputStream Helper library I can see is 0.5.4 and it doesn't seem to have any option to pick a version of widevide
