### ISSUE TITLE
Only 540 SD with Xiaomi Mi Box 3 (MDZ-16-AB)

### ISSUE THREAD

**Issue by DoctorBR** [CastagnaIT/plugin.video.netflix#475]
#### Your Environment
- Netflix add-on version: 0.16.4
- Operating system version/name: Android TV Oreo 8.0
- Device model:  Xiaomi Mi Box 3 (MDZ-16-AB)

### Describe the bug

Probably the ESN number of my Mi Box 3 is not being used, as the maximum resolution of the films and series is at 540 SD. 

My TV is 4K and my plan is 1080p, and with previous versions of the add-on I was able to watch 1080p with a bitrate of up to 7 Mbps without any problem.

P.s. With the Amazon VOD add-on I can watch 1080p.

### Debug log

The debug log can be found from this link: https://paste.ubuntu.com/p/tHN7yCH6PX/

**Comment by CastagnaIT** [comment]
you have entered a manual esn?

i need also you give me this infos:
-Install `Info DRM` app and send here a screen shot of the infos
-Open original Netflix android app go to settings and send here a screen shot of the ESN

**Comment by DoctorBR** [comment]
1) Yes, I added the ESN manually via the add-on, but, as I told you in the thread on the Kodi forum, the add-on does not accept it **(the ESN ends up incomplete)**. Even adding directly to org.xbmc.kodi / files / .kodi / userdata / addon_data / plugin.video.netflix / settings.xml **has no effect**;

2) Google Widevine Modular DRM is **SUPPORTED** and **Security Level is L1** ... as I mentioned, your add-on worked perfectly well (1080p) on my Mi Box 3 (MDZ-16-AB). The problems arose after the ESN error appeared, just over 30 days ago;

3) I believe that posting the ESN of my MDZ-16-AB publicly is not safe ... 

I believe the problem with **Xiaomi Mi Box 3** (MDZ-16-AB) is the lack of space to intrude all **111 characters of her ESN**. As a result, the code is incomplete and the Mi Box does not play any content above 540 SD.

**Comment by CastagnaIT** [comment]
if you don't give me this information, i can't help you in any way,
if you prefer you can send all the screenshots and data to my personal github e-mail

i need:
-The screenshot of ESN of original android netflix
-What value has `Current HDCP Level` of DRMInfo
-To know which ESN is generated by the addon, you can see it after doing `Reset ESN`, selecting Show ESN

I also need one more thing, a little less practical:
After installing Material Terminal app, type `getprop`
and press enter a long list will be show, then in the options, send this list to my email

thit should give me the full picture of the situation
and figure out what might not work

**Comment by DoctorBR** [comment]
I forgot to inform the **HDCP level**:
• Max HDCP Level Supported: **HDCP-2.2**;
• Current HDCP Level: **HDCP-2.2**

I sent the screenshots to your email, please check if they are sufficient.

As I mentioned earlier, not even adding the ESN manually makes it valid. Probably his **111 characters are too long** for the add-on.

About the Material Terminal app, it doesn't work on the Android TV Oreo 8.0 from Mi Box 3 ...

**Comment by CastagnaIT** [comment]
Hi,

very good,

 

you can install some other compatible Terminal apps

more or less all works in same way

 

if the other terminal app not have send to email option,

you can find for me these value and take a screenshot:

 

ro.product.manufacturer

ro.product.model

ro.build.characteristics

ro.nrdp.modelgroup

 

please be very careful, this data is of crucial importance,

some strings may not exist, please double-check

 

>> list the missing ones, too <<

 

Thanks for the collaboration

we're almost done

 

Stefano

 

 

 

 

Da: DoctorBR <notifications@github.com> 
Inviato: sabato 15 febbraio 2020 03:17
A: CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc: Stefano Gottardo <gottardo.stefano.83@gmail.com>; Comment <comment@noreply.github.com>
Oggetto: Re: [CastagnaIT/plugin.video.netflix] Only 540 SD with Xiaomi Mi Box 3 (MDZ-16-AB) (#475)

 

I forgot to inform the HDCP level:
• Max HDCP Level Supported: HDCP-2.2;
• Current HDCP Level: HDCP-2.2

I sent the screenshots to your email, please check if they are sufficient.

As I mentioned earlier, not even adding the ESN manually makes it valid. Probably his 111 characters are too long for the add-on.

About the Material Terminal app, it doesn't work on the Android TV Oreo 8.0 from Mi Box 3 ...

**Comment by DoctorBR** [comment]
How can I get the information you need **via ADB**?

But, I insist, the problem seems to be in the number of characters ...

**Comment by CastagnaIT** [comment]
to get via adb you have to enable 
Dubug USB on android developer menu

then, connect the phone mode type "file browser",
open `adb shell`
and write same thing `getprop`

i can not change the limits of kodi text controls,
in this moment the last part of esn is not very important

**Comment by DoctorBR** [comment]
> I also need one more thing, a little less practical:
> After installing Material Terminal app, type `getprop`
> and press enter a long list will be show, then in the options, send this list to my email
> 
> thit should give me the full picture of the situation
> and figure out what might not work

@CastagnaIT, I sent the long list to your email and it includes the following properties: 

- ro.product.manufacturer: Xiaomi 

- ro.product.model: MIBOX3

- ro.build.characteristics: mbx,nosdcard

- ro.nrdp.modelgroup: XIAOMIM12TRIAL

> i can not change the limits of kodi text controls,
> in this moment the last part of esn is not very important

Ok, how many characters are **really important**, from left to right?

Maybe I just need to add the correct amount, **not all 111 characters**, although the number of characters on nVidia Shield TV is even greater than on Xiaomi Mi Box 3.

**Comment by CastagnaIT** [comment]
i received the email 
and now i found the problem, but i need you to run a test
because i wouldn't want this change to break other devices

i need that you connect your mibox3 on a normal 1080P monitor or tv
after open the original netflix app, then show me how the esn has changed (send by mail)
or instead if it's the same as before, just answer here

I understand the nuisance, but i have no other way

**Comment by DoctorBR** [comment]
To use ADB I had to install my Xiaomi MI Box MDZ-16-AB (global version) on the computer (1080p).

And since the ESN was never “captured” by the add-on, I had to add it manually a few days ago, which also had no effect. So, when installing the Mi Box on the PC with a Full HD monitor, nothing changed. ESN remained the same as the one I added and remained unrecognized by Netflix (the content remains at 540 SD)...

**Comment by CastagnaIT** [comment]
not the Kodi addon,
i need to know the "original android netflix app"
if when device is connected to the monitor the ESN in the app settings is changed compared to what you sent me

the tests you did with the Kodi add-on are not useful...

**Comment by DoctorBR** [comment]
The ESN in the Netflix app **does not change** when I connect the Xiaomi Mi Box 3 (MDZ-16-AB) on a 1080p or 4K monitor.

I uninstalled and installed Kodi again, but the ESN is not recognized by the add-on and the videos continue in 540 SD... 

@CastagnaIT , if I go back to version **0.14.6**, or whatever, will I get 1080p again?

**Comment by CastagnaIT** [comment]
I will have to modify the generation of the esn
but i'm also waiting an answer from other users to avoid problems with other android devices

when ready i will attach here a test version

**Comment by CastagnaIT** [comment]
Please test, after install do Reset ESN from expert settings
[plugin.video.netflix_0.16.4_20200222_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4239549/plugin.video.netflix_0.16.4_20200222_test1.zip)
if not work give me another log

**Comment by DoctorBR** [comment]
Thank you!

I will test it, but will I need to uninstall the current version?

And after restarting ESN, and clicking the OK button in the add-on settings, will I need to restart Kodi **or something special?**

**Comment by CastagnaIT** [comment]
You can install as update

**Comment by DoctorBR** [comment]
**It worked!** :)

With the **plugin.video.netflix_0.16.4_20200222_test2** the resolution was as high as possible with my Netflix account (1080p).

But the ESN **was not recognized automatically** even after clicking the “Reset ESN” button. And I had to disable the passthrough or choose “AAC - 2 channels”. 

Here what I had to do to have the ESN recognized automaticall:
1. I clicked on the “Reset ESN” button; 
2. After confirming that the maximum resolution **was still 540 SD**, I clicked on “Manual ESN” and typed “DoctorBR” and waited for the error message “Entity used incorrect entity authentication data type”, so I restarted Kodi;
3. I clicked on the “Reset ESN” button **again** and this time the ESN **was recognized** .

@CastagnaIT , what about [**WIP] Synchronize the watched status of the videos with Netflix**, is it already working?

The debug log can be found from this link: https://paste.ubuntu.com/p/X3YtgSzTzf/

P.s. I have a **Samsung KS7000 TV** (maybe Samsung KS8000 in Italy) and **it supports Dolby Digital Plus**.

**Comment by CastagnaIT** [comment]
thank you for the test

there is no correlation between Dolby or passthrough and ESN used, you disabled it for nothing,
the only consequence on Dolby can be the type of plan subscribed
if the dolby doesn't work, it's because of some wrong Kodi, connection or tv settings

> what about [WIP] Synchronize the watched status of the videos with Netflix, is it already working?

the version i attached is the last one I'm currently developing,
no is not full ready yet
you can enable it if you want, but it's got some problems

**Comment by DoctorBR** [comment]
> there is no correlation between Dolby or passthrough and ESN used, you disabled it for nothing,
the only consequence on Dolby can be the type of plan subscribed
if the dolby doesn't work, it's because of some wrong Kodi, connection or tv settings

I thought it was related, because before it worked, just like Dolby Digital Plus works on my TV with the Amazon VOD add-on.

> the version i attached is the last one I'm currently developing,
no is not full ready yet

I was very sad to read that you will stop. Thank you very much for all the work. The add-on is spectacular.

> you can enable it if you want, but it's got some problems

I'll disable it so I don't have any problems!

By the way, an error appears when I click on “Exported”. Can't see the exported ones or is it an error or lack of configuration here?

**Comment by misiom1** [comment]
Hi,

I had exactly the same issue on my MiBox S. After installing test version and entering ESN manually HD started to work. The ESN was not discovered correctly even after doing reset.

Thanks

**Comment by CastagnaIT** [comment]
> By the way, an error appears when I click on “Exported”. Can't see the exported ones or is it an error or lack of configuration here?

whats error?

**Comment by DoctorBR** [comment]
> whats error?

@CastagnaIT, an error (**HTTP**) appears when I open the Netflix add-on and click on "Exported" to manage the content that has been exported to the library.

The debug log can be found from this link: https://paste.ubuntu.com/p/SHQhMmSRkh/

**Comment by CastagnaIT** [comment]
thanks for the log i will check

**Comment by CastagnaIT** [comment]
i have found the problem,
will be fixed on the next release

**Comment by CastagnaIT** [comment]
The new release is out,
if you still have problems with the Export menu open new Issue, thanks

**Comment by confusedcharlotte** [comment]
> Please test, after install do Reset ESN from expert settings
> [plugin.video.netflix_0.16.4_20200222_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4239673/plugin.video.netflix_0.16.4_20200222_test2.zip)
> 
> and please give me another log

Is there a version with this fix available for matrix? I'm having the same problem with a mecool km6, but the test build mentioned above requires python 2.26
