### ISSUE TITLE
Errno 10 No child processes

### ISSUE THREAD

**Issue by U5MANKHAL1D** [CastagnaIT/plugin.video.netflix#476]
#### Your Environment
- Netflix add-on version: 0.16.4
- Operating system version/name: iOS 13, Kodi 18.5
- Device model:  iPad Air 2

Used Operating system:
* iOS

### Describe the bug

The addon is installed correctly but it does not open. Upon clicking the addon icon it gives error. Log says " Errno 10 No child processes". Other than Netflix, all addons work.
#### Expected behavior

It should work as it works on Windows
#### Actual behavior

It does not work on iPas running iOS 13.3
#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link: [kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4205280/kodi.log)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
this seem an issue of the python library
not of the addon itself
I'll try to do a search, i don't know the reason

**Comment by CastagnaIT** [comment]
i need that you provide a log in right way as described in readme

**Comment by CastagnaIT** [comment]
Try install this test
[plugin.video.netflix_0.16.4_20200214_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4205732/plugin.video.netflix_0.16.4_20200214_test1.zip)
if not work give a log as described in readme

**Comment by U5MANKHAL1D** [comment]
Thanks for your help. Test1 gives the same error.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4205859/kodi.log)

**Comment by U5MANKHAL1D** [comment]
Another log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4205961/kodi.log)

**Comment by CastagnaIT** [comment]
It is a python platform issue
try this new test
[plugin.video.netflix_0.16.4_20200214_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4206259/plugin.video.netflix_0.16.4_20200214_test2.zip)

should start correctly, **BUT**
i need that you perform this steps and let me know what happen:

1) test 1:
After login, and entered to an profile,
try to rate a tvshow or film by using context menu
a window with thumbs should be opened

2) test 2:
Go to addon settings, and open Parental control
let me know if the window will open

3) test 3:
Play an episode of tv show, most have the option to skip the introduction
let me know if Skip button will be displayed

**Comment by U5MANKHAL1D** [comment]
Okay ... lemme do all that

**Comment by U5MANKHAL1D** [comment]
Addon installed but a different error this time. Addon did not open so could not do as you directed.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4206402/kodi.log)
<img width="1024" alt="Screenshot 2020-02-15 at 12 23 55 AM" src="https://user-images.githubusercontent.com/61058010/74561244-08cdaf00-4f8a-11ea-8b66-38e9d2993f9e.png">
<img width="1024" alt="Screenshot 2020-02-15 at 12 26 25 AM" src="https://user-images.githubusercontent.com/61058010/74561266-13884400-4f8a-11ea-9cea-5d8601f6b98f.png">

**Comment by CastagnaIT** [comment]
I just read an discussion that says that iOS not support `subprocess` functions
because is linux-based and this creates several complications

I need more time to figure out how to find a workaround
I'll let you know

**Comment by U5MANKHAL1D** [comment]
I really appreciate and thankful for your effort and time.

**Comment by CastagnaIT** [comment]
Test 3:
[plugin.video.netflix_0.16.4_20200215_test3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4208326/plugin.video.netflix_0.16.4_20200215_test3.zip)

in theory it should be a step forward already, but i don't know how many limitations there are on iOS, let me know how works

**Comment by U5MANKHAL1D** [comment]
Thanks .. let me check this

**Comment by U5MANKHAL1D** [comment]
Same errors as with test 2. 😔😔
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4208355/kodi.log)

**Comment by CastagnaIT** [comment]
yes same but on different code
i check

**Comment by U5MANKHAL1D** [comment]
Right

**Comment by CastagnaIT** [comment]
Try:
[plugin.video.netflix_0.16.4_20200215_test5.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4208365/plugin.video.netflix_0.16.4_20200215_test5.zip)

**Comment by U5MANKHAL1D** [comment]
A little progress. It worked and asked for email and password. After that it gave error as in screen shot
<img width="1024" alt="Screenshot 2020-02-15 at 4 01 10 PM" src="https://user-images.githubusercontent.com/61058010/74586754-a8338600-500c-11ea-9db4-7f6542e94fed.png">
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4208369/kodi.log)

**Comment by CastagnaIT** [comment]
go on
[plugin.video.netflix_0.16.4_20200215_test6.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4208374/plugin.video.netflix_0.16.4_20200215_test6.zip)

**Comment by CastagnaIT** [comment]
go on:
[plugin.video.netflix_0.16.4_20200215_test7.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4208375/plugin.video.netflix_0.16.4_20200215_test7.zip)

**Comment by U5MANKHAL1D** [comment]
Okay

**Comment by U5MANKHAL1D** [comment]
Different errors. On fresh install, background service works but after kodi restarts, background service does not work. After putting login details, it’s gave error.
<img width="1024" alt="Screenshot 2020-02-15 at 4 14 37 PM" src="https://user-images.githubusercontent.com/61058010/74586970-fea1c400-500e-11ea-9a48-4f6708db46a5.png">
<img width="1024" alt="Screenshot 2020-02-15 at 4 16 59 PM" src="https://user-images.githubusercontent.com/61058010/74586983-0fead080-500f-11ea-9941-06755105ccd8.png">
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4208388/kodi.log)

**Comment by U5MANKHAL1D** [comment]
After putting login details, it gave attribute error

**Comment by CastagnaIT** [comment]
I hope this is the right time
[plugin.video.netflix_0.16.4_20200215_test8.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4208413/plugin.video.netflix_0.16.4_20200215_test8.zip)

**Comment by U5MANKHAL1D** [comment]
I hope so

**Comment by U5MANKHAL1D** [comment]
Bravo .. you are awesome .. huge progress .... 
1. Login successful
2. Background service starts after kodi restarts
BUT
Could not play because of following errors. Both notifications appeared one after the other. First it was Missing CDM and then other
<img width="1024" alt="Screenshot 2020-02-15 at 4 46 30 PM" src="https://user-images.githubusercontent.com/61058010/74587395-cd77c280-5013-11ea-9cfd-635f46661359.png">
<img width="1024" alt="Screenshot 2020-02-15 at 4 55 48 PM" src="https://user-images.githubusercontent.com/61058010/74587443-1596e500-5014-11ea-89c5-5822a91880fc.png">
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4208419/kodi.log)

**Comment by U5MANKHAL1D** [comment]
Logs
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4208423/kodi.log)

**Comment by U5MANKHAL1D** [comment]
Kodi 18.5 has inbuilt inputstreams adaptive and it works in other addon.

**Comment by CastagnaIT** [comment]
if you play unprotected video content you will never make an error,
netflix has DRM video protected then is needed widewine library

@dagwieers it is possible to find a way to download iOS widevine library? from documentation seem supported

**Comment by U5MANKHAL1D** [comment]
Right

**Comment by CastagnaIT** [comment]
can you provide an info?
install Chrome browser app
then open with chrome: https://bitmovin.com/demos/drm

scroll down the page until title "Encrypted media extension - EME"
report what has the tick ✅

**Comment by U5MANKHAL1D** [comment]
Okay

**Comment by U5MANKHAL1D** [comment]
Here is screen shot
<img width="1024" alt="Screenshot 2020-02-15 at 6 50 00 PM" src="https://user-images.githubusercontent.com/61058010/74589084-159ee100-5024-11ea-9706-64fcae4509d0.png">

**Comment by dagwieers** [comment]
Open an issue report at inputstreamhelper. I think this is a bug as iOS ought to be supported and nobody reported any issues before.

**Comment by U5MANKHAL1D** [comment]
Alright

**Comment by U5MANKHAL1D** [comment]
Opened issue report with inputstreamhelper

**Comment by CastagnaIT** [comment]
from my side this error is resolved, then close
