### ISSUE TITLE
No episodes showing

### ISSUE THREAD

**Issue by fildubek** [CastagnaIT/plugin.video.netflix#478]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe the bug
The Tv series episodes list are empty.
Movies work normaly

#### Expected behavior
When choosing on a Tv series, there should be
a list of episodes to watch.

#### Actual behavior
When choosing on a Tv series, no
 list of episodes to watch appears.

#### Steps to reproduce the behavior

1)Netflix Plugin
2)choose account
3)choose my list or search for a tv series
4)Pick a Tv series
5)No episodes

### Debug log

The debug log can be found from this link:
https://paste.gg/p/anonymous/747726e87aa7496cbd8bb76fc592bb83

**Comment by CastagnaIT** [comment]
_Ignored rules_ label: The guidelines for compiling the Issue post have not been followed correctly, add or modify the information in the correct way, otherwise it will be closed in the next days.

**Comment by CastagnaIT** [comment]
Unfurnately the log is incomplete, no debug info,
instructions to get a right log in the Readme
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/README.md#something-doesnt-work

**Comment by fildubek** [comment]
I have done exactly what the instructions say
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Feb 19, 2020, 09:41 by notifications@github.com:

**Comment by CastagnaIT** [comment]
the log is not as it should be, so you did not follow the log instructions correctly..
then i can't do anything

**Comment by fildubek** [comment]
Someone suggested to me to delete all log files and try
again so here is another attempt
https://paste.gg/p/anonymous/7be1c4c88ecd4f3590f8367cd4d32034

**Comment by CastagnaIT** [comment]
yes now the log is good
analyzing the log i not found errors or problems of any kind your case is strange

you can try go to addon expert settings and do a _purge cache in memory and to disk_
after do it, reboot the device, so we are certain that there's no trace of old data

**Comment by fildubek** [comment]
I purger cache in memory and disk, rebooted but no change 
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Feb 20, 2020, 20:19 by notifications@github.com:

**Comment by CastagnaIT** [comment]
at the moment i don't know how to help you

**Comment by fildubek** [comment]
Ol
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Feb 20, 2020, 20:31 by notifications@github.com:

**Comment by fildubek** [comment]
ok*

I removed the .kodi folder on the raspberry pi. Then I open Kodi again reinstalled the add on
and now everything is working. Episodes are listed again.

**Comment by CastagnaIT** [comment]
something broke in Kodi you were unlucky..
at least you found a way to solve
