### ISSUE TITLE
cant seem to get widevine cdm

### ISSUE THREAD

**Issue by unitypunk** [CastagnaIT/plugin.video.netflix#481]
#### Your Environment
- Netflix add-on version: 16.3,16.4
- Operating system version/name: LibreElec 9.0
- Device model:  RPI3 

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
when attempting to play a video on netflix, im met with the "widevine CDM is required" popup
press install widevine,
 Yes, to 2gb of space check(i have 12 free on a 16gb sd),
 agree to eula,
Download in progress
then "netflix addon error" appears
SSLError:('the read operation timed out')

#### Expected behavior
it should install widevine cdm
#### Actual behavior
it does not install wide vine CDM
#### Steps to reproduce the behavior

1.be me
2.use latest libreelec
3. attempt to play video from  netflix addon.

### Debug log
The debug log can be found from this link: https://pastebin.com/JiECWLFp

#### Installation
Using this repo

**Comment by unitypunk** [comment]
after about 100 attempts and 0 changes it worked.

not sure what was going on.

**Comment by ekkerdthomas** [comment]
I am experiencing the same issue. Can we please open this issue?

**Comment by CastagnaIT** [comment]
no this not concern nf addon but inputstreamhelper addon
