### ISSUE TITLE
Addon not updating played status in other Netflix clients?

### ISSUE THREAD

**Issue by greenmr** [CastagnaIT/plugin.video.netflix#483]
- Netflix add-on version: 0.16.4
- Operating system version/name: Fire TV OS 6.2.6.8 (NS6268/2315)
- Device model:  Fire TV Stick 4K

After playing Netflix streams in this Kodi addon other Netflix clients (native Fire OS one and Sony Bluray player Netflix app) don't know they were played and don't update "Continue Watching", "Watch it Again", etc. Is this a bug or do I have things configured wrong?

**Comment by CastagnaIT** [comment]
This is not supported
