### ISSUE TITLE
unable to play movies in HighmediaQ10pro Androidbox

### ISSUE THREAD

**Issue by Elytium** [CastagnaIT/plugin.video.netflix#485]
## 

#### Your Environment
- Netflix add-on version: 
- Operating system version/name: <Android 7.0 -->
- Device model:  <HimediaQ10pro-->

Used Operating system:
* [X ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

request failed validation during key excange

https://paste.kodi.tv/galodonoji

I have the following problem on my Himedia Q10 Pro Androidbox. I have installed your plugin under Kodi 18.5 and unfortunately I don't get a movie or series played. There is always a message that an error has occurred.

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/galodonoji

#### Installation
* [ X] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

thanks for the help in advance

**Comment by CastagnaIT** [comment]
Install this last updated:
[plugin.video.netflix_0.16.4_20200224.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4243627/plugin.video.netflix_0.16.4_20200224.zip)
Open addon settings,
on expert settings:
- first enable Debug verbose, press OK
- reopen settings, do Reset ESN

if working, then disable debug verbose
if not working put a new log

**Comment by Elytium** [comment]
Hello again,
I did what you wrote on my Himedia Q10 pro Box
-enable Debug verbose in the Netflix Addon
-reset ESN in the Netflix Addon
I had installed the new version of the netflix addon, but i still have the same error. could you take another look at the current logfile. thank you again for your help. best regards T.T.
https://paste.kodi.tv/aqoyevetir

**Comment by CastagnaIT** [comment]
you didn't install the version i attached
the log displays the previous version

**Comment by Elytium** [comment]
Hello and good evening,
sorry for my mistake.I don't know wat was going wrong in the moment of fatigue ;.-))
How ever i tried again and now it works famous.
Thanky you and all coworker for your help and good job. I'm verry happy and my wife too ;-)
