### ISSUE TITLE
Widewine CDM extraction error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 34

### ISSUE THREAD

**Issue by optimist10150** [CastagnaIT/plugin.video.netflix#487]
#### Your Environment
- Netflix add-on version: 0.16.4
- Operating system version/name: Raspbian Buster with Kodi Leia 18
- Device model:  Raspberry Pi 4 Model B

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

When I start the Netflix AddOn and choose any movie it asks to install Widewine. Everything is working just fine until it wants to extract Widevine CDM.
After a short time an error message shows up, that the extracting of the files failed and the movie won't play.

#### Expected behavior

It should install Widewine and start the movie that was chosen.

#### Actual behavior

The following error message pops up after trying to extract the files:  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 79: ordinal not in range(128)

#### Steps to reproduce the behavior

1. Open Netflix Addon
2. Choose any movie
3. Accept all the messages that pop up
4. Download of Chrome OS Recovery Images will start
5. Extracting of Widewine will start
6. Error message shows up

#### Possible fix

Not a clue. I tried to remove and reinstall everything but nothing changed. 
Before I installed the AddOn I did the following steps:
1. sudo apt update
2. sudo apt upgrade
3. sudo apt install kodi kodi-peripheral-joystick kodi-pvr-iptvsimple kodi-inputstream-adaptive kodi-inputstream-rtmp
4. sudo apt install build-essential python-pip python-dev libffi-dev libssl-dev libnss3
5. sudo pip install setuptools wheel pycryptodomex
6. wget https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.0.zip

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/sekusalari

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

Amazon Prime (from Sandmann79 repository) showed the same error when trying to extract the Chrome OS Recovery Images.

**Comment by CastagnaIT** [comment]
From the log

In netflix, there is a lot of
`Failed to establish a new connection: [Errno -3] Temporary failure in name resolution`
this is a bad network settings or problems with your ISP

The widevine error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 34`
it's not concerning this addon
you have to ask here: https://github.com/emilsvennesson/script.module.inputstreamhelper

**Comment by optimist10150** [comment]
Thanks for the quick response. Do you have any idea which network settings could be the problem here? After a few failed starts because of the error "Failed to establish a new connection" the AddOn will start just fine.

I will ask  here (https://github.com/emilsvennesson/script.module.inputstreamhelper) about the problem with widevine.

**Comment by CastagnaIT** [comment]
usually it could be problem with:
DNS,
VPN or Proxy (not allowed by netflix),
ISP
or if you use complex network of routers/extenders is needed to check each device

**Comment by CastagnaIT** [comment]
Closed due to inactivity
