### ISSUE TITLE
No video. Kodi treats them as audio files. It has always worked fine.

### ISSUE THREAD

**Issue by TimmyP777** [CastagnaIT/plugin.video.netflix#488]
#### Your Environment
-14.6
- Fire OS
- Fire Stick 4k

Used Operating system:
* [* ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
No video. Kodi treats them as audio files.

#### Actual behavior
Play video
Plays audio

#### Steps to reproduce the behavior

1. Play video
2.
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
_Ignored rules_ label: The guidelines for compiling the Issue post have not been followed correctly, add or modify the information in the correct way or it will be closed in the next days
