### ISSUE TITLE
Support for interactive content

### ISSUE THREAD

**Issue by Sybas** [CastagnaIT/plugin.video.netflix#492]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

It should be nice to be able to watch interactive content like the movie Black Mirror's Bandersnatch.

**Comment by CastagnaIT** [comment]
The interactive content is a complex system
i think it will take at least one or two month to try to implement it properly
personally i'm already too busy, so i will not do it
of course anyone else can study how to implement it

**Comment by CastagnaIT** [comment]
I think it's hard to find someone willing to integrate such a complex functionality
if in the future there will be evolutions it will be possible to reopen this Issue
