### ISSUE TITLE
Addon fails to load directories

### ISSUE THREAD

**Issue by laclaro** [CastagnaIT/plugin.video.netflix#493]
Hi,

I am on a RPi3 with OSMC Kodi 18.5 (Debian 9.12, package version rbp2-mediacenter-osmc-18.5.0-4). Since a couple of Versions I have issues with the Netflix Addon to load properly.

After running launching the waiting-icon is circling on and on...forever. I recently uninstalled every trace of plugin.video.netflix. Now, after a significant waiting time with my processor running at 100%, I get to the addon-login screens (since I deleted the credentials when uninstalling). After giving them, the circle is again spinning endlessly without giving any trace in the debug log what is going on.

The log is here https://gist.github.com/laclaro/7ce3e2161010cad703b02a7721190277

The json calls are most likely caused by my phone remote.

Best regards,

Henning

**Comment by CastagnaIT** [comment]
from the symptoms described this seems more like a problem of your Kodi installation
anyway the log is incomplete is practically empty

**Comment by CastagnaIT** [comment]
Closed due to inactivity

**Comment by laclaro** [comment]
Tried again with a default OSMC stretch installation. Same result. Infinite loop without logging anything.
How to increase the log level?

**Comment by laclaro** [comment]
Ha! Apparently I did not wait long enough: here is the log with some SQLite exception
https://gist.github.com/laclaro/b87da360b2dd1db35a8c4318771ca27d

**Comment by CastagnaIT** [comment]
this error should never happen
and it's particularly strange that this happened
and given the previous problems, it seems that something in your device is not working properly

anyway the only way is to uninstall the addon deleting also user data when prompt
and install it again, there is no fix for this

**Comment by laclaro** [comment]
That is what I just did. I installed vanilla OSMC and your plugin, just like the Wiki said.
However, I started completely anew.
* shutdown kodi
* removing userdata/addon_data/plugin.video.netflix and addons/plugin.video.netflix, addons/repository.castagnait
* installed repo from zip
* installed addon from repo
* cold-started addon without configuring addon
**Works**

Maybe the addon or something else just destroyed the database?
Do you know why it could take so long to throw this SQLite error without responding in the first place? Is it an addon error or does it come from kodi itself?

Best,

Henning

**Comment by CastagnaIT** [comment]
is an error that comes from a python module that manages the database of the add-on
means that it is trying to add an already existing value
but before that there is already a check to prevent this kind of error

so i have no idea what happened to your database, it's never happened to anyone
maybe some type of delay in reading/writing? caused from some other problem?

in the past i remember an RPI user with a faulty memory disk caused data loss
has formatted the memory disk and is back to work

**Comment by laclaro** [comment]
Thank you for your time. It might be the cheap SD card, which is a little faulty. This happens sometimes with RPIs. I already checked dmesg and found nothing, but maybe it was only temporary.
