### ISSUE TITLE
[HTTPError] After logging in, get HTTPError, please debug log for details

### ISSUE THREAD

**Issue by ortonomy** [CastagnaIT/plugin.video.netflix#498]
#### Your Environment
- Netflix add-on version: 0.16
- Operating system version/name: Raspbian Buster
- Device model:  Raspberry Pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
System shows an HTTPError modal after logging in

#### Expected behavior
1. Login
2. Enjoy Netflix

#### Actual behavior
1. Start add-on
2. Enter email
3. Enter password
4. Displays HTTPError modal

#### Steps to reproduce the behavior
1. Start Kodi
2. Start Netflix Add-on
3. Login OR

3. Log out
4. Log back in

### Debug log
The debug log can be found from this link: https://pastebin.com/XD54CRrb

#### Screenshots
![481582816068_ pic](https://user-images.githubusercontent.com/6688676/75456873-0de12400-59b6-11ea-80ea-224b54f821c9.jpg)

**Comment by CastagnaIT** [comment]
i can not fix this error
your http error is: 403 Forbidden Error
could be caused by the type of network used

**Comment by ortonomy** [comment]
OK, I think this might be because I'm on a VPN in China. I'll see what I can do about using a different connection

**Comment by CastagnaIT** [comment]
Netflix do not allow VPN
I can't help you here, Proxy or VPN topics are not allowed here
