### ISSUE TITLE
Netflix addon - This title is not available to watch instantly error

### ISSUE THREAD

**Issue by theflyingsquirrel88** [CastagnaIT/plugin.video.netflix#499]
#### Your Environment
- Netflix add-on version: <0.16.4>
- Operating system version/name: <Android 9.0.0 API Level 28>
- Device model:  <Lenovo P10>

Used Operating system:
* [ ] Android

### Describe the bug

I am using Kodi 18.5 on Android 9.0.0 with the netflix add on. I installed the addon Repository from https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.0.zip
Inputstream Adaptive is installed and enabled,
After I log into netflix, I can see the list and browse into it. However, when I tried to play the video, it displayed the message "This title is not available to watch instantly".
ESN in netflix addon is NFANDROID1-PRV-T-L3-LENOVLENOVO=TB-X705F-9075-
DRM info showed that this tablet has security Level of L1.

#### Expected behavior

The video show play normally.

#### Actual behavior

After I log into netflix, I can see the list and browse into it. However, when I tried to play the video, it displayed the message "This title is not available to watch instantly".

#### Steps to reproduce the behavior

1.Install kodi 18.5 in Android 9.0.0 with netflix addon 0.16.4
2.Play netflix video
3.Get the message

#### Possible fix

I have no idea.

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/acoqojisag.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
 I'm using Netflix Repo

**Comment by CastagnaIT** [comment]
the log has not netflix debug info
how to: https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

Try read FAQ solution:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ#The-error---This-title-is-not-available-to-watch-instantly

**Comment by theflyingsquirrel88** [comment]
I understand the rest, but I cannot find this.
Open add-on settings, go to in Expert page and change Debug logging level to Verbose
Is it in the netflix addon? I cannot seems to find that Verbose settting.
I will try that again on monday as the device I have is at work now.
Thanks.

**Comment by CastagnaIT** [comment]
> Is it in the netflix addon?

yes
i think you have to see better and scroll the page down

**Comment by theflyingsquirrel88** [comment]
This is the new debug log.
https://paste.kodi.tv/wajemiwizo.kodi
Am I doing it correctly this time?

**Comment by CastagnaIT** [comment]
yes now it is a good log
the profiles data are correct

have you tried the solution in the FAQ?

**Comment by theflyingsquirrel88** [comment]
Yes. I tried. It did not work.
I logout and login again from netflix even though it was a fresh setup. No difference.
From my understanding, since it is android,  reinstall Widevine CDM would not be necessary.

**Comment by CastagnaIT** [comment]
mmh your situation is strage,
i can only suggest you to wait until the new version of the add-on will be released
i think more o less in a week

**Comment by theflyingsquirrel88** [comment]
Ok. I will do that. 
What do it say failed in the log?
I tried to read it but can't understand it.

**Comment by CastagnaIT** [comment]
what has failed is the message you read,
from my experience this type of error usually can appears in these situations:
- the video is not more available on netflix
- the video at this moment not available to play (try later)
- you are playing a video from a limited age profile (this is an addon bug fixed in next release)
- It could also be other unknown reasons

but i see now that your video is the _Test patterns_ not a real netflix movie or episode of tvshow
so if it doesn't work it's not in my interest to waste time on this

**Comment by theflyingsquirrel88** [comment]
I actually tried it on many other videos, like lost in space and it works in the tv box that I use with the same netflix addon in CoreElec.
None of the video I try works in kodi app i install in this tablet.
It is not video specific. 
If you want, I can create another log with lost in space. Would that give you some more insight?

**Comment by CastagnaIT** [comment]
The new addon release is out,
try install this new version

**Comment by theflyingsquirrel88** [comment]
I tried it and the error is the same.
Here is the log file.
https://paste.kodi.tv/nabusufece.kodi

**Comment by CastagnaIT** [comment]
yes seem updated although the debug is disabled,
Try Reset ESN in expert settings

if you're still having problems after that,
i don't know how to help you because you do not understand what's wrong with your account

can you also verify that each profile has not set some type of age limit or family filter or PIN

**Comment by theflyingsquirrel88** [comment]
I reset the ESN. The ESN looks different now, but the error message is still the same.
Log
https://paste.kodi.tv/akotanulos.kodi
How do I enable the debug setting? It is set to Verbose in the setting already.
I have the same netflix addon installed on my TV box with Coreelec and it worked perfectly.
I can stream 1080p with the addon there.
I dont have any pin, age limit or family filter with my netflix account.
Would it be Kodi not compatible with the chipset in my device?

**Comment by CastagnaIT** [comment]
Kodi's not the problem, it's something else that's not right
between netflix account/device...but who knows what...

you can take a screenshot of the esn from official netflix app? (but censure some last numbers)
I'd like to see if there's something different

**Comment by Losos3113** [comment]
Hello,
i have the same problem on raspberry pi 4 (4 GB RAM,raspbian,64bit kernel).
I have tried log out reinstal Widevine and reset ESN nothning changed.
my logfile: 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4301832/kodi.log)

**Comment by theflyingsquirrel88** [comment]
Netflix official app ESN: NFANDROID1-PRV-T-L3-LENOVLENOVO=TB-X705F-
Netflix add on ESN after reset: NDANDROID2-PRV-LENOVOTB-X705F-LENOVLENOVO=TB-X705F-

**Comment by CastagnaIT** [comment]
sadly not...
but this shows that the original Nfx app recognizes the device as an L3 sec widevine and not L1 sec widevine, that's weird

I don't know how to help you i am sorry

**Comment by theflyingsquirrel88** [comment]
That is ok.
I will just stick with the 520p then.
Is there something like CoreELEC that will work with Qualcomm Snapdragon 450?

**Comment by CastagnaIT** [comment]
I don't think i'm the right guy to give you that kind of answer
I take care of this addon but i don't know all the hardware supported by every kind of Kodi OS

**Comment by theflyingsquirrel88** [comment]
I see. Thanks anyway.

**Comment by pikopikopikopiko** [comment]
this is because this forces wrong profile, I assume there is no longer chance to watch mpl40 on widevine L3, hpl are profiles you should look for, otherwise an error occuress

**Comment by gombosg** [comment]
For TB-X606X HD playback worked for me with ESN
`NFANDROID1-PRV-T-LENOVLENOVO=TB-X606X-15973-`
For TB-X606F I don't know, but it could then be:
`NFANDROID1-PRV-T-LENOVLENOVO=TB-X606F-15957-`
for HD playback!

**Comment by iamzain1** [comment]
I'm seeing exactly the same issue , Login with Authentication key is fine, Profile list is fine, I can see all items in Netflix, but when I attempt to play anything , I get the message "This title is not available to watch instantly".

Nothing has changed, this just suddenly started happening.
