### ISSUE TITLE
Search function choking on 'Tidying up with Marie Kondo'?

### ISSUE THREAD

**Issue by Borromini** [CastagnaIT/plugin.video.netflix#5]
*I'm submitting a ...*
  - [ x] bug report

## General information

LibreELEC 9.0 x86_64

### Addon version used
0.14 beta 20

### Description
I know, it sounds silly. But the girlfriend's watching it on her laptop :-)

The search function in the main menu does not show any results. E.g. Marie Kondo has a show on Netflix, but typing her name into the search function doesn't list the show as a result, nor does it with 'Tidying up', which is the title of the series ('Tidying up with Marie Kondo).

It's pretty weird since e.g. inputting 'Luther' (which is also on Netflix) will show Luther on top of the results. So not sure what's going on here. 

### Steps to Reproduce

1. Open Netflix search function in the plug-in overview (after you selected the user)
2. Search for 'Marie Kondo' or 'Tidying up'

**Expected behavior:** Marie Kondo's show on top of the list

**Actual behavior:** Other tangentially related shows show up but not the Marie Kondo 

* [x] I'm using this Netflix Repo

### Operating System

* [x] Linux (x86/x64)

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log
https://paste.debian.net/1066647/

**Comment by CastagnaIT** [comment]
with my tests i can find marie kondo without problems
in this partial log there is nothing abnormal, put the full log

I've seen that you use AutoCompletion plugin, suggest try disable it and after write the words using the keyboard

let me known

**Comment by Borromini** [comment]
I tried without using the autocompletion plugin (I did not disable it but ignored its input). I have removed the data: ["..."] hashes, they made the log file close to 20 MB.

https://paste.kodi.tv/ohirawalaw.kodi

**Comment by CastagnaIT** [comment]
eh.. are missing pieces in this last log if your log reaches such a large size, you have activated the kodi log specific component which is not necessary

Try so
-disable log specific component (but leave kodi debug active)
-after reboot librelec device (so you can have a clean log)
-open netflix addon, search Kondo
-now copy the log file
