### ISSUE TITLE
OSError JSONRPC-Error -32602: Invalid params

### ISSUE THREAD

**Issue by tweimer** [CastagnaIT/plugin.video.netflix#500]
#### Your Environment
- Netflix add-on version: 0.16.4 (snapshot 8d35a42)
- Operating system version/name: Libreelec 19
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
After updating to the current snapshot, I had to reenter my login credentials (which I did).

However, I cannot play any Video, it gives me the error message from the description.

I attatched the logfiles. Do you need more infos?
[log-2020-02-28-21.50.07.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4269275/log-2020-02-28-21.50.07.zip)

**Comment by CastagnaIT** [comment]
thanks for the test
I will have to ask to libreelec devs

**Comment by CastagnaIT** [comment]
Try this:
[plugin.video.netflix_0.16.4_20200301.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4271569/plugin.video.netflix_0.16.4_20200301.zip)
should be working

**Comment by tweimer** [comment]
Looks good now, thanks!
