### ISSUE TITLE
Netflix and Kodi crash a few seconds after having started a video

### ISSUE THREAD

**Issue by akirikos** [CastagnaIT/plugin.video.netflix#503]
## Bug report
Netflix and Kodi crash a few seconds after having started a video - possibly when trying to show  "Skip Intro" .

#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: LibreELEC 9.2.0 (Kodi 18.5)
- Device model:  Raspberry Pi 3B

Used Operating system:
* [X] Raspberry-Pi - LibreELEC 9.2.0

### Describe the bug
When starting a video, it plays for a few seconds and then Netflix crashes along with Kodi. Kodi restarts. 

#### Expected behavior
The video should play.

#### Actual behavior
Netflix crashes and Kodi restarts.

#### Steps to reproduce the behavior
After installing using the method in https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon, 
1. Login on Netflix add-on
2. Play any video with subs enabled (for me it was Star Trek: Discovery, Season 2 episode 1)

#### Possible fix
Workaround: In the "Playback" settings of the add-on disable "Ask to skip intro/recap"

### Debug log
Link for debug log:
https://paste.ubuntu.com/p/xdr7wjzzTg/

#### Installation
* [X] I used CastagnaIT repo to install Netflix.
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information
I have tried to uninstall and reinstall  Netflix, Inputstream and Inputstream Helper add-ons, and also to reset CDM / Widevine. Also, because default subtitle language is Greek for my installation, I tried reverting this to the default language and disabling subs altogether. None of these actions corrected the problem. I read the topic https://github.com/CastagnaIT/plugin.video.netflix/issues/8 but it does not seem to bee the case.

**Comment by CastagnaIT** [comment]
In the log there are no unexpected errors
this seems more like a problem of your Kodi installation or with the device

**Comment by akirikos** [comment]
Well, I removed 0.16.4 and installed version 1.0.0 and I also de-activated "Ask to skip Intro/recap" and now it works.
Sometimes I get "AddonSignals call timed out" though...!

**Comment by vteccorp** [comment]
@akirikos 
Turn on "Enable IPC over HTTP" in expert settings and check... it helped me.

**Comment by CastagnaIT** [comment]
it's particularly strange what you say
if that was the real problem of "Ask to skip Intro/recap", it would happen to everyone
but that part of code has never been changed

**Comment by akirikos** [comment]
Yeah, well, the whole thing was strange... I will try to switch on "skip intro/recap" again and post here again. The "AddonSignals call timed out" has disappeared without changing anything.

**Comment by akirikos** [comment]
UPDATE: I can confirm that enabling "ask to skip intro/recap" in Playback settings causes Kodi to crash. When it is disabled, the plugin works fine.

**Comment by CastagnaIT** [comment]
If it is Kodi to be crashed it means it's something wrong in Kodi core
i can't do anything about it

if instead a verifiable error happens in the log, then we can figure out what to do

your case is unique and difficult to understand because the code "ask to skip intro/recap" doesn't do anything in particular

you can try to do last two things:
-update libreelec to latest version
-download and install netflix addon Daily Build (link in readme)

**Comment by CastagnaIT** [comment]
closed due to inactivity
