### ISSUE TITLE
Dolby Vision and Auto refresh rate switch breaks video colors

### ISSUE THREAD

**Issue by DeckardCain2014** [CastagnaIT/plugin.video.netflix#505]
![IMG_20200306_202805](https://user-images.githubusercontent.com/10652393/76115733-038fdd00-5fe9-11ea-91d0-aa1217cb61c4.jpg)

#### Your Environment
- Netflix add-on version: 1.0
- Operating system version/name: Latest Kodi on FireTV
- Device model:  FireTV Stick 4K

Used Operating system:
* [x ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request
Hi,
I installed today the current release 1.0 on Kodi on a Fire TV Stick. I enabled auto refresh rate in Kodi. However, this seems to break Dolby Vision playback. HDR is working fine. In DVision, only strange yellow and blue video colors are shown instead of the correct ones. I will supply a screenshot later.

**Comment by quietvoid** [comment]
I'm noticing this behaviour as well.
The stream played is Dolby Vision at first (the display switches modes correctly to Dolby Vision).
After the refresh rate change, the display goes back to SDR mode. Hence the bad colors/contrast.

**Comment by CastagnaIT** [comment]
Whats Kodi version?

**Comment by quietvoid** [comment]
Kodi 18.6, armv7a on Fire stick 4K as well.
I can look at logs if they're needed, sorry haven't read the contribution guidelines.

**Comment by CastagnaIT** [comment]
you have to report the problem in the Kodi forum,
this is not a problem of this add-on but of the Kodi system

**Comment by CastagnaIT** [comment]
Closed because the issue do not depend on the addon
