### ISSUE TITLE
Netflix plugin won't play videos

### ISSUE THREAD

**Issue by the-isz** [CastagnaIT/plugin.video.netflix#507]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: ArchLinux
- Device model:  x86_64

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

* Log in to Netflix works and I can navigate through the movies/shows.
* Trying to play something fails instantly, no error is shown in the GUI. log is attached.
* Amazon Prime plugin can play videos.
* Playing Netflix through chromium instead of kodi also works.

#### Expected behavior

Netflix plugin should allow me to play videos through kodi.

#### Actual behavior

See above.

#### Steps to reproduce the behavior

See above.

### Debug log

The (slightly truncated) debug log can be found from this link:

https://pastebin.com/bcf7v6Li

**Comment by CastagnaIT** [comment]
Is needed a full log, taken after a Kodi reboot, and tried to play a video

**Comment by the-isz** [comment]
Hi @CastagnaIT and thanks for looking into this!

Please find a full log here: https://pastebin.com/vy8CvEiP

Netflix login failed first, but this is pretty normal and it worked the second time.

After starting Kodi, I only navigated to a show and tried to play it, which failed.

FYI: I tried downgrading to 0.16.4, but the problem was the same on that version.

Let me know if there's more information I can provide you with!

Best regards!

**Comment by CastagnaIT** [comment]
there is a problem with Addon Signals add-on
i don't know if that depends on the type of operating system used (arch linux)
but there seems to be a problem with the use of the socket ports, that fails to communicate data
(for information the socket ports are dynamic, free numbering is taken)

I don't know how to help you,
you can try to enable "Enable IPC over HTTP" on expert settings
will probably work, but remember that your problem is just camouflaged and unresolved

**Comment by vteccorp** [comment]
Today I came across the same problem. Luckily "Enable IPC over HTTP" works good.
Strange things are happening on the Netflix server lately... :|

**Comment by the-isz** [comment]
Hi @CastagnaIT,

thanks for your response! I hope you are still well.

I think you might be looking at the wrong problem (for this issue). If I'm seeing this correctly, the Addon Signals problem in my trace (line 805) only caused the first login to Netflix to fail (I mentioned this when I posted the full trace). I've had this quite often, but it only happens once after a reboot and after that, everything is fine.

The problem with playback (this issue) happens around line 1404 in my full trace. Maybe you could have another look?

As per your suggestion, I also tried enabling "Enable IPC over HTTP" and it didn't solve my problem, which makes me even more certain the Addon Signals is not related to it.

Best regards!

**Comment by CastagnaIT** [comment]
i see in the log that Amazon was updating
before run Netflix try disable Amazon addon

**Comment by the-isz** [comment]
Hi again @CastagnaIT,

as per your request, please find a new reproduction with Amazon addon disabled here:

https://pastebin.com/meMaNSuY

Again, thanks for your help and great work!

Best regards

**Comment by CastagnaIT** [comment]
go to addon Expert settings,
select "Impoutstream adaptive settings"
on Expert page, TURN OFF Enable Pre-Release features
Press ok, double check, is it is disabled

Then try again to play

**Comment by the-isz** [comment]
Hi @CastagnaIT,

please find a new log with both Amazon addon and "Enable Pre-Release features" disabled here:

https://pastebin.com/B7BKyjru

Again, thanks for your help! Hope you are well

**Comment by CastagnaIT** [comment]
Seem same problem of this Issue https://github.com/CastagnaIT/plugin.video.netflix/issues/390

where the InputStreamAddon for some unknown reason, it doesn't connect to the netflix service
you should take a test if you can do it, to see what comes out

Run Kodi, and resize Kodi window in one side screen
open the log and find the line: `[MSL] Picked Port: xxxxxxx`
and take note of the number

Now (with Kodi always opened) open the Terminal shell
and write:

`curl 127.0.0.1:xxxxxx`

replace the xxxxxxx with the number, then press enter
let me know what is the answer

**Comment by the-isz** [comment]
Hi @CastagnaIT,

it seems you are right, I can't get a connection either:

```
$ grep Picked\ Port .kodi/temp/kodi.log
2020-03-20 19:19:28.526 T:140644123137792    INFO: [plugin.video.netflix (0)] [MSL] Picked Port: 42513
$ curl localhost:42513
curl: (7) Failed to connect to localhost port 42513: Connection refused
```

**Comment by CastagnaIT** [comment]
it is possible that your loopback ip is different
give me from the Terminal the output of command
`ip add`

**Comment by the-isz** [comment]
Here you go:

```
$ ip add
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
```

**Comment by CastagnaIT** [comment]
mmh it is normal,
i don't know what's blocking communication...

you can try this, last resort..
[plugin.video.netflix_1.1.0_20200321_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4362697/plugin.video.netflix_1.1.0_20200321_test2.zip)

I don't think it will work, but we can try

**Comment by the-isz** [comment]
It works! Here's a log from the first successful run on this machine:

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4362749/kodi.log)
(couldn't use pastebin anymore due to increased file size)

When I use `curl localhost:<port>` now, it immediately exits without error.

Thank you! If I may ask: What was the problem? And do you need me to test anything else / provide more information?

**Comment by CastagnaIT** [comment]
I changed the ip address where the netflix addon servers are listening from 127.0.0.1 to 0.0.0.0
and luckily it works

But this also means that listening to the nf addon servers will no longer be limited to the internal network (loopback) but they could also accept connections from other IP addresses on the network, but if there is an active firewall, will never be reached (also because the ports are randomly assigned)

Seems to be a problem with the localhost loopback IP (127.0.0.1)
i am not an expert in network configuration, so i can't figure out what's not well-configured

I will add a switch in the Expert settings, in order to switch the IP of the servers as workaround

**Comment by CastagnaIT** [comment]
Please can you try also this?
[plugin.video.netflix_1.1.0_20200321_test3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4362904/plugin.video.netflix_1.1.0_20200321_test3.zip)

I tried to use the label "localhost" instead the resolved ip

**Comment by the-isz** [comment]
Thanks for the detailed explanation! I tried your latest experimental (test3), but unfortunately, it doesn't work.

I will start looking into network configuration for Archlinux and see if I can find a simple repro case and possible solutions.

Let me know if there's anything else I can do.

Again, thanks for your tremendous work!

**Comment by the-isz** [comment]
I wrote a simple Python script to isolate/reproduce the issue:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import socket
import sys

def main():
    parser = argparse.ArgumentParser(description="Simple TCP socket server")
    parser.add_argument \
        ( "-a", "--address"
        , dest="address"
        , help="Local address to bind to (default: 127.0.0.1)"
        , default="127.0.0.1"
        )
    parser.add_argument \
        ( "-p", "--port"
        , dest="port"
        , help="Local port to bind to (default: 0)"
        , default=0
        , type=int
        )
    args = parser.parse_args()

    with socket.create_server((args.address, args.port)) as sock:
        print("Listening on {}:{}".format(*sock.getsockname()))
        conn, address = sock.accept()
        print("Connection from {}:{}".format(*address))
        conn.close()

    return 0

if __name__ == "__main__":
    sys.exit(main())
```

I'm not quite sure, but I think I can reproduce our issue like this:

```
$ python ss.py -a localhost &
[2] 10360
Listening on 127.0.0.1:33377
$ curl localhost:33377
curl: (7) Failed to connect to localhost port 33377: Connection refused
$ curl 127.0.0.1:33377
Connection from 127.0.0.1:36308
curl: (56) Recv failure: Connection reset by peer
```

It seems that localhost is not properly resolved to 127.0.0.1 and produces the same issue as in kodi.

Using the resolved IP works, however.

Do you think this is a proper isolated repro case or is this something else?

**Comment by the-isz** [comment]
If the above is actually a repro, then I think I know what's wrong: localhost seems to be resolved to ::1 (IPv6) instead of 127.0.0.1 on my machine. Here's the extended sample:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import socket
import sys

def main():
    parser = argparse.ArgumentParser(description="Simple TCP socket server")
    parser.add_argument \
        ( "-a", "--address"
        , dest="address"
        , help="Local address to bind to (default: 127.0.0.1)"
        , default="127.0.0.1"
        )
    parser.add_argument \
        ( "-p", "--port"
        , dest="port"
        , help="Local port to bind to (default: 0)"
        , default=0
        , type=int
        )
    parser.add_argument \
        ( "-6", "--ipv6"
        , dest="ipv6"
        , help="Use IPv6 (default: False)"
        , default=False
        , action="store_true"
        )
    args = parser.parse_args()

    with socket.create_server \
        ( (args.address, args.port)
        , family=socket.AF_INET6 if args.ipv6 else socket.AF_INET
        ) as sock:
        print("Listening on {}:{}".format(*sock.getsockname()))
        conn, address = sock.accept()
        print("Connection from {}:{}".format(*address))
        conn.close()

    return 0

if __name__ == "__main__":
    sys.exit(main())
```

And the shell session:

```
$ python ss.py -a ::1 -6 &
[2] 11066
Listening on ::1:36319
$ curl localhost:36319
Connection from ::1:40704
curl: (56) Recv failure: Connection reset by peer
```

**Comment by the-isz** [comment]
Oh my god...

The whole problem is even more stupid. There was an error in my /etc/hosts! It bound localhost to 127.0.**1**.1 instead of 127.0.0.1!

I'm so so sorry for wasting your time! Thanks for all your help and patience. I'll definitely make a donation, you deserve it.

**Comment by CastagnaIT** [comment]
heh.. as i mentioned at first there was a misconfiguration...

sidenote, usually if is set the name 'localhost' the machine should resolve the address according to the network configuration v4 or v6,
then i think it is better if i change the IP with the name 'localhost'

now i think that the test3 should be working

**Comment by the-isz** [comment]
Yes, I can confirm that test3 also works now :)

**Comment by the-isz** [comment]
How can I send some tip money to you?

**Comment by CastagnaIT** [comment]
I don't have a direct link to donations, but you can use my website page that redirect to PayPal:
http://autorinomina.it/index.php/en/contribute/donate

Thank you very much!
