### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by yloose** [CastagnaIT/plugin.video.netflix#509]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: LibreElec 9.0
- Device model:  RaspberryPi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [x] OSX
* [ x] Raspberry-Pi
* [ ] Windows

### Describe the bug

When I open the add-on after doing the setup it just loads forever.

#### Steps to reproduce the behavior

1. Just opening the addon

### Debug log

The debug log can be found from this link:
https://pastebin.com/jcQutDRK

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
* [x ] I downloaded the repo as explained in the Readme and then installed it as a zip file.

**Comment by CastagnaIT** [comment]
The log file is wrong, instructions on the Readme

**Comment by yloose** [comment]
Sorry, I forgot to reboot the Pi.

**Comment by CastagnaIT** [comment]
I think first  you better uninstall addon with also user data,
then after update the Libreelec with the latest version 9.2.0

you have installed pycryptodomex?

**Comment by yloose** [comment]
Thank you very much for the fast replies. I can now login and see all the movies. I updated LibreElec and reinstalled your plugin. But I still can't watch any movies, because nothing happens after clicking on a movie. I still can freely browse the library of movies. Should I make a new issue?
Log: https://pastebin.com/qzNbnrA7

**Comment by yloose** [comment]
Thank you very much for the fast replies. I can now login and see all the movies. I updated LibreElec and reinstalled your plugin. But I still can't watch any movies, because nothing happens after clicking on a movie. I still can freely browse the library of movies. Should I make a new issue?
Log: https://pastebin.com/qzNbnrA7

**Comment by CastagnaIT** [comment]
the log is wrong and incomplete, If i don't have right log, i can't verify
instructions in the Readme

you didn't answer my question:

> you have installed pycryptodomex?

**Comment by CastagnaIT** [comment]
Closed due to inactivity
