### ISSUE TITLE
Audio Described Genre with Date Added Sorting

### ISSUE THREAD

**Issue by kwizrr** [CastagnaIT/plugin.video.netflix#51]
First let me say how much I love your plug-in. I'm visually impaired and having the ability to access Audio Described movies and TV shows being offered by NetFlix through my Kodi v18.1 setup is so darn convenient.

http://www.acb.org/adp/netflix.html

I don't even have to manually select the Audio Described stream, it comes up playing automatically when I select content that has an AD audio track available. Guess because I have the "Accessibility" option set to "Yes" under Kodi -> Settings -> Player Settings -> Accessibility -> Prefer audio stream for the visually impaired?

I'm hoping you can add an "Audio Described" option under the Genre menu for the NetFlix plug-in?

https://www.netflix.com/browse/audio-description

Also is there anyway to make the plug-in display all found listings sorted by date added: not alphatize them? Would make it much easier to locate any newly added Audio Described content for they would be placed at the very top of the listings.

I think having it behave this way for the "Recently Added" menu option would make a llot more sense too.

If some users prefer having the list alphabetized, how about providing a toggle under settings to sort in either Date Added, or Alphabetized.

Again I'm using the latest build of Kodi v18.1 under Windows 10 1809.

Thanks again for the fantastic plug-in and all of your hard work.

**Comment by CastagnaIT** [comment]
I'm glad you like this addon,
as soon as i can, verify the option for visually impaired

if you install the latest "dailybuild" version,
you can find in the addon settings, on the page "views",
the possibility of changing the sort order of the lists, you can try "Year released" or "Suggestions for you"

the new addition of the menu i put it in queue for future implementations, before this there are other priorities

**Comment by kwizrr** [comment]
Thanks for the rapid reply to my request. I do understand the needs of the many, outweigh the needs of the few. Just  your having the willingness to make these changes is grately appreciated.

I'm off to install the "DailyBuild" version. You have a good one!

**Comment by kwizrr** [comment]
Sorry to bother you again. Where can I download the latest "DailyBuild" version that contains the view changes? Can't seem to locate it. Thanks.

**Comment by notoco** [comment]
In the same place where the beta version:
![obraz](https://user-images.githubusercontent.com/36659110/56013590-c98f5b80-5cf1-11e9-9097-2dd86bb6f0a9.png)
http://www.mediafire.com/folder/vifnw8ve44bi7/KodiNetflixAddon

**Comment by Dnkhatri** [comment]
> In the same place where the beta version:
> ![obraz](https://user-images.githubusercontent.com/36659110/56013590-c98f5b80-5cf1-11e9-9097-2dd86bb6f0a9.png)
> http://www.mediafire.com/folder/vifnw8ve44bi7/KodiNetflixAddon

He said he was visually impaired he probably won't be able to see the large yellow arrow you have pointed to the location in the image.

**Comment by notoco** [comment]
OMG. I have just read and noticed, of course sorry. I hope I did not offend you.

**Comment by kwizrr** [comment]
LOL! No problem. Appreciate the posting of the MediaFire link. Have the file now.

**Comment by CastagnaIT** [comment]
it's your turn, as i promised you i added the Audio Description menu for people with visual impairments,
the order of the video list can be configured from the addon settings, Views.
I hope you enjoy it.

To try it now without waiting for a new release i write here the link to download easly the the update:
[LINK CLICK HERE TO DOWNLOAD](http://www.mediafire.com/file/ba27rdm0o2z52w6/plugin.video.netflix_0.14.0_20190420.zip/file)

**Comment by kwizrr** [comment]
Thanks for taking the time to not only review my concerns, but implement changes (Specifically for visually impaired users) into your already excellant add-on.

Great job!
