### ISSUE TITLE
Error when select profile

### ISSUE THREAD

**Issue by xv007** [CastagnaIT/plugin.video.netflix#511]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: Libreelec 9.2
- Device model:  RPI3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

After loging, when select some profile, it crashes, but it does not crash with all profiles 

#### Expected behavior

After loging and select a profile, it should not crash and go to menu.

#### Actual behavior

After loging, when select some profile, it crashes, but it does not crash with all profiles 

#### Steps to reproduce the behavior

1. Open Netflix Add-on
2. Select a profile
3. Crash.

### Debug log
The debug log can be found from this link: https://we.tl/t-zYOqYCtEZd

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
I need more information, please install this modified addon, and get a new log after given error
[plugin.video.netflix_1.0.0_20200310.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4314365/plugin.video.netflix_1.0.0_20200310.zip)

**Comment by xv007** [comment]
Hi,

You'll find the new log attached.
Is it ok ?

Thanks,

Xavier

Le mar. 10 mars 2020 à 20:29, Stefano Gottardo <notifications@github.com> a
écrit :

**Comment by CastagnaIT** [comment]
where is?🤔

**Comment by CastagnaIT** [comment]
Fixed,
you can download the updated addon in the Daily Build, link in the Readme
