### ISSUE TITLE
MSLError: Request rejected by key exchange service

### ISSUE THREAD

**Issue by andrzejgluch** [CastagnaIT/plugin.video.netflix#516]
#### Your Environment
- Netflix add-on version: kodi 18.6 / plugin.video.netflix 1.0.0
- Operating system version/name: Android 7.1.1 API level 25, kernel: Linux ARM 32-bit version 4.4.3+
- Device model:  TV MANTA 40LFA19S

Used Operating system:
* [ x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Error appears while starting kodi or trying play a movie - MSLError: Request rejected by key exchange service.
Add-on installed from official repository.
Please help thank you

#### Expected behavior
Play a movie

#### Actual behavior
MSLError: Request rejected by key exchange service

#### Steps to reproduce the behavior
1. Install add-on from repository 
2. Login to netflix account - successful
3. Try play a movie (or restart)  

### Debug log

The debug log can be found from this link: https://drive.google.com/file/d/11Jfn0a6NUWT9zbwt3FvV1Ywbfsd8dFRt/view?usp=sharing

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Uninstall the addon with also user data
and try this:
[plugin.video.netflix_1.0.0_20200313.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4329178/plugin.video.netflix_1.0.0_20200313.zip)

let me know

**Comment by andrzejgluch** [comment]
The same MSLError: Request rejected by key exchange service
Log from this version: https://drive.google.com/file/d/10AIE6x_q07AcQU_TyAW6UjEtO0lFMgYJ/view?usp=sharing

**Comment by CastagnaIT** [comment]
open the official netflix app, go to settings and take a screenshot of the ESN
attach image here by censuring some last characters

**Comment by andrzejgluch** [comment]
![obraz](https://user-images.githubusercontent.com/62137893/76624584-d934a700-6535-11ea-8ba0-5920c8058a67.png)

**Comment by CastagnaIT** [comment]
now please install "DRM Info" app and take a screen shot of page with widevine drm infos
there's something weird about the ID

**Comment by andrzejgluch** [comment]
![obraz](https://user-images.githubusercontent.com/62137893/76628412-f751d580-653c-11ea-994f-f63c789fd1d0.png)
![obraz](https://user-images.githubusercontent.com/62137893/76628485-13557700-653d-11ea-83cb-3b34b5d8bc0a.png)

**Comment by CastagnaIT** [comment]
Uninstall again as before,
and try this:
[plugin.video.netflix_1.0.0_20200313_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4330280/plugin.video.netflix_1.0.0_20200313_test2.zip)

**Comment by andrzejgluch** [comment]
Thanks, but error the same - https://drive.google.com/file/d/1WQCzctRFD8kBTfLcw_xqtjiYpeUZLQ1n/view?usp=sharing

**Comment by CastagnaIT** [comment]
why you use an old version of official Netflix app?

**Comment by andrzejgluch** [comment]
This version was originally installed when I bought the TV. The support for this application is strange and hard so I try with kodi and add-on.

**Comment by CastagnaIT** [comment]
I don't know how to help you

because there is an HDCP value marked as "Disconnected"!?! that this should not be missing,
instead should be "Unprotected" or "1.4" or "2.2"

DRM Info show a system ID of 10839,
but the official Netflix app show a system ID of 4445,
this means that the official old app has internally changed?! the system ID, for some unknown reason

As far as i know the system ID 4445 is often used on widevine L3 devices and not L1 devices, as reported by nf app of your device.
In fact the official app shows an ESN with an format used in the L3 devices.

All this makes me consider only one thing,
that your device _might have a false_ widevine certification

the only thing you can try is to enter the ESN of the official app,
in the expert setting of the addon, in the field "Manual ESN"

**Comment by andrzejgluch** [comment]
Full ESN or "NFANDROID1-PRV-B-L3-REALTSMART=TV-4445-" only?

**Comment by CastagnaIT** [comment]
complete if all the characters can fit, otherwise as you wrote here

**Comment by CastagnaIT** [comment]
Closed case motivation currently not solvable
