### ISSUE TITLE
MSLError: Previous credentials are no longer valid

### ISSUE THREAD

**Issue by sjuk** [CastagnaIT/plugin.video.netflix#518]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: Ubuntu 18.04.4 LTS | OSMC
- Device model: x86_64 | armhf

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

Opening Netflix addon works.
Browsing my list works.
Starting video shows: "Previous credentials are no longer valid...".
In result no Netflix video starts to play.

#### Expected behavior

Video plays.

#### Actual behavior

Video does not play.

#### Steps to reproduce the behavior

1. Open Netflix addon
2. Browse my list
3. Start any video

#### Possible fix

1. Reset password on Netflix website
2. Deinstall Netflix addon
3. Install Netflix addon

### Debug log

The debug log can be found from this link: [https://paste.kodi.tv/daharukugu.kodi](https://paste.kodi.tv/daharukugu.kodi)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

At first there were similar symptoms as described in **Can't login on Netflix plugin - Incorrect password** #502, but only on my second device (Raspberry PI 3 with OSMC).
After trying to get Netflix addon getting back to work on the RPI3 Netflix forced me to reset my password (there was an email notification about that).
After resetting my password my main media center pc (from this report) stopped working too.
I already had a look at **Netflix plugin won't play videos** #507.
Perhaps it's somehow related, but it seems to be another issue.
As next step I started debugging on my main media center pc and began to write this report.
Then I tried the steps described as possible fix with my Raspberry Pi 3, and it worked.
Then I did the same with my main media center pc, and it worked.

_I hope this will help improving the addon and help anyone else to get a workaround._

#### Screenshots

![screenshot002](https://user-images.githubusercontent.com/5033784/76684912-f5a51200-660f-11ea-8922-4d43a758d7df.png)

**Comment by CastagnaIT** [comment]
Finally someone who publishes a log.... everyone complaining but no one cooperating to help

in summary you removed the addon on all devices, reset the password and then reinstalled the addon on each device

the problem seems to have happened because of the RPI,
the RPI is was always turned on 24/24h 7/7days ?

**Comment by sjuk** [comment]
I hope it won't happen again. But if so I will report it. But next time I will choose the log file from RPI3 before reinstalling the addon.

Did you geht any useful information from the log file of the main media center?

**Comment by CastagnaIT** [comment]
not much help the log of htpc

when RPI stopped working for the problem with password,
while you reset the netflix password to restore RPI:
were you already using netflix on Kodi HTPC while resetting the password?

**Comment by sjuk** [comment]
Not exactly. I will try to give you the events and steps happening in a timeline.

1. I watched Netflix on the **htpc**.
2. My family reported a problem with login to Netflix addon on **rpi3**. #502
3. I removed the addon from **rpi3** and installed it again, but that didn't help.
4. While searching for matching issues on github I got an email from Netflix to reset my password.
5. I reseted the password and tried it on **htpc** and addon stops playing videos. #518
6. I enabled debug logging and raised log level of the addon to verbose on **htpc**. I also had to disable any other addon because they would produce too many debug information to fit into a hastebin.
7. I restarted kodi and reproduced the issue on **htpc**. I copied the log file to hastebin and created a screenshot.
8. While creating the report I had the idea to try the new password on the **rpi3**, and surprise it worked like a charm (login & playing video).
9. Now I tried the workaround with the **htpc**. I removed addon and installed it again. After giving user name and the current password Netflix was working again like a charm (login & playing video). Important: I did not reset the password again. I only reset it in step 5.
10. I disabled the debug logging on **htpc** and activated all addons.

I hope this will help. Please don't hesitate to ask any further question.

**Comment by sjuk** [comment]
By the way. Do you know what the "2 of 8" under the the issue stands for?
![Bildschirmfoto von 2020-03-14 19-51-29](https://user-images.githubusercontent.com/5033784/76688472-5db62100-662d-11ea-8da2-527d3ae25ec0.png)

**Comment by CastagnaIT** [comment]
thanks for your very detailed useful explanation

the numbers should be the project tasks where the issue is attached,
can be used for organize the tasks to do with more devs and organize the project stages,
i do not really use it

**Comment by CastagnaIT** [comment]
This error however, is correct
in your case when the password reset happened, the old and new access credentials got mixed up
will be better investigated for the problem of password reset
