### ISSUE TITLE
Blank screen after Fetching content

### ISSUE THREAD

**Issue by tonytozoo** [CastagnaIT/plugin.video.netflix#519]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: OSMC 2020.01-2
- Device model:  RPi 3b+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

When I lunch Netflix, I'm able to open my profile, but when I click My List, or any other button, instead of a list of the playable items I get a blank screen

#### Expected behavior

Play the videos
#### Actual behavior

Got a blank screen instead of a list of episodes
#### Steps to reproduce the behavior

1. Log-in
2. Select my own profile
3. click My List
4. Blank Screen

### Debug log

https://paste.kodi.tv/ilayonafiq.kodi
 

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

https://imgur.com/F8XeVYI

**Comment by CastagnaIT** [comment]
The log is incomplete,
how to in the Readme

if you use an unofficial Skin it could be a skin problem, then change skin

**Comment by tonytozoo** [comment]
I was sure it was set on "Verbose", here is the new one https://paste.kodi.tv/imiyaranov.kodi
I'm using the OSMC official skin, I've tried to change it and it actually works, I'll post it on OSMC then

thanks, it's already a big step

**Comment by tonytozoo** [comment]
I reinstalled the whole OSMC on a new SD card, eveything works now. :\

**Comment by CastagnaIT** [comment]
i am happy for you
maybe the other sd is defective and some data was corrupted
would not be the first time on RPI
