### ISSUE TITLE
Coercing to unicode Error.

### ISSUE THREAD

**Issue by spikerguy** [CastagnaIT/plugin.video.netflix#520]
#### Your Environment
- Netflix add-on version: 1.0
- Operating system version/name: Manjaro Linux - Arch - Aarch64
- Device model:  Pine64 PineBook Pro

Used Operating system:
* [X] Linux - Aaarch64

### Describe the bug
Coercing to unicode error while uncompressing Widevine CDM

#### Expected behavior
After uncompressing it tries to run some python package and fails, Assuming I have python2.7 and python3.8 installed.

#### Your Environment
Manjaro Linux with Kde Plasma compiled kodi for aarch64 using gles and panfrost driver. Video playback is quite smooth but trying to get netflix to work. 64bit userspace is used.

#### Steps to reproduce the behavior

1. Installed plugin.video.addon
2. Logged in to Netflix and tried playing a movie, this ask for permissions to download Chrome OS image and then after downloading it tries to uncompress it.
3. While uncompressing I get the Coercing to unicode error and the uncompressing box stays on until I close kodi.

#### Possible fix
Looks like a python issue.

### Debug log
The debug log can be found from this link:
https://pastebin.com/6zb7S3G1

#### Installation
Installed this plugin from the git wiki.

#### Screenshots
![Uncompressing](https://user-images.githubusercontent.com/48839029/76691692-8efb1500-665e-11ea-8c11-96c11173b91a.jpg)

![IMG_Coering](https://user-images.githubusercontent.com/48839029/76691689-8c98bb00-665e-11ea-888c-a10bb0ef059b.jpg)

**Comment by CastagnaIT** [comment]
inputstreamhelper is not netflix addon,
you have to open issue in to the right addon github
