### ISSUE TITLE
ERROR: CDVDVideoCodecAndroidMediaCodec::GetOutputPicture unknown index(-10000)

### ISSUE THREAD

**Issue by dorajistyle** [CastagnaIT/plugin.video.netflix#524]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: 
- Device model:  
Beelink GT King Pro

Used Operating system:
* [ X ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

ERROR: CDVDVideoCodecAndroidMediaCodec::GetOutputPicture unknown index(-10000)

I got an error message while attempting video play.

#### Expected behavior

It play smoothly without any problems.

#### Actual behavior

Video did not played.

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
ERROR: CDVDVideoCodecAndroidMediaCodec::GetOutputPicture unknown index(-10000)

#### Installation
* [ x] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

When I turned off the hardware acceleration, I can listen audio, but when it turned on the error message popped up and both video and audio not work.

#### Screenshots

![DSCPDC_0000_BURST20200316000251954](https://user-images.githubusercontent.com/1202809/76712823-443fd280-671c-11ea-9165-64bfcade8bf0.JPG)

**Comment by CastagnaIT** [comment]
the one specified is not a problem of this addon
already other users have complained that this device does not work

your device has a firmware problem or something inherent
then i can not do anything
