### ISSUE TITLE
Asian subtitle show %lrm; letter in Netflix addon at COREELEC 9.0

### ISSUE THREAD

**Issue by dryusc** [CastagnaIT/plugin.video.netflix#526]
#### Your Environment
- Netflix add-on version: <1.0.0>
- Operating system version/name: <COREELEC 9>
- Device model:    <Tanix TX9 Pro>

Used Operating system:
* [ ] Android
* [ ] iOS
* [V] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

Thank you for your good work.

Asian subtitle add %lrm; letter in Netflix at COREELEC running.
Android & Windows works very well.

If you revise the netflix Add-on.
Please correct this problem.

Thanks a lot for your work.

**Comment by CastagnaIT** [comment]
This is not nf addon issue but CoreElec/Kodi core issue or InputStream Addon issue
most likely CoreElec and its components are not yet available with the latest released versions

**Comment by dryusc** [comment]
Thank You..

I always love your add on.
Have a good luck.
