### ISSUE TITLE
Infinite loading when launching plugin

### ISSUE THREAD

**Issue by Jean-PhilippeD** [CastagnaIT/plugin.video.netflix#527]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: Raspbian buster
- Device model:  RPI 3b

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

When starting the plugin, I got an infinite loading and I never got the home page.
I'm successfully loged in with my credential as I get the message before the inifinite loading.

#### Expected behavior

When starting the plugin, I would expect to get the profile page.
#### Actual behavior

Once I start the app and I filled the credentials, I got the spinner telling it's loading but I never got the home page with my profiles

#### Steps to reproduce the behavior

1. I upgraded my kodi to kodi 18.5 
2. I uninstalled netflix plugin and data (through GUI)
3. Installed netflix 1.0.0
4. I start plugin
5. I fill the credentials
6. And then I got inifinite loading

### Debug log

The debug log can be found from this link:
https://pastebin.com/05Ta0QwG

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
the log is wrong and incomplete, instruction in the Readme

I also need to know if you are using amazon addon

**Comment by Jean-PhilippeD** [comment]
Sorry I had not put the plugin in verbose mode.

Here is a new link:

https://pastebin.com/Lras567C

Tell me if it's enough.

And I don't use Amazon addon.

**Comment by CastagnaIT** [comment]
now is right but is not full,
i think it is better you reboot Kodi or the device before take a new log

**Comment by Jean-PhilippeD** [comment]
Do you want the whole log from startup ? even with the logs from the scan of my libraries ?

**Comment by CastagnaIT** [comment]
what is the problem.. you can temporary disable the scan

**Comment by Jean-PhilippeD** [comment]
Here is the full log

https://paste.kodi.tv/oqitegasap.kodi

**Comment by CastagnaIT** [comment]
Please try to install this _test1_, then only if works try also the second one (dailybuild) and let me know if the daily build works or not

[plugin.video.netflix_1.0.0_20200320_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4358529/plugin.video.netflix_1.0.0_20200320_test1.zip)

[plugin.video.netflix_1.0.0_20200320_dailybuild.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4358528/plugin.video.netflix_1.0.0_20200320_dailybuild.zip)

**Comment by Jean-PhilippeD** [comment]
It does not work

**Comment by CastagnaIT** [comment]
can you try to set another Kodi Skin?
some user OSMC has solved it this way for a bug in the skin or kodi i do not know

**Comment by Jean-PhilippeD** [comment]
You're right, I changed the theme and it's working !

**Comment by CastagnaIT** [comment]
can you say the name of problematic skin?

**Comment by Jean-PhilippeD** [comment]
Pellucid

**Comment by CastagnaIT** [comment]
thanks

**Comment by Jean-PhilippeD** [comment]
Thanks for your help !

**Comment by quentinus95** [comment]
@CastagnaIT do you have a solution to allow using this Addon with Pellucid skin?

**Comment by CastagnaIT** [comment]
this seem to be a Skin bug

there are no problems in addon implementation
since the `xbmcplugin.endOfDirectory` is called correctly,
and the script finish its execution correctly as:
`CPythonInvoker(10, ***\portable_data\addons\plugin.video.netflix\addon.py): script successfully run`

this means that the data has already been read from addon, but the Skin dont update the GUI or do something wrong with Kodi
i have no idea

you have to report the problem to the Skin developers, i can do nothing from addon side
