### ISSUE TITLE
Plugin not working on retropie 4.5.17

### ISSUE THREAD

**Issue by joaovlg** [CastagnaIT/plugin.video.netflix#529]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: Retropie 4.5.17
- Device model:  RPI 3b+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe the bug

After start the plugin on Kodi 18.2 (retropie 4.5.17) the follow message pops-up: "The background services may not yet be available if you just started kodi the addon. In this case, try again in a moment."

#### Expected behavior

When started the plugin i expected it to show the login page.

#### Actual behavior

The plugins shows the follow message: "The background services may not yet be available if you just started kodi the addon. In this case, try again in a moment."

#### Steps to reproduce the behavior

1. I installed retropie 4.5.1
2. I updated it to version 4.5.17
3. I installed Kodi
4. I added CastagnalT repository from a usb flash driver
5. I installed Netflix 1.0.0
6. And then i receive the error message

### Debug log

The debug log can be found from this link:
https://pastebin.com/bm02UC2r

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by arvvoid** [comment]
Hello, from the log looks like you are missing the pycryptodomex dependency, on most Linux systems have to be installed manually.

You can try from command line:
```
sudo apt update
sudo apt install build-essential python-setuptools python-pip
sudo pip install wheel pycryptodomex
```

**Comment by joaovlg** [comment]
Hello there! Thanks for you help. After i installed the libraries that you suggested it worked until a new error message appeared. After the Widevine CDM and chrome os libraries are installed a pop-up message asks for the following libraries: libnss3.so libnssutil3.so libnspr4.so 

If anyone is having trouble with those libraries i found the solution here: [https://github.com/asciidisco/plugin.video.netflix/issues/489](url)

So far its only necessary to use this command: `sudo apt install libnss3`
After that everything works normally.

**Comment by CastagnaIT** [comment]
Thanks i will add to the Wiki
