### ISSUE TITLE
Background services are not starting

### ISSUE THREAD

**Issue by Vitocorl** [CastagnaIT/plugin.video.netflix#530]
#### Your Environment
- Netflix add-on version: 1.1.0
- Operating system version/name: Android 9
- Device model:  Xiaomi Mibox S

Used Operating system:
* [ ] Android

### Describe the bug
Background services are not starting at all. I have uninstalled the plugin (deleting all settings), re-installed and the same problem occurs.
Log file: https://paste.kodi.tv/hitunigizu.kodi

**Comment by CastagnaIT** [comment]
The log is without debug info, the instructions are in the Readme

Then try to do what described in this last post and report:
https://github.com/CastagnaIT/plugin.video.netflix/issues/527#issuecomment-601587133

**Comment by Vitocorl** [comment]
I finally reached at thee most curious solution, i thought to clear the thumbnail cache of Kodi, went into  Android/data/org.xbmc.kodi/files/.kodi/userdata/Thumbnails and deleted every folder in it...
I then restarted Kodi and Netflix backround services stared normally! I cannot explain it further, i am thinking a corrupted thumbnail was preventing the services from starting....

**Comment by CastagnaIT** [comment]
Thanks for the information, this is really weird
