### ISSUE TITLE
The background service may not yet be available if you just started Kodi

### ISSUE THREAD

**Issue by mrkapqa** [CastagnaIT/plugin.video.netflix#532]
## Bug report

https://paste.kodi.tv/aworoniqic.kodi

#### Your Environment
- Netflix add-on version: 

1.1.0
- Operating system version/name: 

Devuan Beowulf (Debian 10)

- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Actual behavior

Netflix Add-on Error upon Starting

**Comment by mrkapqa** [comment]
solution was found here

https://github.com/asciidisco/plugin.video.netflix/issues/665

**Comment by CastagnaIT** [comment]
this sound more like a hack
it looks like you installed a wrong module

I think it would have been better try uninstall all crypto modules installed
and install again pycryptodomex

**Comment by mrkapqa** [comment]
could be,
installed kodi + kodi-pvr-iptvsimple or similar through deb-multimedia.

did not install any crypto modules by myself, maybe they got added in the process?

**Comment by CastagnaIT** [comment]
i do not know the others addon i use only netflix and youtube

**Comment by CastagnaIT** [comment]
since you found a solution anyway,
i close this issue

**Comment by Nears** [comment]
> 
> 
> this sound more like a hack
> it looks like you installed a wrong module
> 
> I think it would have been better try uninstall all crypto modules installed
> and install again pycryptodomex

Hi, i am facing the same warning after an installation of Netflix on my Kodi (Raspbian). On my Kodi in Windows everything is fine. How can I fix this issue? What exactly do you recommand?

**Comment by Nears** [comment]
sudo apt install build-essential python-pip python-dev libffi-dev libssl-dev libnss3
sudo pip install setuptools wheel pycryptodomex

Solved it for me. Sorry for the previous post :-)
