### ISSUE TITLE
Playback error - This title is not available to watch instantly

### ISSUE THREAD

**Issue by guinuxbr** [CastagnaIT/plugin.video.netflix#533]
#### Your Environment
- Netflix add-on version: 1.1.0
- Operating system version/name: LibreElec 9.2.1
- Device model:  Raspberry Pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

I cannot play any video. I've tried many of my Netflix and always receive the same error:
**Playback error - This title is not available to watch instantly. Please try another title**

#### Expected behavior

The videos should play normally.

#### Actual behavior

I always receive an error as described above.

#### Steps to reproduce the behavior

1. Install the latest version (at the time of writing this is the 1.1.0) of the extension on top of LibreElec 9.2.1 in Raspberry Pi 4
2. Open the extension and fill the login details
3. Try to play any content

#### Possible fix

I have no idea. :-(

### Debug log

The debug log can be found from this link:
Here is the log: https://paste.kodi.tv/qupomefozi.kodi

### Additional context or screenshots (if appropriate)
Here is the screenshot of the error: https://imgur.com/a/97pc0uZ

#### Installation
I've followed the install instruction available at: https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon
I'm not sure of what I should mark here.
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

What I already have tried to:

- Enable VP9 profiles with no result.
- Reset ESN with no result.
- Purge in-memory cache with no result.
- Purge in-memory and on-disk cache with no result.

#### Screenshots

Here is the screenshot of the error: https://imgur.com/a/97pc0uZ

**Comment by CastagnaIT** [comment]
Have you read wiki?
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ

**Comment by guinuxbr** [comment]
Yes, sorry I forgot to mansion.
I've tried to log-out/log-in with no result.
I've tried reinstalling Widevine CDM with no result.

Is there any other configuration that I should try?

Thank you for your quick answer.

**Comment by CastagnaIT** [comment]
unfortunately i can't do anything
these cases are very rare and i can't identify the problem

only two thing
-if you have a PIN you can try disable it
-if you have set lower stream quality in the website account, change it to the Auto

**Comment by guinuxbr** [comment]
I have tried this last two things with no success.

The good and strange news is that using RaspEX (http://raspex.exton.se/) that is based on Debian Buster I can play the videos normally.
I've received a warning about update Widevine but I didin't and everything works as expected.

Anyway, I don't know why. 
Thank you for your attention.
