### ISSUE TITLE
Netflix Addon Giving Errors in Kodi

### ISSUE THREAD

**Issue by Dittizardichu** [CastagnaIT/plugin.video.netflix#538]
I am attempting to use this with the latest version of Kodi (I believe 18.6) on a Raspberry Pi 3 B+. However, after installing the Netflix addon, I am getting a notification telling me to check the log.

Here is a link to the log: https://pastebin.com/zfyM4C6D

Any help would be appreciated.

**Comment by notoco** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon#installing-on-raspbian-raspberry-system

**Comment by CastagnaIT** [comment]
closed for inactivity
