### ISSUE TITLE
Resume Positions - Feature Request

### ISSUE THREAD

**Issue by vladashram** [CastagnaIT/plugin.video.netflix#54]
- [ *] feature request

The ability to resume content watched from at least Kodi would be great, to be able to continue a TV series or a movie where you stopped watching would increase the flow when you add the Netflix content to your library. It would be better if it could somehow sync with the Resume Position on the Netflix site/app as well, but that seems much more challenging.

**Comment by CastagnaIT** [comment]
the resume in kodi is working properly, watched and resume point in synchronization with netflix app or site it is not possible at the moment

**Comment by vladashram** [comment]
Interesting, it currently isn't functioning for me. Kodi appears to recognize where I last left off when watching a netflix movie previously, but when I attempt to play it the movie always restarts.

**Comment by CastagnaIT** [comment]
ah now i understand it's a known error of kodi not of addon, i can't do anything
