### ISSUE TITLE
Addon Signals Time Callout on Kodi 18.2

### ISSUE THREAD

**Issue by joaovlg** [CastagnaIT/plugin.video.netflix#541]
#### Your Environment
- Netflix add-on version: 1.1.1
- Operating system version/name: Retropie 4.5.17
- Device model:  Raspberry Pi 3B+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe the bug

After clicking on Netflix addon to login the follow messages pops-up: Exception: Addon Signals Time Callout

#### Expected behavior

It's supposed to show me the login panel where i can select my account

#### Actual behavior

It gives me the message reported

#### Steps to reproduce the behavior

1.I login o Retropie
2.I open Kodi
3.I go to addon section
4.I started netflix addon
5. the message error pops-up

### Debug log

The debug log can be found from this link:
https://pastebin.com/6JK2UVYw

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by joaovlg** [comment]
Now it's giving again this error: The background service may not yet be available if you just started Kodi - And i tried to install again all the libraries necessaries for raspberry but they are already installed so, i do not know what to do.

**Comment by CastagnaIT** [comment]
wrong debug info in log
read istructions on Readme

**Comment by huyld** [comment]
Hi @joaovlg, have you tried the [Wiki FAQ](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ#the-error---addon-signals-call-timeout)? `Enable IPC over HTTP` did resolve the `Addon Signals call timeout` exception in my case.

**Comment by CastagnaIT** [comment]
closed due to inactivity
