### ISSUE TITLE
Bad display of watched/unwatched list

### ISSUE THREAD

**Issue by Badsheep** [CastagnaIT/plugin.video.netflix#542]
#### Your Environment
- Netflix add-on version: 1.1.0
- Operating system version/name: KODI 18.4
- Device model:  iMac

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ X] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

The watch/unwatch list in the plugin seems not to work well : 

- I watch the episod 8 of a serie (see the screenshots to understand the example)
- the episod ends, closes and the display comes back to the list of the season 2 (picture 1)
   The list of watched episods is correct
- I go one folder upper, on the page where there is the list of the seasons (hope I'm clear, sorry my English is not good...)
- I select "season 2" and I'm back on the page where I was before : the list isn't good anymore (Picture 2)

### Debug log

How could I give you an interesting log ?
I have to watch an entire episod to reproduce the bug and my log would be gigantic ??

### Screenshots

![Picture-1](https://user-images.githubusercontent.com/46049911/77847864-76434100-71c0-11ea-9ad6-3a61804d90e8.jpg)

![Picture-2](https://user-images.githubusercontent.com/46049911/77847866-7b07f500-71c0-11ea-959e-9eda809a6e24.jpg)

### AND once again thanks for your work and I hope the situation is not too bad with that f*** virus... salutations from another confined guy.

**Comment by Badsheep** [comment]
Of course I use the "Synchronize the watched status of the videos with Netflix" option.

**Comment by CastagnaIT** [comment]
As described in the function name and in the wiki this is a WIP / TEST feature:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/Sync-of-watched-status-with-Netflix

this report is not useful
the problems are already known

**Comment by Badsheep** [comment]
Ok I didn’t saw.
