### ISSUE TITLE
Widevine Download stops and error

### ISSUE THREAD

**Issue by adrianhartz1** [CastagnaIT/plugin.video.netflix#544]
#### Your Environment
- Netflix add-on version:  netfkix 1.1.1
- Operating system version/name: retropie kodi
- Device model:   Raspberry pi 3b

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X Raspberry-Pi
* [ ] Windows

### Describe the bug

When i try to Install widevine 
IT Starts to Download but sends an error and stops directly
I followed the Instruktionen Here but when i start a movie it says i have to Install widevine, so i so but then Error occurs.

I know i need the Log where do infind IT?

I am New Here can Simeone Help?

#### Expected behavior

Download Install widevine
#### Actual behavior

Error message
#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4407616/kodi.log)
#### Installation
* [X) I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
this is not an error of Nf addon
you have to report to inputstreamhelper
