### ISSUE TITLE
The Netflix Addon just crash after starting it

### ISSUE THREAD

**Issue by Fablo020** [CastagnaIT/plugin.video.netflix#545]
#### Your Environment
- Netflix add-on version:  1.1.1
- Operating system version/name: 
Windows 10 Pro x64 - 1909 (18363.720)
- Device model:   PC x64- i5-6500, GTX 970, 16GB DDR4 RAM

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows 10 Pro x64 - 1909 (18363.720)

### Describe the bug

Since about a week i cant use my Netflix on Kodi anymore.
After the first start i can enter my username and password for Netflix and then it just crash. After every start it wont even let me do anything and just crash. After several tries i even could choose my profile but then it just crashed like before.

#### Expected behavior

Its supposed to open the Addon.

#### Actual behavior

It just crash after starting the Addon

#### Steps to reproduce the behavior

1. In my case just open the app 
2.
3.

#### Possible fix

I tried like everything. I installed multiple versions of Kodi. e.g. 18.6 (My Main Kodi with the problem), 18.7 several versions and even 19 and i still got this bug with all versions. I switched from Portable to "Normal" tried to delete all files and even tried to downgrade the dependencies for that Addon. They were all updated before. I tried multiple locations on 2 different HDDs.

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/ziyelocaqi.kodi

#### Installation
* [ ] I'm using a different source 
I used the CastagnaIT Repo and tried all versions (1.1.1, 1.1.0, 1.00)
Then i tried to download the Addon from Github. 
Then i just cloned the whole files from Github and installed it. 
Before i switched the versions i deleted the current Kodi installations and all files eg. userdata etc.
* [ ] I'm using other Netflix Repo

**Comment by CastagnaIT** [comment]
i see that twitch going in error before try disable it

but also see that the IPC http requests to server not reply seem blocked
this can means an external influence to Kodi to be verify:
-VPN or Proxy to disable it
-firewall
-internet security
-wrong network configuration
-wrong host file configuration

or other things that i do not know
unfortunately i can't help you
