### ISSUE TITLE
[Bug]Enable UpNext not possible

### ISSUE THREAD

**Issue by shinji95** [CastagnaIT/plugin.video.netflix#547]
Your Environment

    Netflix add-on version: 1.1.1
    Operating system version/name:
    Windows 10 Pro x64 - 1909 (18363.720)
    Device model: PC x64- i5-6500, GTX 970, 16GB DDR4 RAM

Used Operating system:

Android
iOS
Linux
OSX
Raspberry-Pi

    Windows 10 Pro x64 - 1909 (18363.720)

Describe the bug

For some reason I cant enable the UpNext Option from the addons settings. The Up Next addon is installed and works correctly for library stuff but the netflix addon cant seem to find it somehow. What am I missing here?
Bug report

Actual behavior

The Lable is grey i can´t select it.

Possible fix

I tried reinstalling both the Kodi player and the UpNext addon on a fresh kodi installation but it made no difference.

Screenshot:

https://imgur.com/a/bLvflw2

**Comment by viking1304** [comment]
I have exactly same issue on Android STB, so it's not OS related.

**Comment by fraxinus-e** [comment]
I Also have the Exact issue cannot tick to enable Kodi running on Raspbian

**Comment by vteccorp** [comment]
Same on my side... on Android and CoreELEC.

**Comment by CastagnaIT** [comment]
the menu disabled should happen only when UpNext addon is disabled
seem a bug introduced inside Kodi builds
i can only remove the check

**Comment by Xamyrz** [comment]
Same issue on LibreELEC on RPI 3

**Comment by CastagnaIT** [comment]
i have removed the check,
the updated build is in DailyBuild folder link
or you have to wait the future next release

**Comment by Error-101** [comment]
I think the issue was the check. According to the [docs](https://kodi.wiki/view/List_of_boolean_conditions#System)`System.AddonIsEnabled(service.upnext)` is a v19 addition so isn't available on Leia

**Comment by CastagnaIT** [comment]
The new release is out
This Issue can be closed
