### ISSUE TITLE
 Connection Error

### ISSUE THREAD

**Issue by Chas1934** [CastagnaIT/plugin.video.netflix#551]
#### Your Environment
- Netflix add-on version: <Created and Modified both 4 March 2020>
- Operating system version/name: <macOS 10.15.4>
- Device model:  <iMac 27in mid-2017>

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ X] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When I select a video episode, I get the error message:
"The Addon encountered the following error:
    EXCEPTION:ConnectionError
  (info about logging to Kodi log)"
#### Expected behavior
<!Video would open and play>

#### Actual behavior

Get the error above
#### Steps to reproduce the behavior

1. Repeat selection above, same result
2. Power off, resboot, restart Kodi. repeat video selection, same result
3. Tried also on my Raspberry PI running Kodi, same result

### Debug log

The debug log can be found from this link:
https://pastebin.com/JDUwVf2n
#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
why you opened a Bug report? this is a network problem not an addon bug

**Comment by Chas1934** [comment]
It’s not network. The file it can’t open/find is on the same computer. Apps and User library are on separate drives. For what it’s worth, I’ve no idea what’s gone wrong, but I’ve deleted Netflix because it also throws up issues recently because I use a VPN.

------------


Charles Houen
Unit 206, 1 Clark Street, Williams Landing VIC  3027
