### ISSUE TITLE
InvalidProfilesError

### ISSUE THREAD

**Issue by bchabbert** [CastagnaIT/plugin.video.netflix#555]
#### Your Environment
- Netflix add-on version: 1.1.1
- Operating system version/name: osmc  Kodi (18.6). Platform: Linux ARM (Thumb) 32-bit
- Device model:  RPi 3B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
When i launch Netflix add-on, i have error message "InvalidProfilesError",
Thank you for your help

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4438067/kodi.log)

**Comment by CastagnaIT** [comment]
error is caused due to missing avatar icon

Can you give me a screen shot of the avatar of profile `laurie` ?

Fixed try this:
[plugin.video.netflix_1.1.1_20200406_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4438714/plugin.video.netflix_1.1.1_20200406_t1.zip)

**Comment by bchabbert** [comment]
hoooo yes i see Laurie don't have a pic (avatar) of her profile.....

![Capture du 2020-04-06 15-52-54](https://user-images.githubusercontent.com/63234248/78565883-c94f7080-781e-11ea-8434-8ee0f4e924a3.png)

I add an avatar and test Netflix.

It works now :) :) :)

Thank you for yor help
