### ISSUE TITLE
Profiles Missing

### ISSUE THREAD

**Issue by prometheist** [CastagnaIT/plugin.video.netflix#556]
#### Your Environment
- Netflix add-on version: <1.1.1_20200406>
- Operating system version/name: <LibreElec 9.2.1>
- Device model:  <Pi 4>

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Installed the app and logged in, but I get the error message "Profiles Missing"

#### Expected behavior
It should take me to Netflix after login, but instead this. 

#### Actual behavior
Successfully logs in, but then closes

#### Steps to reproduce the behavior
Open Netflix

### Debug log
https://paste.kodi.tv/edifahuqid

**Comment by CastagnaIT** [comment]
Follow istructions on Readme to get a good log
the provided one has not debug info

**Comment by dhon2407** [comment]
Had same issue.

http://paste.osmc.tv/usigosomaq

**Comment by dhon2407** [comment]
![image](https://user-images.githubusercontent.com/55686321/78857770-e4a7bf00-7a5c-11ea-8ca8-1f6137e4f368.png)

**Comment by CastagnaIT** [comment]
@dhon2407 your error is different the first error is `TypeError: unhashable type: 'dict'`
the other are cascading errors,
but you are using a unofficial release you can rollback to official release

**Comment by CastagnaIT** [comment]
Closed due to inactivity of Issue author
