### ISSUE TITLE
WebsiteParsingError: Unable to find html maturity level points

### ISSUE THREAD

**Issue by Neelix57** [CastagnaIT/plugin.video.netflix#557]
This error occurs after validating password for parental control in the add-on options.

I'm running version 1.1.1 of the add-on, with Kodi 18.6 Leia, under Xubuntu 18.04.

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4449397/kodi.log)

Could you help me please ?

**Comment by CastagnaIT** [comment]
Netflix has completely changed the data schema
it is necessary to reconstruct this part of the add-on
will not be done in the short term

you can still change your settings from the website
