### ISSUE TITLE
Expanding to Disney+ with it's new inputstream.adaptive support

### ISSUE THREAD

**Issue by bryanhaskins** [CastagnaIT/plugin.video.netflix#559]
I'm not sure if this is something that you would be interested in, so feel free to close this if it's completely out of scope and something you don't want to pursue, but recently (as seen in this thread: https://github.com/peak3d/inputstream.adaptive/issues/353 ) inputstream.adaptive has gained the ability to playback streams from Disney+, there is even a functional, but quite barebones addon available (linked in that thread).

Given that (functionally) Disney+ and Netflix work quite similarly, I was wondering if it would be within the realm of possibility to use the structure and feature-set of the amazing Netflix addon as a starting point to get something similar available for Disney+.

It seems to me that adapting the Netflix addon to Disney+ would be huge, and widely appreciated, so I thought I would float the idea out there.

**Comment by yoshimo** [comment]
https://forum.kodi.tv/showthread.php?tid=353316 already has a plugin covering that service

**Comment by CastagnaIT** [comment]
I saw the project,
quite confusing and merged in a few classes with a poor approach as it happens in most new projects,
thing happened with the early Netflix versions

but the very bad thing is that from now that the project is in its beginnings are not followed the PEP8 python code standards, which will lead to a lot of problems for automated integration testing

surely in this project there are many things you can assimilate to start a new VOD Kodi project, but it is also complex to understand for those who have never developed in this project

in any case i already have too much to do with Netflix,
i already spend more than hundreds of hours every month on this project
