### ISSUE TITLE
Upnext and Skip intro

### ISSUE THREAD

**Issue by n4tur3502** [CastagnaIT/plugin.video.netflix#560]
#### Your Environment
- Netflix add-on version: <1.1.1 commit 0533c49>
- Operating system version/name: <android 8.0.2>
- Device model:  <Shield Tv>

Used Operating system:
* [ x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When i play items from the netflix addon it does not give the options to skip intros and upnext does not work. Upnext works in other areas in Kodi including other add-ons. 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4459861/kodi.log)

#### Steps to reproduce the behavior

1. Removed and reinstalled the netflix add-on
2. Updated to listed commit to enable upnext check box
3. enabled option, restarted kodi.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
dalily build or master branch can have problems,
rollback or wait a new release
