### ISSUE TITLE
[Bug] Low-Res streams have green and purple lines

### ISSUE THREAD

**Issue by emc02** [CastagnaIT/plugin.video.netflix#561]
#### Your Environment
- Netflix add-on version: 1.1.1
- Operating system version/name: LibreElec 9.2.2
- Device model:  Raspberry Pi 4

Used Operating system:
Raspberry-Pi 4 with LibreElec 9.2.2

### Describe the bug
Some Streams (I guess the ones with low resolution) result in a bad image with green and purple colors. High resolution content works fine

#### Expected behavior
good picture quality

#### Actual behavior
bad image with green and purple colors on some streams

#### Steps to reproduce the behavior
1. set max. stream resolution to 1080p
2. open stream like "Trotro" or "Star Trek - Next Generation"
3. see bad image (see attachement)

#### Possible fix
set max. stream resolution lower than 1080p (but then you have to switch this every time you want to watch high-res content)

### Debug log
in Attachement

### Additional context or screenshots (if appropriate)
[netflix.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4461037/netflix.log)

#### Installation
Installed via your repo

#### Other information
The issue is not present on Windows 10 platform

#### Screenshots
Bad:
![IMG_20200410_114026 (Groß)](https://user-images.githubusercontent.com/5359218/78983044-b214c980-7b23-11ea-9f64-a432940f6a0d.jpg)
Good:
![IMG_20200410_114109 (Groß)](https://user-images.githubusercontent.com/5359218/78983041-b0e39c80-7b23-11ea-9d43-7c7685cde0c8.jpg)

**Comment by CastagnaIT** [comment]
the audio/video streams are handled by Kodi core,
open an issue in the Kodi forum

**Comment by emc02** [comment]
I've opened a ticket in XBMC and they wanted me to test netflix on newest milhouse libreelec build based on KODI19, but your latest plugin-version and daily-build is not compatible with this version?
Can you provide me a testversion for Kodi19 of your plugin?
Thanks.

**Comment by CastagnaIT** [comment]
You can download addon for Kodi19 from `Matrix` branch

I still have to finish the repository for Kodi 19,
I will do it when release 1.2.0

**Comment by emc02** [comment]
Thanks for your help!
Can confirm: on Milhouse-nightly #0412, 12-Apr-2020 with latest (todays) netflix-matrix-plugin it works fine with no issues!
