### ISSUE TITLE
Movies with SD540p Media-flag limited to 540p

### ISSUE THREAD

**Issue by farhanito** [CastagnaIT/plugin.video.netflix#57]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [ *] support request

## General information
CoreELEC on Odroid-N2
### Addon version used
Beta24

### Description

Can't get movies with SD 540p Media-flag to be streamed at higher resolution. 
Most movies have SD540p Media-flag. 

### Steps to Reproduce

1. Choose any movies with SD 540p flag 
2. Start streaming 
3. [and so on...]

**Expected behavior:** 
1080p res. 
The movie is playing at 1080p on ftv stick 4k (same kodi and addon version). 

**Actual behavior:** 
Limited to 540p (or lower). 

Contents with HD 1080p or 4K UHD media-flag can be played at 1080p very well. 

## Context (Environment)
CoreELEC on Odroid-N2
Input stream Min. Bandwidth set to 10000000

### Installation

* [* ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [* ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://www.mediafire.com/file/9r705i7lgc5tskv/kodi.zip

**Comment by CastagnaIT** [comment]
Yes is a limitation imposed by netflix to Chrome

**Comment by umfk** [comment]
Is this something that is being worked on or is this considered impossible currently? Controlling Netflix via Kodi on Windows is working great but anytime I want to watch a series or movie that was not produced by Netflix I have to take out my keyboard and mouse and start up the Netflix App.

**Comment by CastagnaIT** [comment]
The first node: https://help.netflix.com/en/node/23742
Netflix support only 720P on Chrome, this addon is based on Chrome
but the thing is more complex because it is based on the system, device and certification ...

so no solution, you have to see future changes from netflix

**Comment by umfk** [comment]
Would it hypthetically be possible to base the add-on on Edge for Windows users and get 1080p that way?

**Comment by CastagnaIT** [comment]
> Would it hypthetically be possible to base the add-on on Edge for Windows users and get 1080p that way?

no Edge doesn't use Widevine DRM

> Another question: Can Android devices view these movies/series in 1080p via Kodi? Maybe I could run Kodi in an Android emulator?!

I don't think it's possible, but If you find a solution, let us know

**Comment by umfk** [comment]
> no Edge doesn't use Widevine DRM

And I just found out inputstream.adaptive only supports PlayReady on Android...

Thanks for your work and for your replies! Let's hope that something changes in the future. Maybe inputstream.adaptive gets PlayReady support for Windows and the Netflix Add-On can then use Edge on Windows.
