### ISSUE TITLE
When using sync of watched status with Netflix, auto mark the video as watched locally when the video ends

### ISSUE THREAD

**Issue by sobralik** [CastagnaIT/plugin.video.netflix#572]
## Feature request
I'm submitting a proposal to ...
  - [X] new feature
  - [ ] change an existing feature

### Describe your request

The idea is to have an option in the settings to auto-mark the video as watched when using the sync of watched status with Netflix feature. I'm not sure how Kodi determines a video has been watched, but it should work in a similar way. I know that if you stop a video or skip to the next video with limited time left, Kodi considers it 'watched' even though the actual end of the video was not reached.

#### Describe the use case

This is a change to take away the need to manually trigger the change watched status (locally) feature when using the sync with Netflix feature.

**Comment by CastagnaIT** [comment]
I didn't get your point...
this is already happening

**Comment by CastagnaIT** [comment]
a video is marked as watched
when reach final credits, or, by simulating Kodi's original behavior:
https://kodi.wiki/view/HOW-TO:Modify_automatic_watch_and_resume_points

the lower of the two values is automatically selected

**Comment by sobralik** [comment]
Interesting. I tried enabling sync of watched status with Netflix on another computer and it did get marked as watched when the video was done. On the system I regularly use, this is not happening. There aren't any errors that come up when a video completes, it just doesn't get marked as watched silently. Feel free to close this since it seems to be unique to that install.
