### ISSUE TITLE
"The requested action timed out. The background service may not yet be available if you just started Kodi/the addon. In this case try again in a moment"

### ISSUE THREAD

**Issue by Sockolet** [CastagnaIT/plugin.video.netflix#575]
#### Your Environment
- Netflix add-on version: v1.1.1
- Operating system version/name: CoreElec 9.2.2 which runs Kodi 18.6
- Device model:  Magicsee N5 Max (Amlogic S905X2)

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Whenever my system starts-up, an error is shown: "Netflix addon failed, please check the registry log".
If I click on the Netflix addon, it gives the error:
"The requested action timed out. The background service may not yet be available if you just started Kodi/the addon. In this case try again in a moment.", and the addon can't be opened.
If I disable and then enable the addon straight away, it works as expected.

#### Expected behavior
Not showing an error at startup. Being able to open Netflix addon without having to disable/enable it first.

#### Actual behavior
Netflix addon can't be opened unless I do a disable/enable process.

#### Steps to reproduce the behavior
1. Start-up system.
2. Error is shown when the skin is loading
3. Try to open Netflix addon.
4. It can't be opened.

#### Possible fix
As I said, workaround is to disable the addon, enable it inmediatly, and the addon works as it should.

### Debug log
http://ix.io/2iax

#### Installation
Using CastagnaIT Repository for KODI 18.x LEIA.

#### Other information
N/A

#### Screenshots
N/A

**Comment by CastagnaIT** [comment]
> gaierror: [Errno -2] Name or service not known

you have some problem with localhost
i can not help you

**Comment by Sockolet** [comment]
Thanks for the answer.
Can you please elaborate it a little bit? I'll be very helpful for me.
I don't really know what do you mean with "you have some problem with localhost".
Do you mean that that function can't get localhost address??

Thank you very much in advance.

**Comment by CastagnaIT** [comment]
i'm sorry but i know little about local network configurations..

**Comment by Sockolet** [comment]
Well, it is solved by setting "Wait for network before starting Kodi" with 10 seconds of timeout in CoreELEC settings.

Sorry for bothering you with this.

Thank you very much for your amazing work!
