### ISSUE TITLE
Kodi matrix - Hevc profiles no playback on Intel Gemini Lake

### ISSUE THREAD

**Issue by brotaxt** [CastagnaIT/plugin.video.netflix#576]
Hey guys,

Iam struggling with playback of Netflix streams with activated hevc profiles. Unfortunately I don't get any output if Hevc profiles are activated.

First it seems that the playback will start, my screen changes the resolution & frequency but then I only see "Please wait..." and an infinite loading circle.

Iam using an Intel nuc7 pjyh2

debug log: https://paste.kodi.tv/raw/ejidirumic

Does Anyone have an idea why the playback won't start?

Many thanks in advance!

**Comment by CastagnaIT** [comment]
the log is wrong, shrinked and without NF debug

in any case the video decoding is handled by kodi core not from the addon
usually if loading screen still infinite or black screen means not supported or problems with Kodi

**Comment by CastagnaIT** [comment]
You should use VP9 profile

**Comment by brotaxt** [comment]
Alright, thank you for the quick response. I trimmed the debug log to the playback part. Iam using vp9 profiles at the moment. That's working fine, thank you for the great Add-on! But shouldn't Hevc profiles work also? 

Greetings
