### ISSUE TITLE
This title is not available to watch instantly.

### ISSUE THREAD

**Issue by feadog1** [CastagnaIT/plugin.video.netflix#581]
#### Your Environment
Netfix addon version 1.1.1
Raspbian Raspberry pi 4
kodi 18.6
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:

Linux
 Raspberry-Pi

### Describe the bug

Login sucessful but result is  "This title is not available to watch instantly"

#### Expected behavior

Should play video
#### Actual behavior

 
Does not play, result is message "This title is not available to watch instantly. Please try another title"

#### Steps to reproduce the behavior

1. install castagnaIT repo, 
2.install netflix addon 1.1.1 from castagnIT repo
3.start addon, login sucessfully 
4. message This title is not available to watch instantly
### Debug log

The debug log can be found from this link:https://paste.kodi.tv/orunizapol.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Read wiki: https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29
no other solution
