### ISSUE TITLE
Netflix failing to start on kodi test builds for rpi4 

### ISSUE THREAD

**Issue by naidu72** [CastagnaIT/plugin.video.netflix#587]
#### Your Environment
- Netflix add-on version: 1.1.1
- Operating system version/name:  LibreElec 9.2.1
- Device model:  raspberry pi 4 
I upgraded my libreelec 9.2.1 to kodi test builds as mentioned below, after upgrade netflix falling to seat due python version dependency . In the kodi test build has python 3+ version.
Kodi test builds:
https://forum.kodi.tv/showthread.php?tid=343068

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ *] Windows

**Comment by jotakswe** [comment]
@naidu72 
You can start by reading this, otherwise you will not get any help.
https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

**Comment by CastagnaIT** [comment]
For Kodi 19 see Issue post https://github.com/CastagnaIT/plugin.video.netflix/issues/537
