### ISSUE TITLE
Not compatible with Kodi Matrix 19 (anymore); The dependency on xbmc.python version 2.26.0 could not be satisfied.

### ISSUE THREAD

**Issue by franknet1** [CastagnaIT/plugin.video.netflix#588]
#### Your Environment
- Netflix add-on version: 1.1.1 
- Operating system version/name: Windows 10 
- Device model: Intel Coffee Lake 

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ x] Windows

### Describe the bug

Netflix does not install in Kodi 19.
Error: The dependency on xbmc.python version 2.26.0 could not be satisfied.
#### Expected behavior

Netflix addon should install
#### Actual behavior

Error during install from repository: The dependency on xbmc.python version 2.26.0 could not be satisfied.

#### Steps to reproduce the behavior

1. Clean install of Kodi matrix 19; build 18-04-2020
2. Install CastagnaIT repository
3. Install Netflix addon from repository

#### Possible fix

Not compatible with Python version I guess
### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/raw/huzomupewe

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by franknet1** [comment]
The Netflix app is not compatible anymore with kodi 19 for some time. Not only with the latest build. And I really want Kodi 19 due to good HDR versions with also improved video with non HDR video; https://github.com/thexai/xbmc/releases
Could you please fix this? I would appreciate this very much.

**Comment by CastagnaIT** [comment]
Discussion Issue already open

**Comment by franknet1** [comment]
Hello Stefano,

I disagree to close the issue. because #537, has not solved the issue as it
is claiming.
It is stil a problem; Netflix installation does not work with fresh
installation oflatest kodi 19 in Windows 10.
Please, some help would be great.

Best Regards,

Frank

Op ma 20 apr. 2020 om 13:52 schreef Stefano Gottardo <
notifications@github.com>:
