### ISSUE TITLE
ConnectionError Message

### ISSUE THREAD

**Issue by tsioukas** [CastagnaIT/plugin.video.netflix#589]
#### Your Environment
- Netflix add-on version: 1.1.1
- Operating system version/name: Windows 10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

In last 2 days I am getting this error message 

"ConnectionError: HTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /nq/msl_v1/cadmium/pbo_licenses/%5E1.0.0/router (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020B8AC2A940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))"

#### Steps to reproduce the behavior
1. It happens randomly, usually in episode list some seconds after playback
2. Also I detect that sometimes in playback it freezes and I have to stop and replay it.
3. My internet connection is stable without any problem at the time that these messages appeared.

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
if happens randomly there is a network/isp problem i can not do nothing with this errors

**Comment by tsioukas** [comment]
I understand that, but it happens while I am doing anything, I just stop an episode. I leave it for some seconds/minutes without playing nothing or navigate on any menu and this message appears. I don't know if some tasks run in background and this message appeared later. This isn't a major problem, I just mentioned it.

I don't understand the ignored rules tag, I follow the example and I fill all the segments that I have data to fill.

**Comment by CastagnaIT** [comment]
> I don't understand the ignored rules tag, I follow the example and I fill all the segments that I have data to fill.

You havent follow the guideline rules: https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

**Comment by tsioukas** [comment]
OK, as a coder I understand that you can't fix something that you can't reproduce, and maybe this is a random problem that caused by Netflix overloaded servers due COVID-19 (by the way on fast.com I get 100Mbps at that time) so I close this report and we will see if I can reproduce it somehow.
