### ISSUE TITLE
Error locale_id

### ISSUE THREAD

**Issue by Simon-the-Sorcerer** [CastagnaIT/plugin.video.netflix#59]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

beta 24 from repo

### Description

When I start any videos, netflix shows the error **locale_id**. My language is german on Netflix and Libreelec

### Steps to Reproduce

1. Start video from addon or library

**Expected behavior:**

Video starts to play

**Actual behavior:**

Netflix shows error locale_id

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Libreelec Milhouse #0414 on RPI3

## Debug log

I can add a debug log when I'm at home

## Other information

Maybe related to #31 

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by jakermx** [comment]
Please share your log file...

**Comment by Simon-the-Sorcerer** [comment]
I'm getting more and more different mistakes. I think I'm trying a clean Libreelec installation
