### ISSUE TITLE
invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by utkabaam** [CastagnaIT/plugin.video.netflix#591]
#### Your Environment
- Netflix add-on version: latest
- Operating system version/name: OSMC 18.6
- Device model: Raspberry  Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
*  Raspberry-Pi
* [ ] Windows

### Describe the bug

I followed instalation guide, got till point where i tried to open an episode of my favourite TV show.
After pressing on selected episode I get this Error.
invalid literal for int() with base 10: ''
#### Expected behavior

I expected it to play a chosen episode.

#### Actual behavior

Error
#### Steps to reproduce the behavior

1.Open Netflix Add-on
2.Chose TV show
3.Open any episode

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/jujurazibo.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon

**Comment by CastagnaIT** [comment]
provide a log with debug info as explained in Readme

**Comment by utkabaam** [comment]
I'm really sorry,  but I'm totally new to GitHub and OSMC.
I did follow instructions https://github.com/CastagnaIT/plugin.video.netflix/blob/master/README.md#something-doesnt-work

And pasted the LOG to https://paste.kodi.tv/jujurazibo.kodi 

Or is this the wrong log ?

**Comment by CastagnaIT** [comment]
no this is wrong log

**Comment by utkabaam** [comment]
Excuse me for stupid question.

I just  Enabled the Debug log in your Kodi settings.
How can i extract the log trough terminal?

**Comment by CastagnaIT** [comment]
i never used OSMC it is better you ask on OSMC forum or read OSMC Wiki

**Comment by utkabaam** [comment]
https://paste.osmc.tv/ugemeyanam

**Comment by CastagnaIT** [comment]
this time the log is good
but you are using a unofficial version not released,
next time you have to specify on the report write "latest" no means nothing for me

seem that has failed to read Kodi version

Please install this, reboot Kodi and give me another log
[plugin.video.netflix_1.1.1_20200421_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4510367/plugin.video.netflix_1.1.1_20200421_t1.zip)

**Comment by utkabaam** [comment]
Ok I will!
Thank you very much.

I'm on it!

**Comment by utkabaam** [comment]
Same error 

https://paste.osmc.tv/qifiyilude

**Comment by CastagnaIT** [comment]
Please try this and give a log
[plugin.video.netflix_1.1.1_20200421_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4510634/plugin.video.netflix_1.1.1_20200421_t2.zip)

**Comment by CastagnaIT** [comment]
deleted sorry wrong thing

**Comment by CastagnaIT** [comment]
done test and give log
[plugin.video.netflix_1.1.1_20200421_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4510668/plugin.video.netflix_1.1.1_20200421_t2.zip)

**Comment by utkabaam** [comment]
Thank you for your help!
Video is playing and I'm satisfied after 3 day search of best option for Netflix on my Pi3.
https://paste.osmc.tv/imugoziget

I will  keep on going trough all the functions and keep updating on any bugs I encounter. 
Thanks again, and have a great day!

**Comment by CastagnaIT** [comment]
good thanks
