### ISSUE TITLE
Ability to create a shortcut with Profile

### ISSUE THREAD

**Issue by Doctor-Eggs** [CastagnaIT/plugin.video.netflix#592]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
Add the ability when creating a shortcut within Kodi to any of the areas inside the Netflix plugin that it would take into account which profile is being used. If the profile guid being passed did not match the active guid then switch the active guid to the one that was passed and then open the menu item.

#### Describe the use case
I would like to create shortcuts or widgets within Kodi that point to the content inside "My List", "Continue Watching", "Top Picks For" for different profiles. Right now it will point to only the active profile.

#### Describe an alternative
Creating different profiles within Kodi that correspond to each Netflix profile. But this gets into a boat load of clicks, fights over why whose profile is active when the TV is turned on and in general a lot more steps than I would like. 

#### Development tips
Add the profile GUID to the query string for all menu items. That way when it tries to load "My List" for my profile but my wife is the active profile, it will change the profile to mine and then load the content. 

### Additional details or screenshots (if appropriate)
Here is what the shortcut currently looks like: 
plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/?genre_id=None
Here is what I'm proposing:
plugin://plugin.video.netflix/directory/video_list_sorted/myList/queue/?genre_id=None&guid=MYGUIDSTRING1234

**Comment by CastagnaIT** [comment]
I do not provide any support/request for Widgets
Read Wiki: [Skin Widgets - problems and limits](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits)

Netflix manages only a single profile access by web session,
and although you might find a way to do it, making multiple switches in very short time for indefinite amounts of widgets to allow separate loading of data is not a safe operation to do and you might risk an increase in the account ban case or password reset

this request will not be considered

**Comment by CastagnaIT** [comment]
If you have problem with widgets because you share Kodi with two person,
exists the Kodi profiles

Create two Kodi profiles, with two netflix addons installations

**Comment by Doctor-Eggs** [comment]
Fair enough. My thought was to have shortcuts but thought that widgets might be a possibility as well not having knowledge about how Netflix handles things and the potential adverse effects.

Thanks.

**Comment by CastagnaIT** [comment]
other users make use of Kodi Profiles, also to be able to customize the Kodi library in a different way according to the user's tastes
bye
