### ISSUE TITLE
Addon produces error after running Kodi

### ISSUE THREAD

**Issue by pocki04** [CastagnaIT/plugin.video.netflix#596]
#### Your Environment
- Netflix add-on version: 1.1.1 2020-03-24
- Operating system version/name: Raspbian
- Device model:  Raspberry Pie 4 2Gb

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

Addon produces error after opening Kodi 18.6.

#### Expected behavior

Addon should start up.
#### Actual behavior

Addon doesn't start up and produces error.

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/wizoresuco.kodi

#### Installation
* [x] I'm using the Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
This is not a bug
your RPI is not configured to run netflix
follow instruction on Readme or ask on forum
