### ISSUE TITLE
1.2.0 throws TypeError if lib_auto_upd_mode is 2 already somehow

### ISSUE THREAD

**Issue by mackal** [CastagnaIT/plugin.video.netflix#597]
## Bug report
This can happen if you downgrade from 1.2.0 to a previous version and then try to upgrade (I tried to upgrade to Matrix version and ran into errors with something and downgraded to continue my day and had to fix this issue) I was able to successfully upgrade after manually changing the value in the XML and using a Leia build.

#### Your Environment
- Netflix add-on version: 1.2.0
- Operating system version/name: Gentoo

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

lib_auto_upd_mode is somehow an unexpected value and fails

#### Expected behavior

Error is handled

#### Actual behavior

Fails

#### Steps to reproduce the behavior

1. Manually set lib_auto_upd_mode to 2 in settings.xml
2. Update from a version below 1.2.0 so the branch in _perform_service_changes is taken

#### Possible fix

Sanity check lib_auto_upd_mode before calling g.ADDON.setSettingInt

### Debug log

The debug log can be found from this link: I ahh already started kodi enough that even the kodi.old.log isn't relevant ... I can re-create the log if I must, but I think I provided enough details.

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
mmh strange i will take a test,
Did you install an unofficially released version before?
as daily build or manually downloaded from git?

**Comment by CastagnaIT** [comment]
maybe I understand the problem
but I don't think there's anything I can do
because the version control, in the previous version was different
and there is no way to instruct the shifting value of the parameter

I can only handle an error in the new version

**Comment by mackal** [comment]
The plugin updated changed the settings.xml then crashed before stuff fully updated (I think I didn't updated inputstream-adaptive for Matrix ...) which left it in a state where https://github.com/CastagnaIT/plugin.video.netflix/blob/6e2f9f32dad31eaa8611449326866aed644dac80/resources/lib/upgrade_controller.py#L77 fails. Could just catch the exception and set to default value.

**Comment by CastagnaIT** [comment]
Yes, that's right, that's what I want to do
