### ISSUE TITLE
Reconnecting to Netflix lead to "wrong email or password" with Widevine 4.10.1610.6  

### ISSUE THREAD

**Issue by anravalli** [CastagnaIT/plugin.video.netflix#598]
#### Your Environment
- Netflix add-on version: 1.2.0
- Operating system version/name: LibreELEC (official): 9.2.1
- Device model:  RPi 4B 4GB Ram

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
With latest Widevine / addons combination (see version information below) disconnecting the device from Netflix or changing its the password leads to `MSLError: Email or password is incorrect` error.  
It should be noticed also that:
* browsing the Netflix contents it's still possible and works as expected
* under the "**_cdm_**" folder the files storing decrypter configuration/secrets (**_*.challenge, *.init, *.response_**) are no more created and/or updated.

#### Expected behavior
Video playback should start for the selected content.

#### Actual behavior
Playback isn't started and a popup is shown reporting that "email or password are incorrect".

#### Steps to reproduce the behavior
1. in Netflix->Addon Setting: select Disconnect 
2. enter credential when prompted
3. browse Netflix to playable content
4. start playback

### Debug log
The debug log can be found from this link:
 https://paste.kodi.tv/eyaxurorur.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information
- Kodi info
  - Release: 18.6
  - Piattaforma/architettura: Linux/arm
- InputStream info
   - InputStream Helper: 0.4.5
   - InputStream Adaptive: 2.4.4.1
- Widevine info
   - Widevine: 4.10.1610.6 (aggiornato il 2020-04-23 16:42)
   - Widevine CDM: /storage/.kodi/cdm
   - Chrome OS: 12739.111.1

**Comment by CastagnaIT** [comment]
read Wiki faq
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#email-or-password-is-incorrect

**Comment by anravalli** [comment]
@CastagnaIT credentials are correct (just checked once more) and the Netflix plugin by it self works pretty well: I'm able to select my profile, navigate my list or any other view, I see all the movie or shows info correctly and so on.  The issue is only related to the movie/episode playback.

IMHO, and from what I was able to see, the issue may be related to how the credentials are handed over to the decrypter the first time (I understood they are then cached) but I know too few about the plugin architecture and how the responsibility are split between the him, the inputstream helper, the  inpustream and the widevine decrypter.

**Comment by CastagnaIT** [comment]
> I understood they are then cached

what means? there is no cache for credentials
with MSL communication credentials are sent only the first time (encrypted), then for all subsequent requests are replaced by encrypted tokens

inputstream helper is not involved is only a support for download widevide
inputstream adaptive is not involved is used only to get drm streaming pass to kodi player
in the case of RPI widevine are not used to encrypt the data, so are excluded

could you send me the file msl_data.json from addon userdata folder
to understand if some tokens are stored?

**Comment by anravalli** [comment]
Hi,  
sorry for the misuse of the term "cached" and thank you for the short explanation about the role that each of that parties have in making the whole thing working.  
Here is the [msl_data.json](https://github.com/CastagnaIT/plugin.video.netflix/files/4531820/msl_data.zip) (it's zipped so that it could have been uploaded).  

Based on your insight I'll try to investigate also by myself, in the mean while I hope you will have the time to try reproduce the issue.  

One last question: do you know the role of the _*.challenge, *.init_ and _*.response_ files under the **cdm** folder?

**Comment by CastagnaIT** [comment]
the problem is that this error is not reproducible
because the actual causes that led to this problem can be very different compared to the MSL invalid password error message

should not be considered as a specific symptom of a single error, but the causes leading to this can be many

as far as I know (one of the causes) this can happen when the password is changed and user tokens already saved/used still related with the old password

but in your case, the user tokens were not saved in the file you sent
this could mean that: you did a logout, or you've reinstalled the addon, or you've already tried to delete the file you sent me, please let me know if you have done one of this things, otherwise i don't know how to continue the investigation

then provide me a debug log with the error, see instructions in the readme to enable verbose debug

_Only after take a debug log_,
try delete msl_data.json (with Kodi off) and try again

---

are not aware of the meaning of the cdm files
it's not important for me to know

**Comment by anravalli** [comment]
> this could mean that: you did a logout, or you've reinstalled the addon, or you've already tried to delete the file you sent me
Yes, you're right, I did all that before to report the issue.  

Just to give you some more background: the issue popped up after I changed my Netflix password and this happen a few days after I was prompted for a Widevine update.  
That two events lead me to the conclusion (wrong) that:
* new Widevine + old password:
  * token and other "exchanged secrets" still good (no issue, playback was still possible as expected)
* new Widevine + new password:
  * token and other "exchanged secrets" no more good (only partly updated)
  * browsing was still possible
  * playback was failing with "email or password" error, then: 
    ---> something went wrong, maybe due to an api change in Widevine

> provide me a debug log with the error
I will provide you new debug log ASAP.
If I understood correctly, the scenario you want me to test is:  
* Precondition: 
  * Kodi log level: _debug_
  * plugin.video.netflix log level: _verbose_
  * remove _msl_data.json_ from  `userdata/addon_data/plugin.video.netflix/`
* Test Steps:
  * Start kodi
  * open Netflix plugin
  * login to Netflix

**Comment by anravalli** [comment]
By the way, I've just checked on my Linux desktop and everything works like a charm.  
Kodi and Netflix plugins are the same as on RPi but InputStreamAdaptive and Widevine are older (of course the architecture is also different).  
Below the detailed version info:
- Kodi information
  - Kodi version: 18.6
  - Kodi platform/architecture: Linux/x86_64
- InputStream information
  - InputStream Helper version: 0.4.5 
  - InputStream Adaptive version: 2.3.22 
- Widevine information
  - Widevine version: 4.10.1582.1 (last updated on 2020-04-25 21:14)
  - Widevine CDM path: /home/andrea/.kodi/cdm

I'll try also to step back both InputStreamAdaptive and Widevine and see what happen.  
I'll let you know.  
Thanks

**Comment by CastagnaIT** [comment]
> the issue popped up after I changed my Netflix password

this is normal, because if you change password you break the token chains
in this case deleting msl_data.json or logout/re-login should solve the problem

I will try to recheck if it is possible to implement a fallback system in case of password change
