### ISSUE TITLE
Remove repository from readme as it points to an older version

### ISSUE THREAD

**Issue by Dnkhatri** [CastagnaIT/plugin.video.netflix#6]
You should remove this from the readme as it points to the older version of the plugin 
```
Installation & Updates
You can use our repository to install the plugin. Using this, you´ll immediately receive updates once a new release has been drafted. 

```

**Comment by CastagnaIT** [comment]
I didn't remove it because the intention would be to unify the modifications on the repository of asciidisco, but with the permission of caphm, unfortunately he hasn't answered yet.

**Comment by Dnkhatri** [comment]
I get that but when anyone is pointed to your GitHub the first thing they see is the repository for the older version of the plugin and probably install that. So I think it would be better to remove the link to that repository untill the matter is resolved. Just don't submit the edit upstream
