### ISSUE TITLE
Fileinfo is missing in NFO export which lead to partially working Kodi library

### ISSUE THREAD

**Issue by mbroemme** [CastagnaIT/plugin.video.netflix#600]
#### Your Environment
- Netflix add-on version: 1.2.0
- Operating system version/name: Arch Linux
- Device model:  Intel NUC

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
When exporting a series to Kodi library with enabled NFO export including all details, it doesn't export `<fileinfo>` to the NFO file. Without it the Kodi library didn't show any tags or small images like HD/SD.

#### Expected behavior
The fileinfo information should be exported, eg:

```
<fileinfo>
   <streamdetails>
       <audio>
           <channels>2</channels>
           <codec>aac</codec>
       </audio>
       <video>
           <codec>h264</codec>
           <durationinseconds>120</durationinseconds>
           <height>1080</height>
           <width>1920</width>
           <language>ger</language>
           <scantype>Progressive</scantype>
       </video>
   </streamdetails>
</fileinfo>
```

#### Actual behavior
Due to absence of fileinfo, some information in Kodi library is missing.

#### Steps to reproduce the behavior
1. Navigate to Netflix library settings
2. Activate export of NFO files
3. Always for movies and series
4. Enable setting to export all NFO information

#### Possible fix
Export `<fileinfo>`, for example like the Amazon Prime plugin does.

**Comment by CastagnaIT** [comment]
this is not a bug report, but rather a implementation request
will be queued up with the others

**Comment by CastagnaIT** [comment]
i have re-analyzing the metadata used to generate nfo
but there are no info to allow add stream details

so your request is not applicable
