### ISSUE TITLE
Function missing required argument 'line1' (pos 2)

### ISSUE THREAD

**Issue by tweimer** [CastagnaIT/plugin.video.netflix#601]
#### Your Environment
- Netflix add-on version: 1.2.0
- Operating system version/name: Libreelec (Milhouse)
- Device model:  Raspberrypi

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
This error appears every time I try to watch smth.
[log-2020-04-25-19.58.47.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4533899/log-2020-04-25-19.58.47.zip)

#### Installation
* [ ] I'm using other Netflix Repo 
* [x] I'm using a different source: Your repository for Kodi Matrix

**Comment by CastagnaIT** [comment]
This error not come from Netflix:
`"/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 124, in yesno_dialog`

**Comment by tweimer** [comment]
@CastagnaIT What does that mean? Any idea on how I can fix it? Do I need a special version of that plugin? I cannot use Netflix plugin at all.

**Comment by CastagnaIT** [comment]
as you can read in my new post in the forum
Kodi 19 is implementing several API changes

that's going to break a lot of add-ons

you probably either installed too old a version 
or they didn't full fixed their addon

**Comment by tweimer** [comment]
So I must report it to inputstreamhelper if there is no new version?
