### ISSUE TITLE
Issue with HDMI output on RPI4b

### ISSUE THREAD

**Issue by Jean-PhilippeD** [CastagnaIT/plugin.video.netflix#602]
#### Your Environment
- Netflix add-on version: 18.6
- Operating system version/name: Raspbian buster
- Device model:  RPI4b

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
In fact, the issue does not directly come from Kodi or the plugin. 
I can use Kodi or watch PVR or movies from nfs without problem, but when I try to watch netflix video, the screen and the sound keeps turning off then on and off again..

I found that It should come from HDMI
There is a page for this known issue on raspbian [here](ttps://www.raspberrypi.org/documentation/configuration/config-txt/video.https://www.raspberrypi.org/documentation/configuration/config-txt/video.md)

But despite every config I tried, netflix keep no working.

#### Expected behavior
The video should work.

#### Actual behavior
The screen (video and audio from hdmi) keeps stop and start again.
On some config, the screen turns off and says there is no input at all...

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
i can only try to suggest to disable "vp9" and "hevc" from expert settings

but video decoding is performed by Kodi core
so you have to ask in Kodi forum
