### ISSUE TITLE
No sound on Netflix

### ISSUE THREAD

**Issue by Luis-MP** [CastagnaIT/plugin.video.netflix#603]
#### Your Environment
- Netflix add-on version: all versions from CastagnaIT
- Operating system version/name: Libreelec Leia
- Device model: PI1

Used Operating system:
[X] Raspberry-Pi
### Describe your help request

I can't hear anything whyle playing Netflix. I used to hear sound, but suddenly it stopped... I have reinstalled the plugin, in all versions available, but to no avail. I can hear kodi sounds, but no sound from netflix.

**Comment by CastagnaIT** [comment]
the only thing i can say is try to disable dolby audio from expert settings
it is possible that is not supported from your system.

But audio decoding is elaborated by Kodi core
you have to ask to Kodi or Libreelec forum
