### ISSUE TITLE
Errors after having used Netflix

### ISSUE THREAD

**Issue by MartChic** [CastagnaIT/plugin.video.netflix#604]
#### Your Environment
- Netflix add-on version: 1.2.0
- Operating system version/name: LibreElec 9.2.1
- Device model:  RPi 3b+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
I am getting many errors recently (CacheMiss), mostly after having used Netflix and having switched to another addon, e.g. Youtube. I recently installed opensubtitles, so maybe it's related. It seems to go away when I reboot the device.

### Debug log
https://drive.google.com/open?id=10O_YQvbKrpxHkMKEspxesSthW3qgrCtv

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by MartChic** [comment]
I edited the message and put a link for the debug log.

**Comment by CastagnaIT** [comment]
from what i can see even though there's a complete lack of debugging info
upstream there is an error already known and not solvable

I don't understand the cause of the cachemiss
you kept a video on pause for several hours?

**Comment by MartChic** [comment]
I often pause videos for a long time but I don't think it's systematicaly related. 

And what do you mean, a "bad connection"? Thanks!

**Comment by CastagnaIT** [comment]
gime me an example of the longest time you have paused

**Comment by CastagnaIT** [comment]
this errors:
> RenderManager::WaitForBuffer - timeout waiting for buffer

> The request has failed: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

means instable internet connection
data cannot always be transmitted and received correctly

**Comment by MartChic** [comment]
The longest time? Could be 24 hours easily. The shortest would be a few minutes. But when I start to get those errors I reboot the device and everything gets back to normal.

**Comment by CastagnaIT** [comment]
here is the problem,
is that you are making improper use of the video stream

with the synchronization of watched status enabled
leave the streams blocked for too many hours (more than 3/4 hours) 
will cause the expire of the validity of the data that can broken also the streams links
where one of side effect on add-on side is CacheMiss error,
minor thing are continuous requests sent over the network (from my side limited to first 30 minuts) 

you have to stop the video, and resume when you have to watch it again

The only thing that i can try to do is implement
an automatic stop of the video after some hours of pause
in this way you avoid the problems mentioned

**Comment by MartChic** [comment]
Ah yes, I think automatic stop would be a good idea. Maybe after 1 hour or even 45 minutes would be ok.

**Comment by CastagnaIT** [comment]
done in the new release
