### ISSUE TITLE
Won't open folders

### ISSUE THREAD

**Issue by wvendrig** [CastagnaIT/plugin.video.netflix#605]
#### Your Environment
- Netflix add-on version: 1.20
- Operating system version LibreElec 9.1.2

Used Operating system:
* [x] Raspberry-Pi

### Describe the bug

I recently updated Libreelec to 9.1.2 and since then Netflix add on became quite unstable
I click on a account and expect the list of folders to show what actually happend is Netflis add-on error with a request to post this error with log on github.

error seems rahter random in behaviour sometimes it actually allows me to browse to lower fodlers but eventually the error appears when browsing to the fodlers in Nerflix

The debug log can be found from this link:
https://paste.kodi.tv/ehotaceyay.kodi

* [x] I'm using other Netflix Repo 
CastagnaIT Repo 1.0.0
* [ ] I'm using a different source

**Comment by pakeha-by** [comment]
[01_KODI.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4543268/01_KODI.log)
I have exact same symptoms after LibreElec was updated to 9.1.2 (before update worked fine).

Installed from official repository.castagnait-1.0.1.
Log file attached.

**Comment by CastagnaIT** [comment]
I don't see anything unusual in the logs
if the service server does not respond and client raise timeout error
there is something not work with localnetwork

i can not do nothing if libreElec has bugs, rollback or ask at libreelec

**Comment by jakermx** [comment]
try updating the timeout from 16 to 60 secs on ipc.py...reboot and try again

**Comment by CastagnaIT** [comment]
it is not a problem of length of timeout
ipc call go out but the communication does not reach its destination of service

I have already seen these problems, often are wrong localhost network configuration
is a problem with their system
