### ISSUE TITLE
After Login it show only Exception : Httperror, and dont show anything.

### ISSUE THREAD

**Issue by phicha20224** [CastagnaIT/plugin.video.netflix#606]
#### Your Environment
- Netflix add-on version: 1.2.0 , 1.10 Kodi 18.6
- Operating system version/name: Android TV 5.1 Api level 22 kernel linux 3.10.61+
- Device model:  MIBOX3 PRO MDZ-18-AA

Used Operating system:
* [ v] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
after login with email and password it show
Exception : Httperror,
it said there is in log but i check on option system log there is no log..

#### Expected behavior
in version 0.13.26 it can login, but video cannot play.

**Comment by CastagnaIT** [comment]
it is a know issue,
you can update with the daily build
