### ISSUE TITLE
HDR stream enabled with Amazon Fire Stick 4K, but stream is only 1920x1080?

### ISSUE THREAD

**Issue by roenthomas** [CastagnaIT/plugin.video.netflix#609]
#### Your Environment
- Netflix add-on version: <1.2.0>
- Operating system version/name: <FireOS / Android>
- Device model:  <Amazon Fire TV Stick 4K>

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Kodi 18.6 Leia build, I can watch the HDR stream on the AFTV Sick 4K, but when I go to video stream info, it says HEVC, 1920x1080. I was expecting a 4K stream, as I know that this series has 4K content through other rips. If I use the Youtube Kodi add-on and watch a 4K video, the stream says VP9, 3840x2160 as expected. Limiting the stream to UHD 4K in add-on settings doesn't change this behavior.

#### Expected behavior

Expected stream to video stream to say HEVC, 3840x2160

#### Actual behavior

Video stream is described as HEVC, 1920x1080

#### Steps to reproduce the behavior

1. Ensure add-on has HDR profile enabled
2. Play a Marvel Series that has Dolby Vision + Dolby Atmos Enabled, like Jessica Jones S3 or Iron Fist S2
3. Check video stream information

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
compare this addon with youtube is totally irrelevant
netflix adopts a proprietary system to manage streams

there are only two possibilities:
- you have wrong settings
in this case read the WIKI VIDEO FAQ
- the resolution is not available for the requested video

no other solutions

**Comment by roenthomas** [comment]
Thanks, the FAQ solved my issues, particularly the min bandwidth setting.
