### ISSUE TITLE
Cannot play HEVC on Windows 10

### ISSUE THREAD

**Issue by posterpico** [CastagnaIT/plugin.video.netflix#613]
#### Your Environment
- Netflix add-on version: 18.6
- Operating system version/name: Windows 10
- Device model:  Intel i5 7300HQ - GTX 1050Ti

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug
Cannot play HEVC on Kodi 18.6 (Windows 10) to play HDR Movies.

#### Expected behavior
Playback will run normally like when play h264 or vp9

#### Actual behavior
Loading forever

#### Steps to reproduce the behavior
1. Open Netflix
2. Play movies

### Debug log
The debug log can be found from this link: https://paste.kodi.tv/ukisijutuz.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

**Comment by jakermx** [comment]
Since video playback depends on widevine, AFAIK, Windows based hw is not certified as HDR/HEVC divice so widevine will just playback at most at 1080p
