### ISSUE TITLE
Cannot download Widevine CDM

### ISSUE THREAD

**Issue by Lznah** [CastagnaIT/plugin.video.netflix#615]
#### Your Environment
- Netflix add-on version: 1.2.0
- Operating system version/name: 4.19.55-6-osmc - Kodi 18.6
- Device model:  Raspberry Pi 3B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Once I want to play a video on Netflix, a pop up window appear that requires to download Widevine from Chrome OS recovery image. Downloading is able to start and finish, even the unarchiving is able to start but finishes with an error "UnknownDecodeError: "
#### Expected behavior
After the installation of Widevine CDM, the error appers
#### Actual behavior
Play a video on Netflix after the installation of Widevine CDM

#### Steps to reproduce the behavior
1. Follow the steps here: https://discourse.osmc.tv/t/how-to-all-platforms-can-i-use-netflix-on-osmc-post-4/54741/4
2. Sign into your Netflix account
3. Play a video on Netflix
4. You are asked to install Widevine. Do it.
5. The error should appear almost at the end of the extraction.

### Debug log
The debug log can be found from this link: https://paste.kodi.tv/yedawivope.kodi

**Comment by CastagnaIT** [comment]
This error not come from this add-on
`File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in extract_widevine_from_img`

do the report to the right addon
