### ISSUE TITLE
ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)

### ISSUE THREAD

**Issue by berturion** [CastagnaIT/plugin.video.netflix#617]
#### Your Environment
- Netflix add-on version: `1.2.0`
- Operating system version/name: `Linux 5.6.9-1-ck-skylake #1 SMP PREEMPT Sat, 02 May 2020 15:38:08 +0000 x86_64 GNU/Linux`
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
I can't open videos, most of the time. Some work one day, then I can't play them anymore. Some never work. Some work another day.

[Kodi log here](https://pastebin.com/sQEmpshm).

#### Expected behavior
The video is playing.

#### Actual behavior
Most of the time the video is not playing. It fails in timeout.

#### Steps to reproduce the behavior
1. Launch Kodi.
2. Open Netflix Extension
3. Try to launch a video (for example, After Live, Season 2, Ep 6)

#### Possible fix
I don't know, something related to this specific server maybe (I saw that in the logs): https://ipv4-c004-run001-zeop-isp.1.oca.nflxvideo.net

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information
The same thing is happening on my Raspberry Pi 3 on OSMC.

**Comment by CastagnaIT** [comment]
the errors come from InputStream Adaptive
I don't know exact workings of that addon

but i see differents type of error
seem more a isp issue or network issue

> I don't know, something related to this specific server maybe (I saw that in the logs): https://ipv4-c004-run001-zeop-isp.1.oca.nflxvideo.net

this address is based on your ISP is provided as is

I can't do anything here

**Comment by berturion** [comment]
Thanks for your answer @CastagnaIT.
I have some questions in order to help me resolving this issue, please:

- Do you know if I can hack my /etc/hosts in order to change the server provided by my ISP and point to another IP address that could work?
- Do you have some IP of netflix server I could try?
- Also, do you think that changing some InputStream Adaptative parameters can resolve this issue?
- Should I declare this issue in InputStream Adaptative repo?
- Should I contact my ISP and what should I ask them in order for them to understand the problem?

**Comment by CastagnaIT** [comment]
...🤔you took me for a call service?

netflix also provides other streams addresses
the addon usually takes the first, so the recommended one

if you are experienced on development
you can try change these two line of code:
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/services/msl/converter.py#L163
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/services/msl/converter.py#L219
and so change the number "0" with "1" or "2"
this will make a switch to select the others url address (are always 3)
the lowest number is usually the best

> Should I declare this issue in InputStream Adaptative repo?

it is not a bug, it don't help you with a local problem..

**Comment by berturion** [comment]
Sorry no I know you're are not a call service :hand_over_mouth: I just think that you are clearly the expert here so if someone know something about this issue it should be you.
Anyway, yes I will change the array index and see what's happening.
Thank you.
:ok_hand:

**Comment by berturion** [comment]
OMG it works ! I changed all `downloadable['urls'][0]` I found by `downloadable['urls'][1]` and tested 3 videos. All were played perfectly!
I had to change `_convert_audio_downloadable` and `_convert_video_downloadable` functions. Each having `downloadable['urls'][0]` referenced.
The bad news is that it will be overwritten by each plugin update and I will have to re-apply the fix.

**Is it possible to make a plugin parameter for this?**

**Comment by berturion** [comment]
The parameter value could have these values:
- server 1 (-> index 0 of the array)
- server 2 (-> index 1 of the array)
- server 3 (-> index 2 of the array)
- random
?

**Comment by CastagnaIT** [comment]
yes i can add an option selectable
i will include for next release

**Comment by berturion** [comment]
Or another possibility, but more difficult to implement, would be to catch this specific error and automatically switch the server index in a param for the next try. While it works, the index is kept.

**Comment by berturion** [comment]
You're awesome :)

**Comment by berturion** [comment]
The advantage of the second solution is that it is not necessary to create a param in the UI. The plugin is selecting the good server automatically following the failures or successes.
Because, I am afraid that most users won't understand what this setting is for...

**Comment by CastagnaIT** [comment]
> Or another possibility, but more difficult to implement, would be to catch this specific error and automatically switch the server index in a param for the next try. While it works, the index is kept.

it is not this add-on that manages the streams,
are managed by InputStream Adaptative and Kodi core.

These parameters should not be touched here,
these parameters should be managed by InputStream Adaptative,
but currently lacks implementation, on the automatic management of streams quality based on network speed, and this too

**Comment by berturion** [comment]
Ok I understand.
So you will implement a simple parameter that allow the server selection (1, 2 or 3)?

**Comment by CastagnaIT** [comment]
thanks for sending me your support is much appreciated
exactly i will add a selection in expert settings

**Comment by berturion** [comment]
Your welcome, it is the least I can do :)

**Comment by berturion** [comment]
I just tested v1.2.1 with this fix. It works perfectly :) Thanks again!
