### ISSUE TITLE
Desync'ed Watched / Unwatched status in Kodi

### ISSUE THREAD

**Issue by masca90021** [CastagnaIT/plugin.video.netflix#625]
Hi, 

The issue is as follows: As soon as you start watching a tv show or a movie , doesn't matter how many episodes you watched, the show or movie is marked as watched in Kodi from the beginning. I have to set Kodi for "All Movies" so I can find the show. I usually use Kodi to show only unwatched movies and shows. It's kinda annoying to scroll 50-60 shows to get to the one you wanna see. It's the same in every category of the Netflix addon. The addon for HBO Go does not have this issue. Would be useful not to set the movie or tv show ( as a whole ) with a watched status before you watch the movie 100% or until all the shows episodes are watched.

Ty for reading this

**Comment by CastagnaIT** [comment]
I don't completely understand what you wrote is a little imprecise

I do not understand if you are talking about Kodi's library or browsing through the lists in the add-on like this:
![image](https://user-images.githubusercontent.com/3257156/81145533-bb545300-8f76-11ea-9aa9-378492b974b6.png)

in this case the tick, ONLY on _TvShows_ folder (not movies), is not given by the add-on, is netflix that establishing this, i can only remove the support to get this ticks or leave it as it is.
There is no way to determine whether all the episodes have been watched.

If you're talking about Kodi's library, i don't know what you are referring to

so to not always browse hundreds of lists items, exists the option to add to "my list"

**Comment by masca90021** [comment]
![screenshot000](https://user-images.githubusercontent.com/57955748/81153906-0af14980-8f8c-11ea-82d7-679f58564690.png)
![screenshot001](https://user-images.githubusercontent.com/57955748/81153911-0c227680-8f8c-11ea-85fb-c1f20359d1b9.png)
![screenshot002](https://user-images.githubusercontent.com/57955748/81153913-0cbb0d00-8f8c-11ea-9bf1-b09f030a8f21.png)

This is what I mean. Netflix decides you already watched that show if you just started watching it and it is marked as watched in the addon, this affecting the sorting for all the library. I always have to switch to "unwatched" and "all videos". Maybe just let Kodi decide the watched status instead of Netflix.

Sorry if I wasn't more clearer previously, was still at work and couldn't upload screens.

Ty in advance!

**Comment by CastagnaIT** [comment]
_What i am writing now, only applies when the settings_ `[WIP] Synchronize the watched status of the videos with Netflix` add-on setting is disabled.

In the case of screenshot 2: the movie is marked as partially watched.
you would say it is marked wrong? that you have watched at 100%?
in this case, this is a behaviour of Kodi core, it is not configurable by add-on
There are special parameters to change this behavior explained in the Kodi wiki but this will reflect to all Kodi system.
Or else you can still manually change the watched status by using the context menu.

In the case of screenshot 3: The TvShow is marked as watched.
here i could only remove this function provided from Netflix or reading the watched status (the tick will no longer be displayed, under any circumstances)

**Comment by masca90021** [comment]
Can't it be done to work as Kodi works ? I have the [WIP] option enabled.

The movie is ok, it is only partially watched in Netflix and partially watched in the addon, so it is ok. The issue is only with tv shows now, the moment you watch 1 episode it marks all show as seen and you have to enable all videos to find it again. In the case of fresh prince I watched season 1 and half of season 2 but, as you can see, you have to have all videos enabled to appear, even in continue watching.

**Comment by CastagnaIT** [comment]
the only info that netflix provide is "true" or "false" when a tvshow is started to watch
there are no other info.
This boolean info is used to mark as watched a tvshow folder.

as explained before the only thing that i could do is remove this info, but i do not think that this resolve your problem because all tvshow are no marked as watched..

I see no other solution

**Comment by masca90021** [comment]
I understand now, Netflix only offers true or false, nothing more as far as info goes. No worries, no point in working more just for this. Just gonna switch it from settings when I start the addon and put it back when I watch movies on my media player. Ty for your answers.
