### ISSUE TITLE
HD and UHD playback not working on Android Devices - Netflix 1.2.1

### ISSUE THREAD

**Issue by knappster1** [CastagnaIT/plugin.video.netflix#626]
#### Your Environment
- Netflix add-on version: 1.2.1
- Operating system version/name: Android 
- Device model:  NVIDIA Shield

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

After updating to 1.2.1 yesterday, HD and UHD playback stopped working on NVIDIA Shield.  Standard def still appears to work.  If I downgrade to 1.2.0, playback works fine as well.

#### Expected behavior

When I playback After Life (4K) or Bee Movie (1080p) playback should begin.

#### Actual behavior

I believe that the sequence is the loading dial turns on briefly while kodi selects the screen resolution / framerate.  The dial goes away, then the screen dims as if playback is about to begin.  Then the dial comes back indefinitely until I hit stop/exit.

#### Steps to reproduce the behavior

1. Select Movie or TV Show to play

### Debug log

The debug log can be found from this link:
https://drive.google.com/file/d/14ld0DILBreyRv9_5BIQHpVRolUcmPh7H/view?usp=sharing
I attempted to play in this order:

After Life (Season 2 episode 1) - 4K did not play
Bee Movie - 1080p did not play
The IT Crowd - 540p played
All work on 1.2.0 so I have reverted to it.

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by shirtjs** [comment]
Can reproduce on Fire TV Stick 4k.

**Comment by mano3m** [comment]
Same on Fire TV stick 4k

**Comment by knappster1** [comment]
I've updated the topic description based on your comments and other users on kodi forums reporting other android devices:

https://forum.kodi.tv/showthread.php?tid=329767&pid=2947318#pid2947318

**Comment by CastagnaIT** [comment]
I think i incorrectly fixed the conversion of the protection

Someone can try? only Kodi 18.x:
[plugin.video.netflix_1.2.1_20200507.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4592230/plugin.video.netflix_1.2.1_20200507.zip)

**Comment by knappster1** [comment]
Thanks for the quick turnaround.  That is working for me.  Might be coincidence, but it would only play 4k once I turned "force hdcp 2.2 videostreams" on.  When I first noticed the playback issue on May 5, I ran the addon configuration wizard in expert settings in case something was corrupted, so that may have something to do with it.  If you want any more logs, just let me know.  Thanks again!

**Comment by CastagnaIT** [comment]
well i will wait some other confermations then will do a new release

the `force hdcp 2.2 videostreams` was used by older versions of this add-on
all latest add-on versions automatically configure themselves according device specs

**Comment by debutanker** [comment]
Many thanks for your effort!
Also working here on Kodi 18.6 and Shield TV Pro 19.

**Comment by knappster1** [comment]
Thanks @CastagnaIT 

To close the loop...
`force hdcp 2.2 videostreams`
consistently made a difference with the modified 1.2.1.  I have upgraded to 1.2.2 and it seems to work at 4K regardless of this setting now.

I will close this issue in a day or two to give some time to anybody else who may have auto-updated to 1.2.1 but not 1.2.2 yet.

**Comment by tofrus** [comment]
Hi,

Sorry for opening this issue again. Tested on Mi TV 4 55 Inch.

After following all the steps on "**My android device supports 4K but does not playback at 4K**" it's still not getting 4K. After turning on "**force hdcp 2.2 videostreams**" it finally able to run on 4K. So @CastagnaIT may add that on the "**My android device supports 4K but does not playback at 4K**" section.

Thank you so much for the add-on btw.

**Comment by CastagnaIT** [comment]
"force hdcp 2.2 videostreams" shoud not be used

if 4k not works means something is wrong,
can be some settings
or your device has some particolarity to be analyzed

**Comment by tofrus** [comment]
> "force hdcp 2.2 videostreams" shoud not be used
> 
> if 4k not works means something is wrong,
> can be some settings
> or your device has some particolarity to be analyzed

I see, Is it bad if I turned it on? However, I see no issue if I turned it on and the 4k running smoothly.

**Comment by CastagnaIT** [comment]
until it works,
in the future if it doesn't work anymore, you already know why...

**Comment by tofrus** [comment]
> until it works,
> in the future if it doesn't work anymore, you already know why...

Ah okay got it, thanks for the info and the add-on, I really appreciate it.
