### ISSUE TITLE
Addon error Timeout: Timed out

### ISSUE THREAD

**Issue by Monkeyking66** [CastagnaIT/plugin.video.netflix#629]
#### Your Environment
- Netflix add-on version: 1.2.2
- Operating system version/name: Windows 10
- Device model: i3 mini PC, 8gb ram

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [X] Windows

### Describe the bug
When attempting to open the addon an error is returned statingAddon Signal Call Time out or if i enable IPC it returns Timeout: Timed out. I've tried reinstalling the addon, Enabling the IPC option, reinstalling Kodi as well switching between plugin versions 1.2.2, 1.2.0 and 1.2.2 all with the same result.
After re-installing the addon does prompt me for my credentials but after validating these it goes back the same error.

#### Expected behavior
The plugin used to display the select user profile screen at this point.

#### Actual behavior
Error Modal appears with the warning and informs me to review the common issues on the wiki site and informs me the error has been written to the Kodi log file

#### Steps to reproduce the behavior

1. Start Kodi
2.Go to addons
3.Select Netflix Addon
4. Error Message appears.

### Debug log

The debug log can be found from this link:
https://1drv.ms/u/s!AvdWC1NZKdb5piB_-xG4Yulw5pRw?e=DlwABO
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4603434/kodi.log)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ x ] I'm using a different source

**Comment by CastagnaIT** [comment]
This timeouts are not an add-on bug

> error: [Errno 10053] An established connection was aborted by the software in your host machine

all error that means something wrong in your localhost network configuration of your device or software that disallow communications
there is nothing to do here

**Comment by Monkeyking66** [comment]
Thanks for the quick response, I'm going to completely remove Kodi with its user data and try a fresh install. I've tried resetting the network and unfortunately, the issue has persisted.

**Comment by Monkeyking66** [comment]
So I've completed the complete remove and re-install of Kodi and re-installed the addon (v1.2.2) and the issue persisted, I then rolled back to v1.2.1 using the update option from the addons menu, it gave me the same error but then successfully logged in, I went back to the addon menu to confirm my results and when I tried to log in again the issue re-occurred, I then rolled back to version v1.2.0 and the system worked again.
It's just a shot in the dark but I'd like to understand a little more about the signal calls component in this case, does switching versions somehow recover the signal calls component? Are there any major differences between the available versions that could be helping or causing my issue?

**Comment by CastagnaIT** [comment]
there is no changes to IPC communication all versions use the same method

**Comment by Monkeyking66** [comment]
Cool, it now seems to be hit and miss as to whether I can open the addon but switching between the Netflix addon versions does seems to recover the Signal call addon which then allows me to log in.

**Comment by hoksilato2** [comment]
I'm in raspi4 with libreelec 9.2.1 (kodi 18) and I have the same error with last update 1.2.2:

> Exception: addon Signals call timeout

But I can watch movies without problems. The error is enoying because popping all time in the kodi menu.

**Comment by CastagnaIT** [comment]
libreelec 9.2.1 on rpi has this problem here i can do nothing
