### ISSUE TITLE
System freeze on playing any episode of a particular series

### ISSUE THREAD

**Issue by helltp** [CastagnaIT/plugin.video.netflix#63]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
 Raspberry Pi 3 B
 OSMC 2019.04-1
 Kodi v18 stable
### Addon version used
 0.14.0
### Description
Right after the addon was installed tried to play S01E02 of Love, the addon prompted me to 
install widevine from ChromeOS. I started it then after half an hour later it was still busy (the 
circular loading animation was still going on the middle of the screen) but the top right corner 
indicated that the episode has started and it is playing. I left it like that overnight (~12h). Next morning it still did the circular animation so I restarted the whole system. Tried to play some episode of Rick and Morty, and it palyed fine. Then I tried to play some episode of Love and it did the same, circular loading animation, play indicator on top right corner, but it was not able to play the video again. so I tried to stop the video that was "playing" and the whole system freezed.
 
Later I tried several series (incl. Rick and Morty, Stranger Things etc.) and all worked fine, but it can not play the episoed of Love.
### Steps to Reproduce

1. Try to play any episode of the series Love
2. Let it buffer a bit, wait for the playing indicator to show up on the top right corner of the screen
3. If it can not play it exit back out (note that the play icon is still on the top right corner)
4. Make the "playing" video fullscreen and try to stop it. (Or just stop it via webui or andriod app.)
5. freeze

**Expected behavior:** 
play the video
**Actual behavior:** 
freeze
Still can be rebooted over SSH so I suspec that just the kodi froze.
## Context (Environment)
 Raspberry Pi 3 B
 OSMC 2019.04-1
 Kodi v18 stable
### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

 Raspberry Pi 3 B
 OSMC 2019.04-1
 Kodi v18 stable
 With Kodi's default skin.

## Debug log

Hosted on google drive:
[https://drive.google.com/open?id=1_3HnAOL_m3EKmoDfWgyAmL6q6Nd2_k7N](https://drive.google.com/open?id=1_3HnAOL_m3EKmoDfWgyAmL6q6Nd2_k7N)

**Comment by CastagnaIT** [comment]
so try goto addon expert settings
disable HEVC profile and enable VP9 profile

**Comment by arfejes** [comment]
Thanks! It is now working properly. Any ideas why this is happening on some series?
