### ISSUE TITLE
it was not possible to get the data from widevine cryptosession

### ISSUE THREAD

**Issue by zagwalker** [CastagnaIT/plugin.video.netflix#630]
#### Your Environment
- Netflix add-on version: 1.2.2
- Operating system version/name: Android 5.1.1
- Device model:  Xiaomi TV 3

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request
Plugin does not run with error `it was not possible to get the data from widevine cryptosession`

Kodi log shows another error: `MediaDrm: Failure creating instance`

DRMInfo app says Google Widvine modular DRm is not supported.

Is there anything I can do in order to run the app?

Thanks in advance
Lev

**Comment by CastagnaIT** [comment]
> DRMInfo app says Google Widvine modular DRm is not supported

this is your answer...
your device not support DRM Widevine content
