### ISSUE TITLE
Wiki correction.

### ISSUE THREAD

**Issue by procobain** [CastagnaIT/plugin.video.netflix#633]
Just a small correction that made me lose a few seconds.

On the Wiki, in the prerequisites, it is written Cryptdome, the correct one is cryptodome.

Thanks for the project, hugs.

https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon

**Comment by npmstart-pray** [comment]
Pycryptodome, isn’t it?

**Comment by CastagnaIT** [comment]
thanks yes is pycryptodome
will change
