### ISSUE TITLE
Auto-update and Sync profile has stopped working

### ISSUE THREAD

**Issue by brainfork** [CastagnaIT/plugin.video.netflix#634]
#### Your Environment
- Netflix add-on version: 1.2.2
- Operating system version/name: Windows 7
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug
Auto-updating and synchronization has stopped working.  TV shows have to be manually updated and it is no longer possible to export movies to a local library

#### Expected behavior
Adding movies and/or TV shows to the Netflix "My List" should result in them being synced to a local library automatically.

#### Actual behavior
Adding movies and/or TV to the Netflix "My List" results in no change to the local library after a day, a week, or a month (so far).

#### Steps to reproduce the behavior

1. Add content to the Netflix "My List"
2. Observe that it's never atuo-synced to your local library

### Debug log

The debug log can be found from this link:
https://pastebin.com/7Kg3VhKD

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
the log is useless without netflix debug verbose

**Comment by CastagnaIT** [comment]
I think I found the problem anyway
try this and let me know:
[plugin.video.netflix_1.2.2_20200512_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4614265/plugin.video.netflix_1.2.2_20200512_t1.zip)

**Comment by brainfork** [comment]
Sorry about the log-level, I'll make note of that for future tickets.

Prior to me installing the update, it looks like a movie was synced to my library, but still missing new TV episodes.  I've installed the update in the zip you attached, set my update time to 5pm EDT, and have turned on verbose logging, I'll update the ticket with the results later.

**Comment by brainfork** [comment]
The issue seems to have been fixed with the update, both movies and shows that I've added to My List started showing up in my local library again.  [Here](https://docs.google.com/document/d/1xofWkW9eICkJGzH1F_z6NPCsz47cguFmUbExTXW58nM/edit?usp=sharing) is a combo of my kodi.old.log and kodi.log, the former should show an auto-sync of My List to the library and the latter should show a manual update.

**Comment by brainfork** [comment]
I'm actually still seeing weird issues, there's a show called "The Hollow" that just had it's second season come out.  I can see the second season in the Netflix lists, but all of the second season episodes are refusing to export.  Here's a verbose [log file](https://docs.google.com/document/d/14h8HynSWRLsWrAVG1ILULoqLX_WH-0zNTNjcsHfgJPk/edit?usp=sharing) of my starting up Kodi, navigating to the relevant show in Netflix, and attempting to manually export new episodes.

**Comment by CastagnaIT** [comment]
i think was a cache issue,
i can not reproduce to my local pc

can you try?
[plugin.video.netflix_1.2.2_20200514_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4626872/plugin.video.netflix_1.2.2_20200514_t2.zip)

**Comment by brainfork** [comment]
That appears to have fixed the issue, the second season episodes were exported
