### ISSUE TITLE
Netflix Error check the log for more information. Raspbian + RaspberyPi B3

### ISSUE THREAD

**Issue by Kacperos89** [CastagnaIT/plugin.video.netflix#64]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X] support request

## General information

I install Netflix from zipfile from here, and after install Netflix will not open. I get information "Netflix Error check the log for more information"

### Addon version used

Version 0.14.0
CastagnaIT Respository

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM) ---------- Raspberry Pi B3
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

I use Raspberry pi B3 with installed raspbian from RetroPie.org.uk it is original raspbian from RaspberryPi.org but with some applications cut out.

I install kodi by use sudo apt-get install kodi

## Debug log

https://pastebin.com/mtv0Fqqr

**Comment by CastagnaIT** [comment]
you forgot to install Cryptdome, read the readme on the main page

**Comment by Kacperos89** [comment]
OMG. Thank You very much for help me with this :)

But I have another issue. To watch some in Netflix I need inputstream.adaptive but i don't have VideoPlayer InputStream category in My-Addon section :/

**Comment by CastagnaIT** [comment]
goto menu addon->install from repository->select kodi rep.->scroll to video player inputstream install it
