### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by etown** [CastagnaIT/plugin.video.netflix#641]
## Feature request
I'm submitting a proposal to ...
  - [X ] new feature

I would like to know what would be involved with adding iOS support. I assume it would mean not using widevine and use something like FPS. Any guidance or suggestions is much appreciated. Thank you.

**Comment by CastagnaIT** [comment]
We rely to DRM supported from nf website system

Netflix website support FairPlay with Safari browser,
with keysystem "com.apple.fps.2_0" (i think should be used with license type)
and nf specs say that videos max resolution is 1080p.

First of all you need to implement FairPlay DRM to InputStream Adaptive:
https://github.com/peak3d/inputstream.adaptive/wiki
currently is not implemented

_Only after this_ - you can think of add implemetation to nf addon

On NF addon is needed to implement something like android crypto module:
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/services/msl/android_crypto.py

You need of an apple ecosystem to debug and test the various implementations, and analyze networks communications to understand how works the NF website with Safari browser and FairPlay DRM.

I can only make suggestions but not implement it (on addon side),
i do not have apple products
