### ISSUE TITLE
Audio Passthrough Not Working

### ISSUE THREAD

**Issue by FolkSong** [CastagnaIT/plugin.video.netflix#65]
*I'm submitting a ...*
  - [*] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used
0.14.0

### Description

Audio is sent to my receiver as PCM rather than Dolby Digital, even though passthrough is enabled.

### Installation

* [*] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [*] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Windows 10

## Debug log

https://gist.github.com/FolkSong/ae9d6cdac5868135a6381796b6b230a0#file-kodi2-log

## Other information

Non-Netflix content through Kodi does passthrough correctly, so it's not a Kodi issue. The Windows Store Netflix app also does passthrough, so it's not Netflix itself or my PC.

I see the log shows "Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, no pass-through)"

**Comment by CastagnaIT** [comment]
if the receiver gets audio pcm
means that on the kodi audio settings you have not selected wasapi default device
and you didn't put the flag on multi-channel streams

**Comment by FolkSong** [comment]
Thank you, I didn't know wasapi was required for DD+. With that change Kodi seems to be sending the passthrough signal, but it turns out my receiver doesn't decode DD+.

My new question is, how are other Netflix devices able to output standard DD rather than DD+? I can use them with the same receiver and they send raw AC3/DD.

I did find a workaround which is to set number of channels to 2 in Kodi's audio settings, then in the passthrough section there's an option to transcode DD+ to DD and that works (it still comes out as 5.1). Maybe this is what the other devices do?

**Comment by CastagnaIT** [comment]
I don't know which devices you talking, but everyone has their own way of decoding and transporting the stream, also depends on how work their operating system, can't make a comparison..

so your practice is unusual, who has a receiver produced in the last 6/7 years can decode DD+ streams

however we can only get DD+ streams...

**Comment by FolkSong** [comment]
Ok thanks! My receiver is about 8 years old so that's why.
