### ISSUE TITLE
KeyError and KeyError lolomo after select profile

### ISSUE THREAD

**Issue by jamtwister** [CastagnaIT/plugin.video.netflix#651]
## Bug report
Starting netflix addon, immediately after select profile, results in KeyError.
Please look at log for more details. 

#### Your Environment
- Netflix add-on version: Version 1.3.2
- Operating system version/name: OSMC 2020.03-1 with Kodi 18.6
- Device model:  Raspberry Pi 3 Model B Rev 1.2

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi OSMC
* [ ] Windows

### Describe the bug
After selecting the profile, the KeyError is shown.
It worked 2 days ago with version 1.3.1. I tried it with version 1.3.0 / 1.3.1 / 1.3.2. The result is always the same -> KeyError
For more details please have a look at the log file.

#### Expected behavior
No KeyError should be raised when selecting the profile.

#### Actual behavior
After selecting the profile, the KeyError is shown. After error confirmation, it stays at the profile selection

#### Steps to reproduce the behavior
1. open video addons
2. select netflix and confirm
3. select your profile and confirm

### Debug log
The debug log can be found from this link:
https://paste.kodi.tv/ewujemosiw.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
* [x] installed from repository castagnait with was added with repository.castagnait-1.0.1.zip

**Comment by CastagnaIT** [comment]
Hi
i need a new log updated with this:
[plugin.video.netflix_1.3.2_20200522_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4666459/plugin.video.netflix_1.3.2_20200522_t1.zip)

**Comment by jamtwister** [comment]
Hi
here is the new log. I hope it contains the info you need ;)
https://paste.kodi.tv/iwaroketub.kodi

**Comment by CastagnaIT** [comment]
well seem that netflix has changed again some data...

I believe that the rollout of this new change is slow, in my country there's still no sign of this change

you will have to wait and see how to proceed
because as i can see from your data, there will be other problems to solve as well

**Comment by tweimer** [comment]
@CastagnaIT If it helps you, Im having the same error. I'm attaching my logs here as well:
[log-2020-05-23-20.10.54.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4672456/log-2020-05-23-20.10.54.zip)

The above build is for Leia, doesn't run on my Kodi Matrix. If you would provide me with a build for Matrix, I can repeat that test.

I could also test debug builds for you.

I guess, unless you have a fix, there is no workaround for the problem.

**Comment by CastagnaIT** [comment]
the only way to understand what these new changes consist of is to debug the browser communications, so i will have to wait for these changes to be implemented to the whole netflix community

if you do not using the sync of watched status, i think is possible try to exclude part of the source code

**Comment by orclex** [comment]
Same problem on LibreElec 9.2.2 x64 with Netflix add-on 1.3.0/1.3.1/1.3.2 in Germany.
If you need an additional log file, grab this one:

https://paste.ubuntu.com/p/htNSpczmGb/

Thanks!

**Comment by CastagnaIT** [comment]
i found some info from website, with this should start netflix but i need to fix the sync of watched status

then i need a new verbose debug log, in this way:
- update with this
[plugin.video.netflix_1.3.2_20200525_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4677128/plugin.video.netflix_1.3.2_20200525_t3.zip)
- open netflix (if no errors go next steps)
- reboot kodi
- open netflix again and now extract the log

**Comment by tweimer** [comment]
@CastagnaIT Do you have it for Matrix too?

**Comment by CastagnaIT** [comment]
Added to the post

**Comment by tweimer** [comment]
Wow, that looks good. Here are the logs. 
[log-2020-05-25-17.41.33.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4678329/log-2020-05-25-17.41.33.zip)

**Comment by CastagnaIT** [comment]
i need a nf debug log instruction in readme

**Comment by tweimer** [comment]
Sorry. Is this verbose enough?

[log-2020-05-25-18.26.39.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4678460/log-2020-05-25-18.26.39.zip)

**Comment by CastagnaIT** [comment]
seem that LE do not output print command try use this:
[plugin.video.netflix_1.3.2+matrix.1_20200525_t3edited.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4678475/plugin.video.netflix_1.3.2%2Bmatrix.1_20200525_t3edited.zip)

**Comment by tweimer** [comment]
Here you go:
[log-2020-05-25-18.40.16.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4678493/log-2020-05-25-18.40.16.zip)

**Comment by CastagnaIT** [comment]
now i see the data
but there is no what i assumed

please try reboot the device and get a new log after opened a profile

**Comment by tweimer** [comment]
This is a complete login sequence on a clean install: 
[log-2020-05-25-19.00.55.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4678546/log-2020-05-25-19.00.55.zip)

**Comment by CastagnaIT** [comment]
no sad....
if you have reinstalled the addon by deleting also addon data
you have reset the web session, i need a pre existent web session active
or do not return different data

now you have to reboot kodi again and get another log...

**Comment by tweimer** [comment]
Okay, I made two new logs. Am I doing it right this time?
[log-2020-05-25-19.13.42.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4678583/log-2020-05-25-19.13.42.zip)
[log-2020-05-25-19.15.58.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4678584/log-2020-05-25-19.15.58.zip)

**Comment by CastagnaIT** [comment]
I can not know for sure because i can not make comparisons, in my country there are not yet these changes, i can make only suppositions

so the data is there, but netflix doesn't seem to provide the lists i need anymore, at least for now...(locos list is empty)

I think there are two solutions:
- temporary disable "sync watched status with netflix" with the accounts that use the new method, until in my country netflix rollout the changes
- try to implement a temporary workaround, perhaps i can resume old code but need testers offering to test changes

**Comment by tweimer** [comment]
Well, I can test things for you.

**Comment by thiagolamosa** [comment]
I can help testing as I'm facing the same error.

**Comment by CastagnaIT** [comment]
@tweimer  i need a first log:
1 Assure that sync of watched status setting is already enabled before update
2 update addon
[plugin.video.netflix_1.3.2+matrix.1_20200526_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4682365/plugin.video.netflix_1.3.2%2Bmatrix.1_20200526_t1.zip)
3 open addon and select a profile
4 extract log

**Comment by tweimer** [comment]
Here we go again:
[log-2020-05-26-17.34.46.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4683982/log-2020-05-26-17.34.46.zip)

**Comment by CastagnaIT** [comment]
nothing the log is incompresible
is better if you extract the real kodi.log not the libreelec parsed log
with samba.conf
map log directory with

<pre>
[LogfilesTemp]
  path = /storage/.kodi/temp
  available = yes
  browseable = yes
  public = yes
  writeable = yes
  root preexec = mkdir -p /storage/koditemp
</pre>

**Comment by tweimer** [comment]
Here you go: 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4684548/kodi.log)

**Comment by Borromini** [comment]
I was bitten by this error too today. I tested plugin.video.netflix_1.3.2_20200525_t3.zip on LibreELEC 9.2.2. Log attached: [kodi-20200526.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4684833/kodi-20200526.log)

The thing is, I don't get a KeyError on every show I try to select; e.g. Space Force persistently gives that error, but selecting another show works. Do you need me to up the loglevel?

**Comment by CastagnaIT** [comment]
@tweimer yes now is the original kodi log, but you have forgot to enable Kodi debug setting

**Comment by tweimer** [comment]
Sorry. Now I have enabled it.[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4689331/kodi.log)

**Comment by CastagnaIT** [comment]
this time you forgot to open an netflix profile..

**Comment by tweimer** [comment]
Well, this is what I did:
- Start Libreelec
- Open Netflix addon
- Now I see a list of profiles.
- I open the Owner profile ("Tobias")
- I select some random movie to watch.
- Repeated this a few times.
I am so sorry for wasting your time. I have done what you said to my best knowledge, but maybe I'm missing some important step.

I read some parts about *lolomo* in there, but no *loco*.

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4689453/kodi.log)

**Comment by CastagnaIT** [comment]
Even you can see that the log is incomplete

also the last log missing all the operations you mentioned...
i do not know why, perhaps you extract the log before doing your operations?

**Comment by tweimer** [comment]
Well, now I find smth with *loco*: 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4689575/kodi.log)

Extracted {'isLocoSupported': True}
LOCO ROOT ID: bda0e70b-ae48-409e-90ce-7a4bdef4d8b2_ROOT

> 2020-05-27 16:56:47.366 T:564     DEBUG <general>: [plugin.video.netflix (0)] Registered AddonSignals slot queue_video_event to <bound method EventsHandler.callback_event_video_queue of <EventsHandler(Thread-7, initial)>>
> 2020-05-27 16:56:47.369 T:842     DEBUG <general>: [plugin.video.netflix (0)] [Event queue monitor] Thread started
> 2020-05-27 16:56:47.380 T:564     DEBUG <general>: [plugin.video.netflix (0)] Executing GET request to https://www.netflix.com/login
> 2020-05-27 16:56:47.550 T:841     DEBUG <CAddonSettings[plugin.video.netflix]>: loading setting definitions
> 2020-05-27 16:56:47.550 T:841     DEBUG <CAddonSettings[plugin.video.netflix]>: trying to load setting definitions from old format...
> 2020-05-27 16:56:47.558 T:841     DEBUG <CAddonSettings[plugin.video.netflix]>: loading setting values
> 2020-05-27 16:56:47.595 T:841      INFO <general>: [plugin.video.netflix (9)] Debug logging level is Verbose
> 2020-05-27 16:56:47.595 T:841     DEBUG <general>: [plugin.video.netflix (9)] Trying connection to the database nf_local.sqlite3
> 2020-05-27 16:56:47.596 T:841     DEBUG <general>: [plugin.video.netflix (9)] Database connection nf_local.sqlite3 was successful (SQLite ver. 3.31.1)
> 2020-05-27 16:56:47.967 T:841     DEBUG <general>: [plugin.video.netflix (9)] Trying connection to the database nf_shared.sqlite3
> 2020-05-27 16:56:47.968 T:841     DEBUG <general>: [plugin.video.netflix (9)] Database connection nf_shared.sqlite3 was successful (SQLite ver. 3.31.1)
> 2020-05-27 16:56:48.000 T:841      INFO <general>: [plugin.video.netflix (9)] Debug logging level is Verbose
> 2020-05-27 16:56:48.001 T:841      INFO <general>: [plugin.video.netflix (9)] Started (Version 1.3.2+matrix.1)
> 2020-05-27 16:56:48.001 T:841      INFO <general>: [plugin.video.netflix (9)] URL is ParseResult(scheme='plugin', netloc='plugin.video.netflix', path='/', params='', query='', fragment='')
> 2020-05-27 16:56:48.012 T:841     DEBUG <general>: [plugin.video.netflix (9)] Executing JSON-RPC: {"jsonrpc": "2.0", "method": "Profiles.GetCurrentProfile", "id": 1, "params": {"properties": ["thumbnail", "lockmode"]}}
> 2020-05-27 16:56:48.017 T:841     DEBUG <general>: [plugin.video.netflix (9)] Add-on was initiated by an external call - workaround enabled time elapsed 0s
> 2020-05-27 16:56:49.023 T:564     DEBUG <general>: [plugin.video.netflix (0)] Request took 1.4720949999999959s
> 2020-05-27 16:56:49.025 T:564     DEBUG <general>: [plugin.video.netflix (0)] Request returned statuscode 200
> 2020-05-27 16:56:49.026 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to _request_call took 1475ms
> 2020-05-27 16:56:49.027 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracting reactContext JSON
> 2020-05-27 16:56:49.078 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to extract_json took 60ms
> 2020-05-27 16:56:49.078 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracting api urls from webpage
> 2020-05-27 16:56:49.078 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'auth_url': '1590591408642.ikEyxxR5FXpcu3oOYDLcUnTRWnc='}
> 2020-05-27 16:56:49.078 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'api_endpoint_root_url': 'https://www.netflix.com/api'}
> 2020-05-27 16:56:49.078 T:564     ERROR <general>: [plugin.video.netflix (0)] Could not extract ['models', 'playerModel', 'data', 'config', 'ui', 'initParams', 'apiUrl']
> 2020-05-27 16:56:49.079 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'request_id': 'fedc4e5d-7674-4cd0-8254-c47bc1846074-151780809'}
> 2020-05-27 16:56:49.079 T:564     ERROR <general>: [plugin.video.netflix (0)] Could not extract ['models', 'playerModel', 'data', 'config', 'core', 'assets', 'core']
> 2020-05-27 16:56:49.079 T:564     ERROR <general>: [plugin.video.netflix (0)] Could not extract ['models', 'playerModel', 'data', 'config', 'ui', 'initParams', 'uiVersion']
> 2020-05-27 16:56:49.079 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'browser_info_version': '78.0.3904.92'}
> 2020-05-27 16:56:49.079 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'browser_info_os_name': 'Chrome OS'}
> 2020-05-27 16:56:49.079 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'browser_info_os_version': '12371.89.0'}
> 2020-05-27 16:56:49.079 T:564     DEBUG <general>: [plugin.video.netflix (0)] Logging in...
> 2020-05-27 16:56:49.107 T:564     DEBUG <general>: [plugin.video.netflix (0)] Executing POST request to https://www.netflix.com/login
> 2020-05-27 16:56:50.531 T:841     DEBUG <general>: [plugin.video.netflix (9)] Routing navigation request
> 2020-05-27 16:56:50.587 T:841     DEBUG <general>: [plugin.video.netflix (9)] Initializing "Directory" with params: {}
> 2020-05-27 16:56:50.587 T:841     DEBUG <general>: [plugin.video.netflix (9)] Invoking action: root
> 2020-05-27 16:56:50.611 T:841     DEBUG <general>: [plugin.video.netflix (9)] Handling AddonSignals IPC call to get_profiles
> 2020-05-27 16:56:51.207 T:564     DEBUG <general>: [plugin.video.netflix (0)] Request took 1.1468720000000019s
> 2020-05-27 16:56:51.207 T:564     DEBUG <general>: [plugin.video.netflix (0)] Request returned statuscode 200
> 2020-05-27 16:56:51.209 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to _request_call took 1151ms
> 2020-05-27 16:56:51.210 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracting session data...
> 2020-05-27 16:56:51.210 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracting reactContext JSON
> 2020-05-27 16:56:51.263 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to extract_json took 63ms
> 2020-05-27 16:56:51.263 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracting userdata from webpage
> 2020-05-27 16:56:51.264 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'name': 'Tobias'}
> 2020-05-27 16:56:51.264 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'guid': 'OUAASENCNNAG5M5MDRMIZN5KUM'}
> 2020-05-27 16:56:51.264 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'userGuid': 'OUAASENCNNAG5M5MDRMIZN5KUM'}
> 2020-05-27 16:56:51.264 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'countryOfSignup': 'DE'}
> 2020-05-27 16:56:51.265 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'membershipStatus': 'CURRENT_MEMBER'}
> 2020-05-27 16:56:51.265 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'isTestAccount': False}
> 2020-05-27 16:56:51.265 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'deviceTypeId': 781}
> 2020-05-27 16:56:51.265 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'isAdultVerified': True}
> 2020-05-27 16:56:51.265 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'isKids': False}
> 2020-05-27 16:56:51.265 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'pinEnabled': True}
> 2020-05-27 16:56:51.266 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'BUILD_IDENTIFIER': 'v1b8c742f'}
> 2020-05-27 16:56:51.266 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'preferredLocale': {'country': 'DE', 'language': 'de', 'dir': 'ltr', 'isCursive': False, 'doubleByte': False, 'hasExtendedDiacritics': False, 'default': True, 'id': 'de-DE'}}
> 2020-05-27 16:56:51.266 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'isLocoSupported': True}
> 2020-05-27 16:56:51.267 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to extract_userdata took 3ms
> 2020-05-27 16:56:51.267 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracting api urls from webpage
> 2020-05-27 16:56:51.267 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'auth_url': '1590591409947.nGlDajsUUv1qm8+VkCYV3ENjGEQ='}
> 2020-05-27 16:56:51.267 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'api_endpoint_root_url': 'https://www.netflix.com/api'}
> 2020-05-27 16:56:51.267 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'api_endpoint_url': 'https://www.netflix.com/api/shakti/v1b8c742f'}
> 2020-05-27 16:56:51.268 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'request_id': '8b3bfb03-3999-4313-9a04-6361b789161a-31695885'}
> 2020-05-27 16:56:51.268 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'asset_core': 'https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0023.527.011.js'}
> 2020-05-27 16:56:51.268 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'ui_version': 'shakti-v1b8c742f'}
> 2020-05-27 16:56:51.268 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'browser_info_version': '78.0.3904.92'}
> 2020-05-27 16:56:51.268 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'browser_info_os_name': 'Chrome OS'}
> 2020-05-27 16:56:51.269 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracted {'browser_info_os_version': '12371.89.0'}
> 2020-05-27 16:56:51.269 T:564     DEBUG <general>: [plugin.video.netflix (0)] Extracting falcorCache JSON
> 2020-05-27 16:56:51.293 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to extract_json took 24ms
> 2020-05-27 16:56:51.294 T:564     DEBUG <general>: [plugin.video.netflix (0)] Parsing profile OUAASENCNNAG5M5MDRMIZN5KUM
> 2020-05-27 16:56:51.298 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'profileName': 'Tobias'}
> 2020-05-27 16:56:51.305 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isAccountOwner': True}
> 2020-05-27 16:56:51.309 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isKids': False}
> 2020-05-27 16:56:51.312 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'maturityLevel': 'ADULTS'}
> 2020-05-27 16:56:51.325 T:564     DEBUG <general>: [plugin.video.netflix (0)] Parsing profile ED6JVF5PKZDNNLBBFNJP6IPR34
> 2020-05-27 16:56:51.329 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'profileName': 'Uwe'}
> 2020-05-27 16:56:51.335 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isAccountOwner': False}
> 2020-05-27 16:56:51.340 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isKids': False}
> 2020-05-27 16:56:51.343 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'maturityLevel': 'ADULTS'}
> 2020-05-27 16:56:51.355 T:564     DEBUG <general>: [plugin.video.netflix (0)] Parsing profile NGGWWXVEMZEJPH45SAL7UBPQ6M
> 2020-05-27 16:56:51.358 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'profileName': 'Verena'}
> 2020-05-27 16:56:51.365 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isAccountOwner': False}
> 2020-05-27 16:56:51.371 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isKids': False}
> 2020-05-27 16:56:51.375 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'maturityLevel': 'ADULTS'}
> 2020-05-27 16:56:51.388 T:564     DEBUG <general>: [plugin.video.netflix (0)] Parsing profile IJU2TEQVFNH3XAKTUGQHQTHXKM
> 2020-05-27 16:56:51.392 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'profileName': 'Oliver'}
> 2020-05-27 16:56:51.398 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isAccountOwner': False}
> 2020-05-27 16:56:51.403 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isKids': False}
> 2020-05-27 16:56:51.406 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'maturityLevel': 'ADULTS'}
> 2020-05-27 16:56:51.418 T:564     DEBUG <general>: [plugin.video.netflix (0)] Parsing profile I4TAZ36QAZCHPNJWVTJTNLOV6Y
> 2020-05-27 16:56:51.421 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'profileName': 'Karsten'}
> 2020-05-27 16:56:51.427 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isAccountOwner': False}
> 2020-05-27 16:56:51.432 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'isKids': False}
> 2020-05-27 16:56:51.435 T:564     DEBUG <general>: [plugin.video.netflix (0)] Profile info {'maturityLevel': 'ADULTS'}
> 2020-05-27 16:56:51.482 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to parse_profiles took 186ms
> 2020-05-27 16:56:51.484 T:564     DEBUG <general>: [plugin.video.netflix (0)] LOCO ROOT ID: b2c58c4e-63b1-4f22-b5ad-6575442c7c76_ROOT
> 2020-05-27 16:56:51.540 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to extract_session_data took 310ms
> 2020-05-27 16:56:51.540 T:564      INFO <general>: [plugin.video.netflix (0)] Login successful
> 2020-05-27 16:56:51.549 T:564     DEBUG <general>: [plugin.video.netflix (0)] Cookies currently loaded:
>                                                    NetflixId (expires ts 1622127409 - remaining TTL 31535997 sec)
>                                                    SecureNetflixId (expires ts 1622127409 - remaining TTL 31535997 sec)
>                                                    clSharedContext (expires ts None - remaining TTL None sec)
>                                                    flwssn (expires ts 1590602209 - remaining TTL 10797 sec)
>                                                    memclid (expires ts 1622127411 - remaining TTL 31535999 sec)
>                                                    nfvdid (expires ts 1622127409 - remaining TTL 31535997 sec)
>                                                    
> 2020-05-27 16:56:51.555 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to _login took 3069ms
> 2020-05-27 16:56:51.619 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to get_profiles took 70ms
> 2020-05-27 16:56:51.620 T:564     DEBUG <general>: [plugin.video.netflix (0)] Performing key handshake. ESN: NFCDCH-01-GDWZXJ09FYK4KVTKKKNQHK3R24MT6F
> 2020-05-27 16:56:51.628 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to _encrypted_chunk took 0ms
> 2020-05-27 16:56:51.628 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to handshake_request took 8ms
> 2020-05-27 16:56:51.629 T:564     DEBUG <general>: [plugin.video.netflix (0)] Executing POST request to https://www.netflix.com/nq/msl_v1/cadmium/pbo_manifests/%5E1.0.0/router
> 2020-05-27 16:56:51.645 T:840     DEBUG <general>: Thread waiting 1387246384 terminating
> 2020-05-27 16:56:51.645 T:841     DEBUG <general>: [plugin.video.netflix (9)] Execution time info for this run:
>                                                    make_call                       526 ms
>                                                    
> 2020-05-27 16:56:51.645 T:490     DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
> 2020-05-27 16:56:51.651 T:892     DEBUG <general>: Thread BackgroundLoader start, auto delete: false
> 2020-05-27 16:56:51.656 T:841      INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
> 2020-05-27 16:56:51.666 T:892     DEBUG <general>: Thread BackgroundLoader 1378853680 terminating
> 2020-05-27 16:56:51.958 T:564     DEBUG <general>: [plugin.video.netflix (0)] Request took 0.26339799999999514s
> 2020-05-27 16:56:51.958 T:564     DEBUG <general>: [plugin.video.netflix (0)] Request returned response with status 200
> 2020-05-27 16:56:51.961 T:564     DEBUG <general>: [plugin.video.netflix (0)] Call to _process_json_response took 3ms
> 2020-05-27 16:56:52.215 T:564     DEBUG <general>: [plugin.video.netflix (0)] Successfully saved MSL data to disk
> 2020-05-27 16:56:52.246 T:564     DEBUG <general>: [plugin.video.netflix (0)] Successfully saved MSL data to disk

**Comment by CastagnaIT** [comment]
finally! well
then i fixed a minor bug so:

now i need to know if the sync of watched status is updated also to android or apple original app

if you can do not use the owner profile

Steps:
- update
[plugin.video.netflix_1.3.2+matrix.1_20200527_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4689837/plugin.video.netflix_1.3.2%2Bmatrix.1_20200527_t3.zip)
- play an episode never watched or new tv show never watched (maybe better)
- playback the episode for minimum 3 minutes then stop video
- after stop video, wait 10 seconds (queue operations in background have to be done)
- Open original netflix app (android or apple), try to see if the episode red bar (of watched status) is visible and forward by 3 minutes

**Comment by tweimer** [comment]
Hi, sync on Android app is working. here is the log: 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4690654/kodi.log)
I hope it helps you

**Comment by mano3m** [comment]
I have the same issue on fire stick 4k since a few days. Can't get past the profile selection screen.

**Comment by thiagolamosa** [comment]
> finally! well
> then i fixed a minor bug so:
> 
> now i need to know if the sync of watched status is updated also to android or apple original app
> 
> if you can do not use the owner profile
> 
> Steps:
> - update
> [plugin.video.netflix_1.3.2+matrix.1_20200527_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4689837/plugin.video.netflix_1.3.2%2Bmatrix.1_20200527_t3.zip)
> - play an episode never watched or new tv show never watched (maybe better)
> - playback the episode for minimum 3 minutes then stop video
> - after stop video, wait 10 seconds (queue operations in background have to be done)
> - Open original netflix app (android or apple), try to see if the episode red bar (of watched status) is visible and forward by 3 minutes
> 
> and log as always

I'm facing the same problem on OSMC in a raspberry pi 3b.
How can I help?

**Comment by thiagolamosa** [comment]
I'm facing the same problem on OSMC in a raspberry pi 3b.
How can I help?

**Comment by CastagnaIT** [comment]
@tweimer i need a detail
the episode played was a tv show that had not been added to "my list"?

**Comment by tweimer** [comment]
@CastagnaIT No

**Comment by CastagnaIT** [comment]
well, all is ok, i think for now we have done

**Comment by thiagolamosa** [comment]
@CastagnaIT I can't install the zip file you uploaded. Is it only for Kodi 19?

**Comment by CastagnaIT** [comment]
the new release will be day 30 or 31
