### ISSUE TITLE
CoreELEC 9.2.2 Error Netflix

### ISSUE THREAD

**Issue by funthomaspr1** [CastagnaIT/plugin.video.netflix#652]
This is an error since the last update!
CoreELEC 9.2.2
The picture shows the link:
https://i.imgur.com/ceMeIXx.jpg 

Please help! Thx

**Comment by stevenhoving** [comment]
@funthomaspr1 Thanks for the bug report, please use the github search feature to search if your bug has already been reported. This helps keeping the github issues tab clean. Unfortunately there is not much you can do about it. There is 1 thing that you can try, and that is enabling the 'Enable ICP over HTTP' workaround. You can find this in the Expert panel of the netflix plugin settings menu. Please be aware that this workaround comes with its own set of limitations.

**Comment by funthomaspr1** [comment]
> @funthomaspr1 Thanks for the bug report, please use the github search feature to search if your bug has already been reported. This helps keeping the github issues tab clean. Unfortunately there is not much you can do about it. There is 1 thing that you can try, and that is enabling the 'Enable ICP over HTTP' workaround. You can find this in the Expert panel of the netflix plugin settings menu. Please be aware that this workaround comes with its own set of limitations.

I did it!  But unfortunately the error still exists!  😭 I can't watch any movies on Netflix!
