### ISSUE TITLE
Exception:Addon Signals call time out

### ISSUE THREAD

**Issue by shaolin-kongfu** [CastagnaIT/plugin.video.netflix#653]
#### Your Environment
- Netflix add-on version: 1.3.2
- Operating system version/name: coreelec 9.2.2
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
when I wanted to log in ,an  unexpected error has occurred.
''The add-on encountered the following error:
Exception:Addon Signals call time out
"
But everything is ok yesterday.
Could you help me ? Thx!

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

![2efcb0a6c3bb2811ab6bef1fb6097b4](https://user-images.githubusercontent.com/61420528/82664300-fe474380-9c63-11ea-9f72-170067f5bf6e.jpg)

**Comment by stevenhoving** [comment]
@CastagnaIT I know that it might become annoying by now but simply marking the bug as 'duplicate' sends the bug reporter the same message.

@shaolin-kongfu Your bug report is a duplicate, the 'ignored rules' label means that you did not search before you created this bug report. It seems that the signals timeout is bound to libreelec. While I don't really know how / why that is.

**Comment by stevenhoving** [comment]
See https://github.com/CastagnaIT/plugin.video.netflix/issues/652#issuecomment-632830962 to enable a workaround.
