### ISSUE TITLE
 MSLError: Request failed validation during key exchange

### ISSUE THREAD

**Issue by todivefor** [CastagnaIT/plugin.video.netflix#654]
#### Your Environment
- Netflix add-on version:  1 .3.2
- Operating system version/name:  Android Kodi 18.6
- Device model:   Firestick

Used Operating system:
* [x ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Start Kodi, usually get the error and then after every restart of Netflix addon

https://paste.kodi.tv/humagiwuna

#### Expected behavior

Netflix starts in background. When I start netflix, it starts without error.

#### Actual behavior

I get the error  MSLError: Request failed validation during key exchange
#### Steps to reproduce the behavior

1. Start Kodi
2. Start Netflix
3.

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/humagiwuna

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
*[x] installed from repository castagnait autoupdate

**Comment by CastagnaIT** [comment]
you can try to do Reset ESN from expert settings?
and give a new log after that?

**Comment by todivefor** [comment]
Reseting ESN did not work. 

FYI - This worked fine in Dec, 2019. When I tried in May, this problem.  Don't know what version of addon I was running in Dec (latest at the time). In May running latest addon on Kodi 18.2. Now on Kodi 18.6

https://paste.kodi.tv/hupebenade

**Comment by CastagnaIT** [comment]
the debug is disabled so the log provided is unuseful

**Comment by todivefor** [comment]
FWIW - I get same error on my MAC OS X Kodi 18.2 Netflix addon 1.3.2:

https://paste.kodi.tv/efonunuvim

**Comment by todivefor** [comment]
I got this working again on both platforms. I changed my password on netflix. I then tried to logout on the addon thinking that I would then have to log back in. This never worked. I uninstalled netflix on both platforms and reinstalled. Entered my credentials and all is good. Does logout not force a new login with credentials?

**Comment by CastagnaIT** [comment]
Logging out deletes all access data in the add-on
I will try to double-check

**Comment by CastagnaIT** [comment]
i checked and all data are deleted correctly
so reinstalling and do the logout is same thing, except that with logout you keep some settings and you don't lose the library
