### ISSUE TITLE
Make Signals http workaround timeout configurable.

### ISSUE THREAD

**Issue by stevenhoving** [CastagnaIT/plugin.video.netflix#656]
@CastagnaIT Thanks for making this awesome plugin. As you might have noticed, this elusive Signals timeout bug keeps poping up. I personally experience this issue often. Yes I run libreelec on a rpi4, using the build in wifi module (I know this is the root cause of my issue and I am reworking my network infra to change this). But this issue is not about that, not really. It is about the http workaround option. When enabled it does resolve many of the Signals timeout issues. But every once in a while the http connection times out, and that bugs the hell out of my wife. As a programmer by trade, I know these things can be annoying. And I have manually changed the timeout to a higher value. This fixes the leftover timeouts for like 99% of the time. Of course this is at an expense of the responsiveness of the system. But as long as my wife does not see this 'timeout' message all is fine.

**The line:**
https://github.com/CastagnaIT/plugin.video.netflix/blob/9f8e9828901d79c4c81f7d64150895e9fba70d57/resources/lib/common/ipc.py#L105

So maybe you can be persuaded to add an 'expert' settings field to allow this to be changed manually. I don't mind changing the scripts every once in a while but.. such a setting would make my life a bit easier in between versions.

**Comment by ccope** [comment]
Alternatively, maybe add retries if a timeout is detected?

**Comment by CastagnaIT** [comment]
it is clear that the problem is in your device
more to 16sec to get a response are big network problems

if i were to accept the requests of every single user who has problems with his device i would have to add hundreds of options

so as i have already answered to others it will not be accepted
so being a fixable thing you can temporarily edit the file manually until you fix the network

**Comment by stevenhoving** [comment]
ok sure np
