### ISSUE TITLE
Unable to login/start addon

### ISSUE THREAD

**Issue by NikolaiMagnussen** [CastagnaIT/plugin.video.netflix#657]
#### Your Environment
- Netflix add-on version: 1.3.2
- Operating system version/name: LibreELEC 9.2
- Device model: Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ x ] Raspberry-Pi
* [ ] Windows

### Describe the bug
The Netflix addon will not start, even after removing the userdata and changing versions.
Versions tested: 1.3.0, 1.3.1, 1.3.2 (from repo), and 1.3.2 from daily build (May 22).
The log file compails about SQlite encoding and invalid profiles.
Link to logfile: cryptobin.co/y4t6o037
Password: netflix

#### Expected behavior
To properly start the netflix addon.

#### Actual behavior
An error message (the same one as shown in the logfile)

#### Steps to reproduce the behavior
0. <same system as me?>
1. install netflix addon
2. try and log in
3. errors

#### Possible fix
No clue

### Debug log
The debug log can be found from this link: cryptobin.co/y4t6o037
With the password "netflix"

**Comment by vid0** [comment]
i have exactly the same problem since the last update. Also, reverting versions back doesn't help 😑

**Comment by CastagnaIT** [comment]
i need a log with debug instruction in readme
