### ISSUE TITLE
Crash on playback start

### ISSUE THREAD

**Issue by gabrielgagz** [CastagnaIT/plugin.video.netflix#661]
#### Your Environment
- Netflix add-on version: 1.3.2
- Operating system version/name: Android Pie
- Device model:  Razer Forge TV

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Expected behavior
Click on video and start playback

#### Actual behavior
Instead of playback, Kodi completely crash

#### Steps to reproduce the behavior

1. Open Netflix Addon
2. Choose video to play
3. Kodi Crash

### Debug log

The debug log can be found from this link:
https://hastebin.com/ezozerucey.coffeescript

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
if kodi breaks you have to report it to Kodi not here
