### ISSUE TITLE
ASCII Codec Can't Encode Character U'\XFC'

### ISSUE THREAD

**Issue by NinjaLooterGeno** [CastagnaIT/plugin.video.netflix#662]
#### Your Environment
- Netflix add-on version:  1.32_20200524
- Operating system version/name:  LibreElec 9.2.2
- Device model:   Intel NUC-Kit NUC6i5SYH

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

After selecting a Video it shows an ASCII Code Error
#### Expected behavior

Video starts normally
#### Actual behavior

Video won't start and shows an Error
#### Steps to reproduce the behavior

1.Start Addon
2.Select Video
3.Try to Play Video

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/fociqumuvo.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [X] I'm using a different source  https://bit.ly/citnfdailybuilds

**Comment by CastagnaIT** [comment]
update and try again if not work give me new log
[plugin.video.netflix_1.3.2_20200525.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4675820/plugin.video.netflix_1.3.2_20200525.zip)

**Comment by NinjaLooterGeno** [comment]
https://paste.kodi.tv/duvebuqiji.kodi

**Comment by CastagnaIT** [comment]
try again
[plugin.video.netflix_1.3.2_20200526.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4680856/plugin.video.netflix_1.3.2_20200526.zip)

**Comment by NinjaLooterGeno** [comment]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 110: ordinal not in range(128)
https://paste.kodi.tv/ohurevozas.kodi

**Comment by CastagnaIT** [comment]
fixed
[plugin.video.netflix_1.3.2_20200526_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4683394/plugin.video.netflix_1.3.2_20200526_t2.zip)

**Comment by NinjaLooterGeno** [comment]
everything works again.
Thanks :D
