### ISSUE TITLE
HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by ORCA058** [CastagnaIT/plugin.video.netflix#663]
#### Your Environment
- Netflix add-on version: 1.3.2
- Operating system version/name: CoreElec 3.2.2
- Device model:  Tanix T9S

Used Operating system:
* [ ] Android
* [ ] iOS
* [X ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
The netflix addon will not start.  HTTPError

**Comment by ORCA058** [comment]
I don't understand what that means.

**Comment by MartChic** [comment]
Post a link to the log instead of pasting it in your bug report. The rules are here:

**Comment by ORCA058** [comment]
I tried to fix the bug report.
I'm sorry, I can't speak English, I use the google translator.

**Comment by spacebug96** [comment]
I have got the same error too. Seems there is problem with https://www.netflix.com/browse request. Server response with 500 error code.

**Comment by CastagnaIT** [comment]
internal server error is a netflix server problem
here you can only try to logout/login

**Comment by spacebug96** [comment]
We have tried login/logout, but unfortunately it doesn't help...
I tried to reinstall the whole plugin (I have removed my user settings also), but the behavior is same. After successful login the first screen is displayed, but after clicking on next screen the error 500 is occurred.

**Comment by CastagnaIT** [comment]
what is your country?

**Comment by spacebug96** [comment]
I'm from Slovakia, but my friend ORCA058 is from Hungary.

**Comment by ORCA058** [comment]
Yes, I am from Hungary.
I also did it as a spacebug96 user, but an error remains.

**Comment by spacebug96** [comment]
I have tried to sniff HTTPS request&response with mitmproxy.  Unfortunately I got following error for mentioned https://www.netflix.com/browse GET request:
HTTP/2 cleartext connections (h2c upgrade requests) are currently not supported.

So, I think mitmproxy is not appropriate for this. How can I help with debugging of this problem?

**Comment by spacebug96** [comment]
Finally I have found a workaround. The error is appearing when I choose Hungarian language in my profile. For other languages (I have tested English & Czech) the /browse request works as expected. 

So, in my case, it was a Netflix server side issue.

**Comment by ORCA058** [comment]
Thanks, I'll check this out.

**Comment by CastagnaIT** [comment]
thanks for the report, i have added the temporary solution to the wiki faq
