### ISSUE TITLE
Install Widevine manually

### ISSUE THREAD

**Issue by fabianfiorotto** [CastagnaIT/plugin.video.netflix#667]
#### Your Environment
- Netflix add-on version: v1.3.2
- Operating system version/name: Raspbian
- Device model:  3b

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe your help request
Can I install Widevine manually? I don't have the 3GB of free space in my raspberry pi required by the automatic installation process. I want to use my pc to download the image and extract the needed files manually and then copy in a USB stick and transfer them to the raspberry pi. I already ran [this script](https://gist.github.com/ruario/19a28d98d29d34ec9b184c42e5f8bf29#file-widevine-flash_armhf-sh) but I don't know if it has everything that I need to make this plugin work.

**Comment by CastagnaIT** [comment]
I don't think this is the right place to ask this
try ask in the Kodi forum
