### ISSUE TITLE
InvalidProfileError when logging in

### ISSUE THREAD

**Issue by vebjornr** [CastagnaIT/plugin.video.netflix#668]
#### Your Environment
- Netflix add-on version: 1.3.2
- Operating system version/name: LibreElec 9.2.1
- Device model:  Rpi4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
When starting the add-on, I enter my email and password, then an error appears, saying InvalidProfileError. The same happens on all subsequent attempts to start the add-on

#### Steps to reproduce the behavior
1. Install add-on from zip-file
2. Launch it, enter login-details
3. It fails with InvalidProfileError

### Debug log
The debug log can be found from this link: https://paste.kodi.tv/ufaqihogor.kodi

(Certain identifiers have been removed/redacted)

**Comment by vebjornr** [comment]
I suppose this is the exact same issue as [issue 657](https://github.com/CastagnaIT/plugin.video.netflix/issues/657)

**Comment by CastagnaIT** [comment]
Next time you add a modified log will close the issue
fortunately it is due to a recent change

test: [plugin.video.netflix_1.3.2_20200528_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4694274/plugin.video.netflix_1.3.2_20200528_t1.zip)
