### ISSUE TITLE
Library Sync issue : Exception: TypeError

### ISSUE THREAD

**Issue by jokerigno** [CastagnaIT/plugin.video.netflix#678]
#### Your Environment
- Netflix add-on version: 1.4.0
- Operating system version/name: Windows 10
- Device model:  NA

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

I just installed the addon and wanted to export items to my library.
This is how my UI appears
![image](https://user-images.githubusercontent.com/23552762/83612799-32373880-a583-11ea-8b9a-ddb52ffc5a3c.png)

When I click on perform full sync I receive a Exception: TypeError error.
Below a link to my log.

#### Expected behavior

Able to sync my list with kodi
#### Actual behavior

Error - As described above
#### Steps to reproduce the behavior

1. Click on "Perform full sync now"
2.
3.

#### Possible fix

Dunno
### Debug log

The debug log can be found from this link:
https://gofile.io/d/XtXLBP

**Comment by CastagnaIT** [comment]
hi,
please update and let me know:
[plugin.video.netflix_1.4.0_20200603_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4721953/plugin.video.netflix_1.4.0_20200603_t1.zip)

**Comment by jokerigno** [comment]
The issue is gone (tested on both windows pc and nvidia shiedl box).

**Comment by mobamoba** [comment]
I wanted to reopen this because I'm getting the same error while doing the same thing on 1.40.
