### ISSUE TITLE
Plugin fails to start after filling in Netflix credentials

### ISSUE THREAD

**Issue by ChristianFrii5** [CastagnaIT/plugin.video.netflix#679]
#### Your Environment
- Netflix add-on version: 1.4.0
- Operating system version/name: LibreElec 9.0.2 
- Device model:  WeTek Core

Used Operating system:
* [ ] Android
* [ ] iOS
* [x ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Manually installed the plugin to .kodi/addons/plugin.video.netflix and reset the hardware. After restart, I opened the netflix addon and was prompted for username/passwd which I filled in. It was loading for a few seconds then an error message appeared with the text "Addon Signals call timeout" and pointed me to the kodi.log file. I attempted to login a few times this way always with the same result. I also tried installing from the repo with the same result.

#### Expected behavior
The Netflix gui should open

#### Actual behavior
The error message appears on screen and points me to the kodi.log file.

#### Steps to reproduce the behavior
1. Install the plugin manually or from the repo, then reset
2. Wait for netflix background service to start
3. Open the addon then login to Netflix when prompted

#### Possible fix
I searched the forum for a fix or workaround but could not find anything that worked.

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/uxamuyorew.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [x ] I'm using a different source  - latest from https://bit.ly/citnfdailybuilds

**Comment by CastagnaIT** [comment]
> ConnectionError: ('Connection aborted.', BadStatusLine("''",))

this is not an addon error there is something wrong in your network or network configuration

**Comment by ChristianFrii5** [comment]
Just to let you know, the issue was my vpn. Once I closed it, everything seemed to work properly.
