### ISSUE TITLE
Feature request : Use tags for releases ?

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#68]
*I'm submitting a ...*
  - [ ] bug report
  - [X] feature request
  - [ ] support request

### Description

By using Git tags, it would be easier to identify the release downloaded.

IE : A commit tagged '14.0.1' will create a zip file named 'plugin.video.netflix-14.0.1.zip' when downloaded from the tag tab.

It's then very easier to manage versions IMHO.

Thanks for the job!

Smeulf.

**Comment by CastagnaIT** [comment]
It's one more thing, though i've pinned it down
