### ISSUE TITLE
[Bug] ListItem.Title no Longer Being Filled?

### ISSUE THREAD

**Issue by drinfernoo** [CastagnaIT/plugin.video.netflix#680]
#### Your Environment
- Netflix add-on version: 1.4.0
- Operating system version/name: Windows 10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug
`ListItem.Title` doesn't appear to be filled on any content from the add-on.

#### Expected behavior
`ListItem.Title` should have a value wherever it is loaded inside Kodi.

#### Actual behavior
`ListItem.Title` doesn't have a value on any items in the add-on.

#### Steps to reproduce the behavior
1. Focus an item in the Netflix add-on.
2. Attempt to read `ListItem.Title`, using whichever method you prefer. I used Devhelper Web.

### Debug log
The debug log can be found from this link: https://pastebin.com/rA85Pd3E

#### Other information
I've so far tested this on Arctic Zephyr 2 and Arctic Horizon.

**Comment by CastagnaIT** [comment]
Title is used for Episode ListItem only
I no longer use it, using it unnecessarily complicates the management of sourcecode

**Comment by drinfernoo** [comment]
@CastagnaIT Would you be able to add it back in? Having it missing causes issues in skins that use `ListItem.Title` for things.

It also breaks compatibility with TheMovieDb Helper's "players", as there is no longer a reliable way to step through the add-on, matching InfoLabels along the way.

**Comment by CastagnaIT** [comment]
this shits of infolabel make me headache
you can reintroduce it will make the loading lists a little slower
