### ISSUE TITLE
Netflix error 1044 android 9.0 motorola g6

### ISSUE THREAD

**Issue by edersonmax21** [CastagnaIT/plugin.video.netflix#684]
#### Your Environment
- Netflix add-on version: <1.4.0>
- Operating system version/name: <Android 9.0>
- Device model:  <Moto G6 - XT1925-3>

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
<I enter the extension, log in to my account.  When I insert a video, this error appears (this title is not available for viewing online. Try another one. 1044)>

<Link Log : (https://drive.google.com/folderview?id=1hd_0iq-vQiLthdvOpxLdMzdyX-KEld-4)>

#### Actual behavior

(Watch the video normally)

#### Steps to reproduce the behavior

1. I open the kodi
2.  I'll go on netflix
3.  I choose any series
4. As soon as I watch, the error appears

#### Possible fix

in a future update

### Debug log

The debug log can be found from this link:

(https://drive.google.com/folderview?id=1hd_0iq-vQiLthdvOpxLdMzdyX-KEld-4)

### Additional context or screenshots (if appropriate)

Link Screenshots :

(https://drive.google.com/folderview?id=1hd_0iq-vQiLthdvOpxLdMzdyX-KEld-4)

#### Installation
* [ ] I'm using other Netflix Repo <castagnait>
* [ ] I'm using a different source <Original Kodi>

#### Screenshots

(https://drive.google.com/folderview?id=1hd_0iq-vQiLthdvOpxLdMzdyX-KEld-4)

**Comment by CastagnaIT** [comment]
In expert settings select Reset ESN
then try again
and get the log

**Comment by edersonmax21** [comment]
I did what you said, but I was not successful, the same error appears after
cleaning esn


Link new log:

https://drive.google.com/folderview?id=1i7hhDoIXwxt9cKMoUGlKxZtDyT7iT-TI

**Comment by CastagnaIT** [comment]
If you use VPN/Proxies then disable it

if you do not use it, then i do not know what can be the problem with your nf account,
you can try also test to change language of the profile used and see what happen

**Comment by CastagnaIT** [comment]
Netflix suggest to do Logout: https://help.netflix.com/it/node/109329
try also this

**Comment by edersonmax21** [comment]
I'm not using vpn or proxy, I tried to change the language and leave and
nothing worked, the funny thing is that on my moto g1 android 5.1 phone it
worked

**Comment by edersonmax21** [comment]
but can this problem be resolved in a future update?  because I don't know what to do.

**Comment by CastagnaIT** [comment]
i have no idea what to do because this is the first time that a user have this problem
and this warning message come directly from netflix not the addon

can you attach here a screenshot of the esn from official netflix app settings,
with censuring last few characters?

**Comment by edersonmax21** [comment]
is it dangerous to send netflix esn?

**Comment by CastagnaIT** [comment]
no because all model device as your use the same esn
you have only to censure the last numbers part

**Comment by edersonmax21** [comment]
Screenshot esn

**Comment by edersonmax21** [comment]
https://drive.google.com/folderview?id=10fHqEylGIxCutjtGKUVTp8nCHPtbDMu9

**Comment by CastagnaIT** [comment]
We can try to use this test version and follow this instructions steps:

- Delete previous nf addon (**with also user settings when prompt**)
- Install this:
[plugin.video.netflix_1.4.0_20200606_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4740585/plugin.video.netflix_1.4.0_20200606_t1.zip)
- Do the login
- Now open add-on Expert settings and enable `Force Widevine security level L3`
- Press Ok to save the setting changes
- Now try to play a video

give a log

**Comment by edersonmax21** [comment]
Another error appeared, but different

Screenshot + New Log


https://drive.google.com/folderview?id=10ok41_2KixYhohrfYgZLo5f4OcQ7aTUg

**Comment by CastagnaIT** [comment]
Write this in expert settings Manual ESN field:

NFANDROID1-PRV-P-L3-MOTORMOTO=G=6=-4445-

let know

**Comment by edersonmax21** [comment]
the same error appears, I don't know what to do.

**Comment by edersonmax21** [comment]
and my security level for widevine is L1, but I don't understand why netflix puts it as L3

**Comment by CastagnaIT** [comment]
i do not understand because raise error, i need time to recheck all the code

**Comment by CastagnaIT** [comment]
i have tested to my phone but works,
so with your phone the partial esn seem not accepted

can you try insert also these esn?
NFCDCH-01-GDQQZVC3XCJT8MQDF313WW2Y03RT3W
NFCDCH-AP-GDQQZVC3XCJT8MQDF313WW2Y03RT3W

probably doesn't work, but better try

**Comment by edersonmax21** [comment]
When I put both esn, the kodi closes, so I open it, select the episode I want to watch and the error 1044 appears again

**Comment by CastagnaIT** [comment]
i am sorry but i do not have other solutions
you can not use it with this device..

**Comment by edersonmax21** [comment]
So, is this a problem with my device?

**Comment by CastagnaIT** [comment]
Netflix add-on is an _unofficial_ Netflix platform based on website
and it is compatible with the most of devices, _but not all devices_.

can be hundred of unknown reason or unknown limitation or restrictions imposed by netflix website
to some device types or also some wrong source code implementation of the addon,
some understandable, but many others impossible to understand,
because netflix does not release any source code for a correct implementation of his services.

so i think no one can give you an answer on what and where it doesn't work

**Comment by edersonmax21** [comment]
I found out that this error 1044 appears when I watch netflix on my moto g6's browser, does that also have anything to do with kodi?

**Comment by CastagnaIT** [comment]
this thing no help to find a solution

**Comment by edersonmax21** [comment]
ok sorry, i don't understand these things, could you close this topic?

**Comment by edersonmax21** [comment]
is there a way to change the kodi user agent?  because error 1044 is
changed when I do this in a browser.

**Comment by CastagnaIT** [comment]
> because error 1044 is changed when I do this in a browser.

what means "is changed"? more details
what browser name?

i need to understand better what you want to do
because changing user agent involve many other things

**Comment by edersonmax21** [comment]
I used the Windows 10 user agent with chrome and gave the following error,
different only when testing it on my phone:

**Comment by edersonmax21** [comment]
I have a theory that this has something to do with the user agent

**Comment by CastagnaIT** [comment]
you can not mix windows 10 with android do not have same widevine architecture

**Comment by edersonmax21** [comment]
yes, ok, but can this have something to do with it?  because i want to
watch netflix on kodi, because on the netflix app you don't choose the
quality.  seriously am i the only one with this problem?

**Comment by edersonmax21** [comment]
in this new update, I enabled it to force the L3 widevine and an error
other than 1044 appeared, now only this one appears:

**Comment by edersonmax21** [comment]
I put your esn and gave this error, and when I put my esn the error from
the previous message appears.

**Comment by edersonmax21** [comment]
still not solved the error?  put the security level L3 and this message
appears, is there still no solution?  please just want to watch netflix on
kodi .....

**Comment by CastagnaIT** [comment]
i do not know what the problem in your device model, but i have a device with same error
and the problem is that is not full google/netflix certified

You can try to check these things:
-Try install from PlayStore: SafetyNet Test app and run test, have to result in to: all test PASSED
-In the PlayStore, open the menu and choose "Settings", scroll down and look what is written on "Play Protect certification", should be written "device certified".

And if you have done one of these things:
-If you have unlocked your bootloader you can not use netflix
-If you have installed custom rom you can not use netflix
-If you have rooted your smartphone you can not use netflix

**Comment by edersonmax21** [comment]
play protect certification: "Device not certified", safetynet test: passed,
root: never did


What do I do now ?

**Comment by CastagnaIT** [comment]
Nothing... use a certified device

**Comment by edersonmax21** [comment]
I saw a tutorial on youtube on how to authorize it back, if I do it will it
work?

**Comment by edersonmax21** [comment]
I left my device certified and, even then, the error appears, I really
don't understand, I never root and my device is certified.

**Comment by edersonmax21** [comment]
hi, a new error appeared, and error 1044 changed, do you want me to send a log for analysis?

**Comment by CastagnaIT** [comment]
if you want to attach it

**Comment by edersonmax21** [comment]
I am constantly updating the logs according to the version of the addon, I
will always leave this link activated if you want to see the logs.

Logs:

https://drive.google.com/folderview?id=17silivVeUGtjAK2w11Pg43LHRhsHF1xl

**Comment by CastagnaIT** [comment]
> MSLError: Request blacklisted by key exchange service

this error is explained in wiki
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#request-blacklisted-by-key-exchange-service

therefore your device model is unusable

**Comment by d4rth-v4d3r** [comment]
Hello! I got this same error using LibreElec 9.8 withi Kodi Matrix (alpha release) I think it is related with the device. I installed LibreElec in an Orange PI PC 2, I shared WIFI connection through USB from a Moto G6 Play. Could it be related with the device also?

**Comment by edersonmax21** [comment]
but were you able to solve the problem?  I didn't quite understand what you said, I have little knowledge about this type of subject, if you could explain it better, I am researching to understand.

**Comment by mac1501** [comment]
hi i have the same error 1044 and I change the ESN manual with this NFCDCH-01-GDQQZVC3XCJT8MQDF313WW2Y03RT3W
and it work fine to me
i use an raspberry pi4 4gb ram with libreelec 9.2.5

**Comment by d4rth-v4d3r** [comment]
@mac1501 I can confirm it works 🎉🎉🎉🎉🎉 thank you very much! You are the real hero 🦸‍♂️.
> @edersonmax21 You should search a working ESN code. I found this but I don't know if it works for your Android device `NFANDROID1-PVR-T-L3-XIAMMIBOX3`, `NFANDROID1-PRV-B-L3–FORMUFORMULER=Z8-4445`, `NFANDROID2-PRV-T-L3-HISILICONZ7=PLUS`

**Comment by CastagnaIT** [comment]
@edersonmax21 i have read your email, i receive a lot of emails every day, so if possible ask in the appropriate Issue thread instead send a email

for unicode error, seem that you have entered illegal characters in the ESN field
that cause addon crash, do a ESN Reset from expert setting or reinstall addon

people who force the use of ESN of other devices they do it at their own risk
therefore take responsibility for possible repercussions from netflix
i always recommend to avoid this practice
