### ISSUE TITLE
Feature Request : Select first unseen episode of a season

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#69]
*I'm submitting a ...*
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## General information
When displaying a season, would it be possible, as in the Kodi library, to focus the first unseen/in progress episode ?

Thanks!

**Comment by CastagnaIT** [comment]
![L2endR3](https://user-images.githubusercontent.com/3257156/57033010-02b15080-6c4c-11e9-95a9-3d605a6943c6.png)
now that the types of contents of the lists are correct and setting as 'always' should work, but it doesn't work, it is not said that this setting also works within of the addons.

first we must ask to developers of kodi

**Comment by Smeulf** [comment]
Regarding the setting place, I bet it's intended for library only :/

I thought there was something in xbmcgui to make an item selected, so that it would be easier ^^

No hurry for me on that feature anyway ;)

**Comment by CastagnaIT** [comment]
tried to open an issue, they told me that this function has no bugs, the option is chosen for the only operation within the kodi library

to request a possible implementation, the interested users must request as a "feature request" in the kodi forum, so i'm closing
