### ISSUE TITLE
Auto-selection profile not working

### ISSUE THREAD

**Issue by abbaskip** [CastagnaIT/plugin.video.netflix#691]
#### Your Environment
- Netflix add-on version: direct from git
- Operating system version/name: windows 10

Used Operating system:
* [X] Windows

### Describe the bug
I set one of my Netflix profiles the default/Auto select option in Netflix addon, but when I play from TMDB Helper widgets it now airways prompts me to select user. Can this option not be turned off if a default user is chosen (surely this is the idea of default user)

#### Expected behavior
It plays under the Profile that is set as the auto selected profile in Netflix settings

#### Actual behavior
It currently brings up a box telling you to select profile

#### Steps to reproduce the behavior
Create TMDB Helper widget (I'm sure others that redirect to Netflix do the same?) and play episode that is in Netflix with Netflix player

#### Installation
I'm using default CastagnalT repo and latest 1.4 but with install from github zip over the top to get latest pull request from Drinfernoo to get TMDBHelper player working again going.

**Comment by CastagnaIT** [comment]
Auto profile selection works only within the addon itself not for outside calls

And no provide help for widgets:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits

**Comment by CastagnaIT** [comment]
but you can try turn off:
Settings->Playback->Ask to select a profile before playback

should working also for your case

**Comment by abbaskip** [comment]
> Auto profile selection works only within the addon itself not for outside calls
> 
> And no provide help for widgets:
> https://github.
