### ISSUE TITLE
 Force the use of external subtitles

### ISSUE THREAD

**Issue by Guedinha** [CastagnaIT/plugin.video.netflix#696]
#### Your Environment
- Netflix add-on version: <1.4.0>
- Operating system version/name: <Android 8.0.2>
- Device model:  <Nvidia Shield TV (2017)>

Used Operating system:
* [X ] Android 
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

I export my content to the Kodi library in .Strm and everything works perfectly. I need to use external subtitles (custom colors, etc.). The plugin always automatically selects the default subtitle netflix and I have to manually switch to my external custom subtitle. Is there any possibility of forcing the plugin to use my external subtilbles always?

**Comment by CastagnaIT** [comment]
external subtitles are handled by Kodi not the add-on
