### ISSUE TITLE
Full Library Sync: KeyError: u'year'

### ISSUE THREAD

**Issue by Goldsucher** [CastagnaIT/plugin.video.netflix#697]
#### Your Environment
- Netflix add-on version: 1.4.1
- Operating system version/name: Android
- Device model:  Nvidia Shield

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I'm trying a full library sync with my list. The entries are deleted. After that while the entries are added again, I get the error.

#### Expected behavior

The Sync should run without error

#### Actual behavior

I get an error while syncing and the sync is stopping

#### Steps to reproduce the behavior

1. Go to Addon Setting --> Library
2. Select "Perform complete sync now" (don't know if this is the exact translation)
3.

#### Possible fix

Don't know

### Debug log

The debug log can be found from this link:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4780124/kodi.log)
(pastebin and hastebin gave me errors)

#### Installation
* [X] I'm using other Netflix Repo: CastagnaIT Repostiry for Kodi 18.x 1.0.1 +leia
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
The log is without nf debug info,
follow readme instruction to get a right log

**Comment by Goldsucher** [comment]
strange, sorry. It actually was activated.

Next try:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4780312/kodi.log)

**Comment by CastagnaIT** [comment]
yes the problem is Rush Hour,
should not be on my list, the movie is not available to play yet
how did you add that?

**Comment by Goldsucher** [comment]
really? Here in Germany, it is available:

![Bildschirmfoto 2020-06-15 um 15 27 41](https://user-images.githubusercontent.com/7906131/84662982-d5d9fe80-af1c-11ea-83a0-607b4d8d08ff.jpg)

**Comment by CastagnaIT** [comment]
wow.... in Italy not yet
![image](https://user-images.githubusercontent.com/3257156/84663199-1c2f5d80-af1d-11ea-8c66-b95c6b040a2d.png)
something went wrong with the metadata
and it is strange because i can get the full metadata without problem at least from here

**Comment by CastagnaIT** [comment]
Can you do a test?
update with this:
[plugin.video.netflix_1.4.1_20200615.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4780807/plugin.video.netflix_1.4.1_20200615.zip)
i think you have enabled the auto sync with my list right?

then, find Rush hour and add it to my list (with the add-on)
should be appear the same error then get me the log
thanks

**Comment by Goldsucher** [comment]
> Can you do a test?
> update with this:
> [plugin.video.netflix_1.4.1_20200615.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4780807/plugin.video.netflix_1.4.1_20200615.zip)
> i think you have enabled the auto sync with my list right?
> 
> then, find Rush hour and add it to my list (with the add-on)
> should be appear the same error then get me the log
> thanks

**Comment by Goldsucher** [comment]
okay, it was added to my list, but the same error appeared 


[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4781540/kodi.log)

**Comment by CastagnaIT** [comment]
apparently the metadata is mixed with "Der Prinz von Bel-Air" tvshow
then raise error

you can try this to see if error happen again:
1 remove it from mylist
2 go to addon settings, expert settings, and do: `Clear in-memory and on-disk cache`
3 add it again to my list

**Comment by Goldsucher** [comment]
okay that helped! There is no error anymore. Thanks for the quick fix 👍
