### ISSUE TITLE
Full Library Sync: HTTPError

### ISSUE THREAD

**Issue by Goldsucher** [CastagnaIT/plugin.video.netflix#698]
#### Your Environment
- Netflix add-on version: plugin.video.netflix_1.4.1_20200615.zip
- Operating system version/name: Android
- Device model:  Nvidia Shield

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I'm trying a full library sync with my list. The entries are deleted. After that while the entries are added again, I get the error. Afterwards I get the error when trying to run the Netflix Addon. After a few minutes, it is working again until I run the next full sync

#### Expected behavior

The Sync should run without error

#### Actual behavior

I get the error while syncing and the sync is stopping

#### Steps to reproduce the behavior

1. Go to Addon Setting --> Library
2. Select "Perform complete sync now" (don't know if this is the exact translation)
3.

#### Possible fix

Don't know

### Debug log

The debug log can be found from this link:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4783022/kodi.log)

#### Installation
* [X] I'm using other Netflix Repo: CastagnaIT Repostiry for Kodi 18.x 1.0.1 +leia
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
the error 403 not depends from add-on
it is possible that you have too items in my list!?

**Comment by Goldsucher** [comment]
hm maybe? I think there are ~120 items

**Comment by CastagnaIT** [comment]
> EDIT: Okay maybe more. Now the error appeared after 85 shows and 128 movies. It try to find out what/how much is missing

yes are enough
i have added some delay between update, try with this update:
[plugin.video.netflix_1.4.1_20200616.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4787586/plugin.video.netflix_1.4.1_20200616.zip)

if today you have tried many times, try this tomorrow

> EDIT 2: Not much is missing. Maybe ~20 items. Do you think, the automatic-update-mode will add these items?

yes the sync should complete what is missing, but sincerely i never tried this particular case

**Comment by Goldsucher** [comment]
> > EDIT: Okay maybe more. Now the error appeared after 85 shows and 128 movies. It try to find out what/how much is missing
> 
> yes are enough
> i have added some delay between update, try with this update:
> [plugin.video.netflix_1.4.1_20200616.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4787586/plugin.video.netflix_1.4.1_20200616.zip)
> 
> if today you have tried many times, try this tomorrow
 
I am not at home for the next 1 - 2 weeks, but then I can test the version, if it's still necessary.


> > EDIT 2: Not much is missing. Maybe ~20 items. Do you think, the automatic-update-mode will add these items?
> 
> yes the sync should complete what is missing, but sincerely i never tried this particular case

yes, the auto-update added the missing items. Now there are 86 shows and 135 movies and I think that's all 👍

**Comment by CastagnaIT** [comment]
no problem thanks anyway
