### ISSUE TITLE
Watched state from library

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#7]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

### Addon version used

14.0b20

### Description

When using the Kodi library, episodes of the series are not marked as viewed
Is it possible to implement this solution:
https://github.com/asciidisco/plugin.video.netflix/pull/293 ?

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]
Mark as watched when using library
**Actual behavior:** [What actually happened]
Not marked as watched when using library

### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [x] I'm using a different source (Please tell which)
14.0b20
### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

**Comment by CastagnaIT** [comment]
if one day I have time i will try to take a look, but now there are more important things to fix
If someone else has time to try a porting, they're welcome

**Comment by helviojr** [comment]
Well, maybe I could try it. Let me fork the project and try to reproduce caphm's PR.

**Comment by helviojr** [comment]
Well, this fork was made after asciidisco#293, so this commit already exists [here](https://github.com/CastagnaIT/plugin.video.netflix/commit/f10c978aa814789139e826fcc64c565399eb498c) in this fork. Including a new file resource/lib/KodiMonitor.py was removed in some newer commit.

The problem would be somewhere else. If that commit has solved the problem, somehow, it became a problem again. I will still try to find out what changed.

**Comment by Dischi** [comment]
For me the state works, but resume does not. When I stop the playback, it is possible to resume. Once I leave the current menu and come back, the state is still "in progress" but the resume point is gone.

**Comment by Smeulf** [comment]
On a single client, after this issue (https://github.com/CastagnaIT/plugin.video.netflix/issues/36) was fixed, it's working on my side. Can someone try with the last master ?

Remains a problem with multiple clients sharing a MySQL database: if I stop a video on client 1, I can see a resume point icon on client 2, but it won't resume and just restart the video at the beginning.

**Comment by notoco** [comment]
Still not working for me.

**Comment by Smeulf** [comment]
> Still not working for me.

Yeay, just saw that :(

It's "funny" cause it works if you stop the video that restart it just right after.
Looks like it's the same delay as the cache TTL again, but I can't confirm yet.

**Comment by Smeulf** [comment]
For the record, from infolabels.py:

# Resuming for strm files in library is currently broken in Leia Beta
# keeping this for reference / in hopes this will get fixed

I tried to uncomment the code following that comment, but with no success.
The resume point is correctly set for the strm file in the database, but it seems the player can't respect it, even by forcing the StartPercent property on the listItem. I may miss something, but for now I'm stucked and don't know what else to try.

Cheers.

**Comment by helviojr** [comment]
I saw something about a workarround in one of those "generic" stream
plugins. Not sure which. It seems they managed to skip to the correct time
after the media is already playing. That way, sometimes you see the first
frames but then jump to the correct place. It seems to be exactly the same
bug of Leia.

I'll try to look for it again.

Helvio

Em ter, 2 de abr de 2019 14:18, Smeulf <notifications@github.com> escreveu:

**Comment by Smeulf** [comment]
That's a possible workaround I've think about also, but it's ugly.

If it's a Leia bug, that should be submitted to Kodi team IMHO for a fix, as it's a regression...

**Comment by Smeulf** [comment]
Well, after some searches in the Kodi code and forums, I can say that for now, resume points can't e handeled by Kodi for STRM files.

The reason is that STRM files are considered as playlists, and playlists are excluded from resuming functions in the library.

So there's 2 options : either handle the resume function in the addon as some did with a seek to the right position, or encourage Kodi team to evolve Kodi to handle this situation properly.

I submitted an idea in the Kodi forum for this, your opinion is welcome : https://forum.kodi.tv/showthread.php?tid=342730

Cheers.

**Comment by notoco** [comment]
I forgot that I had already found that it was a kodi bug ... now I remembered. 
https://forum.kodi.tv/showthread.php?tid=229951
https://trac.kodi.tv/ticket/12763#no2
So... the situation has been known for years :) In version 13 of the netflix plugin, it somehow worked from what I remember, but there again, UpNext does not work properly ... closed circle.

**Comment by notoco** [comment]
The light in the tunnel appears: https://github.com/xbmc/xbmc/pull/16076

**Comment by Smeulf** [comment]
Thanks! Let's hope Kodi team will commit the PR!

**Comment by CastagnaIT** [comment]
notify when it will be implemented

**Comment by notoco** [comment]
(I'm sorry, I had to ...)
**Order accepted**

**Comment by Smeulf** [comment]
@notoco Is your PR still exists? I can't find it anymore...

In the meantime, we worked on a workaround https://github.com/CastagnaIT/plugin.video.netflix/tree/4a3de522da692be42ffa946ac5b805ce605c9c81

Feedback is welcome.

**Comment by notoco** [comment]
It was not my PR - I only found it - and actually it disappeared some time ago.

**Comment by notoco** [comment]
Back to the topic. In the last daily, everything works great (I did not check the resume point, but the view state works). The episode watched is beautifully viewed as being viewed. However, if you use integration with NextUp, it does not work anymore. The last episode watched is not marked correctly. With the integration of NextUp disabled in Netflix, but in the background acting NextUp - it works - but then there is no convenience in the form of pop-ups at the same time as the final credits.
The solution would probably be to see if the watch was triggered from the library or directly from the plug-in - and therefore the corresponding serving of responses to the NextUp plugin

**Comment by Smeulf** [comment]
@notoco: if I understand correctly, when playing an episode from the library, at credits it will show NextUp correctly, then start the following episode.

On the second (and so on) episode, NextUp will continue working but none of the episodes will be marked as watched in the library.

But they are marked as watched in the Netflix addon are they?

If I didn't understand correctly, please add steps to reproduce and a capture of you NextUp settings, so I can take some time to find the problem and maybe fix it, I think I know why it behave that way...

**Comment by notoco** [comment]
You understood me exactly. It is not marked in the library, but in the Netflix plugin itself it is marked. For testing, I always use the default settings of the Nextup and Netflix plugins

**Comment by Smeulf** [comment]
I think this is because NextUp integration plays some "plugin://" path rather than the "library://" path.

So I have to check if the next episode is in the library, and if it is, replace the path in the NextUp data in order to play the right item...

Will keep you in touch!

**Comment by notoco** [comment]
Cool. I'm sorry but I have to:
![pobrane](https://user-images.githubusercontent.com/36659110/61713703-777ebd00-ad59-11e9-8f6c-7af137a1e130.jpg)

**Comment by Smeulf** [comment]
Hehe ^^ 

But it might take a little longer than expected, I've just test to call the right path, and it's not solving the issue. I have to dig in the code more to understand the 'why'...

Damn I thought it would be very easy to fix!

**Comment by Smeulf** [comment]
@notoco can you try this branch? https://github.com/Smeulf/plugin.video.netflix/tree/Export_New_Episodes

There's a lot of new things with the library:
- Auto export new episodes finally working
- Tv show can be excluded/re-included from auto update (usefull for an ended tv show)
- UpNext fix (hopefully)

Feedback is very welcome!

Warning: once upgraded, you won't be able to revert unless you delete the library.ndb2 in addon_data/plugin.video.netflix. So maybe it's better to try this on a specific system, or save your data before ;)

**Comment by notoco** [comment]
It works.
It just works. Marks both in the plug-in and in the library
I have not tried the other news yet. All in all, I still have to check the export of NFO files - many serials are not in my language on TMDB..

**Comment by notoco** [comment]
Heh - I know - the plugin does not generate an NFO file for the entire series, only for single episodes. And kodi requires NFO for the whole series (as a title)
https://kodi.wiki/view/NFO_files/TV_shows

> TV Shows require the following nfo files
> 
> **One nfo file for the TV Show. This file holds the overall show information**
> One nfo file for each Episode. This file holds information specific to that episode
> For one TV Show with 10 episodes, you will require 11 nfo files.

**Comment by notoco** [comment]
Ok - my fault - the skin I use, does not show me one option, I had to scroll down:

> Include all information in NFO files (use only with 'Local Information' scraper)

**Comment by Smeulf** [comment]
Thanks for you feedback. I'm glad you like it!

**Comment by notoco** [comment]
For me, finally, the integration of Netflix, UpNext and the benefits of using the kodi library makes sense.
A great job. Subject definitely closed.
@CastagnaIT - you just have to turn it into the main branch.
As we say in Poland:
Kawał dobrej roboty odwaliliście....

**Comment by Smeulf** [comment]
I wait some more time before giving @CastagnaIT a green to merge it in the master branch. I'm still running a custom version to ensure auto update is running fine. Hopefully at the end of the week it will be ok, if no showstopper is found!
