### ISSUE TITLE
Videos won't play on RPi3, I just get a black screen with "Skip Intro" button and no sound

### ISSUE THREAD

**Issue by coaxial** [CastagnaIT/plugin.video.netflix#70]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
I have installed the addon on LibreELEC 9.0.1, enabled inputstream.adaptive and the rtmp plugin (just in case). It automatically installed the Widevine component.

### Addon version used

0.14.1

### Description

After logging in, I can navigate through Netflix shows etc. When I select a video to play, it starts the video and I get a black screen with a "Skip Intro" button. Nothing plays (sound or video) and if I press the button to stop playback on my remote, it crashes Kodi. I have to SSH in and `reboot`.

### Steps to Reproduce

1. Install the addon as per the instructions
3. Enable inputstream.adaptive and RTMP plugins in Kodi settings
2. Login to Netflix when prompted
4. Install Widevine when prompted
3. Navigate to the show/movie you want to watch
3. The screen is now "playing" a black video without sound and with the "Skip Intro" button showing

**Expected behavior:**

Play the content, with sound

**Actual behavior:**

Black screen, no sound, "Skip Intro" grey button showing only in the bottom right corner.

## Context (Environment)

LibreELEC 9.0.1 on RPi 3B+

### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [x] I'm using a different source (Please tell which)

I'm using the CastagnaIT zip file repo

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Freshly upgraded from LibreELEC 8

## Debug log

https://paste.kodi.tv/okoyasosec.kodi

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

**Comment by CastagnaIT** [comment]
go to Expert setting,
try to enable the profile VP9

**Comment by coaxial** [comment]
Same result

**Comment by CastagnaIT** [comment]
have you installed Cryptdome?

**Comment by Smeulf** [comment]
I have the same config you have. 

You can make sure :

- OMXPlayer is disabled in settings/player/videos (that should solve your problem)

- HEVC is disabled in the Netflix/Expert settings (RPi3 is not powerfull enough to decode HEVC correctly)

- Set inputstream adaptative max resolution to 720p (RPi3 can't decode 1080p, it's not powerfully enough too)

For now, VP9 was not a solution for me either. I just use H264 streams.

**Comment by coaxial** [comment]
@CastagnaIT I haven't done it manually. Does the addon or LibreELEC/Kodi take care of it? I ssh'ed in the Kodi box but `pip show cryptdome` doesn't work: `pip` is not installed. And because of LibreELEC's nature, I can't install any package with the usual tools from the CLI.

**Comment by CastagnaIT** [comment]
see Smeulf comment i'd forgotten about the OMXPlayer problem
i not having RPi for test...

**Comment by coaxial** [comment]
Yep it was OMXPlayer
