### ISSUE TITLE
TV Show name showing as numbers during playback

### ISSUE THREAD

**Issue by xpronic** [CastagnaIT/plugin.video.netflix#700]
#### Your Environment
- Netflix add-on version: v1.4.1 
- Operating system version/name: Android TV
- Device model:  Nvidia Shield

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Every tv show episode I try and play through the addon  or through the library (when added) is showing as random numbers during playback with no episode info when paused. This does not happen with movies, the poster and name are displayed correctly, with a short description.

#### Expected behavior
Show tv show poster and episode info during playback. 

#### Actual behavior
Just shows random number and no info during playback. 

#### Steps to reproduce the behavior

1. Go to a show through the addon or library
2. Select an episode to play

### Debug log
The debug log can be found from this link: [https://paste.kodi.tv/isulomuruk](https://paste.kodi.tv/isulomuruk)

### Additional context or screenshots (if appropriate)
How its meant to look (movies work fine) ![Pic](https://i.imgur.com/OlyAcHP.png)

How it looks with when playing an episode ![Pic](https://i.imgur.com/PMRCTTn.png)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
you have not follow instruction to get a right log
read the readme

**Comment by CastagnaIT** [comment]
closed due to inactivity
