### ISSUE TITLE
InputStream based plugin for Netflix Android Mobile

### ISSUE THREAD

**Issue by Veeresh8** [CastagnaIT/plugin.video.netflix#702]
I don't know if this is appropriate here, but I have a sample **Android** project which fetches the DASH Manifest from Netflix to start the playback, however, this is DRM protected. I further do have the calls to the license servers to perform the playback.

However, I do not seem to understand how to bind the DASH Manifest to a video player specifically ExoPlayer on Android, which also makes calls to the license servers to decode the DRM data. (I've used JWPlayer Android to do the same but no luck there)

Also, is there a way to verify if the manifest I've constructed is valid?

I can share a link to my project if needed.

**Comment by CastagnaIT** [comment]
i have never used ExoPlayer so i do not know
i think you have to construct a custom manifest/license in some way

perhaps this wiki can help you
https://github.com/add-ons/best-practices/wiki/Streaming-issues

sorry but i do not have time to follow your project

**Comment by jakermx** [comment]
AFAIK Media Playera are called by InputStreamAdaptive(ISA) AddOn, if you want to play DASH/Widevine, you should make the calls throght ISA....caus you should grab Manifest, License and  Certificatesm select media URLs, decrypt them mix and finally play them sync.

look at https://github.com/peak3d
