### ISSUE TITLE
Addon fails to start

### ISSUE THREAD

**Issue by CraigHB** [CastagnaIT/plugin.video.netflix#705]
## Bug report

My Netfix add-on stopped working, as far as I can tell not related to anything I did on my end.  Was working fine up until yesterday.  Every time I try to start the add-on it fails to run with an error.

#### Your Environment
- Netflix add-on version: 1.4.1
- Operating system version/name: CoreElec 9.2.3 (Linux)
- Device model:  Odroid N2 (AMLogic)

### Describe the bug
Add on persistently fails to start with error, "Background services can not be started due to: u'lolomo'

### Debug log
http://ix.io/2pwN

**Comment by stevenhoving** [comment]
check #701

**Comment by CraigHB** [comment]
Okay thanks, didn't realize this was already posted as I didn't know it's a login issue.  Do you want to close this with a reference to #701?  Your preference.
