### ISSUE TITLE
Netflix addon fails with key error on Raspberry Pi

### ISSUE THREAD

**Issue by gjdent** [CastagnaIT/plugin.video.netflix#706]
## Bug report
When I installed the addon Netflix worked great - about a week later it fails on startup with a Key Error; specifically, KeyError: u'lolomo'. 
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Also - from the add on configuration page in Kodi I tried to log out and back into Netflix and experienced the same key error. Suspect that Netflix is now blocking the add on from running on the Pi but figured I would submit the log in case you have any recommendations.

#### Steps to reproduce the behavior

1. Trying to start the Netflix add on fails
2. Trying to log out and back into the Netflix account from the add on configuration page also causes the same key error - so suspect that Netflix is detecting and not liking my Pi for some reason. It was working ok for 4-5 days.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4801695/kodi.log)

3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by dm2912** [comment]
did you even read any other posts lol
