### ISSUE TITLE
AddonSignals: call timeout - when you browse having a lot of items on my list (ARM)

### ISSUE THREAD

**Issue by ffpp2003** [CastagnaIT/plugin.video.netflix#716]
#### Your Environment
- Netflix add-on version:  15.0
- Operating system version/name:  LibreElec 9.2.3
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ✓ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I'm trying to open Netflix on LibreElec and the error AddonSignals: call timeout

#### Expected behavior

Open Netflix without showing up the error AddonSignals: call timeout

#### Actual behavior

Opening Netflix generates the error AddonSignals: call timeout, and after pressing ok, exits Netflix

#### Steps to reproduce the behavior

1. Turn on pc
2. Open Netflix
3. If Netflix takes a long time to load, probably, the error will show up

#### Possible fix

Optimize AddonSignals???

### Debug log

The debug log can be found from this link:
https://pastebin.com/Xpn6sMvW

I had the opportunity to reproduce the error two or three times in a row. Sorry if the log is too long, I don't know how to start a new one.
(I'm new in GitHub and in log setup and log exporting, so, if I did something wrong, please, tell me how to do it right)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ✓ ] I'm using a different source 
* [ ✓ ] I'm using the provided repo by CastagnaIT

**Comment by CastagnaIT** [comment]
a long log is good, to reset the log you have to reboot the device

from what i see your network takes too long to answer
the network doesn't seem to be working properly
there are no errors

**Comment by jakermx** [comment]
@CastagnaIT , maybe it could be useful to add a timeout parameter on settings, that users with low quality internet like me, could set, instead of the 16 sec that is defined by default, it works for both AddOn Signals and IPC.

I have to mod files everytime I update the AddOn, in my case, I have to set it to 60 sec, caus "My List" has a lot of titles.

**Comment by franchetoxx** [comment]
> @CastagnaIT , maybe it could be useful to add a timeout parameter on settings, ... 

I think that would be a good addition

**Comment by CastagnaIT** [comment]
>2020-06-24 19:56:22.816 T:140542805538560   DEBUG: [plugin.video.netflix (0)] Fetch initial page
>2020-06-24 19:56:22.816 T:140542805538560   DEBUG: [plugin.video.netflix (0)] Executing GET request to https://www.netflix.com/browse
>2020-06-24 19:56:25.251 T:140542805538560   DEBUG: [plugin.video.netflix (0)] Request took 0.438476s

this is the normal behaviour when your network is good
the issue happen when "Fetch initial page" not receive data

@jakermx
this is not a path request that could require more time of usual,
it is a normal http request to fetch web page

the time stat in the log provided is always less than 1 second
so the problem is not network speed are other issues
the web page is not responding

**Comment by jakermx** [comment]
@CastagnaIT I can find what you post on 140542805538560.....

look at line 905..

2020-06-24 19:50:32.424 T:140542805538560   DEBUG: [plugin.video.netflix (0)] Executing GET request to https://www.netflix.com/browse

It looks fine, but crashes after LE Update crashes....LE crashed at 921 and NF on 939, maybe they are related on urlib or the pipes used by it...IDK, just guessing

**Comment by CastagnaIT** [comment]
<pre>
020-06-24 19:50:36.841 T:140542398170880   ERROR: ## LibreELEC Addon ## oe::load_url(https://update.libreelec.tv/updates.php?i=c168903dc5f915a0db4ebc375ef3490f&d=LibreELEC&pa=Generic.x86_64&v=9.2.3&f=radeon) ## ERROR: (URLError(SSLError('_ssl.c:711: The handshake operation timed out',),))
2020-06-24 19:50:36.841 T:140542398170880   ERROR: Traceback (most recent call last):
                                              File "/home/jails/home/jenkins/LE/build2/workspace/Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.2.3/LibreELEC-settings-42acf2613927fa93d9d8ec9aa1d3135d101db0e0/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/oe.py", line 362, in load_url
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error ('_ssl.c:711: The handshake operation timed out',)>
2020-06-24 19:50:36.842 T:140542398170880   ERROR: ## LibreELEC Addon ## updates::check_updates_v2 ## ERROR: (TypeError('expected string or buffer',))
2020-06-24 19:50:36.842 T:140542398170880   ERROR: Traceback (most recent call last):
                                              File "/home/jails/home/jenkins/LE/build2/workspace/Generic/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.2.3/LibreELEC-settings-42acf2613927fa93d9d8ec9aa1d3135d101db0e0/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/updates.py", line 564, in check_updates_v2
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                            TypeError: expected string or buffer
</pre>

i see these errors on LibreELEC for about a month
it is strange that they not fix this breaking errors
or at least manage them in some way without causing exceptions

**Comment by risogolo** [comment]
I have got 120 Mbit internet so I believe the network speed should not be an issue

**Comment by DimitriosPi** [comment]
I have the same problem with latest coreelec on tvbox. Actually 2 tv boxes with coreelec and one with libreelec.

**Comment by DimitriosPi** [comment]
Widevine asked for an update, after that the issue was resolved, at least on Tanix 9s with coreelec 9.2

**Comment by CastagnaIT** [comment]
> I have to mod files everytime I update the AddOn, in my case, I have to set it to 60 sec, caus "My List" has a lot of titles.

@jakermx can you say me the number of titles you have in my list?

**Comment by jakermx** [comment]
1st profile with 145 in 2 Pages
2nd wit 192

**Comment by montvid** [comment]
Got the same problem of timeout. https://paste.gnome.org/p0zfdzo39/d0ql9m

**Comment by Dominit86** [comment]
I have this problem to with Kingston class 1 sdcard. Now i switched Samsung EVO Plus and no more timeout error.

Keep in mind english it's not my native language.

**Comment by risogolo** [comment]
the issue remains

**Comment by jakermx** [comment]
> the issue remains, unable to watch, I will have to cancel my netflix subscription

Dont need to be that drastic, grep for urlib under netflix addon and  add timeout parameter and set it to a timeot up to your needs...... it works cool, if you dont know how , just need to click menus twice or at most,  three times.

**Comment by risogolo** [comment]
> > the issue remains, unable to watch, I will have to cancel my netflix subscription
> 
> Dont need to be that drastic, grep for urlib under netflix addon and add timeout parameter and set it to a timeot up to your needs...... it works cool, if you dont know how , just need to click menus twice or at most, three times.

Can you describe how-to please, regarding going trough the menu, I tried yestarday much more times than 3 and I did not work, so I cannot watch at all

**Comment by CastagnaIT** [comment]
I want to point out that the error `AddonSignals: call timeout`
not means exclusively net slowness

may have resulted from other problems inside or also outside
like the example of @Dominit86 (that can happen also with slow mechanical HDD)
therefore each case must be evaluated separately

**Comment by montvid** [comment]
Yeah, i'm using libreelec on USB 2 stick. Will try sata ssd next. :) But maybe it is a good idea to put this functionality in RAM?

**Comment by CastagnaIT** [comment]
> But maybe it is a good idea to put this functionality in RAM?

what functionality?

**Comment by montvid** [comment]
> > But maybe it is a good idea to put this functionality in RAM?
> 
> what functionality? IPC is not a functionality

Well if the timeout depends on the media one is running kodi on then how to remove that dependency? Get a faster media like an ssd?

**Comment by franchetoxx** [comment]
> I want to point out that the error `AddonSignals: call timeout`
> not means exclusively net slowness
> 
> may have resulted from other problems inside or also outside
> like the example of @Dominit86 (that can happen also with slow mechanical HDD)
> therefore each case must be evaluated separately

If the problem is the HDD, I have a mechanical HDD, to be precise, a western digital wd320aaks

**Comment by CastagnaIT** [comment]
i have improved the initial data collection part when accessing menu lists for first time and slightly increased the timeout time

For the case of @jakermx that have more than 140 items to my list:
at first access to "my list" (or other lists) were performed 3 http requests, and now should be done only one request
with a great time saving, in theory, because i do not havemany titles in mylist, so let me know
it is probable that is not more needed to change the timeout value

For @risogolo:
i do not know your real situation without debug log, so if you want you can try the test

For @montvid:
I don't know what you mean, but the way you're talking, i don't think you're familiar with the Python environment
so no operation are performed on disk, at least not directly from the addon maybe from some python module that i can not control.
The timeout can not be removed is a safety measure to avoid block the Kodi system in particular cases,
and assigning a very high timeout is not good practice.
Your attached log is inaccessible, then i can not say nothing for your situation,
so if you want you can try the test

For @franchetoxx;
Your case is slightly different, but also you can try the test

Update test for Kodi 18: [plugin.video.netflix_1.6.0_20200706_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4880301/plugin.video.netflix_1.6.0_20200706_t1.zip)

**Comment by risogolo** [comment]
I provided my log here https://github.com/CastagnaIT/plugin.video.netflix/issues/711

**Comment by franchetoxx** [comment]
> i have improved the initial data collection part when accessing menu lists for first time and slightly increased the timeout time
> 
> For the case of @jakermx that have more than 140 items to my list:
> at first access to "my list" (or other lists) were performed 3 http requests, and now should be done only one request
> with a great time saving, in theory, because i do not havemany titles in mylist, so let me know
> it is probable that is not more needed to change the timeout value
> 
> For @risogolo:
> i do not know your real situation without debug log, so if you want you can try the test
> 
> For @montvid:
> I don't know what you mean, but the way you're talking, i don't think you're familiar with the Python environment
> so no operation are performed on disk, at least not directly from the addon maybe from some python module that i can not control.
> The timeout can not be removed is a safety measure to avoid block the Kodi system in particular cases,
> and assigning a very high timeout is not good practice.
> Your attached log is inaccessible, then i can not say nothing for your situation,
> so if you want you can try the test
> 
> For @franchetoxx;
> Your case is slightly different, but also you can try the test
> 
> Update test for Kodi 18: [plugin.video.netflix_1.6.0_20200706_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4880301/plugin.video.netflix_1.6.0_20200706_t1.zip)

As soon as I can, I'll try that zip

**Comment by CastagnaIT** [comment]
> I provided my log here #711

The log is wrong

**Comment by risogolo** [comment]
> > I provided my log here #711
> 
> The log is wrong

What's wrong, I followed rules, can you let me know, I'm willing to provide log and all what's necessary

**Comment by CastagnaIT** [comment]
no rules followed:
These are the explicit rules for Issue Post:
<pre>
### Debug log
1) Go to add-on settings, in Expert page and change "Debug logging level" to "Verbose"
2) Enable Kodi debug: go to Kodi Settings > System Settings > Logging, and enable "Enable debug logging"
3) How to get the log file? Read Kodi wiki: https://kodi.wiki/view/Log_file/Easy
RESPECT THE RULES!
- A DEBUG LOG IS ALWAYS MANDATORY WHEN CREATING AN ISSUE. PROVIDE A LINK TO THE LOG!
- DO NOT PASTE THE CONTENT OF THE LOG HERE
- DO NOT CUT THE LOG
- If the log file is really huge (more 1Mb) in Kodi settings disable "Component-specific logging" then create a new log
</pre>

In the Readme is also well explained how get a good log

Your log is cutted, without debug info, and without nf debug enabled

**Comment by risogolo** [comment]
log is slightly over 1MB I dont know what specific component to select - [log](https://github.com/risogolo/kodi/blob/master/kodi.log)

**Comment by CastagnaIT** [comment]
well now it is good!
i have added a new test in upper message https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-654361188

the weird thing is that the timeout is occurred before his real end time...
please install the update test, before using it do a "Clear cache mem & disk" from expert settings,
then provide me a new log

**Comment by risogolo** [comment]
> well now it is good!
> i have added a new test in upper message [#716 (comment)](https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-654361188)
> 
> the weird thing is that the timeout is occurred before his real end time...
> please install the update test, before using it do a "Clear cache mem & disk" from expert settings,
> then provide me a new log

How to install from zip?, I used repository for installation

**Comment by CastagnaIT** [comment]
from kodi addons section, "install from zip"
but there is a new release 1.6.1 out today, then you have to temporary disable the addon autoupdate
(addon icon context menu "information",then auto-update to off)
otherwise the test will be overwritten from the new version (after zip install)

**Comment by risogolo** [comment]
log fom the version lugin.video.netflix_1.6.0_20200707_t2 [log](https://raw.githubusercontent.com/risogolo/kodi/master/plugin.video.netflix_1.6.0_20200707_t2.zip-kodi.log)

**Comment by CastagnaIT** [comment]
@risogolo apparently seems the code flow is blocked somewhere but i have too little data to understand something
i need that you install this test and that you reply same navigation steps,
so i can get more info from debug log:
[plugin.video.netflix_1.6.1_20200708_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4892703/plugin.video.netflix_1.6.1_20200708_t3.zip)

**Comment by risogolo** [comment]
[log from plugin.video.netflix_1.6.1_20200708_t3.zip](https://raw.githubusercontent.com/risogolo/kodi/master/plugin.video.netflix_1.6.1_20200708_t3-kodi.log)

**Comment by CastagnaIT** [comment]
good we are already narrowing the field on the problem
i need another log please do again the steps with this:
[plugin.video.netflix_1.6.1_20200708_t4.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4892862/plugin.video.netflix_1.6.1_20200708_t4.zip)

**Comment by risogolo** [comment]
1,9 MB [plugin.video.netflix_1.6.1_20200708_t4](https://github.com/risogolo/kodi/blob/master/plugin.video.netflix_1.6.1_20200708_t4-kodi.log)

**Comment by CastagnaIT** [comment]
well,
I wasn't expecting a situation like this, the addon continue to elaborate data, then the problem is not here,
but seem that AddonSignals dependency stop the communication for some unknown reason

i need another debug, always same navigation steps
this time i have added also "addon.signals" zip test update where i hope i can see what happen
so install both zips

[plugin.video.netflix_1.6.1_20200709_t5.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4895088/plugin.video.netflix_1.6.1_20200709_t5.zip)
[script.module.addon.signals-0.0.5_debug.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4895089/script.module.addon.signals-0.0.5_debug.zip)

**Comment by CastagnaIT** [comment]
This is the fixed version, please test and let me know

@risogolo before run netflix restore the regular NF add-on version:
To restore regular version: On NF icon, open the context menu "informations", select "Update" and select the latest version. (if all is ok you can re-enable also auto-update)

AddonSignals dependency fixed (for Kodi 18.x):
[script.module.addon.signals-0.0.5_pathed.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4896676/script.module.addon.signals-0.0.5_pathed.zip)

**Comment by risogolo** [comment]
> This is the fixed version, please test and let me know
> 
> @risogolo before run netflix restore the regular NF add-on version:
> To restore regular version: On NF icon, open the context menu "informations", select "Update" and select the latest version. (if all is ok you can re-enable also auto-update)
> 
> AddonSignals dependency fixed (for Kodi 18.x):
> [script.module.addon.signals-0.0.5_patched.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4896703/script.module.addon.signals-0.0.5_patched.zip)

So should I use latest regular version of addon and then install script.module.addon.signals-0.0.5_patched.zip ?

**Comment by CastagnaIT** [comment]
yes right

**Comment by risogolo** [comment]
I upgraded to the latest regular version and then install signals addon, the same issue occurs, I will provide log once i will have a time

**Comment by risogolo** [comment]
[patched](https://raw.githubusercontent.com/risogolo/kodi/master/script.module.addon.signals-0.0.5_patched-kodi.log)

**Comment by CastagnaIT** [comment]
ok now the timing of addonsignals is right,
now try install the test 2 again from upper post https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-654361188

**Comment by risogolo** [comment]
> ok now the timing of addonsignals is right,
> now try install the test 2 again from upper post [#716 (comment)](https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-654361188)

are you sure t2, we had already t4, so should I install t2 + signals 0.0,5 ?

**Comment by CastagnaIT** [comment]
yes is needed the code of test 2 + patched addonSignals

**Comment by risogolo** [comment]
[t2+signals005](https://raw.githubusercontent.com/risogolo/kodi/master/t2_signals005-kodi.log) how many iternations should I expect?

**Comment by CastagnaIT** [comment]
I'm more tired than you, i am taking hours to try resolve the situation...
what type of disk you are using? ssd/mechanical hdd/sdcard standard or hispeed...?
you have small ram?
it is really weird that in 30 sec your device not have done the elaboration...

however if you want to give it one last try, now the timeout is set at 60seconds:
[plugin.video.netflix_1.6.1_20200709_t5_60timeout.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4899012/plugin.video.netflix_1.6.1_20200709_t5_60timeout.zip)

**For all other users of this thread**
it would be appreciated to have an answer
by updating with these (NF addon+addonSignal patched):
[plugin.video.netflix_1.6.1_20200709_t5_30timeout.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4899022/plugin.video.netflix_1.6.1_20200709_t5_30timeout.zip)
[script.module.addon.signals-0.0.5_patched.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4899023/script.module.addon.signals-0.0.5_patched.zip)

**Comment by risogolo** [comment]
> I'm more tired than you, i am taking hours to try resolve the situation...
> what type of disk you are using? ssd/mechanical hdd/sdcard standard or hispeed...?
> you have small ram?
> it is really weird that in 30 sec your device not have done the elaboration...
> 
> however if you want to give it one last try, now the timeout is set at 60seconds:
> [plugin.video.netflix_1.6.1_20200709_t5_60timeout.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4899012/plugin.video.netflix_1.6.1_20200709_t5_60timeout.zip)
> 
> **For all other users of this thread**
> it would be appreciated to have an answer
> by updating with these (NF addon+addonSignal patched):
> [plugin.video.netflix_1.6.1_20200709_t5_30timeout.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4899022/plugin.video.netflix_1.6.1_20200709_t5_30timeout.zip)
> [script.module.addon.signals-0.0.5_patched.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4899023/script.module.addon.signals-0.0.5_patched.zip)

No worries, this is open source and Im very thankful for the job youre doing, very appreciate your willingnes to help, Im using sdcard in RPI4, 2GB RAM, I will try shortly latest build

**Comment by stevenhoving** [comment]
@CastagnaIT did you consider this?

`    def waitForReturn(self):
        monitor = xbmc.Monitor()
        if monitor.waitForAbort(self.timeout / 1000)
            if self.use_timeout_exception:
                unRegisterSlot(self.sourceID, self.signal)
                raise AddonSignalsTimeoutError()

        unRegisterSlot(self.sourceID, self.signal)
        return self._return`

**Comment by risogolo** [comment]
seems like t5_30 works for me, the strange is that tried immediately, loading of "folders" too slow, after reboot its much faster, why?

**Comment by CastagnaIT** [comment]
@stevenhoving nice suggestion thanks! i can improve the addonSignal patch, tomorrow i will test to see if the timing result correct

@risogolo i have no idea maybe some memory leakage somewhere, can happen when an operating system has been running for many many hours without any reboot

it's a good thing if it works now

**Comment by risogolo** [comment]
> @stevenhoving nice suggestion thanks! i can improve the addonSignal patch, tomorrow i will test to see if the timing result correct
> 
> @risogolo i have no idea maybe some memory leakage somewhere, can happen when an operating system has been running for many many hours without any reboot
> 
> it's a good thing if it works now

nope it did not work long time, I always installed your version, deleted log via ssh, reboot, erased cache of the addon , enabled log, logged error, disabled logging

**Comment by CastagnaIT** [comment]
Sorry, I'm a too tired right now...hard to understand, can you say me in few words if is it working now?

**Comment by risogolo** [comment]
> Sorry, I'm a too tired right now...hard to understand, can you say me in few words if is it working now?

if youre talking to me, then yes it is working now, THANK YOU VERY MUCH again

**Comment by franchetoxx** [comment]
I've completely lost track of this issue. How is it going? Are you, CastagnaIT, near to fixing this bug?

**Comment by CastagnaIT** [comment]
@franchetoxx read upper post https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-656303346

**Comment by stevenhoving** [comment]
@CastagnaIT may I assume that my suggestion doesn't work? tbh I didn't test it myself.

**Comment by CastagnaIT** [comment]
@stevenhoving no because waitForAbort block code execution:
https://codedocs.xyz/AlwinEsch/kodi/group__python__monitor.html#ga9a1d271d0fddebee906abcda904e8249
we must have a loop to verify the incoming data

**Comment by stevenhoving** [comment]
@CastagnaIT ah fuck your correct.

**Comment by montvid** [comment]
`For all other users of this thread
it would be appreciated to have an answer
by updating with these (NF addon+addonSignal patched):
plugin.video.netflix_1.6.1_20200709_t5_30timeout.zip
script.module.addon.signals-0.0.5_patched.zip`

Works very good so far on x86 64 libreelec usb2 stick. After update don't forget to disable updates & reboot - after that you're golden.

**Comment by moozhub** [comment]
Hello @CastagnaIT ... I appreciate your efforts. I've been following along the thread like a fly on the wall. I tried your latest fixes that you suggested and unfortunately still experiencing the issue. I attached my log here: http://ix.io/2rmS

My kodi instance is running on a SSD if that makes any difference.

**Comment by CastagnaIT** [comment]
@moozhub your problem not concern this issue
you are using Fedora 32 with Kodi 18 that is not more not supported
Read the "Notice" in Wiki install instructions

**Comment by moozhub** [comment]
> @moozhub your problem not concern this issue
> you are using Fedora 32 with Kodi 18 that is not more supported
> Read the "Notice" in Wiki install instructions

Hmm, didn't really grasp that from that notice.. but I'll stick around to see if you have anymore solutions. Thanks.

**Comment by CastagnaIT** [comment]
there are no solutions, Fedora has started removing python 2

**Comment by moozhub** [comment]
python2 still exists in the repos, they may be phasing it out but it's probably not much different than the other users you're speaking with about this issue. The plugins are still using python2.

**Comment by CastagnaIT** [comment]
sorry but i need to ask you to do not this Issue thread for your problem because is totally different

**Comment by moozhub** [comment]
@CastagnaIT Agreed.. I can open a new issue for you

**Comment by risogolo** [comment]
How is it going with fixing this ?

**Comment by CastagnaIT** [comment]
> How is it going with fixing this ?

see comment https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-656303346

**Comment by risogolo** [comment]
> > How is it going with fixing this ?
> 
> see comment [#716 (comment)](https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-656303346)

Yes I saw that, I meant permanent proper fix

**Comment by CastagnaIT** [comment]
to know the exact date for release of AddonSignals you have to ask to AddonSignals dev maintainer

**Comment by risogolo** [comment]
> to know the exact date for release of AddonSignals you have to ask to AddonSignals dev maintainer

OK I will wait, Im not Python / Kodi developer. I dont know what AddonSignals is

**Comment by MartChic** [comment]
A new version of AddonSignals has been released. Is there anything to do to update it if we installed your patched version?

**Comment by CastagnaIT** [comment]
I don't see the official release yet, but I think it's almost ready
when it will be released,
if you already have the latest version of the NF addon, there is nothing else to do

**Comment by risogolo** [comment]
I dont see any release yet for addon signals, Im confused, Im still using the version of netflix plugin that you built for "me". Can I start to to use latest version or not? (will that version contain patch the you createdfor addon signaks even if no official release of addon signals)

**Comment by CastagnaIT** [comment]
the dev of AddonSignals is still busy...
yesterday i have tried to write to him to remember him to publish the new release

**Comment by stevenhoving** [comment]
@CastagnaIT I figured out what was wrong with my setup. I had a really slow sd card in my rpi4. I switched to a 128GB Supersonic Rage Elite 3.1 usb stick. The difference in performance is night and day. So it might be a good advice to people who suffer from a lot of these timouts to change there storage type.

**Comment by montvid** [comment]
I changed to sata ssd + latest version of netflix addon and I don't see timeouts anymore. Storage has a big impact.

**Comment by CastagnaIT** [comment]
@stevenhoving is already mentioned in the most frequent cases in the wiki
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#addon-signals-call-timeout

**Comment by stevenhoving** [comment]
> @stevenhoving is already mentioned in the most frequent cases in the wiki
> https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#addon-signals-call-timeout

Thanks... now I kind of look like an idiot 😄. I should have consulted the wiki.

**Comment by xLAva** [comment]
My pull request #884 fixes the issue for sd cards by disabling the caching on disk and removing the art cache completely.
It is super fast now on my rpi4 even with just an sd card.

**Comment by CastagnaIT** [comment]
@risogolo I think you have already seen the new addon signals release is out

**Comment by risogolo** [comment]
nope I havent, I will try to update plugin to the latest version tonight, thank you
