### ISSUE TITLE
KeyError: u'year'

### ISSUE THREAD

**Issue by franchetoxx** [CastagnaIT/plugin.video.netflix#717]
#### Your Environment
- Netflix add-on version:  1.5.0
- Operating system version/name:  LibreElec 9.2.3
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ✓ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Using the "-Perform full sync now" function, in library settings, gives me back the next error:

The add-on encountered the following error:
KeyError: u'year'

#### Expected behavior

I don't know, I've never used this function

#### Actual behavior

After some time and some titles are downloaded, the error "KeyError: u'year'" shows up

#### Steps to reproduce the behavior

1. Go to Netflix settings
2. Library
3. Perform full sync now
4. Wait for some of the titles to download
5. The error will show up

#### Possible fix

Check syntax on script???

### Debug log

The debug log can be found from this link:
https://pastebin.com/wWte5qhr

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ✓ ] I'm using a different source 
* [ ✓ ] I'm using the provided repo by CastagnaIT

**Comment by CastagnaIT** [comment]
Do an update with this:
[plugin.video.netflix_1.5.0_20200626.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4835757/plugin.video.netflix_1.5.0_20200626.zip)

and give a new log after try full sync

**Comment by franchetoxx** [comment]
https://paste.kodi.tv/kukugeqodu.kodi
the same error shows up

**Comment by CastagnaIT** [comment]
i already encountered this issue on other old issue thread
i do not found where is the problem, i tried to simplfy again the code i hope not happen again in future

Install the update:
[plugin.video.netflix_1.5.0_20200626_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4837360/plugin.video.netflix_1.5.0_20200626_t2.zip)

then, open Expert setting and do Clear cache on memory & disk

if you can try to do full sync, two times (the second **without** clear cache)

**Comment by franchetoxx** [comment]
It worked! Thanks CastagnaIT

**Comment by CastagnaIT** [comment]
also the second round sync?

**Comment by franchetoxx** [comment]
Yep
