### ISSUE TITLE
Auto Select User when movie starts

### ISSUE THREAD

**Issue by MSzturc** [CastagnaIT/plugin.video.netflix#718]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request

When a movie starts i have to select the user that watches the movie. In configuration i've configured that netflix should use a user by default, therefore i would expect that i don't have to select a user when movie starts to play.

**Comment by jakermx** [comment]
Check playback options in Addon Settings

**Comment by CastagnaIT** [comment]
?? You are mixing up the purpose of settings...
