### ISSUE TITLE
Remove Beelink GT1-A from the supported 1080P-4k-Android-tested-devices (wiki)

### ISSUE THREAD

**Issue by brazso** [CastagnaIT/plugin.video.netflix#721]
Netflix banned Beelink GT1-A device, from the end of April that device is not supported more. Beelink had been using some trial ESN of Xiaomi on its device, until it was kicked out.

Please remove the Beelink GT1-A device from the wiki site:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/List-of-1080P-4k-Android-tested-devices

(There is another ESN using the Netflix mobile app, which works, however it supports only SD video content. Using that ESN, manually overridden that in your plugin configuration, Kodi cannot play Netflix movies neither. I may create another issue on that later.)

**Comment by CastagnaIT** [comment]
Really they have not fixed yet?

I'm already in contact with this company and they answer pretty quickly

Write directly to company to:
beelinkservice@bee-link.com
and avoid the forum

Expose the problem in details,
and include also these details:
-screen shot of the ESN in original Netflix settings
-device model, SN and Build version (from android settings)

and try to ask to a fixed firmware update
let me know

**Comment by brazso** [comment]
Thanks for the advice. I have just sent an email to the Beelink service. I will inform you about their answer as soon as I receive it.

**Comment by CastagnaIT** [comment]
any news?

**Comment by brazso** [comment]
no answer from Beelink to my email... I have just sent another email forwarding my previous one to the same beelink service with the following surplus content:

> any chance to get an answer from you? I have also checked my email spam folder, but unfortunately there is no trace of your respond. Be so kind to let me know about the Netflix support status of the device.

**Comment by brazso** [comment]
These recent [posts](http://www.bee-link.com/forum.php?mod=viewthread&tid=52251&extra=page%3D1&page=10) are an excellent summarization of the problem. My presumption is that Netflix threatened Beelink, so the latter cannot play with the device ESN more. As for me I cannot watch Netflix above SD (540) resolution since the end of April, only the mobile Netflix app works on the device.

**Comment by CastagnaIT** [comment]
I have a confirmation from another user who has the same problem he decided to contact Netflix customer service and they replied that this model device is not certified

at this point i believe the suspicions are well-founded,
they have modified the firmware for unauthorized access to hi-res netflix videos

now the only way is use CoreELEC in order to have at least 1080P but is not always guaranteed

i will remove from the list
