### ISSUE TITLE
Next episode option for a TV show on raspberry pi 4

### ISSUE THREAD

**Issue by esaudet** [CastagnaIT/plugin.video.netflix#723]
#### Your Environment
- Netflix add-on version: 1.5.1
- Operating system version/name: LibreElec 9.2.1
- Device model:  Raspberry pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

I realized that the option to directly play the next episode for a TV show seems to be missing on raspberry pi. I tested on my linux computer and the option is available so it is not a missing feature. 

#### Expected behavior

A next button should appear in the playback menu when a TV show's episode is playing.

#### Actual behavior

No next button appear in the playback menu.

#### Steps to reproduce the behavior

1. Play any TV show episode
2. Notice that the next button doesn't show up

#### Possible fix

Maybe a dependency or something is missing for accessing that feature on rpi?

### Debug log

The debug log can be found from this link:
https://pastebin.com/PBHjGnvw

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

Here's a screenshot of the playback menu options on the rpi : 
![IMG_0143](https://user-images.githubusercontent.com/32800206/86026706-c3bc8d80-b9fd-11ea-956e-e7ff6aecd5fe.jpg)

Here's a screenshot of the playback menu options on a linux desktop : 
![Capture d’écran de 2020-06-29 11-40-33](https://user-images.githubusercontent.com/32800206/86026645-b30c1780-b9fd-11ea-8ebe-45ac56d7eb19.png)

**Comment by CastagnaIT** [comment]
this is handled by kodi not addon
