### ISSUE TITLE
netflix plugin crashes during install ( and after it is installed )

### ISSUE THREAD

**Issue by RobVerduijn** [CastagnaIT/plugin.video.netflix#726]
#### Your Environment
- Netflix add-on version: 1.5.1
- Operating system version/name: fedora32 x86_64
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* X Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Today my kodi htpc refused to boot properly, it kept crashing.
This is a dedicated fedora 32 htpc system using only x11/xinit scripts to start kodi. 
I install and configure this system using ansible playbooks to ensure a stable configuration.
Which is why I find it so strange that it is now broken.
I found out that wiping the kodi home directory (rm -rf /home/kodi/.* /home/kodi/* the system worked again.
So I reinabled the inputstream adaptive plugin and added the castagnait netflix repo
Then I tried to reinstall the netflix plugin,however kodi crashed when I tried this.
So I wiped the kodi homedir again and tried to install the dependencies first, which worked fine.
Then I tried installing netflix and kodi crashed immediatly after that.

After netflix crashed kodi, it reapears and the netflix is installed

#### Expected behavior
netflix plugin should install without crashing kodi

#### Actual behavior
kodi crashes when the netflix is installed

#### Steps to reproduce the behavior
install kodi
enable adaptive inputstream adapter
install netflix plugin
crash

### Debug log
the logs can be found here: 
The debug log after the installation can be found from this link: https://paste.kodi.tv/raw/yaqegixeca
the debug log after enabling debug mode in the plugin can be found here : https://paste.kodi.tv/raw/gerapafexo

#### Installation
I use your repo: https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.1.zip

#### Other information
inputstream adaptive version : 2.4.5

**Comment by wagnerch** [comment]
I am pretty sure this is going to be an bug with whomever is building your Kodi package or your OS.  From what I can tell Kodi is not a standard package that is part of Fedora, so you might need to check with the repository that provides Kodi.  The exception is coming from a Python base class, not from the Netflix addon.

You might want to try reverting to an older version of Kodi and see if that resolves your problem.  You should also review your OS logs to see what packages were updated recently and compare that against when you noticed it was working last and broken.

It's been a long time since I have ran a Red Hat distribution (way back when it was called "Red Hat 9", not enterprise, not Fedora), but I recall they tend to prefer auto-updates.

**Comment by CastagnaIT** [comment]
Fedora should have removed the support to python 2 from version 30
probably some py2 package is missing or not works
from my part i do not know how help you..

in case you will not find a solution fix, you can try to use Kodi 19 (that use py3) but remember that is a unstable version

**Comment by RobVerduijn** [comment]
I'll look into the packages (hope that is an easy fix),or else I start packaging kodi 19 (matrix)
lucky for me I also have plays for that lying around ( from back in the time when netflix plugin wouldn't run on kodi 17 and 18 was still in alpha)

**Comment by wagnerch** [comment]
@CastagnaIT 

Fedora 32 still has a backwards compat python27, apparently they didn't hit the goal of removing python 2.7 100%.  But they removed a ton of dependencies, etc, so who knows if anything is broken.  I started an lxd container with Fedora 32, dnf install python27 (latest version), and it works fine doing an "import io".

I believe Fedora 33 is when Python 2.x will be completely removed now.  Guessing Fedora 32 will probably the base for EL9 which may be the motivation to leave a python27 package.

**Comment by RobVerduijn** [comment]
Hi,

It wasn't an easy fix, it took some effort.
I packaged kodi19 (and inputstream adaptive 2.6.0), removed all python2 packages from my htpc and installed kodi 19 plus all requirements. 
Now it is working again.
As a side effect, all plugins that where broken due to python2/3 related issues now started working again.

Cheers
Rob
