### ISSUE TITLE
 I have an error message when opening the Netflix addon.

### ISSUE THREAD

**Issue by ob2000ma** [CastagnaIT/plugin.video.netflix#742]
## Bug report
![1](https://user-images.githubusercontent.com/67972817/86819479-01698800-c088-11ea-86e5-7363c6d30ff1.jpeg)
![2](https://user-images.githubusercontent.com/67972817/86819483-029ab500-c088-11ea-8184-c62fd94ba2c6.jpeg)
![3](https://user-images.githubusercontent.com/67972817/86819486-03334b80-c088-11ea-83f8-53b78a050c92.jpeg)

#### Your Environment
- Netflix add-on version: 1.6.0
- Operating system version/name: Android 8.1.0
- Device model:  Mecool KM9

**Comment by finkleandeinhorn** [comment]
It appears you either have a version of Kodi lower than Leia, you haven't I stalled Widevine, or your system isn't Widevine certified. I'm leaning more on the latter, as everything I can find regarding your device says that it is "Widevine certified", but "not Netflix certified"... I'm not sure if that would affect this add-on, as typically even "non-certified" devices can stream from Netflix, albeit only in SD.

**Comment by ob2000ma** [comment]
I have the latest vesrion from Kodi "Leia". Regarding my Android tv box, it's not Netflix certified but I saw videos on YouTube with devices also not Netflix certified and which managed to make this addon work without problem.

**Comment by CastagnaIT** [comment]
YouTube is totally different, it is not DRM encrypted
Netflix is encrypted then if your device has not a valid Widevine certification library it is not possible run Netflix

**Comment by ob2000ma** [comment]
You misunderstood me.
I wanted to say that on YouTube, there are people who have successfully installed the Netflix addon on android tv box devices that are not Netflix certified and it works very well with HD quality.

**Comment by CastagnaIT** [comment]
I understand better now
But you have posted your problem in a development section and this is not an addon problem
so i close your Issue
