### ISSUE TITLE
I tried to search something in the addon and I get this 

### ISSUE THREAD

**Issue by nammminn2** [CastagnaIT/plugin.video.netflix#744]
<img width="1280" alt="Screen_Shot_2020-07-07_at_3 46 07_PM" src="https://user-images.githubusercontent.com/64177573/86844173-a62e9a00-c075-11ea-85c1-7543581a1fe0.png">

**Comment by finkleandeinhorn** [comment]
It may help to post an actual log of the event, as they give **far** more information than this type of popup could hope to.

**Comment by CastagnaIT** [comment]
if it is a fresh install it is possible, i have forgot to add database code
i do a new release today, then you have to reinstall
