### ISSUE TITLE
Add-on not working on Linux Fedora 32 with Kodi 18 - AddonSignals: call timeout

### ISSUE THREAD

**Issue by moozhub** [CastagnaIT/plugin.video.netflix#749]
#### Your Environment
- Netflix add-on version: netflix_1.6.1_20200709_t5_30timeout & script.module.addon.signals-0.0.5_patched / netflix_1.6.1
- Operating system version/name: Fedora 32 (5.7.7-200.fc32.x86_64)
- Device model:  OEM

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

~Same AddonSignalsCall timeout as described in https://github.com/CastagnaIT/plugin.video.netflix/issues/716~

#### Expected behavior

Login / view

#### Actual behavior

Timeout

#### Steps to reproduce the behavior

1. Start Kodi
2. Install Plugin
3. Attempt login

#### Possible fix

Unsure but think you're on to it.

### Debug log

The debug log can be found from this link:
http://ix.io/2rmS

#### Installation
* [x] I'm using  CastagnaIT Netflix Repo (https://github.com/CastagnaIT/repository.castagnait) 
* [ ] I'm using a different source 

#### Other information

Tried with alternative method of connection in expert settings with same results
#### Screenshots

No useful screenshots to provide

**Comment by CastagnaIT** [comment]
> Same AddonSignalsCall timeout as described in

It is not same thing, next time do not link Issue thread unless there is a valid reason

as mentioned earlier Fedora has started removing Python2 packages from his system
https://fedoraproject.org/wiki/Changes/RetirePython2

This is not an add-on failure but a Fedora problem

**Comment by moozhub** [comment]
Yeah, that's not in anyway the same issue. If you look at my logs the plugin is still running which indicates the python dependency is still there, in fact the user in the thread you mentioned even said that python27 was left around, and in fact it is (for users and developers, also indicated in the fedora wiki you sent). But if you don't want to continue supporting that I guess I understand, but if you want to debug I'm here to help. Thanks.

**Comment by CastagnaIT** [comment]
from add-on side there is no changes to do
if it is (maybe) possible you have to do something in your operating system to fix/run python 2 enviroment

**Comment by moozhub** [comment]
I'll take any suggestions.. As noted in my log, my python2.7 environment is in my path:

2020-07-10 20:46:44.139 T:140449457108736   DEBUG: CPythonInvoker(3, /home/kodiuser/.kodi/addons/plugin.video.netflix/service.py): setting the Python path to /home/kodiuser/.kodi/addons/plugin.video.netflix:/home/kodiuser/.kodi/addons/script.module.addon.signals/lib:/home/kodiuser/.kodi/addons/script.module.certifi/lib:/home/kodiuser/.kodi/addons/script.module.chardet/lib:/home/kodiuser/.kodi/addons/script.module.future/libs:/home/kodiuser/.kodi/addons/script.module.idna/lib:/home/kodiuser/.kodi/addons/script.module.inputstreamhelper/lib:/home/kodiuser/.kodi/addons/script.module.requests/lib:/home/kodiuser/.kodi/addons/script.module.urllib3/lib:/usr/share/kodi/addons/script.module.pycryptodome/lib:/usr/lib/python27.zip:/usr/lib64/python2.7:/usr/lib64/python2.7/plat-linux2:/usr/lib64/python2.7/lib-tk:/usr/lib64/python2.7/lib-old:/usr/lib64/python2.7/lib-dynload:/usr/lib64/python2.7/site-packages:/usr/lib/python2.7/site-packages

Without this environment, I don't see *any* of my addon's working since kodi 18 is primarily python2 and hasn't migrated until kodi 19.

**Comment by CastagnaIT** [comment]
I can't help you,
not only NF but other add-ons are already broken on Fedora 32 (with Kodi 18)

I leave the Issue thread opened for a few days to let other users have time to answer you if they know of an alternative solution

**Comment by moozhub** [comment]
Appreciate your efforts, I'll try poking around to see if there might be something I'm missing. If there's an actual python version dependency required for the plugin it might be of assistance as well. Thanks

**Comment by moozhub** [comment]
@CastagnaIT I was able to get this to work, but I had to download the package from your git repository. I also downgraded to 0.0.3 of addon.signals just to make sure.. not sure if there's a difference between the kodi repository version and your git version but it's working fine now. I looked and I'm actually using the repository from (https://castagnait.github.io/repository.castagnait/), perhaps it's different? ... Thanks again..hope it helps others

**Comment by CastagnaIT** [comment]
if you use this link: https://castagnait.github.io/repository.castagnait/
is the version for Kodi 18.x
and is the same identical version provided by repository.castagnait-1.0.1.zip

i do not think change AddonSignal version make difference at least from the log provided not refer to this

**Comment by moozhub** [comment]
Not entirely sure then, no other changes were made. The procedure was uninstalling both add-ons and beginning with v 1.4.0 install and attempt login, I believe the first error had something to do with KeyError which I remember from some time ago which lasted a couple releases, but after installing version 1.5.0 I was able to login successfully all the way up to 1.6.1. I can't really explain why that is but if you want the logs of all of it happening I can setup a new kodi install to gather logs.

**Comment by CastagnaIT** [comment]
what you did doesn't make sense...
because in all versions the login is done in the same way
