### ISSUE TITLE
Different series are not updated

### ISSUE THREAD

**Issue by sajo84** [CastagnaIT/plugin.video.netflix#752]
#### Your Environment
- Netflix add-on version: **1.6.1**
- Operating system version/name: **LibreELEC V9.2.3 [official]**
- Device model:  **RPI2.arm**

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug:
Different series are not updated, for example: 
- Rick & Morty (Series 4 is missing)
- The Sinner (Series "Jamie" is missing)
- Modern Family not showing at all on "My List" from Netflix
I've already cleared the cache on the Netflix Addon and updated the Netflix List_

#### Expected behavior
It should be updated like on my official Netflix Android App on Smartphone

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
[log-2020-07-13-18.53.16.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4914540/log-2020-07-13-18.53.16.zip)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by jarandaf** [comment]
I also experience this issue with the same setup.

**Comment by CastagnaIT** [comment]
what you're talking about Kodi's library or the My List menu of the addon?

**Comment by sajo84** [comment]
It's basically in both.
In the **Netflix Addon** => **My List** and in **Kodi Library** => **TV Shows** which is linked via the "**Custom library path**" on the **Netflix Addon**

FYI: while updating the Netflix "My List" via **Addon Properties** => **Library** => "**Check for updates now**", I often got an error message "Exception: Addon Signals call timeout" (same if the Auto update is enabled on the Addon)
It may be related that the Kodi is heating up (_I see the thermometer icon on the right top of the Kodi interface; means that the ARM core(s) will be throttled back in an attempt to reduce the core temperature_.)
I've more than 60 series on "My List"...

**Comment by CastagnaIT** [comment]
you are talking about too many different problems, so we have to give an order

You have an ARM device then AddonSignals dependency not work well
some times can cause timeout due to a internal bug, a temporary solution is here:
https://github.com/CastagnaIT/plugin.video.netflix/issues/716#issuecomment-656303346

for now we talk about only for the "My List" menu list inside the add-on,
it is very strange what you say, that in this list are missing entries because it comes directly from the netflix servers there are no filters

Do these steps:
1- If you are using non original kodi skin, set the default Estuary kodi skin
2- Update with this [plugin.video.netflix_1.6.1_20200714_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4917753/plugin.video.netflix_1.6.1_20200714_t1.zip)
3- Now reboot the device
4- Open the add-on, select the profile, then select My List menu list
5- Check what is missing
6- Extract a new debug log

**Comment by sajo84** [comment]
Ciao,

Thanks for your fast response! :)

1) I've installed the **script.module.addon.signals-0.0.5_patched.zip** from #716 (comment)
2) I've installed the **plugin.video.netflix_1.6.1_20200714_t1.zip**
3) Rebooted the device, but the TV shows "Rick & Morty" or "The Sinner" for example on my profile are not updated.
4) Even when I remove "The Sinner" from My List and do a Search for "The Sinner" on the Netflix AddOn, the Search only shows Season 1 & 2 (called "Cora" & "Julian"), but the 3rd called "Jamie" is not shown (differently to my Android App).
LOG: 
[log-2020-07-14-11.40.17.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4918557/log-2020-07-14-11.40.17.zip)

**Comment by CastagnaIT** [comment]
For "The sinner" you can check by using a pc browser
i do not see season 3 but between different countries there are different release date
and also the nf releases may be delayed

what Rick & Morty problem?

**Comment by sajo84** [comment]
Hi,
- Rick & Morty Season 4 is not shown
- The Netflix Addon Search for "Modern Family" does not find the TV show, but "My List" on the Android App contains Modern Family Season 1 to 10...
**_BUT_** you're right, when I open Netflix on the browser on my PC, it's identical to Netflix on Kodi; R&M only till Season3, The Sinner only till Season2, Modern Family not available?! Strange.

I do not understand the discrepancies between the App and the Browser interface

**Comment by CastagnaIT** [comment]
Exactly, as i said the add-on has no filters, what is shown is directly the one provided, is not an addon error

The only things i could suggest are
-Are you using same profile on android and website?
-If you use different profiles try check the profile language is different (different language can cause different results, also on video availability)
-Have VPN on PC? disable it
-Try create a new profile and see what happen
