### ISSUE TITLE
Can't connect on local repository

### ISSUE THREAD

**Issue by jlgarnier** [CastagnaIT/plugin.video.netflix#754]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name:  LibreElec 9.2.3
- Device model:   Raspberry Pi4 4Gb

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

Kodi cannot connect on local repository.

#### Expected behavior

Expected: installation of Netflix plugin

#### Actual behavior

Kodi: "Cannot connect to repository" message

#### Steps to reproduce the behavior

1. Retrieved repository.castagnait-1.0.1.zip from the Github
2. Kodi: installed from zip file --> OK
3. Repository appears when I select "Install from repository" --> select it then "Cannot connect to repository" message

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

Thanks in advance for any help!

**Comment by CastagnaIT** [comment]
the repository is hosted by github
if you can not connect you have some type of connection problem

**Comment by jlgarnier** [comment]
Hi, thanks for the quick answer! I've checked the internet connection, which is given as "connected". Can you please indicate the exact URL of the repository so I can perform a last check with direct source connection?

Thanks in advance for your help!

**Comment by CastagnaIT** [comment]
https://github.com/CastagnaIT/repository.castagnait/raw/master/zip

**Comment by jlgarnier** [comment]
Thanks Stefano! I finally solved my issue by installing the genuine Raspian distro, then Kodi, which found all repositories! I still don't understand why Libreelec cannot access the internet while the connection is OK...

Thanks again for your support!
