### ISSUE TITLE
Series not working

### ISSUE THREAD

**Issue by CrudelisPL** [CastagnaIT/plugin.video.netflix#755]
#### Your Environment
- Netflix add-on version: 1.6.1
- Operating system version/name: Windows 10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ *] Windows

### Describe the bug

When adding series from netflix to the main menu using a custom widget, Kodi tries to play the folder instead of displaying its contents ([seasons] subfolders). This causes an unsupported video format error in the player. The movies work fine.
It might be the dublicate of:
https://github.com/CastagnaIT/plugin.video.netflix/issues/683

https://drive.google.com/file/d/1oFkxmuSUQ0LMkDIyh_vpn8MxSyGlz6qB/view?usp=sharing

#### Expected behavior

Shows the seasons of the series.

#### Actual behavior

Kodi tries to play a directory.
CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/directory/show/80027042/

#### Steps to reproduce the behavior

1. Add for example the most popular on netflix where there is a mix of movies and series to the main category. 
2. Try to play a series.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

![git](https://user-images.githubusercontent.com/50275622/87788010-e0015c80-c83c-11ea-9ea2-7108d540a3c6.png)

**Comment by CastagnaIT** [comment]
i do not understand the relation with #683, the menus mentioned on that Issue have been completely removed and not concern tvshow folders.

In any case i do not offer support to any widgets

https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits

**Comment by CrudelisPL** [comment]
Didn't see that, sorry.
