### ISSUE TITLE
Accessing "info" on series selection, then "browse" from info page, fails to open series.

### ISSUE THREAD

**Issue by PVrX** [CastagnaIT/plugin.video.netflix#757]
When accessing information of a series, "browse" option within this "info" window fails to open the series. It results in a few spinning circles / screen flashes, then nothing.

For movies, "play" within the "info" window does successfully play a movie selection.

Any help on this issue would be great!

**Comment by CastagnaIT** [comment]
Next time open an Issue thread in correct way thanks.

There is a bug in Kodi 18 and 19 that not handle add-on path
the "browse" button is not usable

**Comment by CastagnaIT** [comment]
I got a response from Kodi developers

For Kodi 18.x the button will not be fixed (is now EOL)
For Kodi 19.x the button will be fixed in next releases
