### ISSUE TITLE
Profile Screen Character Error

### ISSUE THREAD

**Issue by arifakyol** [CastagnaIT/plugin.video.netflix#759]
#### Your Environment
- Netflix add-on version: 1.6.1
- Operating system version/name: Kodi 18.6 Leila
- Device model:  Pi 3+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
The names on the profile screen were broken a few days ago

#### Expected behavior
Profile name "ARİF" now appears as "AR & Idot ; F"

There is a typo problem in all profiles with special characters

#### Screenshots
https://snipboard.io/frtaIn.jpg

**Comment by CastagnaIT** [comment]
These special chars are not supported on Kodi18/Python 2
you should install Kodi19 to see it correctly but it is currently in development and it is available only as _unstable build_
