### ISSUE TITLE
"Netflix error" appears after install and trying to open

### ISSUE THREAD

**Issue by Wittmannen** [CastagnaIT/plugin.video.netflix#76]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

0.14.1

### Description

I simply get "Netflix error" message when trying to run or update the add-on, also appeared after installing the add-on. All dependencies are installed and I'm running Kodi 18 (via osmc). 

### Steps to Reproduce

1. Press "open" on Netflix add-on.
2. Wait for error

**Expected behavior:** Netflix add-on opening

**Actual behavior:** Netflix doesn't open, "Netflix error" message.

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Not using any other repos or anything like that. Pretty close to stock osmc kodi.

## Debug log

https://paste.kodi.tv/ixihezaxer.kodi

## Other information

Haven't done anything other than installing it (error appeared) and trying to run it.

**Comment by Smeulf** [comment]
Looks like you're using OSMC and cryptodome library is missing.

You can try in ssh :

sudo apt install python-pip
sudo pip install pycryptodomex

**Comment by Wittmannen** [comment]
Installing pip was fine, but pycrytodomex resulted in the following

https://paste.kodi.tv/odazofuxuc

**Comment by Smeulf** [comment]
This is once again a missing py module.

You have to install Wheel this time, and some more packages may be needed...

If you need more help to install modules in OSMC, I encourage you to ask for help in their forum.

And btw, a missing Cryptodome library is not a big, but a prerequisite ^^

**Comment by Wittmannen** [comment]
I'll try on their forum then! :)
Yeah sorry, thought it was a bug since I assumed it was installed (after checking under dependencies).
Not very much of a veteran in this yet, but thanks for the help!

**Comment by adam7** [comment]
@Wittmannen You should install build-essential to add the missing build tools.

`sudo apt-get install build-essential`

You'll then be able to install wheel and cryptodomex with pip 

```
pip install wheel
pip install --user pycryptodomex
```

**Comment by Smeulf** [comment]
Just tried on OSMC, and the full sequence is, for the record:

`sudo apt-get install python-dev python-pip build-essential'

and then

`pip install wheel
pip install --user pycryptodomex`

@Wittmannen is your problem solved?

**Comment by Wittmannen** [comment]
Yeah forgot to close the issue, but adam7's instructions worked, but guess yours would have accomplished the same. 
Thanks for the help!
