### ISSUE TITLE
Netflix items/series not syncing/exporting with/to KODI (CoreELEC) library

### ISSUE THREAD

**Issue by laolab0mber** [CastagnaIT/plugin.video.netflix#762]
#### Your Environment
- Netflix add-on version: 1.6.1 
- Operating system version/name: CoreElec 9.2.1
- Device model:  Khadas Vim

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request
The Sync between Netflix (MyList etc.) is not working with the Kodi instance.
I tried just like described in the Wiki here: https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-to-export-and-sync-tv-shows-and-movies-in-Kodi-library
But even there was a "sync" dialogue my TV Show Library stays empty.

What does I need to comply with ? Is this broken in general? Or a known issue with the setup I have?
Could not find any information on that.

**Comment by CastagnaIT** [comment]
From what you say seem you have add a wrong folder path to kodi "Tv show" menu

**Comment by CastagnaIT** [comment]
Closed due to inactivity

**Comment by laolab0mber** [comment]
> From what you say seem you have add a wrong folder path to kodi "Tv show" menu

Is this even possible via UI ? Or do I need to edit any config files for that?
