### ISSUE TITLE
Issues with video playback of specific shows

### ISSUE THREAD

**Issue by MarcT** [CastagnaIT/plugin.video.netflix#764]
## Bug report
Recently I have been seeing video playack issues with Netflix on Kodi where the interlacing looks bad, and colors are missing/in the wrong place.

#### Your Environment
* Netflix add-on version: 1.6.1
* Operating system version/name: KODI 18.7
* Device model: Raspberry Pi 4

Used Operating system:

* [ ]  Android
* [ ]  iOS
* [ ]  Linux
* [ ]  OSX
* [X] Raspberry-Pi
* [ ]  Windows

This is Avatar, as you can see the colors are missing/muted. I'd almost say its black and white, but its not.
![Avatar-Neflix-1 6 1-Kodi-18 7](https://user-images.githubusercontent.com/109933/88357407-283ae600-cd39-11ea-9aee-26045bd5fdd8.jpg)
Comparison of the same scene from Netflix on Chrome on Win 10.
![Avatar-Neflix-Win10](https://user-images.githubusercontent.com/109933/88357503-78b24380-cd39-11ea-8ddf-43e2fb5180c4.jpg)
And to prove its not all video, this is Umbrella Academy on the same Pi 4
![UmbrellaAcadamy-Neflix-1 6 1-Kodi-18 7](https://user-images.githubusercontent.com/109933/88357533-967fa880-cd39-11ea-9d37-84826920c99f.jpg)
I did some additional research and it seems it only affects shows that are in 4:3. Movies and 16:9 shows are all fine. For example, the Danger Mouse classic cartoon also has the issue.

**Comment by CastagnaIT** [comment]
the addon do not handle video playback you have to report to Kodi
