### ISSUE TITLE
Video Scanner loop on start with "Keep My List and Kodi Library in sync"

### ISSUE THREAD

**Issue by elbowz** [CastagnaIT/plugin.video.netflix#771]
## Bug report

**The issue report contains a kodi.log not in debug mode, I'll try to update ASAP, sorry**

#### Your Environment
- Netflix add-on version: v1.6.1
- Operating system version/name: Ubuntu 20.04 LTS, kernel: Linux x86 64-bit version 5.4.0-40-generic

Used Operating system:
* [x] Linux

### Describe the bug

if the **Keep My List and Kodi Library in sync** option is enabled, Kodi on start looping on Video Scanning (or it maybe restart it many many times). 

This append only the when Netflix plugin perform the MyList sync. In fact, I have set it all days at 8:00 am. So, the first time I start kodi (after that time) the issue appear, if I restart kodi, the synchronization is not performed anymore (until next day). 
In the same way the issue disappear if I disable the **Keep My List and Kodi Library in sync**.

### Debug log

The debug log can be found from this link:

The kodi log (NOT IN DEBUG MODE): https://pastebin.com/raw/aYqu7CrV
I'll try to add the log for the debug mode...I have to wait since tomorrow and keep enabled the debug mode.

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
is really stuck in a loop, yes without debug not see nothing

At this time a new release is about to be released,
the functioning of the library has been _completely revised_

so it is better if you install this test preview of next release,
because i need to know if your issue persist also to the new add-on version

Before install read with attention these:
- After the update, you can not reinstall a previous/older add-on version, or the videos played from library will not works! (due to new changes)
- When the official release will be out, you have to manually re-update with the official release version, because Kodi only in this case it will not do (do not recognize the test version), i will let you know when

[plugin.video.netflix_1.7.0_20200725_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4975844/plugin.video.netflix_1.7.0_20200725_t1.zip)

Update and let me know if the problem persist

**Comment by elbowz** [comment]
This is insane speed answering ;) 

I have installed the test preview, but...I have to wait until tomorrow?!
**There is some workaround/trick to avoid to wait until tomorrow and force the plugin to sync?** (I remember the Netflix ban issue)

I have try to move ahead the scheduled time, but I haven't luck...

Unrelated: The plugin touch in anyway the movies DB? I have this error: 
`SQL: [MyVideos116.db] SQLite error SQLITE_ERROR (no such column: movie_view.c0)`
I have just eliminate the whole DB and re-scraped all...but the error is there, and ONLY on Movies and Tv Show (not on music).
Probably it's unrelated, but I don't found nothing on google...

**Comment by CastagnaIT** [comment]
The MyVideos116.db is kodi database,
is severely forbidden to the addon access to kodi database,
but i see some other unofficial addons using workarounds to access and modify the kodi database.

You have to delete the file MyVideos116.db
then run "Update library" option from the folders in Kodi library

It is also possible that  the cause of the loop is a broken kodi database

**Comment by elbowz** [comment]
> The MyVideos116.db is kodi database,
> is severely forbidden to the addon access to kodi database,
> but i see some other unofficial addons using workarounds to access and modify the kodi database.

Good to know...so could be a Kodi bug (maybe).

> You have to delete the file MyVideos116.db
> then run "Update library" option from the folders in Kodi library

Yeah, it's what I had done...same issue : (

> It is also possible that the cause of the loop is a broken kodi database

Could be...but the library works like a charm. I have discovered it because the global search (I don't remember if this is the name) didn't report movie/tv show in the result (that error appear ONLY after a global search or filter).
Anyway, It's not a Netflix plugin issues (at least could be the root trouble as you said).

> > There is some workaround/trick to avoid to wait until tomorrow and force the plugin to sync?
> 
> not easily, is needed act to add-on database manually

I have try to change system clock...but strangely don't works. We can wait tomorrow morning...

**Comment by elbowz** [comment]
debug kodi.log of today: https://pastebin.com/SmVJj5Uv

No Video Scanner Loop this time...but I really don't know if the MyList sync was done (I guess you can understand by log).

I have afraid of these lines:
```
2020-07-26 11:49:54.703 T:140687285975744   DEBUG: CSettingsManager: requested setting (lib_sync_mylist_shw_profile) was not found.
2020-07-26 11:49:54.703 T:140687285975744   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting lib_sync_mylist_shw_profile. Creating a setting on-the-fly...
```

Maybe something related to the *test preview*?

p.s. I have added a test movie to my netflix MyList...so, tomorrow I will be sure if the sync is done or not

**Comment by CastagnaIT** [comment]
You have to enable netflix debug as explained in to readme your log is "empty"...

I thing that in your addon file settings there are some settings of oldest addon version
lib_sync_mylist_shw_profile is not more used, so ignore it

**Comment by elbowz** [comment]
Sorry, I have missed that part of readme...my fault.

I'll update the log enriched with verbose logging after the scheduled sync of tomorrow.

**Comment by elbowz** [comment]
Kodi log (with debug enabled in kodi and addon settings): https://pastebin.com/FrGjDrKq

I had added a new movies in MyList but it was not added => No Sync performed (and of course no loop)

FYI: I had to update to Kodi 18.8 for test a bug fix on kodi

**Comment by CastagnaIT** [comment]
the verbose mode setting took effect after then again no info
but is now enabled

if you are experienced with database you can use "sqlite studio" software to edit nf_shared.sqlite3 database
then edit `library_auto_update_last_start` row on `shared_app_config` table and set a old date
(of course with Kodi closed)

so we have not to wait days to check...

try also to set again the profile to sync:
settings>Library>set a profile for synchronization

**Comment by elbowz** [comment]
Finally you trusted me ;)
I had written some kodi plugin in the past...

Last gift for you: https://pastebin.com/FBqekzva

**Sync performed and no loop** :+1: 

Thanks!

p.s. make me know what I have to do for future plugin update

**Comment by CastagnaIT** [comment]
eh.. it is not always easy understand the level of ability of a user
do assistance, "meet" a wide variety of type of users...

i will let you know when do the release
in the meanwhile i leave this thread opened

**Comment by elbowz** [comment]
I'm kidding...I don't know where you get the patience for "customer care".

Thanks a lot !

**Comment by CastagnaIT** [comment]
now you can update with regular 1.7.0 version:
add-on icon > contextmenu Information > update button > select 1.7.0
