### ISSUE TITLE
Padding cannot be imported even though lib is installed

### ISSUE THREAD

**Issue by AnnonymousProgrammer** [CastagnaIT/plugin.video.netflix#775]
## Bug report

Dear plugin.video.netflix community

I have tried to install the plugin according to your recommendations on your repo. I end up with a similar problem as 
in the post below (Padding cannot be imported). The lib is installed (checked it with python and python3 shell). I also 
did a reinstall. However, it did not solve my issue :(

https://github.com/CastagnaIT/plugin.video.netflix/issues/213

#### Your Environment
- Netflix add-on version: 1.6.0
- Operating system version/name: raspbian
- Device model:  Pi 3B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

I get an import error for the Python lib even though i can see it in my pip list and import it manually (are you using some venv?). This occurs when I try to start the App.

#### Expected behavior

The App should start.

#### Actual behavior

The App does not start as an import error occurs.

#### Steps to reproduce the behavior

1. Click on the App in Add-Ons
2.
3.

#### Possible fix

Somehow I must find out which python distro you are using and how to install packages to it.

### Debug log

The debug log can be found from this link:
[click here](https://github.com/AnnonymousProgrammer/error_log/blob/master/kodi.log)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Try read this solution https://github.com/CastagnaIT/plugin.video.netflix/issues/343

**Comment by AnnonymousProgrammer** [comment]
@CastagnaIT thanks for the hint but this did not work :/

**Comment by CastagnaIT** [comment]
i do not have rpi so it should better if is some other help you

but it is possible that you have a mix of libraries installed
you could try uninstall all these:
pycrypto
pycryptodome
pycryptodomex
with and without sudo

and install only "pycryptodomex" (with final: x) without sudo
should be installed only to python 2

**Comment by wagnerch** [comment]
I don't know if pycryptodome is available with Raspbian 9 (stretch), but it is with 10 (buster).  I just did:

sudo apt-get install python-pycryptodome

And good to go.  If it doesn't work, then you might want to try using pip -- but you need to install it for Python 2 (not 3).  You might also need to install libnss3, as that is a dependency I believe for InputStream Helper.

**Comment by juanpa669** [comment]
I have had the same error, and I have had to fix by myself, lost hours and days to try to find a related post,  cause my tickect has finished in the trashcan, cool!
I had finally run `pip uninstall padding` and after a `pip3 install padding` and now it "works "

**Comment by CastagnaIT** [comment]
Closed due to inactivity of author

**Comment by MPParsley** [comment]
The problem is in [the documentation for Raspberry Pi and Retropi](https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon): 

`sudo pip install wheel pycryptodomex
`
should be

`pip3 install wheel pycryptodomex
`
