### ISSUE TITLE
Profile Hidding

### ISSUE THREAD

**Issue by JemaineV** [CastagnaIT/plugin.video.netflix#776]
Hi. Great Work.
Is it possible to hide the Profile and Automatically log into 1 profile perhaps under the settings menu before officially going into the account.
Choose 1 Username profile and stick to it. Find it hard as Wife messes up and goes into mine, so would like to set it to just hers.
Tx

**Comment by CastagnaIT** [comment]
create two Kodi profiles, install the add-on on each kodi profile,
and when you are in the profiles list, open context menu on selected profile and select "Set for auto-selection"

**Comment by JemaineV** [comment]
BroYou saved my DayOn 27 Jul 2020 09:21, Stefano Gottardo <notifications@github.com> wrote:
create two Kodi profiles, install the add-on on each kodi profile,
and when you are in the profiles list, open context menu on selected profile and select "Set for auto-selection"

**Comment by JemaineV** [comment]
Just a question. Regarding this, can the master user not lock the settings on it for the secondary profile so nothing can be accessed.
