### ISSUE TITLE
KeyError: u'locale_id'

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#78]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

0.14.1-c51d582

https://github.com/CastagnaIT/plugin.video.netflix/tree/c51d58264f2269d3d1ef14cd3074e75133bc5638

### Description

Randomly, the addon generates this error: "KeyError: u'locale_id'' when starting a video.
If I try to play the video again, the error pops out again, and persists until I reboot my Raspberry Pi.
The error exists since a while, it's not related to a very recent change.

### Steps to Reproduce

Random error, can't be controlled yet.

## Context (Environment)

Rapsberry Pi3 with LibreELEC 9.0.1

### Installation

From sources https://github.com/CastagnaIT/plugin.video.netflix/tree/c51d58264f2269d3d1ef14cd3074e75133bc5638

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

## Debug log

No debug enabled, sorry : I can't yet control how to reproduce the error, and it's on my day to day setup, so debug is not always enabled as you can imagine.

https://paste.kodi.tv/wovomujonu.kodi

## Other information

Kodi language : French
Prefered audio language : User interface language
Prefer default audio streams : disabled
Prefered subtitle language : Forced only
Enale parsing for close caption : disabled

I hope it will be enough to understand what's going on.

Should you need me to run a special version for logging without enabling debug, just let me know.

**Comment by Smeulf** [comment]
Forgot to mention, because it's obvious, that the video won't start.

**Comment by CastagnaIT** [comment]
it looks like you've got your persistent global file ndb corrupted losing the key cited,
or in the profile used did not find the preferredLocale value, so get in error

we have to do some tests, when you come back we'll see how to do it

**Comment by born-to-be-root** [comment]
I have the same Problem but the error pop up every day.

**Comment by Smeulf** [comment]
@born-to-be-root is you system is OpenElec 9.0.1 with a Raspberry Pi too ? Or is it different ? If different, can you give us some details ?

Also, is 'save language and subtitles for tv show' enabled or not ? I feel it can be related.

Thanks.

**Comment by born-to-be-root** [comment]
My System is a libreelec 9.0.1 with a Raspberry Pi 3b+
I take a lock at the language Settings later and Post my Settings
Thanks

**Comment by papylhomme** [comment]
Same problem here, running LibreELEC 9.0.1 on a Raspberry Pi 3. 

For me the problem first occured a few days ago when you released the version 0.14 : it got automatically installed through the TVAddons repository, but previously I was running the version [0.13.22 from asciidisco](https://github.com/asciidisco/plugin.video.netflix) without ever encountering this.

If you need some testing I would be glad to help

**Comment by Smeulf** [comment]
Is "Save audio / subtitle settings for TV shows" enabled for both of you ?

It is on my side. Can someone tell if the error exists when it's disabled ?

Thanks.

**Comment by papylhomme** [comment]
It's also enabled on my side. I'll try to disable this parameter and I'll keep you updated soon, I run into this a few times a day.

Just now : I checked the content of the file `resources.lib.globals.ndb` while streaming, and the `locale_id` field was present. It got removed after the episode (or when I went to check the parameter's value). Then the error occurs each time I try to play something until I restart Kodi.

**Comment by CastagnaIT** [comment]
@papylhomme  please better explains the moment when it disappeared

**Comment by papylhomme** [comment]
Nothing peculiar really, I checked the file while streaming and the `locale_id` key was present. Then when the episode ended I checked the extension settings, and only then I checked the file again and noticed the key had disappeared.

I doubt it's related to me **viewing** the plugin settings, so it seems the key is removed when the playback stops (the key was present during playback).

**Comment by CastagnaIT** [comment]
note: these test must always be made with standard kodi skin, NOT use skin with widgets, that create unexpected behaviors

does it always happen in this sequence?
-Start kodi and netflix
-Play a first video, it's played? yes
-so, play a second video , it's played? no
or happens randomly?

**Comment by CastagnaIT** [comment]
but is it the only value that disappears or the file is emptied completely?

**Comment by Smeulf** [comment]
Based on my experience, the second video will pop an error randomly.

Most of the time, I can play 2 or 3 or even  more episodes without error, but sometimes I can play just one episode, then error, then reboot to play one more episode, to get the error again...

**Comment by papylhomme** [comment]
I concur with @Smeulf, first playback always works, after that it seems random (wether or not I change the show, the subtitles or the language).

@CastagnaIT The global ndb file just lacked the `locale_id`, the other keys were preserved

**Comment by papylhomme** [comment]
More information: 

- I'm not really sure of this, but I think the problem just occured for the first playback, quite some time after rebooting Kodi (usually I reboot to watch a new episode directly). Maybe an async thread writing to this file ?
- `resources.lib.globals.ndb` content:
  - before reboot `{"sub_menus": {}, "show_menus": {}, "menu_titles": {}}`
  - just after reboot -> **same**
  - after netflix startup notification `{"sub_menus": {}, "show_menus": {}, "menu_titles": {}, "locale_id": "fr-FR"}`

**Comment by papylhomme** [comment]
I can confirm the key is removed even when not using the plugin, related logs:

    2019-05-10 21:46:23.210 T:1676272496 WARNING: [plugin.video.netflix (0)] Canceling previous library update: duration >6 hours
    2019-05-10 21:46:23.453 T:1676272496 WARNING: [plugin.video.netflix (0)] Backing file does not exist or is not readable

**Comment by papylhomme** [comment]
FYI, no more problem since I disabled the library update feature.

**Comment by Smeulf** [comment]
Thanks @papylhomme.

I'll give a try on it too so my wife will be happy lol.

Furthermore, that feature is currently broken, so no need to keep it enabled yet.

**Comment by CastagnaIT** [comment]
I think that the schedule update function
it doesn't work because function points to
`XBMC.RunPlugin(plugin://{}/?action=export-new-episodes'
             '&inbackground=True)`

I can't find anything in the addon that matches "export-new-episodes"....
Maybe I'm wrong, but I don't think it's ever been implemented

**Comment by Smeulf** [comment]
About the current issue, I propose to keep the sync off for a week and report back after.

Unless you can determine what's wrong in the meantime, or you need anything else.

**Comment by CastagnaIT** [comment]
I agree

**Comment by bast69** [comment]
FYI : I have the same error, I purge the library and reboot. For the moment, no more error with the "locale_id"

**Comment by Smeulf** [comment]
No more more error since the sync is off. So it's definitely the sync service that breaks the resources.lib.globals.ndb file.

**Comment by n0valis** [comment]
I have this annoying problem as well. But I wouldn't like to to turn the sync off because I find it kind of important. Is there a way to get that going?

**Comment by Smeulf** [comment]
@n0valis I recommend you turn the function off for now.

It's not functional at all anyway, so having the option on won't synchronize the episodes. It was never implement yet.

I'm working on it, bit it takes time, and it's not so obvious. Thanks for your understanding.

**Comment by n0valis** [comment]
Oh it is not implemented it? Are you sure? I thought that new episodes were auto exported to my library at sometime. How would you explain that?

**Comment by Smeulf** [comment]
A manual refresh, or maybe it was a very erlyer version by asciidisco? (I can't remember if it was implemented or not)

For now, the code is not written here to sync new episodes. See https://github.com/CastagnaIT/plugin.video.netflix/issues/74

**Comment by n0valis** [comment]
I would really appreciate if it would be written.

**Comment by Smeulf** [comment]
@CastagnaIT would you take a look on this branch https://github.com/Smeulf/plugin.video.netflix/tree/Export_New_Episodes and comment?

The code to export new episodes is not done yet but the very basics are here, with a lot of TODO ^^

Thanks!

**Comment by jakermx** [comment]
I did have this issue, when I updated my Netflix AddOn, even updating with settings deletion , I got the Background services msg again, so services were restard, so I tried to play a movie, and I got this error, It was looking at PERSISTENT_STORAGE and cannot find locale_id Key, so I restarted my RPi and it worked as usual....

**Comment by Smeulf** [comment]
@jakermx please disable 'export new episodes' feature in the library settings for now, and you won't see the error again.

This issue is fixed on my repo, but I want to finish the new episodes work before we can push the fixes all together.

**Comment by jakermx** [comment]
I meant, that I got it when I updated the AddOn without restarting my system , once I restarted it, I did not got it.
I dont have any exported title, so I dont use Library... I post it as informational, this issue happens when update without restarting.

:)

**Comment by Smeulf** [comment]
> I dont have any exported title, so I dont use Library... I post it as informational, this issue happens when update without restarting.

Can you please ensure the feature I mentionned is really disabled?

**Comment by jakermx** [comment]
yep, it was and It still not enabled.

**Comment by Smeulf** [comment]
Ok, I take a good note about that. It might be a different issue than the one we catched. But will be harder to find out what's going on :/

Thanks.
