### ISSUE TITLE
SQLite error - no such table search

### ISSUE THREAD

**Issue by juanpa669** [CastagnaIT/plugin.video.netflix#782]
## Bug report
When clic on search button got an error dialog box and in logs says search table does not exists
#### Your Environment
- Netflix add-on version: 1.7
- Operating system version/name: Raspberry Raspbian
- Device model:  P2 B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

 sqlite error No such table search
#### Expected behavior

Expect to navigate  to the search page

#### Actual behavior

Open an error dialog box
#### Steps to reproduce the behavior

1. Open Netflix addon
2. Navigate to search link
3. Clic on it

### Debug log

The debug log can be found from this link:

What you are looking for is from line 5337
https://gist.github.com/juanpa669/b4751e34ec43256e1e7f2e39582c3ddc

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
It is not possible that a table is missing
if happen means that you tried to mix up old add-on versions/files
the easy way is delete all and reinstall

of if you have skill in database management and you not want lose settings i can try say you another way

**Comment by juanpa669** [comment]
Ok ! Let me know how (DB location, fields) to add this table in the db

**Comment by CastagnaIT** [comment]
well
the add-on will take care of everything

You just have to do this (with Kodi closed):
go to the addon user data folder
and open the database `nf_local.sqlite3`

open table: `app_config`
then go to row `local_db_version` and on column "Value" change to: `0.1`

now try open the add-on should be working

**Comment by juanpa669** [comment]
Great! Thank you very much ;)
