### ISSUE TITLE
Unable to install Netflix addon on Ubuntu 20.04

### ISSUE THREAD

**Issue by mariojuggernaut22** [CastagnaIT/plugin.video.netflix#788]
#### Your Environment
- Netflix add-on version: 
Ubuntu 20.04
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ x] OSX
* [ ] Raspberry-Pi
* [ ] Windows

Hello. Essentially when I try to install  Inputstream Helper, It says the addon is not avaliable and  when I try to install  the app. It fails to  install. What can I do to fix this?

**Comment by notoco** [comment]
You must install inputstream through your package manager. On Linux systems, it is not installed with kodi, but separately. Search for kodi-inputstream-adaptive
