### ISSUE TITLE
unable to open netflix: "netflix error" on screen

### ISSUE THREAD

**Issue by pcbatterij** [CastagnaIT/plugin.video.netflix#79]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General information
after installing the repossitory and the netflix addon I get a "netflix error" message on screen when trying to open the addon.

### Addon version used

netflix v0.14.1

### Description

after installing the repossitory and the netflix addon I get a "netflix error" message on screen when trying to open the addon.

### Steps to Reproduce

1. click on netflix addon
2. error message: Netflix error

**Expected behavior:** addon opening
**Actual behavior:** addon not opening

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreELEC release: RPi2.arm-9.0.1

## Debug log

https://paste.kodi.tv/ecobazujac.kodi

## Other information

I only have one other addon installed on my Libreelec: Vrt Nu

**Comment by CastagnaIT** [comment]
your installation of librelec has problems i don't know what kind but it's not about anything netflix addon
