### ISSUE TITLE
Skin HUB feature, does anyone know it?

### ISSUE THREAD

**Issue by CastagnaIT** [CastagnaIT/plugin.video.netflix#790]
### Describe your help request

I'm looking for someone who has some experience on the skins **_HUB feature_**

I'm primarily interested in understanding its meaning, because i have not found any documentation
Secondly, how it works, if possible with a practical example

Netflix add-on integrates an incomplete code inherited from the old version 0.14
and i need to figure out how to proceed

i need to understand if this feature require low maintenance,
then if there is already some add-on that supports this feature, i could analyze the integration code
alternatively i will delete this partial code

**Comment by dm2912** [comment]
only thing i know regarding "hubs" is what some skins are integrating which is essentially widgets presented as spotlight areas. 

So for instance, pressing "up" on a menu on the homepage would take you to a "hub" which would have menu items to the top and then a spotlight widget which is just a normal widget. 

Aura Mod uses hubs (although that skin is no longer in development)
Aura does to a degree, Arctic Horizon can do

but its just another way of presenting widgets which dont play nice with netflix addon anyway, far easier to use library



thats the only time ive heard of "Hubs" regarding kodi

**Comment by CastagnaIT** [comment]
thank you for the info
i will try to do some tests with Arctic skin to see what happens

**Comment by CastagnaIT** [comment]
the main problem with widgets is that none of the developers who integrated this thing
has thought of allowing a separate endpoint to be used
or at least add the possibility of include an argument to the end of the called path

therefore they are currently unmanageable
because it is not possible to determine whether the add-on call is coming from an widget

unfortunately the management code of these Widgets is very fragmented among the various skins
in the past i have tried to propose at some devs the addition of this parameter
but no one is willing to cooperate in finding a solution and i was rejected...

therefore for me the things will stay broken forever

I ran some tests, and the endpoint "hub" isn't called, then i will remove the existent partial code
