### ISSUE TITLE
Crashing Kodi when trying to play a netflix video

### ISSUE THREAD

**Issue by wacind** [CastagnaIT/plugin.video.netflix#8]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General information
I am using Kodi 18. - 64bit version
InputStreamAdaptive version 2.3.15

### Addon version used
Netflix Addon through the repository version 0.13.21

### Description
I installed InputStream Adaptive and then the Netflix Addon through the repository
Which installs Widevine 
However, when i go to play any video, my kodi crashes with the following log lines
https://pastebin.com/embed_js/Echc0Yu7

### Steps to Reproduce

1. installed InputStream Adaptive from kodi repo (version 2.13.15 on kodi 18 64-bit windows
2. install netflix repo from zip
3. install netflix addon which installs widevine
4. log into netflix
5. browse to any video file in netflix
6. crashes kodi

**Expected behavior:** [What you expected to happen]
play video

**Actual behavior:** [What actually happened]
crashes kodi

### Installation

* [x ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
just kodi 18 on 64 bit

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/) or [https://pastebin.com/](https://pastebin.com/)) or similar, please do not paste]

https://pastebin.com/embed_js/Echc0Yu7

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment]
I'm not supporting version 13, use the latest 14 beta by clicking button "Clone or Download" of this repository

**Comment by wacind** [comment]
Ahh nevermind. i figured out what was going on. for some reason even though i had the lastest kodi installed, it was still showing as kodi 18 rc2. i uninstalled everything and reinstalled and things look much better now.
