### ISSUE TITLE
Playback doesn't work after update to Kodi 18.8

### ISSUE THREAD

**Issue by xumxum** [CastagnaIT/plugin.video.netflix#811]
Playback doesn't work after system update including to Kodi 18.8. 

#### Your Environment
- Netflix add-on version: 1.6.1
- Kodi: 18.8 (Build: 18.8.0)
- Operating system version/name: Arch Linux
- Device model:  Intel NUC

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Playback does not work anymore after system update including to Kodi 18.8(Build 18.8.0). Was working fine on Kodi 18.7.

020-08-17 09:45:49.922 T:140049880704768   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2020-08-17 09:45:49.922 T:140049880704768   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/70283264/season/80066406/episode/80094486/?profile_guid=3BHDTBIKI5AOLCBYIA6TE7P3TM]

#### Expected behavior
Playback should start immediatly

#### Actual behavior
Nothing happens on selecting a movie/episode.  Error in the log

#### Steps to reproduce the behavior
1. Select any movie tv/show to play 

### Debug log
https://paste.kodi.tv/qesefuqohe.kodi

**Comment by CastagnaIT** [comment]
`ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation`

Your error comes from another component: inputstream.adaptive
not concern this add-on

this to me suggest two things:
that your device has badly updated Kodi components in Kodi upgrade
or you have tried rollback Kodi version or mixed versions which has broken the dependencies
