### ISSUE TITLE
auto load subtitle, subtitle language same with Netflix profile language

### ISSUE THREAD

**Issue by kokikoku** [CastagnaIT/plugin.video.netflix#829]
## Feature request
I'm submitting a proposal to ...
  - [Y ] new feature
  - [ ] change an existing feature

### Describe your request

the subtitles for each program need select seperately. 

#### Describe the use case

is't possible to auto load subtitle and subtitle language same with Netflix profile languge. reduce remote buttons touch for subtitle language select.

#### Screenshots

> the management and loading of subtitles is done by Kodi core not the add-on
> before you have to ask to Kodi devs (for external files)
> 
> you means external file?

Netflix original subtitles auto match.

**Comment by CastagnaIT** [comment]
the management and loading of subtitles is done by Kodi core not the add-on
before you have to ask to Kodi devs

**Comment by kokikoku** [comment]
@CastagnaIT i mean Netflix original subtitle, auto match profile language.

**Comment by notoco** [comment]
In **Kodi** (not in Netflix Addon) go to: Settings - Player - Language - Prefered Subtitle Language

**Comment by kokikoku** [comment]
@notoco It's work. Thanks a lot!

**Comment by kokikoku** [comment]
> In **Kodi** (not in Netflix Addon) go to: Settings - Player - Language - Prefered Subtitle Language

Not work on Kodi 19 beta 2 anyone?  Netflix Adds-on version 1.12.0.
