### ISSUE TITLE
the netflix repository config does not inform the system about minor updates

### ISSUE THREAD

**Issue by RobVerduijn** [CastagnaIT/plugin.video.netflix#833]
#### Your Environment
sorry can't create an issue for the repository project, therefore I create it here

fedora32 64bit
latest git build of kodi 19 ( but this also fails on 18 )

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
all works fine except the update notifications

I get updates for 1.x releases.
ie the kodi system updates when the version is increased from 1.7 to 1.8
but when the version increase is a minor one like 1.8.0 to 1.8.1 it will not automatically update.
this has been the case since the beginning of this repository
something seems botched in the repository meta data

 #### Expected behavior
minor updates are also picked up by the kodi system

#### Actual behavior
minor updates are not picked up by the kodi system

#### Steps to reproduce the behavior
install kodi
install the netflix repo
install 1.8.0
see if it updates to 1.8.1 ( not yet released but once it does you will see it won't update )
install 1.7.0 to see the automatic update to  1.8.0

### Debug log
I'm not sure this is needed and can't really create it since the kodi system sees no errors (not even in debug)

**Comment by CastagnaIT** [comment]
usually if you install from the repository the add-on is updated automatically

if you install the add-on manually, before installing the repository, it is possible that the installed add-on is not connected to the source repository then it will not updated

**Comment by CastagnaIT** [comment]
In Kodi 19 Kodi devs are performing repository management changes and updates
you should have to ask to kodi devs

**Comment by CastagnaIT** [comment]
just performed a test and the repository work as expected
minor versions are recognized
so your problem is not here

also keep in mind that when Kodi performs a version availability check,
for a subsequent check it is necessary to wait 24h
