### ISSUE TITLE
Kodi Matrix git on Ubuntu 18.04 sqlite3.OperationalError: near "ON": syntax error

### ISSUE THREAD

**Issue by prinskarnatie** [CastagnaIT/plugin.video.netflix#836]
#### Your Environment
- Netflix add-on version: 1.8 git master 889b5dc
- Operating system version/name: Ubuntu 18.04
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [X ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

After addon commit b5d5de2, the addon throws following error : sqlite3.OperationalError: near "ON": syntax error when opening addon from Kodi. After some investigation, the above mention commit requires that when running Kodi Matrix, SQLite has to be on version 3.24.0 or higher. The highest version level available on Ubuntu 18.04 is 3.22.0.

#### Expected behavior

Addon should open.

#### Actual behavior

Addon returns error on open.

#### Steps to reproduce the behavior

1. Open addon on Kodi Matrix running Ubuntu 18.04
2.
3.

#### Possible fix

The current version check for the SQL upsert which requires SQLite 3.24 is done by checking for Python 2 (Kodi 18 vs 19?). To fix on my system I modified the version check to check the SQLite version. I'm sure there is a much better way to do.

diff --git a/resources/lib/database/db_base_sqlite.py b/resources/lib/database/db_base_sqlite.py
index 979c75f..c609e66 100644
--- a/resources/lib/database/db_base_sqlite.py
+++ b/resources/lib/database/db_base_sqlite.py
@@ -245,7 +245,7 @@ class SQLiteDatabase(db_base.BaseDatabase):
         table_columns = table[1]
         # Doing many sqlite operations at the same makes the performance much worse (especially on Kodi 18)
         # The use of 'executemany' and 'transaction' can improve performance up to about 75% !!
-        if G.PY_IS_VER2:
+        if tuple(sql.sqlite_version.split("."))[0:2] < ('3', '24'):
             query = 'INSERT OR REPLACE INTO {} ({}, {}) VALUES (?, ?)'.format(table_name,
                                                                               table_columns[0],
                                                                               table_columns[1])

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/anupubiseq.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [x ] I'm using a different source 
Git master branch

**Comment by CastagnaIT** [comment]
Thanks for your good explaination
i will consider your change
