### ISSUE TITLE
Netflix 4K won't work after update to Android Pie

### ISSUE THREAD

**Issue by almirsahbaz** [CastagnaIT/plugin.video.netflix#838]
#### Your Environment
- Netflix add-on version:  1.8.0.
- Operating system version/name:  Android TV OS 9 Pie
- Device model:   EON box - Kaon KSTB6020/SDMC SDOTT0202

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

EON box (Kaon KSTB6020) - United Group
After I got update to version 9 Pie, Netflix add-on stoped showing 4K content, and I can't make it work with any of the settings under expert tab.
Firmware version is 1.1.5.
Build: PTT1.190228.001 release keys

This is also happening on EON OTT box (SDMC SDOTT0202)
Firmware version is 9.3.32
Build: Build: PI.20190720 release-keys

I can see that EON box is under devices that support 4K.

#### Expected behavior

It should play 4K content, because it was working great on Android 8.

#### Actual behavior

It play's only 720x480p content or 960p content on 4K settings.

#### Steps to reproduce the behavior

1. Open Netflix app
2. Play 4K movie
3. It play only 480p.or 960p

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/rovomuboqe.kodi

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by almirsahbaz** [comment]
I can only install mobile version of the app on both devices.

TV version displays this error:

![image](https://user-images.githubusercontent.com/34383528/92136023-d2635e80-ee0b-11ea-9a69-73daeb02b015.png)

Android mobile version on Kaon EON box (which allowed 4K content before) shows this for ESN:

![image](https://user-images.githubusercontent.com/34383528/92136115-f030c380-ee0b-11ea-8e23-18cf703e1103.png)

I couldn't run Playback info on this devices because of screen positioning, but I was able to show you results from DRM Info:

![image](https://user-images.githubusercontent.com/34383528/92136254-16eefa00-ee0c-11ea-8ad5-7ba73dfcc3d9.png)
![image](https://user-images.githubusercontent.com/34383528/92136284-2110f880-ee0c-11ea-88c1-4a6fa43d8b57.png)
![image](https://user-images.githubusercontent.com/34383528/92136314-2bcb8d80-ee0c-11ea-8c73-abaf77b21b11.png)
![image](https://user-images.githubusercontent.com/34383528/92136359-38e87c80-ee0c-11ea-9bfc-71aa6c5f3c3d.png)
![image](https://user-images.githubusercontent.com/34383528/92136377-3dad3080-ee0c-11ea-9029-a5ef1e576903.png)
![image](https://user-images.githubusercontent.com/34383528/92136390-4271e480-ee0c-11ea-8166-6c7c3b7814ab.png)

This is ESN for SDMC version of the box:

![image](https://user-images.githubusercontent.com/34383528/92136438-50c00080-ee0c-11ea-9393-5ad9037d8a1f.png)

And here is its Playback info:

![image](https://user-images.githubusercontent.com/34383528/92136501-633a3a00-ee0c-11ea-811e-eba10c3e3f8e.png)

**Comment by CastagnaIT** [comment]
Well,
all this means that this new version android firmware of EON is not certified to play netflix 4k
or is possible that they will have to publish in future a new certified firmware

To be able to play 4k:
-The original app have to be available on playstore
-The original app have to report:
Widevine:L1
HD on resolution 
HEVC to Codecs for HDR

whitout this you are out of the game...

**Comment by almirsahbaz** [comment]
> 
> 
> Well,
> all this means that this new version android firmware of EON is not certified to play netflix 4k
> or is possible that they will have to publish in future a new certified firmware
> 
> To be able to play 4k:
> -The original app have to be available on playstore
> -The original app have to report:
> Widevine:L1
> HD on resolution
> HEVC to Codecs for HDR
> 
> whitout this you are out of the game...

I have TV Android TV devices that are certified for Netflix, can I use their ESN numbers for Netflix Kodi add-on.

I tried to put it in Manual ESR section in Expert mode, but I kept getting validation key error.
