### ISSUE TITLE
Serach tool not working on 1.8.0

### ISSUE THREAD

**Issue by mflorezm** [CastagnaIT/plugin.video.netflix#843]
Hi, I'm using your plugin.video.netflix 1.8.0 in on a RPI4 with Leia 18.6 and librelec 9.2.1.

It works like a charms, but the search tool since a couple of weeks is giving me a DBSQLiteError. The error was present on a previously version too. Any ideas on how to solve this?

Below there are two images from my kodi's log.

Thanks.

Mauriio F.

![20200903_175853](https://user-images.githubusercontent.com/7923418/92186988-1cedd680-ee1e-11ea-8de1-20926c693cb1.jpg)
![20200903_175937](https://user-images.githubusercontent.com/7923418/92186992-1f503080-ee1e-11ea-8cde-e56415e95228.jpg)

**Comment by CastagnaIT** [comment]
you have a broken addon database reinstall the addon

**Comment by mflorezm** [comment]
Thanks
