### ISSUE TITLE
Use the changelog for the GitHub release

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#853]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
It would be useful if the Netflix add-on releases in GitHub would get the changelog added so that people watching this project get releases with changelog in their mailbox. It would make it more useful to watch this project.

See: https://github.com/add-ons/plugin.video.vrt.nu/releases

If you like I can make a GitHub action that would automatically release and get the changelog entry from addon.xml into the official release. Then if you tag a commit, it would automatically make the release for you. This is how VRT NU is doing this. (It also pushes the release upstream for Krypton and Matrix, but that is not possible here)

**Comment by npmstart-pray** [comment]
I fully support this request.

**Comment by CastagnaIT** [comment]
so i understand correctly

i create a release  tag to a commit (due to verbump)
after github read automatically the xml and add to the tag the info
and create/add also the zip's to the release tag

if it does automatically i think you can add it
