### ISSUE TITLE
Exeption: authentication file not supported

### ISSUE THREAD

**Issue by switherjunkie** [CastagnaIT/plugin.video.netflix#857]
I'm trying to run this on pop os linux distro, this particular exception is show when i try to log in using the authentication file. Please help me out.

**Comment by gudge25** [comment]
same problem

**Comment by gudge25** [comment]
2020-09-10 20:48:34.651 T:140375320733440   ERROR: [plugin.video.netflix (83)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in wrapper
                                                func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 249, in run
                                                success = route(pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 88, in lazy_login_wrapper
                                                if _check_valid_credentials():
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 73, in _check_valid_credentials
                                                if not login():
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 65, in login
                                                data = common.run_nf_authentication_key()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 135, in run_nf_authentication_key
                                                return _prepare_authentication_key_data(data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 189, in _prepare_authentication_key_data
                                                raise Exception('Authentication key file not supported')
                                            Exception: Authentication key file not supported
2020-09-10 20:48:47.832 T:140376904034048  NOTICE: script.tv.show.next.aired: ### no prior data found
2020-09-10 20:48:49.835 T:140376904034048  NOTICE: script.tv.show.next.aired: ### starting data update
2020-09-10 20:48:49.835 T:140376904034048  NOTICE: script.tv.show.next.aired: ### grabbing a new country mapping list

**Comment by gudge25** [comment]
antonio@antonio-MS-7596:~/Downloads/NFAuthenticationKey$ python3 NFAuthenticationKey.py

NFAuthentication Key for linux (Version 1.0.0)

Disclaimer:
This script and source code available on GitHub are provided "as is" without warranty of any kind, either express or implied. Use at your own risk. The use of the software is done at your own discretion and risk with the agreement that you will be solely responsible for any damage resulting from such activities and you are solely responsible for adequate data protection.

Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Browser startup... please wait
Establish connection with the browser... please wait
Opening login webpage... please wait
Please login in to website now ...waiting for you to finish...
Verification of data in progress... please wait
File creation in progress... please wait
Operations completed!
The "NFAuthentication.key" file has been saved in current folder.
Your PIN protection is: 3153

**Comment by gudge25** [comment]
version 1.9.0

**Comment by switherjunkie** [comment]
> version 1.9.0

is it working for you now ?

**Comment by switherjunkie** [comment]
The pin has been generated for me too, I'm facing this issue when I try to log in after typing in the pin.

**Comment by gudge25** [comment]
I have found a workaround.
I have created key file from windows and successfuli is se it on Linux

**Comment by gudge25** [comment]
> > version 1.9.0
> 
> is it working for you now ?

See my prev message

**Comment by t-morales** [comment]
I also have the same problem. I cannot login to netflix using email and password so I tried the new method instead. I get exactly the same problem.
I cannot use the workaround since I am using linux and do not have a windows to create key

**Comment by t-morales** [comment]
OK, actually I found what the problem was. It is quite easy:
In the file 
plugin.video.netflix/resources/lib/common/credentials.py 
comment line #180 which says:
data['app_system'] == 'Windows' and
This was False in linux sytem and rising an exception afterwards
After that I could log in with key file

**Comment by klacointe** [comment]
> OK, actually I found what the problem was. It is quite easy:
> In the file
> plugin.video.netflix/resources/lib/common/credentials.py
> comment line 180 which says:
> data['app_system'] == 'Windows' and
> This was False in linux system and raising an exception afterwards
> After that I could log in with key file

Same problem and resolution here. Just comment this line `data['app_system'] == 'Windows'` and it works. (I needed to reboot libreelec)

Thanks @t-morales

**Comment by CastagnaIT** [comment]
no one ever learns to read posts in the thread
it is clearly explained what to do
https://github.com/CastagnaIT/plugin.video.netflix/issues/502#issuecomment-689386047

this change is not needed

**Comment by fabianbur** [comment]
I can confirm that the file for Linux is broken.

The message appears: The "NFAuthentication.key" file has been saved in current folder. when authenticating.
I generate it again in a windows virtual machine and it can now enter. I hope it won't break in the future. Thank you

**Comment by notoco** [comment]
Works perfectly - on 3 computers with different systems (Arch / Ubuntu / Mint) and then uploaded to coreelec. The most important thing is:
https://github.com/CastagnaIT/plugin.video.netflix/issues/502#issuecomment-689386047

> Before you have to update the add-on with last DailyBuild version (link in the readme)
