### ISSUE TITLE
VPN not working with Netflix

### ISSUE THREAD

**Issue by Curraheee** [CastagnaIT/plugin.video.netflix#860]
#### Your Environment
- Netflix add-on version: 1.9.0
- Operating system version/name: CoreELEC 9.2.4.2
- Device model:  Odroid N2

Used Operating system:
CoreELEC 9.2.4.2

### Describe the bug
When I install the Netflix addon, VPN Manager (https://github.com/Zomboided/service.vpn.manager) stop working. Uninstal Netflix addon and VPN Manager working fine. But netflix addon working perfect!

#### Expected behavior
When connecting to VPN error: Could not authenticate with VPN provider, Please check user name and password and try again.

#### Steps to reproduce the behavior
1. Change protocol VPN UDP to TCP
2. Change starting VPN before kodi starts
3. Uninstal Netflix addon and VPN working correct.

#### Possible fix
Any service of Netflix running in the background blocked VPN?

### Debug log
The debug log can be found from this link:
https://paste.kodi.tv/ibawobodug.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
before try install an older CoreELEC version that contains Kodi 18.6
and let me know if works

i remember you that here we not provide support to use VPN with netflix https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy

**Comment by CastagnaIT** [comment]
closed due to inactivity
