### ISSUE TITLE
Authentication key file not supported - Linux

### ISSUE THREAD

**Issue by batuhanfaik** [CastagnaIT/plugin.video.netflix#861]
#### Your Environment
- Netflix add-on version: 1.9.0
- Operating system version/name: Ubuntu 18.04
- Device model:  Raspberry-Pi 3B

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
I had issues with logging in (#502) so I followed the instructions on [here](https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key). I used Ubuntu 18.04 to create the .key file then transferred it to my Pi using scp. Then I tried to authenticate using the key and after entering the correct pin, I got the following message:
Exception: Authentication key file not supported

### Debug log
The debug log (kodi.log file) can be found on this link:
https://paste.ubuntu.com/p/b3tnMTdzFC/

**Comment by batuhanfaik** [comment]
I've tried creating the key using Windows and everything worked fine. Probably there is an issue with the NFAuthenticationKey.py or credentials.py

**Comment by CastagnaIT** [comment]
it is all explained in the Issue thread
https://github.com/CastagnaIT/plugin.video.netflix/issues/502
