### ISSUE TITLE
Netflix shows some videos only black and white

### ISSUE THREAD

**Issue by cbaptista** [CastagnaIT/plugin.video.netflix#863]
Hi,
I have opened this bug on the older repository, asciidisco, sorry for that.
I have an installation with XBian  and this netflix plugin with a problem. Some videos only show black and white and I can't fix it.
This as snip of kodi.log with one of the videos, the episode 18 of season 5 StarTrek Voyager. This also happened with The Big Bang Theory and Lucifer

[DELETED - no log as comment]

Any idea?

Thanks

Carlos Baptista

**Comment by npmstart-pray** [comment]
Also using xbian: kodi 18.8 on RasPi 4. 
Can’t report the same issue. 
Is your WideVine/Inputstream adaptive current?

**Comment by CastagnaIT** [comment]
This problem is focoused to LibreElec
you have to report to LibreElec or Kodi devs
NF addon do not do video decoding

in ISA a thread is already open
https://github.com/peak3d/inputstream.adaptive/issues/509

**Comment by jakermx** [comment]
Try LibreElec 9.2.4 - Just Installed a new one frm the scratch and works without issues on my RPi2 B ,3B+,and 4B w/8GB

I saw the complete Lucifer Series less than a month from now without any issues. ÇJust Limit Streams on NF, dont change any config on ISA.

Hope it helps.

**Comment by cbaptista** [comment]
Hi all,
I solved my problem.
addons settings -> netflix -> expert -> limit resolution to 1080p
all videos are working now

**Comment by edurenye** [comment]
Limiting resolution did not work for me.
