### ISSUE TITLE
Keymap Button Export 

### ISSUE THREAD

**Issue by ro0o0ge** [CastagnaIT/plugin.video.netflix#864]
## Feature request
I'm submitting a proposal to @CastagnaIT 
  - [*] new feature
  - [ ] change an existing feature

### Describe your request

I was hoping to export a selected video, using a custom keymap request to the route() function, which would add that specific movie/tv show to the local library. 

However, when I viewed the code, I noticed that the common.videoId object needs to be passed to that keymap-export function, and AFAIK there is no way to get the common.videoId object to pass it to that function.

#### Describe the use case

After adding a keymap value in the keyboard.xml (i.e. <f12>XBMC.RunPlugin(plugin://plugin.video.netflix/library/keymapexport)</f12>   
 Clicking on F12 while a list of movies\tv shows is open (and selecting one of them), would add that movie/show to the local library.

**Comment by CastagnaIT** [comment]
seems interesting
the only thing is that I have some doubts about updating the data on the screen (because it would be done by a different addon instance)
and the reliability of this system to complete the operations without overlapping when commands are repeated too quickly
when i have time i will try

**Comment by CastagnaIT** [comment]
This is the test update, let me know:
[plugin.video.netflix_1.9.1_20200927_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5288389/plugin.video.netflix_1.9.1_20200927_t1.zip)

the endpoind are:
Export to library
`RunPlugin(plugin://plugin.video.netflix/keymaps/lib_export)`

Remove from library
`RunPlugin(plugin://plugin.video.netflix/keymaps/lib_remove)`

**Comment by ro0o0ge** [comment]
Now that works like charm, thanks for the help much appreciated.
