### ISSUE TITLE
build_media_tag: unable to find video data with codec" error popping up after watching netflix video video

### ISSUE THREAD

**Issue by matejdro** [CastagnaIT/plugin.video.netflix#866]
#### Your Environment
- Netflix add-on version: 1.9.1
- Operating system version/name: Manjaro Linux

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Sometimes, after watching Netflix content and then moving on to non-netflix content, following mesage will start popping up every couple of minutes:

![image](https://user-images.githubusercontent.com/507922/93816675-236eb180-fc58-11ea-9ca1-16311a538152.png)

#### Expected behavior

Netflix plugin shouldn't pop up errors or do anything at all when I'm not watching Netflix content

#### Actual behavior

Netflix pops up error message every couple of minutes

#### Steps to reproduce the behavior
1. Watch a Netflix video
2. Finish watching a Netflix video
2. Start watching a non-Netflix video (for example video from local disk)

(Every time I perform above steps, there is a small-ish chance for the bug to reproduce. It doesn't always happen)

### Debug log
The debug log can be found from this link: [kodi2.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5257954/kodi2.log)

(Log is not in verbose mode since I cannot know when the bug will happen and I cannot put Kodi into verbose mode prematurely. If above log is not enough I can enable verbose mode all the time and wait for the next instance of this bug).

**Comment by CastagnaIT** [comment]
unfurnately a log without kodi/netflix verbose debug in this case is not helpful

happens when you play only 1 netflix video since you opened Kodi? 
if you notice any other particular pattern to reproduce this problem please let me know

**Comment by matejdro** [comment]
I set the login to Verbose, but there is no additional output. I assume Verbose mode only works when debugging is on? I will try this the next time, but debugging overlay makes watching videos pretty annoying.

> happens when you play only 1 netflix video since you opened Kodi?

Yes, that's the pattern:

1. Open Kodi
2. Play one Netflix video
3. Play one non-netflix video (I suspect letting kodi run idle would also work, but I have to test it).

Also, any idea what is pluggin doing in the background anyway? I thought it was only supposed to be serving Netflix videos.

**Comment by CastagnaIT** [comment]
I tried to reproduce the problem as described, but in my station it does not happen,
so without debug log i don't know what might happen on your device

do you can try to play only 5 or 10 minutes without waiting until the end?

**Comment by matejdro** [comment]
I managed to reproduce it with debugging enabled:

[kodi4.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5285098/kodi4.log)

**Comment by CastagnaIT** [comment]
sadly you have forgot to enable netflix debug:

> 2020-09-25 21:13:57.568 T:140305491809856    INFO: [plugin.video.netflix (1)] The debug logging level is set as "Disabled"

I do not have enough information to understand something...

**Comment by matejdro** [comment]
I did not realize Verbose tag resets itself after restart. Here is another try:

[kodi5.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5287279/kodi5.log)

**Comment by CastagnaIT** [comment]
it good now,
a question you watch to the end the video,
but you leave in-playback the video in background before start another one non-netflix?

**Comment by matejdro** [comment]
I think so:

1. Video ends (credits start to roll)
2. I press back button to get I to the menu (Netflix credits are still
rolling in background)
3. I find the new video and start it
4. Credits stop and new video starts

**Comment by CastagnaIT** [comment]
this is an important step that was missing in the steps
now i can reproduce it
i will try to find a solution

**Comment by CastagnaIT** [comment]
Now should works good:
[plugin.video.netflix_1.9.1_20200927_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5288153/plugin.video.netflix_1.9.1_20200927_t1.zip)
let me know

**Comment by matejdro** [comment]
At first test it works great. Will test some more and reopen if issue reappear.

Thanks!
