### ISSUE TITLE
ConnectionError: HTTPSConnectionPool - Max retries exceeded with url

### ISSUE THREAD

**Issue by AreaScout** [CastagnaIT/plugin.video.netflix#868]
#### Your Environment
- Netflix add-on version: 19.1
- Operating system version/name: Debian 10 
- Device model:  ODROID XU4Q

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Upon Logon I get the following error message
`ConnectionError: HTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x8d4c6070>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

#### Expected behavior
Granted Logon and able to browse movie database and watch movies 

#### Actual behavior
![20200923_142439](https://user-images.githubusercontent.com/1681560/94012181-b9b1ed00-fda8-11ea-9d0f-ab9e042edf10.jpg)

#### Steps to reproduce the behavior
Logon

#### Possible fix
I haven't seen any other issue report about this error, maybe it's a local network problem, but I can't see any problem here, I am waiting what others can tell

### Debug log

[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5268099/kodi.log)

**Comment by AreaScout** [comment]
Ok I found it, it was a strange DNS server problem, still don't know if it was just my wlan router or the route from my providers DNS server, I used the one from google 8.8.8.8 and that worked

**Comment by ShadowRaiderZA** [comment]
Hi AreaScout. 

So I had  the same problem as you. It seems like it might be a local network area. I reset my DNS to 8.8.8.8 as well. Reset my device and it is working perfect.

**Comment by AreaScout** [comment]
Good that I could help ! :)
