### ISSUE TITLE
Exception: build_media_tag: unable to find audio data with language: gl, channels: 2.0

### ISSUE THREAD

**Issue by naciohr** [CastagnaIT/plugin.video.netflix#869]
#### Your Environment
- Netflix add-on version: 1.9.0
- Operating system version/name: LibreElec 9.2.4
- Device model: Raspberry Pi 3 B+ 

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Kodi pops up an error of an exception **build_media_tag: unable to find audio data with language: gl, channels: 2.0**. The error pops up at starting and along the video stream at random intervals of time. It needs user interaction to acknowledge (Accept) every time.

After troubleshooting, it looks as if the error happens only when the audio track **es-Spain** is selected. If the track is selected after the stream was started in a different language, the error comes out after quiting the pop up menu.

However, I tested with other stream that uses **spa** as the name of the audio track and it does not fail.

#### Expected behavior

No errors.

#### Actual behavior

Popping up the described error when audio track tagged as **es-Spain** is selected.

#### Steps to reproduce the behavior

Error message:
1. Start any *Narcos* episode.
2. Choose audio track **es-Spain**

No error message
1. Start any *Narcos* episode.
2. Choose any audo track different to **es-Spain**.

#### Possible fix

My Kodi baseline language is gl_ES (Galician) and that may conflict with es_ES (Spanish - Spain) if expected by the plugin.

### Debug log

The debug log can be found from these links:
- Logs with Netflix debug verbose only: [short log of error](https://raw.githubusercontent.com/naciohr/public/master/plugin.video.netflix-logs).
- Logs with Netflix debug verbose and Kodi debug: [full log of error](https://raw.githubusercontent.com/naciohr/public/master/plugin.video.netflix-logs_DEBUG).
- Logs with Netflix debug verbose only: [short log - no error](https://raw.githubusercontent.com/naciohr/public/master/plugin.video.netflix-logs_working).
- Logs with Netflix debug verbose and Kodi debug: [full log - no error](https://raw.githubusercontent.com/naciohr/public/master/plugin.video.netflix-logs_working_DEBUG).

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

![Error popup](https://raw.githubusercontent.com/naciohr/public/master/Captura%20de%20ecr%C3%A3%202020-09-24%2C%20%C3%A0s%2019.16.59.png)

![Audio track (fluxo de son)](https://raw.githubusercontent.com/naciohr/public/master/Captura%20de%20ecr%C3%A3%202020-09-24%2C%20%C3%A0s%2019.34.56.png)

**Comment by CastagnaIT** [comment]
i need to know two more things
-what profile language is set to the netflix profile used
-if you are able, from the addon user-data folder get the file "manifest.json" after played the video (mandatory nf addon verbose debug enabled from expert setting)

**Comment by jakermx** [comment]
Hi,

I also have RPi 3 B+ with LibreElec...no Errors at all, try setting default audio and subtitle languages, on KODI Settings,  Player,  Languages...I use my default to English or Spanish , even I use Spanish - Mexico (Latin).

Hope it helps.

**Comment by naciohr** [comment]
Hello,

Thanks for your replies. Regarding Kodi player language, audio is already set to Media Default.

Regarding the questions:
1. Netflix user's profile language is set to Spanish. I see Netflix addon in English because there is no translation to Galician… yet (I will try).
2. [manifest file](https://raw.githubusercontent.com/naciohr/public/master/manifest.json) taken with Kodi and Netflix verbose debugging.

Many thanks again.

Regards.

**Comment by CastagnaIT** [comment]
I think i have fould the problem, try update test and let me know:
[plugin.video.netflix_1.9.1_20200926_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5286357/plugin.video.netflix_1.9.1_20200926_t1.zip)

**Comment by naciohr** [comment]
Yes! It works smooth now!

Thank you very much.
