### ISSUE TITLE
Netflix on kodi 

### ISSUE THREAD

**Issue by strickl72** [CastagnaIT/plugin.video.netflix#870]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by strickl72** [comment]
Since the recent update to Netflix. I  can't login  on Netflix inside kodi. It keeps telling me invalid password. It works on regular Netflix. Please fix it

**Comment by MartChic** [comment]
You will have to provide a log...

**Comment by strickl72** [comment]
What do you mean by provide a log

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 24, 2020 at 4:27 PM, MartChic<notifications@github.com> wrote:   


You will have to provide a log...

**Comment by strickl72** [comment]
I don't know what you mean by provide a log much less how to do it.
I signed out of Netflix on kodi 3 days ago, and haven't bee able to sign back in. I EVEN changed  my password.

**Comment by greentechno01** [comment]
Hi,
I Made a log. Also there is something wrong after it outputs the wrong password info, it forces/opens the other authentication window method open. Maybe not a bug.. I left some keystrokes on the log.. Tried to take the identifications out. Let me know If there is still something majour left :D.. Hope this helps.. If you need something that is removed, we have to email or something.
Included system info. All the support softwares are latest versions. Android 6.xx Minix Neo U9 and Kodi 18.8.

[KODI NETFLIX BUG.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/5280581/KODI.NETFLIX.BUG.txt)

**Comment by greentechno01** [comment]
netflix addon 19.1.. So latest.

**Comment by notoco** [comment]
Read readme and wiki There is a new login method. Just read and apply.

**Comment by strickl72** [comment]
Where do I find that? I have a build that had the Castagnal repo on it already.

Sent from Yahoo Mail on Android 
 
  On Fri, Sep 25, 2020 at 12:28 AM, notoco<notifications@github.com> wrote:   


Read readme and wiki There is a new login method. Just read and apply.

**Comment by greentechno01** [comment]
Can you use the win laptop extracted authentication file on ANDROID? Not installing linux just to get it and hard to change everyday.. :/. Or can the linux version .exe used on Android with android chrome? Maybe a time for a used firestick.. :/

**Comment by greentechno01** [comment]
Is there something funny on the keystroke lines on my logs? :)

**Comment by notoco** [comment]
@strickl72 RTFM! read the readme on this page. Just read. You have all the information and links there. Nobody will rewrite it here because someone doesn't want to read it.

**Comment by notoco** [comment]
@greentechno01 Yes, you can run the program on windows and upload the file to any other system (android / coreelec / rasppbery etc.).

**Comment by scamper07** [comment]
Not sure if this is the right place to comment, but the script NFAuthenticationKey.py fails if the Netflix account has multiple profiles.
As a workaround, I had to comment out
`        if 'falcorCache' not in html_page:
            raise Warning('Possible wrong login or unexpected problem, please try again.')`
after which the key was generated and i was able to successfully login to Netflix on Kodi

**Comment by CastagnaIT** [comment]
@scamper07
the multiple profiles has not influence
falcorCache is an important data that must exist
if is not present means could two thing
-you have changed page while the script was working (eg selected a profile)
-in your country the webpage is different but it's a rare case

**Comment by scamper07** [comment]
@CastagnaIT 
Thanks for the reply. I'm pretty sure that I did not change the page while the script was running. The main reason I went through the code was because it kept giving me an error when login was successful and the profile selection screen was shown.

Like you said it could be because of the country. 
Thanks for the awesome plugin

**Comment by strickl72** [comment]
@notoco first off I don't like how you caused at me with RTFM. Secondly I came in here for help because unlike you I am not a computer geek and don't know how to do what you  claim is  an easy fix. So that you for the attitude.

**Comment by notoco** [comment]
@strickl72  But you know that this is what WIKI was created for (which you have at the top of this page, just click) so that you do not rewrite the same help over and over again? You got a message that the answer to your problem is in the wiki. Just read. You have all the information and links there. Nobody will rewrite it here because someone doesn't want to read it.

**Comment by strickl72** [comment]
What you are not understanding is 1. I have read it. And just because I read it doesn't mean that I understand it. 

Sent from Yahoo Mail on Android 
 
  On Sun, Sep 27, 2020 at 1:25 PM, notoco<notifications@github.com> wrote:   


@strickl72 But you know that this is what WIKI was created for (which you have at the top of this page, just click) so that you do not rewrite the same help over and over again? You got a message that the answer to your problem is in the wiki. Just read. You have all the information and links there. Nobody will rewrite it here because someone doesn't want to read it.

**Comment by notoco** [comment]
so say what you don't understand, what's your problem. The program is not installing? File not creating? there is nothing to understand, just follow the instructions.
