### ISSUE TITLE
nf authentication key

### ISSUE THREAD

**Issue by mann679** [CastagnaIT/plugin.video.netflix#872]
## Bug report
While installing the NFAuthenticationKey getting error messge
"The chrome browser executable path has not been found.please specify it manually in the settings.json".

I modified the settings.json as under:

{
  "url": "https://www.netflix.com/login",
  "localhostAddress": "localhost",
  "chromeDebugPort": 9222,
  "chromeExePath": "C:\Program Files\Google\Chrome\Application\chrome.exe"
}

But getting error message
"Bad JSON escape sequence: \p.Path 'chromeExePath', line 5, position 24."

Please guide

#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by mann679** [comment]
Figured it out guys.In any case if anybody else facing same issue you have to put extra back-slashes in chrome path name

Like
C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe

Thanks.Enjoy your day cos I am gonna enjoy my day with netflix in Kodi

**Comment by CastagnaIT** [comment]
this is not a bug,
if you have downloaded the last version of NFAuthenticationKey 1.0.2.0
there is a good example in json file on how write the path
