### ISSUE TITLE
NFAuthenticationKey: An error is occurred: unexpected EOF while parsing (<string>, line 0)

### ISSUE THREAD

**Issue by Renetrox** [CastagnaIT/plugin.video.netflix#878]
#### Your Environment
- Netflix add-on version: <1.9.1>
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe your help request
Help please, I can't get the script to work for authentication, the title message appears.
#### Screenshots

https://tgho.st/t6arI

**Comment by CastagnaIT** [comment]
let me know the python version with:
`python --version`

and show me the error details with this:
[NFAuthenticationKey_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5309958/NFAuthenticationKey_t1.zip)

**Comment by Renetrox** [comment]
python --version
Python 2.7.16
reneto@solydxk:~/Vídeos/Autenticación$ python NFAuthenticationKey.py

NFAuthentication Key for linux (Version 1.0.1)

Disclaimer:
This script and source code available on GitHub are provided "as is" without warranty of any kind, either express or implied. Use at your own risk. The use of the software is done at your own discretion and risk with the agreement that you will be solely responsible for any damage resulting from such activities and you are solely responsible for adequate data protection.

Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Traceback (most recent call last):
  File "NFAuthenticationKey.py", line 57, in __init__
    input_msg('Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel', TextFormat.BOLD)
  File "NFAuthenticationKey.py", line 241, in input_msg
    return input(text_format + text + TextFormat.END)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

An error is occurred:
unexpected EOF while parsing (<string>, line 0)

**Comment by CastagnaIT** [comment]
This time have to work:
[NFAuthenticationKey_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5317703/NFAuthenticationKey_t2.zip)

**Comment by Renetrox** [comment]
It opens the browser in private, but if I do not put the address manually it closes, when entering it does not detect that the session started.

Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Browser startup... please wait
Establish connection with the browser... please wait
Unable to connect with the browser
reneto@solydxk:~/Vídeos/Autenticación$ python NFAuthenticationKey.py

NFAuthentication Key for linux (Version 1.0.1)

Disclaimer:
This script and source code available on GitHub are provided "as is" without warranty of any kind, either express or implied. Use at your own risk. The use of the software is done at your own discretion and risk with the agreement that you will be solely responsible for any damage resulting from such activities and you are solely responsible for adequate data protection.

Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Browser startup... please wait
Establish connection with the browser... please wait
Opening login webpage... please wait
Please login in to website now ...waiting for you to finish...
An error is occurred:
Connection is already closed.

**Comment by CastagnaIT** [comment]
you can not write the url manually,
**assure that all Browsers windows are closed before start the script**

if after this not works again, it is possible that your system have the default debug port occuped
open the py file, and change the DEBUG_PORT value with another port number

if after this not works again, i do not know what kind of problem could have your chrome or chronium

**Comment by Renetrox** [comment]
Thanks for the help! I got it, for some reason it didn't work because I had the vivaldi browser installed, apparently it shares some similarity with chrome and chromium
