### ISSUE TITLE
Zip downloads no longer work

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#879]
I discovered that the GitHub ZIP archives no longer seem to work in Kodi. It is missing the mysql-connector as part of the ZIP file.

This will fail to work for the release workflow as well, because those released ZIP files will not have the necessary dependency either.

It is probably wiser to either re-include mysql-connector in this codebase, or add it to the Netflix repository so people can get it from somewhere. (I had a package made for Netflix at: https://github.com/add-ons/script.module.mysql.connector)

_Originally posted by @dagwieers in https://github.com/CastagnaIT/plugin.video.netflix/issues/877#issuecomment-701539618_

**Comment by CastagnaIT** [comment]
the last zip 1.9.1 have the connector included (packages folder), why you say this?

**Comment by CastagnaIT** [comment]
fixed

**Comment by dagwieers** [comment]
Thanks !
