### ISSUE TITLE
Cannot play netflix video on 05/25/2019

### ISSUE THREAD

**Issue by FotixChiang** [CastagnaIT/plugin.video.netflix#88]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
can not play video. Login is ok.
### Addon version used

0.14.3

### Description

After clicking the video that I want to watch, Nothing just happened.

### Steps to Reproduce

1. pure install the plugin and inputstream.adaptive
2. install the Windvine files
3. login in the account
4. click the netflix video

**Expected behavior:** It should be played

**Actual behavior:** nothing happened

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Totally pure installation with reinstalled pure kodi 18.2
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3219412/kodi.log)

## Debug log
https://paste.kodi.tv/fosokegixi.kodi

**Comment by CastagnaIT** [comment]
you have manually installed widewine?

**Comment by CastagnaIT** [comment]
the log is missing debug information, enable kodi debug before use netflix app, then take the log

**Comment by FotixChiang** [comment]
> you have manually installed widevine?

No, just let it installed automaticly by the add-on.

The new log with debug info is here:
https://paste.kodi.tv/imanituvul.kodi

This time when i reopen the kodi to test Netflix, I even cannot get into the Netflix Playlist.

**Comment by CastagnaIT** [comment]
try "Purge in-memory and on-disk cache" in expert setting then reboot kodi,
if it doesn't work yet, there's something corrupt try uninstall kodi with removing all preferences when asked, and make a new installations

**Comment by FotixChiang** [comment]
> try "Purge in-memory and on-disk cache" in expert setting then reboot kodi,
> if it doesn't work yet, there's something corrupt try uninstall kodi with removing all preferences when asked, and make a new installations

That really works and thank you for all the great thing you have even done!
And I find that Netflix Credential problem is about the proxy.
If i use the Global mode, it will work.
The Kodi in-build proxy is useless for that.
