### ISSUE TITLE
Find a way to avoid NFAuthentificationKey Workaround

### ISSUE THREAD

**Issue by flavi1** [CastagnaIT/plugin.video.netflix#881]
Hello.
Since last relative ticket is considered as closed (and is just keep opened for cases of malfunctions...) i open this ticket as a non-urgent feature suggestion. It's not hard to generate a 5 days pass by an external script, but if i don't have to, i will prefer... 

For example, is it possible to simulate web browser and take cookies resulted in the Kodi plugin itself ?
This can maybe help : 
https://stackoverflow.com/questions/2567738/browser-simulation-python
http://wwwsearch.sourceforge.net/mechanize/

Maybe possibility to silently fill NF authentication page : https://mechanize.readthedocs.io/en/latest/forms_api.html

(not sure, just in case)

**Comment by CastagnaIT** [comment]
Mechanize do not support javascript:
https://mechanize.readthedocs.io/en/latest/faq.html#is-javascript-supported

you are free to try if you want,
but it is difficult that it works because the Form fields are partially handled by javascript
and is needed also handle request/response of google rechaptcha to have the required token to send with the login data

**Comment by flavi1** [comment]
I will not try because of my so little knowledge in Python...
But if someone wants to do it a day : 

PhantomJS (a nodeJS library) support javascript. And can be used in Python : 
https://stackoverflow.com/questions/13287490/is-there-a-way-to-use-phantomjs-in-python
It may probably will be hard efforts for this very little feature...

For Recaptcha, there is another project (maybe more than one) that implement Recaptcha in Kodi. It's vStream.
You can reslove google captchas in Kodi itself by selecting pictures by your remote control... (impossible to find an example video)
I don't know how it's done. Perhaps they already use phantomJS or other thing...

Closed ticket until someone else reopen if needed.
Thanks.

**Comment by flavi1** [comment]
Closed ticket until someone else reopen if needed.

**Comment by CastagnaIT** [comment]
unfortunately your proposes are not too much useful

if you add external dependencies must be taken in account that the addon is multiplatform,
NodeJS need a separate installation to work and can not be used here

NF website do not use image chaptchas
use the last antibot google recaptcha (v3) FWIK need a dedicated server to elaborate the token's
