### ISSUE TITLE
1.9.1 cant be opened on Kodi 18 OSMC

### ISSUE THREAD

**Issue by Quandm1195** [CastagnaIT/plugin.video.netflix#882]
#### Your Environment
- Netflix add-on version: 1.9.1
- Operating system version/name: OSMC - Kodi 18 Leia
- Device model:  Raspberry pie 3 B plus
 
Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
The app updated to 1.9.1 and something failed to start. Log: https://paste.osmc.tv/poxoruramo

#### Expected behavior
App starts normally 

#### Actual behavior
Failed to start, no background service started

#### Steps to reproduce the behavior

1. Open the app
2.
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

It was working fine on 1.5.0, I tried to find the zip file but couldnt find it anywhere anymore

**Comment by CastagnaIT** [comment]
missing a table to the database
reinstall the addon from scratch
