### ISSUE TITLE
Help request - possibly problem report or issue?

### ISSUE THREAD

**Issue by strangeintp** [CastagnaIT/plugin.video.netflix#886]
#### Your Environment
- Netflix add-on version: current as of submission
- Operating system version/name: LibreELEC
- Device model:  x86-64

Used Operating system:
* [ ] Android
* [ ] iOS
* Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request
Not sure if the new authentication file instructions work for Kodi on LibreELEC...  it seems I can't install the python installers?

Results:
```terminal
LibreELEC:~ # pip install pycryptodomes
-sh: pip: not found
LibreELEC:~ # sudo apt install build-essential python-dev python-pip python-setu
ptools

 There is no working 'sudo'.
 
 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy
 
 With LibreELEC you have root access by default, so you dont need 'sudo'

LibreELEC:~ # apt install build-essential python-dev python-pip python-setuptools
-sh: apt: not found
```

I am new to Kodi (and LibreELEC)... was just giving it a test drive and Netflix was the first thing I wanted to install, sort of a Litmus test.

So I don't know if there's a whole bunch more hoops I have to jump through just to get this working (I probably won't)?  A short bit of research indicates that you're not supposed to be able to do pip installs etc. on LibreELEC.
Or do I need to copy file from my ssh client (Linux Mint) into the appropriate LibreELEC location via the SSH?  If so, how do I do that?  And if that's the solution, please consider updating your authentication file instructions.

**Comment by jakermx** [comment]
LibreELEC has the OS limited, to do the Authentication key reteivial, you need to do it in another Computer.

**Comment by strangeintp** [comment]
ok, then what?  email it to myself and then download it inside Chrome?  or I guess I have to do something like SFTP within the SSH?  convoluted, becoming too much effort...  Litmus test failing.

**Comment by jakermx** [comment]
I use kodi web page to set email and pass ,accesing Netfkix add on from it

**Comment by CastagnaIT** [comment]
have you read the Wiki instructions?
seem clear to me about the process, no need heavy knownledge

**Comment by strangeintp** [comment]
Yes, those instructions are what I was referring to.  So let me try to spell out more.  Following, I've pasted the instructions from the wiki and commented:

> INSTRUCTIONS: Download the zip, extract the folder and open this folder with the Terminal/Console. Then run the following commands.
> Install these python packages:
> 
> pip install pycryptodomex
> pip install websocket-client

None of these instructions work on LibreELEC, as I pointed out in my original post.

> 
> After run the script:
> 
> python NFAuthenticationKey.py
> or
> python3 NFAuthenticationKey.py

Possibly these instructions work without the `pip install` anyways on LibreELEC?  Are those python packages already part of the LibreELEC distro?  I don't know, I didn't get that far and didn't think to try it at the time, was already getting frustrated failing the first step.  But if so, then the first pip install steps can be stepped on LibreELEC.

I successfully followed the instructions up to this point on another Linux machine (that I'm not running Kodi on).

> Follow the instructions on screen, after you have created the file, 

I did this on the other Linux machine and generated "NFAuthentication.key"

> you have to open it with Netflix add-on by choosing the login with "Authentication key".

Obviously I can't do this step without another one in between because the key file was generated on a separate machine... probably the easiest thing to do would be to email it to myself and then download it on the LibreELEC machine.  But at this point it's kind of academic as far as I'm concerned because I've already given up trying to get a HTPC as a convergent platform using Kodi/LibreELEC because my short experience with trying to get Netflix and Amazon as streaming services required more time and energy than I'm willing to expend.  So you can take or leave my comments as feedback on your instructions, I'm kind of done with this experiment now.

**Comment by CastagnaIT** [comment]
you forgot to read a step:

> You can create this file from any computer

it is not intended to do on LibreELEC but on a _Computer_ machine
LibreELEC is not a standard linux distribution

the only thing that you have after generated the file is copy it to a usb key and connect it to the libreELEC to login NF the first time

**Comment by strangeintp** [comment]
ok, I still think that could be made more clear, maybe put that at the end of the instructions, instead of leaving it at the beginning (and somewhat ambiguous).  Up to you, that's just my opinion so you can take it or leave it.

**Comment by notoco** [comment]
If it is placed at the end, no one will read it. All important information, in any manual, is always first.
