### ISSUE TITLE
Cannot play Netflix Testpatterns

### ISSUE THREAD

**Issue by padok** [CastagnaIT/plugin.video.netflix#89]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

14.2

### Description

I'm tring to use the test patterns that netlix offers, but its getting stuck at loading.
https://www.netflix.com/title/80018499

### Steps to Reproduce

1. Add Test Patterns to My List
2. Select Test Patterns to play on Kodi
3. Stuck on loading

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

I'm using LibreElec on RPI3, but it's similar on my Arch Linux machine.

## Debug log

https://paste.kodi.tv/uvuxatixir.kodi

Sry its a mess

**Comment by CastagnaIT** [comment]
try disable vp9 profile in expert settings

**Comment by padok** [comment]
With vp9 profile disabled, the permanent loading indicator disappears. However, the test patterns are still not played.

**Comment by Smeulf** [comment]
@padok please check and correct your settings against these recommendations : https://github.com/CastagnaIT/plugin.video.netflix/issues/70#issuecomment-488350108

If it's still not working, please post logs again so we can get an another look.

**Comment by Smeulf** [comment]
And btw, here on my Raspberry it works.

Cheers.

**Comment by CastagnaIT** [comment]
if within 2 days there are no other feedbacks i close

**Comment by padok** [comment]
Sorry, I can't access my raspberry at the moment because I'm not at home. But I've got it running on my PC. Thanks for the help.

**Comment by jakermx** [comment]
try disabling OMX Player

**Comment by jakermx** [comment]
In order to play it, you should set you InoutStream Adaptive as suggested
Max to 720
Secure to 720 or lower
And set the Stream Selection to Manual and check the ignore Resolution option.
Also, disable the HD codecs i.e. DV, HEVC, etc... Raspberry won´t reproduce them....remember, netflix video is software based encrypted so, RPi has limited resources. it wont play nothing above 720... well it will, but with errors or will crash.

**Comment by jakermx** [comment]
I can confirm that using the default values for InputStream Adaptive and disabling VP, HEVC and 4K codecs, it works on RPi2 and RPi3, but I will suggest set the max and secure resolution to 720p in order to get better video experience.
