### ISSUE TITLE
Widevine update should tell me if I have enough space

### ISSUE THREAD

**Issue by strugee** [CastagnaIT/plugin.video.netflix#892]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request

When a Widevine update is available, the plugin prompts me to download the update and tells me how much space is required. Instead of telling me how much space is required, it should say "this update will temporarily use xyz MB of free space on your device, which you have available."

#### Describe the use case

This eliminates a case where the user is supposed to SSH into Kodi and use the terminal, making it both more user friendly and more convenient.

#### Describe an alternative

* Leave things as are; the UX is already pretty decent
* Don't mention space at all unless there's not enough since it's only temporary (so who cares how much space is used in the couple minutes while the update is performed) - instead just say, "Would you like to download this update?"
* Say, "The update will temporarily use xyz MB of disk space. You currently have abc MB of space available."
* Probably some other phrasings too; let us bikeshed

**Comment by CastagnaIT** [comment]
the widevine library is not managed from this addon
you have to report to InputStreamHelper
