### ISSUE TITLE
ConnectionError while loggin in

### ISSUE THREAD

**Issue by Pieha** [CastagnaIT/plugin.video.netflix#896]
I installed the netflix addon following the procedure found on Kodi forum post 4 on OSMC (Kodi version 18). I am based in cambodia. When i try to log in, i got the following:
Exception: Connection error
Error details:
HTTPSConnectionPool(host='www.netflix.com',port=443):Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x6038b450>: Failed to establish a new connection: [Errno-2] Name or service Not known',))

Is it an issue ? How can it be fixed ?

**Comment by Pieha** [comment]
![Uploading 16030125522483815723718850490943.jpg…]()

**Comment by Pieha** [comment]
Please find attached the log
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5397286/kodi.log)

**Comment by HanatielHawk** [comment]
I have the same issue.

**Comment by npmstart-pray** [comment]
Same issue here. 443 errors where there weren’t any before...but port 443 is https, which suggests a networking problem, yet every other device on my network can play Netflix. (Current xbian on RPi4).

**Comment by CastagnaIT** [comment]
> Happens when I try to login with both email/password and authentication key

the error mentioned is a network error
could be you have a broken/unstable DNS address in your network
or something similar that prevent a good communication
i can not do nothing here

**Comment by npmstart-pray** [comment]
No, it is an addon problem:  I can update other add ons from within kodi AND I can watch Netflix on other devices on my network. DNS isn’t the issue. I suspect it’s crypto-related. Will test and update. Which version of pycryptodomex do you test with?

**Comment by CastagnaIT** [comment]
cryptodome? in what sense?
/login endpoint mentioned before do not use crypto it is a simple http request

anyway if you want to test something:
On windows/android: crypto package is embedded on kodi
On linux there are three different crypto packages that can be used:
PyCrypto
PyCryptodome
PyCryptodomex

when more packages are installed by default the addon give priority to PyCryptodomex

**Comment by npmstart-pray** [comment]
In my head, Netflix would want a secure https connection on 443, with some sort of key exchange between host (them) and client (us). A failure or issue there would result in a closed connection, wouldn’t it? And that response returned as the error. 

I’m probably wrong, off somewhere in my logic, but it would be good to know where and why.

**Comment by CastagnaIT** [comment]
https by default use only the port 443 and is good

> with some sort of key exchange between host (them) and client (us)

if it is what i think, this is the standard behaviour of the https protocol, but this is managed automatically by Request package otherwise you do not estabilish the communication

if you discover something let us know

**Comment by Pieha** [comment]
I that can helps, i tried to connect netflix from raspi OS desktop Chromiun browser and it worked.

I had exactly the same hardware and network configuration as the one i used to try netflix.

**Comment by wagnerch** [comment]
This error could be SELinux-related.  In essence it is either DNS (i.e. not working properly), security policy (SELinux), firewall/network connectivity, or perhaps a broken IPv6 network (i.e. not routable).

DNS you can rule out by running "host www.netflix.com" via the OSMC SSH login.  For SELinux, perhaps run "journalctl" via the OSMC SSH login and see if there are any messages around the same time.

I have had zero issues with the Netflix plugin on OSMC Vero4K+ (initially running the Stretch build, now using Buster build w/ 4.9 kernel).

**Comment by Pieha** [comment]
Ok, problem fixed, and not related to the plugin itself. I had a DNS issue on my network.

I fixed the problem by doing:
My OSMC > Network > Connection > Configure manually > change primary dns IP address to 8.8.8.8.

For user-friendliness, this quick fixe could be suggested tu users when this error show up.

**Comment by CastagnaIT** [comment]
thanks i will add in the wiki

**Comment by Kalyan-M** [comment]
I'm getting the same error for /browse call on Windows.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6171431/kodi.log)

**Comment by kudschi753** [comment]
> I'm getting the same error for /browse call on Windows.
> [kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/6171431/kodi.log)

Me too. Check DNS configuration, no problems.
Maybe someone got a clue.
