### ISSUE TITLE
Video Stream only at 540? mi box 3 und mi box 3s

### ISSUE THREAD

**Issue by lesjouers** [CastagnaIT/plugin.video.netflix#899]
#### Your Environment
- Netflix add-on version: <1.10.1>
- Operating system version/name: < Andoid 9 -->
- Device model:  <Mi Box 3 and Mix box 3S>

Used Operating system:
* [x ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request
<I've tried to set 1080 in the plugin setting but still it is only playing at 540p. 
since I upgraded to andoid 9>

#### Screenshots

![20201019_195013_resized](https://user-images.githubusercontent.com/73129945/96493311-1cca5e80-1245-11eb-8e56-0e13f69e63b5.jpg)
![20201019_195206_resized](https://user-images.githubusercontent.com/73129945/96493320-20f67c00-1245-11eb-951d-347e235f5090.jpg)
![20201019_195107_resized](https://user-images.githubusercontent.com/73129945/96493333-248a0300-1245-11eb-9654-b6b94817ac6f.jpg)

**Comment by CastagnaIT** [comment]
First thing to do, reset ESN from expert setting, and attach here a debug LOG as instruction say or will close the issue

After install netflix official app from playstore go to the settings:
-get a screenshot of ESN
-check Playback specification page, if supported quality is HD or SD

**Comment by lesjouers** [comment]
i reset ESN, it doesn't work.[
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5432947/kodi.log)
](url)

**Comment by lesjouers** [comment]
[](url)
![20201024_152843_resized](https://user-images.githubusercontent.com/73129945/97083151-93cd7180-160e-11eb-8ae4-f35b75d31a00.jpg)

**Comment by CastagnaIT** [comment]
I need these 3 things:

1) A good log, you have posted a bad log, follow the full steps instructions in the Readme, then redo reset ESN.

2) What say Netflix original app in Playback specification page?

3) Give me the device configuration, this steps:
-Install "Material Terminal" app or similar
-Open the app, in the black screen write "props" then OK a long list appears
-Open options, then select "Send to e-mail", send to my github email

**Comment by CastagnaIT** [comment]
Closed due to inactivity
