### ISSUE TITLE
Feature request: enable dolby Atmos choice in the settings menu

### ISSUE THREAD

**Issue by ccamo** [CastagnaIT/plugin.video.netflix#9]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

### Addon version used
20
[eg. 13.21.0]

### Description
missing Atmos option
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
In the settings option have the choice to enable or disable Atmos sound
**Actual behavior:** [What actually happened]
There isn't any option and in the settings.XML Atmos is disabled
### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/) or [https://pastebin.com/](https://pastebin.com/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment]
the dolby atmos is enabled by default
if in expert settings you have set "Use Dolby Sound" to Enabled

some other users have complained that they do not receive the atmos tracks,
I don't know if something netflix has changed,
i need the file "manifest.json" and the log could help me

before get the files:
-open kodi activate debug
-close kodi
-reopen kodi (clear the log)
-open netflix and play the atmos movie
-stop and exit kodi

after you can find "manifest.json" in:
C:\Users\USERNAME\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix
or similar folder of kodi in your device

also attaches the log present in AppData\Roaming\Kodi\

**Comment by CastagnaIT** [comment]
on kodi settings,
I hope you've already set to audio:
allow passtrought with device WASAPI and Enabled the HD audio compatibility

**Comment by ccamo** [comment]
Ciao Stefano!

 

Visto che siamo entrambi italiani, anzi, siamo ad un tiro di schioppo l’uno dall’altro (io sono di Bassano del Grappa), direi di passare all’italiano per semplificarci la vita.

Il tuo meraviglioso addon per Kodi lo uso su Nvidia Shield e dunque purtroppo sono molto limitato nell’uso di un gestore file.

Ho seguito le tue istruzioni per attivare il LOG:

 

-open kodi activate debug
-close kodi
-reopen kodi (clear the log)
-open netflix and play the atmos movie
-stop and exit kodi

 

Ma in Android non ho il percorso da te indicato e non trovo nulla cercando per manifest.json.

COME POTREI AIUTARTI?

 

 

Per quanto riguarda:

on kodi settings,
I hope you've already set to audio:
allow passtrought with device WASAPI and Enabled the HD audio compatibility

 

ecco I miei settaggi:



 

Non so dove sia il settaggio “with device WASAPI”; come vedi ho solo il dispositivo d’uscita per il passtrough android,audiotrack e l’opzione è disabilitata.

 

Grazie ancora per il tuo lavoro di implementazione ed aggiornamento!

 

 

Da: Stefano Gottardo <notifications@github.com> 
Inviato: domenica 17 febbraio 2019 12:32
A: CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc: ccamo <carlo.camonico@virgilio.it>; Author <author@noreply.github.com>
Oggetto: Re: [CastagnaIT/plugin.video.netflix] Feature request: enable dolby Atmos choice in the settings menu (#9)

 

the dolby atmos is enabled by default
if in expert settings you have set "Use Dolby Sound" to Enabled

some other users have complained that they do not receive the atmos tracks,
I don't know if something netflix has changed,
i need the file "manifest.json" and the log could help me

before get the files:
-open kodi activate debug
-close kodi
-reopen kodi (clear the log)
-open netflix and play the atmos movie
-stop and exit kodi

after you can find "manifest.json" in:
C:\Users\USERNAME\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix
or similar folder of kodi in your device

also attaches the log present in AppData\Roaming\Kodi\

**Comment by CastagnaIT** [comment]
ciao mi fa piacere! ma l'addon non è tecnicamente mio :) sto solo facendo manutenzione perchè molti parlano ma nessuno se ne occupa...
forse potresti aiutarmi meglio a capire una cosa su questo Nvidia shield

ho letto in rete che per permettere sempre a kodi di usare l'output per l'audio alta qualità (atmos ecc..) è necessario (prima di eseguire kodi) cambiare la seguente impostazione:
Shield setting -> Display & Sound -> Advanced settings -> Surround Sound -> Set to Always

e solo dopo avviare kodi e attivare dalle impostazioni il passtrugh abilitando le apposite compatibilita ai formati audio alta qualità

tu avevi già impostato Surround Sound a Set to Always?

**Comment by ccamo** [comment]
Ho due Nvidia Shield collocate su due TV indipendenti tra loro.

Nei settaggi dello Shield c’è effettivamente il settaggio:

 

Shield setting -> Display & Sound -> Advanced settings -> Surround Sound ->  dove c’è la possibilità di scegliere tra “Automatico”, “Sempre” e “mai”.

 

Da un po’ di tempo ho su  entrambe impostato la scelta su “Sempre”.

 

La cosa buffa è che prima avevo entrambe impostate su “Automatico”: un sistema aveva il dolby 5.1 con Kodi, mentre l’altro no.

Impostando entrambi su “Sempre” ho risolto il problema.

 

La schermata che ti ho spedito prima è il risultato del setup Nvidia: Shield setting -> Display & Sound -> Advanced settings -> Surround Sound -> Set to Always

 

Su Kodi, nelle impostazioni audio ho provato anche a mettere 7.1 al posto di 5.1…..

Ma come puoi vedere, il dispositivo di uscita audio non è selezionabile.

 



 

Da: Stefano Gottardo <notifications@github.com> 
Inviato: domenica 17 febbraio 2019 13:31
A: CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc: ccamo <carlo.camonico@virgilio.it>; Author <author@noreply.github.com>
Oggetto: Re: [CastagnaIT/plugin.video.netflix] Feature request: enable dolby Atmos choice in the settings menu (#9)

 

ciao mi fa piacere! ma l'addon non è tecnicamente mio :) sto solo facendo manutenzione perchè molti parlano ma nessuno se ne occupa...
forse potresti aiutarmi meglio a capire una cosa su questo Nvidia shield

ho letto in rete che per permettere sempre a kodi di usare l'output per l'audio alta qualità (atmos ecc..) è necessario (prima di eseguire kodi) cambiare la seguente impostazione:
Shield setting -> Display & Sound -> Advanced settings -> Surround Sound -> Set to Always

e solo dopo avviare kodi e attivare dalle impostazioni il passtrugh abilitando le apposite compatibilita ai formati audio alta qualità

tu avevi già impostato Surround Sound a Set to Always?

**Comment by CastagnaIT** [comment]
mancano le foto... devi allegarle rispondendo attraverso il sito di github

**Comment by ccamo** [comment]
![dsc_0482](https://user-images.githubusercontent.com/47712881/52913586-b0ed6100-32bf-11e9-84ee-83b8f57f2b66.JPG)
![dsc_0483](https://user-images.githubusercontent.com/47712881/52913589-b34fbb00-32bf-11e9-9297-49293c517952.JPG)

Ecco le due foto del setup audio di Kodi.
Ho provato a mettere 5.1 e 7.1 nel numero di canali.

**Comment by CastagnaIT** [comment]
mi puoi dire alcuni titoli con audio atmos?

**Comment by ccamo** [comment]
Velvet Buzzsaw di sicuro:
![img-20190209-wa0002](https://user-images.githubusercontent.com/47712881/52915308-94a6ef80-32d2-11e9-922d-6f4a6053b4fc.jpg)

e anche:
Outlaw king

**Comment by ccamo** [comment]
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/2877508/kodi.log)

Sono riuscito a trovare la directory dove salva il LOG in android. 
LOG in allegato.
Grazie ancora per il tuo lavoro e la tua pazienza! :-)

**Comment by CastagnaIT** [comment]
ma sopra hai scritto che hai risolto,
hai postato il log perchè non hai ancora risolto il problema o per cosa?

**Comment by ccamo** [comment]
Ho postato il log se poteva aiutarti a capire qualcosa.
Penso che ci sia un po' di confusione rispetto alla codifica Atmos.
Tra le tracce audio selezionabili c'è quella in lingua (italiana o inglese) con la dicitura "DD 5.1"
Non credo che ci sia una traccia audio nominata come "Atmos" ma quella nominata come "DD 5.1" sia quella codificata in Dolby digital e contenga anche la codifica atmos.
Ora selezionando la codifica DD 5.1 si azionano anche i diffusori supplementari dedicati alla codifica Atmos.
Le label nell'anteprima riportano come risoluzione video HD1080 anche se posso scegliere la risoluzione 3840X2160 (4K) e non riportano la sigla HDR.
Le label nell'anteprima riportano come codifica audio 5.1.
Se posso esserti utile con prove o log, sono a disposizione.
Grazie.

**Comment by CastagnaIT** [comment]
allora non avendo un sistema atmos, ho basato i miei test sulle risposte da netflix, quindi mi hai confermato quello che avevo capito inizialmente.
-si le tracce audio sono descritte tutte come DD 5.1 che siano atmos oppure DolbyD normale proverò a informarmi se si può in qualche modo impostare delle descrizioni diverse, non è una cosa immediata dipende da inputstream e/o kodi stesso
-puoi darmi un titolo la cui la risoluzione del flag è HD1080 invece di 4K?

**Comment by ccamo** [comment]
![velvet](https://user-images.githubusercontent.com/47712881/53047884-b4394600-3493-11e9-8e60-2dcb728ab311.JPG)

Ecco qua, Velvet Buzzsaw, posso vederlo in 4K selezionando 3842X2160 ma l'etichetta riporta !1080 HD".

**Comment by CastagnaIT** [comment]
ciao @ccamo avrei una semplice richiesta se puoi farla quando hai tempo,
su Nvidia Shield utilizzando l'app android originale netflix, puoi andare sul menu "impotazioni app" e postarmi lo screenshot dell'ESN che ti appare? grazie

**Comment by ccamo** [comment]
![DSC_0328](https://user-images.githubusercontent.com/47712881/55282710-65ac8080-534a-11e9-8c85-8de2554604ee.JPG)

Ecco l'ESN. Ti prego però di non condividerlo, visto che è unico non vorrei essere bannato in qualche modo se venisse condiviso...

**Comment by ccamo** [comment]
Dimmi poi quando posso cancellare il commento sopra, grazie.

**Comment by CastagnaIT** [comment]
fatto l'ho cancellato io, grazie

**Comment by CastagnaIT** [comment]
mi serve solo per capire com'è composto niente altro

**Comment by ccamo** [comment]
Grazie! 
Grazie per lo sviluppo che porti a questa app!
Se posso esserti utile... non hai che da chiedere!
Buona domenica!

**Comment by CastagnaIT** [comment]
Ciao @ccamo quando hai tempo potresti provare questa versione dell'addon?
ho fatto una modifica per provare a risolvere i flag 4k segnati come 1080P
grazie e buona pasqua

[plugin.video.netflix_TestInfo4k.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3101424/plugin.video.netflix_TestInfo4k.zip)

**Comment by ccamo** [comment]
Buona Pasqua anche a te!
Provato! Ecco i risultati:
![DSC_0353](https://user-images.githubusercontent.com/47712881/56474648-ec053f80-647c-11e9-8ce1-b2c81a99b0c8.JPG)

purtroppo vedo ancora il tag dei 1080i.
Vedo in 4K ma sono scomparse le tracce della lingua italiana!

![DSC_0350](https://user-images.githubusercontent.com/47712881/56474670-2a026380-647d-11e9-88c3-d9b1cf72f336.JPG)

![DSC_0351](https://user-images.githubusercontent.com/47712881/56474673-31c20800-647d-11e9-9e11-ac59e424d383.JPG)

![DSC_0352](https://user-images.githubusercontent.com/47712881/56474676-35ee2580-647d-11e9-83e5-968a7c8ff82b.JPG)

ecco i settaggi impostati:

![DSC_0354](https://user-images.githubusercontent.com/47712881/56474691-66ce5a80-647d-11e9-9b23-01de899a32e5.JPG)

![DSC_0355](https://user-images.githubusercontent.com/47712881/56474692-70f05900-647d-11e9-8dd7-f35e52ffba0c.JPG)

**Comment by ccamo** [comment]
A disposizione se ti serve qualcosa!

**Comment by CastagnaIT** [comment]
...caspita non mi aspettavo tante complicazioni,
credo all'incirca di aver capito il problema, il nostro addon sfrutta widevine di chrome e netflix ha limitato i contenuti web su chrome ciò influenza anche i flag che vedi sbagliati, ma a quanto pare ci sono altre complicanze di mezzo che al momento non comprendo, prima su tutte non mi spiego perchè su sistema windows i flag vengono fuori correttamente e su linux/android no...

ti preparerò due zip test, nella speranza che uno dei due workaround funzioni
ma prima ho bisogno che mi mandi lo screen o fai copia incolla dell'user-agent  string che vedi su questa pagina:
Mi raccomando di aprirla da Shield solo con Google Chrome, perchè si basa sul browser:

www.whatsmyua.info

**Comment by ccamo** [comment]
AHI! Nvidia Shield non ha Chrome, neppure tra le app ufficiali.
Potrei scaricarla seguendo questo workaround: 
https://streamertips.com/how-to-install-chrome-on-the-nvidia-shield/
Potrebbe andar bene per i tuoi scopi?

**Comment by ccamo** [comment]
Ho installato Chrome; ecco gli screenshot:
![DSC_0351](https://user-images.githubusercontent.com/47712881/56498166-e2bdb680-6500-11e9-8bf4-3c90909e92cb.JPG)

![DSC_0352](https://user-images.githubusercontent.com/47712881/56498183-ebae8800-6500-11e9-8b8e-03c9bab3f0ae.JPG)

![DSC_0353](https://user-images.githubusercontent.com/47712881/56498193-f23cff80-6500-11e9-8e2a-d6b0b994a5d6.JPG)

![DSC_0354](https://user-images.githubusercontent.com/47712881/56498203-f8cb7700-6500-11e9-8ff2-fc873934fe1e.JPG)

![DSC_0355](https://user-images.githubusercontent.com/47712881/56498212-ff59ee80-6500-11e9-8f17-b5d3476494c5.JPG)

**Comment by ccamo** [comment]
Se posso ricordarti anche l'italiano scomparso tra le tracce audio selezionabili....
Ciao!

**Comment by CastagnaIT** [comment]
Non sapevo che Chrome non fosse supportato, gia da qui ho paura che la situazione non migliora...
Qui ti ho messo i due test, non sono necessari altri screenshot basta che mi scrivi come si comportano:

[plugin.video.netflix_UAShield.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3103199/plugin.video.netflix_UAShield.zip)

[plugin.video.netflix_UAWIN10.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3103200/plugin.video.netflix_UAWIN10.zip)

**Comment by ccamo** [comment]
Provati entrambi; stesso comportamento con tutti e due: streaming a 4K effettivo ma tag sempre 1080HD.
Linguaggi sempre spanish-french-english deutsch, ma no italiano.

**Comment by CastagnaIT** [comment]
allora resterà cosi in attesa di cambiamenti da parte di netflix, altro qui non si può fare, grazie per aver eseguito le prove

**Comment by ccamo** [comment]
:-( 
Figurati! Grazie a te per il tuo lavoro! 
Sempre a tua disposizione per eventuali altri test!
Ciao!

**Comment by CastagnaIT** [comment]
per caso sei disponibile a fare un nuovo tentativo per il problema delle etichette 1080P/4K sbagliate?

**Comment by ccamo** [comment]
Certo! A disposizione!

Sono passato a Nvidia Shield pro ora.

Mi mandi un file o scarico quello in GitHub?

 

Da: Stefano Gottardo <notifications@github.com> 
Inviato: giovedì 23 gennaio 2020 13:11
A: CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc: ccamo <carlo.camonico@virgilio.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [CastagnaIT/plugin.video.netflix] Feature request: enable dolby Atmos choice in the settings menu (#9)

 

per caso sei disponibile a fare un nuovo tentativo per il problema delle etichette 1080P/4K sbagliate?

**Comment by CastagnaIT** [comment]
grazie, trovi tutto con gli step da seguire sul post intitolato:
"Help request to NVIDIA SHIELD Users - wrong media flag 1080P / 4K"

**Comment by ccamo** [comment]
Ciao Stefano, installato il plugin.

Errore di password non riconosciuta, ma mi permette di entrare comunque nell’account.

Ecco le due foto dello schermo:

 

Netflix su NVIDIA shield:



 

Netflix su plugin di KODI:



 

Al “PLAY” però esce un altro errore e non parte la riproduzione del video.

 

 

Da: Stefano Gottardo <notifications@github.com> 
Inviato: giovedì 23 gennaio 2020 19:45
A: CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc: ccamo <carlo.camonico@virgilio.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [CastagnaIT/plugin.video.netflix] Feature request: enable dolby Atmos choice in the settings menu (#9)

 

grazie, trovi tutto con gli step da seguire sul post intitolato:
"Help request to NVIDIA SHIELD Users - wrong media flag 1080P / 4K"

**Comment by CastagnaIT** [comment]
non dovrebbe accadere tutti questi problemi,
ma hai mai aggiornato l'addon con le ultime versioni?

Le immagini non si vedono comunque un log sarebbe stato meglio
se lo fai assicurati che Kodi debug sia attivo e che nelle impostazioni di nf addon in expert settings il livello di log sia Verbose

**Comment by ccamo** [comment]
Addon aggiornato con il download di quello che ho trovato al punto 3 del “Help request to NVIDIA SHIELD Users…”


Nonostante gli errori comunque  il “flag” mostrato è quello corretto, cioè 4K.


Ho attivato il debug di Kodi e nelle impostazioni dell’addon il livello è “verbose”.


Purtroppo con file commander andando sulla cartella che dovrebbe contenere il log non mostra nulla.


Hai qualche app da consigliarmi per fare il browsing dei file su android?


Lo Shield non è proprio “amichevole” sotto questo punto di vista; anche perché tentare di navigare con il telecomando non è il massimo…


 


 

Da: Stefano Gottardo <notifications@github.com> 
Inviato: venerdì 24 gennaio 2020 09:09
A: CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc: ccamo <carlo.camonico@virgilio.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [CastagnaIT/plugin.video.netflix] Feature request: enable dolby Atmos choice in the settings menu (#9)

 

non dovrebbe accadere tutti questi problemi,
ma hai mai aggiornato l'addon con le ultime versioni?

Le immagini non si vedono comunque un log sarebbe stato meglio
se lo fai assicurati che Kodi debug sia attivo e che nelle impostazioni di nf addon in expert settings il livello di log sia Verbose

**Comment by ccamo** [comment]
Aggiornamento:

Numero ESN presente nell’addon era errato.

Inserito manualmente il nuovo numero ESN e non sono più comparsi gli errori che mi impedivano la visione dei video.

Ora il video parte e dopo aver scelto la risoluzione in “manuale” e messa in 4K una volta partito il film, il video è in 4K.

Il problema è che l’italiano non compare nelle lingue dell’audio!

Fatto test con film OKJA.

 

Da: Carlo Camonico <carlo.camonico@virgilio.it> 
Inviato: sabato 25 gennaio 2020 17:20
A: 'CastagnaIT/plugin.video.netflix' <reply@reply.github.com>
Oggetto: R: [CastagnaIT/plugin.video.netflix] Feature request: enable dolby Atmos choice in the settings menu (#9)

 


Addon aggiornato con il download di quello che ho trovato al punto 3 del “Help request to NVIDIA SHIELD Users…”


Nonostante gli errori comunque  il “flag” mostrato è quello corretto, cioè 4K.


Ho attivato il debug di Kodi e nelle impostazioni dell’addon il livello è “verbose”.


Purtroppo con file commander andando sulla cartella che dovrebbe contenere il log non mostra nulla.


Hai qualche app da consigliarmi per fare il browsing dei file su android?


Lo Shield non è proprio “amichevole” sotto questo punto di vista; anche perché tentare di navigare con il telecomando non è il massimo…


 


 

Da: Stefano Gottardo <notifications@github.com> 
Inviato: venerdì 24 gennaio 2020 09:09
A: CastagnaIT/plugin.video.netflix <plugin.video.netflix@noreply.github.com>
Cc: ccamo <carlo.camonico@virgilio.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [CastagnaIT/plugin.video.netflix] Feature request: enable dolby Atmos choice in the settings menu (#9)

 

non dovrebbe accadere tutti questi problemi,
ma hai mai aggiornato l'addon con le ultime versioni?

Le immagini non si vedono comunque un log sarebbe stato meglio
se lo fai assicurati che Kodi debug sia attivo e che nelle impostazioni di nf addon in expert settings il livello di log sia Verbose

**Comment by CastagnaIT** [comment]
> Nonostante gli errori comunque  il “flag” mostrato è quello corretto, cioè 4K.

per me l'importante è che riesci a fare una comparazione con i flag mostrati con la versione dell'addon attuale e quella modificata, quindi magari segnati due film/serie con il flag errato
e li compari con la versione modificata, altrimenti non capisco se effettivamente funziona
**ricordati quando cambi versione dell'addon di eliminare la Cache "in memoria e su disco" altrimenti restano memorizzati i dati precedenti**

Io utilizzo Solid Explorer non so se è compatibile, ma se hai sistemato non importa

se non vuoi avere problemi con gli stream mancanti le impostazioni corrette per InputStream Adaptive sono:
Override HDCP status su ON
Stream selection su AUTO
E solo nel caso hai impostato la GUI di Kodi con una risoluzione inferiore a 4K allora è necessario impostare anche Ignore Display Resolution ON, altrimenti lascia OFF

**Comment by CastagnaIT** [comment]
Un utente ha segnalato che il flag 4K sul film Bird box ora si visualizza correttamente
potresti fare una controprova per confermare?
ossia vorrei sapere quale flag visualizzi nella versione modificata e quale su quella regolare dell'addon

**Comment by CastagnaIT** [comment]
credo di aver capito l'errore che hai avuto
[plugin.video.netflix_0.16.3_20200126_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4113608/plugin.video.netflix_0.16.3_20200126_test1.zip)
utilizzando questa versione dovresti poter fare la comparazione tra release regolare e questa modificata senza errori strani
