### ISSUE TITLE
Unable to playback with Netflix 14.3 Kodi 18.2

### ISSUE THREAD

**Issue by ryangodammit** [CastagnaIT/plugin.video.netflix#90]
*I'm submitting a ...*
  - [x] support request

## General information

Browsing netflix fine, but playback causing error

### Addon version used

Netflix 0.14.3

### Description

Logging into and browsinfg netflix is fine but playback creates a "Playback Error" message- "This title is not available to watch immediately..."

### Steps to Reproduce

1. Updated to Libreelec 9.0.0 (Kodi 18.2) via .tar file in libreelec's update folder
2. Removed older versions of netflix 
3. Installed CastagnaIT repo, then installed Netflix

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Context (Environment)
Libreelec 9.0.2 on a asus chrombox
### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Libreelec 9.0.2 on a asus chrombox

## Debug log

http://ix.io/1KbP

## Other information

I think that's everything.
Potentially a hangover from an earlier netflix I had on here?
I had been using 13.22 fine and then netflix playback stopped working (no error message), which is when I updated to kodi 18.2 and found netflix 14.3

**Comment by Smeulf** [comment]
Netflix says this message is most likely related to a wrong cache content.

I'm not sure it will help, but you can try this:

- Under Netflix addon configuration, expert, purge on memory and cache disk, wait for a message that says it's cleared

- Delete all content in the folder /storage/.Kodi/userdata/addons_data/plugin.video.netflix/cache

- Delete /storage/.Kodi/userdata/addons_data/plugin.video.netflix/manifest.*

- Reboot LibreELEC

These are only temporary files, so it won't harm to do so.

**Comment by ryangodammit** [comment]
Wide vine hadn’t installed properly.

I installed another add on that obviously needed widevine and it prompted itself to reinstall widevine, now everything works.

Thanks for your help

On 28/05/2019, at 3:39 AM, Smeulf <notifications@github.com<mailto:notifications@github.com>> wrote:


Netflix says this message is most likely related to a wrong cache content.

I'm not sure it will help, but you can try this:

  *   Under Netflix addon configuration, expert, purge on memory and cache disk, wait for a message that says it's cleared

  *   Delete all content in the folder /storage/.Kodi/userdata/addons_data/plugin.video.netflix/cache

  *   Delete /storage/.Kodi/userdata/addons_data/plugin.video.netflix/manifest.*

  *   Reboot LibreELEC

These are only temporary files, so it won't harm to do so.
