### ISSUE TITLE
Netlfix Add-on Error - timeout

### ISSUE THREAD

**Issue by subiceman** [CastagnaIT/plugin.video.netflix#900]
#### Your Environment
- Netflix add-on version: 1.10.0
- Operating system version/name: CoreELEC 9.2.4.2/KODI 18.8
- Device model:  X96Max Plus S905X3 4gb/32gb

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Hello. I have a problem with the Netflix add-on. It crashes very often. Sometimes when selecting a profile, often when navigating the Netflix menu. Before I start a movie, netflix will crash at least several times

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/acoxuwusez.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
i have no idea the error you encountered seem a python issue perhaps caused by external conditions

**Comment by subiceman** [comment]
I used a second memory card, fresh coreelec and kodi installation. I installed the Netflix add-on and still have the same problem :(

**Comment by jakermx** [comment]
I had the same issue, I looks that need to close the current playback session, before use a new one.

If you try to play another video while playing, it crashes, but if you stop the video and then start a new one, it is fine.

I dont know if there are some hanged sessions that makes this happens.

**Comment by CastagnaIT** [comment]
> If you try to play another video while playing

just tried on my CoreElec last version but the error not happen
what are the specifics steps?

**Comment by CastagnaIT** [comment]
closed due to inactivity
