### ISSUE TITLE
Kodi crashes after installing the netflix plugin

### ISSUE THREAD

**Issue by codebori** [CastagnaIT/plugin.video.netflix#903]
Kodi crashes immediately after installing the netflix plugin and then again when trying to start Kodi again.
Manually removing the netflix plugin folder allows me to start Kodi again.
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5422892/kodi.log)
[kodi.old.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5422896/kodi.old.log)

**Comment by npmstart-pray** [comment]
More info please: host, os/distro, kodi version...

**Comment by codebori** [comment]
Kodi (18.8 (18.8.0) Git:20200727-20200727-45686bd). Platform: Linux x86 64-bit
Kodi compiled 2020-07-27 by GCC 9.3.1 for Linux x86 64-bit version 5.9.0 (329984)
Running on openSUSE Tumbleweed 20201021, kernel: Linux x86 64-bit version 5.8.15-1-default
FFmpeg version/source: 4.3.1
Host CPU: AMD Ryzen 7 2700X Eight-Core Processor, 16 cores available

I'm sorry, I thought it was enough to include the log files.

Also, the log file states that Kodi was compiled for 64-bit. (who still uses 32 bit?)

**Comment by npmstart-pray** [comment]
Including log files is correct!

Moving everything kodi to 64b would force quite a few users to upgrade host platform, and staying on top of two tranches of kodi would make development and support difficult for devs...when it becomes a clear, inevitable way forward, I’m sure the course will change, but for now (even if I agree w/ you), things stay 32b. (Why can’t everyone be using a rpi 4?)

Rebuild @32b and I’d wager your problems disappear...mostly.

**Comment by codebori** [comment]
> Rebuild @32b and I’d wager your problems disappear...mostly. Sent from nowhere near my ready room with my new tricorder

I didn't build it myself, I installed it through Yast, the opensuse package manager. Trying to change Kodi to 32 bit in Yast will also change some shared libraries to 32 bit, so I'm afraid that is not an option for me. (I am not a developer, I created my GitHub account for some simple patches for game mods.)

So if I understand it correctly, it is not possible for the regular end user to install Kodi with the netflix plugin on a modern desktop?

My main reason to use Kodi is to have the the same easy interface and remote control for Netflix, HBO Go and local videos etc. So if it's not easy it defeats the purpose for me. 
Eventually I might get a Raspberry Pi, but that would be just for fun, I don't need to share my video library or streaming accounts with multiple devices anyway.

But since it doesn't do hardware decoding, could I use a simple virtual machine to run Kodi, or would that still be a big performance hit?

Thanks

**Comment by CastagnaIT** [comment]
do not see error in log,
but if kodi crashes with a force close there is a problem in Kodi core
the add-on is just a script if it fails it is just closed...

**Comment by codebori** [comment]
> do not see error in log,
> but if kodi crashes with a force close there is a problem in Kodi core
> the add-on is just a script if it fails it is just closed...

I found a different log: 
[kodi_crashlog-20201023_144133.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5429520/kodi_crashlog-20201023_144133.log)

But I tried the HBO Go plugin and Kodi does crash as well with that one eventually, however not immediately. So it seems plausible that Kodi itself is the culprit.

Should I close this issue?

**Comment by CastagnaIT** [comment]
Unfurnately i can do nothing here,
and report this problem to Kodi dev is not very useful because Kodi 18 is EOL.

But if Kodi 19 is available for your system and use it you encounter the same crash,
then you can open a issue thread on Kodi github to try fix this on Kodi 19

**Comment by codebori** [comment]
Thanks. I'll try that.
