### ISSUE TITLE
PIN entry at profile selection is shown in clear text

### ISSUE THREAD

**Issue by storage-cube** [CastagnaIT/plugin.video.netflix#905]
#### Your Environment
- Netflix add-on version: 1.1.10
- Operating system version/name: LibreELEC 9.2.4
- Device model:  Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
If I select a profile that needs entry of a PIN, the entered PIN is visible in clear text.

#### Expected behavior
The PIN that is entered shall not be visible in clear text, should rather be * or ? (like usual at PIN entry)

#### Actual behavior
If I select a profile that needs entry of a PIN, the entered PIN is visible in clear text.
Doesn't matter if PIN is entered via mouse, keyboard or TV remote.

#### Steps to reproduce the behavior
1. start plugin
2. choose profile (that needs a PIN entry)
3. enter PIN

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/asapekubuj.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Only the new Kodi 19 support to hide the entered numbers
