### ISSUE TITLE
MySQL connection does not work

### ISSUE THREAD

**Issue by Artiom-M** [CastagnaIT/plugin.video.netflix#906]
#### Your Environment
- Netflix add-on version: Latest
- Operating system version/name: Raspbian
- Device model:  Pi3

Used Operating system:
* [x] Raspberry-Pi

In my setup I have a mySQL database, but when I switch on MySQL in the plugin I am getting this:

2020-10-24 20:53:53.310 T:1426060000   ERROR: [plugin.video.netflix (0)] MySql error 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused):

That's correct, but my database is not on the local host! I have not found where can I change this address.

**Comment by CastagnaIT** [comment]
all the MySQL settings are under addon the setting:
Library->Use shared library MySQL

**Comment by Artiom-M** [comment]
Thank you. I've found it now. It's not evident without documentation. When I switch mySQL on nothing indicates that there are more menus added and I was assuming that it will use the same connexion as Kodi. And after some time it's just auto switched off because of the error (or after I click OK) so when I try to find what's wrong mySQL options are not there any more
