### ISSUE TITLE
Asking to skip credit freeze 

### ISSUE THREAD

**Issue by tsaklidis** [CastagnaIT/plugin.video.netflix#908]
#### Your Environment
- Netflix add-on version: 1.10.1
- Operating system version/name: Raspbian GNU/Linux 10 (buster) 
- Device model:  Raspberry pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
When I see an apisode for example from the middle and after, everything is good. But when I try to watch an episode of some series at the beginning when the titles should be played everything freeze. Example Big Bang theory video plays until the credits are appeared. 
When the crash happens I see in the debug log
one of these: Entered section credit or Asking to skip credit

#### Expected behavior
Play the video or give the ability to skip the credits

#### Actual behavior
Video stops, kodi exits by itself

#### Steps to reproduce the behavior
1. Select an episode of the Big Bang Theory
2. Play the video from the begining

#### Possible fix
Didn't investigate the code. 

### Debug log
The debug log can be found from this link:
[big file] https://tsaklidis.gr/share/kodi.log
[less info] https://paste.kodi.tv/rogozukucu.kodi

#### Installation
Installed based on your github readme page

**Comment by CastagnaIT** [comment]
You are using custom Skin or original Kodi skin?
if yes, try restore original Kodi skin

you mentioned Big Bang theory, only with this tvshow happen?

let me know other 2 things:
- try select a tvshow, open context menu, and select menu "Vote to Netflix". Kodi crash or the window to rating is shown?
- try open addon settings, and open Parental Control. The window is shown or crash?

**Comment by tsaklidis** [comment]
@CastagnaIT 
I am using original skin, just with different color. (Selected from the available)

No it happens on all tv shows. I installed the plugin today so I tried Big Bang Theory, Friends and Peaky Blinders. 

- I can't find the option for the "Vote to Netflix" you mention.
- The parental control is shown. It asks me for password.

**Comment by CastagnaIT** [comment]
unfurnately i can do nothing more for you, the addon not output any errors,
and a kodi crash is a much more serious problem than running an addon script...

i can only suggest to try reinstall Kodi with last version, your version is quite old

**Comment by tsaklidis** [comment]
Okey will try to use Kodi 19. Thank you for your time, closing this.
