### ISSUE TITLE
[doc] Update Authentication wiki

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [CastagnaIT/plugin.video.netflix#910]
Hello,

I used this doc https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key,
and following the "For Linux" on macOS works fine (I had to manually set the Chromium path, but that's it).

So I think you could update the page to add  "macOS" :smile:

Anyway, lot of kudos for the great work!

**Comment by CastagnaIT** [comment]
I have not classified it for macos because it is not full ready for macos,
there is to fix the chrome identification executable,
I no users who volunteered to do tests and also modify the instructions

**Comment by BenjaminVanRyseghem** [comment]
I can do some testing if you guide me :smile:

**Comment by CastagnaIT** [comment]
yes thanks

Is the path to the Chrome executable file standard or could it also be installed to other directories?

Can you run this script and show me the output of screen? (basically check a path and will open the browser)
you can run in same way of authkey script
[test.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5445534/test.zip)

**Comment by BenjaminVanRyseghem** [comment]
Chrome could be installed anywhere, but there's 99% chance it's at `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome` (or `/Applications/Chromium.app/Contents/MacOS/Chromium` for Chromium)

```
SYSTEM: Darwin
PATH EXISTS
ENTER TO CLOSE THE BROWSER
terminate call
```

**Comment by CastagnaIT** [comment]
thanks!
on MacOs python is already installed or a user have to install it to run the script?

**Comment by BenjaminVanRyseghem** [comment]
MacOS Catalina includes python 3, while previous versions included python 2.7.

You can always do a `brew install python3` to have the latest version

**Comment by CastagnaIT** [comment]
well, when you can try to see if now the script open correctly the browser (no need that you login to netflix):
[NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5445718/NFAuthenticationKey.zip)

**Comment by BenjaminVanRyseghem** [comment]
Yes it does, in incognito mode.

**Comment by CastagnaIT** [comment]
good i will publish the new changes
thanks for your time

**Comment by BenjaminVanRyseghem** [comment]
you're welcome :smile:

do not hesitate to ping me if you need more testing :smile:
