### ISSUE TITLE
Complain about pycryptdome version - 3.4.3

### ISSUE THREAD

**Issue by gilbertoferreira** [CastagnaIT/plugin.video.netflix#913]
#### Your Environment
- Netflix add-on version: Leia (18)
- Operating system version/name: Ubuntu 20.10 Groovy
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Trying to used this plugin and complain about pycryptdome wrong version 3.4.3
#### Expected behavior
I expected to be possible install this plugin without issues

#### Actual behavior
complain about pycryptdome wrong version 3.4.3

#### Steps to reproduce the behavior
1. Install Ubuntu 20.10 
2. Install kodi from defaul repo
3. Download https://github.com/CastagnaIT/plugin.video.netflix
4. Initialize the kodi 
5. Try to install plugin but zip file
6. Then complain about pycryptdome version - 3.4.3

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by jakermx** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/requirements.txt

Says it needs version 3.4.5
