### ISSUE TITLE
NFAuthenticationKey_Windows.zip is being flagged as malware

### ISSUE THREAD

**Issue by Beres-Berlin** [CastagnaIT/plugin.video.netflix#915]
Both Firefox and Chrome (on Windows 10) don't let me download your "NFAuthenticationKey_Windows.zip" from dropbox.com, flagging it as "harmful malware". Nine days ago (!) it worked beautifully...

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not used any of the templates provided to correctly open an Issue thread.

Using the templates provided is mandatory to provide all necessary information, this helps us to better manage all your requests, optimizing the time needed to deal with the requests of all users and the development.

Please edit your Issue message to follow our [templates](../issues/new/choose) and make sure to fill in all fields appropriately, or close this Issue and create a new one by using the most suitable template.

If you believe it was sent in error, please say so.
