### ISSUE TITLE
This title is not available to watch instantly. 1044 ERROR

### ISSUE THREAD

**Issue by occubr** [CastagnaIT/plugin.video.netflix#916]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ x] Raspberry-Pi
* [ ] Windows

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not full followed the template we provide and require for all bug reports.

Attach the debug log is mandatory for a bug report, _the log rules are explained in the Issue creation page or in the ReadMe_.

Please edit your Issue message to follow our [template](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md). The issue will be closed after about one week has passed without satisfactory follow-up from your side.

If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.
