### ISSUE TITLE
NFAuthenticationKey_Windows.zip being flagged as malware

### ISSUE THREAD

**Issue by Beres-Berlin** [CastagnaIT/plugin.video.netflix#917]
Hi!

I installed your addon nine days ago on my Raspi 4, now I setup a new system for a friend. When trying to download your "NFAuthenticationKey_Windows.zip" from dropbox ([](https://www.dropbox.com/sh/80zv4umiiyx8ok1/AAABi-vk9CKNNXvpmzkCRTiIa?dl=0)) both Firefox and Chrome stopped the download, claiming a virus is in this file. 

Is there ;-) ?

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not used any of the templates provided to correctly open an Issue thread.

Using the templates provided is mandatory to provide all necessary information, this helps us to better manage all your requests, optimizing the time needed to deal with the requests of all users and the development.

Please edit your Issue message to follow our [templates](../issues/new/choose) and make sure to fill in all fields appropriately, or close this Issue and create a new one by using the most suitable template.

If you believe it was sent in error, please say so.

**Comment by Beres-Berlin** [comment]
Hi!

I think the templates don't apply in this particular case. Here is the result of an online virus scan:
[](https://www.virustotal.com/gui/url/7a4a4de4e768c7739a8f12a3053081fbd583b2139245cdf7b754ddab20efb02d/detection)

**Comment by CastagnaIT** [comment]
You have verified the Dropbox URL, not the content of the ZIP file
The dropbox page is managed by Dropbox itself, if it contains something strange you have to report to Dropbox

This is the result of the ZIP file:
https://www.virustotal.com/gui/file/9fa587b707cd20b438b4357dff104a7543e4778b1ef5ff6b64a52f80effc1e5c/detection
checks 1 to 64 are good, so is a good zip

To have 100% of good rating on the Executable file and allow the verification of any antimalware proccess to pass, the file need to be signed by a certificate.

Buy a certificate costs a lot of money and has an expiration date
I am not going to buy a certificate to sign the executable

You are free not to use this software if you do not trust of the content

**Comment by marcomow** [comment]
Just a heads up @CastagnaIT - for this reason Chrome won't let you download the file

**Comment by Beres-Berlin** [comment]
I understand about the missing certificate and I forgot to mention that I'm very grateful that you publish the addon and the authentication key method. But, as I mentioned, I was not alerted because ten days ago when I downloaded the .zip (also with Firefox on Windows 10) without any trouble. In fact, yesterday, Firefox threw a warning concerning dropbox.com in general "known to host malicious software". And I couldn't download the .zip file. What concerned me is that is this warnings are a new thing. At least for me...

**Comment by CastagnaIT** [comment]
google takes days or mounth to checks websites changes that's why everything was fine in the beginning

Firefox and Chrome both use the same "Google safe browsing" API then report same thing

i have just now reported to google the incorrect phishing warning
i do not know if it will be accepted and within how many days it will be reviewed

then the only way is press "ignore and continue"

**Comment by strech345** [comment]
would it be possible to find the authentication key in chrome console?

**Comment by antquaye** [comment]
I can not use the aunthentication key on adroid. I need your help

**Comment by notoco** [comment]
Just use it on your computer and transfer the file to your android

**Comment by atglabs** [comment]
I was able to use the Edge browser on WIn10 to download the Authentication Key file, without bogus errors from chrome.

**Comment by antquaye** [comment]
it keeps giving me authentication key has expired. when i start a new process to get the another key too, the system gives me current status as 'object reference not set to an instance object.
i need help to overcome this.

thanks

**Comment by bakibhm88** [comment]
I can not use the aunthentication key on adroid. I need your help

**Comment by olivergran** [comment]
@CastagnaIT  why does the key always expire so fast?

**Comment by CastagnaIT** [comment]
The key file to login should be used one time only, not multiple times over the time.

The expiring time is set to two reasons:
- The data contained in the key file does not remain valid over time, the website can also change, this could lead to unexpected problems with the addon and makes it more difficult to analyse reported Issues
- The key file contains the account access data and this is a security issue

**Comment by kaynemo** [comment]
No matter what I do, after the key is generated, the addon returns "emal field not found" error - can't login with this key

**Comment by marianna600** [comment]
Salve a tutti mi sono iscritto da poco come posso fare per avere la key windows zip. Grazie

**Comment by marianna600** [comment]
Sono riuscito a scaricare il file solo che al momento di aprirlo google lo blocca, cosa devo fare?

**Comment by jlcueto** [comment]
I am having the same problem of being able to login to Netflix since I installed a few days ago. I enter the email and password, which are correct but the netflix says it is incorrect. I have tried NFAuthenticationKey and it has loggged in but when I try to play a movie, it states error you must login. It asks me for my email and password or the NFAuthenticationKey again but never lets me play any movie. I have tried uninstalling, re-installing, checking my network router, and cryptodomex but to no avail. I am running on rasspberry pi 4b buster OS with Kodi 18.7, though I want 18.9 but it is not available for buster OS and I do not want Kodi 19.4 because it is still not capable of running an IPTV addon that I use. I would upload my Kodi log but I don't know where to upload it for assistance.

**Comment by maxmalice** [comment]
pareil probleme avec mon compte netflix et la key veux pas telecharger

**Comment by sumnerboy12** [comment]
> No matter what I do, after the key is generated, the addon returns "emal field not found" error - can't login with this key

I am getting this as well - any ideas what the issue might be?

**Comment by tyshiro** [comment]
> Just use it on your computer and transfer the file to your android

How do you transfer to android?

**Comment by tyshiro** [comment]
Hello,
Please advise, I have an Nvidia SHIELD TV pro but I do not have a PC. Is there any other way I can generate the authentication key without having a PC? I love your Netflix add-on.  It made everything so simple for me but I had to factory reset, my Nvidia shield. So now I cannot log back into the add-on using username/password like before. So is there any other way to get that authentication key without having a PC?  Pease advise. 
Thank you so much,
Kris

**Comment by bob-mcsnow** [comment]
Hey @CastagnaIT ,
Thanks greatly for your support for the add on. Can I suggest that instead of storing the file at some random file share like dropbox or files.fm. Maybe just add the script in a submodule in the repo? This would go a lot further to creating the trust that is being questioned in this thread.
Just a suggestion. 
Many thanks,
Tom

**Comment by Isaackodi** [comment]
Hola. Buenas tardes. He conseguido iniciar sesion en netflix en kodi. Pero me da error a la hora de reproducir. Que puede ser? Gracias

**Comment by Flekoun58** [comment]
> Hej[@CastagnaIT](https://github.com/CastagnaIT), Moc děkuji za vaši podporu doplňku. Mohu navrhnout, abyste místo ukládání souboru na nějaké náhodné sdílené místo, jako je Dropbox nebo files.fm, možná skript přidali do submodulu v repozitáři? To by mnohem více přispělo k vytvoření důvěry, která je v tomto vlákně zpochybňována. Jen návrh. Moc děkuji, Tome.



> Hej[@CastagnaIT](https://github.com/CastagnaIT), Moc děkuji za vaši podporu doplňku. Mohu navrhnout, abyste místo ukládání souboru na nějaké náhodné sdílené místo, jako je Dropbox nebo files.fm, možná skript přidali do submodulu v repozitáři? To by mnohem více přispělo k vytvoření důvěry, která je v tomto vlákně zpochybňována. Jen návrh. Moc děkuji, Tome.

**Comment by Flekoun58** [comment]
@tyshiro Yes, there is, the key can also be generated on a phone with the Android operating system via the Pytroid3 application. Cookies can be obtained via the Edge browser and the Edge Editor cookies add-on. It's a bit inconvenient, but it's possible, I did it myself and signed in to Netflix.

**Comment by ml4559** [comment]
@Flekoun58 - thanks for the tip, even whole procedure sounds inconvenient little, yes.
But I know, in the past PC generated key problem have been solved some ways. 
Note - I have cookies enabled on browser setting, Anti-virus disabled, tried on Win7 & Win10...no success.

**Comment by jeod5694** [comment]
hello,

i have an error MSLERROR on android box ? any idea ?

**Comment by HeadbangerWacken** [comment]
Hello I have Netflix Addon 1.23.3 installed on Kodi 21.2. The method with Authentication.key does not work. I created a keyfile with a password. After adding, a password is obtained again and I enter my Netflix password and then get an error.
