### ISSUE TITLE
NFAuthentication not working

### ISSUE THREAD

**Issue by Choccreamyum12** [CastagnaIT/plugin.video.netflix#918]
I keep getting a error saying "Error Reading JObject from JsonReader. Path ", line 0 position."

![image](https://user-images.githubusercontent.com/69184156/97759984-45602b80-1b56-11eb-826d-72ad204a28c4.png)

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not used any of the templates provided to correctly open an Issue thread.

Using the templates provided is mandatory to provide all necessary information, this helps us to better manage all your requests, optimizing the time needed to deal with the requests of all users and the development.

Please edit your Issue message to follow our [templates](../issues/new/choose) and make sure to fill in all fields appropriately, or close this Issue and create a new one by using the most suitable template.

If you believe it was sent in error, please say so.
