### ISSUE TITLE
NFAuthentication not working

### ISSUE THREAD

**Issue by Choccreamyum12** [CastagnaIT/plugin.video.netflix#919]
#### Your Environment
- Netflix add-on version: -----
- Operating system version/name: Windows 10
- Device model:  ----

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
- [x] Windows

### Describe the bug

I keep getting a error saying "Error Reading JObject from JsonReader. Path ", line 0 position."
I keep getting a error saying "Error Reading JObject from JsonReader. Path ", line 0 position."
![image](https://user-images.githubusercontent.com/69184156/97760317-f2d33f00-1b56-11eb-8cfe-287312c8be54.png)

#### Expected behavior

It should take me to the login page.

#### Actual behavior

Comes up with an error

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
NONE

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

![image](https://user-images.githubusercontent.com/69184156/97760356-18604880-1b57-11eb-9b1d-45f91df26bac.png)

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not full followed the template we provide and require for all bug reports.

Attach the debug log is mandatory for a bug report, _the log rules are explained in the Issue creation page or in the ReadMe_.

Please edit your Issue message to follow our [template](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md). The issue will be closed after about one week has passed without satisfactory follow-up from your side.

If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

**Comment by Choccreamyum12** [comment]
> Thank you for your interest in this add-on development,
> this is an automatically generated message by our Bot
> 
> It seems that you have not full followed the template we provide and require for all bug reports.
> 
> Attach the debug log is mandatory for a bug report, _the log rules are explained in the Issue creation page or in the ReadMe_.
> 
> Please edit your Issue message to follow our [template](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md). The issue will be closed after about one week has passed without satisfactory follow-up from your side.
> 
> If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

I am not referring to the Kodi add on but to the NF authentication app, There fore I can not get any logs to upload.

Thank you,

**Comment by CastagnaIT** [comment]
have you edit settings.json?

**Comment by Choccreamyum12** [comment]
No I have not edited the settings.

**Comment by bierbaron2** [comment]
hi, i have the same problem after editing the seetings.json -> Bad JSON escape sequence: \P. Path 'chromeExePath', line 5, position 24. 
I downloaded Chrome for this script and just added in line 5:  "chromeExePath": "C:\Program Files\Google\Chrome\Application\chrome.exe"

**Comment by CastagnaIT** [comment]
I have improved error management try:
[NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5470914/NFAuthenticationKey.zip)

**Comment by CastagnaIT** [comment]
New file: [NFAuthenticationKey.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5470933/NFAuthenticationKey.zip)

**Comment by schitzelfrank** [comment]
I get the same error with, even with the new file

**Comment by CastagnaIT** [comment]
Closed due to inactivity of author
