### ISSUE TITLE
Error playing video

### ISSUE THREAD

**Issue by jamesgreystone** [CastagnaIT/plugin.video.netflix#92]
*I'm submitting a ...*
  - [ * bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

[eg. 13.21.0] latest .14.3

### Description

[Description of the bug or feature]

Error Argument “cipherkeyid” for “Encrypt” must be a string or a bytearray

### Steps to Reproduce

1. [First Step] just try to play anything 
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

Should play
**Actual behavior:** [What actually happened]

## Context (Environment)
Kodi 18.2
### Installation

* [ *] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ *] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

Standard Kodi 18.2 on Android box
## Debug log

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have con
![922A60F1-FCD9-4D20-9BB7-C39ED9C142AA](https://user-images.githubusercontent.com/51140757/58752028-eb959680-8475-11e9-8cf8-1065b55bb808.jpeg)
text, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Smeulf** [comment]
Please enable debug and send logs following the debug logs section.

**Comment by CastagnaIT** [comment]
and what is the exact model of the device?
there are several chinese android boxes that have similar problems some are netflix banned devices,
probably also need to check the android logcat to know what happen

**Comment by jamesgreystone** [comment]
here is the debug log.

https://paste.kodi.tv/elexesosud

**Comment by jamesgreystone** [comment]
> and what is the exact model of the device?
> there are several chinese android boxes that have similar problems some are netflix banned devices,
> probably also need to check the android logcat to know what happen

It is a Mecool M8S L pro box

**Comment by jamesgreystone** [comment]
> Please enable debug and send logs following the debug logs section.

Oddly now I can't even get to the same error, it now comes up initially as Addonsignals call timed out first.
I turned on debug log and set it up here.

Thanks.

**Comment by jamesgreystone** [comment]
Let me know if I can send any other logs to help. Thank You.

**Comment by CastagnaIT** [comment]
yes confirm, that device is not full certified for netflix and widevine
some say to replace the original firmware, but this does not fit into the context of the addon
i'm sorry no easy solutions for you...
