### ISSUE TITLE
Please close all Chrome windows open

### ISSUE THREAD

**Issue by marcomow** [CastagnaIT/plugin.video.netflix#920]
#### Your Environment
- Netflix add-on version: Authenticator
- Operating system version/name: Windows10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

The authenticator won't go further than "Please close all Chrome windows" even if there are none
![image](https://user-images.githubusercontent.com/4977000/97776487-30dd5c80-1b71-11eb-8dee-f41de4608a42.png)

#### Expected behavior

The authenticator should run

#### Actual behavior

the authenticator gets stuck with this improper error

#### Steps to reproduce the behavior

1. open the authenticator app
2. click Run
3. get the error

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not full followed the template we provide and require for all bug reports.

Attach the debug log is mandatory for a bug report, _the log rules are explained in the Issue creation page or in the ReadMe_.

Please edit your Issue message to follow our [template](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md). The issue will be closed after about one week has passed without satisfactory follow-up from your side.

If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

**Comment by CastagnaIT** [comment]
open task manager
go to Details page and terminate all Chrome.exe
