### ISSUE TITLE
JSON-RPC videolibrary.flattentvshows triggers error

### ISSUE THREAD

**Issue by gversluis** [CastagnaIT/plugin.video.netflix#921]
#### Your Environment
- Netflix add-on version: 1.10.1
- Kodi version: 18.9.0
- Operating system version/name: Ubuntu 16.04

Used Operating system:
* [ ] Android
* [ ] iOS
* [x ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

When shows have a single season JSON-RPC: {"params": {"properties": ["thumbnail", "lockmode"]}, "jsonrpc": "2.0", "method": "Profiles.GetCurrentProfile", "id": 1}
The JSON-RPC response is {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}
Which triggers an error.
This may be a configuration issue at my side.

#### Expected behavior

Display list of episodes.

#### Actual behavior

Show error JSON-RPC: -32602, Invalid params.

#### Steps to reproduce the behavior

1. Open TV show with single season, i.e. Love, Death &amp; Robots

#### Possible fix

As temporary solution I directly set value=0 (but other values also work) in addons/plugin.video.netflix/resources/lib/navigation/directory.py:128

### Debug log

I skipped the log and completely understand if you will directly close the issue.

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Other information

$ telnet localhost 9090
Trying ::1...
Connected to localhost.
Escape character is '^]'.
{"params": {"properties": ["thumbnail", "lockmode"]}, "jsonrpc": "2.0", "method": "Profiles.GetCurrentProfile", "id": 1}
{"id":1,"jsonrpc":"2.0","result":{"label":"Master user","lockmode":0,"thumbnail":""}}
{"params": {"setting": "videolibrary.flattentvshows"}, "jsonrpc": "2.0", "method": "Settings.GetSettingValue", "id": 1}
{"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}

I probably have an invalid configuration and found flattentvshows in these userdata files:
advancedsettings.xml (nested in advancedsettings > videolibrary): <flattentvshows>0</flattentvshows>
guisettings.xml (nested in <settings version="2">): <setting id="videolibrary.flattentvshows">0</setting>

I'm still looking into this issue myself and might come with a solution.

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not full followed the template we provide and require for all bug reports.

Attach the debug log is mandatory for a bug report, _the log rules are explained in the Issue creation page or in the ReadMe_.

Please edit your Issue message to follow our [template](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md). The issue will be closed after about one week has passed without satisfactory follow-up from your side.

If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

**Comment by gversluis** [comment]
I shared this issue so other with the same issue might easily solve it and can see the cause. I will log my progress on solving the issue here.

**Comment by gversluis** [comment]
Tried {"params": {"setting": "videolibrary.flattentvshows"}, "jsonrpc": "2.0", "method": "Settings.ResetSettingValue", "id": 1}
Result {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}

Tried {"params": {"setting": "videolibrary.flattentvshows", "value": 0}, "jsonrpc": "2.0", "method": "Settings.SetSettingValue", "id": 1}
Result {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}

No progress so far.

**Comment by gversluis** [comment]
Solved.
