### ISSUE TITLE
Impossible login

### ISSUE THREAD

**Issue by MarcoViti** [CastagnaIT/plugin.video.netflix#922]
S.O. Windows 10 (19042.610) x64 pro
Netflix add-on version 1.10.1 (Matrix)

Hi, for months I have been using the netflix add-on with NFAuthenticationKey access quietly ... after a clean installation of Kodi Matrix (latest build of 10/31/2020) I can no longer access the kodi / netflix add-on with none of the 2 systems (email / password and not even with NFAuthenticationKey), while from chrome I can easily access my profile (so my credentials are correct). I attach kodi .log file:
https://paste.kodi.tv/ihocamegop.kodi

**Comment by CastagnaIT** [comment]
Thank you for your interest in this add-on development,
this is an automatically generated message by our Bot

It seems that you have not used any of the templates provided to correctly open an Issue thread.

Using the templates provided is mandatory to provide all necessary information, this helps us to better manage all your requests, optimizing the time needed to deal with the requests of all users and the development.

Please edit your Issue message to follow our [templates](../issues/new/choose) and make sure to fill in all fields appropriately, or close this Issue and create a new one by using the most suitable template.

If you believe it was sent in error, please say so.

**Comment by CastagnaIT** [comment]
Your matrix version has some bugs
nothing that can be done here
