### ISSUE TITLE
Exception: Authentication key file not supported

### ISSUE THREAD

**Issue by o-rayer** [CastagnaIT/plugin.video.netflix#923]
#### Your Environment
- Netflix add-on version: <1.9.1>, tested also with <1.10.0> and <1.10.1>
- Operating system version/name: <LibreElec , Kodi 18.8 Leia>
- Device model:  <Raspberry Pi 4 model B>

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ X] Raspberry-Pi
* [ ] Windows

### Describe the bug

Hi, I followed every step in the ReadMe to generate an Authentication Key for Netflix add-on and I get the error : `Exception: Authentication key file not supported`.

I generated the key using MacOS and last Python file available (1.0.3) that worked like a charm.

Thanks in advance!

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:

https://we.tl/t-mxGySLEgUo

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by simon-vasseur** [comment]
Hey,

I think it's only supported only in version 1.10.2 (- Add support to NFAuthentication for MacOS).

On my side, as a temporary workaround, I edited the source file directly on LibreElec to add "MacOS" case.

https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/common/credentials.py#L216

Regards.

**Comment by o-rayer** [comment]
Thanks @simon-vasseur , after further investigations it is indeed simply not working on MacOS...

I think @CastagnaIT [last commit](https://github.com/CastagnaIT/plugin.video.netflix/commit/d9c371ef2844c0b11b4dffbe2220687394773cc3) will fix it in a later version.

Meanwhile the easiest workaround I found (the direct file editing was also a cool option) was to install Raspberry OS on a second SD Card and run the script from there 👍 !

Thanks a lot!

**Comment by OBrown92** [comment]
Maybe it should be mentioned in the wiki, cause there is the title `For Linux and MacOS`.
