### ISSUE TITLE
XBMC numeric dialog box not working in Kodi 19

### ISSUE THREAD

**Issue by johnpaul7** [CastagnaIT/plugin.video.netflix#924]
#### Your Environment
- Netflix add-on version: 1.10.1+matrix.1
- Operating system version/name: LibreElec (community) nightly-20191226-b814aab 9.80 (Kodi 19.0-ALPHA1)
- Device model:  Pine A64+

Used Operating system:
* [ ] Linux

### Describe the bug

After selecting the Authentication key file, the Netflix addon fails when trying to open the XBMC numeric dialog box claiming it has too many arguments.

#### Expected behavior

Should come up with a dialog box for entering the PIN number for the Authentication key.

#### Actual behavior

Gives a 'Netflix Add-on Error' dialog box saying:

TypeError: function takes at most 3 keyword arguments (4 given)

#### Steps to reproduce the behavior

1. Open the addon
2. Choose Authentication Key
3. Select the key file

#### Possible fix

Looks like there is a difference in the xbmcgui.Dialog().numeric function between Kodi 18 (which accepts 3 arguments) and Kodi 19 (which accepts 4 arguments), but I'm a little confused as I'm running Kodi 19 so it should work.

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/anonusewes.kodi

#### Installation
* [ ] I'm using other Netflix Repo: CastagnaIT Repository for Kodi 19.x (MATRIX)

**Comment by CastagnaIT** [comment]
This Kodi version is old and currently ALPHA versions has a differents problems

**Comment by uhdtv3d** [comment]
Hi,
I am also getting the same error in my fire TV stick 4K while it is working fine in my android 4K TV.
Any help for fire stick would be appreciated.
