### ISSUE TITLE
Addon Signals call timeout

### ISSUE THREAD

**Issue by Lordjontan** [CastagnaIT/plugin.video.netflix#925]
#### Your Environment
- Netflix add-on version: 1.10.1 
- Operating system version/name: Coreelec 9.2.5
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

After turn on the system, Netflix addon works well but after a few minutes I get an Addon Signals Call Timeout error, so I have to disable/enable the addon every time I want to watch something
#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link: http://paste.kodi.tv/saxipakaro

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by wsnipex** [comment]
this is fixed by inputstream.adaptive 2.6.4

**Comment by CastagnaIT** [comment]
@wsnipex here is Kodi 18 that is 2.4.6

but from the log i do not see the internet http response, suggest problems with your network
i can not do nothig here

**Comment by Lordjontan** [comment]
I don't think it's a networks issue, I have not problems with other addons in the same box neither with Netflix official apps on another devices. I'll check with my neighbour wifi...

**Comment by CastagnaIT** [comment]
i am sorry but i do not have other solutions for you

**Comment by petvoigt** [comment]
On Sun, 01 Nov 2020 01:27:44 -0700
Wolfgang Schupp <notifications@github.com> wrote:

> this is fixed by inputstream.adaptive 2.6.4
> 

Thanks for feedback. I am struggling with timeout problems for some
days too. I am using Libreelec 9.0.2 on Odroid C2.

I checked my installed version of inputstream.adaptive and it is
2.3.22.1. However, an update is not offered. Could you please advice
how to upgrade to version 2.6.4?
