### ISSUE TITLE
Continously email notification from netflix about a new log-in

### ISSUE THREAD

**Issue by the-dreamer** [CastagnaIT/plugin.video.netflix#93]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used

[14.3.0]

### Description
On each start of the LE Kodi 18 i've got an email notification from Netflix that a new device has been logged in. This happend since the very beginning of the V14 development. For me since today not solved. 

### Steps to Reproduce

1. restart system
2. 
3. 

**Expected behavior:** [What you expected to happen]
Email notification only once after first login in addon

**Actual behavior:** [What actually happened]
nearly after every restart of the system i've got an email notification from netflix

## Context (Environment)
Libreelec V9.0.2 (Kodi 18.2)
### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by Smeulf** [comment]
Without your logs, there's no way to tell what's going on. Please unable debug logs, then restart your device, go to Netflix, ensure you have an email a d post your logs

**Comment by Smeulf** [comment]
Also please update to 14.3 before, may already be solved

**Comment by CastagnaIT** [comment]
the notification is possible when your ip address change often or esn changed or uses vpn?!?
this notification not depend from the addon

**Comment by the-dreamer** [comment]
I need to mention, with v13.22 ist doesn't Happen.
IP is changes only every 24h, vpn is not used.

**Comment by C-O-D** [comment]
Same here, only thing that changes is the IP everyday forced by my provider and I get this mail every day...

**Comment by chris42** [comment]
It is the regular behaviour of netflix. Every time you log in you get an E-Mail. You can use your browser on the same IP to log in-out-in... and every time you get the E-Mail. Hence if your restart your Kodi, it logs in, you get the E-Mail.
On the bottom it is stated, that you can change it in the communication preferences in your account, however never tested it.

**Comment by the-dreamer** [comment]
The Problem is not the email itself, when new login happens. The issue here is that everyday kodi start you get this mail and this behaviour is new since Netflix Addon V0.14.xx

Asciidiscos Netflix Addon doesn't have this issue.

**Comment by Smeulf** [comment]
Did I asked for logs? If you want help, help us with logs...

**Comment by kendrak24** [comment]
There are two short-lived cookies that may cause this problem. Names start with 'lhpuuidh-browse-' and they expire after 12 hours.

**Comment by the-dreamer** [comment]
Is that fixable? I mean, in < 0.14 it doesn't happend.
