### ISSUE TITLE
Login by email or Authentication Key fails.

### ISSUE THREAD

**Issue by JatB1964** [CastagnaIT/plugin.video.netflix#930]
#### Your Environment
- Netflix add-on version: 1.10.1
- Operating system version/name: Windows 10, LibreElec 9.2.5
- Device model:  Laptop, Rasberry PI 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows
* [x] Libreelect

### Describe the bug
After applying the Authentication Key, a parse error occured when entering the password

#### Actual behavior
Login to netflix via username and password fails
Login to netflix via authentication fails 

#### Steps to reproduce the behavior

1. Installed the actual netflix plugin from zip file 1.10.1
2. Try to login to netflix
3. select key file, generated on windows machine
4. enter code
5. enter password

### Debug log

The debug log can be found from this link:
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5504652/kodi.log)

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Hi please update or reinstall with: [plugin.video.netflix_1.10.1_20201109_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5510942/plugin.video.netflix_1.10.1_20201109_t1.zip)
and let me know

**Comment by JatB1964** [comment]
Hi,

I reinstalled the provided plugin and it worked very good for me with authentication key. Login by user and password is still not working.

Thanks for quick support.

Norbert

**Comment by CastagnaIT** [comment]
Good,
thank you for your support is of great help!

**Comment by fcr** [comment]
> Hi please update or reinstall with: [plugin.video.netflix_1.10.1_20201109_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5510942/plugin.video.netflix_1.10.1_20201109_t1.zip)
> and let me know

I had the same problem on my Mac Mini 2018 running 10.15.7.
This fix also solved the problem. Thank you.
