### ISSUE TITLE
Error message(s) after each video

### ISSUE THREAD

**Issue by beatschubser** [CastagnaIT/plugin.video.netflix#931]
#### Your Environment
- Netflix add-on version: 1.10.1
- Operating system version/name: LibreELEC 9.2.6
- Device model:  RPi 3B+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Since a couple of weeks I get one or two error messages after each video on netflix. Often I get thrown out of netflix into the main menu and have to navigate to the series I was watching again.

#### Steps to reproduce the behavior

1. Start a movie or series on netflix
2. Stop the video
3. Most of the time one or two errors will be displayed

### Debug log

The debug log can be found from this link: https://pastebin.com/2qUrCEit

**Comment by beatschubser** [comment]
Changed inline log output to pastebin-link. Please remove the "Ignored rules"-label.

**Comment by CastagnaIT** [comment]
The log is incomplete and not follow the rules

**Comment by lardwick** [comment]
hello,

i got the same issue  i run kodi 18.8 with librelec 9.2 on a raspberry pi 4.

after i watched a netflix video, impossible to watch a second with several error message that kick me out of the netflix addon , to come back i got desactivate and re activate the addon on kodi.

this is my logs 
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5518223/kodi.log)

**Comment by beatschubser** [comment]
@CastagnaIT New logfile with verbose enabled in LibreELEC and netflix-Plugin: https://pastebin.com/s0xV0dGW

**Comment by CastagnaIT** [comment]
guys if you do not publish logs by following the Readme instructions i will close this Issue
@lardwick the log has no netflix info and no played video info
@beatschubser a cut log is not useful

**Comment by beatschubser** [comment]
I cannot find any service that accepts log files that big (6-10MB). I'm not an expert and just trying to help find the issue. I thought lines 85ff in my log show what's wrong.

If you know where to upload huge logfiles I will provide a full log from booting until the error occurs.

**Comment by CastagnaIT** [comment]
you can try attach the file directly in the message or use dropbox links or use wetransfer links

**Comment by CastagnaIT** [comment]
take the log after a Kodi reboot can help to have a smaller log

**Comment by beatschubser** [comment]
@CastagnaIT  Full log from boot to error: https://www.file-upload.net/download-14359969/kodi.log.html

**Comment by CastagnaIT** [comment]
@beatschubser thanks now you have post a good log
now i can understand that you have same problem of already opened issue
please follow: https://github.com/CastagnaIT/plugin.video.netflix/issues/914
