### ISSUE TITLE
Plugin fails to start due to ImportError

### ISSUE THREAD

**Issue by pheanex** [CastagnaIT/plugin.video.netflix#932]
#### Your Environment
- Netflix add-on version: Tested with v1.10.1, v1.10.0 and v1.9.1
- Operating system version/name: (lsb_release -a)
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
~# uname -a
Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
- Device model:  Raspberry Revision a0104
Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

#### Expected behavior

App starts up successfully

#### Actual behavior

When starting the app, an error message is shown that mentions an import for Crypto.Random fails

#### Steps to reproduce the behavior

1. Installing the plugin
2. Starting the plugin

### Debug log

The debug log can be found from this link: https://paste.kodi.tv/fosawituja.kodi

#### Installation
I am using the https://github.com/CastagnaIT/repository.castagnait repository
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by GVDmeijde** [comment]
I have the same issue, the login is not displayed. Instead i get a message stating "cryptodome.random" is not available.

**Comment by wagnerch** [comment]
You need to install pycryptodome.  On Raspbian 10 (Buster), you can do:

```
sudo apt-get update
sudo apt-get install libnss3 python-pycryptodome
```

Also, you should bump your GPU mem.  76MB is too low for HEVC playback.  See:
https://www.raspberrypi.org/forums/viewtopic.php?t=251645

For more instructions on how to probably configure Kodi on Raspbian 10.

**Comment by CastagnaIT** [comment]
@wagnerch our wiki RPI Raspbian install instructions are outdated?

```
sudo apt update
sudo apt install build-essential python-pip
sudo apt install python-setuptools
sudo pip install wheel
pip install pycryptodomex
sudo apt install kodi-inputstream-adaptive
```

can you explain a bit?
"pycryptodomex" package is not more available for RPI?
"libnss3" package is now a requirement (other users in the past told me that it was not necessary to install it manually)?

**Comment by wagnerch** [comment]
@CastagnaIT 

- libnss3 is a requirement from inputstream helper, on a "Lite" install of Raspbian it didn't come preinstalled.  When I built my Raspbian 10 install, that popped up from IS helper as a requirement.
- you can use pip to install pycryptodomex, if you want.  On stretch (Raspbian 9) the only way to install pycrypdomex was to use pip.  On buster, the apt repositories include python-pycryptodome (since it is included in Debian 10).  So it can be reduced to these steps (on Raspbian 10 only):
```
sudo apt-get update
sudo apt-get install libnss3 python-pycryptodome kodi-inputstream-adaptive
```

NOTE: python-pycryptodome was available in apt on Raspbian 9 (stretch) as well, but you needed to use debian-backports repository.  I was using that on my OSMC device which was still running stretch until recently.

**Comment by CastagnaIT** [comment]
thanks for the good explanation, now i can see the light better

**Comment by pheanex** [comment]
@wagnerch Thank you for your response.
Is there some documentation, that i might have missed about installing these dependencies?
I would have assumed that these packages had been automatically installed with either the plugin or kodi itself.

@CastagnaIT Can you link to which documentation you are referring to?

**Comment by wagnerch** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon

**Comment by pheanex** [comment]
Installing the suggested packages fixed the problem. Thank you for your support :+1:
