### ISSUE TITLE
This title is not available to watch instantly. 1044 ERROR 

### ISSUE THREAD

**Issue by occubr** [CastagnaIT/plugin.video.netflix#935]
#### Your Environment
- Netflix add-on version: 1.10.1
- Operating system version/name: Libreelec 9.2.5
- Device model: Raspberry Pi 4 model B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x ] Raspberry-Pi
* [ ] Windows

### Describe the bug

https://paste.kodi.tv/emayuhobuy

I am multibooting libreelec, kali, retropi, picroft using barryboot on an external hdd on my raspberry pi. I get this title is not available instantly 1044 every time I try to play anything on netflix

#### Expected behavior

It should play videos
#### Actual behavior

It dosent play videos and gives me 1044 error

#### Steps to reproduce the behavior

1. I have installed libreelec 9.2.5 and kodi 18.8 leia, also I have installed fusion.tvaddons, indigo, GitHub, and the castagnait repository and the Netflix add-on.
2.
3.

#### Possible fix

no ideea
### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/emayuhobuy

#### Installation
* [ x] I'm using other Netflix Repo castagnait
* [ ] I'm using a different source

**Comment by notoco** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#This-title-is-not-available-to-watch-instantly

> I have installed fusion.tvaddons, indigo,

You also installed a ton of crap, Bitcoin miners, free ads, and a few spies - Just read on reddit
Remove whatever you have from tvaddons asap.

**Comment by occubr** [comment]
I am new at this so please bear with me. I will make a soft and hard reset of libreelec and a dimitrology repository reset of kodi and try again fresh with netflix add on and se what happens. I will post the result today.

**Comment by occubr** [comment]
Also i have read the wiki with faq about netflix problems before i have opened this issue, it didnt help me, maybe i didnt understand, can someone tell me how to make netflix work on my raspberry pi?

**Comment by CastagnaIT** [comment]
The wiki answer is the only know solutions
if you have the opportunity you can try also to connect to a different internet connection

**Comment by occubr** [comment]
I have tryed 3 different internet conections, 2 on wirless 1 on a lan, the same result. I thought that two, i thouth that it was a connection problem, and the video could not load properly. I also installed hbo go and videos play fine on it. I dont know what else to do. I will probebly try a different os if this dosent work. But i really liked kodi and libreelec

**Comment by CastagnaIT** [comment]
your debug log have no netflix log info, follow readme instruction and get new log

> I have tryed 3 different internet conections, 2 on wirless 1 on a lan

on same physical router? i do not mean connection type but different line

**Comment by occubr** [comment]
I dont mean that 3 different conections on a single router, i have tried on my home router, wirless on a mobile hotspot, and on my work router on a lan connection.

**Comment by occubr** [comment]
If you loook at the logs at line 1943 you can see plugin netflix error also 1968 and so on. I will provide latter a new debug log after i will do a libreelec reset and kodi reset

**Comment by occubr** [comment]
ok, I have made a factory reset for libreelect, soft and hard, and a kodi reset using dimitrology repositori. I only installed the log viewer for kodi, kodi logfile uploader and Netflix and I get the same error. 
https://paste.kodi.tv/okukuliquv
this is the error log, you can see at line 1902 the 1044 error message. 
Can someone help me? please

**Comment by CastagnaIT** [comment]
you have not followed log instruction again
also the new log not have the netflix debug info

**Comment by occubr** [comment]
What instructions have i not followed and what netflix debug log info should i have posted

**Comment by CastagnaIT** [comment]
These are the instruction steps of the Readme:

![image](https://user-images.githubusercontent.com/3257156/99063536-f0380700-25a4-11eb-9685-d93dccf91873.png)

You have not done the 1° point

**Comment by occubr** [comment]
https://paste.kodi.tv/osotayuful
Hope that now it`s fine and that someone could help me. the error starts at line 10614

**Comment by CastagnaIT** [comment]
no

`2020-11-13 16:07:10.202 T:3864355696    INFO: [plugin.video.netflix (0)] The debug logging level is set as "Disabled"`

**Comment by frkikg** [comment]
I have same issue, here is my log (kodi debug level, netflix plugin verbose)
https://paste.kodi.tv/oseyolutaf.kodi 
and here is another one 
https://paste.kodi.tv/eyoyoheyik

Issue started to happen 3 weeks ago, previously I didn't have any issues. 

This error is from kodi on Android TV. I've also tried kod on windows where same plugin works without issues

**Comment by CastagnaIT** [comment]
@frkikg try update with last addon **Dailybuild** version, link in readme,
after install, try do a `Reset ESN` from addon expert setting

**Comment by frkikg** [comment]
@CastagnaIT  thanks for answer. I 've tried latest Dailybuild plugin.video.netflix_1.11.0_20201123.zip , and did Reset ESN. Same issue happened. I've tried reinstalling plugin as well. 

Here is new log file https://paste.kodi.tv/notafakomu.kodi from Dailybuild version.

**Comment by CastagnaIT** [comment]
@frkikg please take a screenshot of the ESN in the android netflix app under settings by censuring only last characters

**Comment by chicc0** [comment]
Same error. Log here

https://paste.kodi.tv/eduvokimer.kodi
Esn in use with Android app
https://gyazo.com/73204db617726bec93afaea6abd3eae4

No problem playing any title in any other device..

**Comment by CastagnaIT** [comment]
@chicc0 i need you attach also system info,
how to here:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#video-stream-only-at-540p-sd-on-android-device

on `Video Stream only at 540P (SD) on Android device` follow step nr.3

**Comment by chicc0** [comment]
> @chicc0 i need you attach also system info,
> how to here:
> https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#video-stream-only-at-540p-sd-on-android-device
> 
> on `Video Stream only at 540P (SD) on Android device` follow step nr.3
 Here is my hetprop with termux
https://paste.kodi.tv/ucuqeboxor.kodi

**Comment by gliga03** [comment]
I have the same issue on Eon Smart Box (KSTB6020) - Android TV 9, Kodi v18.9 Leia, Here is my log:

**Comment by gliga03** [comment]
I have the same issue on Eon Smart Box (KSTB6020) - Android TV 9, Kodi v18.9 Leia, Here is my log:
https://paste.kodi.tv/epudeticus.kodi

**Comment by CastagnaIT** [comment]
for @frkikg and @chicc0 
update addon with follow test and under Expert setting on `Force Widevine security level L3` set to `Widevine L3`
if no error is show in toast message, try play a video

for @gliga03
update addon with follow test and under Expert setting on `Force Widevine security level L3` set to `Widevine L3`
if no error is show in toast message, try play a video
in alternative try set to `Widevine L3 (ID-4445)` and if no error try play a video

[plugin.video.netflix_1.11.0_20201203_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5634575/plugin.video.netflix_1.11.0_20201203_t1.zip)

**Comment by gliga03** [comment]
Thank you, it works now (with Widevine L3)!

**Comment by frkikg** [comment]
@CastagnaIT Thanks, works for me too.

**Comment by CastagnaIT** [comment]
well then this fix has been added (for android devices)
