### ISSUE TITLE
Mibox 3 540p playback 

### ISSUE THREAD

**Issue by ananias47** [CastagnaIT/plugin.video.netflix#947]
#### Your Environment
- Netflix add-on version: 1.10.1
- Operating system version/name:  android 9 ,kodi 18.9
- Device model:  mibox 3

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Mibox 3 plays all videos at 540p
#### Actual behavior

doesnt play the videos at 1080 as it shouds
#### Steps to reproduce the behavior

1. i have try to delete kodi and install only the netflix addon from your repo
2. i also reset esn 
3.

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

![Screenshot_20201113-002335_AnyDesk](https://user-images.githubusercontent.com/6560173/99004827-63f7f680-2548-11eb-8f0b-99405377da4b.jpg)
![Screenshot_20201113-002511_AnyDesk](https://user-images.githubusercontent.com/6560173/99004828-65c1ba00-2548-11eb-8afc-b0b1944e6ef3.jpg)
![Screenshot_20201113-002249_AnyDesk](https://user-images.githubusercontent.com/6560173/99004831-665a5080-2548-11eb-8c14-c89b086125ee.jpg)
![Screenshot_20201113-002422_AnyDesk](https://user-images.githubusercontent.com/6560173/99004835-66f2e700-2548-11eb-9793-2569df72166e.jpg)
![Screenshot_20201113-002407_AnyDesk](https://user-images.githubusercontent.com/6560173/99004838-68241400-2548-11eb-9f3b-0f0977044daf.jpg)
![Screenshot_20201113-002457_AnyDesk](https://user-images.githubusercontent.com/6560173/99004841-68bcaa80-2548-11eb-9e6a-83f59ed6d6b3.jpg)
![Screenshot_20201113-002435_AnyDesk](https://user-images.githubusercontent.com/6560173/99004845-69edd780-2548-11eb-90cd-b2cd82e6e502.jpg)
![Screenshot_20201113-002316_AnyDesk](https://user-images.githubusercontent.com/6560173/99004823-622e3300-2548-11eb-9789-8b8ad2637f6e.jpg)
![Screenshot_20201113-002350_AnyDesk](https://user-images.githubusercontent.com/6560173/99004825-635f6000-2548-11eb-9a1d-bbba0de4cce5.jpg)

**Comment by CastagnaIT** [comment]
Open an regular `Bug report issue` and fill all required points

Ensure that you provide all informations of 3° step of "Video Stream only at 540P (SD) on Android device":
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#video-stream-only-at-540p-sd-on-android-device
