### ISSUE TITLE
Mibox 3 540p playback

### ISSUE THREAD

**Issue by ananias47** [CastagnaIT/plugin.video.netflix#949]
#### Your Environment
- Netflix add-on version: 1.11. 0
- Operating system version/name: android 9,kodi 18.9
- Device model:  mibox 3

Used Operating system:
* [X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
plays all videos at 540p 

https://paste.ubuntu.com/p/D52K3NpFfX/
#### Expected behavior

Should play video at 1080p as the original Netflix app
#### Actual behavior

Plays at 540p
#### Steps to reproduce the behavior

1.i have try many videos and all plays at 540p
2.
3.

#### Possible fix

I have tried to reset esn but still the same problem
### Debug log

The debug log can be found from this link:
https://paste.ubuntu.com/p/D52K3NpFfX/

### Additional context or screenshots (if appropriate)
![Screenshot_20201115-211417](https://user-images.githubusercontent.com/6560173/99309894-d75c7980-2862-11eb-9b89-baf2b2f94fc1.png)

#### Installation
* [ ] I'm using other Netflix Repo  

* [ ] I'm using a different source 

#### Other information

[terminal.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/5549619/terminal.txt)
Also i sent you on email the esn photo of Netflix app

#### Screenshots

![20201115_211159](https://user-images.githubusercontent.com/6560173/99308138-2d7bed80-2860-11eb-9095-7b2fa338afca.jpg)
Netflix app plays at 1080p.

**Comment by CastagnaIT** [comment]
addon debug is disabled:

`2020-11-16 22:30:15.814 T:25827    INFO: [plugin.video.netflix (25)] The debug logging level is set as "Disabled"`

by following instruction in Readme get a new log

**Comment by ananias47** [comment]
Sorry my friend i didn't managed to upload it on Ubuntu pastebin 
#[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/5552888/kodi.log)

**Comment by CastagnaIT** [comment]
can you say me another two things
have you installed last version of android Netflix app of playStore?
what is your Netflix android app version number?

**Comment by CastagnaIT** [comment]
Try delete the addon with also user data when prompt then install this test:
[plugin.video.netflix_1.11.0_20201117_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5553879/plugin.video.netflix_1.11.0_20201117_t1.zip)

**Comment by ananias47** [comment]
Yes my friend with test version it plays 1080p thnx
Ps and yes i have latest version of Netflix app 8.0.0 build 3642
