### ISSUE TITLE
Share video from the Android Netflix app

### ISSUE THREAD

**Issue by MartChic** [CastagnaIT/plugin.video.netflix#950]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

With the Youtube and Amazon Prime Video addons, it is already possible to share a video and send it to Kodi via "Play with Kodi". It would be nice to have this also with Netflix.

**Comment by CastagnaIT** [comment]
i have no idea how works Amazon and how is this implemented
but netflix app provide only share link for film and tvshow and not single episodes

personally i will not invest time in this,
if someone else wants to dev to integrate it i am willing to offer help
