### ISSUE TITLE
NFAuthentication Key for linux Unable to connect with the browser

### ISSUE THREAD

**Issue by kocicky** [CastagnaIT/plugin.video.netflix#951]
#### Your Environment
- Operating system version/name: Mac OS 10.13
- Python 2.7.16
- NFAuthentication Key for Linux/MacOS (Version 1.0.3)

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [X] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

I have closed Chrome, write into terminal, browser starts but nothing happened, than browser close.

**Comment by kocicky** [comment]
When I try it on Windows, I got this error: https://github.com/CastagnaIT/plugin.video.netflix/issues/919

**Comment by CastagnaIT** [comment]
Hi, i need you try again on MacOS and take a screenshot of the terminal output when the script end

> , than browser close.

you have closed the browser or the browser closed by itself?

**Comment by kocicky** [comment]
https://www.dropbox.com/s/muyz4yvdgc3kjvk/Sn%C3%ADmek%20obrazovky%202020-11-29%20v%C2%A021.18.03.png?dl=0
Telemicka:~ catt$ python /Users/catt/Downloads/Linux/NFAuthenticationKey/NFAuthenticationKey.py 

NFAuthentication Key for Linux/MacOS (Version 1.0.3)

Disclaimer:
This script and source code available on GitHub are provided "as is" without warranty of any kind, either express or implied. Use at your own risk. The use of the software is done at your own discretion and risk with the agreement that you will be solely responsible for any damage resulting from such activities and you are solely responsible for adequate data protection.

Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Browser startup... please wait
Establish connection with the browser... please wait
Unable to connect with the browser

**Comment by CastagnaIT** [comment]
Try this on windows:
[NFAuthenticationKey_Windows_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5625021/NFAuthenticationKey_Windows_t1.zip)

Try this on mac, and if not works, show me the terminal output:
[NFAuthenticationKey_LinuxMac_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5625088/NFAuthenticationKey_LinuxMac_t1.zip)

**Comment by kocicky** [comment]
Mac:
Browser startup... please wait
Establish connection with the browser... please wait
ERROR: <urlopen error [Errno 61] Connection refused> (repeated)
ERROR: 'ascii' codec can't decode byte 0xc3 in position 206: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 1106: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 1556: ordinal not in range(128) (repeated)
Unable to connect with the browser

**Comment by CastagnaIT** [comment]
My bad python2 is different... try show me again the errors with this:
[NFAuthenticationKey_LinuxMac_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5627621/NFAuthenticationKey_LinuxMac_t2.zip)

**Comment by kocicky** [comment]
ERROR: <urlopen error [Errno 61] Connection refused>
ERROR: 'ascii' codec can't decode byte 0xc3 in position 206: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 205: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 656: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 1106: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 1556: ordinal not in range(128) (repeated)
ERROR: 'ascii' codec can't decode byte 0xc3 in position 220: ordinal not in range(128) (repeated 6x)
ERROR: 'ascii' codec can't decode byte 0xc3 in position 674: ordinal not in range(128) (repeated)
Unable to connect with the browser

**Comment by kocicky** [comment]
Windows version works, thanks!

**Comment by CastagnaIT** [comment]
> Windows version works, thanks!

good to know!

shit of py2 unicode error ...
for mac can you try edit the file and change line 139?
from:
`print('ERROR: ' + exc.decode('latin-1'))`
to this:
`print('ERROR: ' + exc.encode('latin-1'))`
and try what happen?

**Comment by CastagnaIT** [comment]
please try this on Mac, last attempt:
[NFAuthenticationKey_linuxMac_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5629465/NFAuthenticationKey_linuxMac_t2.zip)

**Comment by kocicky** [comment]
ok, i tried to replace decode to encode in previous script:
RROR: 'ascii' codec can't decode byte 0xc3 in position 206: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc3 in position 635: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc3 in position 1064: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 205: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 656: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc4 in position 1106: ordinal not in range(128)

New script is very brief:
Establish connection with the browser... please wait
Unable to connect with the browser

**Comment by CastagnaIT** [comment]
mmh unfortunately i have no experience with the apple system to go deep in this,
another user have tested the script on MacOs with success here #910

errors aside seem the script is not able to create a socket communication with your browser

**Comment by CastagnaIT** [comment]
another user has found a problem in the script
this should work, can you confirm?
[NFAuthenticationKey_MacOS_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5643583/NFAuthenticationKey_MacOS_t3.zip)

**Comment by CastagnaIT** [comment]
updated: [NFAuthenticationKey_MacOS_t4.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5643882/NFAuthenticationKey_MacOS_t4.zip)

**Comment by kocicky** [comment]
Previous version [NFAuthenticationKey_MacOS_t3.zip] worked, new version was marked as malicious by Chrome. I downloaded it through Safari and it works as well.
Anyway, thanks for your help.

**Comment by CastagnaIT** [comment]
lately chrome has been working badly also marks malware some microsoft downloads... it is absurd
