### ISSUE TITLE
Netflix only shows Originals when a VPN is connected

### ISSUE THREAD

**Issue by GreenField0** [CastagnaIT/plugin.video.netflix#953]
#### Your Environment
- Netflix add-on version: 1.11.0
- Operating system version/name: LibreElec 9.2.6
- Device model:  Raspberry Pi 4 B (4 GB)

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

I've just installed LibreElec with this Addon as well as VPN Manager (NordVPN). I've set that VPN will be connected before Kodi starts. When I launch the Netflix Addon it shows a lot of content, but a lot seems to be missing, too. In my opinion, only Netflix Originals are shown.
When I open Netflix in a browser, on my TV or on my phone everything is is like it should be. I have no idea why some series are listed and some are completely gone (not only the newest season). When I connect NordVPN on my Windows laptop and open Netflix everything is like it should be. 
The search doesn't show the missing content either.  Disconnecting the VPN doesn't solve the issue. 

#### Expected behavior

The Netflix library should look like it does on every other platform. 

#### Actual behavior

Some series are missing in my Netflix library

#### Steps to reproduce the behavior

1. Connect a VPN or not
2. Launch Netflix, look for content
3.

### Debug log

The debug log can be found from this link: https://pastebin.com/0nZjkC4C

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
VPN is not an accepted topic with this addon:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy

**Comment by simonk83** [comment]
Can confirm, for example Star Trek: Discovery is just nowhere to be seen. I'm not using a VPN and it shows up on all other Netflix instances (phone, Shield native app etc etc).
