### ISSUE TITLE
Asked to login again

### ISSUE THREAD

**Issue by danielristic** [CastagnaIT/plugin.video.netflix#954]
#### Your Environment
- Netflix add-on version: 1.1.1.0
- Operating system version/name: Kodi 18.8
- Device model:  RPI 3B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe your help request
I am not sure if this is an issue with the plugin or with Netflix so that's why I did not post it in the "report a bug" section:

For me the login works with the authentication key method, but it asks me to login again pretty often. This does not happen every time I reboot the system but I got asked to login again multiple times in the one hour it took me to setup everything correctly.

What's expected here? Once successfully log in should stay this way for a long time like on other Netflix enabled devices? Or maybe it's Netflix that's not used to the device but once it's been active long enough this will no longer happen?

Thanks in advance.

**Comment by CastagnaIT** [comment]
I do not know what to tell you,
the current login system is not perfect and it is not possible to do it much better

**Comment by danielristic** [comment]
Thanks for your answer and for the great work,

I guess what I'm really asking here is if there is a way to have the plugin store the login information (password, authentication key and pin) so I don't have to literally type it in everytime it needs a new login (which I get is something that is from netflix's side and out of your control).

Best.
