### ISSUE TITLE
NFAuthenticationKey.py fails on slow connection (fix included)

### ISSUE THREAD

**Issue by kleag** [CastagnaIT/plugin.video.netflix#957]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: Raspbian
- Device model:  Raspberry Pi 400

Used Operating system:
* [ ] Linux
* [ ] Raspberry-Pi

### Describe the bug
The script NFAuthenticationKey.py was terminating with 'Possible wrong login or unexpected problem, please try again.'

#### Expected behavior
It should have generated the key file.

#### Actual behavior
It terminated with the message above.

#### Steps to reproduce the behavior
1. Use a very slow ADSL connection
2. Follow all instructions to generate the auth key

#### Possible fix
Change the sleep time at Line 91 to 10 seconds instead of 1:
        time.sleep(10)  # Give time to have the full html page

This way, it worked for me. Maybe a more clever retry loop would be better.

#### Other information
My ADSL is very slow (around 1 MBs. (switching to fiber in 1 week!)

**Comment by kleag** [comment]
There is no log available for this script. Only the error message I did paste in the bug description field.

**Comment by kleag** [comment]
> Please edit your Issue message to follow our [template](../raw/master/.github/ISSUE_TEMPLATE/bug_report.md). The issue will be closed after about one week has passed without satisfactory follow-up from your side.
> 
> If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.
There is no log available for this script. Only the error message I did paste in the bug description field.

**Comment by CastagnaIT** [comment]
Thank for the fix suggestion
but use wait and loop methods are the last resort solution to be used when there are no suitable tools,
so the better thing is use a [websocket DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) command to understand if the requested page in the browser is loaded

I did not spend time in studying how to add this thing any help will be appreciated
