### ISSUE TITLE
 Exception: build_media_tag: unable to find audio data

### ISSUE THREAD

**Issue by jrleek** [CastagnaIT/plugin.video.netflix#958]
#### Your Environment
- Netflix add-on version: 1.11.0
- Operating system version/name: Raspbian GNU/Linux 10 (buster) (kernel: Linux 5.4.72-v71+)
- Device model:  Raspberry Pi 4

Used Operating system:
* [X] Raspberry-Pi

### Describe the bug

An exception continually appears on the screen, every 2-5 minutes, while watching a video.  The exception is: 

Exception: build_media_tag: unable to find audio data with language: ja, channels: 2.0

The language in the exception changes depending on the audio language of the video being watched, in this case it's Japanese.  This exception occurs after changing between Netflix and a video with different language audio track. This might occur even when the two videos are both hosted in Netflix, but I'm not sure about that.  I reproduced it reliably when switching between Netflix and a locally hosted video with a different audio language track. 

#### Expected behavior

No exception occurs.  Or the Netflix add-on exits when Netflix is no longer being watched.

#### Actual behavior

Exception repeatedly appears until Kodi is exited.

#### Steps to reproduce the behavior

1. Start Netflix add-on.  Select a video that only has an English language track.  In this case I used an older American movie.
2. Pause the movie, and back out to the main menu.
3. Go to movies.  (The locally hosted ones, no add-on.)
4. Select a movie that has a foreign language track.  In this case it was an .mkv with a Japanese language track and English subtitles.
5. Watch for 5 minutes.  The Exception will occur.  
6. Clear the exception.  Wait a few minutes. The Exception will reoccur. 

#### Possible fix

Unsure.  Possible workaround would be a way to completely shutdown and restart the Netflix add-on.  Or just ignore exceptions about a video not having the requested audio track.  

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/ojiresalen.kodi

You can search for this line in the log to find the problem:
Exception: build_media_tag: unable to find audio data with language: ja, channels: 2.0

**Comment by CastagnaIT** [comment]
this will correct your error, 
[plugin.video.netflix_1.11.0_20201127_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5608434/plugin.video.netflix_1.11.0_20201127_t1.zip)

the steps to reproduce the problem are:
-Play a netflix video
-Pause the current video
-Return to Kodi home without Stop the video
-Play a non-netflix video, while the other is in the background

Unfortunately, every time this error appeared to you it has corrupted some data in the netflix addon database
then you will have to reinstall the fixed addon from scratch

let me know

**Comment by jrleek** [comment]
OK, thanks.  I installed your new version and it seems to have fixed the issue.  When backing out to the menu, I did get a "OSError" exception, with no further message.  If that issue persists I I'll file a different bug.

Thank you for fixing this for me.

I'm a little new to Kodi, so I also didn't realize I wasn't properly stopping the video. I assumed the video was stopped automatically when I exited the Add-On, or at least when I started a new video.  Thanks for the tip.

**Comment by CastagnaIT** [comment]
it is not a problem to play one video while another is still running in the background
but this addon requires some special features not always easy to integrate
so it can happen that not all variables done by the users are considered

if you can post a debug log with this OSError i would like to see if has something related to this fix
