### ISSUE TITLE
Addon causes instant crash of Kodi Matrix on Windows

### ISSUE THREAD

**Issue by n0valis** [CastagnaIT/plugin.video.netflix#960]
#### Your Environment
- Netflix add-on version: 1.11.0 matrix
- Operating system version/name: Windows 10

### Describe the bug
I have installed a fresh Kodi Matrix Beta, added CastagnaIT Repo for Matrix, added Netflix Addon, logged in with AuthKey, started a stream, Widevine installation was requested and successfully installed, stream didn't start but Kodi exited with crash. This is repeatable. The logfile always end with 'initalizing crypto session' 

Did I miss something? 

#### Steps to reproduce the behavior

1.As described above

### Debug log
[logfile](https://paste.kodi.tv/igibohexix.kodi)

**Comment by CastagnaIT** [comment]
Kodi crashes must be solved by the Kodi team not here
