### ISSUE TITLE
Auto select profile

### ISSUE THREAD

**Issue by manyacclau** [CastagnaIT/plugin.video.netflix#963]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model: Nvidia shield pro

Used Operating system:
* [x] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

Hello, is it possible somehow to auto select the profile instead of staying and select the one i want to use every time i start a movie ?  I have 2 profiles on my netflix account and every time i start a movie i have to select one of the profile. 

Thank you

**Comment by CastagnaIT** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#how-to-set-the-automatic-selection-of-a-profile
