### ISSUE TITLE
Videos wont play. Infinite loading spinner.

### ISSUE THREAD

**Issue by flos06** [CastagnaIT/plugin.video.netflix#964]
#### Your Environment
- Netflix add-on version: 1.11.0+matrix.1 
- Operating system version/name: LibreElec 9.80 nightly
- Device model:  Raspberry pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

I can login to Netflix fine, but as soon as I try to play a video it will show the loading spinner. Then very briefly the spinner dissappears only to return en spin infinitely. I have tried playing a multitude of different videos and all show the same behaviour. I've tried searching for help and have so far tried reinstalling widevide cdm and reinstalling everything. Also I have tried a multitude of different skins which all give me the same problem.

#### Expected behavior

The video should start and play.

#### Actual behavior

The video does not start. Instead a loading spinner will be there infinitely.

#### Steps to reproduce the behavior

1.   Open the netflix addon and select any video.
2.
3.

### Debug log

The debug log can be found from this link:

https://paste.kodi.tv/osuqipebad.kodi

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by BugDeliverer** [comment]
Bug can be reproduced:
- Raspberry Pi 3
- Libreelec 10 beta (any available, from 2020/11/28 to 2020/12/05)
   config.txt modifications:
   + mpg2 codec enabled
   + hifiberry-dacplus
- Netflix addon v1.11.0+matrix.1

**Comment by CastagnaIT** [comment]
I can't do anything here, your problem has to be solved by the CoreElec team
