### ISSUE TITLE
Kodi Stürzt ab sobald der hintergrund dienst startet

### ISSUE THREAD

**Issue by Bender2403** [CastagnaIT/plugin.video.netflix#965]
#### Your Environment
- Netflix add-on version:  1.11.0 
- Operating system version/name: Android 
- Device model:   Amazon Fire TV Stick 4k 

Used Operating system:
* [+ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Kodi crashes as soon as the background service starts

#### Expected behavior

The Kodi does not crash

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
https://www.dropbox.com/s/lavkd5twhsefmwc/kodi.log?dl=0

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
english only or will be closed

**Comment by Bender2403** [comment]
Ok sry my English is not very good I have used the Microsoft translator

**Comment by CastagnaIT** [comment]
only the Kodi team can handle kodi crashes not here

in any case your log is useless because
you have not followed the instructions specified in the readme

**Comment by CastagnaIT** [comment]
Due to your crash may be useful install this version with verbose debug already enabled by default:
[plugin.video.netflix_1.11.0_20201204_verbose.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5642844/plugin.video.netflix_1.11.0_20201204_verbose.zip)
but in any case you have to enable kodi debug

**Comment by Bender2403** [comment]
I did.

I uploaded files to log files for security reasons.

But let's offtopic a super addon continue like this.

https://www.dropbox.com/sh/tihw4h9i4vx834x/AACTy1W19NLqKkuiIpNmFbAaa?dl=0

**Comment by Bender2403** [comment]
I have installed the addon once on a naked kodi since it runs but as soon as I log in to my account (must use the method with key file) storms kodi off.

**Comment by CastagnaIT** [comment]
> ... 
> [plugin.video.netflix (0)] The debug logging level is set as "Disabled"
> ...

for some reason the netflix log verbose setting, still disabled in all your files
if you want that i can try to see something, before you have to enable it

PS. Try use https://www.deepl.com/translator instead of microsoft translator
