### ISSUE TITLE
Geoblock

### ISSUE THREAD

**Issue by byronwat2020** [CastagnaIT/plugin.video.netflix#969]
#### Your Environment
- Netflix add-on version: 1 11 0
- Operating system version/name: LibreELEC 9 2 6
- Device model:  RPi4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ x] Raspberry-Pi
* [ ] Windows

### Describe the bug
I live in Canada Content seems to be always from same region. Using a VPN that works on my pc and iPhone, was able to access content from France. Ex Star Trek but when I use VPN on the raspberry I have no access to Netflix content anymore. Other addons works so I have accès to Internet and VPN works. 

#### Expected behavior
Should be able to access France Netflix content when over VPN and France server 

#### Actual behavior
Only Canadian content showing but not accessible anymore 

#### Steps to reproduce the behavior

1.  zomboied repo + VPN manager addon 
2.ExpressVPN account 
3. Connect to France server
4. Open Netflix addon and see if content changed or accessible

### Debug log

The debug log can be found from this link:

#### Installation

zomboied repo + VPN manager addon 
2.ExpressVPN account 
3. Connect to France server
4. Open Netflix addon and see if content changed or accessible

**Comment by CastagnaIT** [comment]
VPN topic not allowed with this add-on:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/VPN-and-Proxy
