### ISSUE TITLE
Can not Play on CoreELEC 0.14.3

### ISSUE THREAD

**Issue by FotixChiang** [CastagnaIT/plugin.video.netflix#97]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used
0.14.3

### Description
login in successfully
get the playlist successfully
click any video and nothing happened.

### Steps to Reproduce

1. power on the CoreELEC
2. launch the Netflix addon
3. choose any video to play and nothing played.

**Expected behavior:** it should work

**Actual behavior:** no video played, no error messages displayed.

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

I am using the CoreELEC which is from LibreELEC and improved for Amlogic Soc.
My device is Amlogic S905D.

## Debug log
https://paste.kodi.tv/xadimifitu.kodi

## Other information

Proxy is on the router and works well for everything this time

**Comment by Smeulf** [comment]
There's a lot of network errors in your logs, like 'unresolved hostname' or 'error 420'.

This makes me think your proxy is the origin of your issue.

There's no specific error related to the add-on itself for what I can see.

**Comment by FotixChiang** [comment]
> There's a lot of network errors in your logs, like 'unresolved hostname' or 'error 420'.
> 
> This makes me think your proxy is the origin of your issue.
> 
> There's no specific error related to the add-on itself for what I can see.

THX for your help with the log reading. I correct the proxy as this is special period here. And now it just works!

But it comes out with smooth problem. It will take full CPU as it is just an arm soc.
Is there any way to take away some cpu pressure?
I just use the default settings. And local kodi video is always smooth 1080P.

**Comment by Smeulf** [comment]
You can always try to decrease the 'max resolution secure decoder' in InputStream Adaptative to a lower value, like 720p, or less.

That part is not hardware but software, so your device may not be fast enough to process 1080p.
