### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by eenbroleke** [CastagnaIT/plugin.video.netflix#98]
*I'm submitting a ...*
  - [ *] bug report

### Addon version used

0.14.1 and 0.14.3

### Description

I've been using version 1.41 to 1.4.3 without any issue for a few weeks, and, suddenly, I'm unable to display any show. Whatever the stream selected, the screen will remain black or it will not refresh itself to display the show (and it remains stucked at the selection page).

I haven't done any update (but I guess that automatic updates might have done something I'm not aware of). If I choose to manually select the resolution from the extension parameters, then I'm offered a list with very strange low resolutions.
When everything was working fine, I could stream at 720p without a hitch.

### Steps to Reproduce

1. select a show
2. play

**Expected behavior:** 
get the stream played :)

**Actual behavior:**
dark screen, but progress bar visible
sometimes audio works for a bit

## Context (Environment)
running on a GT King, thus S922X Amlogic soc, with Android 9.0, Kodi 18.2

### Installation
* [ *] I'm using this Netflix Repo

### Operating System
* [* ] Android

#### Additional informatin on the environment

Kodi 18.2 release on Android 9.0

## Debug log
https://paste.kodi.tv/sepirotako

Cheers !

**Comment by eenbroleke** [comment]
Just in case, some close issues referred to OMXPlayer that needs to be disabled from settings>player>video, but I cannot find any menu with OMX player name.

**Comment by Smeulf** [comment]
Please enable debug logging in Kodi and post your logs again so we can see something.

I'm not familiar with Kodi on Android, but I can see many errors related to codecs that might be related.

OMXPlayer issues are related to Raspberry Pi issues. It doesn't apply to you.

**Comment by eenbroleke** [comment]
Hi, do you mean that https://paste.kodi.tv/sepirotako is not verbose enough ?

**Comment by eenbroleke** [comment]
https://paste.kodi.tv/nokihedusu

**Comment by Smeulf** [comment]
Please enable debug logging.

As from the issue template:

- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue

**Comment by eenbroleke** [comment]
https://paste.kodi.tv/atowimabiz.kodi

with proper debug logging set.

**Comment by CastagnaIT** [comment]
if you haven't already tried, try this:
in expert settings:
>disable vp9 profile
>enable hevc profile

or else:
>disable vp9 profile
>disable hevc profile

I don't know the "true" potential of this chinese box😂😂
good luck

**Comment by eenbroleke** [comment]
Hi, already tried : it make absolutely no difference.

**Comment by eenbroleke** [comment]
What I do not get is why suddenly, the resolution made available through inputstream adaptive are so low. I used to watch at 720p, and now, nothing as such is made available (even if there is nothing displayed on the screen -p)

**Comment by eenbroleke** [comment]
linked to https://github.com/asciidisco/plugin.video.netflix/issues/155 (likely)

**Comment by Smeulf** [comment]
Thanks for the logs.

For what I can see, the error is not in the addon itself. It's in CDVDVideoCodecAndroidMediaCodec with is a Kodi internal module, and the error would be into InputStream...

You may try those commands for diagnostic, and post link. But I'm not specialist into Android so I may not be able to help you much: https://github.com/peak3d/inputstream.adaptive/issues/79#issuecomment-343477374

**Comment by Smeulf** [comment]
Also, I'd run some network tests to ensure I don't have any connections issues (lags, packets drops, etc), even if I'm not sure it's related.

Most probably, if you had any firmware upgrade, you can try to restore the previous one, I wouldn't be surprised it is the origin of the issue.

**Comment by CastagnaIT** [comment]
the ESN is autogenerated it must not be the same, this is not the problem
it is easier to have a software/firmware problem
I would not be surprised if that box has some corrupt or not really certified library
maybe extracting the logcat we can see what happen
some box can't even make the original netfix app to work

**Comment by eenbroleke** [comment]
https://paste.kodi.tv/ejavetucaj.kodi

it begins after line 769.

just for information, the tablet netflix app works on this box.
the netflix addon used to work too.

**Comment by Smeulf** [comment]
A lot of '_OpenDevice(1183): FATAL: Failed to open device, errno=No such file or directory' in that log, but that internal log is not clear enough to says what's going on :( Maybe a folder removed, or some permission change, can't tell sorry.

You still can try a factory reset of your device, but I can't guarantee it will solve the issue.

If someone else is more familiar with Android, your opinion is welcome.

**Comment by CastagnaIT** [comment]
neither do I have anything more to say, just this
ERROR: CDVDVideoCodecAndroidMediaCodec::AddData error(-10000)
seem there is a problem with mediacodec

you can try disable hardware acceleration by going here, if the settings allow it
![image](https://user-images.githubusercontent.com/3257156/59144218-c4d6e300-89d4-11e9-8c4c-f8a24dad1944.png)

**Comment by eenbroleke** [comment]
hi, yes, i've tried this.
if both mediacoder are disabled, then audio play for a while, but display remains black.

**Comment by CastagnaIT** [comment]
for my part i have no other solutions for you,
in any case it does not depend on this addon,
but on a lower level problem or of kodi or your firmware

**Comment by eenbroleke** [comment]
ok, thank you both for having looked at it.
