### ISSUE TITLE
Netflix watched status reporting stopped working

### ISSUE THREAD

**Issue by matejdro** [CastagnaIT/plugin.video.netflix#981]
#### Your Environment
- Netflix add-on version: 11.1.0
- Operating system version/name: Arch Linux, Kodi 18.9

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Expected behavior
Watched status should be synchronized with Netflix.

#### Actual behavior
When I start video playback, `Amvideoevents disabled due to exception: 
No lists with context continueWatching available` error will be displayed and watched status will not be synced to Netflix servers

#### Steps to reproduce the behavior

1. Enable "Synchronized the watched status with Netflix" option
2. Watch a show

### Debug log
The debug log can be found from this link:  [kodi2.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/5678258/kodi2.txt)

#### Installation
* [X] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

![image](https://user-images.githubusercontent.com/507922/101885785-e05b1500-3b9a-11eb-8e6e-b51da205b4a5.png)

**Comment by CastagnaIT** [comment]
this can happen if your profile not have a Continue watching list,
you can temporary fix by play some minutes of a video from website or mobile
in this way will be created the continue watching list in the selected profile
then after reboot the addon (or kodi) the problem disappears

**Comment by matejdro** [comment]
Thanks, it works!

Let me turn that issue into a feature request: Any chance you can display better error message (essentially tell in the error message what you just told me)? That way anyone in the future can fix their problem without going to the github.

**Comment by CastagnaIT** [comment]
fortunately this message can be removed without side effects
