### ISSUE TITLE
Any Videos don't start.

### ISSUE THREAD

**Issue by JinJin-o** [CastagnaIT/plugin.video.netflix#985]
#### Your Environment
- Netflix add-on version: 
  LATEST 1.12.0
- Operating system version/name: 
  Coreelec 9.2.5
- Device model:  
 Odroid C4 / Odroid N2 either

Used Operating system:
* [ ] Android
* [ ] iOS
* [V] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Any Videos don't start
Odroid C4 / N2 same

#### Expected behavior

netflix video show itself

#### Actual behavior

Any Videos don't start

#### Steps to reproduce the behavior

1.installed Netflix addon with CastagnaIT repo.
2.logged in with keyfile
3.after that installed widevine when popup came out
4. I choose vedeos It happen nothing. loding icon rotated and nothing.

#### Possible fix

I have no idea. i checked inputstream adaptive / helper addons. I have reinstalled with helper addon

### Debug log

The debug log can be found from this link:

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by rradar** [comment]
@JinJin-o can you please attach a debug log? Could be related to #986
