### ISSUE TITLE
Movies does not start

### ISSUE THREAD

**Issue by bogdanszmyd** [CastagnaIT/plugin.video.netflix#988]
#### Your Environment
- Netflix add-on 1.12.0
- Operating system LibreELEC 9.2.6, Kodi 18.9 (2020-10-25)
- Device model:  Raspberry Pi 3 B+

Used Operating system:
- Linux kernel 4.19.127

### Describe the bug

Addonn is installing corectly, logging to account and downloading and installing cdm. But whene I try start some movie, it is turning off after about 1 sec.

#### Expected behavior

The movie should start

#### Actual behavior

Addonn is installing corectly, logging to account and downloading and installing cdm. But whene I try start some movie, it is turning off after about 1 sec.

#### Steps to reproduce the behavior

1. Install addon
2. Login to Netflix account
3. Try start any movie

### Debug log

The debug log can be found from this link:
https://paste.kodi.tv/ibilawowar.kodi

#### Installation

https://zips.ovh/castagnait

**Comment by mathieu2em** [comment]
same problem here

**Comment by CastagnaIT** [comment]
`
2020-12-14 19:58:37.352 T:1329570688   ERROR: [script.module.inputstreamhelper] [u'ldd', u'/storage/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2020-12-14 19:58:37.353 T:1329570688   DEBUG: [script.module.inputstreamhelper] [u'ldd', u'/storage/.kodi/cdm/libwidevinecdm.so'] cmd output:
                                            $	not a dynamic executable
2020-12-14 19:58:37.353 T:1329570688   ERROR: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
`

this is a inputstreamhelper problem not netflix add-on problem
you have to open an Issue thread in **Input stream helper addon** to get a solution

**Comment by zjoasan** [comment]
https://github.com/xbmc/repo-scripts/pull/1780

**Comment by CastagnaIT** [comment]
Thanks @zjoasan the new inputstreamhelper version solve this problem
you will have to wait for it to be released

**Comment by Leepic** [comment]
With InputStreamHelper 0.5.2 from Kodi Repo and after reinstalling WideVineCDM (rollback doesn't work because I've Kodi 18.2 installed from scratch) via _Add-On_ > _InputStream Helper_ > _Configure_ > _Reinstall WideVineCDM_.
Netflix is now working again!
PS: @CastagnaIT thanks for your work and your time on Netflix add-on :).

For information:

- Before

```
$ ldd /home/kodi/.kodi/cdm/libwidevinecdm.so 
	not a dynamic executable
```

```
$ sha1sum /home/kodi/.kodi/cdm/libwidevinecdm.so 
0a282d15691c6e88bbb546566965364a7eceee94  /home/kodi/.kodi/cdm/libwidevinecdm.so
```

```
$ cat /mnt/borg-archive/home/kodi/.kodi/cdm/config.json 

{"sku": "", "sha1": "919f200c3a9a50db976c33a48692e889a93c3918", "name": "Haier Chromebook 11", "photourl": "", "url": "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13020.87.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin.zip", "hwid": "JAQ", "hwids": [], "zipfilesize": 612761304, "version": "13020.87.0", "filesize": 2321571840, "file": "chromeos_13020.87.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin", "md5": "8271fe1cdee1229046154a62c474c8da", "hwidmatch": "^JAQ \\w{3}-\\w{3}-\\w{3}-A\\w{2}(-\\w{3})*$", "desc": "", "model": "Haier Chromebook 11", "channel": "stable-channel", "manufacturer": "Haier WL"}
```

kodi.log:

```
2020-12-16 23:29:45.230 T:1549791968   ERROR: [script.module.inputstreamhelper] [u'ldd', u'/home/kodi/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2020-12-16 23:29:45.230 T:1549791968   ERROR: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
2020-12-16 23:29:45.592 T:1766621920   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/kodi/.kodi/cdm/libwidevinecdm.so)
2020-12-16 23:29:45.592 T:1766621920   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
2020-12-16 23:29:45.593 T:1766621920   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80025678/season/80025812/episode/80025761/?profile_guid=KJJBUU3HXBFORJVDM6HBPIVOGE]
```


- After

```
$ ldd /home/kodi/.kodi/cdm/libwidevinecdm.so
	linux-vdso.so.1 (0x7eea1000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76771000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76748000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x766c9000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x766b6000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x7669f000)
	libnss3.so => /usr/lib/arm-linux-gnueabihf/libnss3.so (0x76588000)
	libnssutil3.so => /usr/lib/arm-linux-gnueabihf/libnssutil3.so (0x76557000)
	libnspr4.so => /usr/lib/arm-linux-gnueabihf/libnspr4.so (0x76516000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x763d7000)
	/lib/ld-linux-armhf.so.3 (0x76ed0000)
	libplc4.so => /usr/lib/arm-linux-gnueabihf/libplc4.so (0x763c3000)
	libplds4.so => /usr/lib/arm-linux-gnueabihf/libplds4.so (0x763b0000)
```

```
$ sha1sum /home/kodi/.kodi/cdm/libwidevinecdm.so 
d5ee489d5c409ff6cb423f318a23dba71ff2f2b0  /home/kodi/.kodi/cdm/libwidevinecdm.so
```

```
$ cat /home/kodi/.kodi/cdm/config.json 
{"sku": "", "sha1": "52d5c55459650fcab4e57e408bfacd76859998bc", "name": "AOpen Chromebox Mini", "photourl": "", "url": "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13505.63.0_veyron-fievel_recovery_stable-channel_fievel-mp.bin.zip", "hwid": "FIEVEL", "hwids": [], "zipfilesize": 1032350355, "version": "13505.63.0", "filesize": 2320468480, "file": "chromeos_13505.63.0_veyron-fievel_recovery_stable-channel_fievel-mp.bin", "md5": "be9fa742e613dff23d8a1484b31ef753", "hwidmatch": "^FIEVEL .*", "desc": "", "model": "AOpen Chromebox Mini", "channel": "stable-channel", "manufacturer": "AOpen"}
```

**Comment by rradar** [comment]
> With **InputStreamHelper 0.5.2** from Kodi Repo **and after reinstalling WideVineCDM** (rollback doesn't work because I've Kodi 18.2 installed from scratch) via **Add-On > InputStream Helper > Configure > Reinstall WideVineCDM**.
Netflix is now working again!

Perfect @Leepic :+1: Now it works :tada:

**Comment by bogdanszmyd** [comment]
It works. Thanks @Leepic .

**Comment by CastagnaIT** [comment]
InputStreamHelper 0.5.2 is released i close the Issue

**Comment by Gironimoon** [comment]
Hello, i got the same issue with:
Netflix addon:1.12.4
on: LibreElec 9.2.6
on a: Raspberry Pi 3B 1.2

Im using:
InputStreamHelper 0.5.2
and already reinstalled WideVineCDM

But the videos still wont start.

**Comment by topquark73** [comment]
I got the same issue with:
Netflix addon:1.12.4
on: LibreElec 9.2.6
on a: Raspberry Pi3

**Comment by darekmeco** [comment]
Now not works on raspberry pi 3,
