### ISSUE TITLE
Cannot load native module 'Cryptodome.Hash.-BLAKE2s' on LibreElec 2.9.6

### ISSUE THREAD

**Issue by Jick9536** [CastagnaIT/plugin.video.netflix#989]
#### Your Environment
- Netflix add-on version: v1.12.0
- Operating system version/name: LibreElec 9.2.6.
- Device model:  Rapberry pi 3 model B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

Cannot load native module 'Cryptodome.Hash.-BLAKE2s'
#### Expected behavior

Suppose to load service bellow and now doesn't and you do not have acces to Netflix's content.

#### Actual behavior

Does not haver acess to netflix content. 

#### Steps to reproduce the behavior

1. Update version 12.0
2. Launch addon
3. Message displayed. Cannot load native mdule 'Cryptodome.Hash.-BLAKE2s'

#### Possible fix

Downgrading to version 1.9.0

### Debug log

The debug log can be found from this link:

https://pastebin.pl/view/e518320d

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots

 
![image](https://user-images.githubusercontent.com/8208253/102275363-91f4a000-3f25-11eb-9323-eed87c8bb611.png)

**Comment by CastagnaIT** [comment]
the problem is in your python module installed
you can try follow addon how to install wiki
or ask in forums
