### ISSUE TITLE
Subtitles not showing

### ISSUE THREAD

**Issue by smvueno** [CastagnaIT/plugin.video.netflix#99]
*I'm submitting a ...*
  - [ x ] bug report
  - [ ] feature request
  - [ x ] support request

## General information
Running OSMC latest Kodi 18
On a Raspberry 3

### Addon version used
plugin.video.netflix-0.14.3

### Description

I'm currently using the Japanese version of Netflix,
Subtitles are not showing at all but the sound can be changed normally.
Any ideas for how to make the subtitles show?

### Steps to Reproduce

1. Start a movie
2. Choose subtitle

**Expected behavior:** [What you expected to happen]
Subtitle to show.
**Actual behavior:** [What actually happened]
No subtitles showing.
### Installation

Installed directly 
* [ x ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log
 https://paste.kodi.tv/egepesonul.kodi

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Smeulf** [comment]
Hi. That's 'funny' because the subtitles streams are present, and seems enabled. No error in the log either.

Maybe you can try to switch 'disable WebVTT subtitles' on or off, depending on your current config, in the expert section of the add-on configuration?

**Comment by smvueno** [comment]
That's really confusing, indeed.
Yeah couldn't see any error regarding it either. I tried to disable, enable WebVTT without any success.

Thank you, will try again when I'm back home.

**Comment by CastagnaIT** [comment]
please provide some titles of movies or tvshows

**Comment by smvueno** [comment]
I was able to fix it. The problem was a bad update from older version of OSMC.
Somehow after the update, the subtitle line was outside the screen.
Moved it back in view again and now it is visible.

Sorry for the trouble, and thanks for the help... 😅
