### ISSUE TITLE
[K18][Upnext][Profile] It is not possible select profile while a video is playing

### ISSUE THREAD

**Issue by notoco** [CastagnaIT/plugin.video.netflix#991]
#### Your Environment
- Netflix add-on version: 1.12
- Operating system version/name: Coreelec 9.2.5, Ubuntu 20.10

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
When using the library and the UpNext add-on, the next episode is not played - the message "It is not possible select profile while a video is playing" appears, Of course, the profile for autoplay from the library is selected. 
I know that the problem applies to K18, but I suspect that it also appears on K19, I have no way to check on K19 yet

#### Expected behavior

Restore old functionality before this commit (i think so)
https://github.com/CastagnaIT/plugin.video.netflix/commit/4a680f537c3a4e63814c16be00a0b0b95853425a#diff-51c976c323dd080dd2390b18a219a0eecfb040a90c0ff2a0b222aa3d0b5a3077
#### Actual behavior
Unable to use UpNext add-on

#### Steps to reproduce the behavior
1. Use two netflix profiles on one account
2. Play TvShow from library
3. Scroll to end, UpNext windows appears.
4. Erro..

### Debug log
The debug log can be found from this link:
http://ix.io/2Iou

### Additional context or screenshots (if appropriate)
![screenshot000](https://user-images.githubusercontent.com/36659110/102464210-5dc7cf00-404c-11eb-98cf-78d44a924a8f.png)

**Comment by CastagnaIT** [comment]
Thanks fixed
in any case it will be necessary to select the same profile used for the video currently playing

**Comment by notoco** [comment]
So the message will be shown even if the options are set to select a given profile for library playback?
This makes it difficult for younger users to use ...

**Comment by CastagnaIT** [comment]
> So the message will be shown even if the options are set to select a given profile for library playback?

not understand
try the change by download the daily build

**Comment by notoco** [comment]
It's probably going to be a never-ending story - as Netflix corrected is another bug on UpNext. I am slowly giving up - for several versions I have been unable to force Netflix and UpNext to cooperate on the library.
http://ix.io/2J9Y

**Comment by CastagnaIT** [comment]
i am sorry for these annoyances but
for my part i am not able to develop and execute every kind of test case for each specific functionality some oversight can happen

usually for a developer should be supported by a tester but currently i have to do both parts
therefore my "testers" become the end users and then i await possible error reports

**Comment by notoco** [comment]
I didn't want to offend you, I know how hard your work is and I wish I could help more. The plug is perfect, always at a high level, apparently just in my setup those two plugs  don't want to work together

**Comment by CastagnaIT** [comment]
i have noticed that the STRM path is in a `nfs` address
it is the first time that you export STRM files on a nfs address?
this problem happen also to the others exported STRM (of another tvshow)?

From your log http://ix.io/2K5v
is possible to see that the STRM path saved in the DB is missing actually do not know the cause

`2020-12-28 12:58:09.938 T:139860677473856   DEBUG: [plugin.video.netflix (0)] file_path from DB: None`

try open NF addon and on the current tvshow, then open context menu and select "Update inside library"
then try to see if the problem still persists

**Comment by notoco** [comment]
OMG... 
A man is sometimes so stupid that his head hurts... From the beginning:
I've been using NFS for several months, before I started using it I did a clean installation of the codi, re-created the library, added all series and movies from Netflix to the library. Most often I add from the box with coreelec. Previous tests I did on my laptop - where I have only the codi database connected - I have no Netflix database connected. 
For coreelec I had a version on which there was a previous playback error all the time. And now - the playback of the next episode works without any problem - but on coreelec. I suspect that setting a common base for Netflix on the computer and on coreelec will solve the problem...
With this version you gave for testing everything works as it used to... I will check if shared library will solve the problem on all connected machines :)  Do I have to import it somehow after enabling the shared library option (mysql database is on a different machine)

**Comment by notoco** [comment]
Ok - I'm doing Perform full sync just in case

**Comment by CastagnaIT** [comment]
what i wonder is how you managed to get a database without exported STRM paths
i do not understand how this can be done

**Comment by CastagnaIT** [comment]
so, if i understand, you have mixed the exported strm files of more devices?

**Comment by notoco** [comment]
Yes. Most often I added via coreelec, but sometimes I also added from the laptop and this is where an error occurred. On the laptop I played the series that I imported to the coreelec library.

**Comment by notoco** [comment]
Now, after full synchronization, it works on 3 randomly selected series. I also created a shared library in the Netflix plugin

**Comment by CastagnaIT** [comment]
i noticed that in addition to UpNext this broken also the STRM resume workaround for the same problem
i will try manage better this particularity, surely other users will mess up
however now it will be fine if you have configured everything well

**Comment by notoco** [comment]
I did a full sync on the main device. I set the same base in the other devices (in the Netflix plug). I will check, but for now it works on the main device. Sorry for confusion

**Comment by notoco** [comment]
BTW, thanks for the Wiki update. Maybe it will be useful to others.

**Comment by notoco** [comment]
Ok - tests done, on 2 separate systems (laptop with Ubuntu and with from Windows - connected to shared library on server, managed by kodi with coreelec). Randomly selected 4 series. Everything works.

**Comment by CastagnaIT** [comment]
thanks for the report
