### ISSUE TITLE
No Subtitles in all streams

### ISSUE THREAD

**Issue by supperka** [CastagnaIT/plugin.video.netflix#993]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

![MVIMG_20201221_004431](https://user-images.githubusercontent.com/3536196/102727505-4f1c3900-4326-11eb-8a0b-f8c45213a504.jpg)
Kodi log
Https://paste.kodi.tv/ayunodufiz

Problem:
i can't load ani subtitles , how on screen showing none.
It's happening on all my boxes or android phone . Problem  start 3 days ago.
in  android netflix apk, I can see Subtitles but not in your add-on.
Thanks for your help

**Comment by CastagnaIT** [comment]
try reinstall widevine
Add-On > InputStream Helper > Configure > Reinstall WideVineCDM

**Comment by CastagnaIT** [comment]
If not work
you have to follow **in right way** the instruction in the readme to get a good log file, the provided one is without debug info

Then after playing a video
provide also these two files contained in kodi user folder ...\userdata\addon_data\plugin.video.netflix\
manifest.json
manifest.mpd

**Comment by supperka** [comment]
I tried Reinstall WideVineCDM.
![MVIMG_20201222_160422](https://user-images.githubusercontent.com/3536196/102902913-e2ad5100-446f-11eb-86d1-0d29d3d24d0c.jpg)


this is new log.
Https://paste.kodi.tv/agilelitav

There is the files
[plugin.video.netflix.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5730578/plugin.video.netflix.zip)

**Comment by CastagnaIT** [comment]
The files sent, they say that the addon receive the subtitles and send in right way the subtitles,
then the problem not come from the netflix addon but from something in your Kodi that not works

The log sent has no info as the first one, you have not follow the instructions steps explained in the readme

**Comment by supperka** [comment]
You're right!! I tried , fresh install of coreelec and netflix ,and all working ! So I dig in and found problém was in adaptive stream input settings.
So thank you !! For your time .

**Comment by CastagnaIT** [comment]
you can say what setting was wrong?

**Comment by supperka** [comment]
> you can say what setting was wrong?

![iMarkup_20201223_183151](https://user-images.githubusercontent.com/3536196/103022983-54a79800-454d-11eb-9046-552d8696063b.jpg)
This settings makes issue ,if I changed, subtitles disappears
