### ISSUE TITLE
Several Titles not showing

### ISSUE THREAD

**Issue by Sc0r** [CastagnaIT/plugin.video.netflix#998]
## Bug report
On the PC Browser and Smart TV Netflix app, I can see the following TV shows in my "continue watching"
Star Trek Discovery
Jojo's Bizarre Adventure
Alien Worlds
Carmen Sandiego
Carmen Sandiego - To steal or not to Steal

Checking the same section in the addon, I could only find one:
Carmen Sandiego - To steal or not to Steal
After marking this one as read(as I didnt plan on continue watching it) the list is now entirely empty on Kodi. 
Searching for "Star Trek" in the Add-On's search function, I find 3 Shows/Movies of Star trek, but not Discovery.

#### Your Environment
- Netflix add-on version: 1.12.0
- Operating system version/name: Raspbian GNU/Linux 10 (buster) (kernel: Linux 5.3.79-v7l+)
- Device model:  Raspberry Pi 4 Model B (4Gig RAM)

Used Operating system:
* [x] Raspberry-Pi

#### Expected behavior

1. 'Currently Watching' Netflix list listing several shows
2. Star Trek Discovery being available to watch 

#### Actual behavior

1. 'Currently Watching' list empty 
2. Star Trek Discovery not listed nor discoverable in the addon's search function

#### Steps to reproduce the behavior

1. Install Kodi 18.7, install dependencies and Netflix Addon V1.12 through the repo
2. log into user profile
3. try to find star trek discovery

### Debug log

The debug log can be found from this link:
https://www.pixelherold.de/kodi.log

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by Sc0r** [comment]
OK just realised it DID find them, but marked them all as watched- even the Episodes I didn't watch yet. 
Did I cause this somehow?

**Comment by CastagnaIT** [comment]
when a tvshow is marked means that you started to watch some episodes
netflix does not provide any data to define a fully watched or partially watched tvshow

**Comment by Sc0r** [comment]
hm yea odd. 
Must be with the view of the kodi skin then, I can only see watched/unwatched/all and if I've seen one, since netflix creates subfolders for each season, these are marked as 'watched' as soon as I've seen a single episode of that season. 
Maybe there is a way to list all episodes of all seasons under the show, but thats more of a skin, not a plugin issue I guess.
thanks for the response and yes, that link is interesting, thanks!!
